### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ArtiXim** [Lunat1q/Catchem-PoGo#1]
I just wanted to say that your Catchem project is incredible! Thank You for the effort.

Some small suggestions:
- [x] Ability to sort Pokemon by #
- [x] Ability to discard items in Information
- [ ] Ability to set Pokemon specific config via right click in Information (Don't Catch / Keep CP or IV / etc)

**Comment by userwau** [comment]
- Also sort by CP & IV Levels.
- Add player level in bot window (next to accountname)

**Comment by Lunat1q** [comment]
Level... ok, thanks possible, about sorting - didn't get it.

**Comment by kevin01523** [comment]
maybe he meant pokedex number or order.

**Comment by Lunat1q** [comment]
3rd task will be implemented under Pokemon lists settings tab in the next updates
