### ISSUE TITLE
what file runs the program?

### ISSUE THREAD

**Issue by HaZeModsII** [Lunat1q/Catchem-PoGo#10]
i am totally new and have no idea what im doing so can someone help me

**Comment by Joesilvpb4** [comment]
Im having the same problem, there is no exe or application file...

**Comment by HaZeModsII** [comment]
im on windows 7 what about you

**Comment by Joesilvpb4** [comment]
windows 10.  Please post if you find a solution, I will do the same

**Comment by HaZeModsII** [comment]
okay

**Comment by Lunat1q** [comment]
Catchem.exe, download release file.

**Comment by HaZeModsII** [comment]
where do i download it?

**Comment by Joesilvpb4** [comment]
Cannot seem to find it either

**Comment by Joesilvpb4** [comment]
Doesn't seem to exist, is there a chance it was accidently pulled out

**Comment by Lunat1q** [comment]
https://github.com/Lunat1q/Catchem-PoGo/releases
