### ISSUE TITLE
translation.th

### ISSUE THREAD

**Issue by monsterinkbless** [Lunat1q/Catchem-PoGo#1000]
Please change this code in the next update. ( in translation.th )

**(From)**
{
      "Key": "eventFortUsed",
      "Value": "ค่าประสบการณ์: {0}, อัญมณี: {1}, ไอเทม: {2}"
    },

**(To)**

{
      "Key": "eventFortUsed",
      "Value": "ชื่อ : {0}, ค่าประสบการณ์: {1}, อัญมณี: {2}, ไอเทม: {3}"
    },

**(Thank you.)**

**Comment by Lunat1q** [comment]
do PR
