### ISSUE TITLE
can u add a label to the waypoints on the custom routes

### ISSUE THREAD

**Issue by kertiek** [Lunat1q/Catchem-PoGo#1001]
can u add a label to the waypoints on the custom routes, to know the order  "icon-waypoint 1" ,  "icon-waypoint 2" , "icon-waypoint 3"  and so ... so u know where to put  the next waypoint?

for example ... it would help to have a visual number next to the icon of whaypoints, to know wich one was the previous waypoint when doing a route in a park not too big.

pd: sorry for the bad english.

**Comment by Lunat1q** [comment]
sure. added.
