### ISSUE TITLE
Somehow to use item from inventory

### ISSUE THREAD

**Issue by acidwae** [Lunat1q/Catchem-PoGo#1003]
First, thanks for this awesome bot, first class job. Grats.

After using your bot for some days, i`m missing a way to use Incense or LuckyEgg whenever i want it.

Is there any chance to able these option to us?

**Comment by fabntic** [comment]
Yes setting...
A=amount of pokeball + potions + revives +berries 
B=recycle at usage percentage X 350 items in bag. 
A should be << than B
Example 
100+40+20+50=210 A
0,85x350=297 B
The difference is enough B-A= 87 item before next recycling.
Refer to #812 solution...
Maybe you make a changes in delay in checking the inventory
