### ISSUE TITLE
[Minor Bug] Poke Markers will not clear on manual route.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1008]
Dear Support,

Im using manual route, Keep Poke Markers is already uncheck
But will not be clear in the map.

v1.4.9.0

Keep up the good work.

**Comment by Lunat1q** [comment]
works just fine http://i.imgur.com/ivv5BlN.gifv

**Comment by alanearl** [comment]
Yeah closing the application & running again just solve the problems.
Well thanks anyways.
