### ISSUE TITLE
No proper route loaded

### ISSUE THREAD

**Issue by CZJohny** [Lunat1q/Catchem-PoGo#1009]
After last update (1.4.9.1) my routes stopped working - generates ok with Google also with Valhalla, but bot does not start to walk. Any idea?

**Comment by devgraal** [comment]
Is route route properly selected in your settings ? (maybe stupid question, but better ask :p)

**Comment by HernestoSanchez** [comment]
When i got this error, i just generate the route again and voilà, it works.

**Comment by B1gM1k3** [comment]
Same to me. Have to rebuild the route after closing the bot.

**Comment by magicdev2** [comment]
I got that error what i did is erase the whole bot and reinstall it and it started to work again

**Comment by CZJohny** [comment]
Hi, I've generated it twice - via Google and via Valhalla, route shows fine but bot on both failed. Any suggestions?

**Comment by zeldaleonz** [comment]
Route that build last time and saved, cant be use anymore when we closed the bot.  Please make it generated file like profile. So it can make more easy setup if there is a new version.

This Very great project and thanks you too for four hard work sir

**Comment by CZJohny** [comment]
@zeldaleonz You are right, problem is only with saved routes via older versions. Solution is - open saved routes, build them and save with other name. Old ones delete. This solution works for me.
