### ISSUE TITLE
Character is too busy

### ISSUE THREAD

**Issue by Krabert4444** [Lunat1q/Catchem-PoGo#1010]
i just set a marker so my character should walk from a to b, i always get the Attention message "character is too busy" bus my chracter does nothing, he spot a pokemon, character is too busy.
not sure what im doing wrong.

i can upload my settings if needed.

Thanks in advance :)

**Comment by Lunat1q** [comment]
that can happend only when u trying to do something from UI.

**Comment by Cryptologism** [comment]
Yeah it happen to me too when im trying to test giving too much works... Too busy when character was transferring or evolving.. too many task in one time... cmon.. give chracter a break for moment... ^-^

**Comment by Krabert4444** [comment]
is there a way to prevent this?
i tried it again and i wanted to transer 1 pokemon, then a wild pokemon appears on the map, my character does nothing (too busy) the pokemon dissapeared and the transer also didnt worked so i had to restard the transfer. so what my character did in the mean time?

**Comment by B1gM1k3** [comment]
It happens to me when i transfer some pokemons (4 or more in a row). I have to restart the bot.

**Comment by magicdev2** [comment]
just don't overload it plus remember it's trying to act like a "human" not a bot.

**Comment by alanearl** [comment]
Ryunosuke Huhuhu...

**Comment by tenderbeyr** [comment]
i think it still reading the path you made, so dont give it any commands yet.
i transfer pokemons when its moving, or far from pokestop, or after a catch, or far from respawn point (memorize the respawn point to where you want to farm).
