### ISSUE TITLE
transferring wrong Pokémon

### ISSUE THREAD

**Issue by meganovato** [Lunat1q/Catchem-PoGo#1012]
Hello Luna1q .

I would like to make a comment about this version of Catchem . He is transferring the Pokemons I marked for saving to evolve if you can fix this in the next version I thank

Marked the "Keep poke que can evolve" option. Despite this marked and the filter selected the Pokemons that want to evolve, it tranfere the Pokemons

**Comment by Lunat1q** [comment]
marked with what?

**Comment by mucro9** [comment]
Yes cause of transfer issue i closed the bot its transferred my fovorite pokemon i see my own eyes

**Comment by petoe93** [comment]
i think he marked them as favorite and the bot crushed it to candy eitherway..
no problem with that for me tho..
but it is indeed a bug that even favorited Pokemon can be sent away if you accidently slip from evolve down to transfer ^^

**Comment by meganovato** [comment]
Marked the "Keep poke que can evolve" option. Despite this marked and the filter selected the Pokemons that want to evolve, it tranfere the Pokemons

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/W5lg2SZ.png) favoured pokemons can't be transfered by automatic system.

**Comment by goiabs** [comment]
This "pokemonList" is the list of the pokemon that will be transfered?
