### ISSUE TITLE
How did you calculate stats?

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1014]
Hi Guys,

Anyone know how did stats attack def stamina was being calculated?

Thanks.

**Comment by Lunat1q** [comment]
It's base pokemon stats

**Comment by alanearl** [comment]
So did you mean that is site is a fake?

https://pogobag.me

**Comment by devgraal** [comment]
I cannot tell if this site is a fake or, but I can tell this one wasnt few days ago:

**Comment by Lunat1q** [comment]
that site will just steal your account data :) that's all
