### ISSUE TITLE
[Small Change] Change location of TRANSFER and EVOLVE

### ISSUE THREAD

**Issue by ArchangelBr** [Lunat1q/Catchem-PoGo#1016]
Hi All!

@Lunat1q Could you change the order of this options on Pokemon's List ?

http://prntscr.com/cc7rdo

Thats the 3rd time I evolve one pokemon by mistake while I'm transfering my pokemons...

Could be Evolve at last position, for example.

**Comment by Lunat1q** [comment]
done

**Comment by Cryptologism** [comment]
huhuhu looks like you were in hurry...  xD
