### ISSUE TITLE
【Suggestion】Make a funciton that could change "throw miss rate" 

### ISSUE THREAD

**Issue by pogoaccount** [Lunat1q/Catchem-PoGo#102]
Because of the Nianic soft ban, if the throwing is always good, the account may be banned to catch pockmon. I know you have the throw accuracy adjust, but I got catch banned a couple of times when the throw accuracy is below 0.5. So I afraid the throw accuracy does not really work. Hope you start the "throw miss rate" which may better solve the catch bann.
Appreciate！

**Comment by Bay101** [comment]
This feature is already implemented as Humanize throws, along with the throw accuracy settings below it.
