### ISSUE TITLE
IV problems and balls

### ISSUE THREAD

**Issue by manuwar9** [Lunat1q/Catchem-PoGo#1021]
I put the value IV high, but the bot does not listen , and masterball spent and ultraball with pokemons of low IV

http://thumbs.subefotos.com/08453492a8e85adaf37cb3cd1c32f939o.jpg

http://thumbs.subefotos.com/cfb7583823ff052a2177d054d8cc7260o.jpg

**Comment by Lunat1q** [comment]
do a proper screenshot.

**Comment by manuwar9** [comment]
https://postimg.org/image/txb0obmer/

https://postimg.org/image/txb0obmer/

**Comment by Lunat1q** [comment]
it was low prob -> that's why it used UltraBall

**Comment by manuwar9** [comment]
okk,thanks
