### ISSUE TITLE
[Telegram] / Sugestion

### ISSUE THREAD

**Issue by Pauloozzy** [Lunat1q/Catchem-PoGo#1024]
I already do and do again the tutorial but not work, don't send ANY mensage to me, someone can help me?

And about e-mail sending of found a especific pokemon? or play a sound and stop walk?
for exemple, i made my route aroud my street, if the bot found something good, play a sound and stop walk or send me a e-mail, then i go to the street and catch on my main account.

**Comment by kingsley7601** [comment]
you can auto complete tutorial

**Comment by Pauloozzy** [comment]
the tutorial already exist, but not work to me

**Comment by Cryptologism** [comment]
Ermmm are you already tried that... Cuz never meet this error before...

**Comment by xPokemasterx** [comment]
i got same fault as Pauloozzy.. nothing works with Telegram.. 

bot receives commands but dont reply anything

**Comment by Bay101** [comment]
Telegram 100% works, @Pauloozzy. You can check the check box and select pokemon here to get messages when you find a certain pokemon. http://i.imgur.com/cPqMSaL.png

**Comment by Pauloozzy** [comment]
my configs are corret, but no one msg on my Telegram.
![image](https://cloud.githubusercontent.com/assets/20846454/18126190/6e4e58b6-6f50-11e6-8d7d-d36820fc1167.png)

It may be blocked my internet provider?
