### ISSUE TITLE
Why cant you rent a domain

### ISSUE THREAD

**Issue by minimacz** [Lunat1q/Catchem-PoGo#1025]
why can u rent a domain

**Comment by kingsley7601** [comment]
or buy one
domainname.com
godaddy.com

**Comment by minimacz** [comment]
the owner said he couldn't rent one for legal reasons

**Comment by kingsley7601** [comment]
you answered your own question

**Comment by minimacz** [comment]
but what are the legal reasons

**Comment by magicdev2** [comment]
Well thats a dumb question to ask...

**Comment by magicdev2** [comment]
because this is a pokemon bot clue word "Bot" and it not legal

**Comment by Cryptologism** [comment]
Huhuhuhu
Mybe some of them thinking that botting was allowed

**Comment by minimacz** [comment]
As long as you don't display that fact that's it's a Pokemon go but only use imagery I pretty sure that's allowed

**Comment by magicdev2** [comment]
if you dont display it a bot how would you know about it then? it could be a scam or something.

**Comment by magicdev2** [comment]
@Cryptologism how could people think botting is good i mean not to be rude or anything but in there terms of service and in there twitter they always say that there finding a way to stop botting "anti botting"
(am not a fan boy by the way even tho i sound like it :p )

**Comment by Cryptologism** [comment]
@magicdev2 hahahaha sound like it... 
Most of them were trying to banned,avoid this all botting aps and botting person...
