### ISSUE TITLE
Pokestops wont load.

### ISSUE THREAD

**Issue by kingsley7601** [Lunat1q/Catchem-PoGo#1027]
Pokestops arent loading any way to fix. Frequent problem occurring please help.

**Comment by Allodssss** [comment]
Hello, I have this same problem, step by pokestop but does not get the items it would like to know how to solve since tried to fix the settings but could not

**Comment by ClaasPlayz** [comment]
I have the same problem :3

**Comment by AlvaroBrisolla2** [comment]
Same here :(

**Comment by kertiek** [comment]
u guys have checked the loot pokestops" in settings right? .. just saying...

**Comment by AlvaroBrisolla2** [comment]
Yes Option is active , and besides not appear the Pokestops appear also not Pokemons on Map

**Comment by ClaasPlayz** [comment]
yes i have checked it

**Comment by Cryptologism** [comment]
This just happen to me a few second ago... Ermmm ip banned? Let wait about 1 hour to make sure of it

**Comment by Cryptologism** [comment]
Confirm it was ip banned but.. Did niantic use new system in ipbanned.. I mean i tried to running 3 bot and only 1 bot was normal running but the other 2 bot showing that no pokestop was showing neither pokemon... 
New system in Niantic or Bug in botting?..?

**Comment by AlvaroBrisolla2** [comment]
Now Pokestops are appearing gradually as it goes walking down the route

**Comment by b3tt0z** [comment]
Version 1.4.9.1 pokestops normal view. And around.

In version 1.4.9.2 the pokestops appear as go walking, and surroundings do not see anything!

**Comment by petoe93** [comment]
as the bot is walking in a new area without preloaded stops, it still catches pokemon and loots the stops, but the bot isn't showing them on the map. Beside this, 1.4.9.2 is working fine :)
Thx for the great work!!

**Comment by ggUdU** [comment]
http://imgur.com/a/BekEw

**Comment by soarsapien** [comment]
So do I, 1.4.9.2 won't turn pokestop to get item, the last version can turn pokestop normal was 1.4.8.1
(I hope this information can help)

**Comment by OSIRISzzGOD** [comment]
Mapzen or Google API
