### ISSUE TITLE
[Suggestion Far in the Future, maybe never] Use Pokemon location as a live feed for other bots

### ISSUE THREAD

**Issue by MarkoHess** [Lunat1q/Catchem-PoGo#1028]
Just an idea!, because something like pokemonradar.de or other scanner websites exist.
It's a nice idea to use the bot as an active scanner for those sites, feed some data to them and also receive others data in the own bot, so it can directly go to nearby (wished) pokemon locations without going from pokestop to pokestop.

**Comment by Lunat1q** [comment]
If any website will accept data from client, that data can be faked.
