### ISSUE TITLE
about the change on custom routes

### ISSUE THREAD

**Issue by kertiek** [Lunat1q/Catchem-PoGo#1029]
can u make this two things
- "For  Custom route - now it will not display all pokestops at the map, will only display the pokestops which was hitted diring the route, that will help you to understand did u build it in right way :round_pushpin: "

ad a checkbox that u can check on the "map & console" tab? .. so is
X follow the player..... speed factor........ X keep pokemon markers.......... zoom........ **show hitted pokestops**

if it is not checked .. then it shows all the pokestops as always.

- and also ... can u show the pokestops on the custom route creator? .. so its more easier to create them and not miss some stops... maybe a right click option ... "load surrounding stops" just like "set start" and "set waypoint" work.

**Comment by Prolesious** [comment]
to add to that, what about the option to continue the route after a limit has been reached, instead of going back to the start of the custom loop.

**Comment by Lunat1q** [comment]
no.
