### ISSUE TITLE
I cant Find the exe

### ISSUE THREAD

**Issue by Dospesos** [Lunat1q/Catchem-PoGo#103]
Hi, sorry for my bad english, but i cant find the .exe in the folder...
Can any one help me?
http://puu.sh/qCPn1/9ccc72b904.png

Thanks

**Comment by EnzzoCaaue** [comment]
This is the source man, the exe is [here](https://github.com/Lunat1q/Catchem-PoGo/releases/download/v1.3.2/Catchem_v1.3.2.1.7z)

**Comment by Bay101** [comment]
Please view the setup guide in the wiki, as you have most likely downloaded the source code rather than the compiled release. Wiki: https://github.com/Lunat1q/Catchem-PoGo/wiki/Setup-Guide

**Comment by Dospesos** [comment]
Wow, thanks! haha im a idiot.
Thanks again!

**Comment by ankhmok** [comment]
sorry guys would you mean to teach me how to download it? is that Code>Catchem? and than how? can anyone tell me the link? 

i know someone had post the source by EnzzoCaaue,

**Comment by Bay101** [comment]
PLEASE REFER TO SETUP GUIDE!!!!!
https://github.com/Lunat1q/Catchem-PoGo/wiki/Setup-Guide
