### ISSUE TITLE
Tranfer pokemon BUG

### ISSUE THREAD

**Issue by kakarotto** [Lunat1q/Catchem-PoGo#1032]
Wow, I had 2 vaporeons (98% and 94%), and when I logged now, the bot just transfered one of mine and I always use "keep 2 duplicates".

`[21:28:14]` (TRANSFERED) Vaporeon     - CP: 1595  IV:  94,03%  [Best CP:  378  IV:  98,02%] (Candies: 395)`

Damn it :'(

**Comment by Raphaph90** [comment]
the same happened here, my pinsir 92% IV, keep 93%...   use "keep 2 duplicates".

**Comment by lonelies** [comment]
set the "keep min IV" to 90% or lower

**Comment by lonelies** [comment]
note that your Vaporeon CP:378 have higher IV which is 98.02%. the bot will keep the higher IV. uncheck the prioritize IV over cp if u only care CP than IV

**Comment by Makyuras** [comment]
Set it to prioritize both

**Comment by Raphaph90** [comment]
the configuration is correct, it is a bug, already use the bot to two weeks and is the first time it happens

Transfer duplicate poke [x]
Keep Min CP 500
Keep min duplicate poke 2
Keep min IV 80
Priorize IV over cp [x] 

My pinsir transfer have 1110 CP / 92% IV

**Comment by CrisOng** [comment]
Pokes setting: 
Keep Min Duplicate 2
Keep Min IV% 90

Always keep only 1 Eevee if din't set up the 'Poke Lists Setting: Not to Transfer'
It will transfer all Eevee and left only 1, no matter what the IV% is over 90 or not.
Since v1.4.4.x.

**Comment by kakarotto** [comment]
Yeah, that's why now I added them to the "not transfer list"
But mannn, my vap =[

**Comment by Lunat1q** [comment]
taking a look into it
