### ISSUE TITLE
Include: In the Route Creator

### ISSUE THREAD

**Issue by b3tt0z** [Lunat1q/Catchem-PoGo#1033]
Include: In the Route Creator, show pokestops, allowing freedom to establish the way.
The pokestops display would be interesting.

Congratulations for the outstanding work!

**Comment by golgolak** [comment]
"For Custom route - now it will not display all pokestops at the map, will only display the pokestops which was hitted diring the route, that will help you to understand did u build it in right way :round_pushpin:"

yes, would be great to show all the pokestops in the area for easy custom routing. as for those that was hitted, just change the color to red so we know which ones were hit in the path and those that weren't. then we can easily re-adjust our routes. thank you.
