### ISSUE TITLE
autostop

### ISSUE THREAD

**Issue by ExequielGC** [Lunat1q/Catchem-PoGo#1034]
can u add an autostop in "x" time or xp or star dust? 

thx for this great bot!

**Comment by iAngelG** [comment]
There's an option to stop after "x" amount of pokestops, "x" amount of xp and "x" amount of Pokémon captured. It'll pause and then resume on it's own. I think there's a few more options too

**Comment by Etygan** [comment]
I think it refers to stay completely stopped in a pokestop and that appear pokemon
