### ISSUE TITLE
Problem in Manual Router not caught pokeballs

### ISSUE THREAD

**Issue by ggUdU** [Lunat1q/Catchem-PoGo#1036]
Have problems on router manual, the pokestops not caught pokeballs, and inventory is empty for pokeballs

**Comment by Etygan** [comment]
The same happens to me

**Comment by ggUdU** [comment]
OMFG, this version new updtate disable loot pokestops, i need cheked and resolved problem.

http://imgur.com/a/BekEw

**Comment by zanhehe** [comment]
Lmao. You guys gotta check the box on 'Loot Pokestop' 😂😂

**Comment by grinse** [comment]
with a custom route i have the issue "no proper route" yesterday all works fine with the same route -.-
