### ISSUE TITLE
from v1.4.4.*.* version

### ISSUE THREAD

**Issue by lwkacc1** [Lunat1q/Catchem-PoGo#1037]
Yes very nice function which very kind and talented. but after that version it crash every single time. rounte unable to load, build, last time telegram crash everytime i start it or even i dont need to click single buttom. i dont need anything special, i only need a simple working function with a route control/radius.  other u can try it slowly  i only need farm peacefully

**Comment by OSIRISzzGOD** [comment]
Follow here Live chat for that
https://discord.gg/tsmF7

**Comment by Lunat1q** [comment]
If u can record or printscreen the process when it get crashed - that will be nice
