### ISSUE TITLE
Delay evolve poke

### ISSUE THREAD

**Issue by platerick** [Lunat1q/Catchem-PoGo#1038]
Hey man, can u fix the delay between evolve more than one poke?
That setting is not working fine.

Ty for bot, its really amazing!

**Comment by OSIRISzzGOD** [comment]
Follow here Live chat for that
https://discord.gg/tsmF7

**Comment by Lunat1q** [comment]
delay is working just as it should 
![](http://i.imgur.com/vpt3qCY.png)
