### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by tombeur** [Lunat1q/Catchem-PoGo#104]
how to put it in French? thank you

comment le mettre en français ? merci

**Comment by Bay101** [comment]
Please view the setup guide at: https://github.com/Lunat1q/Catchem-PoGo/wiki/Setup-Guide

**Comment by mmedinay25** [comment]
Goodnight,
Despite having the configuration .jason in Spanish does not work on the bot, I will be grateful for your support problem.

Thank you very much;)

**Comment by tombeur** [comment]
hello, I followed the installation instructions to change the language in French I mi "en" in place of "in" but its not working if you could check in advance thank you
