### ISSUE TITLE
it don't get any pokebells or pokestop

### ISSUE THREAD

**Issue by livedalzen22** [Lunat1q/Catchem-PoGo#1040]
![image](https://cloud.githubusercontent.com/assets/11879916/18113329/68b67936-6f61-11e6-952c-1ddd9db5ef3a.png)

why?????????????

**Comment by catchya** [comment]
check the setting, click the box under catch wild poke

close

**Comment by livedalzen22** [comment]
oh, the bot add "loot pokestops" method but i don't click this box
