### ISSUE TITLE
NEED HELPS

### ISSUE THREAD

**Issue by klykly1** [Lunat1q/Catchem-PoGo#1042]
Hey guys everytime i run the bot one of my account gonna recieved this kind of error , but when i tried to log in to my android its not yet ban i can still login. Anyone knows this kind of issue how to fix? Help me mate thanks a lot (Y) Bdw its a google account

![image](https://cloud.githubusercontent.com/assets/20981088/18114087/f72ae47c-6f66-11e6-83ff-b4e248a2e108.png)

**Comment by Lunat1q** [comment]
Try google app spec password

**Comment by billytheonly** [comment]
maybe the 2 step password... add an application password on google
