### ISSUE TITLE
My bot no auto favorite any pokemon

### ISSUE THREAD

**Issue by juliopokemon** [Lunat1q/Catchem-PoGo#1043]
it does not have any favorite pokemon

![aaaaa](https://cloud.githubusercontent.com/assets/21186387/18114325/b137affe-6f0c-11e6-83ab-c1ccb95ee9bc.png)

**Comment by Lunat1q** [comment]
Then u have non of IV > 90

**Comment by juliopokemon** [comment]
![aaa](https://cloud.githubusercontent.com/assets/21186387/18120861/34094ac0-6f38-11e6-87b4-4c59345e9f58.png)
