### ISSUE TITLE
Add import usernames w/config and proxylist [REQUEST]

### ISSUE THREAD

**Issue by Sparkman3271** [Lunat1q/Catchem-PoGo#1046]
I cool idea would be to have an option to import multiple accounts from a txt file and you could have an option of importing it with a config file to each account. Also, another good idea is to implement a way to have multiple proxies that switch whenever a proxy gets banned, and you could import a proxylist with thousands of proxies. I didnt know where to put ideas so i just put it here please tell me where to put ideas/requests if this isnt the right place :)

**Comment by Lunat1q** [comment]
Batch creation. Already exists
