### ISSUE TITLE
attention in the message bot info

### ISSUE THREAD

**Issue by teemo63** [Lunat1q/Catchem-PoGo#1047]
MobBotRouting api Key is empty

I see often in the post info bot is could someone help me?
translated with google translation (I'm French)

je vois se message souvent dans le bot info est ce que quelqu'un pourrait m'aider ? 
traduit avec google traduction ( je suis français )

i take a picture
![catchem_2016-08-31_05-47-28](https://cloud.githubusercontent.com/assets/21278468/18115296/a078c45a-6f3e-11e6-8d81-a809dde45441.png)

[http://i.imgur.com/oVNIGZ2l.jpg](url)

**Comment by yepaco** [comment]
va par ici !

https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen

**Comment by teemo63** [comment]
thank for your help but
I followed that and brand but I still have the same message
is that prevents me from taking pokestop
but I captured pokemon
translated with google translation

j'ai suivi se qui et marque mais j'ai toujours le même message 
se qui m'empeche de prendre les pokestop 
mais je peux capturé des pokemon 
traduit avec google traduction

**Comment by Lunat1q** [comment]
Need to fix the wiki... Will do it today

**Comment by teemo63** [comment]
thank you suddenly I have to stay patient in order to correct bugs or use an older version?
