### ISSUE TITLE
Transfernot working

### ISSUE THREAD

**Issue by FantoYouYou** [Lunat1q/Catchem-PoGo#1050]
Hello, I've activated the transfer option for duplicate pokemon, but it won't transfer my pokemon, the bot keep all of them. It worked fine before but since 1.4.9.1 i can't seem to make it work. Any idea ?

**Comment by tryndamerewu** [comment]
did you put  kep min duplicate on 1?

**Comment by FantoYouYou** [comment]
Yes it's set to 1

**Comment by Lunat1q** [comment]
He will transfer it an next maintain routine. Let it walk.
