### ISSUE TITLE
Can't touch the pokestops

### ISSUE THREAD

**Issue by soarsapien** [Lunat1q/Catchem-PoGo#1051]
Hello, I met a problem after 1.4.8.1
My bot pass through a lot of pokestops but just not active it

[11:26:20] Name: 粉紅色的小金剛 XP: 50, Gems: 0, Items: 1 x ItemPotion, 2 x ItemPokeBall
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Something like this didn't happened anymore after 1.4.8.1)
(so I cannot get any new balls and items)
(1.4.8.1 is the latest version worked normal in active pokestops)

How to fix this problem? Thank you

**Comment by zellerda** [comment]
![2016-08-31_07-26-25](https://cloud.githubusercontent.com/assets/140013/18117008/43a56ed2-6f4c-11e6-8601-037cc5e42a47.jpg)

**Comment by soarsapien** [comment]
I missed that, Thank you for helped!!
