### ISSUE TITLE
Add a random delay seconds when transfer

### ISSUE THREAD

**Issue by harley12** [Lunat1q/Catchem-PoGo#1053]
Hi Lunat1q / Author:
First, I very appreciate your enthusiasm to develop this tool.

I know in Setting sheet, there is a Delays column, and I can set the delay when transfer.
But when bot to transfer a lot of pokes, the time between each action is the same.

I think this action is not like a human, can we add a number "n".
The "n" means a random number (for example: n= 1~5).
When each transfer, the bot will get a new "n", so the delay time will become "Delay Transfer Poke" + "n"

Thanks for your patient!

**Comment by Lunat1q** [comment]
Delays are always random.
