### ISSUE TITLE
[Feature Request] Items to keep/recycle

### ISSUE THREAD

**Issue by devgraal** [Lunat1q/Catchem-PoGo#1056]
Is there an easy way to deal with pokeballs type to keep/recycle ?
I mean, for now we keep %amount% of pokeball, not depending on their type.
Could be a nice thing to add if you can ;)
BTW: very verry nice work !!!

**Comment by tkien212** [comment]
it will recycle the worst pokeball, and keep the best pokeball

i don't think your feature is needed

**Comment by Lunat1q** [comment]
Tired of replying same shit over and over. USE SEARCH at closed Issues
