### ISSUE TITLE
Proxy doesn't works

### ISSUE THREAD

**Issue by JBWKZ2099** [Lunat1q/Catchem-PoGo#1058]
When I test any proxy, no one works, every time I test a proxy, it always fails.
I don't know if the problem is the webpages that i use:
http://www.freeproxylists.net/
http://free-proxy.cz/en/

**Comment by Lunat1q** [comment]
Proxy works. I use it every day. The fact what your proxy don't work say only 1 thing: you use shitlike proxy.
