### ISSUE TITLE
[Feature Request]  info/data layers on world map

### ISSUE THREAD

**Issue by stanq87** [Lunat1q/Catchem-PoGo#1059]
can u add showing of
gyms
pokestops
pokemons seen/caught ( with options to filter)

if u do something liek that a big plus would be  if Catchem would keep that data beetwen sessions so we can pinpoint a pokemon nest that we want to farm

**Comment by Lunat1q** [comment]
It can't be done, current map controller don't have overlays. If you will have info about map controll what can work with system proxy - you are welcome.
