### ISSUE TITLE
The sniper is not displayed on the bot

### ISSUE THREAD

**Issue by mmedinay25** [Lunat1q/Catchem-PoGo#106]
I have a 18.5-inch screen and opening the bot can not display the options of the lower part.

https://www.dropbox.com/s/odcyzhk4tcw2sez/issue.png?dl=0

Please support.

Thank you :)

**Comment by daimoncall** [comment]
Sniping is not yet stable. That's why it is disabled.

**Comment by Lunat1q** [comment]
fixed
