### ISSUE TITLE
Never spin a Pokestop

### ISSUE THREAD

**Issue by andnyue** [Lunat1q/Catchem-PoGo#1060]
In version 1.4.8.1 Bot can spin any pokestop,
But in 1.4.9.2, Bot never spin a pokestop, and gradually will runout pokeball.

So I revert my version back

Sorry for bad english

**Comment by sapdkeybinder** [comment]
Settings Option Loot Pokestops activated?

**Comment by gregory0219998** [comment]
Team has added an option "loot pokestop" that from default is turned off, so please turn on.
Also i want suggest to @Lunat1q  to put it on by default

**Comment by Lunat1q** [comment]
it's ON by default. but when u move old profile into new release, it's being set to false, cause false is default value for bool. if you don't like it - call microsoft :)

**Comment by Lunat1q** [comment]
Also:
![](http://i.imgur.com/eNLBHSm.png)
