### ISSUE TITLE
No pokestops and pokemons displayed

### ISSUE THREAD

**Issue by Initiols** [Lunat1q/Catchem-PoGo#1061]
Basically, even when using fresh pokemon GO accounts, or old ones; whatever the version of Catchem, no pokestops are displayed, and no pokemons are spawning...

**Comment by sapdkeybinder** [comment]
restart your router IP Ban

**Comment by Initiols** [comment]
Wait what Niantic banned me ? x')

**Comment by sapdkeybinder** [comment]
your IP is banned, when you not see Stops and Pokemons restart router

**Comment by Initiols** [comment]
Un I mean, just changed IP, worked for a moment, started over again (same problem)
Btw the accounts I'm using right now aren't banned on my phone rip

**Comment by Initiols** [comment]
Hold on problem solved, I guess that was due to the GoogleDirections' custom route (that I created myself). Seems to only display nearby pokestops...

**Comment by Lunat1q** [comment]
yes. and that is described in release note.
