### ISSUE TITLE
(Error)Niantic servers unstable, throttling API call-every 30 mins happens once

### ISSUE THREAD

**Issue by omg982** [Lunat1q/Catchem-PoGo#1065]
(Error)Niantic servers unstable, throttling API call-every 30 mins happens once

**Comment by gregory0219998** [comment]
Did you try a proxy? all works good here

**Comment by omg982** [comment]
run the application without proxy...

**Comment by Lunat1q** [comment]
it was fixed like... 3 versions ago.

**Comment by angelaayer** [comment]
same error with the latest version. What does it mean?
