### ISSUE TITLE
No Pokestops ...

### ISSUE THREAD

**Issue by nikogoe** [Lunat1q/Catchem-PoGo#1071]
[11:59:10] (ATTENTION) Keine nutzbaren Pokestops in deiner Gegend gefunden. Ist die maximale Distanz zu klein?

No usable Pokestops ... since a few hours ... please fix this!!
I did not change the configs ... so please fix this!!

**Comment by CuspMe** [comment]
![image](https://cloud.githubusercontent.com/assets/21124201/18124472/fdfb1edc-6fa4-11e6-9947-1dd676c306c7.png)

**Comment by tryndamerewu** [comment]
look in config you see option loot pokestop
