### ISSUE TITLE
Pokestops doesnt auto update

### ISSUE THREAD

**Issue by CuspMe** [Lunat1q/Catchem-PoGo#1072]
![image](https://cloud.githubusercontent.com/assets/21124201/18124615/89d3e10a-6fa5-11e6-8166-5bf434399dd8.png)

after i forcemove it, the pokestops doesnt update. * i dont have custom route 

![image](https://cloud.githubusercontent.com/assets/21124201/18124679/dd7b7f84-6fa5-11e6-957b-66b88bf0b9dd.png)

after i restart the bot, the pokestops updated. please fix this bug

**Comment by Lunat1q** [comment]
it will display it as soon as he gets to the point, but still. added pokestops what bot spin during the move to the map..
