### ISSUE TITLE
Pokeballs ...

### ISSUE THREAD

**Issue by nikogoe** [Lunat1q/Catchem-PoGo#1076]
![image](https://cloud.githubusercontent.com/assets/21286663/18125425/80db5832-6f76-11e6-8723-c0945fc166e0.png)

What the Fuck is this? I did not change anything and your Bot is spamming me ...

**Comment by meganovato** [comment]
Ban

**Comment by wagas** [comment]
try restarting your bot

**Comment by Lunat1q** [comment]
Read release notes. v1.4.9.0
