### ISSUE TITLE
Console Mode

### ISSUE THREAD

**Issue by zeldaleonz** [Lunat1q/Catchem-PoGo#1077]
Please add alternative way to start bot from console mode. So we can run it different way.

Main setting will be from GUI Mode, and all setting will save in profiles, (Bot profile, saved routes, telegram setting), when everything complete we can start it in console mode, to make less resources.

Main Focus is GUI Mode, console just for alternative mode only

Thank for your time for this project sir

**Comment by Lunat1q** [comment]
Are you insane? if u want just a console - you Mobbot!
