### ISSUE TITLE
Missed PokeStops

### ISSUE THREAD

**Issue by xTeddiusx** [Lunat1q/Catchem-PoGo#108]
Hello,
lot of times pass near unused pokestops and going for the far away one.
maybe something oing on with this code?

`    "UsePokeStopLuckyNumber": true,
    "PokestopSkipLuckyNumberMinUse": 3,
    "PokestopSkipLuckyNumber": 1,
    "PokestopSkipLuckyMin": 0,
    "PokestopSkipLuckyMax": `4,``

**Comment by Lunat1q** [comment]
nope, this settings related only to non-Discovery pathing
