### ISSUE TITLE
GoogleDirections

### ISSUE THREAD

**Issue by Initiols** [Lunat1q/Catchem-PoGo#1080]
(Already posted another boring post for another randown subject, but anyways)

Just got my GoogleDirections API Key, like on the wiki page, I have red and green paths..

But how do I make my character follow the green one cause the red one's going in wierd places :[

**Comment by ArchangelBr** [comment]
If I could give to you an advice: use mapzen valhalla.
It's easy to get the key and is more efective for me.

**Comment by Initiols** [comment]
Thanks for your tip, just got the key, but it haves the same pattern, and sometimes it misses some pokestops, so I there is a way to target the green path ?

**Comment by Lunat1q** [comment]
Call to google, ask ask them to fix their fucking google directions api :)
