### ISSUE TITLE
No proper route loaded.

### ISSUE THREAD

**Issue by alcianderson** [Lunat1q/Catchem-PoGo#1081]
Whats this error?
I make manual route in createroute.

**Comment by Lunat1q** [comment]
Did u select it? in the bot settings?

**Comment by alcianderson** [comment]
I select use custom route.

**Comment by alcianderson** [comment]
And make the route in createroute

**Comment by Lunat1q** [comment]
I asked not about this!
![](http://i.imgur.com/Y87385G.png) DID U DO THIS?

**Comment by petoe93** [comment]
got the same problem now.
i created a new route yesterday, saved it and used once, everything was working then (only has 19 waypoints). Now i wanted to start the same route again, but i keep getting the same error.

**Comment by alcianderson** [comment]
No have this option
