### ISSUE TITLE
Sniping

### ISSUE THREAD

**Issue by NeoNecris** [Lunat1q/Catchem-PoGo#1082]
Is there a way to implement sniping?  (like pokesnipers.com)

As what I understand it should be possible to enter some coords.
Go to the coords
Wait for the rare pokemon... when it spawns - click it ;-)
then return to your old startpoint coords
and then catch the pokemon so gps ban is avoided...

Is this a possible feature?

**Comment by minimacz** [comment]
I recon they could do this because its a fairly easy thing ti implement seeing as he could just use the map spoofing which is already in it.

**Comment by minimacz** [comment]
sniping gets you banned really easily thought and the point of the bot is so you dont have to do it your self and you dont get banned

**Comment by NeoNecris** [comment]
I've seen the following in the config files... what does this do?

  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "charmander",
      "charmeleon",
      "charizard",
      "squirtle",
      "wartortle",

**Comment by Lunat1q** [comment]
You will be banned for that, explained this like 10 times.
