### ISSUE TITLE
not replenishes in pokestop

### ISSUE THREAD

**Issue by andersonrufino** [Lunat1q/Catchem-PoGo#1083]
when you arrive in pokestop not replenishes items

**Comment by uchitake84** [comment]
Same here

**Comment by juancarealone** [comment]
same over here

**Comment by NeoNecris** [comment]
Please verify if the setting "loot pokestops" is checked!

**Comment by juancarealone** [comment]
is checked

**Comment by andersonrufino** [comment]
ah yes I did not realize pokestop loot cleared
