### ISSUE TITLE
No Pokeballs causing enter a loop

### ISSUE THREAD

**Issue by diorox** [Lunat1q/Catchem-PoGo#1085]
Hi.
The character used all pokeballs and when it tried to catch a pokémon, Catchem Bot entered a loop.
Can you code to the character to verify pokeballs before to try catch pokémon? If it doesn't have pokeballs go to pokestop for more items? ( http://prnt.sc/cci985 )
(I verify that "Loot PokeStops" is checked)
Regards. :smile:

**Comment by Lunat1q** [comment]
done.
