### ISSUE TITLE
wrong # candies on evolve

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1086]
If you evolve a pokemon manually, the new pokemon is listed in inventory, but the number of candies available does not decrease on screen until you manually refresh the list. (1.4.9.2)

first pic is after evolve, second is after refresh
![capture1](https://cloud.githubusercontent.com/assets/9252175/18131065/acfb548a-6f4e-11e6-9a27-6b355d7c4eb2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9252175/18131071/b08b687e-6f4e-11e6-8917-2613410c63ca.PNG)

**Comment by Lunat1q** [comment]
fixed, can be caused by cached iventory
