### ISSUE TITLE
wrong # of candies when batch transferring (from information tab)

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1087]
(TRANSFERED) Bellsprout   - CP:  184  IV:  29.29%  [Best CP:  143  IV:  79.71%] (Candies: 10)
(TRANSFERED) Bellsprout   - CP:  143  IV:  79.71%  [Best CP:  297  IV:  69.46%] (Candies: 11)
(TRANSFERED) Bellsprout   - CP:  255  IV:  52.79%  [Best CP:  297  IV:  69.46%] (Candies: 11)
(TRANSFERED) Bellsprout   - CP:  253  IV:  48.45%  [Best CP:  297  IV:  69.46%] (Candies: 11)

The inventory list is right however, listing 13 at end of transfer.

**Comment by Lunat1q** [comment]
it's ok, just a cached inventory info.
