### ISSUE TITLE
how to copy map routecreator

### ISSUE THREAD

**Issue by cyberfilou** [Lunat1q/Catchem-PoGo#1098]
Hello,

How to copy map ( routecreator ) from old releases  to new releases

Thx for respons

Cyberfilou

**Comment by franj62** [comment]
catchem.json - map config
tlgrm.json - Telegram config

**Comment by Lunat1q** [comment]
catchem.json contains some extra data :) not just a routes, but routes are there, that's  for sure

**Comment by cyberfilou** [comment]
Thx for Help ;-) :P
