### ISSUE TITLE
GPS system not working correctly

### ISSUE THREAD

**Issue by NavyBloodH** [Lunat1q/Catchem-PoGo#110]
gps system is not working correctly. If other Latitude and Longitude are entered.
please check this
ty

**Comment by Bay101** [comment]
Please Elaborate

**Comment by marceloclp** [comment]
Everytime I enter a new latitude and longitude and hit start, after 3-4 seconds the bot just crashes. The same thing happens if you select the place using the map gui. The bot just crashes and there are no errors on the logs.

**Comment by Lunat1q** [comment]
fixed
