### ISSUE TITLE
not the favorite Pokemon

### ISSUE THREAD

**Issue by meganovato** [Lunat1q/Catchem-PoGo#1100]
Marked the "Keep poke que can evolve" option. Even with that marked the bot tranfere the Pokemon that I scored in the filter, to evolve

Marked the "Keep poke que can evolve" option. Even with that marked the bot tranfere the Pokemon that I scored in the filter, to evolve
The bot is also not favoritando the Pokemons. I mark the "Auto favorite poke" and "Poke min Iv porcentagen" I March 90 and saved, it still does not favorite anything

It is also not keeping the Pokémon to evolve, landmark the "Use lucky eggs while evolving" and in March in "Lucky eggs min poke" 70, but he never joins the 70 Pokemon to evolve

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/slMmr7u.png)
fixed, redownload the latest release.
