### ISSUE TITLE
The over inventory checking issue getting worse

### ISSUE THREAD

**Issue by catchya** [Lunat1q/Catchem-PoGo#1101]
![self check](https://cloud.githubusercontent.com/assets/21166049/18137182/5a9d8182-6f75-11e6-8483-d649a7e33083.png)

the updated release made the thing worse, bot self check too much, it checked 8 times straight.
so far 1.4.8 is the most efficient version. 1.4.9 slowed down a lot

**Comment by catchya** [comment]
btw i set the inventory checking as 0.95

**Comment by Lunat1q** [comment]
what's your other settings?

**Comment by Lunat1q** [comment]
show me the screen shot of entire Inventory group

**Comment by catchya** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21166049/18137713/90a9e638-6f77-11e6-9dc3-a7ce5429e09c.png)

right now i changed to 0.99 so it not self check too much, but cannot set route. Since during route, it wont self check, so the inventory easy to full and always get no items from pokestop, make the activities look fishy.

**Comment by Lunat1q** [comment]
Ok, here is your problem, you set it to 240 + 80 = 320 which is 91%, but you forgot about Lucky eggs, Incenses, and other items in your inventory. So... but just can't clear it with the current settings. and trying to do it over and over.

**Comment by catchya** [comment]
the other item add up together around 20, so I kept 10 as cousin.

then problem is when i set as 0.95, which is higher than 91%, it still self check.
or you mean the ball+berry+other items need to be lower than this percentage?

**Comment by Lunat1q** [comment]
exactly. it's total % of inventory usage, not just berries and pokeballs

**Comment by catchya** [comment]
gotcha, reset and remove 10 more balls.
thx for your efforts
