### ISSUE TITLE
separate each item by dividing each type of Pokeball, potions, etc.

### ISSUE THREAD

**Issue by roneys93** [Lunat1q/Catchem-PoGo#1105]
It would be interesting to separate the items by category not more per item really **Ex: Great ball - 10 ---- Ulta ball - 100 --- pokeball - 100**

It would help a lot to keep the amount of items we have in inventory

**Comment by Lunat1q** [comment]
holly.... i should explain this EVERY DAY? READ CLOSED ISSUES... really...
