### ISSUE TITLE
feature request : on demand lucky eggs

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1107]
I prefer to evolve my own pokemon. I end up with more evolves per 30 minutes than the bot can do with its algorithm. For instance. If you have 13 pidgeys and evolve 12 to pidgeotto, you can transfer those 12 pidgeotto and evolve the last pidgey -> extra 1000XP with the egg. That is one of the tricks a human can do that the bot can't (yet!).

I wish the bot would do nothing else at all while (batch) evolving.  Don't spend time dumping extra inventory or other things between evolves.  Lucky eggs are hard enough to get. There is no reason to waste time getting a 2x pidgey captured when you could get 1000xp for evolving one!

**Comment by developnoop** [comment]
Also would like to see this. But for me the bot doesn't start evolving with lucky eggs. Maybe i have a problem in my config. Will check.

**Comment by Lunat1q** [comment]
i've got what u mean, but i'm not sure when i'll be albe to do this. closed for now.

**Comment by Cowering** [comment]
How about adding another option to right click menu in information tab 'use item'. Could deploy a lure, egg, or incense. I don't know if the real game sends an error to PMG servers if you try to use 2 eggs at once so maybe you have to keep your own flag/timer if the bot already used an egg,
