### ISSUE TITLE
RouteCreator

### ISSUE THREAD

**Issue by gholke** [Lunat1q/Catchem-PoGo#1108]
Where is saved routes created in previous versionss? 
I would like to use those who are ready.

**Comment by developnoop** [comment]
Me too, was searching also for them. No Textfile or GPX file to be found in the directory of Catchem

**Comment by franj62** [comment]
It's already answered #1098

**Comment by developnoop** [comment]
Thanks @franj62! Didn't know this.

**Comment by developnoop** [comment]
Added this info to the wiki page, so that it didn't get lost :-)

**Comment by gholke** [comment]
Sorry I did not see, thank you!
