### ISSUE TITLE
[STILL BUG] New release crashes after a random time.

### ISSUE THREAD

**Issue by kaktusisko** [Lunat1q/Catchem-PoGo#1109]
![crash](https://cloud.githubusercontent.com/assets/21192128/18140484/0a7d59b6-6fb6-11e6-9cdf-accee0a8bc0a.png)

**Comment by kingsley7601** [comment]
How many bots are you runinng?
and for how long?

**Comment by kaktusisko** [comment]
~25 bots ~30 min.
![cpu](https://cloud.githubusercontent.com/assets/21192128/18140930/d94dcbb2-6fb7-11e6-9d48-54160816490a.png)

**Comment by petoe93** [comment]
25 bots..fml..people just can't get enough

**Comment by kaktusisko** [comment]
I assume that the majority will be banned.

**Comment by JeanRolszt** [comment]
i have just 1 bot running, and crashes about 30 min.
stop working message.
nothing in the console.

**Comment by KoopaTheTurtle** [comment]
I have 2 bots and crashes every 20ish minutes

**Comment by developnoop** [comment]
One bot, crashes randomly. Sometime if i try to transfer something or evolve something, sometimes just so. A Debug Option for Debug Outputs could maybe help :-)

**Comment by kingsley7601** [comment]
i have ten bots but without a proxy my ip gets soft ban so i only run 5-8 atm do you have any proxies i could use

**Comment by franj62** [comment]
You don't have enough with a bot?

If you abuse, it is what you get.

**Comment by kaktusisko** [comment]
1 bot / 1 IP. If someone uses the same proxy - ban.
Please don't spam here, lets get back to the subject.
V1.4.8.1 works best for me, but some catch (ERROR)s too.

**Comment by maknado** [comment]
I GIVE ERRO WHEN TELEGRAM IS ACTIVE PLESE HELP

**Comment by Lunat1q** [comment]
Try to run the bot in VS debug, can help a lot with catching error, info u gave is just useless to determine the problem.

**Comment by kaktusisko** [comment]
![crash2](https://cloud.githubusercontent.com/assets/21192128/18146336/59678128-6fcf-11e6-852e-0ff106b492a8.png)

**Comment by kaktusisko** [comment]
Application: Catchem.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: PokemonGo.RocketAPI.Exceptions.InvalidResponseException
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions+<PostProtoPayload>d__1`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc+<PostProtoPayload>d__7`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PokemonGo.RocketAPI.Rpc.Inventory+<GetInventory>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PoGo.PokeMobBot.Logic.Inventory+<RefreshCachedInventory>d__33.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PoGo.PokeMobBot.Logic.Inventory+<GetCachedInventory>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PoGo.PokeMobBot.Logic.Inventory+<GetPlayerStats>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PoGo.PokeMobBot.Logic.Utils.Statistics+<GetCurrentInfo>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PoGo.PokeMobBot.Logic.Utils.Statistics+<Dirty>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()





Faulting application name: Catchem.exe, version: 1.4.9.3, time stamp: 0x57c6ee56
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x5736541b
Exception code: 0xe0434352
Fault offset: 0x00014878
Faulting process ID: 0x98c
Faulting application start time: 0x01d203b87795d752
Faulting application path: C:\Users\Administrator\Desktop\Catchem\Catchem.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report ID: af854d67-6fb4-11e6-80e5-00163caf6e4b
Faulting package full name: 
Faulting package-relative application ID: 



A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 10. The Windows SChannel error state is 1203.

**Comment by allencyl** [comment]
1 bot / 5 hour
應用程式: Catchem.exe Framework 版本: v4.0.30319 描述: 處理序已終止，因為有未處理的例外狀況。例外狀況資訊: PokemonGo.RocketAPI.Exceptions.InvalidResponseException 於 PokemonGo.RocketAPI.Extensions.HttpClientExtensions+<PostProtoPayload>d__1`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PokemonGo.RocketAPI.Rpc.BaseRpc+<PostProtoPayload>d__7`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PokemonGo.RocketAPI.Rpc.Inventory+<GetInventory>d__4.MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PoGo.PokeMobBot.Logic.Inventory+<RefreshCachedInventory>d__33.MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PoGo.PokeMobBot.Logic.Inventory+<GetCachedInventory>d__7.MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PoGo.PokeMobBot.Logic.Inventory+<GetPlayerStats>d__23.MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PoGo.PokeMobBot.Logic.Utils.Statistics+<GetCurrentInfo>d__16.MoveNext() 於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) 於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 於 PoGo.PokeMobBot.Logic.Utils.Statistics+<Dirty>d__10.MoveNext() 於 System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object) 於 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object) 於 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 於 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) 於 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() 於 System.Threading.ThreadPoolWorkQueue.Dispatch() 於 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by kaktusisko** [comment]
@Lunat1q Is that enough? Can you fix it?

**Comment by JeanRolszt** [comment]
1 bot/ 2hrs
w10 64bits
i3 , 2ram
 
![error](https://cloud.githubusercontent.com/assets/21296883/18176120/afb29f42-704a-11e6-81be-080855d09bb7.png)

**Comment by Clayoud** [comment]
Não está pegando pokebolas

**Comment by Clayoud** [comment]
e está usando ultrabal em pokemons fracos, ou seja, não está seguindo a configuração.

**Comment by ramsay2016** [comment]
It seems that it crashes after auto **pause**, and when theres an **error** (Niantic Server Unstable). Checking Catchem logs i can see las logged before crashing was going to pause:

last line of log file:
**[22:50:59] Current Operation was canceled. Bot stopped/paused.**
another case:
**[14:54:58] Niantic Servers unstable, throttling API Calls.
[14:54:58] [NIANTIC] Se produjo una excepción de tipo 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException'.**

**Comment by kaktusisko** [comment]
V1.4.8.1 works a little longer, but im not sure is it safe.

**Comment by miguelslemos** [comment]
thats happen with me too, last line of Log (Success) Weedle, lvl 2....
2 bots / maybe 20 hours
Windows 7

**Comment by JeanRolszt** [comment]
i'm just install the new version (V1.4.9.4)
let's try...

**Comment by JeanRolszt** [comment]
@Clayoud tem uma opção nas configurações, (LOOT POKESTOPS) ela deve estar desmarcada.
Já nos casos da ultraballs, tenta colocar denovo no filtro, apertar salvar e reniciar o bot.

**Comment by JeanRolszt** [comment]
@Lunat1q maybe this can resolve? http://stackoverflow.com/questions/36526128/system-net-http-httprequestexception-occurred-in-mscorlib-dll-but-was-not-hand

**Comment by ramsay2016** [comment]
Version 1.4.9.4, almost 12 hours running, no crash. :D. 2 bots

**Comment by kaktusisko** [comment]
1.4.9.4 works long, but 4/10 bots have this for hours:
![crash3](https://cloud.githubusercontent.com/assets/21192128/18209234/3241cb02-7133-11e6-963a-7e26f080c4e1.png)
Status of the bot hasn't changed. Showing xp/h but not working.

**Comment by kaktusisko** [comment]
Turn off bot for one minute helps.
And still some throttling API Calls errors.

**Comment by JeanRolszt** [comment]
running about 7 hrs, no crash,
but when i close my notebook, the bot crash, so i don't close my notebook :)

**Comment by delunatix** [comment]
Limit botting to 2 only... tis more stable and there is no point of being greedy lol.

**Comment by magicdev2** [comment]
you must be doing something in order to crash it i run 15 pokemon accounts and i can use it up to how many hours i want without a crash.

**Comment by kaktusisko** [comment]
V1.4.9.4 (updated) crashes after couple seconds at Windows Server Datacenter 2008 R2 SP1 (64bit).
Works good before release update. Works good at Windows Server 2012 R2.

**Comment by kaktusisko** [comment]
Crashes also at Windows Server 2012 R2. Working about 1-2 hours. 
V1.4.9.4 works good before update of this release.

**Comment by tyu366** [comment]
I have 1 bot running only.  I run the bot for 13 times in 3 days and crash twice.  I have using windows 10.  There is no screen off during the run and no human operation during the moment.  The internet is stable so far during the running time.  I seems not very stable for this release.  One not sure whether this is due to change to a new calendar day (after 00:00).  I suggest the log to list the event in turns of local time.

**Comment by SweeTIPi** [comment]
Crashing here sometimes too.

**Comment by tyu366** [comment]
![2016-09-06_230216catchem](https://cloud.githubusercontent.com/assets/21959374/18279026/b944dbca-7486-11e6-9808-328c9465faa9.jpg)

**Comment by kaktusisko** [comment]
v1.5.0.0 works without this crash.
v1.5.1.0 works only about 4 hours/one time.
v1.5.1.1 works only about 2 hous/one time.

**Comment by kaktusisko** [comment]
v1.5.0.0 works without this crash, but more (ERROR)s.
v1.5.1.0 works only about 4-5 hours
v1.5.1.1 works 2-9 hours
v1.5.2.0 works 1-3 hours
v1.5.2.1 works only couple minutes.

**Comment by kaktusisko** [comment]
Why?

**Comment by kaktusisko** [comment]
v.1.5.3 all bots can't log to the game.

**Comment by developnoop** [comment]
Must be a proplem on your side, on my side the 1.5.3.0 runs 6h without problems.
