### ISSUE TITLE
api error before egg hatching still continue

### ISSUE THREAD

**Issue by kadirboz** [Lunat1q/Catchem-PoGo#1110]
hi,
firstly thanks for this great work. now i get api error before egg hatching like this.
![ekran alintisi](https://cloud.githubusercontent.com/assets/21368679/18140440/359f7270-6fbe-11e6-82f2-eb114b76e3ae.PNG)

and i think writing pokemon's attack power in pokemon's info popup, it will be awesome. like this;
![adsiz](https://cloud.githubusercontent.com/assets/21368679/18140527/a0dc0f4e-6fbe-11e6-8be5-8c8ab3239a0e.png)

thanks for everything.
regards

**Comment by petoe93** [comment]
DPS would be way smarter than the dmg of the attack itself, but good idea though

**Comment by Lunat1q** [comment]
that idea is soooo fresh, what i even smell it. there is no way to calculate attack dmg for now. It's not server-side data, looks like.

**Comment by kadirboz** [comment]
it will be array in code.
```
attackmoves = array(
'tackle' => 10,
'bite' => 6,
'earthquake' => 100,
);
```

like this. it dont need server-side. every moveset is same attack power. it will be easy for you.
