### ISSUE TITLE
manual mode log msg?

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1114]
How about a msg in the log that manual mode is on or off? my 1.4.9.3 keeps walking and spinning pokestops while I am trying to manually transfer pokemon.

**Comment by developnoop** [comment]
Would like a option like this, happens to me also a lot :-)

**Comment by Lunat1q** [comment]
spining is ok. walking too, you can do it in the real game nearly the same time, for other actions, there is a lock already.

**Comment by developnoop** [comment]
Which lock do you mean? Sorry to ask, but maybe i oversee the obviuos?
