### ISSUE TITLE
Request : on the choice of the differents Pokeballs

### ISSUE THREAD

**Issue by JewelsNirvana** [Lunat1q/Catchem-PoGo#1115]
Hi Lunat1q and again good job for your work everytime !
My english is bad, so i try to explain easily. So, a function or additional lines would be this possible to add which would give us the choice into the different pokeballs and their number which we want to catch and keep.
For example : Inventory -->  -70 Pokeballs
                                              - 80 Greatball
                                              -100 Ultraball

If i ask that, it's cause i've all the time 150+ pokeballs and only [5-10] great and ultra balls, same after 6-7 hours of CatchemPogo Bot.
Thanks and have a nice day ! :)

P.S : Like that -->
![catchem change](https://cloud.githubusercontent.com/assets/21356159/18142827/8ada4fc0-6fbf-11e6-946f-d9aa44cc1177.PNG)

**Comment by catchya** [comment]
dont really think this function is necessary.

**Comment by Cowering** [comment]
This is how I play with my real account. I keep pokeballs to about 20 so as to get my great and ultra count up. That was, if a hard to catch pokemon comes along, I have the right ball to use.  As a matter of fact, the bot is kinda brain dead on when to use razzs. It will use one and then use a pokeball... miss the capture, and use a greatball next without using another berry. no human would do that!

**Comment by JewelsNirvana** [comment]
I think, in fact, that it is a good idea, because not to have somes Greats & Ultra Balls, when you play really with your friends after, that suck.. To be lvl 30 + and not to have somes of this items, it's sad and more difficult to catch Rare Pokemons for us ! 
It was a suggestion for Lunat1q, now if nobody want that, too bad.
 I found that really nice and useful

**Comment by Lunat1q** [comment]
Duplicate, not goint to explain this shit again.
