### ISSUE TITLE
My catcher app is broken?

### ISSUE THREAD

**Issue by LifeForKill** [Lunat1q/Catchem-PoGo#1116]
https://gyazo.com/a32871c4b8cfecb9c3d57058163cbeec

this is happening to me now, i cant get te the bot to work... any help?

**Comment by catchya** [comment]
looks like you got banned, did you snipe?

**Comment by LifeForKill** [comment]
no i didnt, i checked it on my phone also. It´s normal there tho..

**Comment by LifeForKill** [comment]
exactly, i can play it on my phone, but the catcher app is not working for me, and i dont know why..

**Comment by catchya** [comment]
good for u, then delete all the old file and unzip again. 
GL

**Comment by LifeForKill** [comment]
i was on vacations for 1 week, i didnt used the catcher on that time. I came today and this is happening...

**Comment by LifeForKill** [comment]
but i didn that, i downloaded the last version today, but this is happening
