### ISSUE TITLE
Any good proxies??

### ISSUE THREAD

**Issue by kingsley7601** [Lunat1q/Catchem-PoGo#1122]
Does anyone use any good stable proxies?

**Comment by kaktusisko** [comment]
almost all have some problems.

**Comment by kingsley7601** [comment]
but is there any i can use to run all my bots

**Comment by kaktusisko** [comment]
1 proxy / 1 account

**Comment by kingsley7601** [comment]
i know but is there is one i can use

**Comment by Cryptologism** [comment]
i think there was lot of ip proxies put there but they will be dead not even 2 hours after use... becasue it was public...
so try to think to make personal proxies.. Lot of way to make it and for more better buy a proxies.. but make sure proxies that you wanna buy can support pokemon go cuz i just google one proxies seller already tell in earlier that thier proxies cannot support pokemon go...

**Comment by franj62** [comment]
A good proxy is that you buy and use only you.
