### ISSUE TITLE
Location catch via Telegram

### ISSUE THREAD

**Issue by leozinxd** [Lunat1q/Catchem-PoGo#1123]
Some people use the bot, but has an account "clean" and use the bot in the locality who live and can get the poke with two accounts, knowing the location would help a lot, would be an alternative, very effective, the pokémesh since the scanning is automatic and the new option of customized routes became much more viable.

add "lat" "lng" in line 194 and line 201 in telegrampage.xaml.cs

```
private void PokemonCaught(PokemonId pokemon, int cp, double iv, string profileName, string botNick,
            double level, PokemonMove? move1, PokemonMove? move2)
        {
            if ((!_tlgrmSettings.AutoReportSelectedPokemon || !_tlgrmSettings.AutoReportPokemon.Contains(pokemon)) &&
                (cp <= _tlgrmSettings.ReportAllPokemonsAboveCp || _tlgrmSettings.ReportAllPokemonsAboveCp <= 0))
                return;
            string messageToSend =
                $"[{botNick}]({profileName}) got {pokemon}! CP:{cp}, Iv:{iv.ToN1()}, Level:{level.ToN1()}, Move 1: {move1}, Move 2: {move2}";
            foreach (var owner in _tlgrmSettings.Owners.Where(x => x.ChatId != 0))
            {
                TlgrmBot.SendToTelegram(messageToSend, owner.ChatId);
            }
        }
```
add variable "lat" e "lng" in TelegramPokemonCaughtEvent.cs who believe that can be obtained from NewMapObject.cs

Please add it!

**Comment by Lunat1q** [comment]
see no point to do so. U can't do a shit with that info.

**Comment by leozinxd** [comment]
Coordinated information would assist me in manual capture pokemon, as I said an alternative to "radar" as pokémesh, I believe it would be something interesting. =\
