### ISSUE TITLE
Request functionality

### ISSUE THREAD

**Issue by dexxlab** [Lunat1q/Catchem-PoGo#1125]
Hi,

Great bot, the best for me ...
Just a question, is it possible for you to implement an export of all pokemon stats (IV/Moves/CP/HP, etc)?

Thank you so much and continue the great job !!!

**Comment by Lunat1q** [comment]
there is a dumper.

**Comment by dexxlab** [comment]
Ok thanks
Where can I found the dumper and an you tell me how it works ?
