### ISSUE TITLE
[Problem] Pokestops

### ISSUE THREAD

**Issue by Kiidtyga92** [Lunat1q/Catchem-PoGo#1127]
the bot collects no Pokestops
i hope u can help me :/

i have the newest version
p.S. sry for my bad english but i'm using Google Translate, my english is very very bad :/

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/ORsLypV.png)

**Comment by kingsley7601** [comment]
try checking if loot pokestops is checked

**Comment by Kiidtyga92** [comment]
oh yeah xD
i didn't see this option, thanks for the help :) now it works *thumbs up for this nice bot*
