### ISSUE TITLE
[Request] PKMN info

### ISSUE THREAD

**Issue by xTeddiusx** [Lunat1q/Catchem-PoGo#113]
Is it possible at Information tab show max capable CP and LvL with the other info (CP - IV) of every pkmn?

**Comment by Bay101** [comment]
Although Possible it is not needed as this is shown in the inventory tab

**Comment by xTeddiusx** [comment]
i dont think that u can see max possible CP and LVL of each pkmn in the info tab. Correct me if i am wrong pls

**Comment by Lunat1q** [comment]
it takes pretty much place to show, but i'll think about it.
