### ISSUE TITLE
[Suggestion] Individual Values (IV) - three hidden stats ranged information

### ISSUE THREAD

**Issue by TiksTriks** [Lunat1q/Catchem-PoGo#1130]
Hello!

Is possible to include the feature of including each pokemon IV three hidden stats information, or Individual Values (IV), ranged from 0 to 15 ?

**Explanation of what is IV's (for those that don't know what is):**
The IV's are hidden stats that affect how strong your Pokemon is in Gym Battles, beyond the Pokemon's CP rating, which the game shows you:
    - Attack
    - Defense
    - Stamina

Beyond Pokemon species base stats, each individual Pokemon has its own set of hidden values that affect its potential for Attack, Defense, and Stamina. These are called Individual Values, or IVs, and range from 0 to 15.

Thank you, 
Best regards

PS: PLEASE KEEP YOUR EXTRAORDINARY GOOD WORK!!

**Comment by petoe93** [comment]
isn't it enough too see the percentage of the IV's???

**Comment by Lunat1q** [comment]
Not going to do this.

**Comment by TiksTriks** [comment]
Hi,

Thank you for reply!

**Comment by TiksTriks** [comment]
Hello friend,

I want to thank you for the IV's ranged hidden stats now available :)
It gives us a clear ideia on selecting the best poke to evolve, keep or transfer by his attack or defense potencial !

Keep the good woork! :+1: 
Best regards.
