### ISSUE TITLE
Just a few suggestions about Speed and some doubts.

### ISSUE THREAD

**Issue by gholke** [Lunat1q/Catchem-PoGo#1131]
I like the Bot just making some suggestions, to make it better and much cool!
When the Bot is walking and will turn a corner or make a turn, It Could slow down, _do not know if you already have this functionality_.
When the bot is walking not change 9km/h to 20 instantly, _I do not know if he does not do that_.
But sometimes When I'm looking at him, he it changes instantaneous speed, it would be interesting to put a speedometer showing the bot's speed.
That would be really cool! hahahaha.

**Comment by JeanRolszt** [comment]
And maybe show the current speed?

**Comment by kingkai808** [comment]
or gradual increasing speed. because it looks like someone is doing a 100m dash going from 2 kph to 14 kph in 0 seconds lol.

**Comment by gholke** [comment]
Yes show the current speed...
If possible add a checkbox input to show or not to show pokestops overdrafts, to make it easier to set up the route, It would help a lot When put waypoints.
And show the area of reach of the bot, when creating the route, see if it will take pokestop or will not.
Sorry my english but I use translate.google, my keyboard sucks too.

**Comment by Lunat1q** [comment]
useless, will not do such a thing.
