### ISSUE TITLE
Create Route With PokeStops???

### ISSUE THREAD

**Issue by NaimRio** [Lunat1q/Catchem-PoGo#1132]
Hello!

First I want to congratulate the team of developers for the excellent work it has been doing and to further improve this already excellent application.

I wonder if you could include the PokeStops within the create route map?
This would help a lot in creating more efficient routes and more "human" because of knowing where streets go and where will be the return to the beginning.

Thank you for attention.

Em Português

Ola!

Primeiramente quero parabenizar a equipe de desenvolvedores pelo excelente trabalho que vem fazendo e melhorando ainda mais esse já excelente aplicativo.

Gostaria de saber se vocês poderiam incluir os PokeStops dentro do mapa do criador de rota? 
Isso ajudaria muito na criação de rotas mais eficientes e mais "humanas" devido a saber em que ruas passar e aonde vai ser o retorno para o início.

Muito obrigado pela atenção.

**Comment by animek06** [comment]
Live help at Discord Channel:
https://discord.gg/6z5AMX5

Join Us!!
