### ISSUE TITLE
I cant get items

### ISSUE THREAD

**Issue by mexpsm** [Lunat1q/Catchem-PoGo#1135]
Hi
i cant catch items on pokestops
![image](https://cloud.githubusercontent.com/assets/20864593/18149201/81fe2f5e-6fa4-11e6-8f79-f75f76a1d767.png)

This part of the log
[17:52:56] (EGG) Incubator status update: 0.16km left
[17:52:57] (INFO) Travelling to Pokestop: Third Church of Christ, Scientist (45m Away)
[17:53:41] (ATTENTION) ForceMove to 40.7648439008298 - -73.9730930328369 Started! Distance: 465.2m
[17:56:32] (ATTENTION) ForceMove Done!
[17:56:34] (INFO) Travelling to Pokestop: Memory of Jinny and Bob's View  (100m Away)
[17:57:34] (INFO) Travelling to Pokestop: The Great Lamp  (50m Away)
[17:58:03] (INFO) Travelling to Pokestop: Plaza Hotel (68m Away)

Thanks

**Comment by Franssa89** [comment]
I'm having the same problem, but is only in one account the other two is Ok, getting all itens. My pokeballs finished and I can't get more.

**Comment by Franssa89** [comment]
I solved the problem, just delete all the account and make new profiles. Just do it and start again.

**Comment by franj62** [comment]
If you play with 3 bots at the same time, you're probably banned, unless you use a different IP.

**Comment by kingsley7601** [comment]
You have been soft ip banned they last from 15mins to 2hours

**Comment by alvarobasto** [comment]
See this issue

https://github.com/Lunat1q/Catchem-PoGo/issues/1127

**Comment by Franssa89** [comment]
I use 3 acc at the same time sometimes, and not banned. But most of the time I use one acc per time. In this new atualization I see that the Pokemons is flee alot

**Comment by animek06** [comment]
Live help at Discord Channel:
https://discord.gg/6z5AMX5

Join Us!!

**Comment by Viking021** [comment]
look if you mark loot pokestop on settings

**Comment by tonylim89** [comment]
Loot is on, normally solved if bot is restarted. Have the same issue and it goes on infinitely. Status of bot is idle when it happens
