### ISSUE TITLE
Badauthentication problem

### ISSUE THREAD

**Issue by andyloup** [Lunat1q/Catchem-PoGo#1136]
i m trying to start a bot where I m  from and not from the starting NY area and the bot work for 2 seconds then it stop and spam badauthentication and captcharequired ... help me please

**Comment by animek06** [comment]
Live help at Discord Channel:
https://discord.gg/6z5AMX5

Join Us!!

**Comment by Lunat1q** [comment]
Log in with your phone and try to play for some minutes.
