### ISSUE TITLE
Fix Please

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#114]
1) make random values ​​pause after catching Pokémon . From min to max value .
2 ) a constantly program crash . Please Fix the problem.
3 ) lags while setting the coordinates. often cleaned dot or a comma. 
looks like that (345435345345 -534534652322 )
4 ) the ability to please , Minimize to tray
5 ) implement the offline account after a certain number of hours . Adjustable timeout , and number of hours . To be able to turn the boat , turn the system tray and forget for a while .
6 ) very long time lvl up

**Comment by xTeddiusx** [comment]
6 ) very long time lvl up.....
 is a matter of xp /hour ...traveling speed and number of pkms and pokestops in area

**Comment by Lunat1q** [comment]
check roadmap in discord before posting issue.
