### ISSUE TITLE
Custom Route Indicate Egg Status Update Every Second

### ISSUE THREAD

**Issue by Yolo1234567890123** [Lunat1q/Catchem-PoGo#1141]
Hi i think there an issue with egg status update for my custom route. It will update the status of the egg every second. Thanks for looking into this matter. Also why the bot does not follow the custom route at all.

![image](https://cloud.githubusercontent.com/assets/21317541/18153505/87299f0e-7030-11e6-9a40-9b8cc08796b3.png)

**Comment by Prolesious** [comment]
did you clarify a start point ?  or all way points?
