### ISSUE TITLE
mapzen api Key is empty even after pasted key 

### ISSUE THREAD

**Issue by silencer13ruiz** [Lunat1q/Catchem-PoGo#1144]
Went to site generated mapzen elveation key pasted it to catchem bot but still get (mapzen elveation api Key is empty)

Checked (use mapzen elveation API )

Changed routing service to (mapzenValhalla)

And pasted key in mapzen elveation spot then saved it 

Is there something I'm doing wrong any help is much appreciated thank you in advance

**Comment by WsTs** [comment]
Mine works fine, have u posted whole sentence?

**Comment by Lunat1q** [comment]
There is 2 mapzen Api keys, Elevation AND Valhalla (routing) consider review your settings.
