### ISSUE TITLE
only very few pokestops in area

### ISSUE THREAD

**Issue by stevenphen** [Lunat1q/Catchem-PoGo#1145]
i dont why it appear very random, sometimes other profile bot appear many pokestops, but this profile very few pokestops. any cause of that? so it just going in that 4 pokestop over and over
![screenshot 2016-09-01 10 31 08](https://cloud.githubusercontent.com/assets/21276845/18154497/64419a38-702f-11e6-8373-9844ad8bee15.png)

**Comment by Lunat1q** [comment]
what your farm routie? Discovery/Normal/Custom route?

**Comment by stevenphen** [comment]
Normal one, sometimes discovery. how bout u add feature like scan pokestop in XX km radius or in my radius, and scan pokemon is usefull too. 
So we can know where headed next to use force move *if possible

**Comment by stevenphen** [comment]
now come to here
![screenshot 2016-09-01 14 25 43](https://cloud.githubusercontent.com/assets/21276845/18158852/0fe73a1c-7050-11e6-82b5-0aeb6b42b613.png)

**Comment by Matdream** [comment]
Hello, 
I've the same problem...

**Comment by Lunat1q** [comment]
ip ban. case closed.
