### ISSUE TITLE
Help with setup :c

### ISSUE THREAD

**Issue by akiramses** [Lunat1q/Catchem-PoGo#1151]
![sin titulo](https://cloud.githubusercontent.com/assets/21349232/18156297/e322a2e8-6fda-11e6-8b46-e40e59375e1e.png)

cause problems if I put 0.85 plis help

**Comment by wagas** [comment]
Pokeballs 120
Potions 100
Revives 60
Berries 30
Total of 310... if you put .85 there it means it will recycle at 85% of your storage 
the total of your storage is 350 so 85% of it is only 297.5 =)

**Comment by akiramses** [comment]
![image](https://cloud.githubusercontent.com/assets/21349232/18156666/899db6ce-6fdd-11e6-88ad-8614ed3fb16f.png)

look at that happens when I put 0.85

**Comment by wagas** [comment]
at .85 it will recycle at 297 if your above it.. it will not recycle... the total of your items is not <= to the % of your recycle.. did you get the point?

**Comment by wagas** [comment]
if you want that to run smoothly put 1.00 so it will recycle at max

**Comment by Lunat1q** [comment]
Exactly the opposite, if you have less then 85% of inventory filled - it will not try to recycle case of that.
