### ISSUE TITLE
some adds :)

### ISSUE THREAD

**Issue by angelotrinario** [Lunat1q/Catchem-PoGo#1155]
Hello , first I wanted to congratulate you for the great work done , soon I will be able make a donation because I think you have well deserved , I apologize for my English

I wonder if it is possible to add a filter for the Pokemon with an IV lower than the established (eg 50 or 60 % ) are automatically rejected?

you can also add the option to display the eggs ( to know what these incubating )

also not possible if you could add a manual pokesniper work with current snipe pages ( as hackemon for example)

 in advance thank you very much and I reiterate my congratulations for the tremendous work done

**Comment by Lunat1q** [comment]
snipe - no, hell no, 100% ban.
sorry all actions with transfer - only via maintence, don't wanna call transfer routine after every poke
