### ISSUE TITLE
No usable Pokestops found

### ISSUE THREAD

**Issue by nwchong** [Lunat1q/Catchem-PoGo#1156]
Hi,

I keep getting the message below and the bot won't start. I am not using any custom routing. Please help.
![catchem_bug_1](https://cloud.githubusercontent.com/assets/21465279/18158620/02437f86-7057-11e6-8fb3-139a6ca74327.png)

Thanks.

**Comment by stevenphen** [comment]
i got this too. same problem here

**Comment by sapdkeybinder** [comment]
restart router /IP-Ban

**Comment by nwchong** [comment]
i still getting this message even though i changed multiple IP address (went to different wifi hotspot to run the bot). Any idea? It doesn't seem like it is an IP banning issue.

Thanks.
