### ISSUE TITLE
[Issue - Not Solved] api error before egg hatching still continue

### ISSUE THREAD

**Issue by kadirboz** [Lunat1q/Catchem-PoGo#1157]
hi,
firstly thanks for this great work. now i get api error before egg hatching like this.
![ekran alintisi](https://cloud.githubusercontent.com/assets/21368679/18140440/359f7270-6fbe-11e6-82f2-eb114b76e3ae.PNG)

and i think writing pokemon's attack power in pokemon's info popup, it will be awesome. like this;
![adsiz](https://cloud.githubusercontent.com/assets/21368679/18140527/a0dc0f4e-6fbe-11e6-8be5-8c8ab3239a0e.png)

thanks for everything.
regards

edit:
it will be array in code.
```
attackmoves = array(
'tackle' => 10,
'bite' => 6,
'earthquake' => 100,
);
```

like this. it doesnt need server-side. every moveset is same attack power. it will be easy for you.

Please not close this time.

**Comment by Lunat1q** [comment]
Every moveset is not same attack power, it differ from pokemon-to-pokemon.
Can't fix that egg issue now, can't catch the exact error.

**Comment by kadirboz** [comment]
i mean;
Acid is 10
Bite is 6
Bubble is 25
Bug Bite is 5
Bullet Punch is 10
Confusion is 15
Cut is 12
Dragon Breath is 6
Ember is 10

like this. every moveset is fixed(constant). all moveset will be collect in one array. and then pokemon has which moveset will get in array.

its easily i think.
thanks

**Comment by Lunat1q** [comment]
Ok, found the way to do it :) thx, hopefully will publish it in next release.

**Comment by kadirboz** [comment]
u r the best :)
