### ISSUE TITLE
Forcemove stops at first pokemon or pokestop

### ISSUE THREAD

**Issue by NeoNecris** [Lunat1q/Catchem-PoGo#1158]
Whenever I start a forcemove lets's say 300 meters away the forcemove stops and says "forcemove done" after catching a wild pokemon or looting a pokestop. It would be nice to continue the forcemove to actually get to the point I wanted.

**Comment by Lunat1q** [comment]
Just tested it, works just fine, check your settings, or wait for a new release, some chanes with movement will be there.
