### ISSUE TITLE
not looking for new Pokestop when leaving initial search range

### ISSUE THREAD

**Issue by NeoNecris** [Lunat1q/Catchem-PoGo#1160]
When starting the bot the pokestops are placed on the map but after a while of walking no new pokestops are retrieved when going to the edge of the initial poksestop search. 
Please look for new pokestop after a while.

**Comment by Lunat1q** [comment]
it does look for new pokestops every time. 
That can happen only if you are using non-Discovery pathing, and your bot is new max search distance.

**Comment by NeoNecris** [comment]
ok sorry, Discovery pathing was indeed checked off
