### ISSUE TITLE
mob bot routing problem

### ISSUE THREAD

**Issue by teemo63** [Lunat1q/Catchem-PoGo#1161]
Hello
I would help because I still have the problem of mob bot routing
I followed the wiki for mapzen
I tried without success even with google result always the same problem
I send you the image to see you
it prevents me from taking pokestop
Help me please

![2016-09-01_10-18-51](https://cloud.githubusercontent.com/assets/21278468/18160553/4b4a0e44-702e-11e6-8cc0-c9f02178a4cc.png)

![2016-09-01_10-19-27](https://cloud.githubusercontent.com/assets/21278468/18160554/4fb6cce2-702e-11e6-9ac4-a4aa8b322043.png)

**Comment by Lunat1q** [comment]
Can you read?
You selected MobBot ROUTING, and it's key is EMPTY, what do u expect?

**Comment by teemo63** [comment]
little one you pass me the link at least to find the API key

**Comment by Lunat1q** [comment]
MobBot api key is paid one.
Read wiki please for others.
