### ISSUE TITLE
[Minor Bug] Candy: xx/zz

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#1162]
Slight bug where the required amount of candy to evolve does not show when it doesn't have enough space to display. For example in picture below. should be 1077/400

<a href="http://imgur.com/fUkMk5v"><img src="http://i.imgur.com/fUkMk5v.png" title="source: imgur.com" /></a>

**Comment by Lunat1q** [comment]
ah lol :) sure will fix it.
