### ISSUE TITLE
Dont appear Pokestops..

### ISSUE THREAD

**Issue by kilado94** [Lunat1q/Catchem-PoGo#1164]
Hi there
Its always appear me this error everytime, +- 6 times per day..domt kn ow what to do
alredy uninstall and isntall, alredy changed proxys...
could someone help me to solve this problem..

![image](https://cloud.githubusercontent.com/assets/21318770/18165585/ed72e7e0-703d-11e6-835e-646d3e5bb476.png)

**Comment by AMontagu** [comment]
I have the same issue since this morning

**Comment by kilado94** [comment]
ye dont know what to do.-..

**Comment by Lunat1q** [comment]
Ip ban.
