### ISSUE TITLE
Telegram message not feedback, please help

### ISSUE THREAD

**Issue by M4xweLL** [Lunat1q/Catchem-PoGo#1169]
I followed all the steps, everything connects well but if I write something from the cell I can see in the window Catchem, but in my cell responses Catchem not see, I can have misconfigured?

Reegards

**Comment by Lunat1q** [comment]
trype /start again. Or you forgot to add owner. was discussed before!

**Comment by M4xweLL** [comment]
What i need to write in owner ?
