### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by tombeur** [Lunat1q/Catchem-PoGo#117]
hello, I followed the installation instructions to change the language in French I mi "en" in place of "in" but its not working if you could check in advance thank you

**Comment by Lunat1q** [comment]
reload client

**Comment by tombeur** [comment]
I myself "fr" in place of "en" revived the series softw desolé not changed or I see little wrong

![1capture](https://cloud.githubusercontent.com/assets/20915835/17697387/e1955efc-63b4-11e6-8e15-bc18bedb2eb5.JPG)
