### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1173]
Could you left justify the inventory pane? This would let another column of pokemon show when a window is sized larger in a lot of circumstances.  The same could probably occur if the 'MENU' section where redone to be all vertical (even combine STOP ALL/ START ALL if possible). For a given size window you would lose a slot to display a bot's name, but get more horizontal space.

Great work on the bot.. I hope I'm not pestering you too much!

**Comment by Lunat1q** [comment]
Can u take a screenshot about what you mean?

**Comment by Cowering** [comment]
![untitledmenu](https://cloud.githubusercontent.com/assets/9252175/18172590/4700d3aa-7023-11e6-975d-5a792e98891a.png)

**Comment by Lunat1q** [comment]
Sorry... didn't get what u mean

**Comment by RevGDFreeze** [comment]
Perhaps an ability to hide both the menu pane and the inventory pane, to allow more pokemon to be viewable in main window?

**Comment by petoe93** [comment]
or maybe he wants the menu & inventory tab to be slimmed so the pokemon tab displays more pokemon in a single row, who knows..

**Comment by kertiek** [comment]
this is what he wants.

![4700d3aa-7023-11e6-975d-5a792e98891a](https://cloud.githubusercontent.com/assets/21158056/18189258/924e948e-708f-11e6-94b1-983a065d23ac.png)

**Comment by Lunat1q** [comment]
ehm, nope, i'm not going to change this, it's enough how many Pokes are being displayed atm, it's up to 10 per row, depends on monitor size.
