### ISSUE TITLE
Success rate - Razberries and ultraballs.

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#1175]
Hi everyone.

I have one 22lvl bot. In the last releases it keeps using ultraballs to catch zubats, caterpies and bulbassaurs IV 10. It stopped using berries, and the catch chance has GREATLY decreased in general. It miss a lot of pokeballs to catch starter pokemons, and uses all my ultra and greatballs. 
I leave all configs as default. Has anyone sufering from this same "problem"?

![image](https://cloud.githubusercontent.com/assets/21060440/18169187/4b69873c-702f-11e6-8c52-213058517008.png)

I know that we can adjust % to throw those balls, but, is this normal now? Those freak little monsters from start being so hard to catch? I feel like Ash just after pallet town trying to catch a pidgey. Altough im lvl 22 already 0.o

UPDATE:

![image](https://cloud.githubusercontent.com/assets/21060440/18169358/29033f48-7030-11e6-8619-db78d2e8123c.png)

That mudafuka just throw a GreatBall on a pinsir 37,37%. And i TOLD HIM to only throw those or 20% or less chance!!!

![image](https://cloud.githubusercontent.com/assets/21060440/18169393/53fe5a16-7030-11e6-9593-d69425d6a472.png)

Ty

**Comment by WsTs** [comment]
u should use 0.20 instead of 0,20 lols, mine working fine all along

**Comment by Lunat1q** [comment]
it shouldn't matter actually.

**Comment by HernestoSanchez** [comment]
In Config it is 0.20. It just show 0,2 in UI. Already changed some settings to higher catch rates, use better balls on a real low success rate, but, it still missing a lot. It appears that all pokemons trained a lot and are now fleeing from all the trainers in the area!! Seriously, the catch rate of all pokemon are very low. Maybe it´s some change in server side.

![image](https://cloud.githubusercontent.com/assets/21060440/18170395/92191026-7034-11e6-801e-b4211d053c09.png)

**Comment by Initiols** [comment]
Because even below you have a IV% for the great ball...
For example that Pinsir was IV 88%, which explain why he used a great ball!

**Comment by HernestoSanchez** [comment]
Sup dude. Yeah, already changed that too (IV level). I´m running some tests after changing all configs. Let's see what we got.

**Comment by HernestoSanchez** [comment]
HI everybody!

After changing a LOT of the default configs, The bot is now running like a.... BOT. It seems the default config made the bot more human than myself 0.o. So, Im closing this thread!

Thanks all!
