### ISSUE TITLE
The Bot is not respecting the amount of duplicate Pokemon (Eevee)

### ISSUE THREAD

**Issue by igorpalma** [Lunat1q/Catchem-PoGo#1178]
Hello,

The Bot is not respecting the amount of duplicate Pokemon with Eevee.
He is transferring all my Eevees.

Thanks!

**Comment by guiguigui222** [comment]
Same for the jynx :/

**Comment by jeriko88** [comment]
I noticed that the values ​​of the inside of the configuration file transfer commands are given to the original every time you start the program.

**Comment by wagas** [comment]
Better check your settings on
Keep min CP
Keep min Dup
Keep min IV%

**Comment by igorpalma** [comment]
**"KeepMinCp": 1250,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 4,**

**_The other Pokemons are being saved
Just I noticed the problem with eevee_**

**Comment by igorpalma** [comment]
**I found the problem
In fact there is a separate configuration for each pokemon that ignores the interface settings**



>"PokemonsTransferFilter": {
>"Eevee": {
>"KeepMinCp": 1500,
> "KeepMinIvPercentage": 98.0,
>"KeepMinDuplicatePokemon": 1
>}

**Comment by Lunat1q** [comment]
i will add this to the UI as soon as i get the chance.
