### ISSUE TITLE
Telegram not feedback

### ISSUE THREAD

**Issue by M4xweLL** [Lunat1q/Catchem-PoGo#1180]
Sorry to reopen the ticket.
What configuration is needed in order to receive feedback from Catchem to the cel.

https://dl.dropboxusercontent.com/u/40731678/telegram.jpg

regards

**Comment by xPokemasterx** [comment]
i got same problem but they always close issues like this without helping.. 

im sorry for you

**Comment by Lunat1q** [comment]
type /start to the bot.

**Comment by M4xweLL** [comment]
I Type /start same isaue, i can see in catchen that recived message but in
my cell no recived feed back
