### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1181]
[08:01:57] Using MapzenAPI to obtian Altitude based on Longitude and Latitude.
[08:01:57] ERROR: Sequence contains no elements

is that a bug? I have a valid API key. Perhaps it means Mapzen does not have altitude info for my small city?

**Comment by berreta1987** [comment]
https://mapzen.com/developers/

**Comment by Lunat1q** [comment]
@Cowering even if mapzen fails - you will get randomized data for altitude, so relax:)
