### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by L7wy** [Lunat1q/Catchem-PoGo#1182]
can you add **order by candies** on the bottom of information tab?

**Comment by Lunat1q** [comment]
ehm... yeah... can do that

**Comment by velazqueca3** [comment]
Good morning, you can also add the option to choose which eggs incubate as the type of incubator but with active bot

**Comment by velazqueca3** [comment]
Good morning, you can also add the option-type hatching eggs as the type of incubator but with active bot
