### ISSUE TITLE
Difference between MaxCP and Possible CP ?

### ISSUE THREAD

**Issue by Initiols** [Lunat1q/Catchem-PoGo#1183]
I just don't understand this random number called Possible CP...

**Comment by stark93** [comment]
I think Possible CP is the maximum CP the same pokemon can reach with 100% IV and maximum level player

**Comment by Initiols** [comment]
No it's not, since it changes between pokemon's CP and IV. The maximum CP a pokemon can have, when fully leveled up, is the "MaxCP" value

**Comment by Initiols** [comment]
(I guess)

**Comment by Lunat1q** [comment]
Possible CP = Max CP at level 40

**Comment by Initiols** [comment]
thanks
