### ISSUE TITLE
Decrease ban chance + cool feature

### ISSUE THREAD

**Issue by VandRalaus** [Lunat1q/Catchem-PoGo#1185]
Hello, I love your bot and all, but can you please add a function to make it stand in 1 spot and catch pokemons that appear? this really helps at nests / to make it look more real (you take breaks in real life you know)

**Comment by Mpako6ec** [comment]
+1 i think it will be so cool

**Comment by agreda** [comment]
+1

**Comment by poetawd** [comment]
+ 1   !!!!

**Comment by Lunat1q** [comment]
set the location. set speed to 0.0001 - enjoy.
