### ISSUE TITLE
this is a mistake ?

### ISSUE THREAD

**Issue by Raafaax** [Lunat1q/Catchem-PoGo#1186]
my giving this so he ta working for now but is showing that there u have a video explaining step by certinho pass as I set up the best you have pass me there is be possible thanks.

http://prntscr.com/cczbx8

**Comment by ArchangelBr** [comment]
Tá dificil de entender, @Raafaax ! Você gostaria de um passo a passo pra não dar esta mensagem ou de como pegar a chave do MobBot ?
