### ISSUE TITLE
sniper function 

### ISSUE THREAD

**Issue by VikingDestructor** [Lunat1q/Catchem-PoGo#1187]
you could integrate pokesniper function in the console or any other place

**Comment by wagas** [comment]
@Lunat1q answered this many times. i guess the answer will still be no.

**Comment by ArchangelBr** [comment]
High chance of ban!

**Comment by Cryptologism** [comment]
the answer still no.. Sniper could make banned and i already ask this thing around weeks ago.. still same big no no
