### ISSUE TITLE
[help] How many bots per one API Key?

### ISSUE THREAD

**Issue by kaktusisko** [Lunat1q/Catchem-PoGo#1188]
As in the subject...
How many bots can I run under one API Key (Google maps, Mapzen Elevation)?

**Comment by berreta1987** [comment]
one by one

**Comment by un4m** [comment]
running 10 without issues...

**Comment by Cryptologism** [comment]
Its better to run 1 bot per 1 api and 1 proxy if you have it... 
I just change 1 api key for 1 bot last night,but before this always get softbanned and ip banned... owh also dont pick the same place to farm.. find others different place.. it better to far aways from each other of bots... Thats if you want to bot more than 1 bot at a time...

**Comment by kaktusisko** [comment]
no info in wiki
@un4m I have issues with 2 bots running under one API Key, sometimes.
(Not always get routing from Google or altitude form Mapzen.)
