### ISSUE TITLE
Add features to transfers ?

### ISSUE THREAD

**Issue by Yassnichou** [Lunat1q/Catchem-PoGo#1189]
Hey, it's would be cool if u can add more features to transfers, for example the bot can transfer only Pidgeys or Rattatas, it can make u take the exp without having to transfer them manualy (since there's some people like me who transfers their Pokemons manualy) since we don't like the auto transfer system for IV and CP issues.
But it would be cool if we can transfer automaticly some specific pokemons just for the extra exp they give instead of activating the "Not to catch"

**Comment by Lunat1q** [comment]
those IV and CP issues was fixed in latest.
