### ISSUE TITLE
[Idea][Ban Issue] Another way to EASILY avoid bans !

### ISSUE THREAD

**Issue by poetawd** [Lunat1q/Catchem-PoGo#1190]
I got banned again... using the bot 6 hours a day, only 1 per IP.... etc...

I was thinking how is Niantic aware that I am using a bot !

This is a suggestion that can be made with a FEW lines of code. The problem is that when the bot is stopped, it will save the spot that it is in that exact moment. When the bot is resumed, the start location is that EXACT SAME LOCATION !

In a real life situation, what are the odds for that to happen ? 

My suggestion is to add a random few meters from the stop location when the bot is started... OR ... add another option that is called START LOCATION that is not changed by the last know location from the bot.

This is a feature that will add more security to the bot ! Since is very easy for Niantic to detect who is using the bot just checking those locations....

**Comment by NeiPCs** [comment]
First of all, need to know the reason of your ban.
This propably is not the reason of your ban, but a lot of other things.
speed, catch pokemons per hour, pokestops per hour, IP exclusive to local internet service and not 3/4G providers, and so on...

**Comment by wagas** [comment]
what do you mean by 1 per IP? are you using proxy to open the other accounts? im still trying to figure on how niantics ban players.. already 4days of botting with hard core sniping and still my account was active, i tried botting 2 accounts and using proxy but with in the 3rd day both accounts were banned..
![hahaha](https://cloud.githubusercontent.com/assets/21025553/18178165/e580b464-70af-11e6-8d64-9a9f1e256874.png)

**Comment by Cryptologism** [comment]
Ermmm actually there is no solution or real solution for banned thinggy here dude... It was random... as long as they find some error or mybe heart feeling they gonna mark on that id or player or maybe more the ip... Theres too much to make connectin to each other about your banned.. Im sorry for that dude...
Im use this but limit mybe 6-7 hours per day only then logging back again at same time at same place.. not to fast,not use sniping,not use proxy... simple as that...
so far im still can use those acc without no ban... 

**Owh mybe you change repeatly the device that u use to log in to play pokemongo**

**Comment by Lunat1q** [comment]
When bot is resumed - he randomize it's location. Just letting you know. i did this like... a week ago.
