### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#1191]
I add an secound account in the Bot, give him settings and want to play the bot load all infos and than i get the Massage" [19:41:16] (ATTENTION) Current Operation was canceled.**

Give him a another google API.

I play only one Account! the Scound is via VPN online, dont know why this happen?!

**Comment by Lunat1q** [comment]
Try the latest release please ( will be posted in 1 hour), looks like you have no custom route selected.
