### ISSUE TITLE
Enable use of lucky egg whenever

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#1192]
Would be cool to add a feature to just use a lucky egg whenever you'd want to. Its much less suspicious to niantic when you just use an egg like a real player would. I use an egg when I'm on a catching spree and would get about 35k xp with one egg using official app.

**Comment by maknado** [comment]
It exists as elvoluir over 90 pokes
Starts Evolution Poke restarts app pokemongo
Already goes to another poke starts evolution restart the app pokemongo
and so on!

Since the app starts in 5 ~ 10 seconds
I do this!

I do it for me! And works

**Comment by Cryptologism** [comment]
Actually i cannot understand well what are you saying dude @maknado ..
Could you elaborate that more spesifically?..?

**Comment by kingkai808** [comment]
anyone have the link # to the duplicate thread? i'd like to know if this will be implemented in future update?

**Comment by kingkai808** [comment]
and dude i cannot understand one word you just said @maknado
