### ISSUE TITLE
catch flee

### ISSUE THREAD

**Issue by dreamwalker1232** [Lunat1q/Catchem-PoGo#12]
apparently all pokemons which i try to catch keep fleeing but the bot collects items and exp from pokestop , mind telling me why i cant catch any pokemons ? its not a ip ban cuz i am using a proxy and on the same proxy i am using another acc which works fine

**Comment by Lunat1q** [comment]
so, 1 account works fine, 2nd account don't?

**Comment by mattxx3** [comment]
Same, people say you get it from sniping. I believe they changed their soft ban system to prevent the unbanning  from spinning the pokestop 40 times.   However this is just speculatio.
