### ISSUE TITLE
Discovering Pathing & Human Phating does not work

### ISSUE THREAD

**Issue by kirimkefadil** [Lunat1q/Catchem-PoGo#120]
Discovering Pathing & Human Phating does not work if im using forcemove. it will move like fly above building
![untitled-1](https://cloud.githubusercontent.com/assets/21058672/17698996/723afab0-63e8-11e6-97c7-d01d22cf3887.jpg)

**Comment by Lunat1q** [comment]
route server is dead  :/ we killed it

**Comment by HernestoSanchez** [comment]
Just to state. Don´t work without forcemove either. This is since 1.3.4.0.

By the way. Thanks for the great job. Using for the past 2 days and already saw a lot of improvements.

**Comment by Ukkime** [comment]
Lunat1q, why do you kill route server? maybe we can do somthing about this

**Comment by Lunat1q** [comment]
fixed
