### ISSUE TITLE
Is it possible... pokestop update.. or pokestop search..

### ISSUE THREAD

**Issue by tenderbeyr** [Lunat1q/Catchem-PoGo#1204]
-Is it possible to update pokestops with lure every 15/30mins or so?
this is helpful when monitoring bots so that we can see where to place bots with lure to those who farm to lures..
-when out of lures or a little too bit far from with lures, can you make bots search or go to it to farm.
like an option or check box.
-also when i try to farm on a lured pokestops, my settings are 50-75 max distance / 5 max spawn location offset / min 1 to max 4 walking speed / delay pokestop at 330000ms. can you make a simple tick box so that if manually observing bot on its travel, and a lured pokestop appear or encounter, its easier to change the settings to standby or stop. i think it can help not to get notice being a bot. 

thanks

**Comment by Lunat1q** [comment]
it's planned, but not done yet.

**Comment by tenderbeyr** [comment]
good to hear, thanks and keep it up :D
