### ISSUE TITLE
pokestop bug v1.4.9.4 ?

### ISSUE THREAD

**Issue by dansafran** [Lunat1q/Catchem-PoGo#1207]
pokestop bug v1.4.9.4 ?
![capture s](https://cloud.githubusercontent.com/assets/14239418/18186957/2968180c-70a6-11e6-8555-c5a66cc7a304.PNG)
![capture](https://cloud.githubusercontent.com/assets/14239418/18186955/295c7f60-70a6-11e6-81c8-40682ff30238.PNG)
![sa](https://cloud.githubusercontent.com/assets/14239418/18186956/296726d6-70a6-11e6-89ca-28963af50a02.PNG)

**Comment by cassone200** [comment]
Google Translate : 
Also I have the same problem , UNIVA version Running here STILL And a 1.4.7.0

**Comment by stonedsonic** [comment]
im not getting xp or items, but still able to catch pokemon.

**Comment by Bay101** [comment]
Mobbot routing now needs an API key to be entered and purchased, Please use another provider if you do not have a key.

**Comment by stonedsonic** [comment]
figured out my problem, the loot poke stop option got UN-ticked
