### ISSUE TITLE
Google MAP and Routing Buggy?

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#1208]
Hey pals!

Is anyone having problem with googlemaps and routing today? I mean, several times i can´t load maps, or use route. The other mapping are alright, but google is unstable. Dunno if is something with my connection.

Thanks for your feedback!!!

**Comment by kaktusisko** [comment]
sometimes API's don't work.

**Comment by Lunat1q** [comment]
Google/connection/ufo... you know, there can be lots of resons for that, can't determine which one is most valid without any logs/investigation.
