### ISSUE TITLE
[suggestion] subsort order

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1211]
when sorting pokemon by name or #, could the bot also sort by CP or IV? It would make batch transfers easier.

**Comment by franj62** [comment]
You can sort by CPU or IV, look at it well.

**Comment by ricardoks** [comment]
He means sorting by # (or name), and then sort those of the same species based on their CP/IV (just like in the app itself)

**Comment by Lunat1q** [comment]
hm, i'll think about that, may be i'll make those sorting at tongle buttons

**Comment by Cowering** [comment]
seems you got it!
