### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by eduardoedson** [Lunat1q/Catchem-PoGo#1212]
can you add a buttom to force remove duplicates?

**Comment by franj62** [comment]
Click the button at player tab

**Comment by eduardoedson** [comment]
Where? Can show a print?

**Comment by franj62** [comment]
I advise you to read the releases [https://github.com/Lunat1q/Catchem-PoGo/releases/tag/v1.4.9.3](url)

**Comment by eduardoedson** [comment]
Manual maintence sequence, click the button at player tab to start this sequence (bot will do it as soon as he became ready) ♻️

This?

Not only works in the backpack?
