### ISSUE TITLE
why

### ISSUE THREAD

**Issue by tenderbeyr** [Lunat1q/Catchem-PoGo#1216]
I stucked myself in 1.4.9, and now i just use the latest release 1.4.9.4 coz of some cool updates.
just want to ask, why did the pokestops removed and not seen in the map while the bot is on.
only visible are the ones near the waypoint..

AND also, what does Possible CP means in "CP / Max CP / Possible CP"..
thanks

**Comment by brendoncwright** [comment]
To chime in exclusively on your secondary issue...
CP: Poke's current Combat Power
Max CP: The maximum CP you can power the poke up to at your current level
Possible CP: The maximum CP the poke can achieve at level 40

**Comment by tenderbeyr** [comment]
ic, so CP can maximize according to player level..

anyone knows the multiplier of CP when trying to evolve?

**Comment by brendoncwright** [comment]
Here's a handy calculator. 

http://pokemongohub.net/pokemon-go-evolution-calculator/

Also, I may submit a feature request for an estimated CP on evolution statistic :)
