### ISSUE TITLE
Can't see any pokepoint

### ISSUE THREAD

**Issue by negodogueto** [Lunat1q/Catchem-PoGo#122]
![untitled](https://cloud.githubusercontent.com/assets/21059234/17698998/a14e49dc-6394-11e6-913d-b1b7025a6102.png)
It was working normally then started to show that "there's no pokestop in your area" :(
What's wrong?

**Comment by Lunat1q** [comment]
=> Wiki

**Comment by negodogueto** [comment]
Ok I'm sorry
