### ISSUE TITLE
info about attacks of pokemon

### ISSUE THREAD

**Issue by kertiek** [Lunat1q/Catchem-PoGo#1221]
now u are showing the dps info of each attack, can u show the position in comparison of dps damage with all the other attacks, that the attack is?

lapras has for first attack frost breath 11.1 dps and ice shard 10.7 

since frost breath has more dps is (1) in the descendant list of dps and ice shard is (2)

so when it shows the every attack the name of the attack goes with **frost breath(1)** or **iceshard(2)** .. telling me that if i have a lapras with iceshard(2) even if i dont know when the other attack is .. i know that what i have is the second best ... i dont know if i can explain it right .. am high :D

**Comment by kertiek** [comment]
maybe this can even be a new filter por pokemons ...  one with high cp and 50-80% iv but with a (1) or (2) moves on each attack can still be a nice pokemon to have :O

**Comment by kertiek** [comment]
can u show also the type of attack?

http://www.ign.com/wikis/pokemon-go/Pokemon_Go_Pokemon_Type_Chart

**Comment by Lunat1q** [comment]
nope, use websites for that.
