### ISSUE TITLE
never transfer favorite pokemon

### ISSUE THREAD

**Issue by kertiek** [Lunat1q/Catchem-PoGo#1222]
now u can transfer any pokemon even if is favorited or not ... can u make it to transfer only non favorites pokemon? and show a message why u cant transfer them. :D

**Comment by kulkarni-ani** [comment]
I'd appreciate if that feature is added. It did transfer my 1500CP dragonite :|

**Comment by kertiek** [comment]
ye ... i have a lapras with low iv but really good attacks that i dont want to lose :D

**Comment by lonelies** [comment]
favorited pokemons won't be transfered. That's ninatics' default setting

**Comment by Lunat1q** [comment]
even on manual transfer... ok :/
