### ISSUE TITLE
No Pokeballs in the inventory!

### ISSUE THREAD

**Issue by kulkarni-ani** [Lunat1q/Catchem-PoGo#1224]
Hi,

Just updated this to latest 1.4.9.4 version. All Bots showing: (INFO) You have no pokeballs in your inventory, no more Pokemon can be caught!

How is this possible, just before upgrading it showed lots of pokeballs. Also, inventory of items seems a bit off, not all items are there in it.

**Comment by Krypsus** [comment]
Go through some pokestops and get many pokeballs, problem solved.

**Comment by kulkarni-ani** [comment]
Well, I force moved it to pokestops after several attempts, it started using pokestops.
Point here is, how did it magically used up all pokeballs from 2 accounts? I had keep minumum pokeballs set to 100, that still seems like a glitch to me! Still monitoring ahead.
