### ISSUE TITLE
Urgently need this feature in bot~~

### ISSUE THREAD

**Issue by DreamSo** [Lunat1q/Catchem-PoGo#1225]
When caught 1000 pokemon  or  caught 2000 pokestop  bot need to stop work,  if not  will softban~

or maby can Switch accounts by bot self~~that all

**Comment by miguelslemos** [comment]
Max Catch Per Hour in tab settings

**Comment by iAngelG** [comment]
It's there already. You set hourly limits and the bot will pause.

**Comment by DreamSo** [comment]
if set that,   XP so slow~~would like set 1000 pokemon and 2000 pokestop to stop~

**Comment by JinxGenius** [comment]
it's already there, dude
all four option in one place
