### ISSUE TITLE
[Feature] Telegram

### ISSUE THREAD

**Issue by miguelslemos** [Lunat1q/Catchem-PoGo#1227]
My suggestion 
to notify via telegram when bot level up,
add this info to _status command_: current exp and total exp to level up or percentage, current state of the bot and countdown timer during the pause routine if bot is stopped.

**Comment by M4xweLL** [comment]
Hello, miguelslemos, you can help to configurate telegram with catchem ?
Regards

**Comment by miguelslemos** [comment]
check the wiki https://github.com/Lunat1q/Catchem-PoGo/wiki/Telegram-setup

**Comment by M4xweLL** [comment]
I follow all steps and cant see feedback from catchem to my cell, but if i write some en my cell i can see in catchem.

**Comment by M4xweLL** [comment]
I worked! thanks anyway

**Comment by maknado** [comment]
Good idea, I would post it here now!
Inform the Level-up and hatched eggs!

**Comment by miguelslemos** [comment]
Thanks @Lunat1q some features that i suggested came on last release v1.5.0.0, could you add to your road map add percentage to level up in command /status

**Comment by Bay101** [comment]
Hatched eggs appear in Telegram as new pokemon

**Comment by OracleMaster14** [comment]
List of Transferred pokemon with CP and IV
