### ISSUE TITLE
[Suggest] Create poke radar from every BOT for snipe in the future.

### ISSUE THREAD

**Issue by jiyuan1202** [Lunat1q/Catchem-PoGo#1229]
[Suggest] 
You create poke radar from every BOT find for snipe in the future.
Maybe everybody can collect pokemon from his other BOT.

**Comment by lonelies** [comment]
sniping will not be implemented

**Comment by WsTs** [comment]
snipe is too dangerous for now, just Poke Radar should be enough so that we can see the pokemon through the map, however i believe this will increase the load to the server and more likely easy to get ban. I am not sure is there any other way around.
