### ISSUE TITLE
Bot not detecting pokemons nearby & Feature request on Telegram

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#1230]
[Bot not detecting pokemons nearby]
Latest bots seems not catching as much pokemons compared to previous versions. Not sure if Niantic changed spawn places but there were no recent update. And yes i'm sure the place i'm botting is a good spawning place, been botting the same place since started using your masterpiece. Sometimes it's not catching anything even after 5 minutes. Last time i'm getting 14k~18k/h in the area. Currently 3k~9k,i guess that mostly exp is from pokestop. Changed location still the same. 
Also, i'm not using "poke not to catch filter", using same setting as previous versions. 
"Catch Wild Poke" is checked.
Max catches/exp/star dust/pokestops, all are disabled. (Set to 0)

<a href="http://imgur.com/3W3SRBT"><img src="http://i.imgur.com/3W3SRBT.png" title="source: imgur.com" /></a>

[Feature Request on Telegram]
A command where we able to check specified pokemon.
For example," Top 1 Growlithe".
It will then report all the Growlithe's CP/IV that you have in your account.

**Comment by Shake1234** [comment]
me is the same thing

**Comment by lonelies** [comment]
Read the wiki. Cant find the setting that allow the bots to detect more pokemons
