### ISSUE TITLE
 APIFailureStrategy

### ISSUE THREAD

**Issue by soramachi** [Lunat1q/Catchem-PoGo#1231]
Just saw this 

[06:36:30] (ERROR) APIFailureStrategy (Exception): Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.

**Comment by JinxGenius** [comment]
I got this and this will crash catchem, any way work around it?

**Comment by Spk345** [comment]
This is due to unstable Internet connection.

**Comment by Charlier69** [comment]
Use an VPN or Proxy?

**Comment by Lunat1q** [comment]
it's not. investigating atm

**Comment by Lunat1q** [comment]
Did it happen on login? or during the run?

**Comment by Cryptologism** [comment]
I think yeah.. Unstable Internet connection...  Sometime im got this cuz using hotspot shield crack and my connection sometimes going break for moment...

**Comment by Spk345** [comment]
It most likely is just unstable Internet connection. Gym on discord gets disconnected every thirty mins. I've gotten it without a VPN or proxy. Local co-op Internet drops during day.

**Comment by Spk345** [comment]
It's during run, drop your connection, 1/3 bots will throw error. Already recreated this.

**Comment by Lunat1q** [comment]
Ok, looks like that happens when bad AuthToken supplied :/
Can happen during the lost connection, or other things, only 1 solution for this so far: relogin.
