### ISSUE TITLE
[Feature] - Bot Pause / Display Top 10

### ISSUE THREAD

**Issue by Ravys** [Lunat1q/Catchem-PoGo#1233]
Can we have a Bot "Pause" option then we can do the "Manual Maintenance" so that we wont have to wait the Bot to become ready?

Also an option to turn off the Top 10 Display?

**Comment by Ravys** [comment]
And also a feature for show info of "dust" :)

**Comment by Lunat1q** [comment]
http://i.imgur.com/k5q3zfG.png set to 0

**Comment by Lunat1q** [comment]
and no, no "pause" option for bot so far.
