### ISSUE TITLE
[suggest/request/issue/question]

### ISSUE THREAD

**Issue by wtxlight** [Lunat1q/Catchem-PoGo#1234]
1)incense on/off
2)poke ball/potion/revive control in details
3)on/off timer to start auto and stop auto
4)use item by double click on it
5)Eggs Tab showing the detail of hatching and total eggs

--------------------------------------------------
issue
1)only Eevee not keeping 2 while i set duplicate to 2
2)delay when opening since the last 3-4 version
3)still getting this error with new version
(ERROR) Niantic Servers unstable, throttling API Calls

-----------------------------------------------------
question
1)do the bot re-run after hit the max pokemon/pokestop per hour pause?

**Comment by Spk345** [comment]
#roadmap on discord.
