### ISSUE TITLE
Keep best potion

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#1235]
Can you add potion filter? 
Recycle potions and super potions and keep only hyper and up? Same with revive?

**Comment by Spk345** [comment]
Doesn't happen with pokeballs either.

**Comment by kingkai808** [comment]
ya great ball etc too would be nice

**Comment by Lunat1q** [comment]
https://github.com/Lunat1q/Catchem-PoGo/blob/master/PoGo.PokeMobBot.Logic/Tasks/RecycleItemsTask.cs
