### ISSUE TITLE
Rename Pokemon Based on IV?

### ISSUE THREAD

**Issue by cchmistake** [Lunat1q/Catchem-PoGo#1236]
Hi team,

Is it possible to rename all pokemon to their IV?

Lets say Pikachu has an 85% IV , will the system help to rename it to 85%?
Perhaps 80% IV above only the system will rename the pokemon.

Thanks

**Comment by devost02** [comment]
it alread has that function lad

**Comment by developnoop** [comment]
look into the settings tab. sounds like this: set rename pokemon to true and rename above iv to 1 (value between 0-100)
