### ISSUE TITLE
Device ID

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#124]
HI everyone!

Is it possible to use an iphone ID on Device Info?

Thanks! Great project by the way!!!

**Comment by JacksonTrue** [comment]
Сори, то что не в чужую тему пишу. Просто вижу, что тема моя тема уже закрыта. Я добавил информацию, которая возможно поможет решить вопрос по поводу краша программы https://github.com/Lunat1q/Catchem-PoGo/issues/121

**Comment by Lunat1q** [comment]
nope, it's not possible.
