### ISSUE TITLE
Renaming Easter eggs not work using bot?

### ISSUE THREAD

**Issue by vuetl** [Lunat1q/Catchem-PoGo#1242]
I renamed an Eevee into Rainer (wanting vaporeon), and when I evolved it, I got a Flareon with the name [Flareon]. Any suggestions in confirming this?

I tried this again and got a Vaporeon but name got reset to [Vaporeon].

![capture1 eevee](https://cloud.githubusercontent.com/assets/21701052/18194164/4c1c60b2-70a9-11e6-82b6-af042ad997e3.JPG)
![capture2 rename](https://cloud.githubusercontent.com/assets/21701052/18194165/4c2859d0-70a9-11e6-94b8-2d4d5204a0ec.JPG)
![capture3 vaporeon](https://cloud.githubusercontent.com/assets/21701052/18194167/4c3955a0-70a9-11e6-9a1f-2b7bd307fa57.JPG)
![capture4 info](https://cloud.githubusercontent.com/assets/21701052/18194166/4c367308-70a9-11e6-8523-14c229203424.JPG)

**Comment by JinxGenius** [comment]
didn't niantic said this method of evolving is no longer valid?

**Comment by vuetl** [comment]
Just tried it out on my Iphone (in-game) with my alternate account and got an Vaporeon with name still as Rainer.

**Comment by Cryptologism** [comment]
It already patch... I tried it also for the first time play... Not work... Huhuhu
