### ISSUE TITLE
[bug] bot after 10 hours crash

### ISSUE THREAD

**Issue by raulken78** [Lunat1q/Catchem-PoGo#1245]
Hi, If I leave the bot work for 10hours the notebook of course turn off the monitor, but the pc continue to work and the bot to run...

After this hours if I show the windows of catchem I see into log the start data of 10hours ago, the but try to restore 10hours of NO SCREEN into log tab and bot crash...

I hope my description is fine for repeat the problem.

So I think U must find a solution for continue to print into tab or reduce the log size before splash on log tab all the info

As always, thankyou

**Comment by Lunat1q** [comment]
didn't get what you mean... at all, please, post some screenshots.

**Comment by raulken78** [comment]
ok, I try:

21:00, bot start and all work fine I leave bot on Map & Console tab
21:05 screen of PC is off, but All pc continue to work and run
7:00(AM) I refresh my PC, screen is ON. I see on Map & Console tab info until 21:05. Bot try to show on Map & Console tab all work from 21:05 to 7:00am and it's freez and crash at end...

It's ok now?

**Comment by Cryptologism** [comment]
I think Sir,he mean to have somekind of log or detail that will display how longer the bot running and then when the bot stop unexpectedly,he also want to know why and what time that bot stop in a log or detail cmd or anything that can be recorded...

**Comment by Lunat1q** [comment]
if your PC was in the "sleep mode" it turns off the internet card... so... you know :)
Look at log files <b>Profiles/Logs</b>

**Comment by alanearl** [comment]
How about checking the windows events logs.
Also updating your dot NET Framework.

**Comment by raulken78** [comment]
only the screen is off, but the pc is on and all work!
I found all the log, 1 for each hours, all the night...
so it's only a problem if I reactivate the screen, but the bot work fine all night
