### ISSUE TITLE
Disable Buttons

### ISSUE THREAD

**Issue by KoopaTheTurtle** [Lunat1q/Catchem-PoGo#1246]
Would like to see 2 buttons/check boxes added.
1) Disable API's... If you dont put in API Key it spams the console Missing API Key
2) Disable Routing... if you dont use a Routing it spams Missing Routing

**Comment by Cryptologism** [comment]
Ermmm sound nice but i think too much button to tick and if made it... There tons of question from it... Hahahaha
Btw dude... Is that ok if we are not using those API.. Isnt that look abnorml if our char crossing the lake or walk through building just by to catch pokemon or pokestop?

**Comment by Lunat1q** [comment]
there is those checkboxes.
HumanPathing - uncheck it, and routing API will be disabled

**Comment by KoopaTheTurtle** [comment]
oki :D
