### ISSUE TITLE
Congratulations to all devs... 😊 

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#1248]
Personally i would like to thx you to sr lunatiq for.this awesome work and sir bay101 i think his name... 
Also not forget for all user cuz wiling to contribute idea,time and effort in order to make this thing real and more functiom eveyday...

Thx you guys and congratulations to all.. I would.love to see this everyday...
Better and better... Keep ggod work and of course i will support this till end.. But i think theres no end.. xD

**Comment by Lunat1q** [comment]
Thanks dude:)

**Comment by Bay101** [comment]
:smiley: Thanks @Cryptologism
