### ISSUE TITLE
[Suggestion] Quantity of pokeballs

### ISSUE THREAD

**Issue by WsTs** [Lunat1q/Catchem-PoGo#125]
Hi Lunat1q,

First of all i would like to thank you for the bot u made, it is so far the best bot i ever used.

However, can i suggest that for the section "pokeballs to keep", can u add an option to set the quantity of the pokeballs /greatball / ultraballs to keep?

Thank you very much.

**Comment by xTeddiusx** [comment]
I think that program recycle low quality balls every time.

**Comment by Lunat1q** [comment]
it's removing low grade pokeballs all the time, i see no reason to keep them
