### ISSUE TITLE
[bug] crash when using 'TEST PROXY'

### ISSUE THREAD

**Issue by siccolein** [Lunat1q/Catchem-PoGo#1251]
The app freezes and crashes when using the test proxy feature. In certain situations the freeze recovered after 1-2 minutes and giving the proxy test result.

**Comment by Cryptologism** [comment]
For me it works well... Yeah it loke hang for a while then that thing going back ok... No worries... About that crash mybe theres overload on loading or too heavyuser on your computer

**Comment by Lunat1q** [comment]
weird... should push it to another thread.

**Comment by Housy123** [comment]
For me the bot freezes when proxy is not reachable

**Comment by kaktusisko** [comment]
@Housy123 true

**Comment by Spk345** [comment]
No problems with my Proxy bot. No crashes for me. /:

**Comment by Housy123** [comment]
@Spk345 
This only happens to Proxies that are either very very slow or down

**Comment by Spk345** [comment]
This is fixed in new release. When my actual internet went down at work, my proxy said it failed, but Catchem did not crash. If you continue to deal with these issues, please visit us on discord. Thank you!
