### ISSUE TITLE
Why why i only have This 5 or 6 pokestop 

### ISSUE THREAD

**Issue by gamelordhacker** [Lunat1q/Catchem-PoGo#1252]
![1](https://cloud.githubusercontent.com/assets/21278539/18198025/040b2e28-712d-11e6-872a-5ccd848bfe24.png)

Only 6 Pokestop over and over again.

**Comment by gamelordhacker** [comment]
up

**Comment by maxsofar** [comment]
Check max travel distance.

**Comment by Lunat1q** [comment]
It's normal, you just have this as optimal sequence. Since no human path is avaliable - that's what u will get. You can try to disable Discovery settings.

**Comment by gamelordhacker** [comment]
thanks
