### ISSUE TITLE
[suggestion] add a filter "keep min Lvl" to transfert duplicate Poke

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1254]

**Comment by Lunat1q** [comment]
IV and CP is enough

**Comment by GandalfLeRouge** [comment]
cp isn't always a good filter, lvl is useful because if you lvl up the poke the cp could change a lot
for example : magikarp lvl 30 cp 225, lvl up Gyarados cp 2304 !!!
