### ISSUE TITLE
UI Suggestion !!

### ISSUE THREAD

**Issue by EdwinTyszczenko** [Lunat1q/Catchem-PoGo#1257]
First thanks a loT !!!

You could create a new list in poke option settings lists to add all poke that we want to transfer that exceeds the options set in the Settings tab?

Again thanks a lot.

**Comment by MarkoHess** [comment]
I currently transfered 3 scyther due to the not shown pokemontransferfilter in the config. The parts seem to be active right now, but are not shown in the UI.

**Comment by Lunat1q** [comment]
ehm... yeah sort of nice idea, will try to do it, if i'll find what it's possible

**Comment by kaku1237** [comment]
hi all

can you put some label on what kind or type of move ex. steelwing is metal then twister i think this is dragon type in pokego

best bot i have @Lunat1q can i share this to my friend many thanks

![capture](https://cloud.githubusercontent.com/assets/21098726/18275376/54bed1f4-7479-11e6-8a0b-673052a823f9.JPG)

**Comment by tyu366** [comment]
On the information tab, it takes a long time to wait.
I propose to mark several pokemon first.  Then user can transfer / favourite / unfavourite in batch.
The module then perform the action one by one with random waiting time to avoid soft banning.

**Comment by Spk345** [comment]
In newest release there is an extended version of transfer filter that does what you asked, you can individually add pokemon and select what you'd like to keep, if any.

@kaku1237 : So types of move? Okay, STAB is already applied by bot so damage is fairly accurate.

@tyu366 : You can select multiple pokemon in batch by either Ctrl+click or Shift+click. The bot does have randomised delays when doing these actions already.
