### ISSUE TITLE
Gyms as Pokestops

### ISSUE THREAD

**Issue by xTeddiusx** [Lunat1q/Catchem-PoGo#126]
Test it at two locations and was 100% happening. Gyms are marked in map as Pokestops too.
(Found the reason for an issue I post previously)

**Comment by oZacDo** [comment]
PokeGym and PokeStop are the same picture.

**Comment by xTeddiusx** [comment]
and have the same text in textbox too. Thats why i post it

**Comment by jaydee9296** [comment]
I saw this one too... I thought it was a Pokestop but it is a gym... :v

**Comment by bunthay** [comment]
usable pokestop help

**Comment by CDAGaming** [comment]
Fixed in Commit 0579572413e1f80933e5984e534a7b69539a137c
