### ISSUE TITLE
[suggestion] minor - include stab bonus in dps

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1260]

**Comment by Lunat1q** [comment]
don't have that info, is that so important?

**Comment by petoe93** [comment]
what is a stab bonus? 
and btw no, its not that important i think

**Comment by Spk345** [comment]
STAB is Same Type Attack Bonus. It means that if the pokemon and the move have the same type, it's stronger.

**Comment by petoe93** [comment]
thx, never stop learning ^^

**Comment by GandalfLeRouge** [comment]
the bonus is 25 %

**Comment by petoe93** [comment]
hmm then it could be useful though..
for example with 2 seadra, one has hydropump which has the stab bonus (90+25%), the other one with blizzard doesn't have stab so only 100..
it's just a small difference however..

**Comment by SweeTIPi** [comment]
I would like to see that but I think its less important than showing the IVs values. 
The correct rate of DPS (including the stab bonus) dismiss the necessity to show this, since stab dont change for every single pkm. Just a fast search and you know if will be stab or not.

**Comment by GandalfLeRouge** [comment]
sorry but you wrong, DPS is more important than IVs, a 100% Iv with bad DPS is very poor,
But if 2 pokemon have the same best attack, IV become important

**Comment by SweeTIPi** [comment]
Thats NOT what I said. Read again.
What I mean is if the correct DPS is there in panel, you dont NEED to include an stab sign.
I said: show IVs is more important than SEE A SIGN OF STAB, that you easily find searching. 
Did you get it?

**Comment by SweeTIPi** [comment]
Btw, I though that the stab was included in DPS already. It was misunderstanding(?) messages. Thats the reason for all this.
I surely agree with stab in DPS. Actually I think that must be included. Make diference.

**Comment by Lunat1q** [comment]
Stab added to the dps number
