### ISSUE TITLE
[Question] Failed with item settings

### ISSUE THREAD

**Issue by Krypsus** [Lunat1q/Catchem-PoGo#1262]
When you receive the message: 
"(ATTENTION) You have failed with item settings! You asked to keep it at 85,0 % clean,which is 297,5 items, and asked to keep 330 items at the same time, while you have 19 extra items like Lucky Eggs/Incubators/etc..."

What is the good configuration?

Thanks

**Comment by Next1306** [comment]
I'd say:

- 20~30 slot (depending from your level) for the extra items (lucky eggs, lures, incubators, etc.).
- 310~300 slot (based on the number you choose for extra items) for normal items (balls, revives and potions).
You now have 330 items: make the bot clean at 95% (so at 332.5 items) and you should be fine.

**Comment by Krypsus** [comment]
I have kept 30 slots for the extra items and 320 slots for normal items, making the bot clean at 92%.

Thanks for your help.

**Comment by Krypsus** [comment]
Testing the new configuration:
(ATTENTION) You have failed with item settings! You asked to keep it at 92,0 % clean,which is 322,0 items, and asked to keep 322 items at the same time, while you have 19 extra items like Lucky Eggs/Incubators/etc...

**Comment by Lunat1q** [comment]
322 + 19 = 341....
