### ISSUE TITLE
Businessman theft

### ISSUE THREAD

**Issue by oZacDo** [Lunat1q/Catchem-PoGo#1263]
Someone has taken over your programs do Sold.
Just want to tell you.
They change name to "GetGoBot".

Following is their website.
http://www.xf-wg.com/
![image](https://cloud.githubusercontent.com/assets/21005066/18202727/8f85f5a2-7144-11e6-8b4a-edd7f94ab847.png)

**Comment by wagas** [comment]
nothings new in chinese people

**Comment by wagas** [comment]
They are really good on copying stuffs LOL
![hahahaha](https://cloud.githubusercontent.com/assets/21025553/18203190/c927da98-7147-11e6-9d5e-58121d7461e7.png)

**Comment by Lunat1q** [comment]
ehm... is there a way i can stop it?

**Comment by Lunat1q** [comment]
I think going closed soure is pretty good idea.... :/

**Comment by GODEXTREME** [comment]
Well, close and invite who already have contributed.

**Comment by wagas** [comment]
why dont you send msg them?

**Comment by JihWei666** [comment]
WTF....................................

**Comment by tr1p0z** [comment]
Dude, should be better if you make this closed source. People and Niantic will stop trying *fuck* your job

**Comment by LPachecoBR** [comment]
Your Bot is the best I've ever used, and is still in development ...
Congratulations...
It is regrettable that some take advantage of the hard work of others for financial gain and cheat others (<http://www.xf-wg.com/> this website is full of virus) ...
If there is something that the community can do, let us know ...
Meanwhile, I'll use your Bot, will test and let you know if I notice a bug that no one warned before ...
Good Work, Good Luck !!!

**Comment by oZacDo** [comment]
I think that you can close source code first.
If they can't update new version, their customers must complain them. .
Maybe stealer will contact you.
I think that you can ask them to be contributor or ....
I start to use your program at version 1.2.
I know that you make great efforts.

Many, thanks

**Comment by WsTs** [comment]
Please make your software close source code. We are also angry that someone steal your work.

**Comment by Cowering** [comment]
Sadly I have firsthand experience with this :(  As a MAMEdev, we have to deal with this ALL the time. The chicoms are a sorry excuse for a people. They have been stealing ideas for time immemorial. The chinese make PC boards expressly to put 10,000 arcade games on and sell em for $100.  MAME can't fight them as the chinese government won't stop them and we won't pay for a lawyer.  We have found that open source is so much better for getting new code fixes. The bot is different because you don't have a million lines of code to maintain.  If their bot is chinese language only, and you are not getting many contributions from chinese people, you are not actually losing anything. The only bad thing I see about open source for the bot is that Niantic can look at it for patterns, but you can change those anytime!

**Comment by kaktusisko** [comment]
I will try to put Google filter on this page. We need tons of bad links. ;-)
From the beginning I thought that closed source is a necessity.
You can give access to those who are active so far.

**Comment by Cryptologism** [comment]
Nice copy cat b1tch... These kind of people runing everything and leechers....
Should kick in the face when meet these people..    -_-
Close the source code or maybe put somekind of password to protect it... ^_^

**Comment by MarkoHess** [comment]
Closing the code would also mean, that normal programmers can't modify the behavior for their own compiled version of catchem. I just modified the moveforce task to not stop at any pokestops and catch pokemon on the way. For me it's enough, but for a pull requests it's lacking an option at the UI.

**Comment by delunatix** [comment]
Closing the source code is the best way nonetheless.

**Comment by zanhehe** [comment]
Wow them assholes tryna steal yo work

**Comment by eloxxx** [comment]
Is it a Cheenise version or Japaneese version ?

If its a Chineese version I didnt get the point to do a bot because we can't play pokemon go in China as google map service is restricted to this country....  They don't have google, facebook etc 

So why are they doing that ?

**Comment by LCTY** [comment]
@Lunat1q Hey, I am LCTY, recently in Discord asked you questions of translation. Because I was angry about the behavior of "GetGO", I made the Traditional Chinese version, opened to the Chinese players.
I also told the people "Do not use GetGO", "intellectual property is important," and also attached your GitHub URL.
The current situation in Chinese discussion board, we already know the behavior of GetGO  (after all, they also charge), and instead use my version, the situation is somewhat improved.

**Comment by zanhehe** [comment]
@LCTY link on the discussion board?

**Comment by LCTY** [comment]
@zanhehe here~ [https://apk.tw/forum-pokemon-1.html](url)
At first people didn't understand how to use the original edition because of English, they turned to use GetGo which was already translated to chinese version.

So the ultimate solution is maping all text to binding, and do aliases and translate them all. It's a huge project. (To me)

**Comment by alfath2016** [comment]
I think translating should be ok as long not taken profits

**Comment by wagas** [comment]
@LCTY the http://www.xf-wg.com/ is getting sponsorship, or same like as contribution in here, am i right?

**Comment by Willxx1p** [comment]
the Getgo is free. did not see mandatory ???
![123123](https://cloud.githubusercontent.com/assets/21964856/18222588/c0e38c88-71ce-11e6-94ae-d25bfcf9765a.png)

**Comment by JihWei666** [comment]
I don't find the download from GetGO website.
Maybe I should be a "sponsor" then I could download GetGO....................
( I sould pay the money then I could download GetGO ?)

**Comment by JihWei666** [comment]
![123](https://cloud.githubusercontent.com/assets/21015061/18222844/b0132a64-71d6-11e6-9203-9ef96b2a2f2a.jpg)
They say " I have been a sponsor , please let me use it."

上面一堆人寫「已經贊助，請開通謝謝」   WTF............................

**Comment by MarkoHess** [comment]
I ran it through google translator. The download links there refer to mega as hoster. There seems no (translated reason to spend money there to download) I haven't tried to start the downloaded version, because who knows what has been changed in it?!?

**Comment by JihWei666** [comment]
Maybe you can have a one month trial ...then...
You need to pay them money or gift cards and tell them " I have paid for the bot , please active my account.＂

The bot they compiled could be connected to their server .
You can log in after checking your account if you have paid for it .

**Comment by MarkoHess** [comment]
Thx for translation.

**Comment by JihWei666** [comment]
![screenshot_20160903-171104](https://cloud.githubusercontent.com/assets/21015061/18224022/ddb4827c-718d-11e6-9859-632f0ef95e36.png)
People live in Hong Kong and Macou should pay 9~10 U
SD gift card .

**Comment by saldotman** [comment]
Close the source.

**Comment by cs8425** [comment]
I know this is unhappy thing.
But your LICENSE is GPLv3,
that means people are allowed to sell copies of the modified program commercially,
but only under the terms of the GNU GPL.
You can look at [FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially) & [stackoverflow's questions](http://stackoverflow.com/questions/2280742/gplv3-can-i-use-these-programs-in-commercial)
They're problem is that they did NOT release modified source code. [see here](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic)

ps. sorry for my bad English.

**Comment by LCTY** [comment]
@wagas The software has a free trial period, so what you see is just an illusion.

**Comment by wagas** [comment]
@LCTY so now if you consume the free trial period you cant use it now? and have to buy it from you? you are making me laugh 

@cs8425 did you even try to ask the real owner of the bot before selling? even the owner doesn't know about this one until someone has posted it..

**Comment by JihWei666** [comment]
@wagas When you try to use the bot, it will send your account to their server to check.
Paid ... then the server will let the bot work.
Not paid ... your bot will not log in Pokemon Go

**Comment by cs8425** [comment]
@wagas 
You should look up what's the "LICENSE" means.
Project owner give permission under the terms in LICENSE file.
So, "sell copies of the modified program commercially" did NOT violations LICENSE at this project.

**Comment by alfath2016** [comment]
Closed the source til they officially bergaining with you as the project owner. Maybe every 10% account will donate to you...

**Comment by cs8425** [comment]
@wagas  I know you do not have logical concept.
You just ignore the truth.

@Lunat1q re-licensing under other terms is possible as long as you get the agreement of "all copyright holders". [see here](http://programmers.stackexchange.com/questions/135450/taking-an-open-source-project-to-closed-source)

**Comment by wagas** [comment]
@cs8425  how about you do you have a logic?

**Comment by magicdev2** [comment]
even if he close the source it looks like they make there own servers aswell there source codes

**Comment by magicdev2** [comment]
so theres no point in doing it.

**Comment by alfath2016** [comment]
Alibaba!!

**Comment by alanearl** [comment]
Ahahaha it is made in China its not a good product either :D

**Comment by haapyend** [comment]
The software is written in https://apk.tw

**Comment by mudebug** [comment]
It is only to the advantage of the fishman when the snipe and the clam are grappling with each other.

**Comment by wagas** [comment]
@magicdev2  in the first place why didn't they make one ?

**Comment by magicdev2** [comment]
@wagas well the mostly everything they need is there the frame of the app it looks and how it works close the source code they will make a new one and hey it will work again..

**Comment by Lunat1q** [comment]
Source closed.
So it's not the problem anymore.
If anyone want to argue with me, about is it legit to close the source, PM me in Discord.
