### ISSUE TITLE
Less pokemon spawns

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#1268]
I've read the wiki, can't find settings that i'm doing wrong that caused the bot not to detect nearby pokemons. At least a link to the solution before closing?

Picture below, only 40+ catches in 4hours
<a href="http://imgur.com/2tHnjcY"><img src="http://i.imgur.com/2tHnjcY.png" title="source: imgur.com" /></a>

**Comment by Krypsus** [comment]
Depends on where you are catching

**Comment by lonelies** [comment]
been botting the same place. it's a good spawning place. just that recently less pokemon appeared.

**Comment by Lunat1q** [comment]
ask niantic, i didn'y change anything in this case.

**Comment by lonelies** [comment]
ahh.. get it. thanks !
