### ISSUE TITLE
Freeze when Transfer

### ISSUE THREAD

**Issue by ArchangelBr** [Lunat1q/Catchem-PoGo#1269]
With this new update, I freeze when I try to transfer a single poke. I have to stop and start the bot again.

http://prntscr.com/cda35b

After feel seconds, I get a console message saying that the character is too busy doing 2 or 3 actions, but I did just one transfer while it was on WALK state.

Anyone else ?

**Comment by druds** [comment]
its your delays settings, probably.

**Comment by ArchangelBr** [comment]
hmmm....  but it's on default...

**Comment by Lunat1q** [comment]
Try latest release (updated today)

**Comment by ArchangelBr** [comment]
I did not see that because it's the same version :(

Anyway, the problem is gone. Thanks.
