### ISSUE TITLE
Lucky lady eggs AND Incense (Again 0.o)

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#1272]
Hi guys!

Can anyone point me a thread where it explains or at least says if we are going to get to use manual itens in the future? I KNOW there has a lot of questions about it in the past. I was searching in old posts about this. Most of then are duplicate and without answer. In the middle of so much questioning about this, I'm lost in wich square we are. 

Thaaaaaaaaaaaaaaaaanks folks!

**Comment by ArchangelBr** [comment]
It's on roadmap... we need to wait

**Comment by HernestoSanchez** [comment]
Hummm i see. Thank you buddy!
