### ISSUE TITLE
Transfer Bug

### ISSUE THREAD

**Issue by 00Mango** [Lunat1q/Catchem-PoGo#1279]
My Bot saved some older CPs for every Pokemon and now he is transfering higher pokemon. E.g. I got 3 Pokemons my old Goldeen with 170cp and 2 Goldeen with over 300cp. The Bot saved the older 170cp and   he transfered both of the 300cp Goldeen. Now i disabled this function and i do it manually.

**Comment by Lunat1q** [comment]
Show me the settings printscreen.

**Comment by 00Mango** [comment]
http://prntscr.com/cdbq61 http://prntscr.com/cdbqaj

**Comment by 00Mango** [comment]
maybe because of Prioritize Both lv and Cp for transfer?

**Comment by Lunat1q** [comment]
yeah... i think it's cause of that
adjust IV and CP values
