### ISSUE TITLE
I do not see pokestop

### ISSUE THREAD

**Issue by Gudlok** [Lunat1q/Catchem-PoGo#1281]
I do not see pokestop
what to do ?

**Comment by Kubster** [comment]
same problem

**Comment by Gudlok** [comment]
I'm not the only okay :)

**Comment by Gudlok** [comment]
if it is good I just restart the software

**Comment by Gudlok** [comment]
sorry for my english: P Google Translation

**Comment by Kubster** [comment]
I don´t find any solution. restart the bot. install a other version. Try a new PTC acc. nothing work :(

**Comment by Cryptologism** [comment]
I assume you guys maybe have some kind of ipbanned... Btw is there any error display on your guys cmd?..?
Btw try to restart modem or change your ip or put vpn for awhile.... then reconnect back again..
The other solution.. try to check if pokestop is TICK inside the bot program... ^_^

**Comment by Gudlok** [comment]
For me it works again
but just now he captured me pokemon recover the pokestop but do not show the pokestop

**Comment by Cryptologism** [comment]
Oooo sometimes happen to me... it was maybe you open too many bots at one time... So i the solution was.. CLose all bot,wait around 2 minutes then start one bot only to make sure there is no ipbanned... I can make sure youre in ipbanned cuz too many connection from same pc... 
To use more that one yes you can but you need a private proxy.. Private Proxy.. not public proxy... You know why... ^_^

**Comment by Gudlok** [comment]
Thank you for all his info :)

**Comment by Gudlok** [comment]
last question
what does mean
(ERROR) Niantic Servers unstable, throttling API Calls.

**Comment by Cryptologism** [comment]
ermm... i think it was somekind of ermmm conenction unstable.. i have error too but im ignoring it... it was server sided.. ^_^
