### ISSUE TITLE
Visual bug: Map: Route shows up in the wrong spot when disconnecting, then reconnecting to remote desktop

### ISSUE THREAD

**Issue by oddhap** [Lunat1q/Catchem-PoGo#1282]
When using remote desktop to run the bot from another pc the route gets displaced if you disconnect and then reconnect to the pc. This is only a visual bug, the bot still follows the original route and functions like it should.
Zooming in and out does not fix the problem. Closing the program and opening it again fixes it.

OS: Win 8.1
Route made using mapzen valhalla
Follow the player is checked

**Comment by Lunat1q** [comment]
it's map control problem, can't fix it for now.
