### ISSUE TITLE
Poke transfer calculation

### ISSUE THREAD

**Issue by DirkDigo** [Lunat1q/Catchem-PoGo#1283]
Hello,

sometimes the bot transfers too many pokes because it does not consider the rewarded candies for  the transfers.

If P is the number of pokes, C the amount of candies and E the cost of an evolve then the number of evolvable pokes N is given by the formula

N = min( P , [  ( P + C ) / E - 1 ]  ) 

where the [ x ] is the smallest integer >= x. 

Hence the bot should transfer only P - N pokes.

Example: P = 25, C = 131, E = 12
Currently the bot transfers 14 pokes. Result: 145 candies, 11 pokes remain, evolvable 11
Transfer 13: C = 144, P = 12, evolvable 12 (preferred result)
Transfer 12: C = 143, P = 13, evolvable 12

**Comment by kingsley7601** [comment]
i fully understand what you mean but most players dont take this into account and to translate that logic into code may be quite a hassle

**Comment by Lunat1q** [comment]
yeah, you are talking about "keep pokemons what can evole" i guess, yes, your logic is right, i have same thoughts but no time to implelement it.

**Comment by DirkDigo** [comment]
Alternatively -- maybe easier to implement -- you could do the following in the transfer loop:

while ( P > floor( ( C - 1 )/( E - 1 ) ) ) 
{
 transfer one poke;
P-- ;
C++ ;
}
