### ISSUE TITLE
altitude meters/feet?

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1288]
I kept getting a softban using mapzen evevation. I was being listed at ~'14' 'units', which if in feet is about the max for my area, but 14 meters is higher than anything for 30 miles in any direction (I am on a coastline). I turned off that API and hardwired 3 'units' into settings menu and now I am instantly back online. 

Does Mapzen return feet for US IP addresses and meters for everyone else???

**Comment by johnpeterphoto** [comment]
you must get flooding there when it rains

**Comment by Lunat1q** [comment]
It's just inaccurate data, or was randomized, take a look into Mapzen/Altitude data

**Comment by Cowering** [comment]
yes, during a real hurricane (over 100mph) this area is gone
