### ISSUE TITLE
levelUp reward

### ISSUE THREAD

**Issue by majekqwert** [Lunat1q/Catchem-PoGo#1289]
Everything worked in previous versions. Now the bot does not receive the prize , but continues to run . To get the prize , I have to log on to the phone. Did I do something wrong, or its a bug ?

**Comment by Lunat1q** [comment]
i'll take a look into it.

**Comment by Initiols** [comment]
Same happened to me, got through lvl 20, didn't recieved my lucky eggs, incubator, insence and lures yet :[

(Didn't checked on my phone)

**Comment by eloxxx** [comment]
same

**Comment by KoopaTheTurtle** [comment]
same (havent checked on my phone)

**Comment by LPachecoBR** [comment]
Same happened to me...

**Comment by saldotman** [comment]
same here.
get the bonus when log in to phone

**Comment by petoe93** [comment]
same for me now, just got to 30 but still same amount of lures, incences & lucky eggs

**Comment by tvMed** [comment]
Here has happened not to show the information level up in the text area. Usually it shows.
I did not see if I won the items to level up.

**Comment by Spk345** [comment]
When I leveled up to 21, I got my rewards immediately in log. 
Is this issue still happening in newest release?

**Comment by majekqwert** [comment]
I checked my log , the last Level Up Reward 's got version 1.4.8.1 version 1.5 still does not work

**Comment by tyu366** [comment]
1.4.9.2 still have this issue.  No reward when going up to level 24.

**Comment by kollp3** [comment]
I bot with V1.4.9.4 no problem here
hit lvl 25 today and the incubator is already in use

**Comment by majekqwert** [comment]
> I bot with V1.4.9.4 no problem here
hit lvl 25 today and the incubator is already in use

? You use incubator, or get reward?

**Comment by kollp3** [comment]
i became a new one at lvl 25 and now there is a 5 km egg in

**Comment by majekqwert** [comment]
> i became a new one at lvl 25 and now there is a 5 km egg in
Off-topic

**Comment by kollp3** [comment]
> Off-topic
I just wanted to say I could recived my items at lvl 25 with this version

**Comment by majekqwert** [comment]
> I just wanted to say I could recived my items at lvl 25 with this version

but You get level up reward?

**Comment by petoe93** [comment]
think he got one incubator on lvl 25, and he is using it now
such an odd bug..missed 3 incubators, lures & lucky eggs on this one :/

**Comment by kollp3** [comment]
> think he got one incubator on lvl 25, and he is using it now

this.. sry for my bad english

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/oJEDarh.png)
Leveling rewards works just fine.

**Comment by tyu366** [comment]
I just get back my level 24 reward when I use the phone to play the game but not by the bot.
