### ISSUE TITLE
[Question] How to fix 'you have failed with item settings' message?

### ISSUE THREAD

**Issue by HanSolo11177** [Lunat1q/Catchem-PoGo#1291]
Tried to mess around with the settings but still I get this error - please could somebody explain how to fix? Thanks
![capture](https://cloud.githubusercontent.com/assets/21951817/18212516/93e2374a-713b-11e6-85d8-7b8c356d9123.PNG)

**Comment by Cowering** [comment]
set the 100% keep to about 90%

**Comment by Krypsus** [comment]
Normal Items + Extra Items = Recycle %
Ej: 280 normal items + 12 extra items  = 0.84

Extra items have to be included in the percentage
