### ISSUE TITLE
new feature idea

### ISSUE THREAD

**Issue by DarkHenos** [Lunat1q/Catchem-PoGo#1292]
hi, it would be possible to add a feature to change the language of the bot, eg to french?
or another language instead whatsoever seullemnt console that can have this feature

ps:sorry the probable fault in my message, I'm french is I use google translation

**Comment by petoe93** [comment]
there is a language option in the settings dude..just change from "en" to "fr"
Anybody ever thinks about reading the FAQ and/or changelogs?? smh

**Comment by DarkHenos** [comment]
I saw my her does not change the language of the application, only the bot ^^ "

**Comment by MaK-88** [comment]
> petoe93 commented 15 minutes ago
there is a language option in the settings dude..just change from "en" to "fr"
Anybody ever thinks about reading the FAQ and/or changelogs?? smh

It changes only the name of the pokemon, not the settings.

**Comment by tyu366** [comment]
I have been using your robot for 8 hours.  It is good but still lack some key features to look like human.

**1. Resting time**
I think it is better to add set up for sleeping time, lunch time, dinner, tea break.  So when that local time has reached, the moving will be paused.

**2. number of stops**
Also, for path construction, 47 stops is not sufficient to run whole day. It will be good to extend to more than 100 stops and allow multiple paths to be run in sequence.
So if a user has set up 10 paths, one can create 1 long path with 1000 stops.

**3. new auto-transfer option**
auto transfer the weaker one if both CP and IV is superior
   except when CP is over xxxx and/or IV is over xx%

I hope that your design more perfect and reflected in your download rate.
