### ISSUE TITLE
[bug] egg not use when evolve

### ISSUE THREAD

**Issue by allencyl** [Lunat1q/Catchem-PoGo#1293]
When I get enough candy to evolve pokemons .
The message show "using lucky egg" but actually not use at all and start evolving.

**Comment by Cowering** [comment]
ouch, don't say that. i got enough pidgeys for an entire level if i use an egg right now

**Comment by Franssa89** [comment]
I can't use the Lucky Egg in bot, but I started the Pokemon Go in the mobile and start evolve in the Bot.
