### ISSUE TITLE
some problem with the accuracy of the boot will catching or farming pokestops

### ISSUE THREAD

**Issue by zhach01** [Lunat1q/Catchem-PoGo#1294]
i am having a problem with the bot it seems farming  pokestops before being in a real life range .
for example it farms pokestops with in distance of 100 meter away from the player location is it a bug an error or something else  ? the same issue with pokemon capture i captures pokemon 1 street block away . fix those 2 bugs to make the bot safer and more ban proof . @Lunat1q

**Comment by Cryptologism** [comment]
I got your point.. Yeah in real life when to get into pokestop which 250meters are mark as too far away.. But using this boot seem esay to get those.. Mybe something i miss too sir @Lunat1q

**Comment by zhach01** [comment]
I guess there is solution of this problem and the issue of pokemon capture it simplifies by adding one step before calling the activity of catching or farming,
For farming, you can add an if or switch or try and catch to compare the coordinate of the player and the pokestop and when if it is far away the character must walk into a range of 12 circle radius of the pokestop and when its in the range he can farm.
the same logic should be applied to the way of catching pokemon .
we find a simple code hoping to clarify my point of view:+1: 
 
do 
{
switch(coordinate):
case coordinate<=coordinate_OF_Pokestop+150 {
walk(oordinate_OF_Pokestop);
continue();
}
case coordinate+>coordinate_OF_Pokestop+150 {
walk(next_pokespot_coordinate);
pokespot_coordinate=next_pokespot_coordinate
break;
}
case coordinate==coordinate_OF_Pokestop+10 || case coordinate==coordinate_OF_Pokestop-10{
farm_pokrstop(pokespot_coordinate);
break;
}
}while(coordinate!= coordinate_OF_Pokestop 
Same logic for capture sorry I am a mechatronic engineer I took c# and c++ and basic programming in my uni 4 years ago,  I know i  suck in programming but I hope you get my logic. Please try to implement this fix or enhancement to your bot if it is possible @Cryptologism @akira02 @CDAGaming @Lunat1q 
case coordinate+>coordinate_OF_Pokestop+150 {
walk(next_pokespot_coordinate);
pokespot_coordinate=next_pokespot_coordinate
break;
}
case coordinate==coordinate_OF_Pokestop+10 || case coordinate==coordinate_OF_Pokestop-10{
farmepokrstop(pokespot_coordinate);
break;
}
}while(coordinate!= coordinate_OF_Pokestop 
same logic for capture sorry i am a mechatronical engenir i took c# and basic programing in my uni from 4 years ago so i know i am suck in programing but i hope you get my logic. please try to emplement this fix to your bot if it is possible @Cryptologism @akira02 @CDAGaming @Lunat1q

**Comment by Lunat1q** [comment]
bot farm PS only in 40m range, which is server side rule, same as the real game
