### ISSUE TITLE
altitude question

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1295]
I peeked at the bot code. is the 0.8 you are adding in various altitude calculations the height above ground of a player's phone?

**Comment by Cowering** [comment]
just saw this pop up in my settings while bot it running.. is the altitude listed including the 0.8, which would explain it being above my set max of 4?
![capture4](https://cloud.githubusercontent.com/assets/9252175/18213494/ca1054a4-7105-11e6-80b0-cba1f0b0fbaf.PNG)

**Comment by tkien212** [comment]
I think it's because you are using mapzen, which explained here

https://github.com/Lunat1q/Catchem-PoGo/releases/tag/v1.4.4.1
