### ISSUE TITLE
[Question] What is the risk of ban if I use 2 or 3 bots at the same time on the same computer?

### ISSUE THREAD

**Issue by LPachecoBR** [Lunat1q/Catchem-PoGo#1296]
What is the risk of ban if I use 2 or 3 bots at the same time on the same computer?
Harnessing the space ...
What is the best way to change my IP?
Thank you.....

**Comment by Krypsus** [comment]
Try not to use more than one, if you don't want to be banned soon

**Comment by Franssa89** [comment]
I use 2 bots at the sametime and didn't get banned, use for 1 month

**Comment by ArchangelBr** [comment]
Let's say like this: the change is higher than if you run just one!

We can't talk about numbers... 

there is people that use only one and got banned!
also there is people like @Krypsus that didn't...

**Comment by wagas** [comment]
i guess one way of getting ban was on the stardust.. normal player wouldn't even save the 200k+ stardust just my opinion

**Comment by Cryptologism** [comment]
Stardust and also dont snipe.. ermm the other one mybe dont change the ip always or dont change the detail of devices uses...

**Comment by LPachecoBR** [comment]
@Cryptologism 
I use real data from my cell phone and other members of my family ...
I never changed the data since when activated the Bots ...

**Comment by magicdev2** [comment]
No you dont get ban for using more then 1 account i have 15 accounts running 8 hours a day for the whole week and weekend

**Comment by magicdev2** [comment]
aslong as you dont change the settings your find
