### ISSUE TITLE
【BUG】 This issue cause the the problem of transferring

### ISSUE THREAD

**Issue by pogoaccount** [Lunat1q/Catchem-PoGo#13]
I have already full pokemons250/250, but thr bot says 240/250. So It does not transfer and stop catch pokemon

**Comment by Lunat1q** [comment]
hm, where did u got those extra pokemons? can't figure out what i've missed some source

**Comment by pogoaccount** [comment]
All are from Sniping which is function inside the bot

**Comment by Lunat1q** [comment]
ah, that can be true, sniping not complete yet.

**Comment by pogoaccount** [comment]
OK hope you can fix, appreciate!

**Comment by Lunat1q** [comment]
recycle issue fixed
