### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#130]
Извиняюсь, подскажите как поменять локализацию сист сообщений программы на Русскую? Не нашел в настройках, и вижу что в папке translations есть соответствующие файлы. Также очень бы хотелось локализацию настроек программы.
P.S. обязательно на англ дублировать или можно только по русски оформлять посты?
_________________________________________________________________________________________________________

Excuse me, tell me how to change the system of localization program messages in Russian ? I not found in the settings and see that the translations in the folder has the appropriate files . It is also very much like to localize the program settings .

**Comment by Lunat1q** [comment]
Set language code to ru_RU
