### ISSUE TITLE
need a new  Features~~~please~

### ISSUE THREAD

**Issue by DreamSo** [Lunat1q/Catchem-PoGo#1300]
when  got  1000 pokemon  or  2000 pokestop  will stop work~~

real need it~~please~

**Comment by Cryptologism** [comment]
I think it already alert the kill troggered dude... make it start again... cuz in normal life theres no one willing to play pokemon go 24/7... without no sleep,no food... ONly bot... soif you wiiling to do this,be my guest to get banned...
