### ISSUE TITLE
(ATTENTION) MobBotRouting API Key is Empty!

### ISSUE THREAD

**Issue by klykly1** [Lunat1q/Catchem-PoGo#1301]
![image](https://cloud.githubusercontent.com/assets/20981088/18215075/1d9e8f74-7182-11e6-83e9-2000b41a14c8.png)

How to solve this one guys? there's pokestop there but i cant get pokeballs thanks

**Comment by Cryptologism** [comment]
Lol... Fill in the blanks of MobBotRouting Key then the error will gone too... 
For cant get pokeballs,did you tick to loot pokestops? at the main ui of this application?

**Comment by Chris20000** [comment]
Fill them with what?

**Comment by Cryptologism** [comment]
I thought mob bot api key should be the key right?

**Comment by Chris20000** [comment]
Have explained my problem detailedly in another issue

**Comment by mortal4gaming** [comment]
Use mapzenValhalla really good work

**Comment by klykly1** [comment]
@Cryptologism what should i put in there? irdk what to do

**Comment by Cryptologism** [comment]
Im not sure neither dude cuz im using Valhalla mapzen... Not mob routing... Some of others saidbit was payment routing...v
