### ISSUE TITLE
"Use Lucky Eggs While Evolving"

### ISSUE THREAD

**Issue by Initiols** [Lunat1q/Catchem-PoGo#1305]
I don't know how this command works, I've been trying to set the "Lucky Eggs Min Poke" to 1, and evole a pokemon to see if it used a lucky egg, but it didn't.

I've gathered a lot of pokecandies, so I can mass evolve with lucky egg, but don't know how to manipulate it..

Help needed ^_^

**Comment by Cowering** [comment]
only time i could drop egg, i had 16 pidgeys and the default limit is set to 15 IIRC. I don't know about just one.. but a forced drop would be EGGcellent!

**Comment by Initiols** [comment]
I still have like 20 pokemons to evolve, but I don't wanna take the risk to fail it cause of a missunderstanding or bug

**Comment by Bay101** [comment]
It is when the bot auto evolves not when you are evolving it manually through the inventory page :smiley:

**Comment by Initiols** [comment]
thanks dude
