### ISSUE TITLE
Right Click to use ?

### ISSUE THREAD

**Issue by Initiols** [Lunat1q/Catchem-PoGo#1306]
Would be great to have the ability to manually use the items in the inventory, such as the insence, lucky egg...

Like we can already right click to "Recycle item", or "Refresh item list", we could get the "Use item" too :3

What's your point of view ?

**Comment by Cowering** [comment]
I think this is a dupe

**Comment by HernestoSanchez** [comment]
Sup Dude. The option to manually use itens will be added in the future. It´s already on the roadmap!

Cya!

**Comment by Initiols** [comment]
thanks then ^_^

**Comment by HernestoSanchez** [comment]
you're welcome 0/
