### ISSUE TITLE
API KEY EMPTY, unable to use bot

### ISSUE THREAD

**Issue by Chris20000** [Lunat1q/Catchem-PoGo#1307]
I used the bot and suddently it stopped working and started saying API Key is empty((ATTENTION) MobBotRouting API Key is Empty!). 

It said this before, but it hasnt been influencing the bot i think.

Beside that, it always tells me: (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

My friend has the same problem and he has the error: (ERROR) APIFailureStrategy (Exception): BadAuthentication

**Comment by Chris20000** [comment]
The full error of my friend is:

APIFailureStrategy (Exception): BadAuthentication
[21:46:12] (ERROR) APIFailureStrategy (Exception): BadAuthentication
[21:46:13] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Eine Ausnahme vom Typ "PokemonGo.RocketAPI.Exceptions.InvalidResponseException" wurde ausgelöst.
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:Zeile 79.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() in D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:Zeile 53.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:Zeile 225.
[21:46:13] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

**Comment by magicdev2** [comment]
i dont know how to help you with the second one but for the frist one you need to go to google api
https://console.developers.google.com/apis/dashboard?project make a key there.

also in settings you have to change the mobbot to google.
hope this helps

**Comment by mortal4gaming** [comment]
MapzenValhalla really good work. Change to mapzen

**Comment by Chris20000** [comment]
How?

**Comment by magicdev2** [comment]
mapzen and google are the same thing.

**Comment by Chris20000** [comment]
And what do I fill in the gap for the api key?

**Comment by Chris20000** [comment]
By the way it stops telling me this problem, but only:

(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by magicdev2** [comment]
then your ipban

**Comment by magicdev2** [comment]
you have to wait a few hours trust me i been there done that :p

**Comment by magicdev2** [comment]
by the way if you dont know what is a ip ban and ipban is when Niantic blocks your ip from there server because of for example for bots hacking or etc...

**Comment by Chris20000** [comment]
:/ Thanks

**Comment by Chris20000** [comment]
Is the IP ban temporally?

**Comment by magicdev2** [comment]
yeah and your question is not dumb i wasnt trying to be rude but i know some people dont understand it

**Comment by magicdev2** [comment]
also sorry you didnt understand it :p

**Comment by Chris20000** [comment]
So is it temporally? Btw Thanks a lot for your lots of awnswers and for supporting my bad english xD

**Comment by magicdev2** [comment]
yes it temporally and your welcome xD

**Comment by Chris20000** [comment]
Just another question xD: How many bots can i run at the same time?

**Comment by magicdev2** [comment]
depends i run 15 accounts at once i heard that some people can run 3 or 1 accounts because or some reason it crashs i didnt get that problem but just in case knock on wood ;p

**Comment by Chris20000** [comment]
:) Thanks again
