### ISSUE TITLE
CONFIGURATION against ban

### ISSUE THREAD

**Issue by lucas3820** [Lunat1q/Catchem-PoGo#1308]
Ola, não sei se aqui é o local correto para esse tipo de pergunta, ja peço desculpa se estou fazendo errado. 

Gostaria de ajuda de alguém, pois ja estou na minha 3 conta de pokemonGO pois fui banido, alguém teria configurações melhores para evitar o banimento?

Estou usando:
Google directons KEY
Mapzen KEY

Walking Speed Min: 3
Walking Speed Min: 8

(As demais configurações estão padrão)

nunca usei varias contas ao mesmo tempo.

--------------------------------------------------------------------

Hello, I do not know if this is the correct place for this kind of question, since I'm sorry if I'm doing wrong.

I would like to help somebody because I'm already in my 3 pokemonGO account because I was banned, someone would have better configurations to prevent the ban?

I'm using:
Google directons KEY
Mapzen KEY

Walking Speed Min: 3
Walking Speed Min: 8

(The other standard configurations station)

I never used several accounts at once.

**Comment by magicdev2** [comment]
you cant prevent the ban if you are using bots you just need luck.

**Comment by HernestoSanchez** [comment]
E ai maluco!

So, actually im using 2 bots (not at the same time) and so far so good. My settings are just like yours. Other than that, I keep always the same phone info, and routing services. Don´t leave the bot alone for more than one and a half hour...
But, as Magicdev said, with a bot, is pure luck!

Até!

**Comment by mortal4gaming** [comment]
you need to use different proxy for each account bot. If multiple bot with the same ip, ip ban fast. Or just run one at a time.

**Comment by mortal4gaming** [comment]
Go discordapp.com Catchem bot UI. https://discord.gg/pPwxX8Q here
https://github.com/Lunat1q/Catchem-PoGo See here

**Comment by lucas3820** [comment]
I have no fluency in English, speak Portuguese.

**Comment by mortal4gaming** [comment]
multi lenguaje foro, yo soy español

**Comment by mortal4gaming** [comment]
Me same use all time gogole translate but new feature, muti-language for all languages

**Comment by goiabs** [comment]
Lucas, posta a print das suas configurações aí. Eu tenho 5 bots (3 são lvl 20+) e não tomei ban em nenhum até agora. Talvez eu possa te ajudar.

**Comment by lucas3820** [comment]
[![Untitled-1.fw.png](https://s15.postimg.org/ed3eigmqj/Untitled_1_fw.png)](https://postimg.org/image/tltbw8gev/)

**Comment by goiabs** [comment]
Olha, primeiro seu "Throw Accuracy Max" está configurado para 100%. Te aconselho a mudar o  para 0,8. Isto porque um acerto 100% exato é quase impossível, humanamente falando.
Agora, o que provavelmente está te dando ban é seu "Delay Between Poke Catch". Se você jogar no celular vai perceber que o processo todo de captura de um pokemon dura ~25 segundos. Você não consegue capturar pokemon mais rápido que isso no celular. Então altere seu "Delay Between Poke Catch" para algo em torno de 25000. Da mesma forma, uma evolução dura no mínimo 25 segundos. Seu "Delay Evolve Poke" está configurado corretamente mas, se você observar, embaixo há uma opção chamada "Delay Evolve Variation". O teu está configurado para 30%. Isto quer dizer que o bot pode fazer uma evolução em 18 segundos (25 segundos - 30%), o que é impossível no celular. Altere o "Delay Evolve Poke" para 0,1.
Tirando isso, altere seu "Max XP Per Hour" e "Max Star Dust Per Hour" para 0. Não sei se influencia, mas os meus bots estão configurados assim e não tomei ban neles.
Faça essas alterações e não esqueça de dar um feedback aqui daqui a 1 semana mais ou menos dizendo se tomou ban.
Espero que tenha ajudado.

**Comment by lucas3820** [comment]
goiabs, vc ajudou muito veio, ja é possível eu esta na próxima lista de BAN, pois já tenho usando sem essas novas configurações que vc me deu ^^, ja que vc esta tão inteirado que ria fazer uma pergunta.
Quanto tempo por dia vc deixa o BOT funcionando?

OBS: pode deixar eu vou postar sim o resultado.

**Comment by goiabs** [comment]
Eu deixo o bot funcionando por no máximo 8 horas seguidas. Aí deixo pelo menos 8 horas desligado. Eu fico nessa: 8 horas ligado - 8 horas desligado.

Tenho 2 tipos de bot (pois estou testando): Em um eu coloquei 5-13 km/h. No outro coloquei 10-50 km/h. Ainda não levei ban em nenhum deles, mas estão em fase de testes. Quero ver se talvez o bot mais rápido (10-50 km/h) leva um ban. Embora acho que não teria motivo para banirem, já que essa é a velocidade média de um carro. 

Todos eles estão acima do level 20. Mas devo dizer que não tem muito tempo que comecei a usar, faz quase 2 semanas. É cedo para saber se vão banir ou não, mas as configurações que te passei são baseadas no que observei no jogo através do celular, tentando ser o mais "humano" possível.

Espero que te ajude.

**Comment by goiabs** [comment]
Lucas, depois de quanto tempo do bot criado você tomou ban? Os bans foram todos ao mesmo tempo?

**Comment by lucas3820** [comment]
depois de umas 2 ou 3 semanas (nao lembro), sim um amigo meu tb levou BAN no mesmo dia.

**Comment by goiabs** [comment]
Entendi. O jeito é esperar a próxima onda de bans e ver se vamos rodar... ^^

**Comment by lucas3820** [comment]
apareceu isso aqui:
[18:21:37] (INFO) Not enough Pokemon to trigger a lucky egg. Waiting for 5 more. (10/15)
não esta evoluindo meus pokemons, nao sei porque.
outra coisa que queria saber, onde eu ativo o incense?

-------------------------------------------------------------------------
appeared this here:
[18:21:37] (INFO) Not enough Pokemon to trigger a lucky egg. Waiting for 5 more. (10/15)
not this evolving my Pokemon, I do not know why.
else I wanted to know where I live incense?


[![Untitled-1.jpg](https://s15.postimg.org/vcdifz8l7/Untitled_1.jpg)](https://postimg.org/image/vp4wm5quv/)

**Comment by mortal4gaming** [comment]
DELETE ¨NO TO CATCH¨ POKEMONS, CATCH ALL / pokedex add before, add only magikarp in no to catch. My lvl 30 take +4500 magikarp candies :S. My 7 gyarados +95% fix this

**Comment by mortal4gaming** [comment]
use this configuration AND CHANGE NAMES::: :¨= no need say CATCHEM in name... obvious.
Change.
Altitude min 1
Altitude max 50
Prioritice both IV and CP for transfer : FALSE (NEED TO TRANSFER POKEMON)
Use only unlimited incubator : FALSE
Lucky egg min poke : 50 (50 o more evolves for double exp)
Use lucky eggs while evolving : TRUE
Always prefer Long Distance Egg : TRUE


This work fine for me

**Comment by mortal4gaming** [comment]
Walking speed min (kmh/h) : 2-3
Walking speed Max (kmh/h) : 7-11

(My tests)::
Fast walk - + 4/5. Running Max - + 11. walking slowly + - 2/4.
Sometimes pathing gps + - 2 km / h do not like being at 0 km / h, +3 min km / h.
walking bicycle (I use only for my pokestop) Min 4 km / h. Max + - 24 km / h.
You can change every time to look more human.

**Comment by Halitz** [comment]
Need new update to use incense and lure modules.  We will have to wait. :+1:

**Comment by Halitz** [comment]
talking about bans. They can not  run 15 accounts. Same IP, same dvide info. Maximum 3 accounts for the same ip / deviceinfo) :.
Or you need to pay private proxy for the same use.
Or it may be ban. Permanent.
