### ISSUE TITLE
Loop'd - Devs Help Please

### ISSUE THREAD

**Issue by KoopaTheTurtle** [Lunat1q/Catchem-PoGo#1309]
I currently have 3 bots running. 2 of which are running fine. the other one is a bit... broken and only on that one.

it logs me in, does the whole best cp etc and then it says how much pokemon i have. it proceeds to tell me what i have in my inventory, how much i have in my inventory and then it says how many pokemon i have and then back to listing inventory. This loops and doesn't stop. the player wont move and that just loops.

**Comment by mortal4gaming** [comment]
you need to use different proxy for each account bot. If multiple bot with the same ip, ip ban fast. Or just run one at a time.

**Comment by magicdev2** [comment]
no you dont you dont need proxys i dont use them and i have 15 accounts active

**Comment by mortal4gaming** [comment]
no dynamic IP . your ip will be BANNED for life and not be able to connect to servers ninatic . I prefer not to risk . I have static ip . VPN proxys 90% banned for that reason. if you have dynamic ip . It is not feasible more than one account. your ip will be BANNED for life with 15 bot. Sorry use translate.

**Comment by KoopaTheTurtle** [comment]
OKAY GUYS. Just started happening on my another bot. It only started when the Recycle stage started. I have tried stopping the bot and restarting but it goes straight back to recycling. I believe this is a bug and @Lunat1q and/or @Bay101 need to look into it

**Comment by goiabs** [comment]
Koopa, post a print of your bot settings.

**Comment by KoopaTheTurtle** [comment]
All defualt except ive turned long distance eggs on

**Comment by KoopaTheTurtle** [comment]
the 2 that did derp was {1}_{0} for rename template
the one that didnt derp was {0}_{1}

thats the only difference and of course the Device Info is different as well

**Comment by goiabs** [comment]
There are other settings more important. Post a print of your all settings.

**Comment by KoopaTheTurtle** [comment]
![5f13b0d14a4d589b3f1ec03f69e16d2b](https://cloud.githubusercontent.com/assets/21056276/18222380/5f877820-71ea-11e6-8b8c-eaca368b2e84.png)
![2217e18ad1d7e9b73d81a01f32057878](https://cloud.githubusercontent.com/assets/21056276/18222382/60a88d0c-71ea-11e6-9507-521e1406a771.png)

thats from one bot. only thing different is device info.
