### ISSUE TITLE
BOT does not move

### ISSUE THREAD

**Issue by Hurr123** [Lunat1q/Catchem-PoGo#1310]
My bot does not move, when I set it's latitude and longitude it goes to the area but it doesn't load around and pokestops don't show.
![screenshot_7](https://cloud.githubusercontent.com/assets/21961230/18217723/32a4f072-7167-11e6-890f-6f862c53c636.png)

![screenshot_8](https://cloud.githubusercontent.com/assets/21961230/18217742/44222770-7167-11e6-9d5a-b026314f5cb8.png)

![screenshot_9](https://cloud.githubusercontent.com/assets/21961230/18217749/48db386a-7167-11e6-86a0-f3b412c09a6f.png)

^My options

**Comment by magicdev2** [comment]
you need a google api key

**Comment by magicdev2** [comment]
thats why it doesnt move

**Comment by Bay101** [comment]
Mobbot is a paid service and you need an API key, Please check when using a routing key if it requires an API key by looking below it at the API key settings area!
