### ISSUE TITLE
Bot auto unfavorite after manually favorite

### ISSUE THREAD

**Issue by tkien212** [Lunat1q/Catchem-PoGo#1312]
> Manually Favorite Pokemons
> 13:44:30] (FAVOURITE) Gyarados      CP: 2370 IV: 96.55% Candies: xx
> 13:44:38] (POKESTOP) -
> 13:44:39] (FAVOURITE) Gyarados      CP: 2364 IV: 94.88% Candies: xx
> 13:44:48] (FAVOURITE) Machamp       CP: 2108 IV: 63.44% Candies: xx
> 13:44:51] (POKESTOP) -
> 13:44:57] (FAVOURITE) Nidoqueen     CP: 2085 IV: 63.60% Candies: xx
> 13:45:07] (FAVOURITE) Nidoking      CP: 2079 IV: 64.62% Candies: xx
> 13:45:13] (POKESTOP) -
> 13:45:16] (FAVOURITE) Magmar        CP: 1994 IV: 96.25% Candies: xx
> 13:45:26] (FAVOURITE) Golem         CP: 1784 IV: 79.00% Candies: xx
> 13:45:55] (POKESTOP) -
> 13:46:14] (POKESTOP) -

> ......................................After leave it there for a while..............................................................
> 13:54:04] (EGG) Incubator status update: 0.39km left
> 13:54:17] (POKESTOP) -
> 13:54:30] (FAVOURITE) Golem         CP: 1784 IV: 79.00% Candies: xx
> 13:54:38] (FAVOURITE) Magmar        CP: 1994 IV: 96.25% Candies: xx
> 13:54:47] (FAVOURITE) Machamp       CP: 2108 IV: 63.44% Candies: xx
> 13:54:55] (FAVOURITE) Nidoqueen     CP: 2085 IV: 63.60% Candies: xx
> 13:55:04] (FAVOURITE) Nidoking      CP: 2079 IV: 64.62% Candies: xx
> 13:55:12] (FAVOURITE) Gyarados      CP: 2364 IV: 94.88% Candies: xx
> 13:55:20] (FAVOURITE) Gyarados      CP: 2370 IV: 96.55% Candies: xx
> 13:55:29] (INFO) [Inventory] Pokemon Stored: 194/250
> 13:55:29] (TRANSFERED) Sandshrew	- CP: 417  IV: 32.41%   [Best CP: 577  IV: 61.09%] (Candies:xx)

**Comment by magicdev2** [comment]
this doesnt show anything....

**Comment by tkien212** [comment]
attached log file is at the end, i'm not sure what can it shows more
Here's a detailed of what happened from what I know:

1. I used Ctrl+LeftClick to select pokemons I wanted to favorite. Then right click -> favorite pokemon
2. Bot will keep catching/walking between the favorite's delay
3. Before transfer pokemon, it will automatically unfavorite

**Comment by Housy123** [comment]
Can confirm if you manually favourite a pokemon the bot will unfavourite it after a while happens because you ticked the deature to favourite pokemon with xx.xx IV

**Comment by alanearl** [comment]
If Check... Uncheck it.

![capture](https://cloud.githubusercontent.com/assets/648116/18225109/047e4a60-721e-11e6-883c-6908ccb6f77d.PNG)

**Comment by tkien212** [comment]
solved, thanks guys

**Comment by kertiek** [comment]
this is still happening.... un-favorite after a manual favorite.
