### ISSUE TITLE
PB Number of Egg Incubator & Lucky Egg when changing trainer level

### ISSUE THREAD

**Issue by eloxxx** [Lunat1q/Catchem-PoGo#1313]
I just got level 25 but my amount of lucky egg and egg incubator are still the same as when I was level 24.

Did anyone experience the same issu ?

Thanks guys.

**Comment by magicdev2** [comment]
1.you have a lot of stuff in your bag
2. just get more xp
3. its a bug and you didnt get lucky sorry...
4.am not sure.... xD
