### ISSUE TITLE
Differentiate Amount Of Pokeballs To Keep

### ISSUE THREAD

**Issue by br0cca** [Lunat1q/Catchem-PoGo#1315]
Is it possible to differentiate the balls to keep?

"TotalAmountOfPokeballsToKeep":
"TotalAmountOfGreatballsToKeep":
"TotalAmountOfUltraballsToKeep":
"TotalAmountOfMasterballsToKeep":

Thanks for the good work!

**Comment by Fenderfix** [comment]
Yes please, do it! :D
