### ISSUE TITLE
Already have a Mapzen key but still

### ISSUE THREAD

**Issue by klykly1** [Lunat1q/Catchem-PoGo#1317]
but still i cant spin pokestops and always prompt a 
![image](https://cloud.githubusercontent.com/assets/20981088/18219792/101ba450-719f-11e6-84cc-ca399f6402ca.png)

**Comment by MarkoHess** [comment]
perhaps there is a " " empty space before or after your key

**Comment by Bay101** [comment]
It is the routing service, Please ensure that you are using the correct routing service and appropriate routing key. There are two Mapzen API's, one is for Altitude and the other is the Routing Service
