### ISSUE TITLE
My bot only stays in xp/h: 0

### ISSUE THREAD

**Issue by PaulinhoCB5** [Lunat1q/Catchem-PoGo#1320]
![gfhfgh](https://cloud.githubusercontent.com/assets/21317410/18220975/756d6622-7145-11e6-8848-0bbffa0ef280.jpg)

It doesn´t loot pokestops but captures wild pokemons, weeeiiirrrrrddd

**Comment by Bay101** [comment]
please ensure the loot pokestops checkbox is checked

**Comment by PaulinhoCB5** [comment]
But it is already marked, there´s a possibility of a soft ban ? Now the pokemons are fleeing

**Comment by Cryptologism** [comment]
Lol.. Running 5 bot usjng same ip... Hahahaha.. Really dude? Read the other post
