### ISSUE TITLE
I'm lvl 33 right now should I stop botting? over 100 hours of waist if ban. (When is the right time)

### ISSUE THREAD

**Issue by h3viin** [Lunat1q/Catchem-PoGo#1322]

**Comment by Cryptologism** [comment]
I think its time to play real now and never go back to bot for ur safety... But its all up to you dude... 
Well if im were u,i think i can stop and play like normal... 😊

**Comment by h3viin** [comment]
@Cryptologism do you think there anti bot system getting better or why stop now? :P

**Comment by Cryptologism** [comment]
Ermmm im not sure bout that... But 1 thing for sure... Niantic gonna increase thier security day by day... Meybe they waiting for proof then they attack at the same time.. Huhuhu sry brokem english

**Comment by juliopokemon** [comment]
lv 33 in only 100 hours?
how much xp/h you do?

**Comment by h3viin** [comment]
@juliopokemon its more then 100 hours sry, 25xp/h !

**Comment by juliopokemon** [comment]
nice!  i make 5k~6k/h

can you send a print of your settings ?
