### ISSUE TITLE
 What is meant by these acronyms

### ISSUE THREAD

**Issue by juliopokemon** [Lunat1q/Catchem-PoGo#1323]
![aaaa](https://cloud.githubusercontent.com/assets/21186387/18221876/a32be630-715c-11e6-9022-6c44962363d5.png)

nt and tf ?

**Comment by goiabs** [comment]
https://github.com/Lunat1q/Catchem-PoGo/wiki/FAQ

Look at the last question.

**Comment by juliopokemon** [comment]
thanks!
