### ISSUE TITLE
NEED HELP MAPZEN KEY/API

### ISSUE THREAD

**Issue by klykly1** [Lunat1q/Catchem-PoGo#1324]
![image](https://cloud.githubusercontent.com/assets/20981088/18221897/7d5fe34a-71b9-11e6-80fd-10a0dee72633.png)

What should i put to get pokeballs and spin in the pokestops? If my character reach the pokestop thats Attention is going to be pop-out . Help me pls

**Comment by Jordan-Zhu** [comment]
Get an API key from https://mapzen.com/developers for their Mapzen Search. the "Mapzen Valhalla API key" should look something like: "search-(random letters and numbers)".
