### ISSUE TITLE
READ THIS BEFORE CREATING AN ISSUE!!!

### ISSUE THREAD

**Issue by Bay101** [Lunat1q/Catchem-PoGo#1327]
**Please only post actual bugs as issues!**

If you have an actual bug please ensure that you read all of the issues already made before creating a new one, this includes all of the closed issues.

Also before creating an issue or going to Discord for help please view the Wiki for information on setup and FAQ: https://github.com/Lunat1q/Catchem-PoGo/wiki

For any issues or help that you require please ask on our discord server: https://discord.me/Catchem

**Comment by Initiols** [comment]
I feel like it's adressed to me somehow

**Comment by Spk345** [comment]
Gorgeous.
Good Jerb.

**Comment by magicdev2** [comment]
....

**Comment by magicdev2** [comment]
@Bay101 the reason i dont do to discord is because i dont like or wont use it just to ask you a person a question and you have to go to a other website or download the discord app just no and i know some people wont go to discord just for one question.

**Comment by itterror** [comment]
Then you have no room to ask question. Its not like you guys pay someone to do a job.
If you have question, go to discordd. dont wanna go to discord? your question wont be answered.
Its that simple.
