### ISSUE TITLE
how many times stop/start

### ISSUE THREAD

**Issue by karcan** [Lunat1q/Catchem-PoGo#1329]
can you add 
**(how many times stop/start - max per hour)** - like stoped 15 times
and 
**(total stoped time)** - like 2h43m in 24h
 in information ? :)

**Comment by Charlier69** [comment]
Or maybe you can set an timewindow like 20 min - 200 and the bot taks any time between this windows

**Comment by Spk345** [comment]
I believe most of these features were implemented with the new Scheduler feature, although it's an hourly schedule I think it does meet all of your requirements.
