### ISSUE TITLE
Transfer setup?

### ISSUE THREAD

**Issue by Lukuntz** [Lunat1q/Catchem-PoGo#1331]
Okay, i'm sorry because I know that have been post several times before...
But I'm sharing my setup config because I've been getting this for half of the day.
And it really don't follow the setup I've put in the transfer config, I have like 100 poke (-1000CP / -85IV)

![transfer 1](https://cloud.githubusercontent.com/assets/21320981/18223488/e2e1a452-71b8-11e6-904c-697ec800ec45.png)
![transfer 2](https://cloud.githubusercontent.com/assets/21320981/18223489/ee858594-71b8-11e6-9b48-32c523bbc725.png)

Can you guys share yours, and tell me if it works fine?

**Comment by Lukuntz** [comment]
NVM I've just discovered I can do it manually using shift or ctrl....

**Comment by Spk345** [comment]
You also should take certain pokemon off your "can evolve" list. Keep only the cheap pokemon and transfer the rest. Make sure they are not on your "not to transfer" list or you'll just hoard them. The bot randomly transfers, but that issue is due to all of them not being allowed to transfer.
