### ISSUE TITLE
] (ATTENTION) Character is too busy if you try to much -.-

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#1332]
If i try to transfer more than 15 Poke´s or try more than 15 Pokes to evolve i get this error and the Bot freez "] (ATTENTION) Character is too busy, proballby you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - ignore that message"

**Comment by Lunat1q** [comment]
Update to latest
