### ISSUE TITLE
new proposition and a new bug 

### ISSUE THREAD

**Issue by zhach01** [Lunat1q/Catchem-PoGo#1335]
i noticed this error every 1:30 min Niantic Servers unstable, throttling API Calls and after that the bot change rout. is it a bug caused by the bot when changing routs or something impracticable? 
-if it the first case i propose adding a delay around 2 min when no command is executed just waiting before changing routs.
-in case of impracticable error : it could be caused by to much command uploaded to the server in a single time . possible fix reduce the number of server calls uploading and downloading to reduce server traffic and increase chance of avoiding ban 
*****************************new enhancement list that could be helpful***********************************
-adding a self shutdown and wake up to stop start the bot( little schedule for number of working ours of the bot)
-adding a dynamic label between the incubator and amount label to indicated the needed distance to travel and the remaining distance .
-add new telegram command like: $ list_all_poke to list all pokemon cp and iv candy
                                                  $ list_inventory to list all the items
                                                 $ stop_bot_and_get_last_location to prevent soft-bean
                                                 $ hatched_report like auto_report to report hatched pokemon
******************************************************************************************************************
i will say thanks for this amazing bot i tried to download the open source and experiment with it to solve many problems but informally i faced a lot of errors when i try to compile it so for that i am posting each request instead of testing it . please try your best in implementing and solving those problems and adding new stuff . keep up the great work @vmwiz @Lunat1q @CDAGaming @kchen-tw @akira02

**Comment by Spk345** [comment]
I have not noticed an issue with Throttle API calls. I rarely get any on default settings. Unless you get more than 5 in an hour of bot time, you are fine. Over five and you should increase your delays. I do not believe route changing is what is causing that. It just random. I'm currently on 5 hrs + of bot time and no Throttling API calls. Decrease to default delays if you continue to experience issues.

#ROADMAP on Discord lists things that Lunatiq will be working on the future after the current additions are debugged. Scheduling bot start/stop times is on Roadmap. 
The dynamic label might induce too many calls to Niantic Servers and could end up getting your bot more Throttling API calls.
I believe he is working on more telegram features.

If you have any other issues, I suggest you join the discord and be a part of the discussion of features.
-Spk345

**Comment by zhach01** [comment]
@Spk345 thanks so much for the clarification i am intending to try increasing the the bot delay by multiple of 2 and hopping it is just a random .
for the dynamic label i know that it will jam the server with calls if its called after every command or every second but if it is implemented and called once every 7 min or 10 min  it will not cause a big traffic and it will make the bot more realistic because every player check his incubators once or twice every hour. @Lunat1q @CDAGaming @kchen-tw @Spk345

**Comment by Spk345** [comment]
As far as I know, the log lists how far you've gotten on you incubators every 10 minutes. And every time one hatches.
