### ISSUE TITLE
В последних двух обновлениях стали плохо прогружаться покепосты

### ISSUE THREAD

**Issue by VladimirFAD** [Lunat1q/Catchem-PoGo#1336]
![go](https://cloud.githubusercontent.com/assets/21343278/18224082/ba60be4a-71d2-11e6-8673-2be80d8806d6.png)
В последних двух обновлениях стали плохо прогружаться покепосты

**Comment by fullme** [comment]
Use english.
Use MapzenValhalla routing and will fix your problem.

**Comment by VladimirFAD** [comment]
Does not solve
