### ISSUE TITLE
no usable pokestop with the newest version but it work normally when i used older version

### ISSUE THREAD

**Issue by PsychoRaven** [Lunat1q/Catchem-PoGo#1337]
What's wrong with catchem v1.4.9.4 and v1.4.9.3 it says "no usable pokestop" buut when i use catchem v1.4.7.0 it works normally, so what's the matter?

**Comment by fullme** [comment]
Download it again, try to unlock your .7z before unzipping it. (Right clik>Properties>Unlock)

**Comment by Spk345** [comment]
There is a new setting called "loot pokestops", You need to have that checked. Started in 1.4.9.3. If that doesn't work, join us on the Discord.

**Comment by PsychoRaven** [comment]
I got it, its works again, thank you so much @fullme 
@Spk345 thanks :)
