### ISSUE TITLE
out of pokeballs, no PokeStops spinning

### ISSUE THREAD

**Issue by danilito78** [Lunat1q/Catchem-PoGo#1339]
I have no PokeBalls in my inventory, I have it set to keep 100 of them.  My avatar is still walking, but the only info I get is that it's walking to a PokeStop, not getting any items or XP, and then walking to the next stop.  

Went back to look at my logs, seems like I stopped getting any items the first time I ran 1.4.9.4.  Only have 145/350 items, so not full.  

Is this just a ban, or just an issue with the new release?

**Comment by Spk345** [comment]
Did you make sure your settings have "Loot Pokestops" checked?

**Comment by kingsley7601** [comment]
maybe an ip ban

**Comment by magicdev2** [comment]
you are not ipban but soft ban

**Comment by magicdev2** [comment]
have you teleport it today?

**Comment by alanearl** [comment]
Soft Ban.. restart modem to renew ip address.

**Comment by Spk345** [comment]
If setting "loot pokestops" is checked and you are not able to spin pokestops, you are temporary ip banned. It will lift in 2-48hrs. If you have a dynamic ip address from your Internet provider, power cycling your router will give you another iP address. 

How did you get ip banned? You ran too many bots on one ip address, or you are using a free proxy. It is advised that you don't use more than one bot on one ip address or proxy. Free proxies are usually ip banned constantly, thus opt for a paid proxy that supports pokemongo (ssl proxy).

**Comment by triski** [comment]
Its 1 of 2 things
1. IP ban (soft/hard)
2. Have you verified the email of the PTC account?

I did not do it, because email had not arrive, they let you use it for 48 hours then stop the account until it has been verified.
