### ISSUE TITLE
(ATTENTION) Mapzen Valhalla API Key is Empty!

### ISSUE THREAD

**Issue by lucashtw** [Lunat1q/Catchem-PoGo#1341]
I did exactly as it says in the tutorial, however neither mapzen or google directions come to work.
![asdfg](https://cloud.githubusercontent.com/assets/11354908/18224955/abe61ff0-71bd-11e6-8b95-d41a5650335d.png)

**Comment by magicdev2** [comment]
you put mapzen elevation api

**Comment by magicdev2** [comment]
uncheck that and you will be fine.

**Comment by lucashtw** [comment]
thank you I had forgotten this detail after test forgot to remove the tag. thank you.

**Comment by Spk345** [comment]
Valhalla api key is in elevation slot, move to valhalla routing box. Check settings and make sure you have option "loot pokestops" checked.

**Comment by lucashtw** [comment]
@Spk345 I had unchecked the box Valhalla and tested and had not worked, but it was my fault he did not see the box "pokestops" is now functioning normally. thank you young.

**Comment by kingsley7601** [comment]
your key goes in the v routing box and select it in the menu above as well and it should work

**Comment by kingsley7601** [comment]
your getting the error cause you put the api key in the wrong box which is why its says its empty because theres no key there

**Comment by lucashtw** [comment]
has already been resolved, you do not need to repeat the solution. :)

**Comment by kingsley7601** [comment]
You sounded like you ended up using google directions instead of mapzen valhalla routing. :)

**Comment by gianncalderon** [comment]
[10:21:12] (ATTENTION) MobBotRouting API Key is Empty!
