### ISSUE TITLE
[QUESTION]How do I use lucky egg?

### ISSUE THREAD

**Issue by toshiossada** [Lunat1q/Catchem-PoGo#1344]
How do I use lucky egg?

**Comment by Spk345** [comment]
Enable the setting "use lucky egg when evolving" and it will automagically use it when you get enough candies and pokemon to evolve. You can also set how many that is as well. Max humanly possible would be 60 evolutions.

**Comment by Spk345** [comment]
Also make sure you have setting "evolve pokemon with enough candies" checked.
