### ISSUE TITLE
old attacks when pokemon evolves

### ISSUE THREAD

**Issue by kertiek** [Lunat1q/Catchem-PoGo#1345]
i evolved a magikarp and the gyarados still shows the attacks of the magikarp when u see the info of the pokemon :O

**Comment by petoe93** [comment]
maybe u just got a crappy gyarados :/

**Comment by kertiek** [comment]
it was still showing the attacks of the magikarp .. i just did a relogin (stop and start) and then the moves got updated to those of the gyarados ..... since gyarados cant do a "splash" .. i knew they were wrong.

**Comment by CrisOng** [comment]
Same here Rhydon have a Rhyhorn's main moves Horn Attack.
It is fine, just wait for the refresh then will go back to normal.

**Comment by alanearl** [comment]
Try to login on your smartphone :D
