### ISSUE TITLE
IP BAN

### ISSUE THREAD

**Issue by xcuts1** [Lunat1q/Catchem-PoGo#1346]
I ALWAYS GET THIS ERROR WHEN BOTTING MULTIPLE ACCOUNTS. ANY SUGGESTIONS?

**Comment by wagas** [comment]
use proxy

**Comment by petoe93** [comment]
yeah lets just type everything in caps..i'll get my attention for sure..smh

**Comment by Sauloerick** [comment]
how do i get a proxy?

**Comment by Initiols** [comment]
don't use many bots at a time
you'll get spotted everytime and get IP banned
(and don't use free proxy, it's gonna be even worse)

**Comment by Spk345** [comment]
One bot per ip address. If you wish to run more than one at a time, then you should either buy a paid proxy or vpn service.  General rule of thumb with free proxies is this: "if you were able to discover this free proxy, someone has already, and it's IP Banned." 

A good pokemon go proxy will use SSL encryption. I recommend:
https://www.sslprivateproxy.com/billing/aff.php?aff=684
Just click on Our Solutions And click on Pokemon Go Proxies.
POKE20 is the code for 20% off

**Comment by alanearl** [comment]
Restart modem every time you experience IP Ban.
