### ISSUE TITLE
Crash when using wrong password

### ISSUE THREAD

**Issue by vandroiy8** [Lunat1q/Catchem-PoGo#1347]
Just a small issue i noticed, the program crashes when you use google login (maybe also PTC) and got the wrong password. easily reproduceable, tested on 2 computers. Windows 10 64bit

**Comment by Spk345** [comment]
Interesting. That might explain some recent errors. Will try and reproduce.

**Comment by Spk345** [comment]
#1378 
Oops, made a new issue thread. This is a reproducible bug a workaround until fix is listed in my thread. Thank you for bringing this to our attention.

**Comment by Lunat1q** [comment]
fixed
