### ISSUE TITLE
No pokemons.. At all

### ISSUE THREAD

**Issue by Tillian1243** [Lunat1q/Catchem-PoGo#1349]
Bot is working fine and all,but at some point bot stopped catching pokemons(Like not they are flying away,there are just no pokemons on the map)

**Comment by L3Ente** [comment]
Maybe the Auto pause option on the setting is on 
u have to turn it off or change the max settings to an number like 50000000 pokestops per/h

**Comment by Tillian1243** [comment]
Thanks,but the problem not with pokestops. Pokestops working perfectly fine

**Comment by Tillian1243** [comment]
Problem solved,thanks. There was no tick on "Catch Wild Poke"
