### ISSUE TITLE
Paused vs. stopped bot and Telegram info

### ISSUE THREAD

**Issue by thefraggle** [Lunat1q/Catchem-PoGo#1350]
Would be great if wie could geht a Telegramm status if the bot is paused because hourly conditions are met.

Also: would it be possible to add a paused status in addition to Start and stop?
If the bot has stopped (paused) and i Start anotjer one, the first one resumes automatically. And i habe no Chance to keep it stopped. Or stop the Pause timer.

**Comment by Lunat1q** [comment]
done
