### ISSUE TITLE
[Feature Request] Evolve higher level Pokemon before their lower level counterparts

### ISSUE THREAD

**Issue by lordcheetah** [Lunat1q/Catchem-PoGo#1353]
Ivysaur before Bulbasaur for instance

**Comment by Spk345** [comment]
I believe you can choose ivysaur as a "pokemon to evolve", in your pokelists, but that's as close as we can get currently. I like this idea of prioritizing spawns.

**Comment by Spk345** [comment]
Evolves*

**Comment by lordcheetah** [comment]
That's a good idea in the meantime

**Comment by Lunat1q** [comment]
tbh... it's absolutelly oposite, cause bot use evolve as the way to get level.
