### ISSUE TITLE
default settings

### ISSUE THREAD

**Issue by lucashtw** [Lunat1q/Catchem-PoGo#1359]
hello, I wanted to know if you have any problems I leave more than 24 hours on bot with the default settings.
I believe it would be beneficial pause to avoid ban, but as the bot already to when it reaches the limit per hour, does anyone know if you have any problems leave it on?

thank you.

olá, eu queria saber se tem algum problema eu deixar o bot ligado mais de 24h com as configurações padrões.
Eu acredito que seria benéfico pausar para evitar ban, mas como o bot ja para quando chega ao limite por hora, alguem sabe se tem algum problema deixar ele ligado?

obrigado.

**Comment by alanearl** [comment]
I don't have any problem leaving it for 12 hrs. The bot will rest anyways. The only problem that you will encounter is you will pay more on your electric bills :D
