### ISSUE TITLE
[Enhancement] User Command List

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1363]
Dear Dev Support,

I would like to contribute an idea about User Command List.
It can really prevent problem in bot activities.

![capture](https://cloud.githubusercontent.com/assets/648116/18227837/f1b1d162-7264-11e6-9e77-e7929c024b79.PNG)

The bot will check user command list if not busy & execute all manual user command.

Hope you like the idea :)

Keep up the good work!

**Comment by Lunat1q** [comment]
You mean hide commands if bot is too busy, right?

**Comment by alanearl** [comment]
Hmmm better the user command list will be shown so that the user will know if his command is already execute or not. Also i prefer the bot will stop/pause from all his activities when executing all of the user manual command list.

**Comment by alanearl** [comment]
My point on this example is to prevent the bot from catching pokemons while it is on transferring pokemon by used of (user manual command) or  preventing the bot from catching pokemons while it is on power up by used of (user manual command).

![capture](https://cloud.githubusercontent.com/assets/648116/18233872/8e5becac-7326-11e6-9801-2348d783319a.PNG)

Keep up the good work :)

**Comment by Lunat1q** [comment]
It's already done, there is a controller of BotState to prevent different actions at the same time.
Well, i still didn't get your idea, cause for now, it's already working with bot state checking. There is no way to add queue of commands, cause it require complete API rewrite, and can cause some bugs.
So for now - Automatic API > manual one, but if manual one started it's rouite, automatic will wait till it's done.

**Comment by alanearl** [comment]
Well if that is the case of the latest bot i will agree with you.
I will try to power up poke to max level if it will not do actions at the same time.

Keep up the good work :)
