### ISSUE TITLE
evolve

### ISSUE THREAD

**Issue by vfedele** [Lunat1q/Catchem-PoGo#1364]
Can I chose pokes not to evolve? I mean, all I managed to do is, evolve all or evolve none.

PLUS
what the number on "info" screen means? stardust pke and xp. all colored

**Comment by thereyrey** [comment]
Poke List Settings "to evolve"..

Just remove/add what you want...

**Comment by vfedele** [comment]
the bot evolved all I had, including what wasnt on the list

**Comment by alanearl** [comment]
Uncheck "Evolve all Poke above IV".
Update you .NET Framework to latest version.
