### ISSUE TITLE
[Request] Pair the bot with a pokemon tracking system (like fastpokemap)

### ISSUE THREAD

**Issue by Drakumor** [Lunat1q/Catchem-PoGo#1365]
It would be awesome to see all the pokemons around the bot with their timer !
You could click on the pokemon you want to catch and then the bot would walk toward it to catch it (if there is enough time depending on how fast the bot is walking). If the bot was on a custom route, then he could came back to it after he caught the pokemon.
I dont even know if that's possible, that's why i'm asking ^^

Thanks for everything you do for the community !

**Comment by silencer13ruiz** [comment]
That would be great if it can be done

**Comment by alanearl** [comment]
Possible User BAN on these kind of feature :)
