### ISSUE TITLE
Doesn't show or spin pokestops or find and catch pokemon

### ISSUE THREAD

**Issue by freshcornbread** [Lunat1q/Catchem-PoGo#1369]
I have the latest version of the bot, and it doesn't show any pokestops in the area. It gives me a message saying "(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?" I have the bot in an area where there are pokestops everywhere.

**Comment by alanearl** [comment]
Soft IP Ban. Reboot your modem.

**Comment by freshcornbread** [comment]
How do i prevent this from happening again in the future?

**Comment by freshcornbread** [comment]
Thank you so much.
