### ISSUE TITLE
Coordinate continues not working

### ISSUE THREAD

**Issue by skzbr** [Lunat1q/Catchem-PoGo#137]
I know you are working hard for this, but is the same problem;

http://prntscr.com/c6ho70

**Comment by skzbr** [comment]
After the problem coordinates get: http://prntscr.com/c6hu9i

it was: 
-23,586249
-46.655582

**Comment by skzbr** [comment]
[14:01:59] System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Nome do parâmetro: Latitude
   em GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) na C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:linha 109
   em PoGo.PokeMobBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) na C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\Utils\LocationUtils.cs:linha 16
   em PoGo.PokeMobBot.Logic.MapCache.<>c__DisplayClass6_0.<UpdateMapDatas>b__4(FortData i) na C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:linha 65
   em System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   em PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() na C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:linha 76
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() na C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:linha 21
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() na C:\Users\m.podolskiy\Desktop\Ketchum_dev\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:linha 38

**Comment by Lunat1q** [comment]
Contact me in Discord, we will try to handle it.
