### ISSUE TITLE
[Suggestion] Telegram /newbot, /delbot

### ISSUE THREAD

**Issue by LionDev514** [Lunat1q/Catchem-PoGo#1371]
It would be good to include a command to the bot telegram that allow you to create a new bot.
as:
newbot
and from here you begin to ask the parameters required

**Comment by Cryptologism** [comment]
Also maybe to deletebot or need to edit bot...

**Comment by Lunat1q** [comment]
sorry, creating/deleting bot will not be able for now.
We will do edit bot config remotely probably.
