### ISSUE TITLE
Log in error

### ISSUE THREAD

**Issue by vjikr** [Lunat1q/Catchem-PoGo#1372]
![error](https://cloud.githubusercontent.com/assets/21979347/18228617/1955590e-7289-11e6-98ee-c3221c9ce980.jpg)

Having this issue.. my account can't log in... Please help me

**Comment by h3viin** [comment]
Wich lvl?

**Comment by vjikr** [comment]
my trainer level is 29..

**Comment by h3viin** [comment]
Try login on your phone?

**Comment by vjikr** [comment]
I can log in on my phone but in catch'em bot this is what happening

**Comment by alanearl** [comment]
Try to change password on your google account.
