### ISSUE TITLE
READ THIS BEFORE CREATING AN ISSUE!!!

### ISSUE THREAD

**Issue by Bay101** [Lunat1q/Catchem-PoGo#1373]
Please only post actual bugs as issues!
**If The Duplicate Issues Do Not Stop We Will Be Forced To Close The Ability To Create Issues!**

If you have an actual bug please ensure that you read all of the issues already made before creating a new one, this includes all of the closed issues.

Also before creating an issue or going to Discord for help please view the Wiki for information on setup and FAQ: https://github.com/Lunat1q/Catchem-PoGo/wiki

For any issues or help that you require please ask on our discord server: https://discord.me/Catchem

**Comment by alanearl** [comment]
Maybe we need to create forums on CATCHEM :D

**Comment by magicdev2** [comment]
really.... let me read that again 

Please only post actual bugs as issues!
If The Duplicate Issues Do Not Stop We Will Be Forced To Close The Ability To Create Issues!

If you have an actual bug please ensure that you read all of the issues already made before creating a new one, this includes all of the closed issues.

Also before creating an issue or going to Discord for help please view the Wiki for information on setup and FAQ: https://github.com/Lunat1q/Catchem-PoGo/wiki

For any issues or help that you require please ask on our discord server: https://discord.me/Catchem
wait.... If The Duplicate Issues Do Not Stop We Will Be Forced To Close The Ability To Create Issues! what.... really are you for real.... wow...

**Comment by Spk345** [comment]
Actually, only Lunatiq and Bay were the only ones who could close issues up until today, so that was adding a lot of workload to the both of them. @magicdev2
