### ISSUE TITLE
[feature] Duplicate/Clone profile

### ISSUE THREAD

**Issue by valdirljr** [Lunat1q/Catchem-PoGo#1375]
A right click to clone/duplicate profile

**Comment by KoopaTheTurtle** [comment]
If you go to where your folder is theres a folder with Profiles. Open that up and you can copy and paste that way

**Comment by alanearl** [comment]
Why not just copy paste the user profile inside the profiles folder?

**Comment by Lunat1q** [comment]
Use BatchCreator.
