### ISSUE TITLE
how to use incense

### ISSUE THREAD

**Issue by pcswatertown** [Lunat1q/Catchem-PoGo#1377]
Not sure how to use incense . We have a time delay for catching incensed pokes .Thanks ?

**Comment by KoopaTheTurtle** [comment]
there is no way of using Incense through the bot :/

**Comment by Spk345** [comment]
Using incense is on the #roadmap. It is not currently possible to use incense in game yet.

**Comment by kadirboz** [comment]
they are working on it: https://github.com/Lunat1q/Catchem-PoGo/pull/1172

if u will open the issue, please search once: https://github.com/Lunat1q/Catchem-PoGo/issues?q=is%3Aissue+is%3Aclosed

a lot of people ask this

**Comment by alanearl** [comment]
Maybe in the future just wait :)
