### ISSUE TITLE
[Bug] Catchem.exe crashes with Invalid Password

### ISSUE THREAD

**Issue by Spk345** [Lunat1q/Catchem-PoGo#1378]
Catchem.exe crashes if one bot profile has an invalid password. It will crash upon startup, if bot with invalid password is set to auto-start. It will also crash if bot has invalid password and it is started manually. This has been observed by three testers.

Possible workaround until fix:
Catchem > Profiles > "Bot Name" > Auth.txt
*Make sure your username and password are correct. Check by logging into another device, or PTC website. 

I hope this helps others with their issues. If you have any questions or need further help, join our discord server:  https://discordapp.com/invite/p6nTp

**Comment by Spk345** [comment]
If auth.txt is accurate, and bot is set to auto-start, try deleting the offending profile, and recreating. Good luck!

**Comment by guiguigui222** [comment]
guy you just need to verify your email adress ...

**Comment by Lunat1q** [comment]
fixed
