### ISSUE TITLE
Player won't follow RouteCreator 

### ISSUE THREAD

**Issue by Chris13564** [Lunat1q/Catchem-PoGo#1379]
I have put on use custom route and picked my one. Yet my character still does his own random thing

**Comment by Initiols** [comment]
Didn't you checked "Use Custom Route", and selected you route there ?

**Comment by delete30** [comment]
1.bro.u must check the "use custom route" option,,,
2.must use the the catchem's create router,not gpx files@

**Comment by Chris13564** [comment]
i've done both of those though

**Comment by Chris13564** [comment]
do i have to enter anything into the api keys

**Comment by Spk345** [comment]
Yes, or use manual route when building your route. Manual route will path through buildings and lakes though, so beware. Routing services allow your bot to know where roads are.

**Comment by kingsley7601** [comment]
yup yup you need api keys to allow human pathing enter your api key for the routing service your using

**Comment by kingsley7601** [comment]
https://developers.google.com/maps/documentation/directions/get-api-key (where to get your google directions api key)
