### ISSUE TITLE
find the crash reason after 10hours with screen off (but pc on)

### ISSUE THREAD

**Issue by raulken78** [Lunat1q/Catchem-PoGo#1380]
the KEEP POKE MAKERS will be too many pokemon and it cause crash.

for repeat:
open bot
set screen off after 5minutes of no pc use (no mouse or keyboard)
after 5minutes screen is off but pc continue to run bot
after 10 hours I touch mouse, screen is on and bot try to design too many pokemon makers and crash

**Comment by Spk345** [comment]
I haven't encountered this issue yet, I always leave pokemarkers on, with two bots running, for 13hrs straight. Is this only in newest release or previous as well?

I will bring this issue up to @Lunat1q .

**Comment by alanearl** [comment]
Update .NET Framework
Disable PC Hibernate
Increase Pagefile (Virtual Memory).

Under Settings Tab
Max Catch Per Hour 1008
Max Pokestops Per Hour 1488
Max XP Per Hour 0
Max Stardust Per Hour 0

This setting is for 24 Hrs :) Enjoy.

**Comment by kaku1237** [comment]
hi alanearl

is that safe with max catch i have recently read an article regarding other bots from banning maxmum of pokestops and pokemon range from 1000 per day. 

Best regards

**Comment by alanearl** [comment]
Yeah its true, but you will only need to bot around 6-10 hrs for safety.
After that close the bot. 
I think there's a crash bug if the bot will sleep & wakeup automatically.
But still more testing should be done.
Just use 42 catch per hour if you want 10 hours that should be 420.

**Comment by Cowering** [comment]
I only have room for 250 pokemon. Mine stops catching them at 241 however, with endless msg:

Pokemon Inventory is full! Please transfer Pokemon manually or set TransferDuplicatePokemon to true in settings...

but it never crashes, just keeps hatching eggs and looting pokestops
