### ISSUE TITLE
[11:08:14] (INFO) Character is too busy, proballby you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - IGNORE that message, and don't send git issue!

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#1381]
If i try to transfer more than 15 Poke´s or try more than 15 Pokes to evolve i get this error and the Bot freez "] [11:08:14] (INFO) Character is too busy, proballby you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - IGNORE that message, and don't send git issue!

Try to walk and try to Transfer

And the Bot Dont use Lucky Egg at Evolve....

Still agian, i use the news Version, any Help?

**Comment by fullme** [comment]
Can you put a screenshot, like this :
[http://i.imgur.com/OAodkB7.png](url)

**Comment by Charlier69** [comment]
Sure :)
![unbenannt](https://cloud.githubusercontent.com/assets/21181078/18230722/d8671aec-72a4-11e6-93fe-e1c4f47acc7f.png)

**Comment by kaktusisko** [comment]
IGNORE that message, and don't send git issue!
