### ISSUE TITLE
Bot doesn't always see Gym?

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1382]
when I direct bot to gym locations, sometimes bot see it, sometimes does not

**Comment by Spk345** [comment]
Would you care to show a screenshot? Is it always the same one? Does it vary?

**Comment by saldotman** [comment]
it varies.
sometimes, the first time bot comes to location, bot doesn't touch the gym.
when I direct for the second time, bot touch the gym.

will try to produce screenshot later.

**Comment by Spk345** [comment]
Interesting. Let us know if it continues to happen.

**Comment by saldotman** [comment]
![image](https://cloud.githubusercontent.com/assets/21153898/18231102/1732ad66-72d9-11e6-9673-2611330a51a7.png)
![image](https://cloud.githubusercontent.com/assets/21153898/18231103/1b108944-72d9-11e6-9207-0a6a6cae7d4b.png)
![image](https://cloud.githubusercontent.com/assets/21153898/18231105/220c2460-72d9-11e6-855a-da79fb900731.png)

can you see the pic?
I don't know how to put pic here. I just copy to clipboard and paste here

I think bot will never touch the gym if there are no pokestop around it.
if there is pokestop around a gym, there probably bot touch the gym.

just guessing

**Comment by saldotman** [comment]
![image](https://cloud.githubusercontent.com/assets/21153898/18235021/cb253004-733e-11e6-8f6e-bf469c345e3d.png)

if you see the blue gym,
that's quite interesting, since it still far away, but bot touch it.
compared to my first post, where bot already at gym location, but bot doesn't touch it.
