### ISSUE TITLE
Error getting Tauros

### ISSUE THREAD

**Issue by Gigantone** [Lunat1q/Catchem-PoGo#1383]
Hello. I'm constantly get this error messages:
[10:05:25] (BERRY) Using Razzberry. Berries left: 28
[10:05:29] (PKMN) Throwing Spinning Excellent! MasterBall - WILL HIT
**[10:05:29] (ERROR) (Error) | Tauros, Lvl: 15 | CP: (739/1540) | IV: 61,35% | Type: Normal | Chance: 23,19% | Dist: 67,44m | Used: MasterBall (0 left) | XP: 0 |** 
[10:05:42] (BERRY) Using Razzberry. Berries left: 27
[10:05:45] (PKMN) Throwing Great! MasterBall - WILL HIT
**[10:05:46] (ERROR) (Error) | Tauros, Lvl: 15 | CP: (739/1540) | IV: 61,35% | Type: Normal | Chance: 23,19% | Dist: 69,15m | Used: MasterBall (0 left) | XP: 0 |** 
[10:05:59] (BERRY) Using Razzberry. Berries left: 26
[10:06:02] (PKMN) Throwing Spinning Excellent! MasterBall - WILL HIT
**[10:06:02] (ERROR) (Error) | Tauros, Lvl: 15 | CP: (739/1540) | IV: 61,35% | Type: Normal | Chance: 23,19% | Dist: 77,18m | Used: MasterBall (0 left) | XP: 0 |** 
[10:06:15] (BERRY) Using Razzberry. Berries left: 25
[10:06:19] (PKMN) Throwing Spinning Excellent! MasterBall - WILL HIT
**[10:06:19] (ERROR) (Error) | Tauros, Lvl: 15 | CP: (739/1540) | IV: 61,35% | Type: Normal | Chance: 23,19% | Dist: 78,12m | Used: MasterBall (0 left) | XP: 0 |** 

I'm in Europe, if it matters...

Thank you

**Comment by fullme** [comment]
Don't care about your location.
I see some wtf stuff here, bot says MasterBall 0 left and try to throw a Masterball...try to check if you have any Masterballs on your bags and try to down "Ultraball below catch probability" to 0,05 and "Masterball below catch propability" to 0,03 and see what happens.

**Comment by xGuardianx** [comment]
I know this Problem...
Go to "Poke List Settings" and delete Tauros from the List "to use Masterball".
Then it should work good... ;)

**Comment by Gigantone** [comment]
Hello.

After configuring both solutions, it worked!

Thanks!
