### ISSUE TITLE
Stay at current position

### ISSUE THREAD

**Issue by iwantlevel** [Lunat1q/Catchem-PoGo#1384]
Hi, i would like to know if it is possible to make the bot stay at current position instead of walking around? (What setting can I set?)

**Comment by Spk345** [comment]
Not available yet. Lunatiq is working on it.

**Comment by fullme** [comment]
Best way for now is to do a custom route.

**Comment by alanearl** [comment]
In the future just wait :D

**Comment by KitazawaMoa** [comment]
You can create a custom route for it
Or disabled your discovery pathing and reduce your max travel distance,it's work for some ppl

**Comment by kingsley7601** [comment]
set walking speed to 0. that will help

**Comment by wagas** [comment]
set walking speed to 0.00001

**Comment by goiabs** [comment]
It is not available yet. But you can set Min and Max Walking Speed to 0, turn off "Use Discovery Pathing" and set "Max Travel Distance in Meters" to 0. It will make the bot stand.
