### ISSUE TITLE
[BUG] Poke markers will not clear on bot waking up.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1386]
Dear Dev,

I think poke markers will not clear when the bot will fall at sleep then waking up.
Also maybe this can cause crash on catchem.

Could you please check this.

![capture](https://cloud.githubusercontent.com/assets/648116/18230343/2ea1c662-72ca-11e6-82df-40831d5a890e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/648116/18230351/6df97ddc-72ca-11e6-8c22-f34faeebb708.PNG)

Keep up the good work!

**Comment by Lunat1q** [comment]
should be fixed
