### ISSUE TITLE
Altitude is vary strongly

### ISSUE THREAD

**Issue by xGuardianx** [Lunat1q/Catchem-PoGo#1392]
I have the feeling the current Altitude is changing very strongly and makes problems. Sometimes the Bot found no Pokemon or Pokestops and I have to set it manually between 11 na 14 again.

Is it a bug? Does somebody else have the same problem?
Or did I anything wrong?

![1234](https://cloud.githubusercontent.com/assets/20952999/18231615/347477f8-72be-11e6-9adf-76955e81eea1.JPG)

**Comment by goiabs** [comment]
Turn on the "Use Human Pathing" and "Use Mapzen Elevation API". And if you dont have a Mapzen Elevation Api, do it and paste in the correct field.
