### ISSUE TITLE
I cant rewrite PokemonsTransferFilter in config

### ISSUE THREAD

**Issue by BSwazZ** [Lunat1q/Catchem-PoGo#1393]
![rewrite](https://cloud.githubusercontent.com/assets/20690071/18231636/21b2d6e0-72bf-11e6-958f-0a9567992095.PNG)
 i cant chance values pls help guys.

**Comment by fullme** [comment]
Does soft running, don't care if bots are running or not ?

**Comment by Lunat1q** [comment]
turn off - do changes - start again.

**Comment by BSwazZ** [comment]
doesnt work. bot not start.
