### ISSUE TITLE
Evolve Pokemon Delay - Delays with some actions but not others

### ISSUE THREAD

**Issue by fdeleo** [Lunat1q/Catchem-PoGo#1399]
I have noticed on my Pokemon Evolve delay, that it was mostly having delay between things like:
- Transfer Pokemon
- Recycling items
(Things that the user would do normal actively on the bot or predefined a routine as those active actions)

But I had no delay between evolving and catching a pokemon for example.
So I was catching a pokemon 9s after evolving, I thought that would be kind of strange as human behavior. I did not get a ban or anything but I was preventing evolving worried about a pokemon spawn appearing while doing the route and getting not delay.

**Comment by fdeleo** [comment]
I have also found one issue similar to this one.

I´ve got a pokemon FAVOURITE in between throwing pokeball and catching the pokemon. (I believe it could also happen with transfer pokemon, but did not  test or saw that yet)

**Comment by kingsley7601** [comment]
The delays are there for the reason of humanizing the bots actions. You can edit these delays under the delays section. And the bot stays still while evolving pokemon. Your last issue may be a bug and more testing is required but i havent experienced this yet.

**Comment by Spk345** [comment]
This is using newest release correct?

**Comment by fdeleo** [comment]
Actually it was 1.4.9.4 update 2, I just noticed the new release, 1.5.0.
I might try with the new, and if something else happens I will post here.

Better the log description with the time between actions?

**Comment by Spk345** [comment]
He fixed a lot of minor noted issues occuring with delays. If you still experience issues with new bot, please open a new Issue, ok? I'm going to close this one.
