### ISSUE TITLE
Cant open bot

### ISSUE THREAD

**Issue by EnzzoCaaue** [Lunat1q/Catchem-PoGo#1400]
After release of 1.5 i could not open Catchem. No error apears even if I run as admin. Just do not open.

**Comment by kingsley7601** [comment]
you might have entered your google/ptc login wrong and clicked autostart try and delete your profile from your Catchem Bot folder if this is the case.

**Comment by Spk345** [comment]
You do not have to delete your profile. You can turn autostart off by accessing config.txt in your profile folder and change Autostart from True to False. Doublecheck your Auth.txt to make sure your password is correct.

**Comment by Spk345** [comment]
If you continue to have issues, let me know. Thank you.
