### ISSUE TITLE
[Feature] Keep minimum number of Pokemon from evolving

### ISSUE THREAD

**Issue by lordcheetah** [Lunat1q/Catchem-PoGo#1401]
I'd like to keep one of each Pokemon

**Comment by kingsley7601** [comment]
The feature is already here if you want to keep one of each pokemon check 'transfer duplicate poke' and select ' 1 ' under 'keep min duplicate'

**Comment by lordcheetah** [comment]
That's for transferring, not evolving

**Comment by Spk345** [comment]
Are you sure you want to cut 151 pokemon into your storage? Why would you like this feature?

**Comment by lordcheetah** [comment]
Right now, if I have enough candies the bot will evolve all my Pidgeys into Pidgettos and then I wouldn't have any Pidgeys. If I'm trying to collect one of each Pokemon, I don't want to evolve all the lower Pokemon evolutions away.

**Comment by lordcheetah** [comment]
Manually, I've been evolving all but the second best Pokemon, then transferring the left overs (both evolved and not). At least for common Pokemon. This way I keep promoting the best Pokemon while keeping my collection of each Pokemon.

**Comment by Virusdead49** [comment]
@ lordcheetah you can put your parameter
