### ISSUE TITLE
[Feature Request] Setting route change in schedule

### ISSUE THREAD

**Issue by Biera2** [Lunat1q/Catchem-PoGo#1402]
would be nice to implement automaticly change saved custom routes on selected hours in the sheldue
also
would be nice that the bot when time hits sheldue to set off, get back to starting cords just like person would return to home and when the time in sheldue hits the bot to start, it will start from starting coords just like person would get out of home :D
i hope it's clearly :D

**Comment by Spk345** [comment]
Schedule changes route during selected hours.
Selecting a "Home" point that bot starts and stops at.

**Comment by Spk345** [comment]
Compiled into one list: #1419
