### ISSUE TITLE
Show only selected pokemon on Maps for "Keep poke marquers"

### ISSUE THREAD

**Issue by Dracula06** [Lunat1q/Catchem-PoGo#1403]
A little window to choose pokemon to show or not on the maps when "Keep poke marquers" is selected

I m french sorry for my bad english...

**Comment by Spk345** [comment]
You can add pokemon to the "Not to Catch" Pokelist and the bot will not mark them on your map.

**Comment by Dracula06** [comment]
You don't understand what i mean.
I want to catch them all, but want that only selected ones appears on map when "keep poke markers" is checked.
