### ISSUE TITLE
bad two moves calculation

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1404]
which two moves, it is not as simple as taking the highest DPS of each type and adding them together. We must calculate the DPS of a full “cycle” of moves. Since the charge move requires a certain amount of energy to be used, the quick move must be used a certain number of times until that energy is amassed.

**Comment by Spk345** [comment]
I will bring it up to @Lunat1q but I do not believe he wants to code movesets. It's difficult and a long process.

**Comment by Lunat1q** [comment]
ehm... i got your opinion, i'll think about that

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/yU0afE3.png)
should be like that

**Comment by GandalfLeRouge** [comment]
it's ok for moves with more than one fill bar (you store extra energy for next moves2)
for moves with one fill bar (Blizzard for example) you need to add a trunc() +1 to movesToDo because you lost a part of energy when the bar is full

but even like that it's much more better than average of moves 1 and moves 2 ^^

**Comment by GandalfLeRouge** [comment]
don't forget to add stab to move1 and move2 dammage (+ 25% if the pokemon and the move have the same type)

**Comment by Lunat1q** [comment]
Duh... ok<br/>
![](http://i.imgur.com/7ofjMLD.png)

**Comment by GandalfLeRouge** [comment]
math.floor() +1
not sure for  energyToFill>=100
cross chop 60
gunk shot 65
heat wave 80 ....
you probably have a data for the number of fill bar

**Comment by SweeTIPi** [comment]
I was about to say that the values of DPS from the program don't match with the values of most other methods of rate that Ive found. Apparently, they're stronger than that. 
Like "Aqua Tail", 23.9 instead of 19.1, for example.
*(just a note to possible correction) 

[OFF]I cant wait for you improve the data showing separate IVs("guessing" really sucks). AMAZING job, thanks for your work!

**Comment by GandalfLeRouge** [comment]
for aqua Tail, Base DPS is 19.15 but with STAB is 23.9375 ...
(+ 25% if the pokemon and the move have the same type)

**Comment by Lunat1q** [comment]
i don't have energy bar amount :/ So... may be it's over 50 then? like the max amount of poke Energy is 100, so if it's over 50, then it can't be more then 1 bar

**Comment by Lunat1q** [comment]
Also it's exactly Math.Floor, cause it's being rounded to next higher integer.

**Comment by GandalfLeRouge** [comment]
Math.floor( 45.95); //  45
Math.floor( 45.05); //  45
Math.floor(  4   ); //   4
Math.floor(-45.05); // -46
Math.floor(-45.95); // -46

Math.ceil(.95);    // 1
Math.ceil(4);      // 4
Math.ceil(7.004);  // 8
Math.ceil(-0.95);  // -0
Math.ceil(-4);     // -4
Math.ceil(-7.004); // -7

Logic ... ceil ... up, floor ... down

**Comment by Lunat1q** [comment]
ah fuck :) yeah, messed up with it :P 
![](http://i.imgur.com/8X6ApNJ.png)
done

**Comment by GandalfLeRouge** [comment]
bug buzz 75, 2 bar ... :-1:

**Comment by GandalfLeRouge** [comment]
sorry you right
if energy spending = 100 then  math.ceil()
(energy spending is # than damage :-1: )

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/Sv0CDKW.png)
so this?

**Comment by GandalfLeRouge** [comment]
Yes, for energy, but stab is gone ...

energy= 100, 1 bar
energy = 50, 2 bars
energy= 33, 3 bars
energy=25, 4 bars
energy=20, 5 bars

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/4nkTDMF.png)
Done :stuck_out_tongue:

**Comment by GandalfLeRouge** [comment]
YESSS !! this the true DPS calculation

**Comment by Lunat1q** [comment]
:) ok, thank you dude :P
