### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1407]
(INFO) Character is too busy, probably you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - IGNORE that message, and don't send git issue!

should be:

(INFO) Character is too busy, probably you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - IGNORE this message, and don't send git issue!

(that->this)

**Comment by Spk345** [comment]
English is not Lunatiq's first language. Will bring up typo.
