### ISSUE TITLE
How to ensure security of info now it's closed?

### ISSUE THREAD

**Issue by JntSlvDrt** [Lunat1q/Catchem-PoGo#1408]
I'm thinking about security now its source is closed.
How can I monitor what program do?

**Comment by Spk345** [comment]
You are welcome to ask @Lunat1q for source code. The choice to go to closed source is because of issues of people ripping off Catchem bot and selling Lunatiq's work for profit. 
Others have also just stolen code and refused to credit his work (Those offenders have since credited Lunatiq after much hassling).

**Comment by JntSlvDrt** [comment]
But my concerning is exactly that everyday releases that I'll not ask everytime they're aired.
I got the reason that led to closing the code but it implies us not knowing what the program does.
I'll not stop using it, but... Gotta monitor'em all.

**Comment by Spk345** [comment]
@Lunat1q , I'll leave this one for you.

**Comment by JntSlvDrt** [comment]
I'm not saying Lunat1q is a bad evil motherfucker who's gonna steal my personal data. But let's say his account got hijacked, then the new "owner" would be able to do so. Once the code is not open anymore I can't guarantee if there's something wrong with it.

But that's not a problem anymore. Found https://www.wireshark.org/ and it will monitor the packages on net

**Comment by golgolak** [comment]
this becomes a security risk. one of the purpose of open source is transparency, allowing the user base to choose between release or compile the codes themselves... it was too good till it lasted.

**Comment by JihWei666** [comment]
If you concern security, you should not use the bot (not only the bot.......).
Maybe you could use it on the system only for Pokemon Go botting.

**Comment by Spk345** [comment]
It is your choice to use Catchem or not. Lunatiq has perfectly valid reasons for going closed source and his helpers (including me) and donators stand beside him on this. If you are worried about security of this application, you can wait and ask Lunatiq in the morning. 

I understand Closed Source is a worrisome issue when it comes to security for some. However, I am not well versed enough to answer all of your questions.

**Comment by Lunat1q** [comment]
Feel free to monitor requests, wireshark is all yours. You say like a lot people actually look at the code, but lol, No, 99% just DL the pre compilled version and start it. So i see No difference. If you don't trust me, sniffer the request as i mentioned, there is No there way to track it.

**Comment by JntSlvDrt** [comment]
I see some people suggesting repression like "dont use if you don't feel safe".
Others felt someway pushed, I don't get it.
Other're mocking about people who don't go through the code. You see? Coding aren't related to intelligence.
The best answer for a question? Close the issue, don't let people discuss about it.

Thanks, gotta sniff a lot (:

**Comment by Lunat1q** [comment]
Enjoy your sniffing.
