### ISSUE TITLE
No pokestops found in your area (im on central park!)

### ISSUE THREAD

**Issue by LifeForKill** [Lunat1q/Catchem-PoGo#1409]
https://gyazo.com/7b332653ec1eff0b359414c6d791c8b4

i have this 3 bots running, and both of them are sending that mensage! How can i fix it?

(btw, congrats for your work!)

**Comment by Spk345** [comment]
This is an IP softban. You are running too many bots on one IP. Max recommended bots per proxy or IP is one Bot. If you wish to continue to use one IP address, use only one bot at a time. If you would like to use more than one, purchase a paid proxy or VPN.

**Comment by LifeForKill** [comment]
ah ok, didnt knew that, thanks :D

**Comment by Spk345** [comment]
If you wish to lift the IP ban, you will have to reset your IP address by cycling your router, if your address is set to Dynamic. Otherwise you will have to wait between 2hrs-48hrs for the IP ban to lift.

**Comment by LifeForKill** [comment]
yeah no problem, i will wait, i can´t change the ip address that way. thanks, keep with the great work!
