### ISSUE TITLE
1.5.0.0 transfer requirements and "Not to transfer list"

### ISSUE THREAD

**Issue by badiay** [Lunat1q/Catchem-PoGo#1410]
Hi (thanks for your work first),
It seems that transfer requirements doesn't work correctly, I have CP: 900 and Iv: 90 (Iv priority off) and it unfavourites Pokemon with higher requirements and transfer them but it keeps Pokemon with lower requirements.

Thanks for everything !

**Comment by Spk345** [comment]
Please post images of your settings.

**Comment by badiay** [comment]
![settings](https://cloud.githubusercontent.com/assets/21133883/18234780/cc4cddb2-730f-11e6-8bad-401dca059fdf.png)
![transfer_error](https://cloud.githubusercontent.com/assets/21133883/18234814/5bd99164-7310-11e6-91ba-9b6fa344bd96.png)
Settings + error

**Comment by JihWei666** [comment]
According to the setting, it could keep one pokemon and transfer another one ramdomly....

Keep Min duplicate : 1

If you want high IV one, you should check " Prioritize both IV and CP for transfer " and " Prioritze IV over CP "

**Comment by delete30** [comment]
1.I always Keep Min duplicate : 2 (safer),then tranfer manual...
2.If U check " Prioritze IV over CP " icon ,sometimes u will lose high Cp with High IV!

**Comment by tyu366** [comment]
If I only want to transfer the one with both lower IV and CP, what should the option?
i.e. those of high CP but low IV should not be transferred.  Those of high IV but low CP should also be retained.

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/IErCEGB.png) 
transfer duplicate logic.
KeepMinCp is the minimum CP from settings or the CP from the list in config, will add that config to UI as fast as i can.

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18247308/5d309ba4-73a4-11e6-8949-2533a1c408fc.PNG)
