### ISSUE TITLE
 Niantic Servers unstable, throttling API Calls  

### ISSUE THREAD

**Issue by gamelordhacker** [Lunat1q/Catchem-PoGo#1411]
Help Me !!1
![111](https://cloud.githubusercontent.com/assets/21278539/18234743/e52f5ebe-7340-11e6-88fe-09af501db5f7.png)

**Comment by Spk345** [comment]
Increase your delays. Do not use same IP address for multiple bots.

**Comment by gamelordhacker** [comment]
same thing from 
![11](https://cloud.githubusercontent.com/assets/21278539/18235594/9b6a73d6-734f-11e6-8e79-d0e4ac94bcc9.png)

to this >>
![22](https://cloud.githubusercontent.com/assets/21278539/18235599/a83b0eb8-734f-11e6-8616-d8a6fb0930a5.png)
