### ISSUE TITLE
lv up safe ?

### ISSUE THREAD

**Issue by druds** [Lunat1q/Catchem-PoGo#1415]
anyone lv 30+ runing bot ?
until what lv its safe ?

**Comment by h3viin** [comment]
![1](https://cloud.githubusercontent.com/assets/21313849/18235748/1858ce5a-731f-11e6-8f81-a07ea2f61d60.jpg)

**Comment by h3viin** [comment]
which lvl are you?

**Comment by druds** [comment]
26 think abot let bot get 30  pr stop for good on this acc

ty for help on my choose xD



BR

**Comment by h3viin** [comment]
@druds ye Im been there, thinking that Im done when gone to 30 then  31 then 32, N so on. But if you have got up to 30 i think you are safe. just set your config more safe 4 every lvl. hmm?
