### ISSUE TITLE
I found a solution to Pokemon FLEE (Soft-Ban)

### ISSUE THREAD

**Issue by domg839** [Lunat1q/Catchem-PoGo#1416]
If you teleport to far the game will soft ban your account for a 1-24 hours causing Pokemon to always flee during the duration of the ban. If you encounter this, try to teleport back to the location you previous were at. In two cases, I teleported to far and Pokemon began to flee. I googled my previous lat/long coordinates and the soft ban was lifted when I went back to my previous location.  

If this doesn't work than you'll have to wait it out.

**Comment by Lunat1q** [comment]
Solution-do not teleport
