### ISSUE TITLE
[Features Request] Simple function to randomize scheaduler !

### ISSUE THREAD

**Issue by poetawd** [Lunat1q/Catchem-PoGo#1417]
First of all, HUGE THANK YOU for listening your community and adding the scheaduler feature that we all have being waiting for !

My request now is very simple, I am afraid that Niantic start checking the bot features and find out who is using it... 

It is very, very rare and not human that someone logs in THE EXACT time everyday, and always in the round hour... like 6:00 am ! 

My opinion is to get the last 5 min of the hour and RANDOMIZE the stop and start time !

Example, my bot is set to start and 12:00pm and stop at 14:00pm everyday. It is not human for this to happen ! With this feature the bot will get a RANDOM time between 12:00 and 12:05pm to start and a random time between 13:55 and 14:00 to stop !

Simple ! But much MORE SAFE !!!

Thank you again and again !!!!! This is by far THE BEST bot available, paid or not !

**Comment by poetawd** [comment]
Is this done already ? LOL

"[00:30:23] (ATTENTION) Bot paused for 1,5h, case of Schedule settings, will be started again at Monday, 02:02"

**Comment by Spk345** [comment]
#1419  Scheduler Known Issues

- Bot will finish it's actions before shutting down, between 1-5 minutes, already.
- Bot will take a few minutes to start up as is, and will pause for exactly an hour.
