### ISSUE TITLE
[Bug] Scheduler Known Issues

### ISSUE THREAD

**Issue by Spk345** [Lunat1q/Catchem-PoGo#1419]
To use Scheduler you must check the setting "Use Schedule", if you continue to have issues let me know here or on discord.

If you moved your profile from the old version, you may need to create schedule, before actually clicking "Enable Schedule", cause even if checkbox it checked, there is no schedule to set it up for, so create one, before checking it.

Many people have asked for the Feature Requests:
- Setting a "Home Point" where bot starts and stops.
- Setting a Variance to where bot starts and stops.
- Setting different routes for different time slots.

@Lunat1q This is my compiled data.

**Comment by poetawd** [comment]
You need to make sure that the bot stops before another one starts ! Otherwise we can have 2 accounts running at the same time with the same IP... and THAT WOULD BE VERY, VERY BAD !

My opinio is to randomize the stop time, not stoping exactly 1 hour after the start time !

**Comment by Spk345** [comment]
Option for 30 minute delay for schedule.

**Comment by Lunat1q** [comment]
Ok, here we go:
1. If bot was manually stopped - schedule will not start it, it works as it should.
2. I'll take a look at the "detect if just walking" algo, may be i'll find a way to make it better
3. As i said full stop = stop of all workers/schedule/etc, it means what bot is TURNED OFF.

About the features:
1. I'll think about the "add an action" during the startup hours or schedule tile.

**Comment by Lunat1q** [comment]
Found 1 problem - If you moved your profile from the old version, you may need to create schedule, before actually clicking "Enable Schedule", cause even if checkbox it checked, there is no schedule to set it up for, so create one, before checking it.

**Comment by JihWei666** [comment]
I think the schedule should not be ramdom.
We can set the time manually and easily.
The only thing we should care is "Does it work on time  precisely?"

Today I will set it stop two hours before the time I get off work.
Testing .....

**Comment by Lunat1q** [comment]
Turn off time is pretty sctrict, like: when it's the hour to stop, schedule worker start to look at the bot state, and wait when bot will finish all tasks, like catching/evolving, then it turn it off.

**Comment by JihWei666** [comment]
I have used another bot, not free, in another online game five years ago.

People can set the schedule at hh:mm.

**Comment by Lunat1q** [comment]
So use it. I don't like that way.

**Comment by JihWei666** [comment]
Never mind.

I just need it stop precisely before I get off work.
Botting 50~100 km away, it stop precisely then I could play immediately.

**Comment by JihWei666** [comment]
After 6 hours, It stop precisely. 
Good job.
Thank you.

**Comment by Cowering** [comment]
how do I do this: I want a running bot to stop at 3am. it is currently 9:30PM. Do I have to stop bot. make a schedule from 10pm-3am, and then just leave it so it will start itself at 10PM (+/- randomness)

**Comment by tyu366** [comment]
The randomness actually means random variance or discrepancy.  Only the bot can wake-up at specific time exactly.  Human will not. e..g early within 15 minutes and later within 30 minutes.
