### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#142]
При первом же запуске новой версии, сразу после нажатия на "all start"
http://screenshot.ru/e1958be5ad157b53cd1bd5735aa6e0f2

**Comment by JacksonTrue** [comment]
Есть какой нибудь режим логирования или отладки? Сделайте возможность запускать Debug режим. Я отправлю вам все данные для выявления неполадки, ибо это дело, у моих товарищей та же проблема. Программа живет от 5 минут до часа в лучшем случае. Благодарю да вашу работу.

**Comment by Lunat1q** [comment]
1. Не пиши по русски.
2. У тебя в журнале винды есть инфа по ошибке.

**Comment by zekinh** [comment]
i just cant read if you write in russian man, i speak spanish and i don't comment in my native lenguage, speak in english if reporting a issue
