### ISSUE TITLE
IV calculated is different from other sites. May cause wrong decision on transfer.

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1421]
I try to check the IVs of my pokemon inventory in https://pokeiv.net and found that the IV does not agree the those shown in the information tab.  I have abstracted some samples with details for your checking.
List of pokemon
http://ihkex.com/test/poke/poke_iv1.jpg
http://ihkex.com/test/poke/poke_iv2.jpg

The details
http://ihkex.com/test/poke/poke_dtl1.jpg
http://ihkex.com/test/poke/poke_dtl2.jpg

It seems that I have problem to upload the pictures for your reference to this post.  It says 'Something went really wrong and we can't process  that file' but do not tell what's wrong.

So I attach the url of the pictures for your reference.

**Comment by arocarlisle** [comment]
I think that is what the website is incorrect
I checked a few sites, their values are not the same
