### ISSUE TITLE
not this shocking incubator

### ISSUE THREAD

**Issue by Grande36** [Lunat1q/Catchem-PoGo#1422]
every update I copy the profile folder to the new folder, but do not know if this is a bug or, my eggs are not shocked, can explain?

**Comment by Spk345** [comment]
What do you mean by shocked?

**Comment by Grande36** [comment]
I'm level 28 and level 25 from the eggs in the incubator are not shocking

**Comment by Grande36** [comment]
despite showing it has egg in the incubator. they do not ta shocking

**Comment by Bravething** [comment]
shock or hatching??

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/e2UhyPQ.png)
