### ISSUE TITLE
[Feature Request] Button "All" in Poke Lists Settings

### ISSUE THREAD

**Issue by JBWKZ2099** [Lunat1q/Catchem-PoGo#1423]
Hi, i would like you to add the button "All" to add all pokemons on each list.
The next screenshot was edited for me to show you how can the button be positioned (rounded in a red circle).
![feature requestx2](https://cloud.githubusercontent.com/assets/21129809/18238275/ffcb35e4-7300-11e6-85ae-f87ad1e0733f.png)

**Comment by Lunat1q** [comment]
Sorry, i see no use in that button, cause those lists should be well configured lists, and "All" is just a wayaround of other functions. I'll do "clear" button, thants for sure, but not the "all" one
