### ISSUE TITLE
Router Creator (bug and feature request)

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1424]
**Feature Request**
There is no way to modify a route even moving the way point a little bit left or right.
There is no way to insert a way point in between.

**Bug reported**
when there is some error encountered say for example that there is no internet connection (wifi broken), all the custom routes created after the exe started are not saved on exit.

**Comment by Lunat1q** [comment]
I'll fix exe crash if no internet connection. If exe crashes - settings are being reseted.
About feature, yes, and that will be it, for now atlease.
