### ISSUE TITLE
Bad level ?

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1429]
Level you use is calculate or it's data ?
Because  I think that you can't catch half level. 
you need to level up to have half level.

so if there is a problem with level, all IVs are wrong ...

**Comment by Lunat1q** [comment]
jesus... it's pokemon level, all IV are fine

**Comment by GandalfLeRouge** [comment]
there is a problem in lvl of pokemon
max pokemon lvl is 1.5 of the trainer lvl 

for example I have a flareon lvl 31.0 max lvl (trainer is lvl 29) it should be 31.5
I have a dragonite lvl 22.5 (never lvl up) iv 94.4% hp 122 cp 2184
if it's a lvl 22.5 with 2184 cp and 122 hp,  iv is 73%
if it's lvl 22 with 2184 cp and 122 hp, iv is 94%

so iv or lvl is wrong ! I hope it's lvl ...

**Comment by juliopokemon** [comment]
a

**Comment by juliopokemon** [comment]
I compared all ivs my Pokemon with pgnexus site , and has a small difference in almost all Pokemon( I do not know which one is correct)
