### ISSUE TITLE
IP ban question.

### ISSUE THREAD

**Issue by ommeirelles** [Lunat1q/Catchem-PoGo#1430]
I have noticed that when i use two accounts without proxy Niantic ban my IP.
So my question, If my friend and i are playing from home connected in the same Wi-Fi Niantic will see that as irregular player behaviour and ban my Home IP or not?

**Comment by alanearl** [comment]
Yes they will ban your IP...
Use 1 Public IP per User Account.
Restart your modem if you have experience IP BAN.
