### ISSUE TITLE
In PRC, some forks use ur project to name it into a different program for sell.

### ISSUE THREAD

**Issue by ccpiloveyou** [Lunat1q/Catchem-PoGo#1432]
Please be advised, the fxcking PRC guy sells ur project for money. 

Some suggestions:
1.When multi mobs pop up, could the program aims on the mob with specific name/CP/IV?  I found out the program will choose the mob in a group randomly.  In the mean time, the specific mob that u wanna get might run away in a flick.
2.I'm not actually understand why the user could not save delay values even "Save settings"?  It turns out whatever u change anything, the delay value will change back to default during next startup.
3.Be advised, it's not "Softban".  When I took certain period of time in order to change my location to a remote distance, I could not sure why the program keep telling me "There's no Pokestop in the field...etc" when I change my lat/long then starting up my program?  Meanwhile, by changing my lat/long to original location, I could hereby flip Pokestop and get mobs without any abnormality.  It's why I doubt that's not a Softban but a program glitch.  But don't why, the long distance shifting somehow works without any heads up or warning.

Thanks for ur work.

**Comment by Lunat1q** [comment]
What is RPC?
Since 1.5.0 it's not possible to "redesign" it

**Comment by Cryptologism** [comment]
What is prc? Askin sir lunatic about this..

**Comment by ccpiloveyou** [comment]
People's Republic of China

**Comment by Lunat1q** [comment]
ah... whatever, we saw it already, source closed.
