### ISSUE TITLE
[BUG] Manual & Automatic activities do the same.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1434]
Dear Dev,

Im using multiple transfer using ctrl. But still the bot automatic activities will resume.

![capture](https://cloud.githubusercontent.com/assets/648116/18251803/eed0c4f8-73bd-11e6-9fb9-8a1d974dd1f8.PNG)

![capture](https://cloud.githubusercontent.com/assets/648116/18251883/6bab494e-73be-11e6-81c5-5a28c9710b7c.PNG)

v1.5.0.0

Keep up the good work :)

**Comment by Lunat1q** [comment]
added extra check, fixed
