### ISSUE TITLE
Accidentally happened

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1437]
I have two bots, for two accounts.
I think I start one of them.

after 30minutes, I realized that both bots are running, with the same IP, without proxy.
somehow, Niantic didn't ban my IP.

just surprised, and curious.
because previously, I've ever tried to run several bots together, and my IP got banned.

**Comment by ccpiloveyou** [comment]
You could not have 3 accounts from the same IP simultaneously.  2 is OK.  Otherwise, U'll got banned.

**Comment by saldotman** [comment]
well noted. thx
