### ISSUE TITLE
Don't get any object from pokestop

### ISSUE THREAD

**Issue by XtebanJog** [Lunat1q/Catchem-PoGo#1438]
Hi friend, i have a little problem, catchem don't get eny object from pokestop. My Inventory don't have eny pokeball and the bot not get any thing from pokestop

**Comment by ccpiloveyou** [comment]
Did you "Loot Pokestop"?

**Comment by XtebanJog** [comment]
No, pokestop is 0

**Comment by ccpiloveyou** [comment]
You shall active "Loot pokestop" in the settings first.

**Comment by XtebanJog** [comment]
Oh, good, you modify the config. ok yes now it's work fine. Thank you friend
