### ISSUE TITLE
How do I set up to catch more Pokemon?

### ISSUE THREAD

**Issue by TankardBR** [Lunat1q/Catchem-PoGo#144]
How do I set up to catch more Pokemon? 
I can only get 1 pokemon every 10 min, can someone help me plz.

Thx So Much!

**Comment by xTeddiusx** [comment]
create a secondary account for testing. try to find areas with lot of pokestops and crowed. 
use secondary accound to see how many pkms u can catch. if u are ok with that ..try your main else search again

**Comment by TankardBR** [comment]
@xTeddiusx i test others spot but its same only 2k xp per hour and 1 pokemon every 8-10min

**Comment by Bay101** [comment]
Please visit our Wiki for more information: https://github.com/Lunat1q/Catchem-PoGo/wiki
Or Join our discord server and ask in the help channel: https://discord.gg/pPwxX8Q
