### ISSUE TITLE
Telegram reports

### ISSUE THREAD

**Issue by diorox** [Lunat1q/Catchem-PoGo#1441]
Hi.
I setup the telegram to report some uncommon pokemons.
The Catchem evolves a Magikarp to Gyarados, but the message appears Gyarados with Magikarp's moves.

![screenshot_2016-09-05-12-37-27](https://cloud.githubusercontent.com/assets/15343342/18254871/dc8434dc-7378-11e6-9f5a-a445c495e810.png)

**Comment by Lunat1q** [comment]
Fixed, thanks! will be in next release.
