### ISSUE TITLE
maximum level is not equal to the trainer level + 1.5

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1443]
for example I have a flareon lvl 31.0 max lvl (trainer is lvl 29) it should be 30.5 but it's a 31.0 lvl

I have a dragonite lvl 22.5 (never lvl up) iv 94.4% hp 122 cp 2184
if it's a lvl 22.5 with 2184 cp and 122 hp, iv is 73%
if it's lvl 22 with 2184 cp and 122 hp, iv is 94%

so iv or lvl is wrong ! I hope it's juste UI lvl ...

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/Wx6CAbc.png)  how level is being calculated

**Comment by GandalfLeRouge** [comment]
algorithm seems to be good, probably a probably a rounding problem
however, if you test equality between float it's better to test the difference and test with epsilon

while math.abs (cpm-CpMultiplier[i])>1E-4

**Comment by Lunat1q** [comment]
i'll take a look at this.

**Comment by GandalfLeRouge** [comment]
Now I'm sure that the problem is here, that explain why some poke have an half lvl above (but not all)
in the test, if you are just below (for example 1E-12) you need another step, but it's too much.

**Comment by GandalfLeRouge** [comment]
unfortunately, CP is wromg,
it's seems you use ATK, DEF and HP to calculate CP, 
ATK and DEF are calculate with CPM
CPM is wromg because the lvl is wrong

**Comment by GandalfLeRouge** [comment]
if you use #1470 
it's clear that the lvl is 16 (not 16.5)

![image](https://cloud.githubusercontent.com/assets/21307163/18276168/26b3b36c-744a-11e6-932f-943a78f258a1.png)

now I don't understant how with CPM, lvl, CP and HP you can calculate IV ATK and IV DEF ?
Is it an average of the different possibility ?
in that case it should be better to give also min and max ? 

The best solution is to store the different solution and specify when evolve or lvl up

like that IV doesn't change when poke evolve our lvl up (it's not like that now)

**Comment by Lunat1q** [comment]
So... all levels are 0.5 higher then they should be?
