### ISSUE TITLE
Minor bug: Add Action Schedule

### ISSUE THREAD

**Issue by badiay** [Lunat1q/Catchem-PoGo#1448]
If you go in "Schedule" -> right click -> click on "Add action" (empty choice) the bot will stop to response and close by itself

**Comment by Spk345** [comment]
Give me a bit more information to recreate this bug please.
Does it stop the bot completely, or crash the application totally?

**Comment by Spk345** [comment]
Try updating to newest .net framework.

**Comment by badiay** [comment]
The "Add action" button works perfectly when you choose one, but if you
just directly click on "Add Action" without selecting one of them it
crashes (the app doesn't respond then close by itself)
