### ISSUE TITLE
[Test-Required] Favorite Pokemon Not Being Renamed Properly

### ISSUE THREAD

**Issue by LeadkShip** [Lunat1q/Catchem-PoGo#1450]
I want to rename all pokemons above 85 iv, but he dont rename the favorite ones. how can i resolve this

**Comment by juliopokemon** [comment]
same problem

**Comment by Lunat1q** [comment]
You can't, rename fav pokemons by the hand,
It's builded in logic to skip favorited pokemons in automatic actions.
