### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by SweeTIPi** [Lunat1q/Catchem-PoGo#1451]
The latest release is crashing when it opens. 
Like appears after execute the file and then window freezes.
I saw the in closed issue #1358 and  around here is everything correct(with my pc/inthernet).
I tried with the configs I pasted and also with the original files from the zip.
Nothing works. What can I do?

Edit: except "Increase System Page File Size", I didnt understand.

**Comment by SweeTIPi** [comment]
![sscrash](https://cloud.githubusercontent.com/assets/21270279/18258987/923d4638-73b5-11e6-9f0b-5775a8637552.jpg)

**Comment by Cryptologism** [comment]
Before this version all wwas ok?
Then you might wanna have a pure fresh new download... Then,try to running it again as administrator..  And err do check all necessary item like netframework 4.0-4 6,some d3d system,and do check the anti-virus quarantine section too

**Comment by Spk345** [comment]
#1458
