### ISSUE TITLE
Sort not working

### ISSUE THREAD

**Issue by Vaye1986** [Lunat1q/Catchem-PoGo#1452]
The sort is just simply not working.

**Comment by Vaye1986** [comment]
apparently some of the sort work, but it's lagging so much. sorting like time isn't working at all

**Comment by pokter75** [comment]
Yes, it is NOT working properly.

**Comment by Spk345** [comment]
How can I recreate your issue? How many pokemon do you have in your inventory? 

You can select multiple sorting orders at the same time. Make sure that you do not have multiple selected. I have no issues with having 2 selected.

**Comment by Cryptologism** [comment]
512mb of ram? xD
Just kiddin.. 😊 
Wonder of anyof us can teamview with the pwrson who having error... Huhuhu

**Comment by Spk345** [comment]
Lol. I wish. Would make all these issue less infuriating.

**Comment by Lunat1q** [comment]
It's Sort => subsort. There is no issues, it works as it should
