### ISSUE TITLE
Amount of Pokeballs to Keep Logic..

### ISSUE THREAD

**Issue by TTiodastia** [Lunat1q/Catchem-PoGo#1453]
the bot should have other options, like "Amount of Great Balls to keep" or "Amount of Ultra Balls to keep", because i choose to keep with 200 poke balls, and when i'm back, my account has 197 poke balls, 2 Great Balls and 1 Ultra Ball..

**Comment by petoe93** [comment]
i have "keep 250 balls" and the bot is constantly keeping up ultra balls around 230 :)
check out the config files in the profiles folder, i think i remember seeing something like keep a certain amount of poke/great/ultra balls in the config file, but i'm not sure about it

**Comment by pokter75** [comment]
And some how in prev. version the bot was recycle 104 of my acct's ball, it may raise to cause the ban. (no one is recycled the balls except ... bot).  Pls take a look for safety caution. Thx

[15:56:19] [Inventory] Inventory Usage: 344/350
[15:56:19] 104x ItemPokeBall
[15:56:35] 20x ItemPotion
[15:56:41] 1x ItemSuperPotion

**Comment by FarisseB** [comment]
+1 TTiodastia.

petoe93 : there is no option in config file for keeping amount of ultraball or greatball. 

pokter75 : actually you can recycle 200 of pokeballs ther is no problem with ot. Niantic has an new option for recycling many items at the same time.... ;-)
