### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1456]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Catchem.exe
  Problem Signature 02:	1.5.0.0
  Problem Signature 03:	57cc7f86
  Problem Signature 04:	Newtonsoft.Json
  Problem Signature 05:	9.0.0.0
  Problem Signature 06:	575e9365
  Problem Signature 07:	1cd
  Problem Signature 08:	178
  Problem Signature 09:	Newtonsoft.Json.JsonReader
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Can't help more without symbols :( (v1.5.0.0)

**Comment by Spk345** [comment]
So, what were you doing to cause this error?

**Comment by Spk345** [comment]
Try fixes in #1458
