### ISSUE TITLE
Transfer High CP pokemon

### ISSUE THREAD

**Issue by OracleMaster14** [Lunat1q/Catchem-PoGo#1457]
got Snorlax! CP:2031, Iv:63.7, Level:24.5, Move 1: ZenHeadbuttFast, Move 2: BodySlam

but it transfer it.

my recently high cp is 1700cp. :-1:

**Comment by Spk345** [comment]
Post screenshot of your settings.

**Comment by juliopokemon** [comment]
same problem here.
I select ' keep  min cp 1000 ' and ' priorize iv over cp '
however transfer my Pokemon with over 1000 cp if he have the lowest iv

**Comment by Lunat1q** [comment]
You select <b>priorize iv over cp </b> and wondering why it transfer Low IV pokemon? srsly?
