### ISSUE TITLE
[Bug] Release 1.5.1.0 Known Issues

### ISSUE THREAD

**Issue by Spk345** [Lunat1q/Catchem-PoGo#1458]
Release 1.5.1.0 has many known issues currently, if I did not list yours, chances are I haven't seen it yet. Comment here, or in discord and we will try to fix your issue.

**Catchem 1.5.1.0 Release crashes upon startup (Without Profiles):**
- Download the Release 1.5.1.0 and try again.
- Download newest .Net Framework 4.6.2 and install it.

**Catchem 1.5.1.0 Release crashes upon startup (with Profiles transferred over):**
- Turn off "Auto-start," Always turn off Auto-start when transferring to a new Release.
- Turn off "Use Custom Routes." Custom Routes becomes a Null value when transferred to new Release.
- Turn off "Use Scheduler." We had many updates to Scheduler feature. You can turn it back on when you open new Release.

**Catchem 1.5.1.0 Release does not show pokestops (when not IP Banned and transferring over Profiles):**
- Turn off "Use Custom Routes," in config.json (in ur profile folder), or in older Release.
- You can re-enable "Use Custom Routes" after you log back in on new Release.
- Download newest .Net Framework 4.6.2 and install it.

**Other issues:**
- If bot crashes anytime after you've made a New Route EVEN if you save it in Route Creator, you may lose your New Route. 
- If you had this New Route selected and Catchem crashes, your bot will tell you "No Proper Route loaded, or Route Too Short." In settings, your Custom Route will be Null. And Bot will Full Stop.

If you continue to have issues after trying all of these fixes, let me know. Thank you.
@Lunat1q 

**Link software to check Net.Framework** --> (http://www.asoft-ware.com/download.php?id=11)

**Link download the lattest offline installer of Net.Framework (4.6.2)** --> (https://www.microsoft.com/en-us/download/details.aspx?id=53344)

**Comment by angelaayer** [comment]
I have tried this two and still having the same problem
-Turn off "Use Custom Routes." Custom Routes becomes a Null value when transferred to new Release
-Turn off "Use Custom Routes," in config.json (in ur profile folder), or in older Release.


about the second option I am not sure how to do it. Can you help me?

**Comment by Spk345** [comment]
What exactly is happening? Is it crashing, or is pokestops not showing?
Update your .Net Framework to newest version.

**Comment by angelaayer** [comment]
I have the latest framework. Pokestops not showing.

**Comment by Spk345** [comment]
And you are not IP Banned?

**Comment by angelaayer** [comment]
no banned. the old version works perfect!

**Comment by Bravething** [comment]
join our discord & we will try to solve ur problem...

**Comment by Bravething** [comment]
using lattest net framework 4.6.2 (offline installer - i recommended for low & unstable connection)

**Comment by Lunat1q** [comment]
Should be fixed now
