### ISSUE TITLE
The Program doesn't work on Virtual Machine

### ISSUE THREAD

**Issue by geovanipfranca** [Lunat1q/Catchem-PoGo#1459]
I use my windows on parallels because i'm a mac user, but the program show this message!

![Screenshot]
(http://i.imgur.com/goB9jN6.png)

#  Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	Catchem.exe
>   Application Version:	1.5.1.0
>   Application Timestamp:	57cddabd
>   Fault Module Name:	KERNELBASE.dll
>   Fault Module Version:	6.1.7601.17932
>   Fault Module Timestamp:	503275ba
>   Exception Code:	e0434352
>   Exception Offset:	0000d3cf
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1046
>   Additional Information 1:	0a9e
>   Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3:	0a9e
>   Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\Windows\system32\en-US\erofflps.txt
>

**Comment by Spk345** [comment]
Have you updated to newest .Net Framework for VM?

**Comment by Spk345** [comment]
#1458

**Comment by geovanipfranca** [comment]
yes!
