### ISSUE TITLE
Eevee Transfer bug

### ISSUE THREAD

**Issue by NotMyProblem** [Lunat1q/Catchem-PoGo#146]
I´m not sure why this happens but the Bot is Transferring all Eevee and its evolutions  except one!
This is no bug until it ignores the MaxCP transfer value (the bot transferred a Vaporen CP 1670 because i have a stronger one of CP1700) and it ignores the keep minimum Pokemon of a kind which is set to 3 at my Bot.

But only on Eevee and its evolutions.

So my settings are:
No transfer: 
- if >1400CP                    
-  if >85IV
- and keep 3 of a kind 

which works perfect but on Eevee, Vaporen, Jolteon and Flareon

**Comment by Bay101** [comment]
You need to Go into the profile directory then click on the name of that bot instance's folder, then config folder. In there you will find a config.json file, open it with a text editor such as notepad and near the bottom you will find the transfer settings for individual pokemon. If you change it there it will prevent this issue

**Comment by NotMyProblem** [comment]
Thanks its a kind of workaround but why does the settings work on all other Pokemon except Eevee. So Why does it keep for example 3 squirtle but doesn't keep 3 Eevee.
Why i´m asking is in this config file are all Pokemon set to keep 1 of a kind and pretty high CP values  and if you set those Values right in the setting of the Bot it uses the settings you set not those in the config file. Except Eevee...

PS thanks for the fast response!
And of course nice work.
