### ISSUE TITLE
[Question] [Suggestion] Import, Export and Transfer Routes...

### ISSUE THREAD

**Issue by LPachecoBR** [Lunat1q/Catchem-PoGo#1462]
Question:
There is a practical way to transfer my routes from one version to another version?

Suggestion:
1. Create a folder for routes such as the profile folder.
2. Create the import and export routes for files (.kml or .kmz) of Google Earth.

Thank You

**Comment by Bay101** [comment]
just copy over the catchem.json file in the main bot folder
