### ISSUE TITLE
a happy user with some questions.

### ISSUE THREAD

**Issue by Alfred4444** [Lunat1q/Catchem-PoGo#1465]
greetings to all.
First of all, a big applause for the team, because thanks to them we have this great advantage. Thank you!
Second: How I can turn incense on the bot?
Third:      I always get this message, (I use mobBot in the routing service): 
[11:59:21] (ATTENTION) MobBotRouting API Key is Empty!
Fourth: It would be possible to integrate struggles gyms? poderte or download a file with the map where are you've seen gyms to go further? , So you create a map with all the gyms in your area. It could go autoguardando As you're finding, regardless if you see an account or other. eg I have multiple accounts on the bot and travel for Spain and the bot is storing all points of gym after meeting to create a map with all the gyms, I think it would be a very great idea!
thanks for reading me! and I feel my English translator !!

**Comment by Lunat1q** [comment]
2. You can't, for now.
3. You need to supply MobBot routing API, it's paid, so i recomment you to use free API like Valhalla
4. Bot see all gyms, but for now, there is no logic to fight em, so, i just don't put them on the map.

**Comment by alanearl** [comment]
Just an advice to avoid ban... don't put high level CP Pokes on the Gym.
Just put less than 1000 CP pokes for Gym defense if you don't want to experience user
account ban :) Enjoy!

**Comment by Alfred4444** [comment]
Thanks for answering.
True , it has logical response to the gym.
But you can download a map with the location of the gyms in your area and then can go on foot and prepare a route or using the NOX , it is not such a bad idea .
A shame not to use incense. Could you add this? , would be great. Thank you.
And thank you also for your advice Alanearl .

**Comment by Lunat1q** [comment]
<b>Shame</b>? 
What's wrong with you?

**Comment by Alfred4444** [comment]
I think the Google translator , not helping me .

**Comment by Alfred4444** [comment]
I'm just saying , that would be nice , to create a downloadable map with places where there are gyms .

**Comment by Alfred4444** [comment]
gyms as shown in the map of the bot, to obtain that information on a map.
For later, for example to make a walking route gyms .
I'm not sure if I explained well .
