### ISSUE TITLE
Error Message; Help please

### ISSUE THREAD

**Issue by ENGChosen** [Lunat1q/Catchem-PoGo#1466]
[21:36:08] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

What's this error?

**Comment by Lunat1q** [comment]
pretty weird error. Can you try to DL 1.5.1.1 pre-release?

**Comment by lapigithub** [comment]
I encounter this error when the accessible pokestops in your vicinity (limited by the maximum distance you have set) have recently been spun and have not yet been refreshed. 

Try using a custom route to space out the timing such that you walk past the same pokestop after at least 5 minutes (give it sufficient time to refresh).
