### ISSUE TITLE
Don't find pokestop

### ISSUE THREAD

**Issue by CaiqueBrito** [Lunat1q/Catchem-PoGo#1467]
Hey guys,

I am in the heart of São Paulo - Brazil , and here has about 200 pokestops , but when I opened today , there is nothing showing in Bot, this is a problem with Bot ?

![screenshot_20160906-080323](https://cloud.githubusercontent.com/assets/8015744/18271559/19957f8a-7409-11e6-8acc-f795501fe603.png)
![where_is_pokestop](https://cloud.githubusercontent.com/assets/8015744/18271561/1d892542-7409-11e6-8559-45a504eda7ba.png)

**Comment by braindeadxxl** [comment]
I have the Same Problem.
but iam in Germany, Hamburg.
On my Smartphone i see everything stop,arena.
With Catchem i see nothing :(

**Comment by Lunat1q** [comment]
Try to update .net to 4.6.2 or try to get pre-release version from the releases
