### ISSUE TITLE
wrong ATK and DEF

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1470]
you write base ATK, Base DEF and Base STA
HP is ok (so you don't need base STA)

real ATK = (Base  ATK + IV ATK) * CPM
real DEF= (Base  DEF+ IV DEF) * CPM

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/RI9t9bY.png) now?:)

**Comment by m-dl** [comment]
+1 for a given pokemon, all duplicate have same atk, def, sta

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/7EbH6P3.png)

**Comment by Lunat1q** [comment]
Should be fine now, wait for next release.
