### ISSUE TITLE
location shift?

### ISSUE THREAD

**Issue by axeljr** [Lunat1q/Catchem-PoGo#1473]
first of all~ thank you, Lunat1q!
I found the location shift very far in 1 or 2 hours!
please check blow picture: the initial location I set at "1", but after 1 or 2 hours I fly to "2"
as you see~ "Max Travel Distance in Meters"= 800.
is it a bug? or a program of Niantic for anti-bot? or just happen to my computer(wrong settings)?
I found this issue from 1.4.x.x to the current version 1.5.1.1.(maybe it already happened in previous version)
![map_poke2](https://cloud.githubusercontent.com/assets/22003217/18274400/d5cc19b4-7474-11e6-9d5b-645b313f01eb.jpg)

by the way, i have few suggestions:
- could you keep the latest status in "Map&Console" and "Information" after click "STOP" or "STOP ALL"?
that's more easy to check POKE and Stop time in LOG of "Map & Console" when offline.
- could you show something different after click "SAVE Settings" in Settings?
because I am not sure my new setting already be activated or not after click that...

my English is not so good, I hope you can understand what I mean...

**Comment by Halitz** [comment]
use a routine, valhalla or google. and solved. It is more complete.

**Comment by Halitz** [comment]
just log in, valhalla or google Directions. Get key (API KEY).
 
Use mapzen elevation API : TRUE (select google o valhalla)
Use custom route : TRUE (Make your routes, in ROUTECREATOR) 
Altitude min : 1 
Altitude Max : 50

Max spawn location offset : (no need change = 10)
Max trabel distance on meters : (same default =5000)

**Comment by Lunat1q** [comment]
Discovery Pathing.
Read wiki please.

**Comment by axeljr** [comment]
thanks for all of you!!!
