### ISSUE TITLE
(ERROR) Access token expired. 

### ISSUE THREAD

**Issue by lapigithub** [Lunat1q/Catchem-PoGo#1477]
The above error message appeared in the version 1.5.1.0.

Yes, I have used the filter function to search for the key words "access", "token" and "expired". Exact issues have been posted in #850 and #1428. Both threads have been closed with no further replies or referrals to answered closed threads. 

Does it mean that this error is unimportant?

**Comment by Lunat1q** [comment]
most of the time that means what u have problems with connection. yes, it's unimportant problem.
