### ISSUE TITLE
pokemon types

### ISSUE THREAD

**Issue by dreamwalker1232** [Lunat1q/Catchem-PoGo#1478]
![capture png1](https://cloud.githubusercontent.com/assets/20989863/18278268/11383fa6-746f-11e6-8e7d-c6cbc5c9fe7e.PNG)
us you can see the jolteon shows both none and none for its type 
thats wasnt the only one , it did that for kabuto , doduo . but once i restarted the entire bot it was fixed

**Comment by Lunat1q** [comment]
Should be fixed in new release.
