### ISSUE TITLE
Tip: Bot stop inclusion, automated restart in cycles!

### ISSUE THREAD

**Issue by b3tt0z** [Lunat1q/Catchem-PoGo#148]
Stop determined in minutes pause time in minutes and restart determined in minutes in cycles, alternating with delay.

**Comment by Bay101** [comment]
So you want to have the bot stop after a set amount of time and also start again at another set time, with a bit of randomness in these values?

**Comment by b3tt0z** [comment]
Yes!
Because I have noticed that every 30 minutes, an API call is made by the server. Interestingly, when there is the first mistake, so it is repeated with time reduction. And if you force a stop, then restarts, does not appear any error.

**Comment by sineao** [comment]
Do you mean the message : "Niantic Servers unstable, throttling API Calls."? Strange is, that this message apears exactly every 30 mins... so i think this cannot be a random event. Isn't it possible, that this is a session-key or something smiliar that will be renewd all 30 min in the legal app? Maybe this will also help niantic to detect bots and flag the accounts for future banning...

Is it maybe possible to add an option, to do a re-login every 25 min or something like this?

**Comment by b3tt0z** [comment]
Yes!
Include field, where each User may have the option to choose: how long the bot will run beyond the period that it should be stopped until reset by the inclusion of a delay variable random seconds for each restart (human style).
