### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1480]
got the same error I just closed. It also occured about 5 minutes after the top of the hour, and I got a 0 byte log file. Could you make the bot flush the log after every printout. It is a tiny bit slower, but on a modern computer you don't notice and you get a better log when something crashes.

**Comment by Lunat1q** [comment]
Log is being flushed upon app being closed

**Comment by Cowering** [comment]
do you have an exception handler to flush on an abnormal ending? In C++ it would be a try{} in main() to cover the whole program. I don't know about C#

**Comment by Lunat1q** [comment]
yes, it should flush it even on crash.
