### ISSUE TITLE
IV stats are integer (0 to 15), so IV % should be fraction of 45

### ISSUE THREAD

**Issue by GandalfLeRouge** [Lunat1q/Catchem-PoGo#1484]
![image](https://cloud.githubusercontent.com/assets/21307163/18282398/47de0f08-7461-11e6-8d0a-c63cd05b419e.png)

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/RsIlb5v.png) current IV algo

**Comment by GandalfLeRouge** [comment]
for the first part :
individual attack, Def and stamina should be integer <=0 and <=15, 

for the second part can you send me Caculatemaxcpmultiplier, Caculatemincpmultiplier and CalculateCpMultplier please

**Comment by Lunat1q** [comment]
Can you contact me in Discord? instead of creating issues over and over?:) i think that will work much faster :)
