### ISSUE TITLE
Batch Create with Proxies (No authentication)

### ISSUE THREAD

**Issue by lycenthedead** [Lunat1q/Catchem-PoGo#1486]
Is it possible to batch create bots with proxies that don't have authentication? No user/password? Even when manually creating bots, I don't see the option to use just the proxy url and port...

**Comment by Lunat1q** [comment]
yes it's possible.
leave it blank.

**Comment by lycenthedead** [comment]
How do I add a proxy with no authentication manually? Putting the IP as the username, including the port, and leaving the password blank doesn't work...

**Comment by lycenthedead** [comment]
Misunderstood, sorry. Just noticed host next to port, haha. Got it, thanks =P
