### ISSUE TITLE
Problem with map coordinates on latest versions.

### ISSUE THREAD

**Issue by AndresAriel** [Lunat1q/Catchem-PoGo#1487]
[Catchem-2016-09-06-14.txt](https://github.com/Lunat1q/Catchem-PoGo/files/457404/Catchem-2016-09-06-14.txt)

First of all, thank you for the work you put into this project, its an awesome job.

But i've a problem with the last verstions of catchem, i select a location in the map and click start and when logged in the coords the location coords get crazy.

Sorry for my bad english. 

PD. I have attached the generated log file.
PD2. I have the .net 4.6.2
PD3. I can use catchem 1.2.5.0 with no problems.

**Comment by Lunat1q** [comment]
Added delay, thanks :)
Try to set coordinates manually, if it fails, try different decimal separator, should solve the problem.
