### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SrRyD** [Lunat1q/Catchem-PoGo#1488]
[14:32:16] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exceção do tipo 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' foi acionada.
   em PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() na C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:linha 79
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() na C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:linha 0
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() na C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:linha 53
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() na C:\dev\Catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:linha 259

**Comment by Lunat1q** [comment]
Unstable connection. Can't do anything with it.
