### ISSUE TITLE
error on feature "Order By"

### ISSUE THREAD

**Issue by angelaayer** [Lunat1q/Catchem-PoGo#1495]
Doesnt work any of the options on feature "order by", cant switch them

**Comment by Lunat1q** [comment]
Screens? extra info?

**Comment by angelaayer** [comment]
actually found theres some lag when trying to orde takes few seconds before ordering. anyway. thanks

**Comment by eloxxx** [comment]
Doesn't work for me too.
When I want to order By CP, Or IV, it doesn't work.

**Comment by LittleShen** [comment]
Ya...the feature "Order By" is not working.
Version: v1.5.2.0

**Comment by MarkoHess** [comment]
For me it is working, but different to older releases.
It works with multiple orders.
Now it orders in the order you press the buttons.
e.g. I order my poke first by its number, then dps and as the last one iv.
So i get the most powerfull of each poke depending on its moves and then their iv value.

**Comment by Lunat1q** [comment]
See no problems with it, closed.

**Comment by LittleShen** [comment]
Thanks @MarkoHess 
It means only first selection is applied to result.

<EX> Multiple selections order: IV -> CP -> A-Z:
1. The "IV" is apply to result.
2. If you deselect IV, then the "CP" is applied.
