### ISSUE TITLE
male/m/female/f ?

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1496]
![capture6](https://cloud.githubusercontent.com/assets/9252175/18289561/1bbe9196-743d-11e6-8851-8ba20595279c.PNG)

Why does the bot name these like this? It happens with both male and females

**Comment by Lunat1q** [comment]
Translation shit. Looks like one of the pokes you have - was renamed and other - translated. Not an issue.

**Comment by Cowering** [comment]
I never rename these
