### ISSUE TITLE
Transfert Pokemon Problem ( setting picture)

### ISSUE THREAD

**Issue by eloxxx** [Lunat1q/Catchem-PoGo#1497]
Hi guys, need some help on Tranfering Pokemon.

I used the following setting but I got a Magikarp (IV 93), Dratini (IV 89), and a Golduck ( CP 1420) which were transfered.

The following setting shouldn't be keeping any Pokemons with more than 1100 CP and 80 IV ?
![loooool](https://cloud.githubusercontent.com/assets/21296701/18291451/072fa170-7488-11e6-8a32-4f47435d2bf2.jpg)

(Even if I put 1 duplicate, it means " one of each pokemon below 1100 CP and 80 IV, isnt it ? )

**Comment by medoamanquer** [comment]
I think because you have the option "Keep Poke that can Evolve" as checked
It is preventing the pokemon transfer if it can evolve ignoring the above options

**Comment by Lunat1q** [comment]
Rechecked transfer settings again, see no problems in it.
Check your transfer filter, may be there is a problem
