### ISSUE TITLE
possible ban recognition from using lucky egg

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#1500]
[16:06:34] (EGG) Used Lucky Egg, remaining: 4
[16:06:47] (EVOLVED) Abra successfully for 1000xp
[16:06:48] (INFO) Evolved into Kadabra CP: 83 Iv: 92.65%
[16:07:19] (EVOLVED) Geodude successfully for 1000xp
[16:07:20] (INFO) Evolved into Graveler CP: 147 Iv: 92.11%
[16:07:45] (EVOLVED) Ponyta successfully for 1000xp
[16:07:47] (INFO) Evolved into Rapidash CP: 1179 Iv: 92.10%
[16:08:07] (EVOLVED) Ponyta successfully for 1000xp
[16:08:08] (INFO) Evolved into Rapidash CP: 1177 Iv: 91.35%
[16:08:42] (EVOLVED) Geodude successfully for 500xp
[16:08:42] (INFO) Evolved into Graveler CP: 642 Iv: 89.61%
[16:09:12] (EVOLVED) Abra successfully for 500xp
[16:09:13] (INFO) Evolved into Kadabra CP: 15 Iv: 90.17%

lucky egg disappears when not using it in official app only. 
i've tested this on official app as well. if you pop a lucky egg, and close app (not log off just close the app off task mamanger) and log in in two minutes later, the lucky egg disappears if it is not detected by official app. i RECOMMEND EVERYONE to STOP using evolve with lucky egg feature until this has a proper work around.

**Comment by Cryptologism** [comment]
Are you sure avout tbis? Try to mention sir lunatic here... Maybe test is required for these problem..

**Comment by kingkai808** [comment]
test maybe required, but i just replicated this again on a different bot. same issue.

**Comment by kingkai808** [comment]
@Lunat1q

**Comment by ShadyBS** [comment]
You mean it dissapears if you close the app? I dont understand the issue.

**Comment by kingkai808** [comment]
Yes. U cannot use it from 3rd party anymore. Has to be in the official app only. Otherwise it'll disappear after 2 minutes. And possibly may be a potential flag

**Comment by petoe93** [comment]
how do you know its disappearing after 2 minutes? 
do you log in the app to test it?

**Comment by kingkai808** [comment]
Yup. Plus look at my log. It disappears after two minutes and only gives 500 xp. Per evolve.
Logged in with official app and lucky egg is indeed gone from timer and -1 lucky egg from inventory.

**Comment by ShadyBS** [comment]
I cannot reproduce this. My log from yesterday: http://pastebin.com/SiEDzPvG
60 evolves, all 1000 xp,

**Comment by ShadyBS** [comment]
@Lunat1q let me know if I can do anything to help test this.
I think you guys might have experienced a bug in the game itself

**Comment by kingkai808** [comment]
I just tested this again on the official app. Logged in under a new account. Used an egg. Opened another app and egg timer disappeared when going back to app after a few minutes. Oddly enough though when my second bot used an egg it granted 1000xp per evolve then went away started giving 500 xp and then magically gave 100 xp back again. So not sure what's going on.

**Comment by redbone75** [comment]
a bunch of evolves of lv: 90%+ could set off a trigger.  I bounce around prioritizing IV over CP until I get what I want.

**Comment by Mordascar** [comment]
not likely. it's quite easy to acquire and then evolve multiple IV 90%+ pokemons, it wouldn't make sense for this to be a trigger

**Comment by Spk345** [comment]
I have tested this again and again, and I'm not having any issues with any of the newer releases. If this was a bug, it has been fixed.
