### ISSUE TITLE
[Feature Request] Pause bot, when transferring, Evolving ect...

### ISSUE THREAD

**Issue by fayssal90210** [Lunat1q/Catchem-PoGo#1501]
Hello

can you add a feature to pause the bot from catching, Walking, when doing other action like batch transferring, Evolving ect ...

and not getting the "_Player Too Busy_" Message

**Comment by eatingtunic** [comment]
Yes, I prefer to pause bot when we doing any manual transfer, evolve, renaming so that not getting the "wait" message

**Comment by Lunat1q** [comment]
Nope, there is no way to "pause" bot for now. I'll think about to add player action queue or something, but not ready to do so atm.
