### ISSUE TITLE
not getting level rewards

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1502]
seems this problem is not exclusive to catchem

https://github.com/PokemonGoF/PokemonGo-Bot/issues/1242

I don't know what I do to trigger getting the level up rewards, as I don't have a current phone account running for my bot account

**Comment by Lunat1q** [comment]
Catchem getting levelup rewards. Just tested it, also added logic to re-check leveluop rewards on start.
