### ISSUE TITLE
[Sggestion] Add options in scheduler.

### ISSUE THREAD

**Issue by dugarila** [Lunat1q/Catchem-PoGo#1505]
Add the option to, for a certain chosen hour in the schedule, catch a max amount of pokestops and another option to a certain amount of pokemons to catch. So if for example the value of total pokemons are caught in that hour, the bot stops to catch pokemon until next hour. Same for pokestops.
This way I think it'll be a better way to prevent soft bans referent to max amount of pokemon/pokestops per hour ban, I know the bot as the option to stop for certain amount when desired limit is reached but I feel that is not the efficient way to not get banned and still get decent exp/hour (even if it's only 20k) as I notice the bot stops for way too much time and runs for little, when I feel it could run longer and still not get banned. Also when that option is on, very often the pokemons/pokestops reached per hour are less then what I inserted in the settings but the bot stops anyway.

**Comment by Lunat1q** [comment]
You have Rate/h pause already, no need to put in into catchem.
Also, it's hard to read suggestions, when they are not properly formatted.

**Comment by dugarila** [comment]
Yeah it's hard to reply to anyone when I clearly made my intentions cleared and IF YOU LOOK CLOSELY I STATED WHAT YOU SAID IN THE FIRST LINE ("You have Rate/h pause already, no need to put in into catchem"). I made this upper capital so next time you can probably read all until the end and not ask stupid things such as "it's hard to read suggestions, when they are not properly formatted".

________________________________
De: Max <notifications@github.com>
Enviado: 7 de setembro de 2016 07:25:51
Para: Lunat1q/Catchem-PoGo
Cc: dugarila; Author
Assunto: Re: [Lunat1q/Catchem-PoGo] [Sggestion] Add options in scheduler. (#1505)


You have Rate/h pause already, no need to put in into catchem.
Also, it's hard to read suggestions, when they are not properly formatted.

-
