### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by KoopaTheTurtle** [Lunat1q/Catchem-PoGo#1509]
So i have 3 bots running.

1 in San Fran which runs fine
2 around Central Park. These 2 seem to have a problem...

they walk out into the middle of the ocean and then just idle there. It only seems to be around Central Park. I watched the player on Follow Player and it disappeared and started to rerender the map and went into the ocean :/ idk if this is the bot doing this or server stuff being derpy o-o

Im using GoogleDirections as the API and use Human Pathing

**Comment by Bay101** [comment]
have you got the API key set up correctly, does it route along streets normally then do this action?

**Comment by alanearl** [comment]
Create a manual route :)

**Comment by golgolak** [comment]
Mine's working fine on 4 bots and tested in multiple locations with a large body of water.
Config:
Routing Service - GoogleDirections
Google Directions - paste your google API key here
Human Pathing - True

Will test it out on central park as well...

**Comment by zhach01** [comment]
@KoopaTheTurtle are you using +2 bots one the same ips with out proxy ?

**Comment by ERAsor83** [comment]
maybe it uses a ship route

**Comment by saldotman** [comment]
in my case,
sometime the bot displayed just 'run away' straight to some places.
but actually it is not there. the actual, bot just walk fine.

**Comment by Lunat1q** [comment]
no reply for 2 days, looks like solved
