### ISSUE TITLE
Visual bug: If you have more than 1k candies it shows up as 0 in the information panel

### ISSUE THREAD

**Issue by oddhap** [Lunat1q/Catchem-PoGo#1510]
If you have more than 1k candies for a specific pokemon it shows up as 0 in the information panel. The console displays the correct number of candies.

**Comment by g00tch** [comment]
Must just be you, as it shows I have 1,997 Rattata candies, and 2,342 Pidgey candies under each one on my Information tab.

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/8uKdKep.png) working just fine
![](http://i.imgur.com/EQK2fuE.png)

**Comment by oddhap** [comment]
On further inspection it seems to just affect voltorb/electrode
![1](https://cloud.githubusercontent.com/assets/1021373/18306960/8306c966-74ee-11e6-91d3-8e3e44ce8dbb.png)
![2](https://cloud.githubusercontent.com/assets/1021373/18306961/8309db56-74ee-11e6-88fd-66c937dd24b8.png)
