### ISSUE TITLE
IV Pokemons

### ISSUE THREAD

**Issue by manieczek** [Lunat1q/Catchem-PoGo#1511]
Please add stats. example 100% 15/15/15

**Comment by Lunat1q** [comment]
hm, i'll think about this :) thanks

**Comment by SweeTIPi** [comment]
PLEEEEEEASE! ):

**Comment by kkirkk** [comment]
I did that way, I think it is a good idea:
![image](https://cloud.githubusercontent.com/assets/21146942/18316995/f7aa9f3c-74f2-11e6-8581-7df51465f12f.png)

**Comment by goiabs** [comment]
/\ Perfect!

**Comment by diorox** [comment]
good idea!

**Comment by Lunat1q** [comment]
Added already.
Atk and Def isn't calculated like Base + Iv.
