### ISSUE TITLE
[Feature Request] Pokeballs

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#1513]
Is there an Option to add the follow function to set manuel the Number of Pokeballs, Greatball, Ultraballs and Masterball like the Pic?
![unbenannt](https://cloud.githubusercontent.com/assets/21181078/18308088/596088c2-74f3-11e6-8b7c-e6548ad25313.png)

**Comment by eatingtunic** [comment]
very good feature if can implement

**Comment by Lunat1q** [comment]
Duplicate.
Tired of explaining how stupid is it over and over.
