### ISSUE TITLE
[feature request]export/import setting or auto update thanks 

### ISSUE THREAD

**Issue by berreta1987** [Lunat1q/Catchem-PoGo#1514]
this will be better if catchem has auto update software system or export/import setting
thank you

**Comment by opidvash** [comment]
Hello there,

You can copy your .json files to the new version to keep your settings (located in \Catchem\Profiles\NAME\config).

You can also copy catchem.json located in \Catchem\ to keep your custom routes.

Hope it helps!
Cheerz
