### ISSUE TITLE
Add sound to avert when forcemove is over

### ISSUE THREAD

**Issue by picobn** [Lunat1q/Catchem-PoGo#1515]
Could you add a sound to alert the user that the forcemove destination is reached.

Thx

**Comment by Lunat1q** [comment]
sorry, i have no plans to add any sounds in the Catchem yet. But i think i can add a "blinking" of Catchem icon when it's done, i'll take a look

**Comment by picobn** [comment]
That's perfect ! 

Thank you for your hard work

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/oqg1pos.png) it will be like that
