### ISSUE TITLE
Catchem version 1.5.2.0  Proxy Test:  Proxy Failed !

### ISSUE THREAD

**Issue by zootvmexico** [Lunat1q/Catchem-PoGo#1516]
I been runing Catchem version 1.5.0.0 now today I updated to 1.5.2.0  and when I go to the Proxy settings and fill my info and test it, I get a "Proxy failed" message its happenin with last Catchem update, worked perfect with 1.5.0.0.

Created a new profile just to be sure wasnt a profile error then I modify values and saved bot settings and tried to do a second test proxy with login and pass and the same "Proxy failed" message window.

Could someone verify this BUG !!!

Thanks

**Comment by zhach01** [comment]
run your bot with administrator privilege that should help :p @zootvmexico

**Comment by zootvmexico** [comment]
Zhach01, that fixed the problem !! for Catchem old versions I never run as administrator privilege !!
