### ISSUE TITLE
Always use masterball

### ISSUE THREAD

**Issue by Anisagithub** [Lunat1q/Catchem-PoGo#1518]
I don't know why it always use masterball in first then when it's run out it's use greatball. If masterball and greatball was over then it's uses normal ball. Help me please..

**Comment by lonelies** [comment]
Maybe your "Use Great Ball above IV" is set at high IV. Try to set it lower. Maybe this way your bot will use your masterball as last option. 

<a href="http://imgur.com/6h7IZNN"><img src="http://i.imgur.com/6h7IZNN.png" title="source: imgur.com" /></a>

**Comment by petoe93** [comment]
how can you have master balls? where to find them??

**Comment by Lunat1q** [comment]
No future data. closing.
