### ISSUE TITLE
[Feature Request]Telegram message details

### ISSUE THREAD

**Issue by Dequim** [Lunat1q/Catchem-PoGo#1519]
Hi

I'm thinking on the telegram features, i think it would be good to choose what details you want to include into the messages. Like i don't really care about what profile, or the moves, instead i would like to see the coordinates... So a ckeckbox collection or a patternfield maybe?

Thanks for your hard work! :)

**Comment by nilsbrychzy** [comment]
Like when the bot receives `loc` then it sends you his location via map?

**Comment by Dequim** [comment]
for example when i catch a pokemon i want to know the location coords of the poke or maybe the closest pokestop's name for the easier location finding next time i want farm that one poke.
not so important, just an idea :)

**Comment by Lunat1q** [comment]
Sorry, we have no plans to implelemnt it for now.
