### ISSUE TITLE
HELP!! Can't open 

### ISSUE THREAD

**Issue by angelotoh4** [Lunat1q/Catchem-PoGo#152]
I have no idea what to do, please help

![14060431_10205704928657264_1522758959_o](https://cloud.githubusercontent.com/assets/21071675/17722149/9fb0f4de-6462-11e6-9e28-e421639c52a3.png)

**Comment by Bay101** [comment]
Update .Net framework

**Comment by Lunat1q** [comment]
should be stable in 1.4, otherwise u have .net lower then 4.5
