### ISSUE TITLE
Candy and transfers

### ISSUE THREAD

**Issue by 123pepo321** [Lunat1q/Catchem-PoGo#1520]
Sorry  to bother you but the last release 1.5.2.0.7.7z  has 2 issues: when you transfer some pokemon all the duplicates show like the have no candy, also dont let you transfer them, evolve or do anything with those duplicates, also rattata: there is always 1 in your inventory that you cant transfer and stays there till you close catchem and restart the bot

**Comment by Lunat1q** [comment]
Fixed in 1.5.2.1
