### ISSUE TITLE
[Minor Bug] Evolved pokemon

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#1522]
Evolved pokemon will show the Max CP & Possible CP of the previous pokemon instead of the evolved one. For example below, the Max CP & possible CP displayed is the Magikarp's data. This data however will be solve if you restart catch'em. Just reporting :p

<a href="http://imgur.com/opkwT9Y"><img src="http://i.imgur.com/opkwT9Y.png" title="source: imgur.com" /></a>

**Comment by petoe93** [comment]
you don't need to restart the whole bot again, just refresh the pokemon list manually & it'll be fine ;)

**Comment by lonelies** [comment]
ohh. aight. ty for the fix
