### ISSUE TITLE
Problem for (v 1.5.2)

### ISSUE THREAD

**Issue by percival0207** [Lunat1q/Catchem-PoGo#1529]
![pg](https://cloud.githubusercontent.com/assets/21152060/18326325/c7f3c4e6-7577-11e6-9316-31a9e05e409c.png)
![pg2](https://cloud.githubusercontent.com/assets/21152060/18326326/c7f9d002-7577-11e6-86d9-9db150895bd2.png)

I don't know what happened in my Cathem. Please help me @Lunat1q . Thank you.  :)

**Comment by Lunat1q** [comment]
Unstable internet.  Mostly. It was discussed previously, you can try to go to the Discord help chat.

**Comment by percival0207** [comment]
Thank you for your fast feedback. :)
