### ISSUE TITLE
Schedule - Needs an Update - randomized

### ISSUE THREAD

**Issue by ERAsor83** [Lunat1q/Catchem-PoGo#1530]
I was thinking about the situation the Bot loggs in and out on a perfect 1,2,3,4,5,6 hour circle. "N" could easily check Players who log in and out after an hourly circle. BAMMM BAN ;-)

TH schedule needs adjustments. 
One thing could be to randomize everythink at the end.. like you told the Schedule  8 till 12. The Program ends with 8:07 - 11:48

Another Option would be to do 1440 individual bars (24x60 Minutes) the Player presses it with the mouse and automatically does the random cicle by himself.  IIIII IIIII III**II IIIII IIIII IIIII IIIII II**III IIIII IIIII    

I hope this helps and could be implemented very fast. because right now its waaaaayyyy to dangerous to use the Schedule.

Era

**Comment by Lunat1q** [comment]
start time being randomized every time, same as the stop time isn't XX:00:00 every time. so, i see no point in randomizing all that stuff.
