### ISSUE TITLE
[1.5.2.0] Proxy Problem

### ISSUE THREAD

**Issue by pleathunder** [Lunat1q/Catchem-PoGo#1532]
i configured the proxy, and in the test say it's working fine. so i start the bot, he log in the account, evolve, transfer, recycle and walk like a crazy in the city.
here's the problem: the bot dont found any pokestop/pokemon in the walk, so he just walk around the city doing anything.
when i disable "Use Proxy" and run the bot, everything is ok.
something i'm doing wrong?

btw, i can run more than one bot (with or without proxy) without get a soft ban/perm ban?

**Comment by Cryptologism** [comment]
Private proxy or free proxies?

**Comment by alanearl** [comment]
IP Ban :) use paid proxies.
