### ISSUE TITLE
Problem-Bot stop for 4 or 6 hours

### ISSUE THREAD

**Issue by angelaayer** [Lunat1q/Catchem-PoGo#1534]
Hi. Thank you for al your great job!

I just have this problem. I have been using catchem almost for 1 month, everything worked good since days ago when the latest two releases I have tried I have the problem of my bot that I use it only for one hour per day and it stops for 6 hours. I didnt change my config it is as usual. Please help me.

![20160906_155112](https://cloud.githubusercontent.com/assets/21321158/18331878/b599eef6-7527-11e6-9c3c-1a6f0913a24b.jpg)
![config](https://cloud.githubusercontent.com/assets/21321158/18331879/b59c4d36-7527-11e6-8c85-eabfee16fcb1.jpg)

**Comment by cruise4** [comment]
u set config Max xp Per Hour 1000 (one thousand)and choose to pause bot on max hourly rates
your bot get 7.147 xp in 1 hour    and it will stop six hours
Max xp Per Hour should be 10000 (ten thousand)
Max stardust should be 20000

*sorry for bad english*

**Comment by angelaayer** [comment]
Im spanish speaker so if u know spanish explain me what am I doing wrong. 
I thought 1000 was the maximun amount for xp to avoid ban. So i was wrong and it should be 10000?

**Comment by TomWolker** [comment]
no hablo español, mas hablo portugues xD

Muitas pessoas conseguem 75k de exp à cada 30min. O limite de exp é de 999.999exp por dia, e caso você ultrapasse levará softban. Resumindo: o bot nunca conseguirá tanta exp, pois ele é lento, então você não precisa configurar isso, deixe um número bem alto...

**Comment by Lunat1q** [comment]
yes. 1000 is a poke amount per day.
