### ISSUE TITLE
Possible Ban Recognition from Transfer Pokémon

### ISSUE THREAD

**Issue by diorox** [Lunat1q/Catchem-PoGo#1535]
I transfer pokemon group while the Catchem Bot continued to try catch a Pokemon. Maybe Niantic can see these actions. 
Thanks for upgrading the great bot :smiley: 
Regards!!

  ![sin titulo](https://cloud.githubusercontent.com/assets/15343342/18332015/8cd4ec70-7539-11e6-964c-dc907319c040.png)

**Comment by pleathunder** [comment]
i see that too, nothing happens yet.

but i get soft ban when i select and transfer 10+ pokemons. after the transfers the character simply walk on the map, no loot pokestops, no found pokemons...

im not using the transfer function atm.

**Comment by Cowering** [comment]
I think this is a dupe of the 'catch should be atomic' bug. i've never transferred 10+ at a time, but I have evolved 10+ at a time without a ban

**Comment by Lunat1q** [comment]
Try the latest. Some improvements there
