### ISSUE TITLE
time for automatic transfer

### ISSUE THREAD

**Issue by romeuwb** [Lunat1q/Catchem-PoGo#1536]
make an implementation that makes the bot always transfer at any given time, not only when the inventory is full.
[20:00:05] Pokemon Inventory is full, transferring Pokemon...
[20:00:06] [Inventory] Pokemon Stored: 242/250
[20:00:17] Pokemon Inventory is full, transferring Pokemon...
[20:00:17] [Inventory] Pokemon Stored: 242/250
[20:00:26] Pokemon Inventory is full, transferring Pokemon...

**Comment by angelaayer** [comment]
i think that is something linked to your configuration, you can change that on settings.

**Comment by pleathunder** [comment]
Transfer happens after cleaning inventory too.
Maybe something with your transfer settings, check to see if anything is wrong, seems the bot isnt' transfering any pokemon.
Plus in the new transfer filters, if you set high numbers on 'keep min duplicates' alot of pokemons will be keeped on the inventory.

**Comment by pcpai** [comment]
the 250 spots its only 241 pokemon and 9 eggs
the eggs uses space of pokemon and bag if incubated

**Comment by pleathunder** [comment]
not really... i count my pokemons and the store number match

and i have 3 eggs incubated

**Comment by romeuwb** [comment]
until I can accept that I have something set up, miss most would be more interesting to have a time for automatic download bot, I'm not always around to clear the inventory or transfer manual, I always keep two duplicate

**Comment by romeuwb** [comment]
for example PokemonGo-Bot (https://github.com/Ar1i/PokemonGo-Bot)
from time to time it will automatically make the transfer, thus avoiding getting full

**Comment by Lunat1q** [comment]
You have wrong settings setup. Join discord to get help.

**Comment by Lunat1q** [comment]
Bot transfer Poke automatically from time to time.

**Comment by romeuwb** [comment]
good, it was a suggestion and informed, even though the program was wrong transfer in a range defined by User, my case it is full and not tranferi, is repedindo this error down until I make manual

[20:00:05] Inventário Pokemon está cheio, transferindo Pokemon ... 
[20:00:06] [Inventário] Pokemon armazenado: 242/250 
[20:00:17] Inventário Pokemon está cheio, transferindo Pokemon ... 
[20:00:17] [Inventário] Pokemon armazenado: 242/250 
[20:00:26] Inventário Pokemon está cheio, transferir Pokemon ...
