### ISSUE TITLE
Suggestions - Translation, etc.

### ISSUE THREAD

**Issue by r0ds** [Lunat1q/Catchem-PoGo#1537]
-**T**ranslation of the other tabs (Settings, Telegram, Poke Lists, Batch Creation, and so on.)
-Also Enable the use of incense. More stardust <3
-Search Box to find the name of the Pokemon in tab 'Information', facilitating research to confirm for example if caught such pokemon.
-System Of PokeSniper, warning of the dangers (High chance ban?)
______________________________________________
_Best English =D
translate.google.com_

**Comment by Lunat1q** [comment]
Generic translation interface is planned, not yet done.
