### ISSUE TITLE
(EGG) Incubator status update: 4,32km left 

### ISSUE THREAD

**Issue by alcianderson** [Lunat1q/Catchem-PoGo#1538]
Please help me.

works for about 30 minutes after is only giving this message !

I do not know what to do, help me lunat1q .

[ 21:31:55 ] ( EGG ) Incubator status update : 4,32km left
[ 21:38:47 ] ( EGG ) Incubator status update : 4,32km left
[ 21:47:57 ] ( EGG ) Incubator status update : 4,32km left
[ 21:56:32 ] ( EGG ) Incubator status update : 4,32km left
[ 22:04:31 ] ( EGG ) Incubator status update : 4,32km left
[ 22:11:48 ] ( EGG ) Incubator status update : 4,32km left
[ 22:18:58 ] ( EGG ) Incubator status update : 4,32km left
[ 22:25:58 ] ( EGG ) Incubator status update : 4,32km left
[ 22:33:53 ] ( EGG ) Incubator status update : 4,32km left
[ 22:42:10 ] ( EGG ) Incubator status update : 4,32km left
[ 22:52:25 ] ( EGG ) Incubator status update : 4,32km left
[ 23:00:27 ] ( EGG ) Incubator status update : 4,32km left

**Comment by MarkoHess** [comment]
That happens if you are walking too fast or you are getting an IP ban after your 30 minutes.

**Comment by saldotman** [comment]
try to stop. wait a few minutes, then start again.

I notice that this happen sometime, but can not recognize yet when this case occurs

**Comment by Wombidou** [comment]
@MarkoHess Are you sure it's a ban ?

**Comment by robertof157** [comment]
Also I would like to know a solution stop this problem

**Comment by Lunat1q** [comment]
Your speed is way too high, or servers are way too busy, but that doesn't happen now that much.
