### ISSUE TITLE
[Feature Request] Location confirmation

### ISSUE THREAD

**Issue by dgiancarloz** [Lunat1q/Catchem-PoGo#1540]
Hello developers team.

I would like to thank you guys for the wonderful job you did.

today i unknowingly logged in to my outdated version of catchem which is v1.4.9.4 second release, not knowing that the latest version is v1.5.2.0.

I set my coordinates correctly and suddenly i'm somewhere half way around the world.

I would suggest that there is a pop up confirming the location of the bot before it actually logs in Niantic's server. that way we can make sure that we are in the intended coordinates to avoid any suspicion triggered from the Niantic side.

I thank you in advance if you could add this feature.

Keep up the good work guys. you're all awesome. 

p/s: I dont know how to label this as a feature request. sorry.

**Comment by whelvenus** [comment]
well actually there is, right?

(ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 14.5827580577667 Lng: -120.97440553035 Alt: 7

**Comment by alanearl** [comment]
Verify first http://www.latlong.net/ your location before clicking start button.
Dont type the lat & long. Always use copy paste.

**Comment by dgiancarloz** [comment]
> 
> Whelvenus commented 31 minutes ago 
> 
> well actually there is, right?
> 
> (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 14.5827580577667 Lng: -120.97440553035 Alt: 7

What i mean is, a popup so that it shows where exactly our location is in a map of some sort and we can confirm it before it commits. The one we have now does not require our confirmation and a lot of people would not know exactly where the location is with just a mere lat and lng. You'll only realize it when you read that your character is thousands of km away from the nearest pokestop that you set your route at.



> 
>  alanearl commented 16 minutes ago
> 
> Verify first http://www.latlong.net/ your location before clicking start button.
> Dont type the lat & long. Always use copy paste.


I did make sure the lat and lng are correct. I saved the coordinates in docx file and would copy paste it whenever needed.

but whenever i start the bot, it changed into the same location which is not what I intended. Perhaps it is caused by the difference in the version i used. I don't know and I dare not replicate the error for fear of detection from Niantic's

**Comment by dgiancarloz** [comment]
@Lunat1q Thank you for your consideration.

**Comment by KitazawaMoa** [comment]
Good idea,hope luna will add it soon. It will help some player that somehow input wrong coordinat in their config which lead them to midle of nowhere or getting notice "No usable pokestop".

**Comment by Lunat1q** [comment]
added 5 sec + delay between player action to check lat/lng
