### ISSUE TITLE
do you think this is possible?

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1541]
Hi, I play using bot, and just reach level 30.
I just run my bot, never do anything (transfer, evolve, etc.) manually.
but today, when I check my log, I see the following

[12:09:41] (EVOLVED) Horsea successfully for 500xp
[12:09:43] (INFO) Evolved into Seadra CP: 22 Iv: 55.02%
[12:10:00] (INFO) [Inventory] Pokemon Stored: 417/500

quite interesting, since to have Horsea evolve to be Seadra CP 22, it means my Horsea should be CP 9.
and I don't think in level 30, I got 12-15 Horsea with CP always less or equal than 9.
If I got a Horsea with CP higher than 9, then the Seadra should be higher than CP 22

**Comment by domg839** [comment]
It probably had a higher IV level. Do you have it set where the bot keeps the higher IV?

**Comment by Lunat1q** [comment]
Why not? it's just a matter of luck

**Comment by saldotman** [comment]
no.

I check the prioritize both iv and cp,
I uncheck prioritize IV over cp

**Comment by saldotman** [comment]
finally, I got the answer.

from my investigation,
if I have two pokes that are able to evolve, the bot will evolve one that
has higher IV rather than higher CP.
