### ISSUE TITLE
Confuse on sorting by DPS

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1543]
![image](https://cloud.githubusercontent.com/assets/21153898/18340004/d90aa9de-75cc-11e6-9cdf-ac9705f3e23a.png)
![image](https://cloud.githubusercontent.com/assets/21153898/18340009/e253c930-75cc-11e6-8fc2-e880f11f9027.png)
![image](https://cloud.githubusercontent.com/assets/21153898/18340011/e712366e-75cc-11e6-879d-8caa26cac56d.png)

how are they sorted?
doesn't seem by DPS

**Comment by Lunat1q** [comment]
They are sorted by possible DPS, calc isn't DPS1 + DPS2.
![](http://i.imgur.com/HAAlrh4.png)
