### ISSUE TITLE
Some problems and suggestions

### ISSUE THREAD

**Issue by Cryped** [Lunat1q/Catchem-PoGo#1550]
Hey everyone,

first of all your bot is one of the best bots which I have ever test before ! :+1: 

Now the bugs:
-If you want to change the name of a pokemon, nothing happens....
-sometimes the bot does not move forward. The bot stands at one point and does not move or move just to the last pokestop. Here a screenshot to understand what I mean: 

http://www.directupload.net/file/d/4472/zplr5nix_png.htm

So the bot moves from the one pokestop to the first one and than to the other one and back...
- the task list is sometimes buggy

Suggestions:
-Autounbanner
-set a region(s) for xxx minutes 
-break handler to set breaks manually
-google map route finding heuristic (Road walk, road fly and more...)

I`m looking forward to hear for you

**Comment by alanearl** [comment]
Try to use manual route on routecreator.

**Comment by Lunat1q** [comment]
Autounbanner? wann toss me a logic?
All other features your proposed is there
