### ISSUE TITLE
Got perma Banned ? 

### ISSUE THREAD

**Issue by eloxxx** [Lunat1q/Catchem-PoGo#1551]
![gggggggggggg](https://cloud.githubusercontent.com/assets/21296701/18345423/b04d4256-75bb-11e6-9519-36b067138e34.jpg)

**Comment by Lunat1q** [comment]
try to login with the phone

**Comment by eloxxx** [comment]
Will do it in 2h,  I will tel you if its working or not

**Comment by cheessyong** [comment]
Not ban.

**Comment by eloxxx** [comment]
Guys, 

It was a pb with gmail.

They froced me to change my password.
So I put a new password for my gmail account and now its working fine.

Thanks
