### ISSUE TITLE
(ERROR) Access token expired. Relogin to get a new token.

### ISSUE THREAD

**Issue by ShipkiyShpiller** [Lunat1q/Catchem-PoGo#1557]
Suddenly happened two days ago with all the bots. What is it?
Два дня назад случилось со всеми ботами. Что это такое?
![screenshot_16](https://cloud.githubusercontent.com/assets/21309823/18349905/af4ff2d2-75d3-11e6-8d8d-ff8fbdec6730.jpg)

**Comment by alanearl** [comment]
Google Account Problem... try to login on web browser using google account.

**Comment by ShipkiyShpiller** [comment]
I tried. No problem with web browser using. But it did not help.  In Profels/config have found that string - "GoogleRefreshToken": "",
it should be like this?
