### ISSUE TITLE
[09:58:10] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by iaecengcvl** [Lunat1q/Catchem-PoGo#1559]
I have the latest version and show this message:

[09:58:10] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

![01](https://cloud.githubusercontent.com/assets/21683186/18350269/7f0bb912-75ab-11e6-8d06-334540dd52e7.jpg)

**Comment by alanearl** [comment]
Restart your modem. IP Ban.

**Comment by eloxxx** [comment]
yes IP ban don't worry about it, 

Try to stay in your IP range and don't run simultanieous bot.
