### ISSUE TITLE
snipe option

### ISSUE THREAD

**Issue by bel0g** [Lunat1q/Catchem-PoGo#156]
why is it disable?

**Comment by TemhAAhmeT** [comment]
You can edit from config.json. Probably it is disabled because of sniping is not safe nowadays.

**Comment by bel0g** [comment]
i see thank you very much
can we put an option to always capture a specif type of pokemon for farming

**Comment by erazyon** [comment]
Yes you have the pokemon to snipe in the config.json, if you erase them and put only pidgey it will snipe only pidgey
