### ISSUE TITLE
[Suggestion] "Force move to" option add more pin to input in live map

### ISSUE THREAD

**Issue by tvMed** [Lunat1q/Catchem-PoGo#1564]
My idea is to allow trainer add various pin (max 5 or more) "Force Move To" on the live map.
This way the trainer can make a manual live route, while trainer moves from pin to pin to complete the amount of manual pins marked on the map.
If trainer is in a manual or automatic route, Catchem to see the pins to "Force Move To", performs the process in the number of "Force Move To" inserted and the end returns the initial route (manual or automatic).

My English is bad, sorry.

**Comment by Lunat1q** [comment]
sorry, nope.
