### ISSUE TITLE
[ issues not display] i Can't display my pokemon status order by all function

### ISSUE THREAD

**Issue by rockaun** [Lunat1q/Catchem-PoGo#1565]
I detected a problem in catchen 1.5.2.1
i Can't display my pokemon status order by all function

**Comment by Lunat1q** [comment]
what? i didn't get what you mean

**Comment by ArchangelBr** [comment]
I got it here too... you have to "unmark" the old one to get the order by the new one.

Just like this:

You order by DPS
Then you order by CP (does not work)

But, if you click DPS again and then click CP, it works...

I don't know if I could help, my english is not so good

**Comment by Lunat1q** [comment]
May be because it's multiple sorting now? and if you sorted by DPS,then click CP it do CP as subsort?

**Comment by rockaun** [comment]
I understand.


Thanks for the answer to solving this problem.😊

2016-09-08 23:14 GMT+07:00 Max <notifications@github.com>:
