### ISSUE TITLE
[FEATURE REQUEST] usesnipelocationserver

### ISSUE THREAD

**Issue by kingbeelzebob** [Lunat1q/Catchem-PoGo#1566]
Can u ADD the usesnipelocationserver???? PLS!?!?!?! your bot would be perfect for me if it had the snipe function.. Some people who dont like it can just set it to false no worries..

**Comment by Cryptologism** [comment]
Nope.. There are big NO for sniper function.. ALready tell adn talk this mill time.. No No No...
