### ISSUE TITLE
Is this a new feature? Confused

### ISSUE THREAD

**Issue by gleichmann** [Lunat1q/Catchem-PoGo#1567]
So, when I keep my bot on, I get this thing.
It lights up like some notification?
 I'm not quite sure what it does or what it signals?
http://imgur.com/3iBM7J1

**Comment by Lunat1q** [comment]
If you could read release notes, you will see what it mean.

**Comment by Cryptologism** [comment]
Lol...
Here dude... https://github.com/Lunat1q/Catchem-PoGo/issues/1515
