### ISSUE TITLE
(ERROR) Access token expired. 

### ISSUE THREAD

**Issue by angelotrinario** [Lunat1q/Catchem-PoGo#1568]
Access token expired. Relogin to get a new token. how to fix it? i log in chrome without problem, but cant log into the bot

**Comment by ShipkiyShpiller** [comment]
Same Problem!!!

**Comment by alanearl** [comment]
Did you try to login on google account using a web browser?

**Comment by ShipkiyShpiller** [comment]
Yes? without problem

**Comment by angelotrinario** [comment]
yes, I can login normally in browser :/

**Comment by alanearl** [comment]
Did you try to change password on your google account?
https://www.google.com/landing/2step/
Try to enable google account verification.

**Comment by ShipkiyShpiller** [comment]
Changed password,.. tryed account verification. Still problem. But if I try to use VPN all OK ..... o_O

**Comment by Lunat1q** [comment]
should be fixed... mostly
