### ISSUE TITLE
traveling

### ISSUE THREAD

**Issue by madgar29** [Lunat1q/Catchem-PoGo#1570]
The way the bot Travels is gonna get me banned. I am already soft banned because of it.  It us say I travel for a living or im a millionaire and im playing pokemon go... I can safely travel from coast to coast give it 8 hours for travel time in a plane? pokemon go is okay with this its reality people move around.  The bot moves me from my last location to new like im walking...... it needs to detect okay my location changed I start there I dont move there. Just like my phone if im at home then i turn pokemon go off and I  travel 50 miles north where the city is pokemon go teleports me there doesnt move me over. this will help prevent bans for fake teleports which im not trying to do im trying to make the bot understand i gave you 8 hours now im over here. i didnt speed run.

**Comment by petoe93** [comment]
what are you talking about dude? i don't get it..
you can set a certain point to start by double clicking on the map before starting the bot.. and you can also set your walking speed up to 100+ if you want to travel fast or whatever..just going to say that this is going to get you banned..
the bot is doing it's best to avoid you being banned so i really don't see your problem..Lunat1q is doing great work on this one

**Comment by Lunat1q** [comment]
this issue make no sense, if you want to discuss bot logic, go to discord.
