### ISSUE TITLE
Telegram Command Bug or Catchem Bug?..?

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#1571]
Greetings all.. A liltle problem here..

Chronology : 

**Bot 2** = Im use command in telegram **poke 2 cp** = (it should show the listing pokemon in bot no 2 right?)
And yes it does show the listing of **pokemon for bot 2** with **detail IV and CP** but...

Im use same cmd **"poke 1 cp"** for **bot no 1** but it did not show any report about the **bot no 1** which is should be shown like **Bot 2**......
Im trying with others bot too 3rd,4th,5th and so on.. All was ok.. Only bot no 1 is a problem... Why is that actually and is there any log to see where and what the error came from?

Others is what is this command for the highlighted one--> "poke [bot number] [iv/cp] **[poke id]**"
I try put id according to Google Id Pokemon.. Also not working...

Anyone?

@Lunat1q 
@Bay101

**Comment by Lunat1q** [comment]
Well, it works foe me just fine :)
just tried poke 1 cp and it's ok

**Comment by Lunat1q** [comment]
poke 1 cp pidgey
works fine too

**Comment by Cryptologism** [comment]
Greetings sir... I think i know why... 
I just restart my pc then i run this Catchem as administrator... Then i let them bot.. after 15 minutes later... i try those command it works like charm... I think it was because 2 things...

1: **Must running as Administrator**
2: **Must give them(a bot / Catchem) a time for moment to stabilize the code reading**

There you go...
