### ISSUE TITLE
Altitude setting is ignored

### ISSUE THREAD

**Issue by sinuraya** [Lunat1q/Catchem-PoGo#1573]
![image](https://cloud.githubusercontent.com/assets/5442013/18361939/3052aa14-762e-11e6-84d4-914b30952e85.png)

As seen in the picture above, max and min altitude is ignored.

**Comment by itterror** [comment]
its ignored when you use mapzen elevation.

**Comment by Cowering** [comment]
Yes, same happens to me. I just lookup average altitude of whatever city i'm roaming and manually set it to a range and uncheck mapzen.

**Comment by Cowering** [comment]
perhaps bot should only use mapzen when it gets a value between what you already set up

**Comment by Lunat1q** [comment]
improved mapzen algo a bit, should be better now.

**Comment by sinuraya** [comment]
No, I'm not using mapzen. The altitude just go crazy all the time.

![image](https://cloud.githubusercontent.com/assets/5442013/18365788/3b37da7a-763e-11e6-8843-88e37f7aee6a.png)

As you can see no mapzen ticked, but the bot still ignore the max and min altitude.

**Comment by sinuraya** [comment]
The problem is bot can't find any pokemon nor pokestop when the altitude above 50 or below -50
