### ISSUE TITLE
1.5.x UI is brighter than previous versions?

### ISSUE THREAD

**Issue by petoe93** [Lunat1q/Catchem-PoGo#1577]
maybe someone else is also experiencing this..the 2 or 3 latest releases seem to have an extra layer of brightness in the UI..
tale a look at the console for instance..for me, it used to be a nice, dark black background, now it looks way more brightened up like a very dark grey (or very dirty black). i hope you know what i mean ^^
and it's not just the console on the bottom, the whole UI seems to be affected by this, but the console is where you see it mostly.
and no, i didn't change any of my display settings..even on lowest config (0% brightness according to Win 10) its still not the good old black in the console :/
Great work either way, really appreciate the dedication of @Lunat1q and majority of the community around here :)

**Comment by Lunat1q** [comment]
it's absolutely the same. Didn't change anything except console log background, it's actually darker now :)
