### ISSUE TITLE
Running background.. i guess

### ISSUE THREAD

**Issue by acidwae** [Lunat1q/Catchem-PoGo#1578]
Hi, i dont know why, but my catchem is running hidden (and i cannot access it). I cant find the process alt tabbing but when i press ctrl alt del, i see the process running.

any ideas?

tried to reboot, shutdown, reinstall, clean up logs..

**Comment by Lunat1q** [comment]
what is your .net version?

**Comment by acidwae** [comment]
help me to check the version lol

**Comment by acidwae** [comment]
it was running until yesterday

**Comment by Cryptologism** [comment]
ermmm... well you can download in here
https://www.microsoft.com/en-us/download/details.aspx?id=48137
and install it...
If it was already said save version then it was installed correctly...
i think maybe you have something 3rd party program that hiding those Catchem.. Try to check the Task Manager program.. One by one..

**Comment by acidwae** [comment]
well, i was looking for any weirdo or new application installed here (by me or wife) and nothing. But i notice one thing: it is happening to any app i tried to execute. they open and run hidden.

**Comment by Cryptologism** [comment]
What os u use?
Try to look more deeper in control panel uninstalling section... 
This 'thing' was trying to hidden all process that you running...
Also try to restart you pc... & check in msconfig what did you setting when after pc reboot... what kind of software that enable to running after pc reboot first...

**Comment by acidwae** [comment]
im using win7

last night i shutdown the bot, turn off my notebook and turn on today again few hours ago. I visited this page to download any update available and that happened.

i checked all progs installed and nothing new.. nobody even used this notebook since last night.

**Comment by alanearl** [comment]
Did you try rebooting your notebook?
Try this better than task manager.
https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx

**Comment by acidwae** [comment]
yes i did.. same thing.

**Comment by Spk345** [comment]
Join us on discord if you are continuing to have this issue with the newest pre-release.
