### ISSUE TITLE
Not moving, no pokestops

### ISSUE THREAD

**Issue by Chris13564** [Lunat1q/Catchem-PoGo#158]
I have tried the new and old versions. Every time I log on [via my gmail] and I start my bot it just says No pokestops in my area. And I cant make my guy force move anymore PLZ help as this is a really amazing project.

**Comment by g00tch** [comment]
Sounds like you're under a softban. Try again in a few hours.

**Comment by g00tch** [comment]
Or, try a VPN or Proxy to change your IP.

**Comment by BrLord** [comment]
It is NOT a softban, other bots works. But this one is the best by far
