### ISSUE TITLE
Transfer Poke

### ISSUE THREAD

**Issue by nobilus** [Lunat1q/Catchem-PoGo#1580]
Hello Guys, 

Trouble with transfer...  With these settings, catchem doesn't made transfert and keep us in bag ...
Don't understand why .. rules are if pokemon had 1250 CP and 90 % IV, or 1250 CP or 90 % IV ?

![capture](https://cloud.githubusercontent.com/assets/22085305/18366042/63f3cec0-7615-11e6-9b92-6b8048f62db8.JPG)

![capture2](https://cloud.githubusercontent.com/assets/22085305/18366278/594ef5ca-7616-11e6-8845-78f3a9b0d9c9.JPG)

Thks a lot.

**Comment by eloxxx** [comment]
If you want to keep 1250 CP or 90 IV
Uncheck "Prioritize IV over CP".

But if with this setting your pokemon bag is full, it gonna tranfert rondomly. So sometimes don't forget to tranfert some Pokemon manually like some 1300 CP which r not so good.

**Comment by nobilus** [comment]
OK Eloxxx Thks a lot. And if i want to keep only Poke With 1250 CP and 90 IV and more ? Uncheck "Prioritize IV over CP" too ?

And Tks Lunat1q, love your work !

**Comment by eloxxx** [comment]
You want to keep only pokemon with 1250 CP and at the same time 90 IV ?

You can't do that I think, in this case you will lose 95% of your pokemon. It means You will lose a magikarp 180 CP with 100 IV !!
I don't think that there is such an option, it is useless.

**Comment by nobilus** [comment]
Yes but for magikarp i want to use this ... 
![capture3](https://cloud.githubusercontent.com/assets/22085305/18367262/83341600-761a-11e6-8205-ff2eb840f2bb.JPG)

Sorry but my english is bad ;)

**Comment by eloxxx** [comment]
ok I got it, you can use filter.

But for your previous question, I don't think you can keep pokemon only with 1250 CP and at the same time 90 IV.

I don't think there is such an option.

I tried all combinaons with catchem, and never seen such a result.

**Comment by nobilus** [comment]
LOL ok thks Guy.

What are your best result to keep only poke with iv > 90 % and transfer all others ?

**Comment by eloxxx** [comment]
Tthis setting will keep iv 90 mini, be carfull, could tranfert 2000 CP with 85 IV
![jjjjjjjjjjjjj](https://cloud.githubusercontent.com/assets/21296701/18367992/fcbeff5a-761d-11e6-91f1-caaea7c4b1ce.jpg)

**Comment by nobilus** [comment]
Thks i try it, at lvl 15 it's not dangerous ;)

**Comment by eloxxx** [comment]
Bot should not tranfer fav poke even if they have 80 IV

**Comment by nobilus** [comment]
Thks eloxxx, trying those things this night and make record tomorrow ! :)

**Comment by eloxxx** [comment]
ok nice ;)

**Comment by Lunat1q** [comment]
Transfer was fixed in Upd2.
