### ISSUE TITLE
Gyarados 100% IV low stats

### ISSUE THREAD

**Issue by danxp1** [Lunat1q/Catchem-PoGo#1581]
I Have a 2074 CP Gyarados with 100% IV, level 27.0, but it has only 78 atk and 79 def. Is it right  or a bug on the calculation ?

**Comment by alanearl** [comment]
I have also this one :)

![jolteon](https://cloud.githubusercontent.com/assets/648116/18367649/d63be0c4-764e-11e6-986f-2020e09d2432.png)

**Comment by alanearl** [comment]
I think the problem is your Gyrados is malnourished :D. Could you please check its weight?

**Comment by danxp1** [comment]
268Kg weight 7.23m height

**Comment by EllosGaming** [comment]
My Gyarados is 93% and has 72/72. I think it's normal...

**Comment by danxp1** [comment]
now updated he have 144atk / 146def.. it was bug xP
