### ISSUE TITLE
(EGG) the pokemon disappeared. 

### ISSUE THREAD

**Issue by YoshiJalea** [Lunat1q/Catchem-PoGo#1583]
Just happen XD, i was waiting for my 10km egg, and puff nothing there XD
the pokemon disappeared, I have only the infinite incubator: /

![missing pokemon](https://cloud.githubusercontent.com/assets/22063132/18369347/9d72c7d8-75fb-11e6-85a2-0e0f850929de.jpg)

**Comment by Xandirius** [comment]
I thought the same thing happened to me too, but after careful analysis of information I realized that I did get the pokemon, it just didn't show in the log.

**Comment by YoshiJalea** [comment]
yes! i got a scyther :(, anyone knows a bulbasaur nest in NYC ?

**Comment by Lunat1q** [comment]
Well, it happens sometimes, trying to fix this, but no luck so far :) sorry
