### ISSUE TITLE
CPU usage run to 100%

### ISSUE THREAD

**Issue by harley12** [Lunat1q/Catchem-PoGo#1584]
Hi Author:
In these days, when I unzip the releases file (Catchem_1.5.2.1_upd.zip & Catchem_1.5.2.1_upd2.zip)
This action always causes my Kaspersky( a anitvirus software) run to 100% usage of CPU.
I don't know why but it always happened.

**Comment by alanearl** [comment]
Im using Quad Core I7, no problems encountered :)

**Comment by Lunat1q** [comment]
Well, that may be caused by the encryption, but you have to deal with it.
