### ISSUE TITLE
force move does not work if no pokestops around

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#1588]
I'm walking through a forest to get to another city.. there are no pokestops. The bot ignores my forcemove (clicked at very startup of bot). This happens if I turn 'loot pokestops' on or off.

The bot should be able to just walk to a point you give it!

100s of: 

[21:49:42] No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by Lunat1q** [comment]
Actually, try to enable Discovery settings and do the ForceMove at early start of the bot, that should help.
