### ISSUE TITLE
Bot travelling yet not reflected on map

### ISSUE THREAD

**Issue by popsoda27** [Lunat1q/Catchem-PoGo#1589]
I don't know why suddenly this happened but the bot console shows that my player is traveling to pokestops every 4-5secs but on the map the player icon isn't moving at all.

http://i.imgur.com/PLTcv0u.png

**Comment by Lunat1q** [comment]
Looks like you have wrong settings or something. Try to recheck it / reset to default.
Also try to update .net to 4.6.2
