### ISSUE TITLE
Add the Gym auto battler

### ISSUE THREAD

**Issue by faisalwildanhabibi** [Lunat1q/Catchem-PoGo#1591]
Set an API that can fight gym automatic as the bot's strategy based on the best of the best strategy

**Comment by Sto7mz** [comment]
I wouldn,t think that would be safe though. 

There are lots of Ban going on with people taking over the gyms lately even they were legit accounts to.

But would still be cool addon.

**Comment by Lunat1q** [comment]
That will not happen, for a secret safety reason.

**Comment by alanearl** [comment]
Wow this is great but my first account was ban due to gym battles.
Advice never put your strongest pokes on GYM :)
Just put magicarps... Its more FUN!
