### ISSUE TITLE
Logfile with account stats

### ISSUE THREAD

**Issue by ex10dead** [Lunat1q/Catchem-PoGo#1592]
Hey there, 
is it possible to create a logfile (or integrate into the existing) with actually account stats?
Stardust, Level, Exp 

Thats will be great.

**Comment by Lunat1q** [comment]
there is dumpers for that, enable em in the config

**Comment by ex10dead** [comment]
There only a dumper for pokemon stats, but not for the acount stats.
If i'll be wrong, i'm sorry for that issue.
