### ISSUE TITLE
bot not following the route and go to the starting point midway

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1596]
I have selected the Mapzen Valhala Routing Service with Mapzen Elevation API option checked,
Both API Key have been entered.

I have watched the bot path twice.  The time to return to starting point are not the same on two trial.
The route data is as follows
    {
      "$type": "Catchem.Classes.BotRoute, Catchem",
      "InitialWp": [
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.705627938205893,
          "Longitude": -74.00390625,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 4.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.704261544615264,
          "Longitude": -74.005880355834961,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 2.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.704294078121777,
          "Longitude": -74.008326530456543,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 32.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.702862588801736,
          "Longitude": -74.0093994140625,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 3.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.702667383328887,
          "Longitude": -74.011287689208984,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 15.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.702081763477764,
          "Longitude": -74.01390552520752,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 21.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.703936208676105,
          "Longitude": -74.013261795043945,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 27.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.70513994371305,
          "Longitude": -74.011545181274414,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 44.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.712784779958255,
          "Longitude": -74.003863334655762,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 32.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.714281113277366,
          "Longitude": -74.006438255310059,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 42.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.714996739064084,
          "Longitude": -74.00789737701416,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 10.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.712264308312406,
          "Longitude": -74.009914398193359,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 50.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.711711302730869,
          "Longitude": -74.009270668029785,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 22.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.702244436175107,
          "Longitude": -74.01587963104248,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 21.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.704359145087118,
          "Longitude": -74.0174674987793,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 4.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.704521812222382,
          "Longitude": -74.018669128417969,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 2.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.706994303763281,
          "Longitude": -74.018540382385254,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 16.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.707644944175691,
          "Longitude": -74.017767906188965,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 29.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.712199249070622,
          "Longitude": -74.017682075500488,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 0.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.712329367490632,
          "Longitude": -74.016480445861816,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 14.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.716688187618836,
          "Longitude": -74.013562202453613,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 3.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.715679829230432,
          "Longitude": -74.009785652160645,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 23.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.720168533106374,
          "Longitude": -74.005622863769531,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 19.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.71707851579788,
          "Longitude": -74.006352424621582,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 15.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.713890768697063,
          "Longitude": -73.999614715576172,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 11.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.716005107798651,
          "Longitude": -73.999271392822266,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 18.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.7170134612603,
          "Longitude": -73.998627662658691,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 15.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.71681829726613,
          "Longitude": -73.997769355773926,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 20.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.715647301286189,
          "Longitude": -73.998541831970215,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 17.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.715029267326166,
          "Longitude": -73.997125625610352,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 20.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.712557074113811,
          "Longitude": -73.995709419250488,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 17.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.718379593199479,
          "Longitude": -73.992791175842285,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 20.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.72238024689,
          "Longitude": -73.991503715515137,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 15.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.720331161623051,
          "Longitude": -73.98442268371582,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 10.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.710540216926326,
          "Longitude": -73.98643970489502,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 6.0
        },
        {
          "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
          "Latitude": 40.708067857034926,
          "Longitude": -73.9998722076416,
          "HorizontalAccuracy": "NaN",
          "VerticalAccuracy": "NaN",
          "Speed": "NaN",
          "Course": "NaN",
          "IsUnknown": false,
          "Altitude": 18.0
        }
      ],
      "Route": {
        "$type": "PoGo.PokeMobBot.Logic.PoGoUtils.CustomRoute, PoGo.PokeMobBot.Logic",
        "RoutePoints": [
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.705627938205893,
            "Longitude": -74.00390625,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 4.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.704261544615264,
            "Longitude": -74.005880355834961,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 2.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.704294078121777,
            "Longitude": -74.008326530456543,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 32.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.702862588801736,
            "Longitude": -74.0093994140625,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 3.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.702667383328887,
            "Longitude": -74.011287689208984,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 15.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.702081763477764,
            "Longitude": -74.01390552520752,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 21.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.703936208676105,
            "Longitude": -74.013261795043945,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 27.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.70513994371305,
            "Longitude": -74.011545181274414,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 44.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.712784779958255,
            "Longitude": -74.003863334655762,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 32.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.714281113277366,
            "Longitude": -74.006438255310059,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 42.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.714996739064084,
            "Longitude": -74.00789737701416,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 10.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.712264308312406,
            "Longitude": -74.009914398193359,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 50.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.711711302730869,
            "Longitude": -74.009270668029785,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 22.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.702244436175107,
            "Longitude": -74.01587963104248,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 21.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.704359145087118,
            "Longitude": -74.0174674987793,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 4.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.704521812222382,
            "Longitude": -74.018669128417969,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 2.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.706994303763281,
            "Longitude": -74.018540382385254,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 16.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.707644944175691,
            "Longitude": -74.017767906188965,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 29.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.712199249070622,
            "Longitude": -74.017682075500488,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 0.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.712329367490632,
            "Longitude": -74.016480445861816,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 14.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.716688187618836,
            "Longitude": -74.013562202453613,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 3.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.715679829230432,
            "Longitude": -74.009785652160645,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 23.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.720168533106374,
            "Longitude": -74.005622863769531,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 19.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.71707851579788,
            "Longitude": -74.006352424621582,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 15.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.713890768697063,
            "Longitude": -73.999614715576172,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 11.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.716005107798651,
            "Longitude": -73.999271392822266,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 18.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.7170134612603,
            "Longitude": -73.998627662658691,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 15.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.71681829726613,
            "Longitude": -73.997769355773926,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 20.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.715647301286189,
            "Longitude": -73.998541831970215,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 17.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.715029267326166,
            "Longitude": -73.997125625610352,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 20.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.712557074113811,
            "Longitude": -73.995709419250488,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 17.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.718379593199479,
            "Longitude": -73.992791175842285,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 20.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.72238024689,
            "Longitude": -73.991503715515137,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 15.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.720331161623051,
            "Longitude": -73.98442268371582,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 10.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.710540216926326,
            "Longitude": -73.98643970489502,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 6.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.708067857034926,
            "Longitude": -73.9998722076416,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 18.0
          },
          {
            "$type": "GeoCoordinatePortable.GeoCoordinate, GeoCoordinatePortable",
            "Latitude": 40.705627938205893,
            "Longitude": -74.00390625,
            "HorizontalAccuracy": "NaN",
            "VerticalAccuracy": "NaN",
            "Speed": "NaN",
            "Course": "NaN",
            "IsUnknown": false,
            "Altitude": 4.0
          }
        ]
      },
      "Name": "NY160908B",
      "WpCount": 37
    }
  ],
  "ProviderEnum": 0

**Comment by alanearl** [comment]
Did you check manual route on creating the route using routecreator?

**Comment by Spk345** [comment]
I'm not very sure what you are saying is wrong here. Is the route varying drastically in time? Are you asking it to force move somewhere and it backtracks?

Visit us on discord for live help please.

**Comment by tyu366** [comment]
For example, if my route setup is 10km,  sometimes the bot go back tot the starting point after 3km and sometimes after 6km.
