### ISSUE TITLE
Altitute current makes the program unstable.

### ISSUE THREAD

**Issue by ccpiloveyou** [Lunat1q/Catchem-PoGo#1597]
Don't know why, sometimes the Altitude current suddenly rushes to the sky which far beyond the setting min/max then the program would show "No pokestop found in the area....".  Meanwhile, the program will stop and also stunned.

**Comment by alanearl** [comment]
Its a soft ban man.
Try to restart modem.

**Comment by ccpiloveyou** [comment]
NO. I did not teleport.  While I change my altitude back to my setting period then restarting, the program will return to normal.  My long/lat were both no changed a bit.  For example, the altitude suddenly jumps up to sky to 3000 but I only set my altitude 1 to 15.  The program will stun.  Modify the altitude back to between 1~15 then restarting, the program works again.  From the beginning to the end, my position did not change at all.

**Comment by ccpiloveyou** [comment]
I do not know why the altitude changed suddenly, unfortunately.

**Comment by petoe93** [comment]
altitude options are ignored if you are using mapzen elevation, which you really should do

**Comment by alanearl** [comment]
Did you put mapzen api key?

**Comment by KitazawaMoa** [comment]
I was about ask mapzen API key is used or not lol. But with mapzen API key enabled I haven't experienced that issues. Mine always shows more than my max and min altitude setting,but I haven't got any altitude higher than 50

**Comment by Spk345** [comment]
If you continue to experience any issues, please join us on discord and get live help. Thank you.
