### ISSUE TITLE
soft ban 

### ISSUE THREAD

**Issue by enzomehue** [Lunat1q/Catchem-PoGo#1599]
someone knows a program to remove the "softban"

**Comment by alanearl** [comment]
Restart modem.

**Comment by eloxxx** [comment]
Be carful, restarting modem does not work everytime because some modem have a static IP, so u might restatrt 10 times, you will have the same IP, in this case the solution is to wait until the softban is removed.

**Comment by alanearl** [comment]
Restart modem until new public ip will be renewed.

**Comment by petoe93** [comment]
the program you looking for is called "don't run multiple bots on one IP"

**Comment by enzomehue** [comment]
how  i can play with multiple accounts?

**Comment by petoe93** [comment]
just don't. why isn't one enough?

**Comment by Cryptologism** [comment]
Can play even 1000 acc but remember to have different ip tough... Use software like vpn or buy private proxies for per acc... There u can have billion account running at same time...
