### ISSUE TITLE
[17:01:01] (ERROR) Current Operation was canceled.

### ISSUE THREAD

**Issue by khai5535** [Lunat1q/Catchem-PoGo#160]
Hmm, how to solve this problem? Pop out every hour and bot stopped.

**Comment by Bay101** [comment]
Stop button was pressed, if not we need more details

**Comment by khai5535** [comment]
No, I didn't press any of the button. I start the bot and went sleep. Notice this " (ERROR) Current Operation was canceled. " in the another morning. It happened quite frequent this two days, as it happened just now again.

**Comment by Bay101** [comment]
It is because you have reached your maximum number of poke stops or Pokemon caught Resulting in bot stopping

**Comment by g00tch** [comment]
Isn't it supposed to "Pause" instead of shutting down?

**Comment by khai5535** [comment]
Er... My speed is only 4-7kmph, it is impossible to reach the maximum pokestop or pokemon caught, as the bot started at around 12am, and stopped at around 12.40am.

Guess there is a bug.

**Comment by khai5535** [comment]
It happened again. [18:20:15] (ERROR) Current Operation was canceled.
Avatar inside the map still moving, but without any log.
