### ISSUE TITLE
did not get level up rewards

### ISSUE THREAD

**Issue by lovecak555** [Lunat1q/Catchem-PoGo#1600]
hi, ive got a problem that from time to time the bot doesnt mention that i've leveled up in console and I also dont get rewards.

**Comment by alanearl** [comment]
Did you check logs?
Are you using v1.5.2.1?

**Comment by lovecak555** [comment]
thanks for your reply. i havent updated yet, so Im using 1.5.2.0. at the moment, but it was the same when 1.5.2.0. was actual. and I can see it by the number of limited use incubators and lure modules, I should have 3 on level 16 but I got only 2... is the bug fixed in 1.5.2.1.? I was a little bit afraid to update, this version worked good for me (just the rewards went wrong).

**Comment by alanearl** [comment]
Level up free items bug was already fixed in the v1.5.2.1

**Comment by alanearl** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/1507

**Comment by lovecak555** [comment]
thank you very much
