### ISSUE TITLE
[bug] crash after approx 10 - 20 minutes - needs confirmation

### ISSUE THREAD

**Issue by MarkoHess** [Lunat1q/Catchem-PoGo#1601]
I'm using the latest version of catchem. (updated this morning from 1.5.2.1 to 1.5.2.1_update2 after second crash)
Since this morning it starts to crash after 10-20 minutes. (windows has to close the application - i can only click on debug and close)
The only other thing i did this morning was to install python-2.7.12.msi (including set path to python directories), updated the pip and installed the PokeAlert on my pc. (https://github.com/kvangent/PokeAlarm)
After the second crash, i closed pokealert, but it hasn't solved the problem. Everything else is the same as of yesterday, when everything was working fine in 1.5.2.1.
Checked my .NET Framework and it's already up to date at 4.6.2.
Can i get a log of catchem, why it was closed?
Any ideas?

**Comment by lbs14** [comment]
This started happening to me today as well, and i didn't even download anything. Did everything possible, like downloading a fresh copy, restarting my comp, updating NET but the problem still exists.

**Comment by Kumohira** [comment]
This started happening also to me today, i didn't download anything. :(

**Comment by alanearl** [comment]
Check Internet Connection. (cmd > ping 8.8.8.8 see latency )
Try to disable Anti Virus for 30 mins.
Repair .NET

**Comment by pika0077** [comment]
Same problem !

**Comment by un4m** [comment]
same here ;/

**Comment by valdirljr** [comment]
Same here

**Comment by Spk345** [comment]
Seems to be a bug, we will look into this. Looks like anything over 6 profiles will cause a crash.

**Comment by un4m** [comment]
so currently it is usable only with up to 5 bots?

I'll verify and confirm. ty!

**Comment by un4m** [comment]
...i can confirm - running without crashes with 5 bots. crashes "reliable" with 7+. Not sure about 6, but would be great to have this fixed, as i used to run 10... :)  tyvm & cheers

**Comment by Daysmith** [comment]
running 1 bot but still crash :/

**Comment by paparino** [comment]
the crash i resolv it,i update flash, java and put i properties administater privileges to catchem.exe

**Comment by Spk345** [comment]
Use newest pre-release, has been confirmed to run more than 6 profiles. Verified up to 15 bots at once.

**Comment by MarkoHess** [comment]
Sorry, but it does not work for me. I deleted all profiles and created a new one with add new bot. I updated my flash, java and also started catchem as administrator. But it crashes after 3-12 minutes.

**Comment by MarkoHess** [comment]
I found the problem for me. It was the **Plays.tv**, that got updated and made catchem crash after 8-12 minutes.
After uninstalling everything works fine.
btw. maybe refer to the windows logs somewhere, that's where i found the problem maker. :)
