### ISSUE TITLE
pokemon not trasnferring

### ISSUE THREAD

**Issue by dreamwalker1232** [Lunat1q/Catchem-PoGo#1602]
all pokemons get transferred as it should but except one which is kangaskhan  , he isnt in donottranfer list and any list  yet the bot never transfers it,

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18384696/9ea97b10-76be-11e6-8fd7-f6663cb2ca05.PNG)

**Comment by dreamwalker1232** [comment]
i did the transfer duplicate option which should be obvious when i said all other pokes that should be transferred are transferring , i have problem only with kangaskhan and not any other pokemon

**Comment by alanearl** [comment]
Did you set Min Duplicate?
If yes, it will not transfer unless it is more than what is set in the duplicate value.

**Comment by dreamwalker1232** [comment]
yes its 2 , let me say it again the transfer feature works perfectly fine for me except when it has to transfer KANGASKHAN it does not transfer it i set all the transfer settings right ( min  cp , min duplicate, min IV , etc) but in the end i have to transfer them manually

**Comment by Spk345** [comment]
Make sure he isn't in the new Transfer Filter list, if he is, set his duplicate value down to 0 and you won't keep any at all. If you don't have the new transfer Filter list on your right hand side, you need to update to the newest release.

Don't forget there is a manual recycle button that will happen as soon as your bot is down with it's next action (such as catching pokemon or looting pokestops) it will run through your inventory and your pokemon, transferring them. If you are still having issues, visit us for live help at the discord!
