### ISSUE TITLE
May be a stupid suggestion, but... "sitting" option?

### ISSUE THREAD

**Issue by damanfra** [Lunat1q/Catchem-PoGo#1603]
First of all, congratulations, your program is amazing!

Could we have an "Sitting" option ?

Why? Sometimes we are in the middle of 3 maybe 4 or 5 pokestops that can be reached from the same position. So, a more human situation would be sitting there and keep looting these pokestops without have to walk.

I can do that right now, by limiting the "maximum travel distance". But after spinning all pokestops I keep seeing the message "No pokestops found in your area..." until they're ready to be turned again.

A message like "I´m sitting and I´m not going to walk, until you tell me to do so." would be more clear and fun  ;)

**Comment by faisalwildanhabibi** [comment]
I think that's not needed, because the bot will create the other route so, the bot can walk on that route, so not needing the sit, but i think that's good enough idea, but how if the pokestops you want to directly spin that's need moe time, so let ur bot create the route, and the bot will walk through all the pokestops in its way

**Comment by tyu366** [comment]
As my previous request, to make a bot operate like human, one should stop sometime to have lunch and dinner and take a rest based on the local time.  The bot should not keep walk while every one are sleeping.  

Every one knows that it is a bot if keep walking 24x7.

**Comment by LeMoo07** [comment]
That's where the schedule option fixes you issue

**Comment by Spk345** [comment]
Good news! There is a "SITTING" option! Drop your speed factor on the console all the wayyyy down to 0.0000001. There's still some variance, so you are not completely still (Just like in real life!)

For the second issue @tyu366 , make a schedule! It's super easy, if you need any help, visit us for live help at our Discord.
