### ISSUE TITLE
[Feature] Last Login

### ISSUE THREAD

**Issue by sapdkeybinder** [Lunat1q/Catchem-PoGo#1605]
it would be cool if you could see when you last logged in to the bot

**Comment by alanearl** [comment]
How about the logs?
What do you mean last login?
Coordinates?

**Comment by Spk345** [comment]
You can see the last time you logged in and when you quit in your Logs. Your last coords are in the bot at start up. 

If you'd like to be more in control of when you log on and out, I suggest using the scheduler feature. If you need help setting that up, visit us at Discord.
