### ISSUE TITLE
Lukky Egg

### ISSUE THREAD

**Issue by pixe00** [Lunat1q/Catchem-PoGo#1606]
Is not using the lukyegg even though with the selected option.

**Comment by ArchangelBr** [comment]
it's on roadmap

**Comment by Spk345** [comment]
Lucky eggs do in fact trigger, however you need to have that setting checked, and also the setting titled "Evolve all pokemon with enough candies". Make sure your Pokelist "To Evolve" is updated with what you'd like to evolve.
