### ISSUE TITLE
[feature request] Add a filter on the minimum level of Pokémon to catch.

### ISSUE THREAD

**Issue by Wombidou** [Lunat1q/Catchem-PoGo#1607]
Hi,

I didn't see this request in issues, is it possible to add an option to catch only the pokemons with a minimum level ?
For example you choose the level 15 and if you see a pokemon with level 10 the bot don't catch him (escape?).

thanks

**Comment by acidwae** [comment]
would be great

**Comment by acidwae** [comment]
or even if we could select which pokemon we wish to catch instead excluding which ones we dont

**Comment by tyu366** [comment]
I don't think so.   It is good to catch poke with low level and immediate transfer to earn XP in short time.
The XP gain will bring you quickly to higher level and let you find poke of higher level.

**Comment by HernestoSanchez** [comment]
@tyu366 Is right. And maybe it would be easy to flag those "players" that choose only pokemons with high IV levels...

**Comment by alanearl** [comment]
Yeah you will loose some experience... 100XP per Pokes + 10 Spin Throw + 10 Nice Throw.
Therefore catch them all then convert to candy :)

**Comment by Wombidou** [comment]
You convinced me !

**Comment by HernestoSanchez** [comment]
lol gota catchém all!
