### ISSUE TITLE
im getting softbanned after 2-3 minutes of botting

### ISSUE THREAD

**Issue by soularrow93** [Lunat1q/Catchem-PoGo#1608]
all the setting are the same as i always used to use but somewhy im getting softbanned after 2-3 minutes of botting and sometime it take less time than that ! please help me out on fixing this ( i dont teleport and i walk between 4 and 7 kmh and start back where i left last time to lat and long are alright )

**Comment by dreamwalker1232** [comment]
try changing ur ip address (turn off ur modem for 1 min or so and ur ip should be changed) and ur device info and id

**Comment by soularrow93** [comment]
@dreamwalker1232 thanks i will try that right now

**Comment by eloxxx** [comment]
Try to stay into your IP range location.

**Comment by soularrow93** [comment]
@eloxxx im at less then 1km of my real location

**Comment by Compufreek** [comment]
Are you using more than one bot, only use one at the time and you should be fine and check the speed setting and dont teleport. you cant play on phone either while you are using bot on the same IP.

**Comment by soularrow93** [comment]
it seems to work now i think it was because i had 2 bots open at the same time ( i wanted to test another bot on another account ) but since i just run 1 bot it seems to work fine so far. so for the others, dont use multiple bot it get you softbanned ( and i guess if you do it too much its permabanned but im totally not sure how niantic work with their ban system )

**Comment by soularrow93** [comment]
@compufreek yeah i think that thats was the problem

**Comment by alanearl** [comment]
Walk speed 2-4km
Throw accuracy 30%-80%
1 Public IP per BOT

**Comment by Spk345** [comment]
Too many bots per one ip will cause a temporary IP ban. We recommend not using more than one bot per ip address. If you'd like to run more than one, we recommend a proxy or vpn service that supports HTTPS and Socks. If you'd like a recommendation for which ones fellow Catchem players use, visit our Discord.
