### ISSUE TITLE
Now... Bot fight gyms?

### ISSUE THREAD

**Issue by maknado** [Lunat1q/Catchem-PoGo#1609]
Congratulations Bot it is too crazy!
There is possibility of the Bot fight gyms?

**Comment by soularrow93** [comment]
no and i dont think it will be added because many people got banned by winning gyms legitly so the chance of getting banned just for that is too big at my opinion to add it to the bot, or maybe adding it but with a notice that it can get you banned like the teleport option does

**Comment by ArchangelBr** [comment]
@Lunat1q said it won't happen!

**Comment by alanearl** [comment]
Yeah my 1st account got ban due to gym fights.
For now just hunting gyms & puts some magicarps.
Its FUN :)

**Comment by tyu366** [comment]
why gym fight cause ban?

**Comment by Spk345** [comment]
It will not happen. The reason why? Your nickname shows when holding the gym, you can easily submit a report on that username and get banned currently, LEGIT or not.
