### ISSUE TITLE
Bot running in in a circle

### ISSUE THREAD

**Issue by Chris20000** [Lunat1q/Catchem-PoGo#1610]
My bots are just running in a small range of approximately 100 meters, even if my settings are right. Can you help me?

**Comment by ArchangelBr** [comment]
can you print your settings and the bot running in circle?

**Comment by zhach01** [comment]
@Chris20000 use google direction api and augment the min distance that should solve it  .

**Comment by Chris20000** [comment]
Ok, thanks, that helped for the moment. What is a good value for max location offset?

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18389975/ed2cb754-76da-11e6-9f9d-b77bc5e996dd.PNG)

**Comment by Chris20000** [comment]
Thanks
