### ISSUE TITLE
Bot can't find pokestops or pokemons

### ISSUE THREAD

**Issue by johnybro1986** [Lunat1q/Catchem-PoGo#1611]
Today when I use the application , I found that wasn't showing Pokestops or Pokemons.

I noticed that in the mobile phone also happens the same on Wifi connection. 

The game starts normally, however if you have connected by Wifi will not appear Pokemons, Pokestops, Gyms ... 
When I turn the Data connection, it appears all the things.

I wonder if the problem is general for all users (network providers) or only in Portugal.

**Comment by zhach01** [comment]
ip ban try to reset your router .

**Comment by alanearl** [comment]
Restart modem until new public ip will be renewed.
