### ISSUE TITLE
[Question] Can catchem run on xp?

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1613]
as tittle i have a pc run xp and i cant run catchem, no error appear, anyone know why?
Thank

**Comment by alanearl** [comment]
Did you install .NET 4.6?

**Comment by devost02** [comment]
my xp say it could only install up to 4.0

**Comment by tyu366** [comment]
I cannot run in XP also but I have another notebook running win 10.

**Comment by Spk345** [comment]
You need at least Net Framework version 4.5.2 to run Catchem, that is the environment it is built for. You cannot run it on anything older.
