### ISSUE TITLE
"failed with item settings" how to solve ?

### ISSUE THREAD

**Issue by meganovato** [Lunat1q/Catchem-PoGo#1614]
"you have failed with item settings! you asked to keep it at 85,0% clean, which is 297,5 items, and asked to keep 330 items at the same time, while you have 11 extra items like Lucky Eggs/Incubators/etc..."

this message is appearing every 2 minutes, How to fix this?

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18390522/17256c7a-76dd-11e6-9172-5e2c66c91b35.PNG)

**Comment by petoe93** [comment]
actually the log tells you exactly..
reduce the amount of items to keep like @alanearl is showing or set recycle at usage from 0.85 to 0.95

**Comment by soularrow93** [comment]
@petoe93 like petoe93 said increase your limit to something like 0.95 for the recycling at usage percentage ( 0.95 )
