### ISSUE TITLE
How to use the Get Data From Android Phone function?? PLS HELP!

### ISSUE THREAD

**Issue by kingbeelzebob** [Lunat1q/Catchem-PoGo#1616]
as the title says.. can anyone here pls help me im a noob.. pls help me i dont know how to use this function..

**Comment by petoe93** [comment]
from the README:
Get Device data from real android device:

   1. [Enable USB debugging at your phone settings]
   2. [Ensure what your PC have proper ADB drivers installed]
   3. [Click "Get Data from Your Android Phone" button at the Settings tab - you are awesome]

    If you have any problems with getting device info, consider watching this post: [AdbDrivers](http://forum.xda-developers.com/showthread.php?p=48915118#post48915118)
even if you are a noob, you could read at least..ffs

**Comment by alanearl** [comment]
This thing is for technical people.
If you dont have any idea about your smartphone usb drivers, usb debugging & adb command.
Just watch youtube and try to read android forums.

**Comment by petoe93** [comment]
sorry to disagree with you alanearl, but it is not..it's 3 simple steps.
you click on the link, read through the instructions once, download the program & run it. the drivers are installed in like 5-15 seconds!! and even if people don't know how to complete the first step, how about f****** googling it first? 
i was also what you'd call a noob, but even i managed to use google..really these 3 steps take like 5 minutes maximum..that i wouldn't call 'for technical people'.. its a few clicks and scrolls but nowadays people just cry around waiting for their food to be chewed and spit in their greedy mouths.
i'm almost sure if he manages to get the bot going next issue from him will be like 'why ip softban when using 8735t3962 bots the same time'
