### ISSUE TITLE
automatic recycling when bag is full

### ISSUE THREAD

**Issue by manieczek** [Lunat1q/Catchem-PoGo#1618]
![screenshot 2016-09-09 17-02-40](https://cloud.githubusercontent.com/assets/22049157/18391771/67d0887c-76af-11e6-9d53-1d4476a3ed7e.jpg)

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18392131/27bf0626-76e3-11e6-867b-5abdadd27a2e.PNG)

**Comment by lapino2016** [comment]
The sum amount is not 350. It is 250.
It should not do an automatic recycle.
Try change amount to be equal 350.
