### ISSUE TITLE
How can i do 1000 cp AND 90 iv?

### ISSUE THREAD

**Issue by BSwazZ** [Lunat1q/Catchem-PoGo#1619]
Title.

**Comment by petoe93** [comment]
i guess it's 3 settings:
keep min cp: 1000
keep min iv: 90
tick the box of 'prioritize ic over cp'
and maybe you check out keep min duplicate, it should be at least 1

**Comment by BSwazZ** [comment]
thank you i gonna try this.

**Comment by BSwazZ** [comment]
no man dont work :/

**Comment by rokashou** [comment]
did you see that your monster more then 1000cp and 90iv been transferred?

**Comment by BSwazZ** [comment]
Problem is... i set Arcanine 1500 cp 90 IV but i have 1027 cp 91 IV do not transfer. I want 1500 cp AND 90 iv.

**Comment by lapino2016** [comment]
check if "Prioritize Both IV and CP for transfer" is set

**Comment by BSwazZ** [comment]
just i am gonna tick Prioritize Both IV and CP for transfer not prioritize iv over cp right ?

**Comment by Spk345** [comment]
You must check Prioritize Both IV and CP for Transfer. That will keep whatever pokemons that exceeds your Minimum Settings for both.
