### ISSUE TITLE
Proxy down

### ISSUE THREAD

**Issue by enryIT** [Lunat1q/Catchem-PoGo#162]
Hello, 

the bot keep saying `(INFO) Proxy Down?` but the proxy works fine in HTTP mode and in previous version it just worked like a charm. If i click the manual test proxy it works no problem, this happens only with the new automatic proxy check feature.

**Comment by enryIT** [comment]
And now without changing anything it just works. 

Well just close this issue.

**Comment by Lunat1q** [comment]
this issue fixed
