### ISSUE TITLE
im catching about 1 pokemon per hour

### ISSUE THREAD

**Issue by soularrow93** [Lunat1q/Catchem-PoGo#1620]
is this normal ? and i even think that the only pokemons i get are from eggs, do i walk to fast or am i missing something ? when i play normally i get 1 pokemon at less each 5-10 minutes so with the bot it should be the same or more, no ? my walking speed is set to 4-8kmh and i dont teleport so i dont see where may be the problem, is 4-8 too fast to catch pokemon ?

**Comment by lapino2016** [comment]
please, send your setup for checking timing and other setups

**Comment by tyu366** [comment]
you should determine a path with plenty pokemon first.  Then setup the route.

**Comment by ShadyBS** [comment]
Its probably related to your botting location.

**Comment by soularrow93** [comment]
i reduced even more my walking speed and reduced delay between player actions and delay between poke catch and delay to catch nerby poke ( BUT offcouse i did not reduced them too much i dont want to get banned ^_^ ) and now im getting a pokemon every 5-10 minutes like im supposed too. 
thanks you @lapino2016 before posting my setting i rechecked them and saw that some delay to catch nerby pokemon was at up to 12 seconds ! so thats normal i was walking away before the delay was done to catch the pokemon so i was not getting any, so thank you to made me re-verify them ! and @tyu366 there are almost no good poke spawner near where i live ( i live up north in canada where there is almost nothing = almost no pokestop = almost no pokemons so determinate a path with plenty of pokemon is barely impossible since i always stay near my original location, i doesnt teleport at all but still thank you for the suggestion )

**Comment by alanearl** [comment]
Yup its your location... change your location to nearest malls and you can see many pokes there...

**Comment by soularrow93** [comment]
I was already close the problem was some delays was too high so my character was walking too fast to catch them since the delay was way to high but its all fixed now thanks
