### ISSUE TITLE
Catchem  1.5.2. crashes at start 

### ISSUE THREAD

**Issue by run-na** [Lunat1q/Catchem-PoGo#1621]
As i said, the soft just crashed as soon as i click on it.

He're the logs, maybe you can help me...

  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	Catchem.exe
  Version de l’application:	1.5.1.0
  Horodatage de l’application:	57ce7b2a
  Nom du module par défaut:	KERNELBASE.dll
  Version du module par défaut:	6.1.7601.17514
  Horodateur du module par défaut:	4ce7bafa
  Code de l’exception:	e0434352
  Décalage de l’exception:	0000b727
  Version du système:	6.1.7601.2.1.0.256.49
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	0a9e
  Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
  Information supplémentaire n° 3:	0a9e
  Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789

Thanks for your contribution, xoxo

**Comment by Lunat1q** [comment]
<b>Version de l’application: 1.5.1.0</b> it's not 1.5.2

**Comment by run-na** [comment]
well, same, i treied every single version.
