### ISSUE TITLE
puting egg after hatching is too fast

### ISSUE THREAD

**Issue by zeruel01** [Lunat1q/Catchem-PoGo#1624]
well i see that  after 1  seccond of hactching it adds anoter egg 

is this intended? shouldnt it wait at least 3 or 5? 

![image](https://cloud.githubusercontent.com/assets/3741561/18395139/d3c86b3a-7682-11e6-8da0-19ac8c67cbd6.png)

**Comment by Lunat1q** [comment]
it hatched not at 32s, it's the time when it was detected.
