### ISSUE TITLE
Plain text password stored in login information creating security issue.

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1625]
Encryption is expected.

**Comment by Lunat1q** [comment]
it can't be encrypted, cause it's being sent to server in raw format.

**Comment by tyu366** [comment]
I mean you store the password in encrypted format (e.g. blowfish, AES-256) in text file and decrypt it in memory for login purpose.  Storing plain text password is a security hazard.  It is prohibited as a general rule of programming. When some bad program finds it, it can do a lot of bad thing.
