### ISSUE TITLE
Catchem  1.5.2. crashes at start 

### ISSUE THREAD

**Issue by run-na** [Lunat1q/Catchem-PoGo#1626]
Again,

Crashed at start. 1.5.2.
windows 7 pro N

Nom d’événement de problème:	APPCRASH
  Nom de l’application:	Catchem.exe
  Version de l’application:	1.5.2.1
  Horodatage de l’application:	57d1cb9e
  Nom du module par défaut:	KERNELBASE.dll
  Version du module par défaut:	6.1.7601.17514
  Horodateur du module par défaut:	4ce7bafa
  Code de l’exception:	e0434352
  Décalage de l’exception:	0000b727
  Version du système:	6.1.7601.2.1.0.256.49
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	0a9e
  Information supplémentaire n° 2:	0a9e372d3b4ad19135b953a78882e789
  Information supplémentaire n° 3:	0a9e
  Information supplémentaire n° 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Spk345** [comment]
Is this the newest release, 1.5.2.1. Update 2?

**Comment by run-na** [comment]
Yup it is

**Comment by Lunat1q** [comment]
.net version installed?

**Comment by run-na** [comment]
![crashd](https://cloud.githubusercontent.com/assets/22103075/18397236/8f2191a6-76c7-11e6-9fe6-c3d05687f387.png)

**Comment by Spk345** [comment]
... Catchem requires .Net Framework version 4.5.2. That's the environment it was built for. You will have to use it or newer.
