### ISSUE TITLE
Hard Ban ?

### ISSUE THREAD

**Issue by nobilus** [Lunat1q/Catchem-PoGo#1629]
have you seen this ?

![capture5](https://cloud.githubusercontent.com/assets/22085305/18396499/403815a4-76c4-11e6-8387-f6ff9dbd5075.JPG)

**Comment by Spk345** [comment]
It's one of two things: Unstable internet connection, or login timeout. If you want to double check your bot, log in on the official Pokemongo App.

**Comment by soularrow93** [comment]
you can also check out if you are permanently banned from this app
[POKEBAN](https://github.com/Ra5tko/Pokemon-Go-Ban-Check)

if you are just softbanned it say that you are not banned it just detect permaban

**Comment by nobilus** [comment]
Thks, it said not banned... Try to reset. Thk U

**Comment by soularrow93** [comment]
No problem mate
