### ISSUE TITLE
Altitude goes to ludicrous numbers

### ISSUE THREAD

**Issue by LeMoo07** [Lunat1q/Catchem-PoGo#1630]
I have set the altitude range to a 10 min and a 15 at max, but sometimes the bot goes up to 24435 and sometimes down to -4333 in a span of 5 minutes.

**Comment by xGuardianx** [comment]
here the same...

**Comment by ArchangelBr** [comment]
Use Mapzen

**Comment by Cowering** [comment]
Bot must be watching SpaceBalls!

**Comment by Lunat1q** [comment]
fixed in the upcomming
