### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by simmy360** [Lunat1q/Catchem-PoGo#1631]
Sometimes it doesn't auto transfer, maybe a manual batch transfer would be a good option to solve the issue?

**Comment by Lunat1q** [comment]
yeah... like batch thansfer what exists for 3 weeks already? that one?
Also, you probably missed transfer filter os failed with settings

**Comment by simmy360** [comment]
I'll have a look into the settings now then haha, maybe I'm just doing
something wrong idk. A manual option to transfer multiple pokemon would be
pretty cool, just a suggestion lol

**Comment by simmy360** [comment]
Think its sorted, I'm a dope xD.
