### ISSUE TITLE
[feature request] confirm manual transfer

### ISSUE THREAD

**Issue by ViXnium** [Lunat1q/Catchem-PoGo#1632]
Hello
I'd like a yes/no confirmation to manual transfer because favorite and transfer are SO close together.

![untitled](https://cloud.githubusercontent.com/assets/21290386/18398175/31427a84-76d4-11e6-8d9e-7e0267f287ea.jpg)

br. Guess what just happened

**Comment by ArchangelBr** [comment]
It's was near Evolve...
I think it's way more better stay there, in last position...

**Comment by zeruel01** [comment]
maybe it should ask on favorites only ?

**Comment by Lunat1q** [comment]
it ignore favorite pokes...
