### ISSUE TITLE
[Help Wanted] Does not respect Max Km after force move

### ISSUE THREAD

**Issue by ArchangelBr** [Lunat1q/Catchem-PoGo#1633]
After I force the bot to go to a big distance (2KM, for example), when the force move is over, a new "route" is created by mapzen, but it includes pokestops in my inicial place, 2km distance and my max distance in settings is 1000m

Happened 2 times today, so I think it could be a bug...

**Comment by KitazawaMoa** [comment]
I think its fine,the bot saved last seen pokestops in cache so it will be still seen for a while

**Comment by Spk345** [comment]
The issue is, is that it's pathing very far away outside of the max KM setting.

**Comment by ArchangelBr** [comment]
It's outside, @Spk345 ... it's about 2km and the max km is 1km.... I'll try to prove it .

**Comment by ArchangelBr** [comment]
I think I could take some prints to help you to debug...

Here was the force move

http://prntscr.com/ch3g15

As you can see, I'm going To 1.950 meters away

When it arrives there, discover new pokestops near but you can see that the red line is point to my inicial point too, 1,950 meters as we saw at the print before

http://prntscr.com/ch3nho

Here is the settings

http://prntscr.com/ch3npk

I hope you can understand.

**Comment by Lunat1q** [comment]
fixed
