### ISSUE TITLE
[Suggestion] Save config of Map & Console

### ISSUE THREAD

**Issue by petoe93** [Lunat1q/Catchem-PoGo#1634]
it would be nice if you could implement the config of "follow the player" & "keep Poké markers" when saving the settings. Somehow i always have to tick them again after restarting the .exe

Thx :)

**Comment by imzer0kool** [comment]
is there a way to automatically save the configuration settings so when theres an update i dont have to keep resetting all the settings i had in the previous version. its just a hassle to keep reticking the settings and saved map routes

**Comment by petoe93** [comment]
you can import your profiles into newer versions, just copy & paste the folder "profiles"
for the routes, there is actually no way to save them i think..unfortunately

**Comment by Lunat1q** [comment]
yeah... no... way...
Copy catchem.json file in the bot root, it contains all routes.
