### ISSUE TITLE
[Help Wanted] Routing service issue in version 1.5.2.1_upd2 !?

### ISSUE THREAD

**Issue by TiksTriks** [Lunat1q/Catchem-PoGo#1637]
Hi,
I have selected the Mapzen Valhala Routing Service with Mapzen Elevation API option checked,
Both API Key have been entered. 

Red path does not apear in Catchem_1.5.2.1_upd2.
The character travels direct lines (ignoring bridges and river).
(also tried google directions and results are the same)

At the same map location, I tried version Catchem_1.5.0.0 and works perfectly

Thank you.
Keep the good work!

**Comment by redbone75** [comment]
Goggle appears to work... Mapzen DOES NOT.

**Comment by alanearl** [comment]
Um using google directions too.

**Comment by Bay101** [comment]
Mapzen Altitude and Routing is working fine, Please check your API keys and Settings :)

**Comment by TiksTriks** [comment]
API keys checked and are the same as used in version Catchem_1.5.0.0.
In older version works perfectly.

thanks.

**Comment by redbone75** [comment]
same here... checked and validated.

Altitude is pretty important to me.  There needs to be a validation check on API's before anything.  Aborting if it's not working.
