### ISSUE TITLE
CRASH ERROR

### ISSUE THREAD

**Issue by platerick** [Lunat1q/Catchem-PoGo#1639]
Any times this error occuring 

![image](https://cloud.githubusercontent.com/assets/21088931/18404308/2ccedbc8-76c0-11e6-9adb-595027a36f6e.png)

**Comment by alanearl** [comment]
Hey man you are showing your player username. Don't post pictures like that possibility of ban.
Did you update your .NET to latest or even repair it?
Maybe your Internet connection is lag?
Try to turn off anti virus for a test too.

**Comment by Spk345** [comment]
Please join us in discord if you are still experiencing this issue, and get live help. Thank you.
