### ISSUE TITLE
HELP! get data from android

### ISSUE THREAD

**Issue by kingbeelzebob** [Lunat1q/Catchem-PoGo#1640]
can anyone help me with how to get data from android function please?

**Comment by EllosGaming** [comment]
Got from the Wiki:

> Q : How can I get the device info from Android?
A : Firstly this only works on android devices. Ensure that USB Debugging is enabled on the device you would like to get the info from and that the device is connected to your computer. After the device is connected and the computer recognizes that the device is there. In the settings for the profile you want the device info on. Click “Get data from Android” It may take up to a minute for the info to be generated and it will appear in the corresponding boxes above.

**Comment by alanearl** [comment]
1. Install the USB Driver of your Android Smartphone to your Computer.
2. Install ADB Drivers (http://forum.xda-developers.com/showthread.php?p=48915118#post48915118)
3. Reboot your Computer & Plug your Android Smartphone to your Computer.
4. Open cmd on your Computer then type the command: "adb devices -l"
5. If you can view your plug devices (Android) installation is successful.
6. Open Catchem then click get android information button.
7. Enjoy.
