### ISSUE TITLE
Question: Does Weight & Height Matters in Pokemon?

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1641]
Hi Guys,

Anyone have a data on Weight & Height Matters in Pokemon?

Thanks.

**Comment by MrCleverCoyote** [comment]
This is a forum to ask questions about this program, NOT a forum to ask about random bullshit you can find anywhere on the internet.

**Comment by alanearl** [comment]
If you don't have anything good to say! just SHUT UP!!! @MrCleverCoyote feeler!!!

**Comment by Spk345** [comment]
Go to discord to ask these questions, alright? This isn't an issue with the program.
