### ISSUE TITLE
[Bug] Ignoring schedule upon Start

### ISSUE THREAD

**Issue by caockerman** [Lunat1q/Catchem-PoGo#1642]
I installed the latest software version, copied my Profile folder from the prior version, and ran the application. I have two bots both with the opposite 12 hour schedule. They are two different Pokemon Go users. I used the Start All button assuming as in prior versions the schedule would Stop the on bot and start the countdown till its start time but it did not. Once I manually stopped the bot whose schedule was set to "off" the timer came up.

**Comment by Spk345** [comment]
Just to make sure, you did check your schedule after you started it in the new release correct?

**Comment by caockerman** [comment]
I did check the schedule for both bots and since they were correct hit cancel on the way out. I did some more playing last night and discovered if I hit Save on the already created schedule it would go into effect.
