### ISSUE TITLE
Transferring Pokes despite settings

### ISSUE THREAD

**Issue by caockerman** [Lunat1q/Catchem-PoGo#1643]
After upgrading to the latest version and starting my bot, it began a maintenance routine to transfer pokemon. For several versions I have had my transfer settings keep two duplicates. During this maintenance routine though it began transferring the second pokemon of several of my pairs and it also appeared to be transferring the higher CP/IV combos rather than the lower CP/IV combos. I was able to stop the bot before it completely transferred all my second duplicates but it did get rid of some.

**Comment by alanearl** [comment]
![capture](https://cloud.githubusercontent.com/assets/648116/18406625/f808db06-7731-11e6-8380-826b81f158d0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/648116/18406626/f8555896-7731-11e6-9117-cfb7ba39d0d6.PNG)

**Comment by caockerman** [comment]
Yes, those are the settings I am using, particularly the Keep Min Duplicate is set to 2 and it still transferred one of the Poekmon where I only had two to begin with.
