### ISSUE TITLE
How high lvl have you reached?

### ISSUE THREAD

**Issue by h3wiin** [Lunat1q/Catchem-PoGo#1644]

**Comment by MrCleverCoyote** [comment]
This is a forum to ask questions about this program, NOT a forum to ask about random bullshit you can find anywhere on the internet.

**Comment by izon13** [comment]
I think he means using bot..

**Comment by alanearl** [comment]
I kinda wonder why these kind of people exist being mean will not get us in the right way.
Going to level 34. Just avoid putting your strongest poke in the gym. Also 10 pokecoin a day will makes you feel safe.

**Comment by nobilus** [comment]
I think the question is with the bot too.
For myself : 23.

**Comment by g00tch** [comment]
There's a discord channel for this type of non-issue question.

The github is for feature requests/posting bugs/reporting issues. Not for regular chat.
