### ISSUE TITLE
The window doesn't fit the screen2

### ISSUE THREAD

**Issue by appocalipse1** [Lunat1q/Catchem-PoGo#1645]
I meant the "Close" button don't appear in fullscreen mode.  Further more the window can't be resized vertically.
http://imgur.com/UfEQvgG
http://imgur.com/kN5IGnX
Using Windows 10 64-bit.

**Comment by g00tch** [comment]
I'm running on Windows 10 64bit, and don't have a problem.

Check your resolution settings, or check your monitor calibration.
