### ISSUE TITLE
[Feature Request] UI improvment proposal

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1646]
Based on 1.5.2.1

**Settings tab**
1. scrolling should be minimized and keep data fields in one page.
those device information such as API keys, authentication, proxy can be put into a separate tab or a popup dialog as it is less frequent to change and not directly game related.
2. Certain wording in the prompt should be changed to power up instead of upgrade or level up to align with game wording.

**Information tab**
1. Many scrolling when going through the Pokemon list.  2 more columns can be added if space reserved for inventory can be reduced.
2. The current sorting order of inventory is not known.  They should be grouped by nature.
- XXX portion, revive
- XXX Ball, Berry
- Incubator, Eggs
- Incense, Lure Module

**Map & console**
1. write mark favourite message to log including the wording auto/manual
2. add wording to distinguish auto transfer and manual transfer in log

**Route Creator**
Route creator can be visualized as a supporting module.  It should allow editing of existing route or creation of new route while the bot is running.  When the current route is saved, those 'next waypoint' should be able to take immediate effect.

**Comment by Cowering** [comment]
I already asked about 'compressing' the inventory display. Didn't get a good response :(

**Comment by Lunat1q** [comment]
Current inventory is grouped my itemid enum. There is no other way or property to be grouped for now. So count that as alphabetic order.
Route creator - the thing you ask can't be done.
