### ISSUE TITLE
[Feature Request] Add pause/resume other than just start/stop and queue user action

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1647]
The action in progress. .. wait a bit. cause a lot of waiting time.   (v.1.5.2.1)
It seems not reasonable to make 30 requests for transfer/favorite pokemon but take a hour.
To resolve this issue
1. User action should be queued for processing instead of stopping them.
2. If user can pause all bot actions, user can concentrate to maintain the inventory.

**Comment by tyu366** [comment]
more pause / resume option here.
![poke pause](https://cloud.githubusercontent.com/assets/21959374/18430308/821e5aa8-790a-11e6-863c-0d11c9fa55c9.jpg)

**Comment by Lunat1q** [comment]
there is checkboxes for that.

**Comment by tyu366** [comment]
What I mean is in the middle of the run.  Those checkboxes in the setting tab is the setting when the bot start to run.  This is the general and global setting.  
I just want to have a temporary override for short duration.
