### ISSUE TITLE
 Rename using template

### ISSUE THREAD

**Issue by sidneyft** [Lunat1q/Catchem-PoGo#1649]
Tab information by clicking the pokemon displays two options to rename : 
Rename Selected Pokemon and Pokemon Rename Selected to Default.
My suggestion would be to have the option : Rename Pokemon Selected using template . 
I would use the rename template placed in settings.

Thank you

**Comment by Spk345** [comment]
[![githubissue1.png](https://s18.postimg.org/xrcf1laeh/githubissue1.png)](https://postimg.org/image/bfem87bad/)

There's already a template option for renaming based on IV's. 
{IV}_{Pokemon Name}

**Comment by sidneyft** [comment]
But after clicking "Rename Selected Pokemon to Default" this option does not work. 
So it would be interesting to force rename a specific pokemon using the template.

**Comment by sidneyft** [comment]
I went back to version 1.4.9.4 and worked in version 1.5.2.1 does not work. 
What has been renamed it does not rename again.
