### ISSUE TITLE
No items from pokestops

### ISSUE THREAD

**Issue by Chris13564** [Lunat1q/Catchem-PoGo#1654]
I've had this problem for a couple hours now and can't fix it.
The bot says it has spun the pokestop: 
[17:42:40] (POKESTOP) Name: S. M. U. R. R. F. Tree Tribute Mural XP: 50, Gems: 0, Items: 
Then at the end as you can see its says "items:" and there isn't any items.
PLZ HELP as with no pokeballs i can't catch it.

**Comment by Spk345** [comment]
You are most likely IP banned, which is temporary, probably due to running more than one bot per IP address giving you a softban. You can reset your router and see if this fixes your issue.

Also check your settings and make sure "Loot Pokestops" is a check.
