### ISSUE TITLE
[Help Wanted] Bot Stops "Walking" When Using Mobbot Routing API

### ISSUE THREAD

**Issue by g00tch** [Lunat1q/Catchem-PoGo#1656]
Seems like at least a couple times a day the bot stops walking to pokestops. Even force-moving doesn't do anything. It doesn't crash, and everything else is operational, as I can still tinker with my inventory and caught pokemon. Stopping and starting the bot doesn't resolve it. I have to completely close it and reopen it, and keep my fingers crossed while I'm at work that it's working properly.

Since it's not walking, it only catches pokemon that appear where my character is stuck. It's been happening to me since around the 1.2ish releases.

The only settings I'm using in Navigation is Mobot, and Use Discovery Pathing, with a walkspeed min/max both set at 6km/h. Nothing else.

![untitled](https://cloud.githubusercontent.com/assets/2353921/18409362/4a05ace6-7713-11e6-86af-baac3bd1d2b8.png)
![untitled2](https://cloud.githubusercontent.com/assets/2353921/18409364/4d774326-7713-11e6-9377-7a0460f89ed2.png)

**Comment by Spk345** [comment]
Can you try other Routing API services? This may be a MobBot Routing service issue.

**Comment by g00tch** [comment]
Changed it to GoogleDirections. 

I'll let it run overnight while I'm sleeping and report back.

**Comment by Spk345** [comment]
It really sounds like it's an issue with MobBot API. Please let us know, thank you!

**Comment by Bay101** [comment]
Please make sure that you have an API Key :)

**Comment by g00tch** [comment]
Woke up to it not walking again. 

![untitled](https://cloud.githubusercontent.com/assets/2353921/18413102/fd6e95dc-776c-11e6-9f06-c8c6af091914.png)

Also, when trying to make credentials for the Google Maps Directions API, it doesn't recognize that I selected GMD API. 

![untitled2](https://cloud.githubusercontent.com/assets/2353921/18413126/660503ce-776d-11e6-8d82-c8d5a72e2fe2.png)

**Comment by g00tch** [comment]
![untitled3](https://cloud.githubusercontent.com/assets/2353921/18413145/b04e6024-776d-11e6-8f0f-3d345d129f0f.png)

![untitled4](https://cloud.githubusercontent.com/assets/2353921/18413148/b998db8c-776d-11e6-9f8c-09917b1543e1.png)

**Comment by g00tch** [comment]
Any help with the API Key?

**Comment by Spk345** [comment]
Did you follow the exact steps on the wiki page? Because you should be able to jump straight from creating the API key, into the credentials and Select Webserver (ie. Tomcat option). If you continue to need help, join me on discord.

**Comment by g00tch** [comment]
I did. There's just no options available for "Which API are you using" other than "Other API", even though I came to that right after selecting the Google Map Directions API.

**Comment by Spk345** [comment]
https://github.com/Lunat1q/Catchem-PoGo/wiki/Google-Directions-API

Honestly if you are coming up with some sort of error that that wiki cannot help you with, then join me on discord.
