### ISSUE TITLE
player little far away from cental park and catch very small pokemons

### ISSUE THREAD

**Issue by manieczek** [Lunat1q/Catchem-PoGo#1659]
I choose Central PArk and the next player is little far away from Central Park and meet a little pokemons:
![screenshot 2016-09-10 11-30-12](https://cloud.githubusercontent.com/assets/22049157/18409555/18200b7c-774a-11e6-8893-12ba4fcba9e4.jpg)

**Comment by Wastl1** [comment]
Double klick inside Central Park to let himm force move inside.
Ist normal that he goes out aswell  because the bot is following the stops if you didnt set a custom route.
No Need to set a custom one just double click where you want him to move and h goes there while farming anything on it's way

**Comment by pcswatertown** [comment]
go up tpward GW bridge GW park excellent spot

**Comment by Spk345** [comment]
Join us on Discord if you continue to have anymore issues, thank you.

**Comment by tyu366** [comment]
I've got around 4500-6000Xp per hr near there

**Comment by Spk345** [comment]
Talking about the best stops are not issues, join us to discuss at discord for best farming places. On Github we are looking for bugs.
