### ISSUE TITLE
Cant logging

### ISSUE THREAD

**Issue by Nurob** [Lunat1q/Catchem-PoGo#1660]
It says "(error) Check your google account/password/2 factor auth internet connection" since the last few hours. It worked fine before that issue.

**Comment by eloxxx** [comment]
Connect on your phone, then connect with the bot

**Comment by EllosGaming** [comment]
Do you have a second factor auth? Like receiving a code on your phone or something like that?

**Comment by alanearl** [comment]
Enable and disable your second authentication on google.

**Comment by Spk345** [comment]
If you continue to have issues like this, come to discord for live help. Thank you.
