### ISSUE TITLE
'You have failed with item settings!'

### ISSUE THREAD

**Issue by HanSolo11177** [Lunat1q/Catchem-PoGo#1661]
Can somebody tell me how to configure my settings so that this message goes away? Would be greatly appreciated
![capture](https://cloud.githubusercontent.com/assets/21951817/18411116/fd541580-7768-11e6-81bf-d58abd2c9b91.PNG)
![capture2](https://cloud.githubusercontent.com/assets/21951817/18411117/00135826-7769-11e6-98eb-c3e52bd8473c.PNG)

**Comment by tyu366** [comment]
Below is my setting for your reference.

  "CatchSettings": {
    "CatchWildPokemon": true,
    "HumanizeThrows": true,
    "ThrowAccuracyMin": 0.2,
    "ThrowAccuracyMax": 1.0,
    "ThrowSpinFrequency": 0.6,
    "MaxPokeballsPerPokemon": 10,
    "UseGreatBallAboveIv": 80,
    "UseUltraBallAboveIv": 90,
    "UseGreatBallBelowCatchProbability": 0.32,
    "UseUltraBallBelowCatchProbability": 0.2,
    "UseMasterBallBelowCatchProbability": 0.05,
    "UsePokemonToNotCatchFilter": false,
    "PauseBotOnMaxHourlyRates": true,
    "MaxCatchPerHour": 85,
    "MaxPokestopsPerHour": 99,
    "MaxXPPerHour": 16000,
    "MaxStarDustPerHour": 25000,
    "MissChance": 0.18,
    "LootPokestops": true,
    "UseBerryMinCp": 1000,
    "UseBerryMinIv": 95.0,
    "UseBerryBelowCatchProbability": 0.25
  },
  "RecycleSettings": {
    "AutomaticInventoryManagement": false,
    "AutomaticMaxAllPokeballs": 100,
    "AutomaticMaxAllPotions": 60,
    "AutomaticMaxAllRevives": 80,
    "AutomaticMaxAllBerries": 50,
    "TotalAmountOfPokeballsToKeep": 140,
    "TotalAmountOfPotionsToKeep": 20,
    "TotalAmountOfRevivesToKeep": 20,
    "TotalAmountOfMaxRevivesToKeep": 40,
    "TotalAmountOfRazzToKeep": 50,
    "RecycleInventoryAtUsagePercentage": 0.85
  },

**Comment by HanSolo11177** [comment]
Thank you very much that seems to have worked!

**Comment by Spk345** [comment]
You left no leeway for your incubators and other items which also use your inventory space. 265 +50 is 90% inventory... That's not including your eggs and lures, etc. You failed with inventory settings, allow more leeway, and drop your pokeball inventory.
