### ISSUE TITLE
[Bug] bot tells pokemon inventory is full when 241 reached

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1662]
Someone tells that it is due to the nine egg in the inventory.   250-9 = 241.
In fact, the gameplay tells us that it is wrong.  If you keep walking to hatch the egg, you can have 259 pokemon.

![poke_inventory](https://cloud.githubusercontent.com/assets/21959374/18411132/0c2ed64a-77a4-11e6-947d-6c5ab4a62960.jpg)

The same applies to the item inventory.  If you have 349 items and visit a poke-stop which provides you ten items. you will end up with 359 items.  If you already have 350 items, you will get nothing from the poke-stop.  This is the rule of the game.

**Comment by Lunat1q** [comment]
sorry, it's server side data, eggs ARE part of poke lists, so 241 is the right number
