### ISSUE TITLE
Bot transfers seconds pokemon

### ISSUE THREAD

**Issue by itterror** [Lunat1q/Catchem-PoGo#1663]
Even when the bot is set the keep min 2, it still transfers all of a poke type but one. (On some ocasions only, not all the time)
![2016_09_10_17_06_48_catchem_v1 5 3 0](https://cloud.githubusercontent.com/assets/20759876/18411522/39eabf5c-7779-11e6-9260-c728ae2bb8d7.png)

**Comment by Lunat1q** [comment]
check 1.5.3.0, it have new transfer logic.
