### ISSUE TITLE
[Feature Request] New Options to filter by levels pokemon

### ISSUE THREAD

**Issue by JCCIRO** [Lunat1q/Catchem-PoGo#1664]
Hello @Lunat1q  please you add these new features:
1. On the Information tab, ADD Sort by LEVEL Poke. (List of Poke ORDER BY LEVEL)
2. On the Settings tab, pokes section, ADD option KEEP LEVEL MIN.
3. On the Settings tab, pokes section, ADD TRANSFER check box for LEVEL MIN

Thank you very much for your help, and congratulations on the great work

**Comment by Lunat1q** [comment]
level ~ CP... so... useless, sorry.

**Comment by JCCIRO** [comment]
Hello @Lunat1q Okay, I understand that.
Next I would like to explain my reasons that led me to conclude ask that feature to its development:
The option would be very useful to filter the pokemon with the same IV but we do not know which is the maximum of CP that specifically reaches every pokemon.
For example; According to the images, which is attached below, I have a Zubat with IV 95.6% as an Eevee with IV 95.6%, both are also level 29 but that does not mean that the CP of both is the same value for each . Zubat CP 524
![poke_list_1](https://cloud.githubusercontent.com/assets/21242553/18421103/3ff75cb0-7847-11e6-82ca-f00497579507.jpg)
 and CP 794 Eevee.
![poke_list_2](https://cloud.githubusercontent.com/assets/21242553/18421106/53392c86-7847-11e6-9241-5e98d62f062a.jpg)
 (It can also be seen in the same type of pokemon, look at pictures of Rattata level 29 as well).
![poke_list_4](https://cloud.githubusercontent.com/assets/21242553/18421111/6da37b94-7847-11e6-95eb-21c161e989b7.jpg)
![poke_list_5](https://cloud.githubusercontent.com/assets/21242553/18421112/7272b194-7847-11e6-8469-effa754357fb.jpg)
Each Pokemon has a maximum value in CP and to know it would have to be consulting it on the web all the time I want to keep the best pokemon in terms of the values ​​of IV and CP together and becomes more wasteful when deciding which TRANSFER.
With a filter that organize at least this value (level), it would be an added value more accurate to help visualize the pokemon that despite having a very high value IV (Example 100%) but very low CP (Example Level 1 10 CP) and ultimately are not good to have them on the list. Sometimes the BOT delete a pokemon high CP level because the IV is less than 94% (Level 30) if you have a 100% IV and 10 CP (Level 1) or simply removed for being an IV lower Maxed 100% regardless of the CP. (Note attached image Flareon Level: 16 CP 1208 and 100% IV, when it encounters a higher level Flareon CP and 99% iv, the BOT transfers)
![poke_list_3](https://cloud.githubusercontent.com/assets/21242553/18421117/8eb77ee8-7847-11e6-8d25-81fe8cc434b2.jpg)

Currently, my configuration is to keep min CP: 2000, but of course the maximum Rattata reach 600 CP in level 30, and if I have any 100% IV and 10 CP BOT only keep on the list 10 CP.
Some other BOTS use that option in the filter transfer.
Just leave it to his consideration and can reflect this case in more detail.
So I want to give that suggestion to further improve the excellent BOT you have managed to develop.
Thank you very much for your offered attention
