### ISSUE TITLE
Bot does not hatch egg

### ISSUE THREAD

**Issue by itterror** [Lunat1q/Catchem-PoGo#1665]
Check the logs below, the pokemon of the hatched egg (XP did; for lvl up) was not recieved.
 

> [17:00:57] Incubator status update: 0,01km left
> [17:00:57] Distance to target location: 17,22 meters. Will take 13,55 seconds!
> [17:01:34] Name: Dame mit Rock und Handtasche XP: 50, Gems: 0, Items: 1 x ItemRevive, 2 x ItemPotion
> [17:01:37] Distance to target location: 5,1 meters. Will take 2,04 seconds!
> [17:01:39] Distance to target location: 5,53 meters. Will take 3,07 seconds!
> [17:01:41] Distance to target location: 6,65 meters. Will take 2,24 seconds!
> [17:01:44] Distance to target location: 12,11 meters. Will take 5,41 seconds!
> [17:01:50] Distance to target location: 6,41 meters. Will take 3,61 seconds!
> [17:01:53] Distance to target location: 7,52 meters. Will take 2,91 seconds!
> [17:01:56] Distance to target location: 10,77 meters. Will take 6,5 seconds!
> [17:01:58] Throwing Normal PokeBall - WILL HIT
> [17:01:58] (Flee) | Rattata, Lvl: 14 | CP: (195/355) | IV: 48,89% | Type: Normal | Chance: 40,01% | Dist: 48,35m | Used: PokeBall (101 left) | XP: 0 | 
> [17:02:30] Throwing Normal PokeBall - WILL HIT
> [17:02:32] [Catch Dump] Caught Pidgey - Coords[Lat:]
> [17:02:32] (Success) | Pidgey, Lvl: 23 | CP: (399/442) | IV: 62,22% | Type: Normal | Chance: 31,22% | Dist: 68,09m | Used: PokeBall (100 left) | XP: 100 | Candies: 1802
> [17:02:32] Level up! Rewards: 25 x ItemUltraBall, 20 x ItemMaxPotion, 15 x ItemRevive, 15 x ItemRazzBerry, 1 x ItemIncenseOrdinary, 1 x ItemLuckyEgg, 1 x ItemIncubatorBasic, 1 x ItemTroyDisk
> [17:03:05] Throwing Great! PokeBall - WILL HIT
> [17:03:06] [Catch Dump] Caught Kabuto - Coords[Lat:]
> [17:03:06] (Success) | Kabuto, Lvl: 1 | CP: (12/692) | IV: 24,44% | Type: Normal | Chance: 100% | Dist: 55,01m | Used: PokeBall (99 left) | XP: 150 | Candies: 6
> [17:03:39] Using Razzberry. Berries left: 39
> [17:03:55] Throwing Normal GreatBall - WILL MISS
> [17:03:55] (Missed) | Squirtle, Lvl: 13 | CP: (319/650) | IV: 44,44% | Type: Normal | Chance: 16,61% | Dist: 48,04m | Used: GreatBall (96 left) | XP: 0 | 
> [17:04:12] Throwing Spinning Normal GreatBall - WILL HIT
> [17:04:12] (Escape Attempt #2) | Squirtle, Lvl: 13 | CP: (319/650) | IV: 44,44% | Type: Normal | Chance: 16,61% | Dist: 48,04m | Used: GreatBall (95 left) | XP: 0 | 
> [17:04:28] Using Razzberry. Berries left: 38
> [17:04:44] Throwing Normal GreatBall - WILL HIT
> [17:04:45] [Catch Dump] Caught Squirtle - Coords[Lat:]
> [17:04:45] (Success Attempt #3) | Squirtle, Lvl: 13 | CP: (319/650) | IV: 44,44% | Type: Normal | Chance: 16,61% | Dist: 48,04m | Used: GreatBall (94 left) | XP: 100 | Candies: 149
> [17:05:18] [Inventory] Pokeballs: 98 | Greatballs: 93 | Ultraballs: 73 | Masterballs: 0 | Total: 264
> [17:05:18] [Inventory] Potions: 6 | Super Potions: 2 | Hyper Potions: 10 | Max Potions: 20 | Total: 38
> [17:05:18] [Inventory] Razz Berries: 38 | Bluk Berries: 0 | Nanab Berries: 0 | Pinap Berries: 0 | Wepar Berries: 0 | Total: 38
> [17:05:18] [Inventory] Revives: 28 | Max Revives: 0 | Total: 28
> [17:05:18] [Inventory] Incense: 9 | Cool Incense: 0 | Floral Incense: 0 | Spicy Incense: 0 | Total 9
> [17:05:18] [Inventory] Lure Modules: 6 | Lucky Eggs: 6 | Incubators: 1 | Total: 13
> [17:05:18] [Inventory] Inventory Usage: 391/350
> [17:05:18] 19x ItemPokeBall
> [17:05:50] 6x ItemPotion
> [17:06:06] 2x ItemSuperPotion
> [17:06:21] 10x ItemHyperPotion
> [17:06:37] 10x ItemMaxPotion
> [17:07:09] 18x ItemRevive
> [17:07:41] 18x ItemRazzBerry
> [17:08:30] [Inventory] Pokemon Stored: 185/250
> [17:08:31] Squirtle     - CP:  319  IV:  44,44%  [Best CP:  527  IV:  60,00%] (Candies: 150)
> [17:08:47] Pidgey       - CP:  399  IV:  62,22%  [Best CP:  369  IV:  84,44%] (Candies: 1803)
> [17:09:04] Eevee        - CP:  592  IV:  82,22%  [Best CP:  390  IV:  93,33%] (Candies: 266)
> [17:09:21] Distance to target location: 5,84 meters. Will take 1,6 seconds!
> [17:09:48] Name: Planten Un Blomen - Karte XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemSuperPotion
> [17:09:50] Distance to target location: 7,18 meters. Will take 2,38 seconds!
> [17:09:52] Distance to target location: 6,88 meters. Will take 2,65 seconds!
> [17:09:54] Distance to target location: 7,57 meters. Will take 2,47 seconds!
> [17:09:57] Distance to target location: 8,68 meters. Will take 2,6 seconds!
> [17:10:01] Putting egg in incubator: 10,00km left
> [17:10:01] Putting egg in incubator: 10,00km left
> [17:10:01] Distance to target location: 7,83 meters. Will take 2,6 seconds!
> [17:10:04] Distance to target location: 20,15 meters. Will take 6,05 seconds!
> [17:10:12] Using Razzberry. Berries left: 19
> [17:10:23] Throwing Spinning Great! GreatBall - WILL HIT
> [17:10:24] [Catch Dump] Caught Kabuto - Coords[Lat: ]
> [17:10:24] (Success) | Kabuto, Lvl: 24 | CP: (611/674) | IV: 13,33% | Type: Normal | Chance: 24,45% | Dist: 33,51m | Used: GreatBall (93 left) | XP: 160 | Candies: 9
> [17:10:57] Distance to target location: 21,49 meters. Will take 6,36 seconds!
> [17:11:04] Distance to target location: 15,18 meters. Will take 9,23 seconds!
> [17:11:14] Distance to target location: 14,29 meters. Will take 4,18 seconds!
> [17:11:19] Distance to target location: 15,93 meters. Will take 5,96 seconds!
> [17:11:26] Distance to target location: 21,71 meters. Will take 6,12 seconds!
> [17:11:32] Distance to target location: 26,05 meters. Will take 14,35 seconds!
> [17:12:07] Name: Modell Messe und Park XP: 50, Gems: 0, Items: 1 x ItemRevive, 2 x ItemPokeBall
> [17:12:33] Name: Klaus Kütemeier XP: 100, Gems: 0, Items: 1 x ItemRevive, 1 x ItemGreatBall, 1 x ItemPokeBall, 3 x ItemRazzBerry, 2 x ItemPotion
> [17:12:33] Found an egg, distance: 2,0km from PokeStop: Klaus Kütemeier

**Comment by Lunat1q** [comment]
i have 1 word... pastebin.

**Comment by Lunat1q** [comment]
Also, i think it just hatched, so nothing wrong imo.

**Comment by itterror** [comment]
no. the pokemon was never awarded!
