### ISSUE TITLE
When disabling discovery pathing before start - bot does not find pokestops

### ISSUE THREAD

**Issue by itterror** [Lunat1q/Catchem-PoGo#1667]
See title.

**Comment by Spk345** [comment]
Does it work with discovery pathing on? Or?

I mean, I can't really help you with this little of information... Might want to join us on discord. Thank you.

**Comment by aldrinskie** [comment]
No usable PokeStops found in your area. Is your maximum distance too small? this is my problem

**Comment by alanearl** [comment]
Softban.
Restart modem.

**Comment by itterror** [comment]
@Spk345 yes it works with discovery pathing on. changing the settings while running has no effect on the bot (keeps using discovery pathing) when i restard bot (so pokestops got flushed) and start without discovery pathing, there is again no pokestops.

**Comment by aldrinskie** [comment]
reset the router? means pushing the small button, restarts all the password,name and etc?

**Comment by furyhawk** [comment]
Just need to power off yr modem for a few mins and then switching it on later. This will grab a new IP
