### ISSUE TITLE
Help batch commands

### ISSUE THREAD

**Issue by Baromm** [Lunat1q/Catchem-PoGo#167]
Could share the commands supported batch?

my example: (bat game to run for 4 hours and to pause for 4 hours and repeat "lack find the command " "START ALL")
--------------------------------------------------------------------------
ECHO OFF
cls
setlocal enabledelayedexpansion
title AUTO GUARD...BY BAROM
start Catchem.exe "START ALL"
echo. -----------------------------------------------------------
echo. -        You are in the game for the next 4 hours         -
echo. -----------------------------------------------------------
ECHO WScript.sleep 14400000 > temp.vbs && cscript temp.vbs
cls
taskkill /F /IM Catchem.exe
cls
echo. -----------------------------------------------------------
echo. -                You are on a break 4 hours               -
echo. -----------------------------------------------------------
ECHO WScript.sleep 14400000 > temp.vbs && cscript temp.vbs
start AUTOGUARD.bat
exit
--------------------------------------------------------------------------

sorry my english I am Brazilian
Thank you..

**Comment by Lunat1q** [comment]
in next release there will be autostart for profiles
