### ISSUE TITLE
SHORT SNIPER IDEA!

### ISSUE THREAD

**Issue by maknado** [Lunat1q/Catchem-PoGo#1670]
short sniper

I use the same route for more than 1 bot, when one of the bots find a rare poke or selected from a list, show the info latitude and longitude, that way I do a forcemove on another bot to get this other also to be near !

Can it possible?

**Comment by Speedmod88** [comment]
and something like to snipe pokemon appeared in the same city only!

**Comment by maknado** [comment]
When I have two bots on the same latitude longitude without using route personalidada bots take the same Pokemon, but if they do not always go pro same side!

**Comment by Cryptologism** [comment]
Anything regarding to word 'Snipe' are not approve by @Lunat1q.. Trust me...

**Comment by Lunat1q** [comment]
This version is better, but still, it's VERY limited range, cause you can't get too far for 15 mins.
