### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by RandomGiHu** [Lunat1q/Catchem-PoGo#1671]
![sem titulo](https://cloud.githubusercontent.com/assets/22119972/18412226/3db0e258-7781-11e6-90e5-b56308fec327.png)

Don't have a clue how to solve this... This just doesn't let Catchem to work.

Help

**Comment by Cryptologism** [comment]
Internet Conenction or maybe because Niantic is updating thier server to banned 3rd party user... 
read #1672
