### ISSUE TITLE
[Need Help] Lured Pokestops

### ISSUE THREAD

**Issue by Smarty2712** [Lunat1q/Catchem-PoGo#1674]
Hey

there was a time my bot shown lured pokestops in red or something, but now every pokestop is blue and i dont see if it is lured or not? Is it possible to see agian witch is lured and witch not?

And if there is a lured can i set up the bot somehow that he just will catch pokemon around the lured stop?

**Comment by Lunat1q** [comment]
if it's blue then it's not lured.
