### ISSUE TITLE
Order by don t work !

### ISSUE THREAD

**Issue by pippocalonio** [Lunat1q/Catchem-PoGo#1675]
When i try to order poke it give me back wrong list

**Comment by tuntin9** [comment]
yes, same to me

**Comment by johnpeterphoto** [comment]
you can have multiple selections clicked when creating the order so make sure what is highlighted is what you want and click the others non-highlighted.  There isn't a large shade difference so look closely.

**Comment by pippocalonio** [comment]
tx a lot good it work
