### ISSUE TITLE
Impossible to Change the Longitude

### ISSUE THREAD

**Issue by ChiiFii** [Lunat1q/Catchem-PoGo#1678]
Hey,
i'm using Version 1.5.2.1 and it is impossible to change the Longitude. I can enter any coord - but it will not accept.

If I change the coords into the config - it won't start the Bot with my Account.

*edit* Error is also in Version 1.5.3.0

**Comment by Spk345** [comment]
Were you able to find the location in the console?
[![githubissue1.png](https://s17.postimg.org/57teb6qgv/githubissue1.png)](https://postimg.org/image/6muyzwrjv/)

Try that and let me know.

**Comment by ChiiFii** [comment]
I've found the solution - I used the coords from Google Maps. They used the format x.xx,x
The Bot is usin x,xx.x
