### ISSUE TITLE
is this softban?

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1679]
Hi,
my bot can't catch poke. always flee.
but it can loot pokestop.

I try to stop it almost an hour. start it again, but it is still the same.
always flee when try to catch poke. but still able to loot pokestop.

it happen after I run my bot almost 24hours without stop. I don't know whether it ever pause or not. I run two bots, and Catchem write log for my two bots in a single log. quite hard for me to check which action did by which bot

now I try to stop for couple hours before I start it again.
will update you later

**Comment by wkeongkhor** [comment]
u cant catch more than 1000 pokemon within 24hours

**Comment by saldotman** [comment]
Ok. thanks
