### ISSUE TITLE
[Suggestion] 2 account walk together

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1681]
Hi guys, it would be nice if 2 bot could walk together (same route, speed, long lat etc...)  like go to catchem all with friends (of cause on the same catchem but with different vpn/proxies)

**Comment by Spk345** [comment]
You are able to do that already by putting the bots on the same route at the same time... However, I wouldn't recommend it because one bot will always have variance and will have "pokemon fled" issue. I have it on my legit account sometimes when riding around with my friends.
