### ISSUE TITLE
[Help Wanted] Issue: Eggs Don't Show in Log After Being Activated On Phone?

### ISSUE THREAD

**Issue by agreda** [Lunat1q/Catchem-PoGo#1685]
Hello,

 i set my settings to Use Egg Incubators checked and use only unlimited incubators checked, this made the bot use only unlimited incubator and made me save 10km eggs i login to my phone and click the eggs 10km 5 of them and go back to bot and run, somehow the bot did not see or notify on logs that those 10km eggs hatched

**Comment by Spk345** [comment]
If your eggs hatched while you were on the phone, then of course it wouldn't be in the logs?

**Comment by agreda** [comment]
I activated the eggs on phone and it hatched during bot timr

**Comment by Spk345** [comment]
I do not use Catchem bots on my phone, so I am unable to test this issue. If anyone else would like to that would be grand.

**Comment by agreda** [comment]
1. Run bot normal activity
2. Stop bot for normal play
3. Decided to click incubator 'not unlimited'
4. Logout phone
5. Run bot normal activity again
6. I noticed those what i incubate during phone time did not apear on bot
logs or show pogo list bot already hatched 3 5kms and those 10kms did not
alert on logs

**Comment by immenz** [comment]
Same issue here!
