### ISSUE TITLE
What is the current order of precedence of the bot? power-up, evolve or transfer

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1686]
When a new poke is captured or hatched, it can be duplicated in the inventory and triggers transfer.  But if it is evolved first, another duplication check needs to be done but under the new poke name.

If power up takes precedence, the candidate to transfer may also change.

When is the current setting now or let user decide on his own in future version?

**Comment by Spk345** [comment]
This would be more of a @Lunat1q question.

**Comment by Lunat1q** [comment]
It's not being marked to transfer upon catch. It's from time to time routine, using latest data.
