### ISSUE TITLE
can not open all

### ISSUE THREAD

**Issue by LuBaJo** [Lunat1q/Catchem-PoGo#1688]
Hello,
I'm sorry for my english but i hope you understand my problem.
I can't open all dats. There is always a problem.

**Comment by petoe93** [comment]
how should we understand your problem if the information on the problem is shorter than your apology for your English...smh

**Comment by LuBaJo** [comment]
I can't open the zip file with Windows.rar
There stand always that there is a problem

**Comment by KitazawaMoa** [comment]
Use 7zip instead of winrar.
http://www.7-zip.org/download.html
