### ISSUE TITLE
[help wanted] What does "delay evolve variation" exactly mean?

### ISSUE THREAD

**Issue by mohhawk** [Lunat1q/Catchem-PoGo#1690]
Can anyone explain what does that mean please?
I looked it up in the wiki but didn't find any thing related.

**Comment by eloxxx** [comment]
I think its the variation between two evolution.

If you set up evolution at 30 sec, and you are evolving exactly every 30 sec, niantic can detect it. So there is a small variation feature between evolution.

For exemple first 30 sec, the second one 28.8, the thir one 31.23 etc

**Comment by Cryptologism** [comment]
Ermmm itz maybe some random time to evolve to make sure niantic did not detect it was bot user...
