### ISSUE TITLE
Help, route on blue lines, red lines, etc

### ISSUE THREAD

**Issue by c4z4d0r4** [Lunat1q/Catchem-PoGo#1691]
hi, i love your work, but i have little question,
in an account, the icon is moved over red lines through the streets
in the other account, it moves by green lines flying over the houses,
the configuration is the same, I have the api key, each has its key
it is possible to move by red? thanks

PD red, green, blue lines? please expand info

**Comment by Spk345** [comment]
Red line is either your routing service or custom route, this is what the bot will follow.
Green line is discovery pathing, if bot is not set to custom route, it will queue your routing service to optimise the best path between all discovered pokestops.
Blue line is your bots recent path walked.

**Comment by c4z4d0r4** [comment]
3

**Comment by c4z4d0r4** [comment]
i understand, and i tested it, but :

**Comment by c4z4d0r4** [comment]
i understand, and i tested it, one account which worked fine, today as changed and fly over houses, the account that did not work, now works fine by red lines, but : when  i make double click (or not)
one of bots uses "Use discovery Pathing" and goes on red line (OK)
![screenshot_2](https://cloud.githubusercontent.com/assets/22132105/18479052/c4709974-79d3-11e6-98b1-d89a8d05d86e.jpg)

other bot are same config and goes (flying¿?)
![screenshot_3](https://cloud.githubusercontent.com/assets/22132105/18479101/f88bff0a-79d3-11e6-9e26-17b9d18ce441.jpg)
sometimes see green line, but not allways
![screenshot_4](https://cloud.githubusercontent.com/assets/22132105/18479124/19483c72-79d4-11e6-8f4d-a64a964acb88.jpg)

pd. forgive my english and my insistence. thanks for hard job
