### ISSUE TITLE
can i get banned or better wait for new version

### ISSUE THREAD

**Issue by manieczek** [Lunat1q/Catchem-PoGo#1692]
can i get banned or better wait for new version?

**Comment by xPokemasterx** [comment]
better wait

**Comment by wkeongkhor** [comment]
@Lunat1q

**Comment by JABUNOO** [comment]
wait

**Comment by beloware** [comment]
wait.

**Comment by nobilus** [comment]
Why ?

**Comment by JABUNOO** [comment]
@nobilus maybe api changes? New anti cheating measures.... Do what u want but waiting is the best option

**Comment by nobilus** [comment]
OK 
I had not seen an update was in progress :/ Stop my bots !

**Comment by alanearl** [comment]
I cant find updates on pokemon go on playstore :)
Therefore botting will resume until i can see the updates...

**Comment by Spk345** [comment]
#1704
