### ISSUE TITLE
No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by WeedAndModz** [Lunat1q/Catchem-PoGo#1693]
I have this message , why?

**Comment by XurWuy** [comment]
Your acc has been softbanned..... Stop botting for 6-12 hours, log on from your phone, test and go cap some poke and spin some stops. Then, rest 2-6 hours, continue botting....

**Comment by chadzkiiyaneh** [comment]
oohww. i see.

**Comment by alanearl** [comment]
Restart modem.
Soft ban
