### ISSUE TITLE
Lunat1q this is the best bott ever. But please help us should we stop botting before you have updated it?

### ISSUE THREAD

**Issue by h3wiin** [Lunat1q/Catchem-PoGo#1697]
@Lunat1q

**Comment by Spk345** [comment]
Please do not tag lunatiq, you are welcome to join discord and ask about current issues. Until newest pogo apk is fully rolled out, older version, which we run on, works fine.

**Comment by h3wiin** [comment]
@Spk345  my bad sorry. So the got will just stop when the new apk kicks in? Or is it mabe a chance of bann in any way when it kicks in?

**Comment by h3wiin** [comment]
personal opinion.
