### ISSUE TITLE
Error on tranfers

### ISSUE THREAD

**Issue by gutosales** [Lunat1q/Catchem-PoGo#1700]
Las transferencias están de nuevo en el error, que no están calculando correctamente y relación de CP / IV y está transfiriendo Pokemon con muy alta CP y dejar pokemons con super bajo cp. Es la segunda vez que el programa pasa me Pokémons con CP / IV alto y deja Pokémons con CP / IV a continuación.
Y NO ME marcado los "priotize IV over CP"
y no está respetando la ''keep min duplicate', puse para mantener 3 duplicados y las transferencias de todos ellos, dejando sólo 1 pokemon.

The transfers are again in error, they are not calculating properly and ratio of CP / IV and is transferring Pokemon with very high CP and letting pokemons with super low cp. It is the second time the program moves me Pokemons with CP / IV high and leaves Pokemons with CP / IV below.
And I DO NOT marked the "priotize IV over CP"
and is not respecting the 'keep min duplicate', I put to keep 3 duplicates and transfers them all, leaving only 1 pokemon

**Comment by lukas1989** [comment]
same here

**Comment by Spk345** [comment]
Have you made sure to update your pokelist settings for the pokemon you'd like to keep? that pokelist will override your settings. If you have it set to keep 2000cp pokemon and 95% IV, it will *only* keep pokemon that meet *both* requirements.

**Comment by gutosales** [comment]
Of course I'm sure I left the settings according to what I what I wanted, so I stopped using the 1.5.3.0 version and returned to use 1.5.2.1_upd version and the problem with the transfers stopped, was working according to the settings you've chosen, it is problem with the version.

**Comment by tyu366** [comment]
@gutosales please refer to my issue #1722. 
The situation is even worst than you expected.

**Comment by Lunat1q** [comment]
fixed
