### ISSUE TITLE
about 'Force Move to'

### ISSUE THREAD

**Issue by gutosales** [Lunat1q/Catchem-PoGo#1701]
I would like to give the idea that 'Force Move To' was a priority command to any other action and the BOT to stop any further action and fulfill this function, based at the time in which a player uses this function he saw some pokemon that locality . So at the time that 'Force Move To' were triggered it prioritize the function and follow this path to the selected maximum speed in settings

**Comment by goiabs** [comment]
/\ would be very nice! I use the "force move" when i see a rare pokemon in the nearby. So i want to arrive quickly, but the bot stops many times in the way to catch pokemon or loot pokestops, spending much time for it.

**Comment by Spk345** [comment]
You can temporary turn off "loot pokestops" and "catch wild pokemon" in your settings. You can also temporary increase your speed factor above console to move faster, but be careful of going too fast.

**Comment by goiabs** [comment]
But need to do a lot of things to it. The suggestion is that te "Force Move" do all that actions (turn off "loot pokestops" and "catch wild pokemon", increase speed factor to the maximum setting).
