### ISSUE TITLE
Routes and Telegram configuration are not saved in the pre-release

### ISSUE THREAD

**Issue by rodrigogs** [Lunat1q/Catchem-PoGo#1702]
While running the bot I can see that json files are successfuly updated when I save my config, but when I reopen the bot it simply erases all the config...

**Comment by rodrigogs** [comment]
Figured out that it only works with a clean installation.

**Comment by rodrigogs** [comment]
If catchem.json and tlgrm.json are present in the root folder, bot erases the config folder's configuration.

**Comment by Spk345** [comment]
Please update to the newest release. Let me know if it continues to have these issues.

**Comment by golgolak** [comment]
yes it erases from the root folder coz it gets transferred under config folder with all your telegram and route settings intact.
