### ISSUE TITLE
[Feature Request] Order by Max CP and Possible CP

### ISSUE THREAD

**Issue by Waale** [Lunat1q/Catchem-PoGo#1703]
Sorry for the repost, I didn't have the chance to explain.
I think this is quite important so you can know easily where to invest your stardust, because CP and IV aren't everything. Max CP is what will matter in the end.

**Comment by JCCIRO** [comment]
#1664 This is my idea for this matter, please review it again, thank you.

**Comment by Waale** [comment]
Yep, your post is definitely more detailed. And for me it makes a lot of sense. That was exactly my point.

**Comment by Lunat1q** [comment]
done.
