### ISSUE TITLE
[README] FAQ About Pokemon Go Update

### ISSUE THREAD

**Issue by Spk345** [Lunat1q/Catchem-PoGo#1704]
# **Frequently asked questions about the newest update and the future of Catchem.**

## **What is the future of Catchem and other bots that run on the older version of Pokemon Go 0.35 APK?**
- With the newest update of Pokemon Go, once it is globally release and *Forced Updated*, all older versions will be refused service.  When that happens, any bot or device that does not update will be refused service to the Pokemon Go servers. Until this happens however, Catchem can still be ran just like always.

## **Will I get banned if I continue to bot with Catchem until the newest release is fully enforced?**
- You always run the risk of being banned by using bots. However, Catchem is a very humanized bot, and until now has avoided detection. When Pokemon Go 0.35 was cracked there was and still is, a lot of variables that we are not sure which flags an account for detection. This has and will most likely always be the case.

**- If however, you are very worried, you can always stop now, it's your decision.**

## **When will the newest Pokemon Go 0.37 APK be available (including the newest feature POKEBUDDY)?**
- Last update took three days to reverse engineer to the point of bringing bots back online. I highly doubt that it will take much longer than that to reverse engineer the newest release, even with the amount of changes. Until then however, Catchem will be down until the newest release is Reverse Engineered and workable. 

## **How will I know when Pokemon Go global release has fully rolled out and Update is Forced?**
- We will take down Catchem latest release,  off the release page and will alert all users through Github and Discord. 

## **What is the Global Release status:**
- *Updated:* Most countries now have the Android and Apple updates to the newest APK 0.37. However, very few are forced updates.

## **Can I run Catchem right now?**
- Yes, until Pokemon Go is Forced Updated globally, you can use the older APK (0.35), which Catchem runs on. After the Forced Update happens everywhere, older POGO APKs will be refused service. 

## **If I'm refused service by using an older version of POGO APK (such as 0.35) will I be banned?**
- I highly doubt you will have your accounts banned by being refused service when using an old APK. Remember, with the newest update to Pokemon Go, a lot of rooted/Jailbroken users cannot access their game, but their accounts are still there.

## **I have updated to the newest Pokemon Go APK 0.37 on my phone, is it still safe to use the same account on Catchem?**
We are not entirely certain if it is safe or not. Considering many people own many devices, some that do not have the update available yet possibly, this may or may not be safe. Best bet is to not use Catchem after you updated the account to 0.37 APK. You can still use older bots that haven't be logged in with 0.37 on phones or other devices.

## **If I updated to 0.37 APK on my phone, but want to use my account for botting anyways, is that OK?**
It's up to you. We do know however, that even though we don't see any buddy settings, they do appear to accumulate distance and candies, which will be accrued when you log into your updated client.

## **Are Catchem Devs working on Reverse Engineering the newest APK currently?**
- No, we are waiting until the APK is Reverse Enginnered by other developers and we will restructure to bring Catchem back online as soon as possible. This could take sometime, so make sure to check on discord for latest updates.

# **If you have any other questions, as always visit us on Discord.**

**Comment by Charlier69** [comment]
1.7.0 was now in Germany, any news when the new Bot Version come?

**Comment by HernestoSanchez** [comment]
Thanks for the info!

By the way. We got this update yesterday in Brazil.

Cya fellas!

**Comment by zhach01** [comment]
it's now in france

**Comment by WsTs** [comment]
Malaysia (Asia) 9-Sep-2016

**Comment by stark93** [comment]
It´s now in Mexico too

**Comment by ExequielGC** [comment]
Peru updated v0.37 13-09-2016

**Comment by shanishkag** [comment]
WHEN YOU GNNA GIVE UPDATE FOR BOT FOR NEW RELEASE ... ???

**Comment by xPokemasterx** [comment]
0,37 Version now in Germany.. better stop botting and wait for new Update on Catchem? 

Thanks for help!°

**Comment by Cowering** [comment]
USA updated.. my phone auto downloaded it :(

**Comment by Arantesrodrigo** [comment]
in Brazil is already available to Update 0.37

**Comment by jahwulf935** [comment]
updated in the Philippines as of Sept14

**Comment by madafoquer** [comment]
Venezuela and Latinamerica too!

**Comment by kaku1237** [comment]
hi all

we got the update here in the philippines many of spoofers here are wondering what went wrong i try to change my device and try to unroot still i get my device is not compatible with the latest release. but still working with my wife phone

**Comment by opidvash** [comment]
Any news about the update in the eastern europe countries?

**Comment by ERAsor83** [comment]
oh i Just read this ... haha well i can say.. "to late 4 me ;-P)" I Already updated my phone to 37 und also use an Jailbroken one.  (Yes there is a Way to get Pokemon running on an Iphone ;-)

Well long story short. I already used it on the Phone (o.37) to get my Buddy running and keep getting Candys like that. Maybe im Falgged. But i have NEVER had an Softban or something like that. Im lvl 25+
Time will show what happens. Right now I can just keep going an we will see.

**Comment by lukas1989** [comment]
Just got another update here in Germany. New version is 0.39.0 
I'm feared the devs can't be fast enough with their reverse engineering. It was a great bot but since the release of 0.37 I'm not using any bot because I think the risk of using an old api is way more risky to get permabanned.

**Comment by daywalker7780** [comment]
i got this error....and i don't know what it mean.....any help?
 Catchem API version is less than the minimum stop botting to avoid ban!

**Comment by HernestoSanchez** [comment]
Sup! So, the catchem API us obsolete? Weird, the devs never let an outdated version without a HUGE WARNING in front page.. I wonder..
