### ISSUE TITLE
Catchem stopped working on my PC

### ISSUE THREAD

**Issue by theamazingzack** [Lunat1q/Catchem-PoGo#1707]
Excuse my English, but my problem is when I open Catchem opens a window warning that the Catchem stopped working ...
But already updated the drivers and still the problem remains, how to proceed?

**Comment by alanearl** [comment]
Repair your .NET to latest version.
Disable anti virus for testing.
Check internet connection latency.

**Comment by Spk345** [comment]
Run as admin. Some Antivirus have been flagging and stopping catchem due to false positives due to encryption.

**Comment by Spk345** [comment]
If you continue to have issues, join us on discord, thank you.

**Comment by h3wiin** [comment]
@Spk345  hey how to join you guys on discord? have download but need a code for your chatt?

**Comment by theamazingzack** [comment]
after doing everything you said, the problem continued
![sem titulo](https://cloud.githubusercontent.com/assets/22139897/18433791/e7c60888-78bf-11e6-9d10-8159fd43e356.jpg)
