### ISSUE TITLE
Question: How did stats was being calculated?

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#1708]
Dear Dev,

Any idea what is the difference?

![untitled1](https://cloud.githubusercontent.com/assets/648116/18423114/857a2eba-78d4-11e6-820e-3601a191f338.png)
![untitled2](https://cloud.githubusercontent.com/assets/648116/18423115/858d9716-78d4-11e6-944c-60723cf76079.png)

My 100% IV is weaker :) on atk & def.

Keep up the good work.

**Comment by Spk345** [comment]
Everything is weaker because your pokemon are not the same level. Level it up 2 and you will see the difference.

**Comment by Spk345** [comment]
Have you refreshed it in your inventory? If you just leveled up and evolved stats don't change immediately.

**Comment by alanearl** [comment]
Yes i already refresh the inventory many times. Maybe this is a bug.
I will just wait for the final release of v1.5.3 maybe its already fixed on that version.

Thanks.
