### ISSUE TITLE
[Feature Request] Evolve/Keep Min CP% instead of raw CP

### ISSUE THREAD

**Issue by jessiewestlake** [Lunat1q/Catchem-PoGo#1709]
Instead of using the base CP for keeping Pokemon or evolving them and other such things, can you add an option for using the percentage of the Current Possible CP? That way we can keep or evolve Pokemon which are almost all the way leveled up.

Using base/raw CP doesn't help since different Pokemon have different CP value possibilities, especially when they have multiple evolutions. This will help prevent wasting candies on upgrading Pokemon.

**Comment by Lunat1q** [comment]
not planned
