### ISSUE TITLE
[Suspect bug] Some favourite Pokémon have been unfavourite or gone (transferred)

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1710]
I do not observe this issue after 2 days running v1.5.2.1 until

1. I have tried to check the auto favourite option last night.
2. The favorite action with log showing transfer keeps running over 15 minute.  (Expect to determine the list in 1 min).  It is abnormal as I already have over 210 Pokémon marked favourite.  The number of Pokémon to determine is within 20.
3. I uncheck the option and save setting but not sure whether the bot has been restarted or not.  I think it is very likely to be restarted but not very sure.  
4. I have checked the inventory and it 'appears' nothing unusual and go to sleep. 
5. The bot crash itself in the early morning after operating for 2-3 hours.
6. Lost and unfavourite Pokémon are observed on the next day.

There is some very prominent clue that 
- if I have 210 Pokémon marked favourite, my inventory level should never drop below that value.
- For each species, I have marked at least one as favourite but I found some species do not have any marked on the next day.  They are not new to my pokedex.

**Possible explanation**
- Pokémon are either unmarked or the marked one already transferred.  So inventory drops.
- **Unfavourite action may be performed on favourite Pokémon when the auto favourite option is checked for short time.  The UI do not display correctly and so the inventory appears unaffected.  Restart the bot does not help unless the executable is restarted.**

**One more finding**
(FAVOURITE) info is not written to log and so we cannot trace it.

**Suggested test case**
1. Fresh start the executable and start the bot with auto-favourite off. You may uncheck ‘Catch wild Pokémon’.
2. Go to the information tab and select all Pokémon.
3. Mark your entire inventory as favourite 
4. Arbitrary unmark some of them of high IV
5. Stop the bot
6. Back to the setting and enter a low IV value for auto-favourite say 50
7. Check the auto-favourite option
8. Start the bot and wait until favourite action triggered
9. See if the favourite run for a long time
10. If so, uncheck the option and save setting.
11. Dump the inventory screen.
12. Restart the bot and dump the inventory screen.
13. Restart the executable and start the bot.  Dump the screen again.

**Comment by Spk345** [comment]
We fixed quite a few bugs in the newest release 1.5.3.0 RC17. We tested 17 release candidates. See if you still encounter this error in the newest version.

**Comment by kingbeelzebob** [comment]
where is this 1.5.3.0 RC17 you are talking about? i dont see it in the official release..

**Comment by tyu366** [comment]
not available in the download page.

**Comment by Lunat1q** [comment]
Untick autofavorite if you wanna do in manually, otherwise, you delegate controll of all poke fav to the bot.
