### ISSUE TITLE
Custom routes are erased after quitting the application.

### ISSUE THREAD

**Issue by coldneo** [Lunat1q/Catchem-PoGo#1712]
It seems that the custom routes are saved in catchem.json in the config folder. 
When it is running and I have added some routes, I can see the details when i inspect the JSON file.

However, when i quit the app, the JSON file reverts to the default template of:
{
  "$type": "Catchem.Classes.CatchemSettings, Catchem",
  "Routes": [],
  "ProviderEnum": 0
}

Reproducible always in my environment.

**Comment by alanearl** [comment]
Please disable your anti virus for a testing.
Maybe catchem is run in an isolated virtual environment by your security software?

**Comment by coldneo** [comment]
I've resolved this by deleting the catchem.json from the Config folder and only keeping it in the root folder. 
It works fine now - although the file is now only in the Config folder and not in the root folder - a little confusing yes.

**Comment by sinuraya** [comment]
What? closing issues without resolving hahaha.. well played mate

**Comment by ArchangelBr** [comment]
I had the same issue. What I did:

- Rename catchem folder to catchem.old
- unzip the release rc17 to new catchem folder
- copy the profiles folder from catchem.old to catchem
- Copy CatchemDb.Sdf from catchem.old\config to catchem\config
