### ISSUE TITLE
Question IV ATK/DEF/STA Calculation

### ISSUE THREAD

**Issue by dexxlab** [Lunat1q/Catchem-PoGo#1713]
Can you give me the formula for IV ATK/DEF/STA for Pokemons with general IV lower than 100%.

Is it possible to export all pokemons data to a database and if yes how?

I develop a database for the moment ...

Thank you for your response.

**Comment by alanearl** [comment]
Hi,

Please join the discord if you want to contribute.
Thanks.

https://discordapp.com/invite/pPwxX8Q

**Comment by pokter75** [comment]
Hi dexxlab, I google and found this, hope it helping you.
https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/
