### ISSUE TITLE
why the bot use ultraball and megaball with IV 30 if i sett up just for 90,80 and more IV,

### ISSUE THREAD

**Issue by paparino** [Lunat1q/Catchem-PoGo#1716]
the bot almost always prefer the megaball and ultraball for poke with low IV ,i set up the bot 80 IV for megaball and 90 for ultraball but nothing ,i tryed wyth the filter catch and without it dont cange nothing use ultraball for poke with 200 and 40 IV

**Comment by wkeongkhor** [comment]
what level can get megaball @paparino

**Comment by paparino** [comment]
maybe is the 0,35 chatch prob for the greatball? and 0,05 masterball

**Comment by ArchangelBr** [comment]
I had an issue like this, but I had no pokeballs, so it was using greatballs instead... I don't know if it's your case....

**Comment by paparino** [comment]
i have 300 normalbals and dont use them

**Comment by HernestoSanchez** [comment]
Probably has something to do with % catch rate. I used to have this problem and after changing the % on use "specific" ball if level/IV/CP, the bot stoped using the rarer balls.
