### ISSUE TITLE
[Errror] Can't Catch Mewtwo

### ISSUE THREAD

**Issue by sinuraya** [Lunat1q/Catchem-PoGo#1718]
![image](https://cloud.githubusercontent.com/assets/5442013/18444520/c0a19b62-7943-11e6-8095-0fab3304e68f.png)

**Comment by ArchangelBr** [comment]
:o:

**Comment by ArchangelBr** [comment]
WOW!

**Comment by EllosGaming** [comment]
Dude, don't play jokes with my feelings like that hahaha.

**Comment by sinuraya** [comment]
I was using a proxy provided by my friend and then I found a mewtwo. But sad strory, my bot can't catch it.

**Comment by EllosGaming** [comment]
Dude, no one can catch him yet... No one have a masterball... How did u throw it?!

**Comment by chumajer** [comment]
He is using a private server, u can catch legendary and u can use masterballs.

**Comment by sinuraya** [comment]
I need master ball to catch a mewtwo? Then it's not bot problem. But i never see bot get a master ball.

**Comment by alanearl** [comment]
Did you see the percentage chance its 0% hahaha!

**Comment by sinuraya** [comment]
![screenshot_2016-09-12-13-58-32](https://cloud.githubusercontent.com/assets/5442013/18453129/06edee9e-7968-11e6-9728-5dd36c6aeb63.png)
Using actual app, i can catch one.  :smile:

**Comment by petoe93** [comment]
good luck leveling that one up :D 
still don't get it tho..he got a fuckin mewtwo o.O

**Comment by Spk345** [comment]
This is not an issue with Catchem. Go to discord.
