### ISSUE TITLE
(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by Amerssa** [Lunat1q/Catchem-PoGo#1720]
since i've updated to newest version all my bots show this same message and don't move, i can't see any pokestops in the map .Can anyone help me ?
![screenshot_1](https://cloud.githubusercontent.com/assets/22024011/18446816/51bb4a70-78fa-11e6-898b-f83b7b10450b.png)

**Comment by ArchangelBr** [comment]
Is it normal on phone ?

**Comment by Amerssa** [comment]
Yup it works fine on phone , im pretty sure i'm not banned

**Comment by r3rodolfor3** [comment]
Soft ban. Restart your modem and try use only one bot at a time.
In a few hours you can star all the others.

**Comment by sinuraya** [comment]
Also check your bot altitude. If it goes under ground or flying than you can't find any pokestops.

**Comment by biggury** [comment]
Make a force move on map and done
