### ISSUE TITLE
UNIX based application

### ISSUE THREAD

**Issue by xalvin11** [Lunat1q/Catchem-PoGo#1721]
Is there a way to run the app on UNIX based OS (Mac, Linux)

**Comment by alanearl** [comment]
Yes if you will use virtual environment :D

**Comment by sinuraya** [comment]
u can always run paralel on mac or virtual box on linux :)

I'm doing this all the time, my main OS is windows 10 and I have linux and android installed in it. So when I need to run app in linux environment like spotify-ripper, all I need to do is fire up virtual box and run ubuntu. When I need to catch pokemons, I run nox app player.

**Comment by Spk345** [comment]
Catchem is windows only. You will have to run Catchem in a virtual machine. Lunatiq does not want to code for other systems.
