### ISSUE TITLE
Bug on handling pokemon of same type with same CP and IV.

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1724]
Though the 1.5.2.1 information tab, 
- You can only mark one of them as favourite.  You cannot mark both. Just nothing happens and no error message received.
- If you do transfer 1 of them (both unfavourite), both will be gone but only one transfer message is logged.  I am not sure whether I obtain one candy or two.
- If you do transfer 1 of them (one favourite), the transfer cannot be done and no failure message shown.

**Comment by Lunat1q** [comment]
it's not the "same type, same cp" it's UI glitch with duplicate pokemon.
