### ISSUE TITLE
Could the Route Creator show where is the pokestops???

### ISSUE THREAD

**Issue by ViniciusJCurtts** [Lunat1q/Catchem-PoGo#1726]
It will be easier to make the routes in the cities that don't have lots of pokestops like NYC.

**Comment by Spk345** [comment]
Good news! It *does*. All you have to do is *see* an area with your bot, and as soon as you open route creator and add a waypoint, all those lovely little cached pokestops will appear around your waypoint to help you route your path.

Even better than that? It's stored in a database between all your bots, so everything is locally saved, just for you.

This is only possible in the *newest* Release, so upgrade to use it.

**Comment by ViniciusJCurtts** [comment]
Perfect!!!

Em 12/09/2016 19:46, "Spk345" <notifications@github.com> escreveu:

**Comment by caioschiavo** [comment]
I try to do that but my pokestops are not show in routecreator
any help?

**Comment by Spk345** [comment]
You have to right click on map. Upgrade to newest rc 35 on release page.
