### ISSUE TITLE
Soft Banned

### ISSUE THREAD

**Issue by kilado94** [Lunat1q/Catchem-PoGo#1727]
Hi guys, i know there is alredy a thread of i gonna ask but i dont find ...
So i have 5 bots at this moment but in need to change IP every 10 minutes, i am geting always ip ban i use Proxy :/
Culd someone help me how to avoid this? 
and btw, whant best program to change ip? im using HotSpotShield Elite
Happy boting

**Comment by Simuroc** [comment]
If you don't use proxy, you always will suffered softban. I advice you use just one account in bot, because more than 1 ip will ban your accounts every time.

**Comment by biggury** [comment]
Look this link: https://github.com/Lunat1q/Catchem-PoGo/issues/1731

**Comment by kilado94** [comment]
thankz ;)
