### ISSUE TITLE
UI suggestion / Problem to distinguish the buttons

### ISSUE THREAD

**Issue by hynn123** [Lunat1q/Catchem-PoGo#1728]
Hey guys, thanks for all work spent with this project. It is a awesome project and you guys are incredible.

So, I dont know if it is just with me, but i just can't distinguish the buttons in "order by" when they are locked or not. It so hard to distinguish.

Thanks again guys.

**Comment by tyu366** [comment]
some tip text display on mouse over may help.

**Comment by sinuraya** [comment]
I think we need better contrast and better glyph for the button. But that may need rework from the start again.

**Comment by Spk345** [comment]
When active the buttons go blue, and when inactive it's green.

**Comment by Lunat1q** [comment]
exactly... see no problem to see if it's BLUE or GREEN.
