### ISSUE TITLE
Get off path and walk wierd

### ISSUE THREAD

**Issue by RandomGiHu** [Lunat1q/Catchem-PoGo#1729]
![sem titulo](https://cloud.githubusercontent.com/assets/22119972/18449925/ffd0bd4c-7928-11e6-818c-93f11b7054ae.png)

Since last update 1.5.3.0 my bot started to have this behavior...

1- When using the "not catch filter", still he walks to the Pokémon he should ignore, and then comes back to the path, and then walks again to the Pokémon, and then goes back to the path... And goes on and on, until he "decides" to go back to the path for good... This happens every single time a Pokémon that I filtered as "not to catch" spawns.

2- I decided to uncheck "not to catch filter" so he could keep walking, and he did what is in the attached picture...

3- He now also ignores PokeStops which is making broke on Pokeballs...

I'm thinking to go back to the version 1.5.2.1

**Comment by sinuraya** [comment]
Same issue but slightly different with me, my problem is bot will go vertical instead. Some time bot will fly (3000 m altitude) and sometime will digging the earth (-500 m altitude). And when that, happen no pokestop or pokemon will appear in map.

**Comment by ispsbg** [comment]
Same issue here, when i was 3 versions behind i didn't have it. Using Google API and Mapzen. Almost got fixed when i turned ON "Human Pathing".

**Comment by Lunat1q** [comment]
it's the attempt to find wild pokemon (3paw old marker), i will review the code, altitute data - from Mapzen, or you have wrong settings.
