### ISSUE TITLE
[Error] Not working

### ISSUE THREAD

**Issue by bitter88** [Lunat1q/Catchem-PoGo#1731]
I used it yesterday and it was working fine, but now it is not working anymore, I get this message:

> [18:03:23] (ERROR) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 189.91.112.33:443
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PokemonGo.RocketAPI.Login.PtcLogin.<GetSessionCookie>d__9.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 94
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Login\PtcLogin.cs:line 35
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Login.cs:line 55
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 33

**Comment by sinuraya** [comment]
connection problem

**Comment by JhulShock** [comment]
To me, works perfectly :S sorry, bro.

**Comment by sinuraya** [comment]
go find better wifi connection

**Comment by Observador2** [comment]
Bitter88, I have de same problem but when i use AVAST SECURE LINE (VPN) it starts to work again.  I don't know if my operator network has been IP banished or if they are firewalling the 443 port to 189.91.112.33   or if it is another problem.

**Comment by biggury** [comment]
Same problem here ... If you connect using different IP the problem is gone. This seems to be an IP ban , but after changing the IP time passes and the problem occurs again

**Comment by bitter88** [comment]
It is working now, I turned the internet modem off and on after a bit.

**Comment by Spk345** [comment]
ISPOKEMONGODOWNORNOT.COM
