### ISSUE TITLE
BIG ERROR IN TRASFER POKEMON

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1732]
i had 2 raticates one at cp 681 and iv 84,44% and another at cp 225 and iv 84,44% and when the bot had to chose which one to transfer it did that: https://gyazo.com/7e30b265b24f6624952f1e4e11840737
my settings: https://gyazo.com/565cf2401f18abd6b3d81c4bbb09dbbf

**Comment by Cowering** [comment]
It's only a RAT! but seriously, I wonder if the bot checks attack/defense/stamina separately. your better rat might have been 14/14/15 and the lower rat 15/14/14. Since the checkbox says IV AND CP with IV first, it might have decided attack is more important than stamina.. just a guess though

**Comment by dedos-q-hablan** [comment]
![transfer](https://cloud.githubusercontent.com/assets/21326046/18456264/8c54d14c-791d-11e6-86a0-7852fb6b8e9c.JPG)


[19:08:39] (TRANSFERRED) Arcanine     - CP: 2192  IV:  68.89%  [Best CP: 1483  IV:  77.78%] (Candies: 1764)
[19:09:26] (TRANSFERRED) Graveler     - CP: 1048  IV:  73.33%  [Best CP:  508  IV:  77.78%] (Candies: 1644)

**Comment by aritakino** [comment]
Got same problem. See it many times a day.
It appeared in elder versions too.
 `[08:55:12] (TRANSFERRED) Graveler     - CP: 1139  IV:  60,00%  [Best CP:  840  IV:  60,00%] (Candies: 3)`
![iv](https://cloud.githubusercontent.com/assets/21104689/18463092/661fe124-7990-11e6-9c45-0dbf2b200398.png)

**Comment by Lunat1q** [comment]
yeah, CP is being counted now too, not sure it was in latest released version.
Anyway, don't forget to check your transfer filters lads !:)
