### ISSUE TITLE
[ERROR] Error in Windows 10 1607 x64

### ISSUE THREAD

**Issue by RodrigoFariaSTS** [Lunat1q/Catchem-PoGo#1735]
With little time to use, it crashes and closes..

**Comment by yurius3** [comment]
win6 x64 have the same problem

**Comment by biggury** [comment]
Same problem here...

**Comment by Spk345** [comment]
I love when people says there is an error, but don't tell me what caused the error or if it was an immediate error or anything. If anyone to figure out your error, you have to be more specific.

**Comment by RodrigoFariaSTS** [comment]
... 
The error occurs after a few minutes of use, it simply closes. "An error occurred and the application will be closed"

**Comment by yurius3** [comment]
i ask Hikari in #help but still cannot solve the problem like Rodigo , the bot just run about 2-10mins then crash :
http://imgur.com/ewdvMjK

i dont know what caused the error it just crash like that , i send him  the log he said its fine nothing wrong then download the newest or lower version with default setting still cannot solve the problem
