### ISSUE TITLE
Help me with evolve?

### ISSUE THREAD

**Issue by vfedele** [Lunat1q/Catchem-PoGo#1738]
I want to save candies from good pokes and evolve trash pokes to get xp;
How do I do it? I tried all the logical options, but in the end it ends up evolving ALL pokes (the one in the list and the ones not in the list) or not evolving anyone (when I say NO to all options, only way I found to stop it evolving the one I didnt want too)

I mean, I have a dragonair 100% but I can´t save candies, because the bot keep evolving the dratinis (I tried to select just evolve all pokes above 95 IV, but it stoped lvling pidgeys ( I saved 1500 candies before realising), or I select evolve all pokes with candy, and it evolves all. How can I make it evolve JUST THE ONES IN THE LIST?

**Comment by Spk345** [comment]
Use the pokelist titled "To Evolve".
