### ISSUE TITLE
"Proxy Down? Will try to interact with server anyway"

### ISSUE THREAD

**Issue by s1616ss** [Lunat1q/Catchem-PoGo#1739]
![image](https://cloud.githubusercontent.com/assets/22164187/18461229/67330716-79aa-11e6-8605-411b3c15600a.png)

can't login when I just update my system to windows 8.1...
please help

**Comment by s1616ss** [comment]
and I didn't set any proxy, it used to work just few hour before
![image](https://cloud.githubusercontent.com/assets/22164187/18461402/aecde66c-79ab-11e6-9110-06ea757b3fa1.png)

**Comment by Spk345** [comment]
Um. Are you using google login with your hotmail address... cause uh. I'm pretty sure that's not how it's supposed to work. Are you supposed to be using a PTC login?

**Comment by s1616ss** [comment]
the hotmail account is binding to the google account, I used to log with this account all the time for sure.
and if there's problem with the account it will show another sign. so I don't think it was the account problem.

**Comment by Lunat1q** [comment]
Try to use 2f auth passwords for that, otherwise, there is no problem with Google login for other people. You can try changing google pass.
