### ISSUE TITLE
GPX doesn't work well

### ISSUE THREAD

**Issue by 0M1N0U5** [Lunat1q/Catchem-PoGo#174]
I use gpx file and the bot dont use de route. 

It show me the message:
Unhandled data in GPX file, attempting to skip.

**Comment by HernestoSanchez** [comment]
Hey Bro. Where do i put the gpx file? DO i have to change the name of it in the profile config?

Thanks

**Comment by 0M1N0U5** [comment]
![ruta](https://cloud.githubusercontent.com/assets/11331036/17824678/c6879880-6663-11e6-945a-a64f6842e03f.png)

But it doesn't work well, the bot farm but dont follow the trainer. Therefore I do not know if the bot is actually taking the GPX or are farming back through buildings.
