### ISSUE TITLE
[Feature Request] Minimize to Tray Icon

### ISSUE THREAD

**Issue by Neecoe** [Lunat1q/Catchem-PoGo#1740]
Can the developer, please, work on the 'Minimize to Tray Icon'.

The point is, while im at work, maybe i can minimize it to tray icon especially if i leave my work computer unattended. So that my co-worker wont see it if they want to use my work computer.

Pardon my crappy english, hope it is understandable. :-)

Thank you!

**Comment by necora01** [comment]
and Boss key too ;-)

**Comment by ocraMgyn** [comment]
hello friend you could use WinRAP it hides any application running on your computer.

**Comment by Lunat1q** [comment]
Well, some time later, after all urgent tasks will be done.
