### ISSUE TITLE
[Suggestion] merge database from pcs

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1742]
as the title, it would better if the db that store information from multi bots pc can merge
Just my opinion, what you guys thinks?

**Comment by alanearl** [comment]
Dont know... multiple bots running on 1 ip not recommended.

**Comment by devost02** [comment]
@alanearl not multiple bot/1pc, multiple pc, each have 1 bot

**Comment by Lunat1q** [comment]
LinqPad is all yours.
