### ISSUE TITLE
[Suggestion] route can export 2 share

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1743]
Just to share the route you created with your friends, or the comunity or just from this pc to that pc of you.

**Comment by alanearl** [comment]
Copy catchem.json Paste to another PC.

**Comment by developnoop** [comment]
Or you can copy the corresponding route out of catchem.json (your PC) and paste it to the other catchem.json (Friend PC). Usefull if you want to share just one route or only special routes.

**Comment by devost02** [comment]
i mean, if it could have export/import easy even for some newbies. or i have to open it and copy into other file may have some error in the progress

**Comment by Lunat1q** [comment]
not planned yet.
