### ISSUE TITLE
[Issues] Catchem has stopped working Catchem_1.5.3.0_rc17

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1744]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Catchem.exe
  Problem Signature 02:	1.5.3.0
  Problem Signature 03:	57d59d42
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0eac
  Problem Signature 07:	326
  Problem Signature 08:	10
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by ghostdragon1611** [comment]
yes, i am experiencing that problem too, catchem stops working after about 19 mins running

**Comment by SoniMail** [comment]
Same problem here. So I stoped using 1.5.3.0 and I'm running 1.5.2.1. I can bot for hours and it keeps flawless

**Comment by tryndamerewu** [comment]
same here  new version stops after 15 min get error i am using old version works fine

**Comment by TomWolker** [comment]
same :/

**Comment by petoe93** [comment]
just switch back to 1.5.2.1 until the new release is stable :)
should take 5-7 days i guess

**Comment by Lunat1q** [comment]
Known, already fixed, not yet published
