### ISSUE TITLE
New Poke tab! where is?

### ISSUE THREAD

**Issue by necora01** [Lunat1q/Catchem-PoGo#1745]
I uploaded the Catchem V1.5.3.0_rc17.7z version and I do not see New player tab! and New Poke tab!

**Comment by brocils** [comment]
only smart people can see it  :dancer:

**Comment by j3R3MyRulz** [comment]
same problem and dont see poke spawn

**Comment by j3R3MyRulz** [comment]
any help ? why #5 and #6 aren't showned on bot?

**Comment by yashara19** [comment]
@brocils is right only smart people can see it. stupid person won't see it cause they no use brain. try to read.

**Comment by yashara19** [comment]
@necora01  @j3R3MyRulz no need to thank me
![capture](https://cloud.githubusercontent.com/assets/21163885/18476608/5163e600-79fd-11e6-82c6-f6a0218d9a74.JPG)

**Comment by ArchangelBr** [comment]
it's not released yet....
