### ISSUE TITLE
IP ban using Google Direction API

### ISSUE THREAD

**Issue by SoniMail** [Lunat1q/Catchem-PoGo#1750]
I don't know if it's just a coincidence, but I tried to use Google Directions API key two time and, in both, I got my IP ban for 20-30 min.
Now that I'm running it w/o it, I don't get IP ban.

Does anyone know if it's a confirmed thing or if it's just a coincidence?

PS: I'm running only 2 bots and playing with my phone using wifi

**Comment by tyu366** [comment]
The Google Maps Directions API has the following limits in place:
Standard Usage Limits

Users of the standard API:
- 2,500 free directions requests per day, calculated as the sum of client-side and server-side queries.
- Up to 23 waypoints allowed in each server-side request, or up to 8 waypoints when using the Directions service in the Google Maps JavaScript API.
- 50 requests per second, calculated as the sum of client-side and server-side queries.

https://developers.google.com/maps/documentation/directions/usage-limits
