### ISSUE TITLE
route creator stuck

### ISSUE THREAD

**Issue by c4z4d0r4** [Lunat1q/Catchem-PoGo#1751]
does not work or not create routes for 2 days ago

![screenshot_1](https://cloud.githubusercontent.com/assets/22132105/18475150/b8d802c2-79c5-11e6-86bb-0c3345c5996f.jpg)

**Comment by alanearl** [comment]
Did you check manual route? then build route? then name it then save?

**Comment by c4z4d0r4** [comment]
sure dude, but red lines are straight over houses and sea.
![screenshot_1](https://cloud.githubusercontent.com/assets/22132105/18478644/472729de-79d2-11e6-871b-82a28811ef03.jpg)

**Comment by c4z4d0r4** [comment]
test & error + 1.5.3.0 + "Use mapzen elevation" + Mapzen valhalla routing service =
perfect pathway with single doubleclick or RouteCreator
![screenshot_1](https://cloud.githubusercontent.com/assets/22132105/18481310/0a17d782-79dc-11e6-8355-20a81b5e1e17.jpg)
