### ISSUE TITLE
Pokemon Evolve: IV lvl + Enough candies ( + CP MIN lvl )

### ISSUE THREAD

**Issue by lovelord83** [Lunat1q/Catchem-PoGo#1754]
Hi there, is it normal that version 1.5.2.1 has no function to choose which CP min lvl pokemon I want to evolve? 

It asks for "IV lvl value" and evolve "if you got enough candies"... but it isn't a good idea to evolve a lvl 12 magikarp into a Gyarados only becouse IV is 96% and you got 400 candies, is it?

I suppose that an "AND" condition should be present, something like: evolve all pokemon over "X% IV" AND "if you got enough candies" AND if "CP lvl is over X "

Could you add this feature to avoid unusefull Gyarados lvl 738 CP and a lot of candies waste?

Thanks!

**Comment by Cowering** [comment]
I only do manual transfers and evolves for this reason. Unless you are getting a LOT of pokemon in an hour, you only have to check your bot once every 8-9 hours to transfer all the junk pokemon manually (even at starting 250 pokemon limit).

**Comment by tyu366** [comment]
I check it every half hour and housekeep manually.  I basically marked almost all pokemon as favourite to avoid the fault transfer to ruin my inventory.

**Comment by kilado94** [comment]
Guys im getting a issue, the bot have this option to evolve only the poke we whant, but for me wont work, i tried put low IV like 30% to evolve the Crapy pokes for exp and we evolme the poke i dont whant to like Dratini..magikarp....bug for me or more peopel have?

![image](https://cloud.githubusercontent.com/assets/21318770/18495635/7b3948ca-7a17-11e6-8db3-20f78f3a57f2.png)

**Comment by lovelord83** [comment]
Hi Lunat1q,

Why bug mark ad closed? Is it solved in next release?
