### ISSUE TITLE
[QUESTION] How to use Incense?

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1755]
Hi, as the title say i want to know how to use incense

**Comment by ArchangelBr** [comment]
You can't for while at catchem. It's on roadmap.

**Comment by paura123** [comment]
> You can't for while at catchem. It's on roadmap.

what is roadmap?

**Comment by ArchangelBr** [comment]
it's the "list" where the developers put all the incoming features to the software.

It's already planned, we just need to wait.

**Comment by paura123** [comment]
ok thanks :)

**Comment by M202A1** [comment]
I would like this too.
