### ISSUE TITLE
Catchem with new update!

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#1756]
Hey everyone!

Does any one of you guys using CATCHEM after the new POGO update? If so, please, share with us if everything is working... or not!

Cya.

**Comment by Mordascar** [comment]
the bot needs to be updated. reverse engineering the latest PoGo version + creating the new version of the bot should take around 5 days to a week.

**Comment by kobbey21** [comment]
For now the 1.4.9 is working perfectly for me but when i use the lastest version i get ip ban after a few minutes

**Comment by HernestoSanchez** [comment]
hummm. @kobbey21 , so using 1.4.9 it works but anything after that don´t... I see. Thanks for your feedback dude!

**Comment by TrevorPhilipsBR** [comment]
I found a bug on V1.5.3.0_rc17. After forcemoving, the character come back instantly to same place where he was before  I forcemoved. I think it can be considered teleporting by Niantic.

**Comment by hectom8** [comment]
mine 1.5.2 works fine

**Comment by kobbey21** [comment]
@hectom8 I was about to try that but thanks for the confirmation.

**Comment by kazuki18** [comment]
I am using v1.5.2.1 no issues, still botting fine.
