### ISSUE TITLE
ban ip

### ISSUE THREAD

**Issue by behzad2n** [Lunat1q/Catchem-PoGo#1757]
i cant use . errore ban ip

**Comment by petoe93** [comment]
cool story bro.
how can we help you on that?

**Comment by rivankio** [comment]
Could be several boots running under the same ip, or because the current version of catchem doesnt match current pokego...
mine is running perfectly tho

**Comment by rivankio** [comment]
sometimes when a get a ipban, i reboot my modem, then i start catchem with just 2 or 3 bots

**Comment by wagas** [comment]
soft ban, 1bot = 1ip
