### ISSUE TITLE
[ ERROR IV (maybe)] 

### ISSUE THREAD

**Issue by nghakhoi** [Lunat1q/Catchem-PoGo#1761]
In Catchem v1.5.3.0, Pokemon's IV is different with Old Catchem.

**Comment by petoe93** [comment]
its described in the 1. point (THE FIRST!!!) from the latest stable release 1.5.2.1

> Poke tooltip info update, now display IV for Atk/Def/Sta, **also fixed some IV and Cpm formula**, thanks to @GandalfLeRouge, helping me to sort out all those stuff

its now accurate. close plz
