### ISSUE TITLE
Pokemon transfer

### ISSUE THREAD

**Issue by yagami82** [Lunat1q/Catchem-PoGo#1762]
My setting for transfering pokemon
![image](https://cloud.githubusercontent.com/assets/21980104/18501392/b059d5ea-7a82-11e6-9a07-5de29954bc9d.png)

But it show
![image](https://cloud.githubusercontent.com/assets/21980104/18501410/d06aaba2-7a82-11e6-88e5-30d672ed2058.png)

Currently I have to transfer manually

**Comment by Lunat1q** [comment]
Untick Keep Poke to evolve.

**Comment by yagami82** [comment]
its untick. but it still cant transfer pokemon itself
