### ISSUE TITLE
[Feature Request] Filter by Poke Level

### ISSUE THREAD

**Issue by PincoPallo01** [Lunat1q/Catchem-PoGo#1764]
It would be easier (for the user) to filter according to the poke level (instead of CP). I know I could just set CP filter for every single poke, but it would be really usefull (and a lot less work for the user) to set a generic Level filter for all pokes (like it's possible for CP and IV)

BTW: Wonderfull job !

P.S.: Just realized this request is really similar to "[Feature Request] Evolve/Keep Min CP% instead of raw CP #1709". Even if the aproach it's different, the motivations are the same... have a big poke without spending stardust, waiting for the perfect one.

**Comment by Lunat1q** [comment]
Level is pretty close to CP. So kinda useless.
