### ISSUE TITLE
What does 'Touched a gym' mean?

### ISSUE THREAD

**Issue by M202A1** [Lunat1q/Catchem-PoGo#1765]
Please.

**Comment by iAngelG** [comment]
Just as if you were using your phone, the bot "touched" a gym to see who's protecting it

**Comment by M202A1** [comment]
ok thank you

**Comment by soularrow93** [comment]
it would be great if it could put a pokemon in the gym and collect the 10 coins every day

**Comment by alanearl** [comment]
@soularrow93 Did you try to use gps joy stick :D
