### ISSUE TITLE
Updating Catchem

### ISSUE THREAD

**Issue by wargien** [Lunat1q/Catchem-PoGo#1766]
Hello! I have a question, it is probably stupid but , how you can save settings for new versions of the bot ? I mean parameters of evolution, transfers... and not have to reconfigure everything with each new version. Thank you very much and sotty for my English. Congrats for your excellent work.

**Comment by opidvash** [comment]
U have to copy .json files from \Catchem\Profiles\Bot_name\config\ to keep your settings.
Your routes are saved in catchem.json, located in \Catchem\ or \Catchem\Config\.

Hope it helps.

**Comment by wargien** [comment]
Thank you very much!!
