### ISSUE TITLE
 ddos.win32.nitol.d ?

### ISSUE THREAD

**Issue by Housy123** [Lunat1q/Catchem-PoGo#1767]
https://virustotal.com/de/file/fd4110549e417c7a6dec320ae60451e5f74c4b4ed91266744aa18f011a35e8c3/analysis/1473851508/

Why exactly is this now appearing while scanning the file?

**Comment by Lunat1q** [comment]
It's paranoic cause of encryption.
here is RAW Catchem.exe ![](http://i.imgur.com/C0O1DtV.png)
but in some way... we really ddos Niantic servers :)
