### ISSUE TITLE
What if I ativate new function of 0.37 version but still using elder Catchem like 1.5.2.1

### ISSUE THREAD

**Issue by ccpiloveyou** [Lunat1q/Catchem-PoGo#1768]
If I activate Buddy function and log in elder version like 1.5.2.1, what will the program react? Crash?

I did not try this yet.  Thanks for update.

**Comment by alanearl** [comment]
Hi,

Please try then give us some feedbacks :) 

Thanks.

**Comment by soularrow93** [comment]
im simply waiting for an update

**Comment by Akantinuris** [comment]
Did that with an extra account 1 or 2 days ago, nothing happend yet.
