### ISSUE TITLE
what error is this?

### ISSUE THREAD

**Issue by stevenphen** [Lunat1q/Catchem-PoGo#1769]
![untitled](https://cloud.githubusercontent.com/assets/21276845/18516472/5e94a1b8-7ac3-11e6-9144-30ed7dea1345.jpg)

**Comment by stevenphen** [comment]
i already tried the newest version and same as this error as well

**Comment by Lunat1q** [comment]
i bet it's outdated .net, but you can take a look at system eventlog for exact error, PM me in discord if you will find it.
