### ISSUE TITLE
about the log

### ISSUE THREAD

**Issue by nutcrackdude** [Lunat1q/Catchem-PoGo#1773]
after running the sofware for a day the log ate 35gb of space on my HD

**Comment by johnpeterphoto** [comment]
what is the largest file?

**Comment by Cryptologism** [comment]
Lol... Really dude..
 Im runnimg around 2 and 4 days without stop only 32mb maybe... How come 35 gb space... Lol 
Are u sure it was catchem?

**Comment by AndresAriel** [comment]
just downloaded latest version, for 15 min running, 4,5 mb logs .-. maybe its possible...

**Comment by Cowering** [comment]
12 hours of my log with a single bot is 36K, you have something set wrong :(

**Comment by nutcrackdude** [comment]
i dont know but i deleted it and ran it again and i kept refreshing and its eating about 10mb of space per second all my previous log was only KB in sizes except for sept. 13-14, btw i used 1.5.3 now i redownloaded 1.5.2.1 and its back to normal

**Comment by nutcrackdude** [comment]
i couldn't really tell how i fixed the log problem but its back to normal now
