### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#1774]
![0x7701b727](https://cloud.githubusercontent.com/assets/21315621/18534406/e30f694a-7b14-11e6-8ed6-30ef68e63c1e.png)

**Comment by lelouchvibrittania3** [comment]
here map is empty
![image](https://cloud.githubusercontent.com/assets/21045748/18534422/508b5870-7ac1-11e6-9615-7347e73cb148.png)

**Comment by MaloneFreak** [comment]
Update your .net framework to 4.6.2 :+1:

**Comment by devost02** [comment]
@MaloneFreak already 4.6.2

**Comment by tsnork** [comment]
If you have a crash issue, pls join the Discord https://discord.gg/pPwxX8Q and talk to one of the helpers. They can help you with getting the important information to Lunat1iq
