### ISSUE TITLE
Route Builder

### ISSUE THREAD

**Issue by pcswatertown** [Lunat1q/Catchem-PoGo#1775]
Route builder is not showing stos, pokes or spawn points . Is there something I missed to check . I did try checking" show exact poke on map" 

2nd part of that when new releases come out we move profiles folder and what else .

**Comment by MaloneFreak** [comment]
about the second question, you just paste the profiles folder in the bot folder.

**Comment by pcswatertown** [comment]
Thanks but I meant what else to we move beside profile folder for the database that remembers spawn locations for route builder

**Comment by tsnork** [comment]
You don't need to move anything, just let the bot run for a bit in the desired location to push that information to the database. After that it is available in route builder.

**Comment by pcswatertown** [comment]
thanks 
ok they showed up when i set start point .
 Is there anyway i can loaf data from previous versions of catchem ?

**Comment by Lunat1q** [comment]
CatchemDB in config.
