### ISSUE TITLE
not responding....

### ISSUE THREAD

**Issue by OracleMaster14** [Lunat1q/Catchem-PoGo#1777]
sometimes the program just not function well. its just stop and not responding.

**Comment by MaloneFreak** [comment]
Look in the properties of the archives if they are blocked and unblock all

**Comment by alanearl** [comment]
Reinstall .NET to latest
Disable Anti Virus for testing.

**Comment by tsnork** [comment]
If you have a crash issue, pls join the Discord https://discord.gg/pPwxX8Q and talk to one of the helpers. They can help you with getting the important information to Lunat1iq
