### ISSUE TITLE
The player icon acting weird!?

### ISSUE THREAD

**Issue by ccpiloveyou** [Lunat1q/Catchem-PoGo#1779]
I'm still using 1.5.2.1 cus its quite stable then present.

While the player icon moves toward a pokestop, out of blue, the player icon will "KEEP" moving toward its certain direction without stopping when I shift the program to background back and forth.

It looks like the player just "Stuck" in specific direction without any reaction.  BTW, I DID NOT change and delay in the setting.

Sometimes the player icon just keep moving.....or it will run back to its origin.

**Comment by ccpiloveyou** [comment]
In addition, all mobs that I encounter will flee during.

All abnormality turns into normal while I close the program and execute it again.

**Comment by sinuraya** [comment]
your bot doesn't see a poke stop maybe?

**Comment by ccpiloveyou** [comment]
I could see pokestop on the screen but I'm not sure if the program was working or just stuck.  One more hint, all mobs I encounter during were flee all the time.....yup....

I change to 1.5.3.0 RC2 now and still trying but it seems ok so far.

**Comment by ccpiloveyou** [comment]
My bad. RC2 is still unstable....Crash or No pokestop occasionally. (I am not SOFTBAN!!!)
Change to elder version now.

**Comment by ccpiloveyou** [comment]
FYI, while trying RC2, the player was trying to walk to multi pokestops like "(INFO) Traveling to XXX" but the program just did not respond and the player stunk there.  By restarting Catchem, the program said "No Pokestop in the field....bah bah".  I'm sure I was not SOFTBAN due to I did not move a bit.

Then, I change back to elder version 1.5.2.1 also at the same lat/lng, everything worked normal afterward.  I think elder version is in a way more stable than new version.
