### ISSUE TITLE
Missing Pokeball

### ISSUE THREAD

**Issue by Akantinuris** [Lunat1q/Catchem-PoGo#1781]
HI, first of all thanks a lot for your effort.
I have a question concerning missing pokeballs (the ones which miss on purpose, so the bot looks a little more human).
Would it be possible to program the bot in a way, so it uses normal pokeballs when it does not attend to hit the pokemon. Cuz I run low on Super- or GreatBalls and it is kinda frustrating when the bot then uses good balls (even though I'd have more than enough normal balls).
Thanks again for your work!

**Comment by atact** [comment]
Change the settings to..
Use GreatBall Above Iv : 90 
Use UltraBall Above Iv : 95
-----------------------------
Use GreatBall Below Catch Probability : 0.20
Use UltraBall Below Catch Probability : 0.1 
Use MasterBall Below Catch Probability : 0.05
