### ISSUE TITLE
[Feature Request]Bot Pause if POKEMON continues to FLEE

### ISSUE THREAD

**Issue by hanjers** [Lunat1q/Catchem-PoGo#1782]
Could you please stop or pause the bot if it;s still catching pokemon but FLED due to limit catch per day.
Or if the Pokemons still contunues to FLED 5x or more then the bot will pause/stop since it was reached its limits.

**Comment by iAngelG** [comment]
There's an hourly limit you can set so that you don't reach that catch flee ban. The bot will utomarically pause and then resume. You have to adjust your settings.

**Comment by iAngelG** [comment]
Automatically*
