### ISSUE TITLE
About Eggs Status

### ISSUE THREAD

**Issue by lee02436** [Lunat1q/Catchem-PoGo#1784]
Bot restart after stop by user, the eggs status(Poke -> EGGS) will not display anything.

**Comment by Mingo1** [comment]
same situation here. bot stop and re-start by schedule then no EGGS status
![image](https://cloud.githubusercontent.com/assets/22056811/18547917/8c2ef4a6-7b78-11e6-8bae-cd2dc740c726.png)

**Comment by tsnork** [comment]
It is a known bug and we are working on fixing it. In the meantime switching bot profiles will show the Egg status after some time.

**Comment by dugarila** [comment]
Where do you see the Eggs separator? I can't see that in my version (latest version 1.5.2.1)

**Comment by tsnork** [comment]
You are not running the latest version, pls check here: https://github.com/Lunat1q/Catchem-PoGo/releases/tag/v1.5.3.0

**Comment by dugarila** [comment]
I have that version (although it's a beta release that's why I said the official latest version is 1.5.2.1 - they even say that in the start of the bot), but anyways it still doesn't appear nothing like the screenshot.

**Comment by dugarila** [comment]
Ok I guess I have downloaded that version for like 2 days ago. I always check if there's new version, but since I only peek at the top of the web page and see that release date only keeps increasing I assume that no changes are being made. The alerts of these updates could be clearer.

**Comment by tvoumatev** [comment]
In the evening I put 3 eggs 10 km. Morning checked: no eggs, no incubators, no new Pokémon( check the logs in the Logs folder, hatched only unlimited incubator (. I was searching for information about this and did not find, I'm sorry that is not the topic. 
Bot - super! I have advised all his!

**Comment by Lunat1q** [comment]
Bot refresh eggs during runtime, they should appear in about 1 minute after the start.
