### ISSUE TITLE
[Feature Request]: Proxy Socks v5 instead HTTP

### ISSUE THREAD

**Issue by lovelord83** [Lunat1q/Catchem-PoGo#1785]
Hi Lunat1q, 

could you use a proxy socks v5 (or v4) as alternative proxy connection? A lot of services are easyer to configure and setup with socks (either ssh tunnels) so it could be nice to have an alternative to HTTP proxy that are hard to find (working) .... 

What do you think about that?

Good work!

**Comment by sainttmp** [comment]
you can use software like proxycap

**Comment by Spk345** [comment]
Sslprivateproxy.com which most of us use already utilize HTTPS and Socks5 for their pokemongo proxies. It  is what is needed for catchem to run properly.

**Comment by Quizzyy** [comment]
I was wondering, if someone can show me how to do all this fancy stuffs, Please PM me or comment on my post, Thanks

**Comment by Lunat1q** [comment]
Can't be done without massie API rewrite.
