### ISSUE TITLE
it is dangerous to use the program if my application update to 0.37?

### ISSUE THREAD

**Issue by JhulShock** [Lunat1q/Catchem-PoGo#1788]
I should not use the program until you update

I have the version  Catchem_1.5.3.0_build35_RC2.7z

**Comment by ReidDead** [comment]
I guess it is.
Your game already has the variables of 0.37, like buddy e etc and the Catchem doesn't.

It's just a guess, but better safe than sorry.

**Comment by tyu366** [comment]
I think I should keep the same version for the bot and my phone.

**Comment by xPokemasterx** [comment]
didn't they say it's ok to use the bot until all the world got 0,37 Update?

**Comment by igorpalma** [comment]
I'm using two days
I think there will be no problems until the update tornarse not mandatory

**Comment by eloxxx** [comment]
Be carfull Guys, The new version of pokemon go is worldwide released. 
What does it mean ? 
It means that on all smarphones, if you don't have the last update it won't work, so you have to update.
So if you are botting that means you are playing without having the latest parameters of the game.
They is a big chance of getting flagged !

**Comment by ccpiloveyou** [comment]
Somehow it's fine either in 0.35 or 0.37.

**Comment by Kumohira** [comment]
@eloxxx dude i did a test with Nox & pokemonGo v0.35 and it work. so its not yet Worldwide released !!

**Comment by Spk345** [comment]
Pokemongo apk 0.37 is not yet globally released or globalized mandatory forced update as of yet. I have heard some areas are requiring the forced update, but that is mostly heresay, as perhaps they had auto-update on and their phones updated pokemongo while they weren't looking.

Until all regions are requiring forced update Catchem will still work, just fine. 
Refer to issue 1704 on github.
