### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Miyabi821** [Lunat1q/Catchem-PoGo#1790]
anyone knows me indicates this problem because the bot and can not find pokestps:  (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by nicos1** [comment]
idem problem windows 10 i supose

**Comment by zhach01** [comment]
ip ban

**Comment by Stefanoac** [comment]
ip ban!

reset your modem.

**Comment by nicos1** [comment]
i m not problem for 1.4.9.4 just 1.5+
