### ISSUE TITLE
Can not get bonus for lvl up after lvl30

### ISSUE THREAD

**Issue by hazaiisme** [Lunat1q/Catchem-PoGo#1791]
Can not get bonus for lvl up after lvl30

**Comment by hazaiisme** [comment]
No item received using bot. When I log in use my phone, it will collect all items.(bag will be overloaded)

**Comment by Spk345** [comment]
Use the newest pre-release of the bot. This was an issue with older releases, before you post issues, make sure updating to the newest version doesn't fix you issue.
