### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by Daysmith** [Lunat1q/Catchem-PoGo#1793]
The bot craches, why?

**Comment by velwong** [comment]
Likewise, I faces crashes whenever I click Stop.
![ss02](https://cloud.githubusercontent.com/assets/22225238/18565547/b7cbdbe8-7bc2-11e6-938a-b7dc181c3aa4.jpg)

**Comment by dugarila** [comment]
Yeah for me it sometimes crashes randomly after a few minutes in and I don't know what is the cause.

**Comment by ccpiloveyou** [comment]
Pls use 1.5.2.1 which is quite stable than new one.

**Comment by weronorew** [comment]
I agree. Catchem_1.5.3.0_build35_RC2 crashes frequently. Now I'm using Catchem_1.5.2.1_upd2 which is more stable and it can run for hours. Anyhow, this is still a masterpiece for me. Thanks Lunat1q, you're doing an awesome job.
-Windows 10

**Comment by Spk345** [comment]
Most likely culprit is your Antivirus, there are more three that just utterly hate the new encryption on recent builds. Whitelist the application.

**Comment by Spk345** [comment]
If you continue to have issues, please post a pastebin.org link of net framework error in Windows event viewer.

**Comment by ronetw** [comment]
Use 1.5.2.1 which is quite stable, the new one are crash or not working this time since update

**Comment by un4m** [comment]
still/again crashing when using (probably) more than 5 bots, max. 30 minutes running time. clean windows 10, worked 24/7 with former versions (about a week ago)

**Comment by Lunat1q** [comment]
Show me the exact errors, PM in discord. You can find em in event logs.
