### ISSUE TITLE
Transfering error

### ISSUE THREAD

**Issue by angelaayer** [Lunat1q/Catchem-PoGo#1794]
I set up in config to keep only 2 pokemon duplicated of any pokemon. However i have like 5 or more of each pokemon because bot only recycles items and not transfers pokemon.  Does it has any relation that i change my recycle delay? it was 0.85 by default and change it to 0.9 thats the only thing i change and then bot stops transfering

**Comment by Spk345** [comment]
You are most likely not at 90% full inventory, but even then your manual transfer *should* work, even if you weren't full. Double check your settings, but keep in mind, max limit on Pokemon is 250 in your bag. If you are keeping two of *everything* then that looks like 145×2=290. Well over the limit of max pokemon inventory with storage upgrades.

What also might be happening is that you have the setting *keep all pokemon that can evolve* checked. Or even *evolve pokemon with enough candies*. 

Check over your settings and do the math. Keeping 2 duplicates of all pokemon isn't feasible.
