### ISSUE TITLE
Help to configure evolution

### ISSUE THREAD

**Issue by Allodssss** [Lunat1q/Catchem-PoGo#1796]
Hello, I would like to know what the ideal setting to use the bot to evolve the greatest possible amount of Pokemons accumulating using luckegg. Currently in use Delay Evolve Poke 24276 option in which I saw in a video. Can I change to be faster to evolve?

**Comment by Spk345** [comment]
~25 seconds is an okay evolve delay, I wouldn't go much lower than that because it's not humanly possible, therefore you will flag yourself as a bot. If you don't care, set it to 0 and expect your banhammer.
