### ISSUE TITLE
Transfer filter in V1.5.2.1

### ISSUE THREAD

**Issue by yagami82** [Lunat1q/Catchem-PoGo#1797]
Here is my setting.
![image](https://cloud.githubusercontent.com/assets/21980104/18572572/0c81d436-7bef-11e6-9d71-7e2d8656d21a.png)

Here is my transfer filter setting.
![image](https://cloud.githubusercontent.com/assets/21980104/18572580/24ddb7fc-7bef-11e6-8650-3bb06ffaadbc.png)

Here is the outcome.
![image](https://cloud.githubusercontent.com/assets/21980104/18572604/45f96760-7bef-11e6-977c-e3057b29f5b2.png)

Can anyone tell me what is the transfer filter?how it works?it doesn't overwrite the transfer setting?

**Comment by sainttmp** [comment]
you set "Keep Min Duplicates" = 0

**Comment by Spk345** [comment]
Update to newest pre-release. It was released yesterday. It fixes transfer issues in catchem. 

Also 0 duplicated means none of that pokemon at all. It's a translation error.

**Comment by yagami82** [comment]
you mean 1.5.3.0?
I cant run it.

![image](https://cloud.githubusercontent.com/assets/21980104/18574294/625db2ee-7bfe-11e6-99cb-4e5c9567a048.png)

**Comment by yagami82** [comment]
By the way, it has no issue keeping my snorlax with 80% and above IV. Only those below 80% is transfered.

**Comment by Spk345** [comment]
Try whitelisting it with your antivirus, as the newest release has more secure encryption algorithms due to source theft, and it often gets flagged by three or four antivirus.
