### ISSUE TITLE
Soft ban after 30 mins - 1 hour use

### ISSUE THREAD

**Issue by mizriel** [Lunat1q/Catchem-PoGo#1798]
Hi guys, anyone of you encounter the same problem? after 30 mins or so my bot will only keep moving but without stopping at any pokestop or catch any pokemons. I tried restart my bot the same thing happen. This issue will only fix if i reboot my router, btw this only happen after pokemon go release 0.37 version

**Comment by devost02** [comment]
me too, but only 1/6 bot im botting is softban like that. dont know why

**Comment by ccpiloveyou** [comment]
During a certain of period, all mobs will flee due to SOFTBAN in 1.5.3.0.  I'm not sure why.  But it looks good in 1.5.2.1.

**Comment by alanearl** [comment]
Dont use 1.5.3.0 full og BUGS.
Stable version: 1.5.2.1
1 Public IP per Bot.

**Comment by wagas** [comment]
still using 1.5.3.0 for 2 days straight with no errors

**Comment by lucashtw** [comment]
you may get ban if your ip is different from where you are on the map.
type rumors that it would be strange an ip of France and you are in central park. : D
