### ISSUE TITLE
I witness the faulty transfer again and again but unable to stop after the bot start to running

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1801]
```

[17:48:18] (INFO) Character is too busy, probably you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - IGNORE that message, and don't send git issue!
[17:48:26] (TRANSFERRED) Drowzee      - CP:  733  IV:  75.56%  [Best CP:  732  IV:  60.00%] (Candies: 206)
```

It seems the terrible faulty transfer has not been fixed for long time almost 2 weeks.
The UI just protect itself and run on its fault logic and make the disaster happens.

Does it mean that when the following situation occur, I have to stop the bot. If I stop the bot, the information tab is empty.   I have to use my fake gps in my phone to set to the same location as the bot and then protect the pokemon via game UI.

That is the reason why I hardly get the 'quality' of my pokemon inventory improved unless I protect it first.

**Comment by Lunat1q** [comment]
I didn't get the problem. Can you actually describe what do you want, and show the settings here.

**Comment by caockerman** [comment]
I have seen it as well where better pokemon, i.e. higher CP & IV, are transferred while the lesser poke is kept. I have also seen it where one's with identical CP but different IV and the one with the lower IV is kept.

**Comment by Spk345** [comment]
All bugs and errors with IV and CP prioritization have been fixed in the newest Pre-release. It should prioritize based on *your* selected settings. Are you prioritizing CP or IV or both?

**Comment by alanearl** [comment]
Wrong settings set priority IV only.

**Comment by johnpeterphoto** [comment]
I see on your picture that appears your best has a lower CP and IV.  I do notice that if you have multiple pokemon of the same type incorrectly stating such.  When you do the final transfer of the same pokemon, you will see the highest CP and IV kept for all transfers

**Comment by tyu366** [comment]
both CP and IV

**Comment by Lunat1q** [comment]
fixed.
