### ISSUE TITLE
Tansfer list request

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1803]
hi, if for example i want to keep 5 Charmender that are above 80 IV, and whatever CP, i can't because if i set it like this: https://gyazo.com/aac020faaa60d7ca79e5f79c44a89d54 it will keep every charmender, even if they are with 0 IV.
sorry for my bad english

**Comment by DirkDigo** [comment]
Set minCP to 9999 and see what happens.

**Comment by paura123** [comment]
didn't work :(
