### ISSUE TITLE
[Suggestion] Order routes by name

### ISSUE THREAD

**Issue by elcaporale** [Lunat1q/Catchem-PoGo#1804]
Those of us with a large number of routes will thank you. XD
Thanks for a extremely great job.

**Comment by Lunat1q** [comment]
Order where? route creator? or in selector?

**Comment by elcaporale** [comment]
Both will be great. ;)

**Comment by fdeleo** [comment]
Yes I guess both would be good :)
Also, can you tell me where the routes are saved?
Sometimes I´ve got my routes lost when updating the version in the same folder (The profiles I know are saved since they are in the "Profiles" folder)

**Comment by elcaporale** [comment]
That would be nice.

**Comment by Lunat1q** [comment]
Catchem.json

**Comment by Lunat1q** [comment]
Also routes will be ordered by name during the bot load process :)
