### ISSUE TITLE
[FEATURE request] assigning pokemon to gym

### ISSUE THREAD

**Issue by medoamanquer** [Lunat1q/Catchem-PoGo#1805]
Since the bot can already touch  gyms and displaying its information
can we have something like
Assign Pokemon to Gym 
Automatically have  pokemon assigned to a gym that your team currently controls.

"No battles" only if there is a free spot and it is controlled by your team

**Comment by ArchangelBr** [comment]
@Lunat1q said it won't happen!

**Comment by medoamanquer** [comment]
kindly refer to that post
or qoute it

**Comment by Lunat1q** [comment]
I can repeat.
As soon as i do it, we all will be banned.

**Comment by medoamanquer** [comment]
Thanks
