### ISSUE TITLE
[FEATURE request] Display type of atack and movesets of poke in info

### ISSUE THREAD

**Issue by valdirljr** [Lunat1q/Catchem-PoGo#1808]
Display type of atack in poke info ( for STAB, for example ) and list of moveset about this poke

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/gCdMjAu.png) ????

**Comment by valdirljr** [comment]
Not the type of atack about this poke, but about any Clefable, for example: 

**Moveset**
![image](https://cloud.githubusercontent.com/assets/558397/18600303/532f7ec6-7c33-11e6-936a-6e1651bae6c3.png)

**Attack with info**
![image](https://cloud.githubusercontent.com/assets/558397/18600731/961c4be0-7c35-11e6-91f0-d6d6c2bfd5ce.png)

Moveset will be showed in the bottom of this box
