### ISSUE TITLE
Can't see pokestops

### ISSUE THREAD

**Issue by johntuan** [Lunat1q/Catchem-PoGo#1809]
The pokestops aren't showing up anymore? Get this message (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by islandroad** [comment]
You need to search before you post It's been discussed many times. IP ban try resetting your router.

**Comment by johntuan** [comment]
Is the ip ban permanent?

**Comment by Spk345** [comment]
Ip bans are not permanent but can take up to a day to lift, more often than not, it will lift in 2 or so hours. 

How to avoid an IP ban: Don't run more than one bot per ip address or proxy.

**Comment by Stefanoac** [comment]
No, just reset your modem (Wait 10 second with modem off)
