### ISSUE TITLE
character not moving on the new version.

### ISSUE THREAD

**Issue by renancaluag** [Lunat1q/Catchem-PoGo#1810]
hi guys, first of all great job in coming up the new version it much better and got great stuff in it for the users. how ever my concern was my character is not moving/walking but it was catching poke. i tried to return back to the old version and it becomes walking again. i want to use the new versions as it has a lot of stuff in it. please guide me on how i can make my old config walk on the new version, thank you very much dev team.

**Comment by Spk345** [comment]
Your character does not appear to move while you are catching pokemon or looting pokestops, but as soon as there are no more around your bot will jump forward at a higher pace then usual. If this is not the case, let me know.
