### ISSUE TITLE
 Language  Modified recommendation(for 繁体中文-台湾.json)

### ISSUE THREAD

**Issue by amisrtv** [Lunat1q/Catchem-PoGo#1814]
"%USE_POKE_NOT_TO_CATCH_FILTER%": "使用不抓取寵物過濾器"，->"使用不抓取寵物的名單"
"%RE_RANDOMIZE_DELAY_ON_START%": "重置隨機延遲間隙當啟動bot時",->"當啟動bot時重置隨機延遲時間"
"%IT_S_A_FREE_BOT%": "這個腳本完全免費,如果你是購買的,請立刻聯繫我們",->"這個軟體是完全免費的，如果你是購買的，請立即連繫我們並停止付款"
"%SCHEDULE%": "控制器",->"排程清單"
"%SAVE_SCHEDULE%": "保存控制器",->"保存設定"
"%DESIRED_NICK%": "昵稱",->"腳色名稱"
"%HOST_PORT%": "地址：埠",->"主機連接埠"
"%RENAME_TEMPLATE%": "改名規則",->"更名規則"
"%GREAT_BALL_BELOW_CATCH_PROBABILITY%": "使用Great Ball當抓捕幾率低於",->"使用Great Ball在抓捕幾率低於"
"%ULTRA_BALL_BELOW_CATCH_PROBABILITY%": "使用Ultra Ball 當抓捕幾率低於",->"使用Ultra Ball 在抓捕幾率低於"
"%MASTER_BALL_BELOW_CATCH_PROBABILITY%": "使用Master Ball 當抓捕幾率低於",->"使用Master Ball 在抓捕幾率低於"
"%USE_ULTRA_BALL_ABOVE_IV%": "使用 Ultra Ball 當IV大於",->"使用 Ultra Ball 在IV大於"
"%USE_GREAT_BALL_ABOVE_IV%": "使用 Great Ball 當IV大於",->"使用 Great Ball 在IV大於"
"%USE_BERRY_BELOW_CATCH_PROBABILITY%": "使用漿果當抓捕幾率低於",->"使用漿果在抓捕幾率低於"
"%MAX_CATCH_PER_HOUR%": "每小時抓捕寵物上限",->"每小時捕捉寵物上限"
"%AMOUNT_OF_POKEBALLS_TO_KEEP%": "Pokeballs精靈球保留總數",->"所有寶貝球保留總數"
"%AMOUNT_OF_REVIVES_TO_KEEP%": "保留恢復劑總數",->"保留恢復藥總數"
"%RECYCLE_AT_USAGE_PERCENTAGE%": "回收道具當背包使用率達",->"回收道具在背包使用率達"
"%ROUTING_SERVICE%": "路徑服務",->"選擇路線運算模式"
"%ANDROID_BOARD_NAME%": "安卓主板名",->"安卓主板名稱"
"%FIRMWARE_BRAND%": "固件廠商",->"韌體廠商"
"%FIRMWARE_TAGS%": "固件標示",->"韌體標示"
"%FIRMWARE_TYPE%": "固件類型",->"韌體類型"
"%FIRMWARE_FINGERPRINT%": "固件指紋",->"韌體特徵"
"%DELAY_BETWEEN_PLAYER_ACTIONS%": "玩家行動間隔",->"玩家行動延遲時間"
"%DELAY_POSTION_CHECK_STATE%": "位置狀態檢查間隔",->"位置狀態檢查延遲"
"%DELAY_POKESTOP%": "訪問補給站間隔",->"訪問補給站延遲"
"%DELAY_CATCH_POKE%": "抓捕寵物間隔",->"抓捕寵物延遲"
"%DELAY_BETWEEN_POKE_CATCH%": "兩次抓捕寵物間間隔",->"兩次抓捕寵物間延遲"
"%DELAY_CATCH_NEARBY_POKE%": "抓捕附近寵物間隔",->"抓捕附近寵物延遲"
"%DELAY_CATCH_LURE_POKE%": "抓捕引誘寵物間隔",->"抓捕引誘寵物延遲"
"%DELAY_CATCH_INCENSE_POKE%": "抓捕香薰寵物間隔",->"抓捕香薰寵物延遲"
"%DELAY_EVOLVE_POKE%": "進化寵物間隔",->"進化寵物間延遲"
"%DELAY_TRANSFER_POKE%": "放生寵物間隔",->"放生寵物延遲"
"%DELAY_DISPLAY_POKE%": "顯示寵物間隔",->"顯示寵物延遲"
"%DELAY_USE_LUCKY_EGG%": "使用幸運蛋間隔",->"使用幸運蛋延遲"
"%DELAY_SOFTBAN_RETRY%": "軟封后重試間隔",->"軟封后重試延遲"
"%DELAY_RECYCLE_ITEM%": "回收道具間隔",->"回收道具延遲"
"%MIN_RANDOMIZE_DELAY%": "最小隨機間隔（毫秒）",->"最小隨機延遲（毫秒）"
"%MAX_RANDOMIZE_DELAY%": "最大隨機間隔（毫秒）",->"最大隨機延遲（毫秒）"
"%MONDAY%": "周一",->"星期一"
"%TUESDAY%": "周二",->"星期二"
"%WEDNESDAY%": "周三",->"星期三"
"%THURSDAY%": "周四",->"星期四"
"%FRIDAY%": "周五",->"星期五"
"%SATURDAY%": "周六",->"星期六"
"%SUNDAY%": "周日",->"星期日"
"%POKEBALLS_THROWN%": "拋擲的寶貝球"
"%NOT_TO_TRANSFER%": "不放生的",->"不傳送"
"%NOT_TO_CATCH%": "不抓捕的",->"不捕捉的
"%TRANSFER_FILTERS%": "放生過濾器","->"傳送名單細調"
"%PROJECT_PAGE%": "項目地址 GitHub",->"專案地址 GitHub"
"%DONATE_TO_THE_AUTHOR%": "贊助作者",->"捐贈作者(paypal)"
"%BOT_INFO_BTN%": "bot信息",->"BOT訊息"
"%REMOVE_BOT%": "刪除bot",->"刪除BOT"
"%PASTE_PROFILE_DATA_HERE%": "粘貼數據在這裡"->"在這裡貼上數據"
"%INHERIT_PROFILE_SETTINGS%": "如果你有選擇bot，所有的bot都會繼承此設置",->"所有的BOT會繼承此設定"
"%RENAME_DEFAULT_SELECTED_POKE%": "恢複選擇的寵物名稱為默認",->"還原選擇的寵命名稱回到預設"
"%TRANSFER_SELECTED_POKE%": "放生選擇的寵物",->"傳送選擇的寵物"
"%PREFFER_MAPZEN_ROUTING_OVER_GOOGLE%": "勾選啟用 Mapzen不勾選則啟用 Google",->"勾選啟用Mapzen,不勾選則啟用Google"
"%BUILD_THE_ROUTE%": "創建路線",->"自定義路線"

[TW .txt](https://github.com/Lunat1q/Catchem-PoGo/files/477504/TW.txt)

**Comment by tyu366** [comment]
full list already?

**Comment by amisrtv** [comment]
Wait

**Comment by Lunat1q** [comment]
You can Pull Request it to main repo, i'll accept it :)
