### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by Quizzyy** [Lunat1q/Catchem-PoGo#1815]
Hello, I'm in love with the new update, I just wondering why I have to go from New York to my new location. Is there a way to auto teleport like in the older versions, or do i just have to wait for it to go ever so closely. ~ Thanks

**Comment by Spk345** [comment]
You can change your latitude and longitude before you start the bot.

**Comment by Quizzyy** [comment]
@Spk345 , I'v done that but it still makes me move from Point A to Point B, instead of instinct,

**Comment by alfath2016** [comment]
Zoom out your map by scrolling mouse and find your area. Click your mouse twice in the area you wanted.
