### ISSUE TITLE
[Need Help?] for Translation to German?

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#1817]
If you need Help, i can translate you all in German, let me Know if i can do anything for you.

**Comment by Finrod87** [comment]
It is all done already, u can check it and do suggestions if u find misspelling:)

**Comment by Charlier69** [comment]
Yes i found a lot of hmm ahm not correct translations :-)

**Comment by Finrod87** [comment]
there is a pull request with changes of me. just post there what u still want to change.

**Comment by Spk345** [comment]
Join us in Translations channel in Discord. Thank you!
