### ISSUE TITLE
97.8% IV bug?

### ISSUE THREAD

**Issue by boomer00oo** [Lunat1q/Catchem-PoGo#1822]
I have 8 Pokémon that have 97.8% IV. All of them exactly the same. I have 1 100% IV and then the rest is lower. Is this a bug or something, I find it very strange how I have 8 that are exactly the same IV.

Also,  it's Pokémon* not Pokémons.
https://gyazo.com/5c52ac8d53938e607a6384237fea7343

**Comment by alanearl** [comment]
Try to verify in here :)
https://pogobag.me/

**Comment by boomer00oo** [comment]
Right okay, apparently it isn't a bug, it happens because the stats are 15-15-14 and that causes it to be 97.8. Cool thank you.

**Comment by Spk345** [comment]
It's a rounding of the stats to percentages. It's always going to look weird since there are 15-15-15 max for all stats. All errors and bugs relating to CP and IV correct calculations have been fixed in newest pre-releases.
