### ISSUE TITLE
How can i change Interface language ?

### ISSUE THREAD

**Issue by bitbithk** [Lunat1q/Catchem-PoGo#1829]
Where should i put the file(*.json) ?
thanks

**Comment by Spk345** [comment]
Translation folder is in the Config Folder. Add it to the others, and restart catchem for it to take effect.

**Comment by Spk345** [comment]
It will appear in drop down list in the header.

**Comment by bitbithk** [comment]
No.... i mean Interface(ChineseZH-TW.json) , not bot info language(translation.zh_tw.json)
