### ISSUE TITLE
[Feature Request] Coins collector

### ISSUE THREAD

**Issue by almeidabrunos** [Lunat1q/Catchem-PoGo#1830]
**Just an idea:** everytime the player touch a gym of the same team with a free slot to put a pokemón, put the pokemón with the highest CP. Collect coins everytime you reach a specific number

**Comment by medoamanquer** [comment]
This was the bot creator reply to a similar request
|   I can repeat.
As soon as i do it, we all will be banned.
So, GYM battles, and assignment will not go public.  |

**Comment by Spk345** [comment]
We will not be adding anything to do with Gyms as it shows your Username which will get your account banned by other players (from reporting your username).
