### ISSUE TITLE
Don't automaticaly unfavorite pokes

### ISSUE THREAD

**Issue by picobn** [Lunat1q/Catchem-PoGo#1832]
Hi,

I'm using the lastest pre-release of Catchem and i'm using the "Auto favorite poke" option above IV percentage 90% and "auto transfert" option

I just realised that Catchem unfavorite by itself poke that I manualy favorited (if IV is under %).

Can you add an option to NOT automaticaly UNfavorite pokemon ? (because i lost some poke with the auto transfert option if their were not favorited)

Thanks in advance,

**Comment by Lunat1q** [comment]
If you are using "Auto favorite poke"  - you delegate all control for favorite/unfavorite to the bot.

**Comment by picobn** [comment]
It si possible to plan on a future update to choose if unfavorite fonction is controled by bot or not ?

Thanks for the quick answer
