### ISSUE TITLE
Text Error

### ISSUE THREAD

**Issue by LPBR2010** [Lunat1q/Catchem-PoGo#1834]
In line 95 of file translation.en.json
   {
      "Key": "errorCatchNearby",
      "Value": "Coordinate failure, please check them again!"
    },
I think the Value parameter is wrong...
Please check...
Thank you @Lunat1q

**Comment by Lunat1q** [comment]
yeah, thx :)

**Comment by Lunat1q** [comment]
should be: 
Error during catch process
