### ISSUE TITLE
[Help] No usable Pokestops in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by PowerYT** [Lunat1q/Catchem-PoGo#1838]
Help me plis
In the bot i am in: -33,8611238403292 | 151,21249973774 | 21,2
![f96ed28602cc2c062f74e1191fd4e7fb](https://cloud.githubusercontent.com/assets/21156867/18608472/8350f41a-7cea-11e6-867f-e787a940e99a.png)

**Comment by Spk345** [comment]
You are temporarily IP Banned.

How'd you manage that? 
- You are running more than one bot on one IP address or proxy, at the same time.
- You are using a free proxy or vpn service.

How do you fix it?
- If using your own IP address, reset your router and pray you have dynamic IP address assignment.
- If not, IP bans lift in minimum of 2 hrs, to maximum of 24hrs.
- Don't use free proxies or vpn services. Pay for one, or find a cracked VPN client.
