### ISSUE TITLE
Human Pathing and Routing

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#184]
In my case the bot continue flying over buildings 0.o . Am I'm doing something wrong? Already tested with every option...

**Comment by warleywsc** [comment]
Like this.

![bot_path](https://cloud.githubusercontent.com/assets/13180717/17754039/0bb4900a-64a9-11e6-98e6-2f815ea9a459.png)

**Comment by HernestoSanchez** [comment]
Yup. That crazy bot just go flying to pokestops, even if i forcemove, it refuses to obey me! 0.o
![image](https://cloud.githubusercontent.com/assets/21060440/17754476/16ba0c08-64ab-11e6-9057-f427ba754bdf.png)

**Comment by osxdoc** [comment]
Some times the valve "Altitude Current" raise up at this time vom 11,000 zu 111,000 ... check under Navigation "Altitude Current", it looks like a bug, after using Force Position.

**Comment by HernestoSanchez** [comment]
So... I live at the beach, and here we have an altitude like... 0... even -2 meters below ocean level. I just put alt to 0 or 2... When the bot start running it automatically changes to 8,xxxxx. If i put a much higher value, the message NO POKESTOP NEARBY (And all pokestops vanish)... keeps warning me. :/. By the way, before the update that killed the routing server everything was working perfect. Now im just out of luck. :/

**Comment by kirimkefadil** [comment]
same as me, and more problem when forcemove, my player keep catching ratata when im set not to cath ratata

**Comment by Lunat1q** [comment]
OpenLS - if checked, MobBot routing AND Mapzen will be disabled, bot will try to get route and altitude from Openrouteservice (OpenLS), but it's hightly unstable.

**Comment by HernestoSanchez** [comment]
Sorry but even with that, it didn't work...
