### ISSUE TITLE
Running 2+ bots with the same IP address will probably get you softbanned

### ISSUE THREAD

**Issue by 777sha** [Lunat1q/Catchem-PoGo#1852]
Just a "PSA".

I may be obvious but I think a warning popup when you are creating multiple bots without using a proxy would be great.

**Comment by saltyNaCl** [comment]
Yeah, I can confirm this. I ran one bot for an entire day without problems. When I added another bot, after a few hours, I began to receive a bunch of errors like **Route API key is empty** or **No pokestops available**...

**Comment by HitzJZ** [comment]
I get IP banned for the same reason.

**Comment by kingkai808** [comment]
Proxies are your friend. and make sure they're good proxies with <30 ms ping or else the bot will be slow returning results.  (laggy) if you need proxies i sell them hmu.

**Comment by g00tch** [comment]
Congrats. You pointed out the obvious. You shouldn't need a popup warning. If you're stupid enough to run multiple bots on the same IP, you deserve to be banned.

Fuck protecting innocent players, since botting eliminates innocence. Don't be dumb. Set your 1 bot to play like a human.

**Comment by 777sha** [comment]
> Fuck protecting innocent players, since botting eliminates innocence. Don't be dumb. Set your 1 bot to play like a human.

I know it's a dumb mistake but I think it could potentially avoid a lot of players to avoid being detected as obvious bot users.

**Comment by wagas** [comment]
dont use free proxies

**Comment by kingkai808** [comment]
^^ privates the only way to go.

**Comment by Spk345** [comment]
We are working to update the WIKI and FAQ with the latest information about Catchem.
