### ISSUE TITLE
option  incense and eggs lucky manually

### ISSUE THREAD

**Issue by ingricardopm** [Lunat1q/Catchem-PoGo#1857]
It is possible that the bot uses incense and eggs lucky manually. This means that the person can decide when to use would appreciate all that implement the option

**Comment by NeFShARk** [comment]
Learn to read and to do a search first! It's on the roadmap of the bot already, this and other features to.

**Comment by Spk345** [comment]
Incense will be implemented soon, it's on the #roadmap. It requires a overhaul on the bots UI to get to work.

Lucky egg will not be able to be controlled manually. It's best for the bot to use it for evolving because that is the best use for Lucky Eggs.
