### ISSUE TITLE
Spanish Translations Size, do not show candys to evolve

### ISSUE THREAD

**Issue by HitzJZ** [Lunat1q/Catchem-PoGo#1859]
![candy](https://cloud.githubusercontent.com/assets/22061787/18612408/0232cef2-7d27-11e6-98d3-dee5d062298e.png)

**Comment by TakRiuto** [comment]
Mmmm i can change "Caramelos" To "Dulces" but, is not correct... This is a problem

**Comment by HitzJZ** [comment]
@TakRiuto you're right, "Dulces" it is not the correct translation.

**Comment by Lunat1q** [comment]
ehm... i'll take a look if there is more space for that :/

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/YrAOSvO.png)
done
