### ISSUE TITLE
[Possible Bug] Unexpected Jump

### ISSUE THREAD

**Issue by HitzJZ** [Lunat1q/Catchem-PoGo#1860]
Sometimes, the bot jump to one place on the map without reason. It happen to me 3 times alredy (2 at v1.5.2.0 and 1 today at v1.5.3.0 that i just downloaded). I must have to stop the bot manually when this occurs. 

![salto](https://cloud.githubusercontent.com/assets/22061787/18612422/6df20b30-7d27-11e6-9f0c-b76653eb12f0.png)

**Comment by 777sha** [comment]
Have you tried using a different routing service ?

**Comment by HitzJZ** [comment]
I use mapzen, I don't know if that happen w another services too..

**Comment by Spk345** [comment]
Is this still happening with the newest pre-release?
[Get Neweset Pre-release #54RC](https://github.com/Lunat1q/Catchem-PoGo/releases)

**Comment by alanearl** [comment]
Maybe internet lag? 
Did you check your internet latency when this error will occur?
Im using moboroute & manual route on routecreator so far no problems encounter in routing.

**Comment by Halitz** [comment]
you have put well, the api key? When updating latest versions, change api keys 4 to only 3 remain empty. I will remove myself and I had to put it back.

**Comment by Halitz** [comment]
Mapzen key route used before. now only Mapzen api, change this and no leave empty.

**Comment by Halitz** [comment]
No bug, you just do not look good settings. TOPIC PLEASE CLOSE, THE  BOT PERFECT  RUNNING: THANKS

**Comment by Halitz** [comment]
Y en español pa que entiendas. al actualizar a la nueva version parece ser que la configuracion no se copia bien. La Api key que tenias seguramente se ha borrado, solo tienes que mirar bien la configuracion. Yo siempre guardo una copia de mi carpeta Catchem para comparar y para no perder datos, las rutas las he perdido ya que no me deja agregarlas a las nuevas versiones. No he tenido mas problemas que ese, si necesitas mas ayuda avisa. Le quedan 4 dias a catchem si no actualizan a la version 0.3.7.0, una pena.

**Comment by Halitz** [comment]
y por lo que veo en la imagen, estas en santa monica??? intenta hacer las rutas donde vivas, sabiendo bien donde se mueve el bot. SI intentas sacar veneficio, por tantas cuentas que veo que tienes, te va a salir muy mal amigo. Maximo 3 cuentas por ip o dispositivo y para uso personal. 
Si es el caso, tendras que donar dinero al creador de catchem y trabajarlo bien. 
Los bann son permanentes, los ip bann tambien y si no utilizas proxy un ip bann permanente no te dejara conectarte mas al servidor de ninatic con ningun dispositivo. Un saludo

**Comment by Halitz** [comment]
Si son para uso personal o comercializar, te recomiendo ubicar el bot en una ciudad cercana a tu casa. Ya que si quieres conectarte por movil con su gps vas a tener un bann permanente instantaneo. No es lo mismo moverte 300km que puedes hacerlos en coche en 3-4h (tendrias que esperar estas horas para abrir el pokemon go o softban) Que moverte de un pais a otro. Tienes que actuar lo mas humano posible, ya sea la velocidad, las rutas, la experiencia y el tiempo de juego.

**Comment by HitzJZ** [comment]
Yo copio la configuración que tengo, y obviamente no se copió el api a la nueva versión, y cree una nueva, sólo la del mapzen, y siempre cambio la ip. Uso una cuenta a la vez y cada vez la cambio. Es para uso personal, no para comercializar, uso varias porque si en algún momento me banean alguna, pues tendre las otras, no creo que las baneen todas. Sé usar los bot, soy estudiante de ingeniería, no un simple amateur.

**Comment by HitzJZ** [comment]
I obviously put the the Mapzen api key. My bot it have a good configuration. I dont know if lag is the reason, but my internet connection it is not doing well in fact.

**Comment by Halitz** [comment]
Pues dicho error me a salido solo en el fallo de la api key. Vuelve a Revisar toda la configuracion. Tu conexion a internet no tiene nada que ver, por muy mala que sea la conexion ese fallo viene de las rutas y de la api. Yo uso la misma key que antes sin problemas, solo la cambie de sitio.

**Comment by Halitz** [comment]
Y por mucho que usted sea estudiante de ingenieria, aprenda C++ si quiere saber. Agradezca cualquier ayuda... Yo te recomiendo volver a descargar la ultima version, copiar solo las carpetas Profiles y Config. Si eso no soluciona vuelva a la version 1.5.1.1(Para mi es la mas estable).

**Comment by HitzJZ** [comment]
Yo a gradezco la ayuda, lo que me molestó es que asumiste algo sin saber: "No bug, you just do not look good settings. TOPIC PLEASE CLOSE, THE BOT PERFECT RUNNING: THANKS". Gracias de todas formas. Es algo que me pasó pocas veces y no me a vuelto a pasar.

**Comment by doonotstare** [comment]
![error](https://cloud.githubusercontent.com/assets/22381707/18795767/bf9fc41e-818b-11e6-8796-8c875dcee71e.PNG)
Same error here. Looks like it may be related to piers, I test this going up and down the pier several times, however as soon as i clicked in the upper left side, where there is no 'road' it teleported me back to mainland.
