### ISSUE TITLE
[Suggestion] Choose the poke buddy

### ISSUE THREAD

**Issue by HitzJZ** [Lunat1q/Catchem-PoGo#1862]
I think that will be a great thing!
Thank thank you for your work @Lunat1q ! Your the best!

**Comment by eloxxx** [comment]
Yes but be patient.
For now he is working on the API part of the 0.37 update.
He even hasn't finished the API part yet. 
This part is the most important if you want to run the bot.

**Comment by Spk345** [comment]
#1704 README FAQ ABOUT POGO UPDATE
