### ISSUE TITLE
problemas con las pokeparadas

### ISSUE THREAD

**Issue by ejortizr** [Lunat1q/Catchem-PoGo#1864]
hola quiero saber por que no me ucionan las pokeparadas va de pokeparada en pokeparada pe no sales la exp ni poquebollas ni nada no me sale nada en las poqueparadas porfavor deme una respuesta gracias

**Comment by Halitz** [comment]
Seguramente tienes un softban, espera entre 30min y 8h para que se pase. No utilizes dos cuentas a la vez o mas ya que el ipban puede ser permanente.

**Comment by ejortizr** [comment]
no tego softban por que cuando abro el juego en mi celular funciona todo me
dan las pokebolas la exp huevos de todo pero con el catchem  solo me deja
coger pokemon y los km para los huevos no me transfiere pokemon tampoco
antes me funcionaba muy bien si me pueden ayudar muchas gracias

2016-09-18 18:19 GMT-05:00 Spk345 <notifications@github.com>:
