### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by dreamwalker1232** [Lunat1q/Catchem-PoGo#1865]
is there a way to hav all logs into one single text file ? since i go through the logs for the events i missed i need to open and close each one to find something , so if it was in one text document it would be so much easier ,

**Comment by devgraal** [comment]
With the upcoming database storage, maybe we could imagine to log events there, dont you think ?

**Comment by Spk345** [comment]
All bots have a single logger. All console logs are printed in 1 hour increments for easier sorting. That's not going to change. You best bet: Search the folder with Windows Explorer with the keyword you are looking for. Open the document and Ctrl+F the keyword.

Database storage is already available in newest Pre-Release. It keeps track of when and where you caught pokemon, and pokestops, viewable in Route Creator by setting a waypoint. It shows stops and pokemon in a radius around the set waypoint. Database does not log events.
