### ISSUE TITLE
What Will Happen with this New Update .. ? bot dnot work ?

### ISSUE THREAD

**Issue by shanishkag** [Lunat1q/Catchem-PoGo#1866]
Can we survive using bot with latest update ? its more target to eliminate bots and emulates.. so we should stop now until bot update will come..??

**Comment by devgraal** [comment]
I personnaly go on using Catchem. The sole pb I have is to cumulate candies with my buddy. But we all know that when the 0.37 will be forced on all devices, the actual release wont work anymore.
But, as usual, it's at your own risk.
Regards,

**Comment by Spk345** [comment]
#1704 README FAQ ABOUT POGO UPDATE
