### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by dexxlab** [Lunat1q/Catchem-PoGo#1867]
Is it possible to dump IV values for pokemons ?
Thank you for you response

**Comment by tyu366** [comment]
You can get the list from https://pokeiv.net/ but they have different formula to compute the IV%

**Comment by dexxlab** [comment]
Sorry but I want a text file or CSV with all data ...
The dump file from Catchem is not ok because the delimiter of the CSV is "," and the IV format is 100,00.
I cannot import the csv file in an Access Database because the CSV delimiter and the decimal is the same.

**Comment by dexxlab** [comment]
Idem for HP please ...

**Comment by Spk345** [comment]
You can increase your pokemon listed in config.txt in your profile tab t display on startup and set it to whatever amount and it will write it to your log.
This is the config.txt location, the blanked out box is your bots name.
![Config Txt Location](http://i.imgur.com/25GfoM8l.jpg)



This is where in the config.txt that you would want to change. Change value from 0 to whatever you want.
![DISPLAY ON START](http://i.imgur.com/fFKGN0tl.jpg)

**Comment by dexxlab** [comment]
Sorry but for me, it's not closed, your solution doesn't work. 
I change 0 by 100 but nothing in the log file...

Why do not put more data in the dump files ? 
Thank you for your response.

**Comment by dexxlab** [comment]
Sorry but for me, it's not closed, your solution doesn't work. 
 I change 0 by 100 but nothing in the log file...

Why do not put more data in the dump files ? 
 Thank you for your response.

 


Le 18 septembre 2016 à 22:39, Spk345 <notifications@github.com> a écrit :






Closed #1867.

**Comment by Spk345** [comment]
It displays it in console upon starting get the bot. It does not write to the log without the bot starting up. You have to change that value for every bot you want to display startup pokemon on. If your bot was already active when you made the change, stop the bot and start it again.

**Comment by dexxlab** [comment]
I do that but nothing is display.
Only the best Pokémon  CP and the best Pokemon IV

I have the last Pre-Release 48

Thanks.

**Comment by Spk345** [comment]
I have the newest pre-release #54. This works perfectly for me, and everyone who tested this with me, including someone on your Pre-release.

STEP 1: You need to find the specific bots Config.txt file. This is the normal directory pathing to get to it.
![FINDING CONFIG.TXT](https://s17.postimg.org/xhsa524kv/screenshot_2.png)

STEP 2
You change and save your settings for your specific bot. You cannot save this if your bot is currently in use. So shut down Catchem.exe.
![CONFIG.TXT SETTINGS](https://s17.postimg.org/hi9mli8j3/screenshot_1.png)

STEP 3
Restart the specific bot that you want to check this with, and it will display in console what is *CURRENTLY* on your bot.
![START BOT](https://s17.postimg.org/4gnxvnk4v/screenshot_3.png)

STEP 4
Catchem logs every file by hour, and only has one logger for all running bots. Look for the log in this path directory. Select the hour that you started the bot.
![FIND LOG FILE](https://s17.postimg.org/p3cngz3jj/screenshot_5.png)

STEP 5
Success, it's written to the log.
![ITS WRITTEN TO LOG](https://s17.postimg.org/6mi8q5nlb/screenshot_4.png)

**Comment by dexxlab** [comment]
Ok with release #54, it works but it's not what I want :)


The file cannot be imported to an access database


No data about HP or IndIV for ATK/DEF/STA ...


The level is not perfect too


For example :





In the log the level of my Arcanine is 35


 



But in fact, the level is 34,5, see picture below (same error in the dump file)





And just for my information, what means the field MoveRankVsAveType ?





Sorry but I repeat my question, is it possible to include all data from Catchem in the dump file.


The dump file is the best way to import the data in a database (SQL or Access).



Thank you for your help and for your response.



Le 19 septembre 2016 à 01:41, Spk345 <notifications@github.com> a écrit :






I have the newest pre-release #54. This works perfectly for me, and everyone who tested this with me, including someone on your Pre-release.

STEP 1: You need to find the specific bots Config.txt file. This is the normal directory pathing to get to it.


STEP 2
 You change and save your settings for your specific bot. You cannot save this if your bot is currently in use. So shut down Catchem.exe.


STEP 3
 Restart the specific bot that you want to check this with, and it will display in console what is CURRENTLY on your bot.


STEP 4
Catchem logs every file by hour, and only has one logger for all running bots. Look for the log in this path directory. Select the hour that you started the bot.


STEP 5
 Success, it's written to the log.
