### ISSUE TITLE
(REQUEST) Pokemon IV and CP Calculator

### ISSUE THREAD

**Issue by jaydee9296** [Lunat1q/Catchem-PoGo#187]
I hope the next update this will be added. :)

**Comment by Lunat1q** [comment]
Calculator?  for what? every pokemon have IV already.

**Comment by munchieiam** [comment]
tagging along on this, maybe not a calculator but could you display the CP as ##/##. I notice when catching the pokemon the line displays the CP in this way but on the display tab it only shows the first number.  Intent is to use this along with the IV to know which ones to transfer, evolve, etc.  Or maybe display the CP as a % like IV.  so then you could set the transfer option to transfer anything that has a CP lower than 80% of it's max and an IV of 90% or lower.  To me it would help determine which is truly the best pokemon of a certain type you have caught.
