### ISSUE TITLE
Character icon ?derping? on map

### ISSUE THREAD

**Issue by klaassr004** [Lunat1q/Catchem-PoGo#1870]
Sometimes during walking on the map, the character icon seems to be changing the direction it faces for one milisecond (it kinda looks like its derping), but recovers itself pretty quickly. Dont know if this has something to do with routing or if it is actually the character in the game itself which does this... Sorry if this issue has been reported already, dont really know how to phrase / search for it.

**Comment by eloxxx** [comment]
nothing to worry about that

**Comment by Spk345** [comment]
Have you seen what your legit Pokemongo character does when you are walking around? This is normal.
