### ISSUE TITLE
Keep Min Duplicate 

### ISSUE THREAD

**Issue by Wat3v4** [Lunat1q/Catchem-PoGo#1872]
Hey, 
For some reason this doesn't work..
It always keep only 1 duplicate if the option is chosen.. I tried to put in 2 and it still leave only one of the same Pokemon..

**Comment by eloxxx** [comment]
save your setting close the ap and re-open it ?

**Comment by Spk345** [comment]
Anything on the settings page only can take effect if you save the settings. There is no known bugs with this.
