### ISSUE TITLE
Delay Envolve Poke

### ISSUE THREAD

**Issue by eAngel4V** [Lunat1q/Catchem-PoGo#1874]
When envolving pokes manually, the BOT will do the other actions in a short time(2 seconds)

[20:44:46] (EVOLVED) Caterpie successfully for 500xp
[20:44:46] (INFO) Evolved into Metapod CP: 226 Iv: 66.67%
[20:44:48] (POKESTOP) Name: 溫泉煙霧迷宮 XP: 50, Gems: 0, Items: 2 x ItemPotion, 1 x ItemPokeBall

**Comment by eloxxx** [comment]
I don't see any problem here

**Comment by eAngel4V** [comment]
Delay Envolve Poke = 25001
when envolving a poke at 20:44:46, the next action should be 20:45:11. am i right?

**Comment by eloxxx** [comment]
Yess but here in your exemple this is the same pokemon and it is the same action, Its caterpie which has evolved into Metapod.

This line " 20:44:46 Evolved into Metapod CP: 226 Iv: 66.67% " is not an action, is just an information.

25001 ms is for the next evolution when you set auto evolution.

**Comment by petoe93** [comment]
yeah but in those 25 seconds the bot shouldn't be able to spin any pokestops or so because in the game you have the evolve screen running for 20+seconds which you cant skip as far as i know..

**Comment by eloxxx** [comment]
Ok i got it, but I reckon the 25 seconds apply only for successive evolution and not for other player actions

**Comment by Spk345** [comment]
I have finished evolving and spun a pokestop immediately after. I don't see very much wrong with this.
