### ISSUE TITLE
No transfers the low IV Pokemons

### ISSUE THREAD

**Issue by Gabo048VNZLA** [Lunat1q/Catchem-PoGo#1877]
As it happens stopped the bot to transfer the low IV Pokemons, not if it is a bug or have to do with any change since the update 0.37, if anyone can help me, I would appreciate. Catchem is a great bot!

**Comment by Spk345** [comment]
Depends on your settings. There isn't any reason why the newest update caused issues.
Post screenshots of your settings with your sensitve data blanked out and I can tell you what is wrong with your settings.
