### ISSUE TITLE
[Feature Request] iPhone HW SW emulation

### ISSUE THREAD

**Issue by beloware** [Lunat1q/Catchem-PoGo#1880]
Like Android devices would be nice to mimic iPhone 5-6 series.

Thanks for your work.

**Comment by felipeuntill** [comment]
Duplicated, before create an issue search about it 

#1752

**Comment by Spk345** [comment]
This wouldn't work as Android and Apple have different package files, and different versions. What Catchem uses is APK or Android Package. You can only emulate your android devices.
