### ISSUE TITLE
Ban or Update ????

### ISSUE THREAD

**Issue by meriemDZ** [Lunat1q/Catchem-PoGo#1886]
Hello , please a little help. Thank you in advance

I have this problem from hours . Server not responding because of ban or update ? 
--------------------------------------------------------------------------------------------------------
[21:19:11] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Une exception de type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' a été levée.
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() dans C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 79
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() dans C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() dans C:\dev\Catchem\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:ligne 53
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() dans C:\dev\Catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:ligne 259
[21:19:12] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

**Comment by eloxxx** [comment]
try to connect with your phone

**Comment by Spk345** [comment]
This error is either unstable internet connection or invalid login.

Always check 
[Ispokemongodownornot.com](http://ispokemongodownornot.com/)
