### ISSUE TITLE
Why doesn't catch pokeballs

### ISSUE THREAD

**Issue by Stormito42** [Lunat1q/Catchem-PoGo#1889]
when my pokeballs end they don't catch more at pokestops, they stay warning forever and ever (sorry for bad english)

**Comment by Spk345** [comment]
Have you selected the setting "Loot Pokestops?"

**Comment by Stormito42** [comment]
now  I think I'm a idiot :( sorry for waste your time, but worked, thank you

**Comment by Spk345** [comment]
It's okay, that one honestly was our fault in the older versions because it wasn't checked by default.
