### ISSUE TITLE
Evolving pokemons

### ISSUE THREAD

**Issue by VforVictory** [Lunat1q/Catchem-PoGo#189]
Seems like "Use Lucky Eggs While Evolving" option doesn't work. The bot evolves pokemons, doesn't wait for 15 pokemons to evolve and doesn't trigger a lucky egg.

My settings: 
![image](https://cloud.githubusercontent.com/assets/21092823/17759152/b8c63498-64fd-11e6-85b9-0fb1dbfd514b.png)

Is it a bug or should I uncheck the "Evolve All Pokemon With Enough Candy" button?

Additional info: I have edited the "To Evolve" list before running the bot.

**Update: now I found out, that I didn't have any lucky eggs. So maybe the bot evolves without an egg only when there are no eggs in inventory?**

**Comment by VforVictory** [comment]
Updated

**Comment by Freerider007** [comment]
I do have 2 lucky eggs and it is not using the lucky eggs for me! Maybe it is also possible to use lucky egg (and incence) manually?

**Comment by kingkai808** [comment]
^^^^ yes please eimplement the use of incense and lucky eggs on command by going into inventory and clicking on it to use.

**Comment by Siedjeey** [comment]
Not only that but it should prioritize CP as well when choosing which Pokemon to Evolve. The amount of dust it takes to power up a lower level pokemon to a decent high level, even if it is a perfect IV is not worth it! Can you also implement a setting where we can set the minimum of CP to auto-evolve a pokemon?

**Comment by lucbas** [comment]
From the original NecroBot wiki:

EvolveAllPokemonWithEnoughCandy:
is set to true, any Pokemon listed in the PokemonsToEvolve list will be evolved every 5 Pokestops limited by the number of Pokemon and candies you have. If this is not set, Pokemon will not be evolved based on this list criteria.

Therefore I assume if you want to use lucky eggs, then uncheck this option. 

Regards
