### ISSUE TITLE
[BUG] Poke inventory full when reached 241 still not solved in 1.5.3.0 bld 48, sometimes even 240 

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1891]
The 240 issue is first observed in this pre-release.  I just use this version for 6 hours.
2 times report full on 241 and once on 240.

Just be reminded that if I keep on walking when I have 250 pokes in my inventory and 9 eggs in the incubator, the game allows me to have 259 pokes finally.  This is the rule of the game.

**Comment by Spk345** [comment]
@Lunat1q Could you check over this, or answer this as you see fit?

**Comment by Lunat1q** [comment]
I dunno what is the rule of the game, or what it show to you. But it's SERVER side data.
it's how that 241 number is being calculated: 
![](http://i.imgur.com/DNxnu7l.png)
It will not count in eggs, but that error appear ONLY when you are full of pokemons and it's SERVER side response.

**Comment by opidvash** [comment]
> Just be reminded that if I keep on walking when I have 250 pokes in my inventory and 9 eggs in the incubator, the game allows me to have 259 pokes finally. This is the rule of the game.

Never seen, never heard, never felt. But it makes sense. If u are full (lets say 250/250) and u continue to hatch eggs... What will happen than?

**Comment by Lunat1q** [comment]
Exactly.
So, it's not a bug, stop reporting it please.

**Comment by tyu366** [comment]
>> Exactly.
>> So, it's not a bug, stop reporting it please.
Exactly wrong.

>> Never seen, never heard, never felt. But it makes sense. If u are full (lets say 250/250) and u continue to hatch eggs... What will happen than?

We all know this fact. But I am very sorry to inform you that the game do not operate this way.  I have game screen in #1662 already show solid evident to prove that.  It is 100% a bug which cannot be denied.

Otherwise would anyone can give a feasible explanation to the screen dump

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/6sBYLDf.png)
Do you have ANYTHING else to say?

**Comment by tyu366** [comment]
If you start with fresh new account, 

1\. setup the bot as follows
- stop the auto transfer.
- allow the bot to visit pokeshop to collect eggs

2\. find a route with many pokemon using the poke radar such as www.pokemap.net

3\. let the bot run until you obtain 241 pokes and 9 eggs.  You should find the message in the console tab telling the inventory is full and advise you to setup transfer.

4\.stop the bot

5\.play the game with your andriod phone and catch pokes until the game ask you to upgrade the bag.

6\.check your poke inventory on the phone.

7\.you now ends up 250 pokes and 9 eggs

8\.put 1 2km egg in the incubator and start hatching

9\.try your way to let the egg hatched.  You now have 251 pokes.

**Comment by wabbit1972** [comment]
if you have all 250 slots full of either items or pokes/eggs and you level up or eggs hatch. the server will increase your slots rather than loosing the pokes or items..
I have had this happen to me a few times..
once you use the items or transfer some pokes the slots will return back to 250.
you cannot go over your slots by collecting pokes or items. but if the server gives you items or pokes(eggs hatch) it will go over.

**Comment by tyu366** [comment]
I just have 250/250 pokes and 9/9 eggs.  One of the egg just hatched.  The inventory still show 250/250, 9/9.  The poke just hatch is found to be appeared in the inventory.  
There are 250 pokes shown in the game screen, not 251.  Not sure which is is not shown or gone/lost.  I am not sure the poke will return after I transfer one out.  My game version is the official 0.35.  

Anyway I just document the official game behavior.

**Comment by Lunat1q** [comment]
For fuck sake. I gave you fucking screenshot of the game! where egg was counted in as a pokemon. WHAT ELSE DO YOU NEED?
