### ISSUE TITLE
[Feature Request] Some UI Recommendations & minor feature

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1895]
Player statistics display as popup
![pokeui 2016-09-19_131614](https://cloud.githubusercontent.com/assets/21959374/18623103/cea19d5c-7e6b-11e6-85c7-a5fb08bf418f.jpg)

Resume the item inventory tab (egg inventory moved and consolidated here)
![pokeui 2016-09-19_131649](https://cloud.githubusercontent.com/assets/21959374/18623112/d8edd938-7e6b-11e6-8f11-79b854958d95.jpg)

Multiple level order by, new poke highlight, poke filter
![pokeui 2016-09-19_131731](https://cloud.githubusercontent.com/assets/21959374/18623117/ec0f8c50-7e6b-11e6-97f2-3937b7baaee7.jpg)

**Comment by Lunat1q** [comment]
Now - fit that in 17" 800x600 screen.

**Comment by Lunat1q** [comment]
Also - i see no use in the popup, even if it looks nice, there is SAME info at player tab, with easily accessible.

**Comment by Lunat1q** [comment]
Egg groupup is nice, but still, can't be coded in a good way, cause egg update require an INotifyPropertyChanges event caller, and since you grouped it up -> no object to call it.

**Comment by Lunat1q** [comment]
Baseline - good idea, BUT, you have time sort, it's quite easy to determine which poke was caught, and when

**Comment by Lunat1q** [comment]
What is the point of sort? at the left top? To show some above *X*, aren't sort do the same thing??

**Comment by Lunat1q** [comment]
Also, i don't like moving too much data in tooltips, they are hard to code, and hard to keep em updated from separate parts of code

**Comment by tyu366** [comment]
1. The resolution 800x600 is a standard over 5 years old.  1920x1080 is a basic resolution for today's desktop, notebook and even the little screen of your mobile.  New monitors already have 2k and 4k resolution.

2. I think the work done is much similar to your work in showing the poke detail.   Player tool-tip also means that I do not not to switch to that tab to display the player statistics.  I can still stay on the log/monitoring tab or the poke inventory tab.

3.  I assume you have a routine to consolidate the egg status. Basically when any of the 4 events occurs, you have to call it for a **full** refresh

- when you update the hatch progress 
- when an egg is collected at poke-stop
- when an egg is hatched
- when you put an egg to the incubator

4. To locate new pokemon captured with an inventory of 2xx still take time to sort out manually especially those prefer manual transfer.  Each time, we only need to review those new poke against the old one.  At max., a person can purchase up to 10 bag upgrade.  (i.e. the game maximum is 250+10x50+9eggs = 759 pokes) .  So this is really a big deal.

5. The sorting by #, then IV and then CP will be useful in general.  So highest IV with highest CP show first for same species is helpful.  That is the reason why multiple level sort is required than just single level sort available now.  

**Highlights**
The filtering of poke will help to eliminate those do not need to cater.
For the player tool-tip, you can also show the medals achieved.  It might be difficult but this is one-off work anyway.

**Comment by alanearl** [comment]
Have mercy :( im still using 1366 x 768 resolution. My monitor is still working for 4 years straight... :D

**Comment by Lunat1q** [comment]
1. I disagree, i will not optimize Bot's UI for 1920x1080, a lot of people all over the world using it, and for a LOT of people, 100$ - big money.
2. I don't want to mess with tooltips that much, they are harder to code, harder to maintain, current state of Player stats are good enough.
3. Well, may be it's good, but i have no time to do it anytime soon.
4. I got your point, well, that's possible, but i think i'll do it without colors, but with a new marker or smth
5. disagree.
