### ISSUE TITLE
Error ater login. Login loop.

### ISSUE THREAD

**Issue by Serpantes** [Lunat1q/Catchem-PoGo#1900]
[15:13:05] (ERROR) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoGo.PokeMobBot.Logic.Tasks.UseIncubatorsTask.<CheckRememberedIncubators>d__2.MoveNext() в F:\catchem\PoGo.PokeMobBot.Logic\Tasks\UseIncubatorsTask.cs:строка 223
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в PoGo.PokeMobBot.Logic.Tasks.UseIncubatorsTask.<Execute>d__0.MoveNext() в F:\catchem\PoGo.PokeMobBot.Logic\Tasks\UseIncubatorsTask.cs:строка 63
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.PokeMobBot.Logic.Utils.EggWalker.<InitEggWalker>d__6.MoveNext() в F:\catchem\PoGo.PokeMobBot.Logic\Utils\EggWalker.cs:строка 36
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   в PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() в F:\catchem\PoGo.PokeMobBot.Logic\State\FarmState.cs:строка 51
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() в F:\catchem\PoGo.PokeMobBot.Logic\State\StateMachine.cs:строка 39

**Comment by Serpantes** [comment]
after disabling "use lucky egg while evolving" with value 40 works fine.

**Comment by Lunat1q** [comment]
thx, fixed
