### ISSUE TITLE
Best info shown is wrong in 1.5.3.0 bld 48 when prioritize both IV and CP

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1901]
```
[19:50:59] (TRANSFERRED) Staryu       - CP:  467  IV:  88.89%  [Best CP:  656  IV:  80.00%] (Candies: 700)
inventory contains
CP: 552 IV: 88.9% (Actual best)
CP: 318 IV: 95.6%
CP: 656 IV: 80.0% (reported best)

[19:51:17] (TRANSFERRED) Eevee        - CP:  262  IV:  71.11%  [Best CP:  738  IV:  68.89%] (Candies: 552)
CP: 676 IV: 73.3% (actual best)
CP: 142 IV: 91.1%
CP:  47 IV: 97.8%
CP: 333 IV: 95.6%
CP: 738 IV: 68.9% (reported best)
```
2 cases abstracted for your reference.  Best info always show the highest CP.
As my prior transfer logic shows, prioritize both IV and CP cannot be achieved by means of sorting.  It has to be done by member scanning. Only prioritize by CP or prioritize by IV can be achieved through sorting.

I am not sure whether the transfer logic is correct or not but the best info is definitely wrong.

**Comment by Lunat1q** [comment]
try build 54, i improved transfer logic
