### ISSUE TITLE
Stuck here...

### ISSUE THREAD

**Issue by vjikr** [Lunat1q/Catchem-PoGo#1905]
Please help me fix this..almost 5mins and not working...
![untitled](https://cloud.githubusercontent.com/assets/21979347/18640877/b0772c96-7ecc-11e6-893d-e79240f40176.jpg)

**Comment by icsusan** [comment]
Me too. 

I just created a issue with the same case.

https://github.com/Lunat1q/Catchem-PoGo/issues/1906

**Comment by Cryptologism** [comment]
Try to check your connection... Or restart catchem then run as administrator...  Also dont forget to allowed catchem insdie antivirus or firewall
