### ISSUE TITLE
The bot remove my favourite pokemon

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1907]
hi, if in the settings i set the autofavorite with 90% IV, the bot will automatically remove from the fav, every pokemon above 90% fix this pls

**Comment by Halitz** [comment]
hi, how much has parameter, keep pokemon with min iv% ?? Works well for me, I no longer fit many pokemon and increase to 94%

**Comment by paura123** [comment]
sorry, i mean that if i want to keep a dragonite with 75% IV in my fav, the bot will remove him beacuse i set the IV at 90% and i wan't the bot to not touch the fav that i set.
sorry for my bad english xd

**Comment by Halitz** [comment]
Change parameter, keep pokemon with minimum pc o use not transfer option in settings lists pokemon, add all the pokemon you want are not transferred. It has many options. Sorry for my bad english XP, translate help, Si no español xD

**Comment by paura123** [comment]
i don't really care about cp beacuse i only use pokemon with high IV. and i want those pokemon in the FAV not because i'm scared that the bot will delete them, but because i want to use them in gym battle without searching everytime. sorry for my bad english XP, i'm italian xd

**Comment by ParanoidShadow** [comment]
I have the same problem, I had a dratini of 100% evolved to Dragonair and then it transfer!!! I wanna die now

**Comment by petoe93** [comment]
> sorry, i mean that if i want to keep a dragonite with 75% IV in my fav, the bot will remove him beacuse i set the IV at 90% and i wan't the bot to not touch the fav that i set.

pal you gotta choose, either you want to keep only 90% iv pokemon or 75%.. you can't set the bot to keep 90%+ only and expect it to keep your 75% dragonite..you can't troll bot logic..
you might want to try make use of the transfer list for single, rare pokemon..that might work
or turn off auto fave poke then you'll not have this problem..
