### ISSUE TITLE
 Problem adding a new BOT and set with key Mapzen Build54

### ISSUE THREAD

**Issue by JCCIRO** [Lunat1q/Catchem-PoGo#1910]
Hello

I'm setting up add new Bot in the Catchem_1.5.3.0_build54, but I find myself confused when entering information for elevation Mapzen services, such as by routing Mapzen.

![mapzen_api_keys_2](https://cloud.githubusercontent.com/assets/21242553/18642713/5dc1fefa-7e67-11e6-9c97-1789f407d432.jpg)

There is a change with the use of keys Mapzen in the latest version?

In the version V1.5.3.0 Catchem 35_RC2 build, options are available for each key Mapzen ... See the picture below.

![mapzen_api_keys_1](https://cloud.githubusercontent.com/assets/21242553/18642861/fd925394-7e67-11e6-9843-6e1a89f25e3a.jpg)

Thank you very much for the help.

**Comment by Halitz** [comment]
hi use your previous key is valid alike. Now in Mapzen page you are only given a key type.

**Comment by Halitz** [comment]
Mapzen Keys
You may have noticed some changes to the way our API keys are organized. All keys (existing and new) now grant access to all services, and you don't need to make any changes to your existing keys. Read more in this blog post. https://mapzen.com/blog/unified-api-keys/

**Comment by luaphsv** [comment]
ok nice info

**Comment by JCCIRO** [comment]
OK Thank you very much for the help.
