### ISSUE TITLE
My bot doesn't catch any pokemon, just walk and walk and walk...

### ISSUE THREAD

**Issue by Ragnax** [Lunat1q/Catchem-PoGo#1915]
Well.. it's basically this. Just wak.. whats happening?

**Comment by L3Ente** [comment]
Same yesterday the bot stopped farming and just walk so i stopped it to be saver i wait now for the new update

**Comment by LeMoo07** [comment]
Maybe it's the same issue i have, check your altitude levels please, if they are to high that's the issue.

**Comment by L3Ente** [comment]
the altitude is automatically with the google direction api and it still dont work so i wait for update or maybe the owner just working for some fixes/update

**Comment by Ragnax** [comment]
the altitude is in meters?

**Comment by tophervargas** [comment]
Its is true, the problem is the Altitute, i have the same problem.

**Comment by L3Ente** [comment]
Works now 
Thanks

Min altitude 0
max 15

**Comment by Charlier69** [comment]
But if i was on a high altitude like in Mounatins whats than?

My altitude is 579 and i found Pokestops, if i set 15 max Altitude are this max 15 meter high, in every Citiy you´ll have much timis in this you go more than 15 meter up and down

**Comment by L3Ente** [comment]
i made my own route with route creator and the altitude is 11-15 so i decided to start from 0 i think u can also start with 0 and go than to 600  or 300-600 or 500-600 try it
