### ISSUE TITLE
Mapzen API and OpenLS Routing

### ISSUE THREAD

**Issue by imoutopantsu** [Lunat1q/Catchem-PoGo#192]
Hello! The"Mapzen key" field should let as "mjE32Mko" or "elevation-mjE32Mo"? Should I let the "altitude min/max" fields blank before using the Mapzen API?

What the difference between not using and using OpenLS Routing? Does it helps to trace a better routing and avoid bans?

Thank you for the amazing work! Your bot is doing god works.

**Comment by Lunat1q** [comment]
evelation-######

OpenLS - if checked, MobBot routing AND Mapzen will be disabled, bot will try to get route and altitude from Openrouteservice (OpenLS), but it's hightly unstable.
