### ISSUE TITLE
] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by markfell** [Lunat1q/Catchem-PoGo#1921]
] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?need help keep getting

**Comment by Spk345** [comment]
Check your altitude in your bot, if its normal, then you are probably IP banned. It is temporary, and will lift in a couple hours. You can try and reset your router, and hope that you have dynamic IP assignment. We do not recommend running more than one bot per IP or Proxy, at the same time.
