### ISSUE TITLE
no poka stops

### ISSUE THREAD

**Issue by markfell** [Lunat1q/Catchem-PoGo#1923]
#] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by kkirkk** [comment]
Softban maybe...

**Comment by markfell** [comment]
how I stop this

**Comment by Cryptologism** [comment]
Stop use 10 id in same ip... Or stop tleporting...
How to solve: reset your modem or router...

**Comment by Cryptologism** [comment]
Or for more information #1921
