### ISSUE TITLE
3 more things need for the localization.

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1924]
1. the google map need to switch to associated language.
2. all templates display the log in complete sentence for translation.
3. the item inventory

**Comment by Spk345** [comment]
@Lunat1q this would be up to you.

**Comment by SEEtheREPLAY** [comment]
Hi!  The following error is occurring: No usable pokestops found in your area, but there are usable pokestops.  Strange.
![image](https://cloud.githubusercontent.com/assets/22305508/18654932/cf1af1e2-7eb2-11e6-8a55-bdb40cf0ee76.png)

**Comment by DGLVCY** [comment]
define buddy too

**Comment by Spk345** [comment]
Buddy is not in this APK, that would be 0.37. See #1704

**Comment by Lunat1q** [comment]
Google map switch is up to google, not me.
All templates for the log are done already.
Item inventory translation is planned, no ETA.
