### ISSUE TITLE
[Bug] when the poke inventory becomes full at the console tab and then switch back to the poke tab ...

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1925]
1. The poke inventory table including the count will not be updated automatically .
2. The egg pane is empty.

Has to press the refresh button to resume normal.
(V1.5.3.0 bld 54)

**Comment by Spk345** [comment]
Poke tab refreshes on a set schedule so as to not call too many times to server and get throttling calls. 

Egg pane has an issue with appearing empty and the best way to fix that is to switch to another profile and back. I hope that helps you.

**Comment by tyu366** [comment]
I just sleep while the bot is walking.  When I saw the full message after I wake up, I switch to the poke tab. I do not find the inventory is full until I press the refresh button.  The inventory image is the image before I sleep.

My current work around is to press the refresh button myself.

So to summarize the necessary refresh activity would be
1. when the user switch to the poke tab,   
- the poke tab refresh once (the poke inventory and egg inventory) **(I think this is the missing part)**
- start the timer function to refresh at regular interval 

2\. when the user stop the bot
stop the timer function

3\. when the user press the refresh button while the bot is running
the poke tab refresh once

4\. when the user switch to other tab
stop the timer function.


One side feature that you may consider is to manage the inventory while the bot is not started.
I guess there is no logout activity right now. So it is just one step further by having one more checking.

- **if not login, login now.  <- this is the missing step**
- refresh poke tab

**Comment by Spk345** [comment]
I'm not sure with the first bit honestly,  I will have to test it.

Managing inventory when bot is off may not be possible or a good idea. If he can store it in database maybe, but it could easily get messed up with syncing to server due to many people using their accounts on phones in between using catchem.  That might cause some issues. Also it takes a moment to pull information to catchem from server as is, and inventory  tabs aren't queried right away when you start the bot currently. Mostly focus on GPS and location at startup.

**Comment by tyu366** [comment]
Yes. the reason why we need to use phone between catchem are due to 
1\. we need to go to specific place to catch specific pokes.  The bot will try to visit as many pokestop and catch some other poke even though the poke is straight ahead.   As a result, the poke will disappear before we arrive.
2\.we need to fight in the gym to get poke coins for buying things such as incubator and bag upgrade.

The bot only help us to get star dust and XP.

**Comment by alanearl** [comment]
When pokes numbers will reached 240 the bot will stop evolving. Need to transfer manually around 100 pokes to help the bot.

**Comment by Lunat1q** [comment]
Counts are being refreshed in some bot actions event, there is no other way to do it.
