### ISSUE TITLE
[Feature Request] Catchem + Fastpokemap.se

### ISSUE THREAD

**Issue by ArchangelBr** [Lunat1q/Catchem-PoGo#1927]
Is there a way to "mix" (put to work together) Catchem + fastpokemap.se ?

Maybe could be awesome to use the bot knowing the exact position of the poke

**Comment by Spk345** [comment]
You could make Pokemongo-Map and collect the spawn data, and input it in your database, if that helps you any.

**Comment by Lunat1q** [comment]
That will ruin their API, so much requests.

**Comment by ArchangelBr** [comment]
That would be awesome, @Spk345 ! Too bad I don't know how to code that! 

I agree with @Lunat1q ... but that @Spk345 solution could be awesome to find nests...

Does anyone knows how to do that?
