### ISSUE TITLE
NO usable Pokestops found in your area. Is your maximum distance too small? & Mapzen Valhalla API Key is Empty

### ISSUE THREAD

**Issue by MasterJared** [Lunat1q/Catchem-PoGo#1929]
please help me how to fix this

![image](https://cloud.githubusercontent.com/assets/22312176/18657795/20e459f0-7f30-11e6-8de8-d79a2e0d5456.png)

**Comment by Spk345** [comment]
I LITERALLY JUST REPLIED TO YOUR LAST ISSUE. READ YOUR EMAIL. DO NOT REPOST.
