### ISSUE TITLE
[Possible Bug] The app crashed. Most of my items and pokemons were gone.

### ISSUE THREAD

**Issue by s3c0ndt0n0n3** [Lunat1q/Catchem-PoGo#1930]
> Device: ASUS UX305FA
> Environment: WIN 10 64-bit (1607)
> App Version: V1.5.3.0 build 54

My Catchem app on the above device has crashed 3 times. Every time I restarted the app, I found most of my items and pokemons were gone... orz...

BTW, I go see the LOG file and it doesn't have any record that my items were recycled or my pokemons were transferred...

However, I tried another computer and it didn't have this problem yet (hope it won't happen). 

> Device: Lenovo ThinkPad E450
> Environment : WIN 10 64-bit (1511)
> App Version:  V1.5.3.0 build 54

Hope someone could help me...

**Comment by L3Ente** [comment]
thats not possible maube subednke pranked u

**Comment by L3Ente** [comment]
maybe*

**Comment by Lunat1q** [comment]
I think you tried to do a shit with my bot, it's bot self defense system against GetGo assholes. Enjoy it.

**Comment by s3c0ndt0n0n3** [comment]
Well... I just reported what I've encountered
Normal setting... and I don't know about GetGo until you tell me
Thanks.
