### ISSUE TITLE
[Feature Request] Evolve Selected Pokemon + Transfer

### ISSUE THREAD

**Issue by shaybogomoltz** [Lunat1q/Catchem-PoGo#1931]
Hi,

I'd like to suggest some feature that could be useful. When we are farming (without lucky egg), we usually use a lot of Pidgeys + Caterpies + Weedles. So for that, I basically wait until I have about 30 or 40 and evolve all of them together. But after the bot finishes his task we have to select all of these pokemons again just to transfer them. So I was thinking that could be nice if we have one button that could some up those 2 activities in once.

**Comment by Lunat1q** [comment]
sorry, that can cause more troubles then help.

**Comment by ArchangelBr** [comment]
You can select more than one using control or shift and do it once...
