### ISSUE TITLE
Buddy system working... But not hatching eggs

### ISSUE THREAD

**Issue by RandomGiHu** [Lunat1q/Catchem-PoGo#1933]
As I start the bot, it tells me the "egg status"... 

Putting egg in incubator: X,XX km left

But thats only when I start the bot... From that moment on, I don't get any egg status update info or distance I've walked.

On the other hand, the kilometers I've walked are counting for my buddy, as when I close the bot, and open the app on my smartphone, I get the buddy candies from the kilometers the bot walked...

Anyone having the same issue?

**Comment by Ononolaus** [comment]
Did you make sure your walking speed is under limit for hatching?

As of now I can hatch eggs walking at 15 or even 20km/h both using Catchem or manually at Nox(v0.35), but one of the nerfs of the new version is the drop to 10km/h max speed for hatching.

Maybe for having already logged in the game v0.37 on your phone you can't hatch eggs at higher speeds anymore, even using Catchem.

**Comment by RandomGiHu** [comment]
My walking speed is between 15 (min) and 18 (max)...

I noticed now that eggs are hatching, however I'm not getting any info update about the distance they have left, as we used to get before.

Suddenly, I relogged and I got a message saying that an 5 km egg had hatched (goldeen)... And a new 10 km egg started to hatch.

Not sure if this is a bug or not... Maybe it's a new feature that won't tell you about the egg till it hatchs.

**Comment by Spk345** [comment]
Your speeds are too fast to hatch eggs, you need to be under 12 for it to update reliably. I honestly haven't had any issues with this, but your egg incubators will give you updatesome when your bot is not in middle of something  (like no pokestops or pokemon nearby).

I have pokebuddy assigned to the bot I am running currently and it is updating correctly.

**Comment by tyu366** [comment]
I set the speed to 2x in console tab and I think the speed will be over 12 (min speed is 6). And so I expect no eggs hatched.
I set back the speed to 1x and let the bot walk for a while, still nothing update in the egg status.

**Comment by Bay101** [comment]
The updates in the console are not showing as they are most likely not called for, just check the poke page as it has a list of all eggs and their current status

**Comment by Cruilowa** [comment]
I'm having trouble with my pole buddy and the candies, it says i have walked 31km but i only got like 15 candies, is there anything i can do?? btw I'm walking a magikarp
