### ISSUE TITLE
The program does not open - 1.5.3.0

### ISSUE THREAD

**Issue by andregauda** [Lunat1q/Catchem-PoGo#1939]
I'm trying to run the latest version (1.5.3.0) but the program is not opening. Version 1.5.2.1 opens normally.

I found nothing about this error in this release in closed problems.

Windows 7
.NET 4.5.2

Here is the log:

Signature of the problem:
  Problem Event Name:	CLR20r3
  Signature of the problem 01:	Catchem.exe
  Signature of the problem 02:	1.5.3.0
  Signature of the problem 03:	57defeb1
  Signature of the problem 04:	System.Data.SqlServerCe
  Signature of the problem 05:	4.0.0.0
  Signature of the problem 06:	4fcd17f1
  Signature of the problem 07:	da
  Signature of the problem 08:	1d1
  Signature of the problem 09:	System.Windows.Markup.XamlParse
  Operating System Version:	6.1.7600.2.0.0.768.2
  Location Identification:	1046
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Thanks!

**Comment by andregauda** [comment]
Here's a print, to help.

![image](https://cloud.githubusercontent.com/assets/12765680/18680173/ffbedbc0-7f38-11e6-936d-56856a030166.png)

**Comment by Spk345** [comment]
So... this is now the second incident of this problem... what's happening is that the database is failing to initialize. The thing is, all the ms dlls required to run database are including in the download.

We've been trying to figure out the issue but as of right now we've had not much luck. 

I'm guessing you have 64 bit windows correct?

**Comment by Spk345** [comment]
https://support.microsoft.com/en-us/kb/974247

This is the Microsoft article on it. That's about as much as we know so far.

@Lunatiq

**Comment by andregauda** [comment]
Correct, Win 7 - 64 bits =\
In my notebook win10 64 bits the program open but close after some minutes.

**Comment by Spk345** [comment]
Can you join us on discord server? I want to speak with you further about this matter.

**Comment by andregauda** [comment]
The version before that Works fine. Can i get some file fron that installation to make a test?

**Comment by andregauda** [comment]
Sure! But not now. Maybe in 2 hours. That's ok?

**Comment by andregauda** [comment]
I will not be on computer with win7, but with my notebook with win10

**Comment by tyu366** [comment]
my ultrabook is also 64-bit win10.  the bot is working.

**Comment by Spk345** [comment]
This issue is your sql ce is failing to initialize. Therefore yes, 1.5.2. Will work because it doesn't have the database feature, 1.5.3 won't.

**Comment by Bay101** [comment]
Please make sure that when you install the bot that you extract all of the files in the archive, It looks as if the required dll files are missing. If that is the case please reinstall with all files extracted to the folder.

**Comment by Nicolassssss** [comment]
WIN7 64bit-crash when editing manual route.

**Comment by kelsondaleph** [comment]
Same too me =(
Any idea ?

**Comment by andregauda** [comment]
Hi @Spk345 
I will enter the discord server. I'll be on the computer with the problem for over 1 hour. Then I'll be here only on Monday.

**Comment by andregauda** [comment]
Sorry! I thought it was a forum, I have no microphone here in my office and did not speak English very well. =(

What information do you need?

**Comment by Spk345** [comment]
I'm not sure there is anything I can do for you. It appears to be an issue with your Windows and reading the SQL CE DLLS necessary to form and run the database.
