### ISSUE TITLE
GetDataFromYourAndroid

### ISSUE THREAD

**Issue by D4D3Z** [Lunat1q/Catchem-PoGo#194]
Hi there,
that won't work.
any chnce to fix it ?
Good work guys
D

**Comment by Lunat1q** [comment]
That works fine. http://lmgtfy.com/?q=How+to+make+adb+works

**Comment by NiXoNII** [comment]
Hey, im New on Github and im german so my english is very very bad.

I have make a Tut from ur Bot, but i need the German info for the Users how the Divice Option.
(So all can write her own divice infos)

And a other lil thing is, i hope u add the button "SELECT ALL" in the Pokemon list to select all pokemons to evolove.
