### ISSUE TITLE
problemas con las pokeparadas  y la transferencia de poemon

### ISSUE THREAD

**Issue by ejortizr** [Lunat1q/Catchem-PoGo#1943]
hola  necesito una ayuda tengo la ultima actualización de catchem la 1.5.3 pero no me deja recojer nada de las poeparadas no me dan  exp ni poquebolas ni huevos ni nada ayuda a alguien mas le pasa esto   y si entro en el juego en el celular si me dan en las  pokeparadas  pokeball  y exp  huevos y de todo pero con el catchem no y tampoco me transfiere los pokemon solo me captura si tego pokeball y me recorre km para los huevos el va de pokestop en pokestop pero no me dan nada los pokestop

**Comment by angelaayer** [comment]
fijate si tienes activada la opcion loot pokestop y para que transfiera debes quitar las opciones de keep poke that can envolve

**Comment by stark93** [comment]
Usas la misma IP tanto en tu celular como en tu computadora? Si es distinta tal vez tengas IP ban en tu PC por eso no puedes recoger pokeparadas, revisa también la configuración de tu bot tal como lo dice angelaayer

**Comment by ejortizr** [comment]
angelaayer Las dos las tego desactivadas  stark93 como se si uso la misma
ip en celular  y en mi pc por que los dos los tengo coneptados al mismo
wifi pero en el pc no me recoje nada pero en mi celular si que puedo hacer
gracias por audarmen

2016-09-20 15:29 GMT-05:00 stark93 <notifications@github.com>:

**Comment by kevindevm** [comment]
loot pokestop la tenes que tener activada para que agarre items de las pokeparadas

**Comment by ExequielGC** [comment]
lo mas probable es que no tengas activada la opcion "Loot PokeStops", la encuentras en "Settings"

**Comment by ejortizr** [comment]
kevondevm muchas gracias era por eso ya lo estoy probando ahora falta por
que no me quiere transferir los poemon


2016-09-20 16:06 GMT-05:00 kevindevm <notifications@github.com>:
