### ISSUE TITLE
Auto Favorite also means Auto UnFavorite?

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1950]
Hi,
I check option Auto Favorite for poke with IV higher than 98.
but, it also Auto UnFavorite all pokes that I manually choose as Favorite (I choose them for other reasons like moves and others. not only IV or CP)

please advise

**Comment by HitzJZ** [comment]
The same happened to me!

**Comment by saldotman** [comment]
and once they are UnFavorite, they are easily (mis)transferred

**Comment by nwchong** [comment]
I have the same issue as well, and my perfect moveset Vaporeon was being transferred because of this. :(

**Comment by tyu366** [comment]
Yes.  I experience the same issue and result in mis-transfer.  So it is dangerous to turn it on especially when you are using the favourite to protect from incorrect transfer.

**Comment by Bay101** [comment]
So this is the auto favorite Pokemon under the settings list?

**Comment by Bay101** [comment]
I just added another setting to fix this issue that you are having, should be in the next release :)
