### ISSUE TITLE
(ATTENTION) Encounter problem: EncounterClosed

### ISSUE THREAD

**Issue by angelaayer** [Lunat1q/Catchem-PoGo#1955]
First time I see this. Should I worry about it? I bot in my city and only have one account running never used more than one.
![pic](https://cloud.githubusercontent.com/assets/21321158/18698212/f2da7716-7f8d-11e6-8fd6-7aed839f1e3e.jpg)

**Comment by Bay101** [comment]
what version are you on?

**Comment by angelaayer** [comment]
latest one. v.1.5.3,0 build54.7

**Comment by Spk345** [comment]
Sometimes this happens when the pokemon despawns. It's not a flee, it just kinda... disappears. Happens in legit POGO too.

**Comment by Spk345** [comment]
Pokemon spawns are only active for 15 minutes or so.
