### ISSUE TITLE
Bot transfers by ivs while Prioritize IVS over CP disabled

### ISSUE THREAD

**Issue by M3m3s** [Lunat1q/Catchem-PoGo#1958]
[08:10:18] (TRANSFERRED) Drowzee      - CP:  641  IV:  51,11%  [Best CP:  338  IV:  60,00%] (Candies: 72)
http://prntscr.com/ckhr84
Please help

**Comment by Spk345** [comment]
You do realise that your transfer settings are for *1500 cp* and *70%* IVs? I mean that pokemon is not hitting the minimums you set on either of those... so bots doing what it should. It's transferring it.
