### ISSUE TITLE
Human Pathing and Routing

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#196]
Hi! someone closed my post but still.. It´s not working... Already changed all routing options, servers etc, and it still fly over everything... OPENSl, MAPzen, whatever, it´s not working :/

![image](https://cloud.githubusercontent.com/assets/21060440/17764232/6efab14e-64f4-11e6-8eb2-78a31c5fc4bc.png)

**Comment by oZacDo** [comment]
I test the first version (v1.3.0.1) with human pathing.
It also does't work.
Maybe something wrong ...

**Comment by itterror** [comment]
Routing in italy has problems, but thats not in the hand of the creator

**Comment by jarlave** [comment]
Have the same problem in germany, PokeMobBot it works, but at Catchem not.

**Comment by Doedelidu** [comment]
Can definetly confirm this.
I got Path discovering and human pathing on true and tried with or without OpenLS the bot does not use any pathing whatsoever.

**Comment by mystique47** [comment]
same here. in pokemobbot it works. in catchem it worked once, but restarting the exe it didn't work anymore

**Comment by Lunat1q** [comment]
Mobbot routing is unstable too.
