### ISSUE TITLE
[Feature Request] Use Lure Modules

### ISSUE THREAD

**Issue by Liframe** [Lunat1q/Catchem-PoGo#1961]
Hi! Would it be possible to add this feature wherein we can force walk the bot and set up a lure on a certain pokestop? Or if possible, be able to auto-lure the stop whenever the lure runs out so we can pretty much camp the bot in a spot and avoid too much movement which could trigger suspicion. Thanks!

**Comment by Spk345** [comment]
Good news! You can already do this!

Right-click on a Pokestop you want to Lure in your Map & Console and the bot will force-move to the location of Pokestop, then set your speed factor all the way down to 0.000001.

You cannot auto-lure the spot. You have to manually set it. 
Another **GREAT** thing to remember is that by setting a lure **YOUR BOTS NAME is VISIBLE**. So keep that in mind, as you can get **banned**. :)

**Comment by Liframe** [comment]
Cool! Never knew it was already possible. May I know starting at what version this feature is available? Thanks!
