### ISSUE TITLE
Egg Incubator not working.

### ISSUE THREAD

**Issue by donder1991** [Lunat1q/Catchem-PoGo#1966]
My egg incubator starts when i start the bot, but when i walked the 5km it dont picks an new egg.
after is stop the bot and click start again he wil pick a new egg. can somebody help me with this problem?

**Comment by Le0n0r1976** [comment]
A mim acontece o mesmo
Percorre 1 Km depois volta a 0
Não entendo

**Comment by Lunat1q** [comment]
62 build fixed
