### ISSUE TITLE
[Request] Change Pokemon Buddy

### ISSUE THREAD

**Issue by OracleMaster14** [Lunat1q/Catchem-PoGo#1968]
just a suggestion guys.

a menu that change the poke buddy 

or 

a schedule or max candy for particular pokemon then switch to another pokemon.
(like snorlax = 100 switch to dratini) if posible... thanks :)

**Comment by ArchangelBr** [comment]
the current version is not ready to buddy yet... the new one is comming.

**Comment by Cryptologism** [comment]
We are concetrate to API first.. First thing first dude... those already been added into FarPlan
