### ISSUE TITLE
Transfer bug?

### ISSUE THREAD

**Issue by poopfeast42** [Lunat1q/Catchem-PoGo#197]
this happened

(TRANSFERED) Pinsir	- CP: 435  IV: 94.6%   [Best CP: 1151  IV: 100%]

and these were my settings

![21eqwd](https://cloud.githubusercontent.com/assets/20999375/17765024/4b46ca88-64f1-11e6-8bb1-7b708abb7c1f.png)

**Comment by port1991** [comment]
hey author how do i contact you for developing the bot????

**Comment by port1991** [comment]
author if you can read this, you should add an option that says " do not transfer any pokemon" sometimes we just want to pick pokestops. :)

**Comment by poopfeast42** [comment]
also a side note the stardust section under information isn't updating properly, the blue number stays the same on the ui until you restart it

**Comment by poopfeast42** [comment]
didnt realize someone already posted it
