### ISSUE TITLE
[Request] Item manual use

### ISSUE THREAD

**Issue by viciousnake** [Lunat1q/Catchem-PoGo#1970]
Hi, if it's possible, can you add the use of Lucky Egg, Incense or Incubator from the Item panel? 

Thanks

**Comment by ArchangelBr** [comment]
it's on roadmap... we need to wait

**Comment by viciousnake** [comment]
Is there a link to see roadmap? I have another ideas but maybe they are repeat.

**Comment by petoe93** [comment]
https://discordapp.com/channels/212977806819196938/213539926250225665
