### ISSUE TITLE
Stop catch pokemons and pokestop

### ISSUE THREAD

**Issue by Taqzoito** [Lunat1q/Catchem-PoGo#1976]
Bot stop to catch pokemos, eggs distance don't change and pokestops gone from the map.

**Comment by kkirkk** [comment]
Maybe softban, w8 sometime and relog.

**Comment by kkirkk** [comment]
Always happens to me too :tongue:

**Comment by Taqzoito** [comment]
same account in my cellphone works perfect

**Comment by Sadi68** [comment]
I also have this problem. He just goes around, finds Pokestops, doesnt do anything!

**Comment by markfell** [comment]
This also happens to me all time

**Comment by tophervargas** [comment]
I also have this problem, I just notice that the Altitud it configures bad, example have to be 10 o 11, but it put in 1167mts Wtf ? I done everything, I use before Mazpen Api Routing, then Changed to Google Directions and works well just for a while, after 1 o more dont find anything.

**Comment by Lunat1q** [comment]
No ptoblems with 62 build bot. So since no extra info given - closed.
