### ISSUE TITLE
[Feature Request] Loot Pokestops + Catch Poke on Map & Console

### ISSUE THREAD

**Issue by ArchangelBr** [Lunat1q/Catchem-PoGo#1977]
I would love to have a button (that is already in settings, I know...) to Loot Pokestops and Catch Wild Poke on Map & Console Tab.

I explain: In my city there is not much pokestops, so I run with no pokeballs (or just a lil bit) very often.

What do I do: I let the bot walk in my neighborhood to count my km for eggs and follow what is spawning in fastpokemap.se.

If I find something that worth a pokeball, I "check" the button to catch wild poke (don't need to save settings, I see this). But I have to do it many times and allways scrool the bar at the botton of settings and then check/uncheck.

If it was on map & console tab, I could do all in one place. This could be just a "mirror" from those who are already on settings... 

Could I explain ? Sorry for my bad english.

**Comment by kkirkk** [comment]
Change your 'not to catch' settings to dont waste pokeballs, its better.

**Comment by ArchangelBr** [comment]
@kkirkk could not get it... could you explain ?

You say to put the "miss chance" setting in 0 ?

**Comment by kkirkk** [comment]
In 'Pokemon list settings' tab > 'Not to catch' pokemon filter
Set pokemons that u dont want (pidgey, caterpie, weedle.... ), then bot doesnt waste your balls.

**Comment by ArchangelBr** [comment]
Thanks for your help, but that was not what I would like to do...

Think: Tomorrow, I want would have to remove all from that list again.... and put then there again.... terrible!

**Comment by kkirkk** [comment]
I see your point, but i think that is the easiest way. :smile:

**Comment by ArchangelBr** [comment]
Between this and the other one (the method I do today), I keep with the actual. But thanks for your help!

Maybe it's not so hard to implement this on the source.

Let's see if lunatic understand.

**Comment by Ononolaus** [comment]
I got the point of having a mirror of "catch wild poke" and "touch pokestop" at map tab. In fact, I do something similar, if I locate anything worthy near my current running bot via pokemesh, I do a force move to that place if its in the time range to walk there. But if I don't disable both option forementioned the bot will stop to catch and spin, making this strategy impracticable.
This practice is very similar to walk snipe from necrobot, that when given a mission, the bot will carry it straight out with no interruption.

**Comment by Finrod87** [comment]
so u want an option, that while u forcemove he doesnt catch pokemon and loot stops until he is at the target?

**Comment by Lunat1q** [comment]
Well, i don't like duplicate functions on different tabs, it's 1 click, see no problem do 1 extra click.

**Comment by ArchangelBr** [comment]
@Ononolaus That's almost this!
@Finrod87 not exactly... but could be used to do this too...  The deal is that I have to click on settings, uncheck, go to Map & Console... after do the same to check again... it's just a way to be easier, but I could not convince @Lunat1q !
Maybe I should send some flowers! LOL

**Comment by ArchangelBr** [comment]
@Lunat1q the "problem" is not the "one extra click", it's the facility to do everything you need at the same tab, since we already have the speed factor on that tab too. In this case, we didn't need that button too, once it's controllying the speed, that is already on settings (kind of mirror function too, in certain way).

I agree that mirror button could confuse some "newbie users", but could give us the oportunity to do everything about "walk, loot and catch" at the same place!!!

Could you think about it ? If I send you some drink could you think a lil bit more ? LOL just kidding!
