### ISSUE TITLE
Sou noob nestas andanças

### ISSUE THREAD

**Issue by Le0n0r1976** [Lunat1q/Catchem-PoGo#1978]
Já tenho a API key.
Funciona direito. Acontece que em 1 hora apanhou 3 Pokemons
Tinha três Ovos a evoluir faltavam 3 Km. Agora depois de 1 hora faltam 4 Km.
Não entendo.
Outra dúvida.
Não é possível entrar em ginásios para combater ou treinar ?
Abraço e obrigado

**Comment by kkirkk** [comment]
Ainda nao eh possivel entrar em ginasios, no bot soh mostra o aviso sobre eles.
Esse negocio dos ovos, se puder postar o log... talvez ajude.
Quanto aos pokemons nao sei kk 
(ps: teclado bugado sem acentos. bjs)

**Comment by mucro9** [comment]
Stop fucking stranger lang...Here ONLY ENG
