### ISSUE TITLE
gems & information

### ISSUE THREAD

**Issue by wakenabom** [Lunat1q/Catchem-PoGo#198]
hi, just a few question.
1) what is gems in (POKESTOP) status?
![q1](https://cloud.githubusercontent.com/assets/8787638/17765982/60aad666-655b-11e6-9ae6-4be881bc15c8.png)

2) what are these numbers? can u put a label at this information tab?
![q2](https://cloud.githubusercontent.com/assets/8787638/17766043/a8cbd3dc-655b-11e6-8092-4b7b73f57094.png)

**Comment by PassiveModding** [comment]
gems is revives
3200 (3405/hr)  stardust gained and hourly rate
44010 is xp per hour
190 is pokemon caught
176 i believe is pokemon transferred
257 is pokestops spinned

**Comment by Lunat1q** [comment]
Please, look at the markup in sources
