### ISSUE TITLE
[Request] Upgrade pokemon Lv

### ISSUE THREAD

**Issue by viciousnake** [Lunat1q/Catchem-PoGo#1983]
Maybe already asked, but as any pokemon with lv 30 becomes really hard to upgrade because of stardust, it would be nice to have some way to level up until lv we want.

For example:

Now
lv 22 > lv 22.5 > lv 23 > lv 23.5

Request
lv 22 > lv (select one)

If it can make the sum of Stardust that will consume, much better

Sorry my english

**Comment by Finrod87** [comment]
U already have the option to lvl up to max.

**Comment by viciousnake** [comment]
yes, but as already mention, last 10 levels consume a lot of stardust, and in my case, i think it's better to have a 4 or 5 pokemon set with lv 30 that only 2 lv 40.

**Comment by Spk345** [comment]
You can individually level it yourself by selecting level up until whatever level you choose. Shows in action queue.
