### ISSUE TITLE
No Issue... Suggestion...Pokestop Lure

### ISSUE THREAD

**Issue by voctavio** [Lunat1q/Catchem-PoGo#1984]
Maybe I'm missing in the setting, or it's not set in the Bot yet. but is there a way to have the Bot break on Lure at Pokestops?

If not, is there a way this could be implemented?

**Comment by Finrod87** [comment]
nope, u can do it manually. just set walking speed to 0.0001 or do a custom route in a circle.

**Comment by Spk345** [comment]
It's planned.
