### ISSUE TITLE
Bulbasaur IVs wrong?

### ISSUE THREAD

**Issue by ivandnt** [Lunat1q/Catchem-PoGo#1985]
So, after a lot of transfers I did, i know came to report that Bulbasaur status is wrong? See, 3 Bulbasaurs, all 3 with 0/x/x always showing 0 Attack Status, ALWAYS, Maybe because of this, I never got the IVs right and never saw one of my bulbasaurs above 60% IV, can u check that? :)
![capturar](https://cloud.githubusercontent.com/assets/21185327/18730756/5e8c7040-802e-11e6-88c9-639237be6677.JPG)
![capturar2](https://cloud.githubusercontent.com/assets/21185327/18730755/5e8aab3e-802e-11e6-883d-7cb6c2ced9cf.JPG)
![capturar3](https://cloud.githubusercontent.com/assets/21185327/18730758/5e9d8aec-802e-11e6-80f5-2e893650caad.JPG)

**Comment by Finrod87** [comment]
U are just unlucky. i cant confirm it for me.

**Comment by Kalrod** [comment]
This is a known Pokédex IV Bug.

[https://www.reddit.com/r/TheSilphRoad/comments/4v0puc/theory_potential_bug_with_ivs/?sort=top](https://www.reddit.com/r/TheSilphRoad/comments/4v0puc/theory_potential_bug_with_ivs/?sort=top)

**Comment by Lunat1q** [comment]
it's proper values.

**Comment by hotmetal007** [comment]
i dont know if its is a bug but,  wild  pokemon have lower IV than hatched pokemons, all of my 100% iv pokemon are from eggs. And i catch a lot of bulbasaur and no one deserve to be evolved, is the same with  pikachu, squirtle and charmander.
