### ISSUE TITLE
RouteCreator Not Saving Route after Bot Restart

### ISSUE THREAD

**Issue by fayssal90210** [Lunat1q/Catchem-PoGo#1987]
Hello 

i have a problem the RouteCreator since i've downloaded The PreRelease version 

the route i'm creating are not save after i close the bot, every time i restart the bot the Route list is empty and i have to re do the route again every time 

do you have this problem too, or it's just me ?

**Comment by Spk345** [comment]
Uhh.. we had an issue with this with an earlier version of catchem, update to the newest release.

As always remember to overwrite old folder with new info.
