### ISSUE TITLE
Can anyone help me?????

### ISSUE THREAD

**Issue by DGLVCY** [Lunat1q/Catchem-PoGo#1989]
I can not get almost any pokemon ... I 'm running bot more than 6h and took only 47 Pokemons ... Can anyone help me ?

**Comment by JBWKZ2099** [comment]
Where do you put the bot? I mean, in wich place (country, etc)

**Comment by DGLVCY** [comment]
In Brazil, Ibirapuera... The elevention of the place is 765, so i put it... But I still can not get almost any pokemon

**Comment by Spk345** [comment]
It sounds like you are in a bad area for catching pokemon, try a different area.
