### ISSUE TITLE
translation bis

### ISSUE THREAD

**Issue by BrYcOu** [Lunat1q/Catchem-PoGo#199]
[https://camo.githubusercontent.com/7647fea29f7cf982fe7ca2bcc0c738e3ee2043dd/687474703a2f2f692e696d6775722e636f6d2f30615759626c6c2e706e67](url)

Sorry, I test here the langage FR and it doesn't work.

**Comment by standujar** [comment]
French trad are not working, you can eddit files if you want it ;)
