### ISSUE TITLE
[Feature Request] Transfer Confirmation

### ISSUE THREAD

**Issue by kazuki18** [Lunat1q/Catchem-PoGo#1990]
During manual transfer, a confirmation pop-up or something to appear to ask if continue or cancel the manual transfer to avoid accidental transfers.

**Comment by Spk345** [comment]
Manual transfers show up in your action queue and you can cancel actions from there.

**Comment by Spk345** [comment]
There will be no options to have a confirmation box in transfer... imagine doing that for 20 pokemon? No thanks. That's what action queue is for.
