### ISSUE TITLE
[REQUEST] Add telegram egg notification

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1993]
Hi, i want an option where i can set that every egg that i hatch send me a report on telegram about what came out. Sorry for my bad english

**Comment by Finrod87** [comment]
i dont think this will ever happen^^

**Comment by paura123** [comment]
> i dont think this will ever happen^^

why? D:

**Comment by Lunat1q** [comment]
It's already done since day 1 of telegram bot.

**Comment by paura123** [comment]
Lunat1q but i don't get any notification about my eggs (untils they are above X IV or CP that i choose) i want the notification for every egg
