### ISSUE TITLE
request: go to location in create route tab

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#1994]
would you add go to location in create route tab? just like one in console

**Comment by Lunat1q** [comment]
What? why u may need it.

**Comment by saldotman** [comment]
I usually 'travel' to other places.
when I want to create route around that place, I can not go directly since
route map does not relate to console map.

so, my bot may walk to place A, but I can not go directly and create route
around that place.
right now I should find that place manually in route map, and then create
route around it
