### ISSUE TITLE
Action Queue!

### ISSUE THREAD

**Issue by Virusdead49** [Lunat1q/Catchem-PoGo#1995]
How to use Queue function!

![2016-09-22_125837](https://cloud.githubusercontent.com/assets/10480101/18745891/7c1b9492-80c4-11e6-9b7d-498bdc72c0d4.jpg)

**Comment by Lunat1q** [comment]
Go to discord, people will explain this to you.

**Comment by Virusdead49** [comment]
before closing at each message you could give me the link for the answer you're supposed to know everything you put in each time information without links how can we know or set your software.
