### ISSUE TITLE
[Error]Telegram

### ISSUE THREAD

**Issue by paura123** [Lunat1q/Catchem-PoGo#1999]
hi, i opened a issue (https://github.com/Lunat1q/Catchem-PoGo/issues/1993#issuecomment-248880687) where i asked a feature and @Lunat1q said that the feature is already here since first day of telegram.
the issue was that i wanted the notify of every egg that i hatch. but i never got those reports. could someone tell me how to set this? sorry for my bad english

**Comment by Lunat1q** [comment]
You want info for EVERY hatch u get? sorry i don't think i'm going to do it.
