### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by Kalashnikitty** [Lunat1q/Catchem-PoGo#2]
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0539	"ClientSettings.MoveSpeedFactor" in der expliziten Schnittstellendeklaration ist kein Member der Schnittstelle.	PoGo.PokeMobBot.Logic	C:\Users\xxx\Source\Repos\Catchem-PoGo\PoGo.PokeMobBot.Logic\Settings.cs	936	Aktiv
`

and

`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0006	Metadatendatei "C:\Users\xxx\Source\Repos\Catchem-PoGo\PoGo.PokeMobBot.Logic\bin\Debug\PoGo.PokeMobBot.Logic.dll" wurde nicht gefunden.	Catchem	C:\Users\xxx\Source\Repos\Catchem-PoGo\Catchem\CSC	1	Aktiv
`

**Comment by Lunat1q** [comment]
Sorry, i don't speak german, but as far as i see - you have problems with some settings, are u sure u used my latest release? with my latest api?

**Comment by Kalashnikitty** [comment]
ups sry.

first error:
`'ClientSettings.MoveSpeedFactor' in explicit interface declaration is not a member of interface `

second said PoGo.PokeMobBot.Logic.dll is missing

i did a fresh fork and opened it with MVS without any changes

**Comment by Lunat1q** [comment]
Yeah, i think i got it, you pulled git wrong, please, try to rebase it. You are using outdated api submodule.

**Comment by Lunat1q** [comment]
git submodule update

**Comment by Kalashnikitty** [comment]
yep. Now everything is working fine! Thx & closed :)
