### ISSUE TITLE
BUG Eevee ? Jynx ?

### ISSUE THREAD

**Issue by youtouff** [Lunat1q/Catchem-PoGo#20]
Hello,
there must be a problem with Eevee and Jynx , can import the parameters he had me transfer all

(I am French I am using a translator)

you understand or I try to rephrase ?

**Comment by Lunat1q** [comment]
Well, rephrase it please, didnt get what u mean

**Comment by youtouff** [comment]
there must be a problem with Eevee and Jynx , (and other ? )
they are transfered

with parameters:
-Keep Min Cp = 1250
-Keep Min Duplicate = 4
-Keep Min Iv = 90 %

if I 2 eevee (or jynx )
he transfer 1

if I 3 eevee (or jynx )
he transfer 2

while with the other pokemon , it keeps minimum 4


( I am French , I am using a translator)
you understand or I try to rephrase ?

(And what part)

**Comment by shinya88** [comment]
I seem to run into what @youtouff describe as well.

I used to have 2 snorlax, and the bot transfer 1 of my snorlax despite I set "Keep Min Duplicate" at 3.

I look through my log and this is what I found:

> [23:33:47] ====== DisplayHighestsCP ======
> [23:33:47] >   CP/BEST/POWERED |	perfect	| LVL | NAME       | MOVE1              | MOVE2  | MoveRankVsAveType |
> [23:33:47] # 1577/1600/3088 | 88.97%	 | 19 | Snorlax    | ZenHeadbuttFast    | Earthquake    | 39
> [23:33:47] # 1492/1511/3093 | 90.09%	 | 17 | Snorlax    | ZenHeadbuttFast    | HyperBeam     | 36

And it transfer some of the pokemon and I saw Snorlax is 1 of them

> [23:34:03] [Inventory] Pokemon Stored: 140/250
> [23:34:03] NidoranM	- CP: 331  IV: 42.50%   [Best CP: 135  IV: 89.13%] (Candies: 38)
> [23:34:05] Snorlax	- CP: 1577  IV: 88.97%   [Best CP: 1492  IV: 90.09%] (Candies: 55)
> [23:34:06] Zubat	- CP: 108  IV: 50.96%   [Best CP: 152  IV: 73.28%] (Candies: 17)
> [23:34:08] Zubat	- CP: 208  IV: 31.20%   [Best CP: 152  IV: 73.28%] (Candies: 18)
> [23:34:09] Pidgey	- CP: 89  IV: 23.35%   [Best CP: 26  IV: 60.47%] (Candies: 11)
> [23:34:11] Weedle	- CP: 149  IV: 15.57%   [Best CP: 125  IV: 42.36%] (Candies: 13)
> [23:34:12] Eevee	- CP: 140  IV: 84.92%   [Best CP: 272  IV: 94.66%] (Candies: 126)

Eevee was also among 1 of them, and I was left with only 1 Eevee. Also FYI, I had "Keep Min IV %" on 85 and somehow the Snorlax got transferred too.

**Comment by shinya88** [comment]
I'd think I found out why.

Under the config.json file there are these following lines:

>   "PokemonsTransferFilter": {
>     "Venusaur": {
>       "KeepMinCp": 1750,
>       "KeepMinIvPercentage": 80.0,
>       "KeepMinDuplicatePokemon": 1
>     },
>     "Charizard": {
>       "KeepMinCp": 1750,
>       "KeepMinIvPercentage": 20.0,
>       "KeepMinDuplicatePokemon": 1
>     },
>     "Blastoise": {
>       "KeepMinCp": 1750,
>       "KeepMinIvPercentage": 50.0,
>       "KeepMinDuplicatePokemon": 1
>     },
>     "Nidoqueen": {
>       "KeepMinCp": 1750,
>       "KeepMinIvPercentage": 80.0,
>       "KeepMinDuplicatePokemon": 1
>     },
>     "Nidoking": {
>       "KeepMinCp": 1750,
>       "KeepMinIvPercentage": 80.0,
>       "KeepMinDuplicatePokemon": 1

And followed with:

>     "Snorlax": {
>       "KeepMinCp": 2750,
>       "KeepMinIvPercentage": 96.0,
>       "KeepMinDuplicatePokemon": 1

And also Eevee & Jynx as @youtouff and I mentioned that the pokemon got accidently transferred.
