### ISSUE TITLE
(Bug) Hitting Pokestops before arriving on map

### ISSUE THREAD

**Issue by g00tch** [Lunat1q/Catchem-PoGo#200]
I'm hitting all pokestops before I'm there on the map...usually about halfway to the pokestop.

I've played with the Navigation settings and nothing I check/uncheck seems to correct this behavior.

"Use Discovery Pathing"
"Use Human Pathing"
"Use OpenLS Routing"

I don't use Mapzen Api Elevation, as I'm unfamiliar with it. 

I went back to 1.3.5 and it's working fine there.

![untitled](https://cloud.githubusercontent.com/assets/2353921/17766557/b299c336-64f9-11e6-985e-800d64a60a16.png)

**Comment by g00tch** [comment]
The bot is running at a faster speed than the map. And the map is going by my settings that I've been using for the past few days.

**Comment by bunthay** [comment]
usable pokestop help

**Comment by Lunat1q** [comment]
It's true, do you use pokestop When you are exact near him? Or When avail to use?

**Comment by g00tch** [comment]
This is every single pokestop using the bot.

I get halfway to a pokestop, and the bot is already spinning it, and starts moving on to the next pokestop, while the map still shows it's heading toward the first one. 

I've been upwards of 3 pokestops via the console message, while the map is still heading to 1.

No matter what I set it to, my Pokestops per hour is far above what my speeds are set at.
