### ISSUE TITLE
[Bug] Pokedex empty occasionally (v.1.5.3.0 bld 62)

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2000]
![2016-09-22_214146](https://cloud.githubusercontent.com/assets/21959374/18750487/dfa686ea-810d-11e6-99df-83528eff87b2.jpg)

**Comment by Finrod87** [comment]
U already tried to restart the bot?

**Comment by Ononolaus** [comment]
I had the same issue, restarting solved it.

**Comment by saldotman** [comment]
or if you run more than one bots, just switch to the other bot

**Comment by Spk345** [comment]
The pokedex tab takes a moment to generate and fill upon first starting the bot for the first time. If the bot doesn't seem to show it at all, restart the bot and it should work fine. 
This is a lot of information to gather upon bot startup as the bot is trying to query for login, route, pokemon nearby and etc. 
The nice thing is, pokedex tab is still viewable after the bot is full-stop in catchem.
