### ISSUE TITLE
[BUG] No useful Pokestops near? Stops bot after some time

### ISSUE THREAD

**Issue by Sadi68** [Lunat1q/Catchem-PoGo#2001]
Hello,
I have the problem, that the Bot will just walk around after some time botting and do nothing then writing up the Pokestops which are near (Name + distance ). Then I have to close the Bot and wait some time. Sometimes after 2-3 hours it works again, sometimes it takes much longer.
Today I got something different, the bot started writing up there are no useful pokestops near ( i have the client in german, i translated it myself, dunno whether the english version also writes up the same).
I am not sure about what you need, I can upload every file u need, just tell me what you need.

The strange point is, that the bot works for a period and then stops working. Then after some time it works again.

**Comment by Ononolaus** [comment]
Looks like soft-ban. Maybe something you're doing is flagging your account. Too many pokémon caught or pokéstops visited are possible reasons.
1k pokémon / 12 hours and 2k pokéstops /12h are the limit.

**Comment by Sadi68** [comment]
But this happens after 1-2 hours. I have a limit of 85 Pokemons and 100 Pokestops. And I don't even bot 12h a day :D

**Comment by velwong** [comment]
Hi,
I have this problem too. 
It was working fine earlier. And, it suddenly reported the error half way through. After 1-2 hrs it was alright again. But then it happens again.

**Comment by wagas** [comment]
1bot = 1IP 
2bot + 1IP = SOFTBAN
1bot +1CP with POKEMON = SOFT BAN
=)

**Comment by leozinxd** [comment]
I also suffer with this problem, the theory of soft ban by IP makes sense, it is to change the IP for each bot? I use 3 bots ... times 3 is running normally, but most of the time the third stop working

**Comment by Ononolaus** [comment]
Well, if/when this problem happens again, try to manually play with with that account to confirm soft-ban or not.

**Comment by speedfucker** [comment]
@Sadi68 try for using different routing service, google api and mapzen valhalla have limit services per day.
combine using both of them alternately, especially if you use the api for more than 1 bot.
for me using openls routing service is the best way.
hope that can solve your problem.

**Comment by lavievn** [comment]
@speedfucker it's working good now, this issue happen 5 minutes ago and i'm changed all routing service to openls and all gone :D

**Comment by wiselytan333** [comment]
It is IP ban , when  you bot more then 1 account with same IP this happen , try botting 1 account only and you wont encounter it anymore.

**Comment by alanearl** [comment]
If you want to do multiple bots use proxy man :D

**Comment by ftmk25** [comment]
I had the same problem but i solved it with changing the routing services 
I had google maps services and i change it to Mapzen
