### ISSUE TITLE
[Feature Request] Standard feature 'go to location' missing in generic map application

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2003]
1. for route creator 
2. for console tab

If you stimulate travel across major cities in Europe, you will know my certain.  Many map web sites provide the same behavior.  I guess it is part of the google map API.

![go to location](https://cloud.githubusercontent.com/assets/21959374/18751092/4f997ad2-8110-11e6-969e-6fb9c5b1be06.jpg)

**Comment by Lunat1q** [comment]
![](http://i.imgur.com/mLZRqKC.png)
I think u should stop posting issues here, before u check it.

**Comment by tyu366** [comment]
>  I think u should stop posting issues here, before u check it.
partially right!

The route creator do not have the 'go to location' in v1.5.3.0 bld 62.
