### ISSUE TITLE
Application crashes after some hours of usage (Windows 10) - v1.4.9.3

### ISSUE THREAD

**Issue by snsrafael** [Lunat1q/Catchem-PoGo#2004]
I've been using the newest version for some weeks without any problem, and recently the program started to crash very often.

I'm botting with 3 accounts, I've tried to mark/unmark the 'Follow the player' option, change the 'speed factor', etc, didn't made any difference, after some hours of usage, the program always crashes and Windows prompts a window asking to close it.

I'm using Windows 10.

Anybody is facing this same issue?

**Comment by Lunat1q** [comment]
1.4.9 is heavily outdated, Update it.

**Comment by snsrafael** [comment]
Hello,

I`ve updated to the latest version (v1.5.2.1) and the problem still happends, the application eventually crashes and Windows asks to close it.

What additional information I can provide to detect a possible kind of incompatibility with Windows 10?
