### ISSUE TITLE
Better Use of the Program

### ISSUE THREAD

**Issue by luisalvim** [Lunat1q/Catchem-PoGo#2006]
Hi! Does anyone knows the best config to improve xp gains? Like my bot says it needs 1600 hours to lvl up. I would like to know a config that keeps like tons of pidgeys, then evolves them all in  one time. Is it possible?

Thank You!

**Comment by Finrod87** [comment]
just keep poke to evolve and use lucky eggs while evolving and wait to have 100 poke to use lucky egg. thats all settings in the bot...just read it.

**Comment by alanearl** [comment]
Buy many lucky eggs in the shop & set to use lucky egg as always.

**Comment by tyu366** [comment]
if up to 9000 xp / hr meet your requirement, just keep the bot walk in some area of central park, NY.  You do not need any special configuration.  The second thing is to walk around any rivers to get as many magikarp as it can.

Evolve pidgeys is fast but you have to pay for 2 price
- lose many star dust 
- losing space to manage a good inventory.  

You will know my point if you get a poke with CP 46 but IV over 97%.  Do you know how much star dust you need to make it strong? How about you want to raise 12 of such pokes?

It is better to use the star dust for power up your pokes to max. for fight.  You need to fight to gain poke coins for later use unless you are willing to pay.
