### ISSUE TITLE
[BUG] Blue Incubator is not Working.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#2007]
Dear Dev,

Reproduce
1. Open Pogo on 0.37 using SmartPhone.
2. Use Blue Incubator on a 10km poke.
3. Close Pogo on SmartPhone.
4. Run Catchem v1.5.3.0build62.
5. Egg will not hatch on Blue Incubator.

Thanks.

Keep up the good work :)

**Comment by tyu366** [comment]
I just guess whether you have selected 'use only the unlimit incubator' in the catchem and the catchem will not update the progress of the blue one.

**Comment by alanearl** [comment]
ReallY? What will happen if both of them is check?

**Comment by tyu366** [comment]
The use egg incubator must be checked.
if you uncheck 'use only the unlimit incubator' and save and then restart the bot, will catchem update both egg progress?

if so, that would be the design flaw of catchem which have not consider your scenario.
If not, it would be difficult to conclude.
