### ISSUE TITLE
[Enhancement] Manual click use lucky egg.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#2008]
Dear Dev,

Adding additional setting to use manual of lucky egg is a great idea :)

![luckyegg](https://cloud.githubusercontent.com/assets/648116/18765552/d67d8998-8148-11e6-8789-32754b301f03.png)

Keep up the good work.

**Comment by medoamanquer** [comment]
Incence, lucky egg and lure
are on the road map
so, we just  have to wait for it

**Comment by szamuka** [comment]
how to use it lucky eggs, I selected 60 pokemons and lucky eggs didn't turn on :( and i chose option use lucky eggs while evloving

**Comment by alanearl** [comment]
Wow thanks man :) luv it!

**Comment by ArchangelBr** [comment]
Lure we can use already... just click on pokestop with right button of mouse and you can activate
