### ISSUE TITLE
[Feature Request] specific items amount to keep.

### ISSUE THREAD

**Issue by wakenabom** [Lunat1q/Catchem-PoGo#201]
hi,
it would be nice if u can make us choose how much items to keeps before being recycled.
![q2](https://cloud.githubusercontent.com/assets/8787638/17767369/4ee5337a-6562-11e6-919f-9e863657e4fa.png)

**Comment by ranrinc** [comment]
2nd for this feature

**Comment by Lunat1q** [comment]
No. I see No point to keep lowgrade
