### ISSUE TITLE
forced move 

### ISSUE THREAD

**Issue by szamuka** [Lunat1q/Catchem-PoGo#2010]
is it to posssible if i set forced move, and when trainer walks no catches pokemons, only walking to the forced move?

**Comment by ftmk25** [comment]
Yes it is possible 
I tried and it did like you said 
But i found other stuffs when we do forced move ,that the bot come back to the route that he leave when we force him to move other way

**Comment by tyu366** [comment]
According to prior answer I get,

- the bot will not walk into grassland if you use those direction api even though you force the bot to move.  You have to turn off those api just for one ad-hoc force move.
- you again have to turn off the catching and don't visit poke stop and save for just one ad-hoc force move.    Unfortunately that it still chooses a long path to walk along many poke stops.  It just not getting things from them.  

I think that is not what you are looking for.  Please refer to #1951
So I suggest to forget about the force move.  You need to setup many stop in between to make the bot go faster.  Sometimes it will take you over 10 minutes to monitor.
It is also not worthwhile to build a custom path.  In this approach you do not need to monitor.
The only way that I am doing right now and this is the most effective is to forget about the catchem.  Use the phone and set up the fake location accordingly.  Remember to wait for reasonably time between hopping.
