### ISSUE TITLE
about the Proxy issue

### ISSUE THREAD

**Issue by oncats** [Lunat1q/Catchem-PoGo#2011]
When I enable the Proxy (check proxy is fined), the Catchem-PoGo just walk, no Gotcha any Pokemon.
But when I disable the Proxy, it works

**Comment by johnpeterphoto** [comment]
then your proxy is not good.

**Comment by d3f4w1t** [comment]
your proxy IP is blacklisted, probably too many players used the same IP

**Comment by szamuka** [comment]
which site is best to take proxies?
