### ISSUE TITLE
請問用完catchem後，道具都被刪除了，寵物也是被刪除一半。這是為什麼?

### ISSUE THREAD

**Issue by qakrocd** [Lunat1q/Catchem-PoGo#2015]
請問用完catchem後，道具都被刪除了，寵物也是被刪除一半。這是為什麼?

**Comment by KitazawaMoa** [comment]
可能有转移吗? 检查您的传输设置。

**Comment by searchingDD** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/1930

**Comment by tyu366** [comment]
you should check the log first on how item inventory are being recycled and how pokes are being transferred?
The value you set in the setting will cause immediate disposal of items.

**Comment by qakrocd** [comment]
我有檢查我的logs，沒有發現道具、寵物異常，早上東西都在，中午看就不見了，道具設定都沒錯，我沒有開自動賣掉寵物的設置，重覆的都是手動賣出。謝謝回覆，感恩

**Comment by xxxky** [comment]
檢查一下最後一頁，稀有小精靈都預設了保留一隻

**Comment by xxxky** [comment]
新版檢查"寶可夢設定列表"的"傳送名單細調"

**Comment by qakrocd** [comment]
不是只有稀有精靈，其他普通的精靈也都消失，道具就連薰香、誘捕模組都消失了
