### ISSUE TITLE
To Evolve Pokemon List (Not Working)

### ISSUE THREAD

**Issue by hotmetal007** [Lunat1q/Catchem-PoGo#2016]
Hi, the bot is evolving all the Pokémon including those who are not on the list, is there an option to evolve only pokemones from the list?

i lose my dratini candis :(,

**Comment by Ononolaus** [comment]
There is an option to "evolve all pokemon above iv...". Which mean, even if your pokemon isn't on the list of pokemon to evolve, it will get evolved because its high iv. Perhaps that's what happened.

**Comment by hotmetal007** [comment]
i will try, thanks!

**Comment by hotmetal007** [comment]
it works, my fault, thanks 💃

**Comment by Spk345** [comment]
![This too](http://s9.postimg.org/bct8uuai7/screenshot_19.png)

That will evolve ALL pokemon with enough candies, including pokemon that aren't on your *to Evolve* list.
