### ISSUE TITLE
Mapzen Valhalla API Key is Empty!

### ISSUE THREAD

**Issue by Arkhang3ll** [Lunat1q/Catchem-PoGo#2018]
Good morning to all.
Excuse my bad English, I open the program well and everything but I get an error (Mapzen Valhalla API Key is Empty!) The character moves and everything but does not leave any pokeparada or any pokemon to catch, and I'm sure I do not have Softban because I open the game on the phone and I get all, as I can solve this problem?
PS: my location is playing Bogota, Colombia.
![catchem](https://cloud.githubusercontent.com/assets/20936642/18789002/d27868b0-816e-11e6-8fa1-4c059d860063.jpg)

**Comment by Spk345** [comment]
Check your attitude setting. Is it 2000, or -1000? Reset it to normal parameters.

How to get mapzen? Check the wiki link and follow the steps by step guide. Or join us on discord.
