### ISSUE TITLE
Alert!!!  Version 0.39 Capture location: The location where a Pokemon was caught will now be displayed on their information screen.

### ISSUE THREAD

**Issue by alfath2016** [Lunat1q/Catchem-PoGo#2019]
Pokemon Go Update Notes:

Capture location: The location where a Pokemon was caught will now be displayed on their information screen.
Pokemon Go Plus and Incense: Trainers can attempt to capture Pokemon they encounter from using Incense with the Pokemon Go Plus accessory.
Minor bug fixes

**Comment by Ononolaus** [comment]
Well, lots of information are already stored for each pokemon, they just don't display it. No big deal, really, snipers have all been flagged long ago because of that.

**Comment by alanearl** [comment]
Im kinda wonder why they cant eliminate snipers. Just compare the public ip address & pokemon location if both countries are different implement automatic ban.
