### ISSUE TITLE
MapzenAPI system 

### ISSUE THREAD

**Issue by khai5535** [Lunat1q/Catchem-PoGo#202]
Can someone pls explain about the use and purpose of  MapzenAPI ? What if I dont use it?

**Comment by khai5535** [comment]
What if I dont use it?

**Comment by Bay101** [comment]
It is a replacement for the OpenLS that was previously implemented due to OpenLS being highly unstable, we are instead using Pokemobbots routing server along with MapZen. An updated wiki will be out soon.
