### ISSUE TITLE
Route creator doesnt work

### ISSUE THREAD

**Issue by Bizadon** [Lunat1q/Catchem-PoGo#2021]
I am going to the route creator and tap "Build the route" but nothing happens.

**Comment by ArchangelBr** [comment]
it's fine here
are you using manual route ?

**Comment by Bizadon** [comment]
@archangelbr I tried with manual route checkbox, without it but no difference - nothing happens

**Comment by Finrod87** [comment]
dude u are doing it wrong. right click the map and set a start, then do some waypoints and when u are done u click build the route...

**Comment by ArchangelBr** [comment]
It's simple, @Bizadon ! Do what @Finrod87 said and tell us what happened

**Comment by tyu366** [comment]
Are you using any API?
You have to wait until done shown in the top right hand corner.
