### ISSUE TITLE
evolve issue 

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2024]
i have a problem evolving pokemons... i only add some pokemon to evolve in the evolve list but when i check the evolve all poke above iv its evolving all of my pokemons and i lost all of my candies... i have evolve iv value 25 and in the list of evolve pokemons rattata pidgey and some other.. but it keeps evolving my special pokemons that i want to keep it for candies.. any ideas ?

**Comment by Spk345** [comment]
![Turn this off](http://s9.postimg.org/bct8uuai7/screenshot_19.png)

There's your problem.
Uncheck the box. Your bot will evolve ALL pokemon with enough candies, not just what is on your *to evolve* list.

**Comment by unknowkir** [comment]
yes but when i uncheck the box nothing evolves..

**Comment by Spk345** [comment]
You bot will evolve using it's *to evolve* list, especially if you use Lucky Eggs while Evolving setting. If you have Lucky Egg set, it will wait until it has enough pokemon and candies on the *To Evolve* list before it will trigger evolving.

Evolve all pokemon with enough candy overrides the *To Evolve* Pokelist.

**Comment by unknowkir** [comment]
that means I must uncheck everything on the settings both evolve all pokemon above iv and all pokemon with enough candies. but when I uncheck both, it just keeps transfer the pokemons and not evolving them..
