### ISSUE TITLE
End of Catchem? Where's the update?

### ISSUE THREAD

**Issue by Charlisson** [Lunat1q/Catchem-PoGo#2025]
It's been days that the bot is not updated, all estam on hold and so far nothing, we have to use older versions, the Pokemon go, updated twice, and nothing Catchem update :(

**Comment by tyu366** [comment]
https://github.com/Lunat1q/Catchem-PoGo/releases 
pre-release bld 65

**Comment by alanearl** [comment]
The only thing is not updated is the PoGo API. Its getting hard to crack cuz it is using SafeNet Security. It is still ongoing.
So far v.1.5.3 build 62 is stable.

**Comment by Spk345** [comment]
#1704
