### ISSUE TITLE
[Feature Req] Pokemon Prefer List

### ISSUE THREAD

**Issue by mohhawk** [Lunat1q/Catchem-PoGo#2026]
While showing Dratini or Pikachu on the map, the bot catches Magikarp, Psyduck or Pidgey : |
Can you add a prefer list so the player can list the pokemons to catch first above the less rare ones.

**Comment by Spk345** [comment]
You can choose to add them to the "Not to catch filter" and check the setting to use it.

**Comment by mohhawk** [comment]
But a prefer list is different from not to catch list!
