### ISSUE TITLE
There are traps in Pokemon go app.

### ISSUE THREAD

**Issue by JihWei666** [Lunat1q/Catchem-PoGo#203]
When we play pokemon go, we can not run too fast .
If we did,we should tap the button "I am a passenger".
Then we can continue playing the game.

Key point: No tap, No play .

The Bot may not send the message to Pokemon server.
But the bot is still fucking busy with Pokestops and pokemons.

OK, it's a bot.  Ban...Ban...Ban...

**Comment by neoneosa** [comment]
i think the bot SHOULD to that,but if not were all fakked

**Comment by Traween** [comment]
This probably has nothing to do with trying to ban botters. It's just to ensure people aren't driving while playing and it is probably is just client-sided anyway

**Comment by JihWei666** [comment]
So.....you can use the bot 60 km/hr.
Because people play the game on the bus , Niantic won't ban their account.

**Comment by itterror** [comment]
As the message is not server triggerd but client triggered i doubt, that it sends it to the sever when you fail to press it. its quite annoying when driving and playing yourself.
