### ISSUE TITLE
[Bug] Action items protection animation lost after refresh

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2031]
v1.5.3.0. bld 65
![2016-09-24_184249](https://cloud.githubusercontent.com/assets/21959374/18808247/4428a3be-828f-11e6-9555-00e6289b851d.jpg)

after refresh (note Mr. Mime still waiting transfer but no transfer animation)
![2016-09-24_184310](https://cloud.githubusercontent.com/assets/21959374/18808250/59e78fd0-828f-11e6-906a-bd0d0f916e3e.jpg)

**Comment by Lunat1q** [comment]
fixed.
