### ISSUE TITLE
[Feature Request] Show Egg Status as ??? Before Load In

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2032]
b1.5.3.0 bld 65
The screen show 0/10km for several minutes.  After that the status is shown.
There is no indication in between.
![2016-09-24_184423](https://cloud.githubusercontent.com/assets/21959374/18808260/a2f888b4-828f-11e6-8b60-a2b7f8cfda73.jpg)

**Comment by Spk345** [comment]
Eggs take a moment to update.

Are you running *human pathing* and staying under 12km/hr speeds including speed factor?

**Comment by tyu366** [comment]
yes.  the egg will hatch.  The speed is below 12.  

When the bot starts, it shows all 0.  User will visualize it as a bug.

I suggest to protect the egg pane as similar to the poke table when the egg progress has not been updated.  When update completed, un-protect the egg pane.

**Comment by Lunat1q** [comment]
It will stay as it is.
