### ISSUE TITLE
[UI Suggestion] Proposed layout of catch setting to make it more structured and readable.  Suggested new catch setting.

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2035]
**Proposed**
![catch1](https://cloud.githubusercontent.com/assets/21959374/18809767/595e9b94-82b7-11e6-87c6-c59d00d14236.jpg)
Those in red are new catch settings

**Current** 
![catch2](https://cloud.githubusercontent.com/assets/21959374/18809768/64415826-82b7-11e6-8bb7-3f6aadcd974e.jpg)

**Comment by Lunat1q** [comment]
No, it will stay as it is now.
