### ISSUE TITLE
[Feature Request] Medal achieved of Players

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2037]
As the player tab have many space currently. showing medal achieved may be a way to fill up this page.
![medal2](https://cloud.githubusercontent.com/assets/21959374/18809899/d3bd8a3c-82ba-11e6-91ff-be69c14a8750.jpg)

![medal1](https://cloud.githubusercontent.com/assets/21959374/18809911/2a37d688-82bb-11e6-96c8-a590292aeec3.jpg)

**Comment by Finrod87** [comment]
Sounds nice

**Comment by Lunat1q** [comment]
let me see... may be, some months later, no ETA.
