### ISSUE TITLE
[Bug] One blue incubator not being used but one in use

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2042]
When level 30 is reached, I get 3 3-time used incubator as level reward.
The bot will use 3 incubators initially as expected but after sometime one incubator remains idle.

My inventory shows that I have 2 blue one
![incub1](https://cloud.githubusercontent.com/assets/21959374/18810707/b6c74872-82cf-11e6-8f90-de214d82956f.jpg)

Only one blue one is in use.
![incub2](https://cloud.githubusercontent.com/assets/21959374/18810708/b6c7d814-82cf-11e6-8a65-1979dd07f48c.jpg)

**Comment by Spk345** [comment]
Have you tried to refresh it? Maybe one of the limited is has been used up and it hasn't update inventory yet.

**Comment by tyu366** [comment]
yes. definitely refresh it. wait over 1 hour but showing no improvement.

**Comment by Lunat1q** [comment]
that can't happen. Or you have to wait untill next egg status refresh. That means you just GOT your second.
