### ISSUE TITLE
[Alert] Do not manipulate poke on the UI with same IV and CP

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#2043]
I witness this issue from v1.5.2.1 to 1.5.3.0 bld 48, 54, 62, 65

The conclusion is whether you favourite one of them or transfer one of them, the other one will be disappeared.

If your queue action is favourite, the animation will not be gone even action performed.

**Case 1 - favourite**
There are 4 oddish on this screen. 2 CP 643 IV 88.9%. One is not shown completely on the left side of the screen.   I favourite one CP 643 IV 88.9% on the left. 
![disappear2016-09-22_201137](https://cloud.githubusercontent.com/assets/21959374/18810803/c19921d8-82d1-11e6-8eee-be317faf72be.jpg)

The animation appear.  When the action is done, the action queue shows empty but the one on the right with same CP and IV is favourite.  The left one still have the animation on.
![disappear2016-09-22_203220](https://cloud.githubusercontent.com/assets/21959374/18810804/c19b0818-82d1-11e6-833c-856d8d8d57e9.jpg)

After refresh, the one with animation disappear.  The one being favourite left as expected.  This is further confirmation with my phone.

**Case 2 - transfer**
If you do transfer, one transferred and one disappeared.

**Comment by sunnydude22** [comment]
The cause of this issue I believe is because a hatched egg pokemon in CatchEm will show as 2 separate pokemon initially (therefore having both same CP & IV).

**Comment by tyu366** [comment]
1 egg hatch + 1 existing poke or
1 catch + 1 existing poke
still bring up the same issue

**Comment by Lunat1q** [comment]
Case 1 - duplicate bug, case of shitty server response from niantic.
Case 2 - same

**Comment by tyu366** [comment]
So what is the conclusion?   Using the phone to handle it?
