### ISSUE TITLE
Force Move Bug?

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#2046]
After force move, bot directly move to previous location in seconds, which can be miles away.
I use 1.5.3.0 build 62.

I use normal routine, not custom route

**Comment by Spk345** [comment]
What routing service do you use? Mapzen may be causing this problem, we don't know for sure yet.

**Comment by ravenskly** [comment]
with me is the same without using "human pathing", but not always

**Comment by saldotman** [comment]
I use mobbot.
it happens when:
1. use mobbot
2. no custom route
3. I start the bot, 
4. force move
5. after force move done. bot will go back to the previous location
