### ISSUE TITLE
[Bug] use custom route when Proxy List enable

### ISSUE THREAD

**Issue by oncats** [Lunat1q/Catchem-PoGo#2050]
Proxy List enable (check pass) and do as below steps:

1. when I create new route and enable custom route
2. It's just walk.... and do noting (BUG)
3. when I disable custom route
5. It can walk and Gotcha!

test version: 1.5.2.1_upd2, 1.5.3.0_build65  (result are same)

**Comment by oncats** [comment]
Note.
1. when I disable Proxy List, and enable custom route, it's ok

**Comment by Spk345** [comment]
Can you post a screenshot of this occuring?
Honestly I use both custom routes on both my normal and proxy ip, and no issue. 
Try *Test Proxy* and see if the proxy is a good proxy. What is probably happening is that it's not getting the custom route fast enough through the proxy, so it appears to *stop*.

**Comment by oncats** [comment]
![2016-09-25_193330](https://cloud.githubusercontent.com/assets/22381759/18815046/116b7d52-8357-11e6-9e9e-11f4d79fbc44.jpg)

I don't know why it just walk.....
I check the proxy is a good proxy.

**Comment by Spk345** [comment]
Are you options set for *loot pokestops* and *catchem wild pokemon*?

**Comment by Spk345** [comment]
So if I'm reading this right, you can catch pokemon, and loot pokestops when you are **not** using the Proxy *or* the Custom Route?

**Comment by oncats** [comment]
yes, If I am not using the Proxy, everything is ok 
(I can catchem the pokemon and loot pokestops)

"Catch Wild Poke" and "Loot PokeStops" enable (default setting)

**Comment by Spk345** [comment]
The proxy is IP banned, It's temporary, and it will lift in a 2-24hrs. However, if it is a free proxy, it will likely get banned again. If you want to use proxies, you should opt for paid proxies, because if you get an IP banned one, you can request another one that isn't. 

Also, never run more than one bot on one IP address, or Proxy/vpn, at the same time. It will usually result in an IP ban again.

**Comment by oncats** [comment]
yes, I understand you mean...  thanks a lot for your detail reply.
