### ISSUE TITLE
Not an Administrator account

### ISSUE THREAD

**Issue by git123hub123** [Lunat1q/Catchem-PoGo#2051]
Hello community:
I created an account of Pokemon Go with the email of my university, that is an google account administered for my university. So, when I sing in to gmail, the website of my university opens and I have to write again my id and pass. Thats the reason I can not use the bot.
Please,I wish I could use my account the bot with my account that is administered for my university.

**Comment by Lunat1q** [comment]
I see nothing related to Catchem, talk to Niantic about that.

**Comment by git123hub123** [comment]
Yes and thanks to answer. Niantic should allow to change the accounts information like email.
But until that, maybe you Lunat1q could make to google administered accounts can use catchem. Here the error message trying to enter the my account:
[11:21:25] (UPDATE) Perfect! You already have the newest Version 1.5.2.1
[11:21:25] (INFO) Logging in using account Google
[11:21:26] (ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[11:21:26] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)
[11:21:33] (ERROR) https://security.google.com/settings/security/apppasswords
[11:21:33] (ERROR) System.ComponentModel.Win32Exception (0x80004005): No se ha encontrado la aplicación
   en System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start()
   en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start(String fileName)
   en PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() en F:\catchem\PoGo.PokeMobBot.Logic\State\LoginState.cs:línea 111
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() en F:\catchem\PoGo.PokeMobBot.Logic\State\StateMachine.cs:línea 39
Please I know you can make that I can use the bot.
Regards.

**Comment by git123hub** [comment]
@git123hub123
