### ISSUE TITLE
egg problem

### ISSUE THREAD

**Issue by Siaokia92** [Lunat1q/Catchem-PoGo#2053]
when during botting the egg will only help to complete it.
but will not auto change to other egg until you restart your bot again.
please help to check this

**Comment by Finrod87** [comment]
Do u use the newest release? My bot is always putting eggs into incubator after finishing the one before. i dont need to restart.

**Comment by Siaokia92** [comment]
yes it is the newest version 1.5.2.1

**Comment by Lunat1q** [comment]
newest is 1.5.3.0 build 68

**Comment by Siaokia92** [comment]
may i know how to update it?
