### ISSUE TITLE
Can't change the config file

### ISSUE THREAD

**Issue by loserme945** [Lunat1q/Catchem-PoGo#2060]
Hi,
I tried to add "KeepMinOperator": "and" to the transfer filter and other lines like   "TransferDuplicatePokemonOnCapture": true to the "PokemonSettings" but the added lines are disappeared whenever I open or close the catchem. 

How can I fix this?

Thank  you

**Comment by Spk345** [comment]
Were you running Catchem when you tried to change the txt file?  Because it would be in use if you did that.

**Comment by loserme945** [comment]
No I didn't. All I did is adding lines, close the config, open Catchem, close Catchem, check the config, then the added lines are gone.

**Comment by Lunat1q** [comment]
Then u added those lines in wrong format.
Also there is no "KeepMinOperator" property.
