### ISSUE TITLE
[Issue] v1.5.3.0 - Map layer  moves but rendered pokestops / little guy does not

### ISSUE THREAD

**Issue by amsagain** [Lunat1q/Catchem-PoGo#2063]
When program starts, everything is fine, pokestops show on map in all appropriate locations, all good. But after a while it's like the layer where the map is is separated from the one with pokestops/poke markers/etc. All markers usually migrate to the corner of the Map & Console view, and stay there immobile when I drag the map around, see below:

Before drag:
![image](https://cloud.githubusercontent.com/assets/22350890/18823248/f81c7034-836c-11e6-87d8-ac670586e088.png)

After drag:
![image](https://cloud.githubusercontent.com/assets/22350890/18823256/0968207c-836d-11e6-8633-c4850610ac77.png)

If "Follow the player" is marked, the pokestops and the map start scrolling around together again, but again, if I manually drag the map, only the map layer moves, the pokestop layer stays immovable. I stop dragging, it moves together again.

Under the link you can see a small video of how it looks I made with TinyTake:

https://alexfisher.tinytake.com/sf/OTkzNzQzXzQxMjUzNjM

**Comment by d3f4w1t** [comment]
whatever the problem is, it doesnt matter anymore. bots, spoofers, legit players all need the latest updated pokemon go app to play. olders versions will be denied service

**Comment by ccpiloveyou** [comment]
Looks like a map lag which shall not affect the process for sure.
