### ISSUE TITLE
[Issue] V1.5.3.0 B68 download

### ISSUE THREAD

**Issue by kingtop68** [Lunat1q/Catchem-PoGo#2064]
In unassembling new version (0.39.1) ago
New Downloads 1.5.3 B68 is currently closed in?
It is expected to release a new version?

**Comment by d3f4w1t** [comment]
all bots are useless now since you are required to use latest updated pokemon go to request any service from their servers.

**Comment by dugarila** [comment]
No, I can still bot fine with build 65 of Catchem 1.5.3 and I even verified in my phone that has the latest update of PoGo and the exp and the pokemons are registered in there. But maybe it's just with me

**Comment by neokiller89** [comment]
so that's mean we're going to get ban right?

**Comment by dugarila** [comment]
I'm still fine and running and not banned for that matter

**Comment by neokiller89** [comment]
so you're still botting.. or just playing pogo on phone..

**Comment by dugarila** [comment]
I've said it on my first comment, I'm still botting and I can play PoGo in my phone aswell. I'm currently lv 37 and a half in case you're wondering :)

**Comment by neokiller89** [comment]
u're from?

**Comment by jemfox** [comment]
same here, I can still use the bot

**Comment by voctavio** [comment]
I've been botting since yesterday, and still catching and looting pokestops. I've been doing it for the past couple of hours, no issues.

**Comment by hotmetal007** [comment]
is not safe use the bot :(

**Comment by neokiller89** [comment]
After you botting.. did u sign in on your phone to check your exp..

**Comment by dugarila** [comment]
That's what I said, I signed in and checked the exp and pokemons caught and it was all fine

**Comment by sunnydude22** [comment]
ban are never immediate. continue at your own risk.

**Comment by neokiller89** [comment]
Hope's everythings will be fine after updated my pogo v0.39

**Comment by hotmetal007** [comment]
im so lazy i want the bot :(

**Comment by Kalrod** [comment]
"As of today, the API uses the encryption for versions below 0.35, while the latest game client uses another encryption for 0.37/0.39. Both are validated by the servers. Niantic has forced every 'legitimate' player to switch to 0.39, so they know every account still using 0.35 encryption is a botter, sniper, scanner, or api 3rd party user... and flags them for a later ban wave."
