### ISSUE TITLE
Collecting pokestops Wthout catching any Pokemons

### ISSUE THREAD

**Issue by Wat3v4** [Lunat1q/Catchem-PoGo#2069]
Hey
Is there a way to just go around and collect pokestops without collecting any pokemons on the way..?
Sometimes I just want to refill my items stock and when it stops to catch pokemons it takes longer to achieve..

**Comment by kingkai808** [comment]
can't use catchem at all anymore.

**Comment by Wat3v4** [comment]
Actually its stil working for me.. maybe because ots been since before the force update..
Either way, for future use, is it possible?

**Comment by kingkai808** [comment]
Of course because the force update isn't completely out yet. But if you keep using it. Chances are you're already flagged for a ban.

**Comment by kingkai808** [comment]
Yes tho u just check the use poke not to catch filter. It'll still catch good Pkmn just not the trash

**Comment by KitazawaMoa** [comment]
You can disable "catch wild poke" in your setting.
