### ISSUE TITLE
you can't get the data from some android phones it seems (even with usb debug and dev options enabled)

### ISSUE THREAD

**Issue by ymega** [Lunat1q/Catchem-PoGo#2070]
you can't get the data from some android phones it seems (even with usb debug and dev options enabled)
the only one i have been ablet to test is a nexus 5x but i assume other google device can have the same problems

**Comment by devost02** [comment]
what data do u mean?

**Comment by tyu36** [comment]
replace the usb cable first.  
I have tried before with 3 pc and trying to install usb driver many times but still not working.
Some bad usb cable cannot deal with data.

**Comment by ymega** [comment]
the "get data from your android" option

**Comment by maurinho14** [comment]
http://visualgdb.com/KB/usbdebug-manual/

**Comment by shanishkag** [comment]
it works thank you bro..!!
