### ISSUE TITLE
cant login in game on phone with newest update 39.1

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#2074]
i can login into game on my phone to "bot manually" even do full update + hide my root (sure it is hide) :). Anyone else have same problem and know how to fix it?

**Comment by tyu36** [comment]
Does it say authenticate fail with login google account?
I have run hide my root to hide the su binary.
If I download a safetynet test app from google play, it still says failed.

**Comment by d3f4w1t** [comment]
hide my root doesnt hide it from safetynet tests. only way is with magisk but  you wont be able to use root apps so you would have to play pokemon legit
