### ISSUE TITLE
[Help] Is your maximium distance too small?

### ISSUE THREAD

**Issue by isPhelipe** [Lunat1q/Catchem-PoGo#2077]
I have been using the latest version, now I used the mapzen and after a while it just gets so
![sem titulo2](https://cloud.githubusercontent.com/assets/22429439/18872188/7e91ffee-848f-11e6-8393-1022af2c15cf.png)

**Comment by era12345** [comment]
Kindly read the Read Me section. You won't able to use the API as of the moment. Wait for further announcement regarding the update.

**Comment by alanearl** [comment]
Softban restart your modem.

**Comment by igorpalma** [comment]
# Read #2062 #

**Comment by isPhelipe** [comment]
@era12345 
even without using the mapzen he does it

@alanearl 
This always happens when the button is on. It's normal?

**Comment by diegosnotrod1** [comment]
download private tunnel and use it to change your ip address

**Comment by era12345** [comment]
Read #2062

**Comment by isPhelipe** [comment]
@era12345 ah, thank you so much
