### ISSUE TITLE
Bot still working

### ISSUE THREAD

**Issue by caockerman** [Lunat1q/Catchem-PoGo#2081]
What does it mean if my bot is still working despite your warnings to the contrary? I am still catching poke, looting stops, etc.

**Comment by voctavio** [comment]
I had created another account, and so far I have been botting still looting and catching for the past few days, no soft ban, no perm ban yet. Seems to be working with no issues.

**Comment by iAngelG** [comment]
It means it works lol. It's a warning. If you use it and it works then alright, but I wouldn't use your main account. I'm sure it'll flag you because you're using an older version that no legit player is able to use.

**Comment by Kalrod** [comment]
> Catchem should not be allowed to connect to Servers and play. If you do, after this Forced Update, then you are very likely flagging your bot for a future banwave, as no LEGITIMATE player can use APK 0.35.

**Comment by mizriel** [comment]
so i guess we should stop using until the new version of bot that use apk 0.37 is out?

**Comment by wagas** [comment]
your bot is being flagged down right now and will be sure to be ban on the next banwave =)

**Comment by alanearl** [comment]
So everyone in this world is being force update?

**Comment by hotmetal007** [comment]
bot pleaseeeeeeeeeee

**Comment by tyu36** [comment]
still work on 0.37, not 0.39?
bot has no option to catch of your favourite pokes
besides the API, anyone works on a root bypass apk which also fix the login issue?

**Comment by iAngelG** [comment]
#2062

**Comment by tyu36** [comment]
I think the manufacturer just stops the front end whose version which do not meet.
The server side at least still works now.  
It might be a phase-wise implementation which focuses on  1) root device  2) api.

So the API might still accessible for certain period.  Development work can still continue but just need a new account to test such that ban do not cause any lost.

**Comment by franziouz** [comment]
1 of my bot got perma banned and it has 6 pokemons with 100 i.v.'s.... T_T... sad

**Comment by Zelkova88** [comment]
Idem for me, this morning when I launched Catchem, appear a message "Niantic server unstable, throttling API calls" and after that, permabanned!
This morning my account was working, so I do not recommend to use the bot for now... :(
My poor dragonite :(

**Comment by easonfu** [comment]
Two of mine got permanently banned 90min go. It started with showing "niantic servers unstable throttling api calls" in the first one and 5min later the 2nd went wrong.

**Comment by kingkai808** [comment]
if you're botting after .37 was released everyone of you deserved it.
