### ISSUE TITLE
Problem with Map

### ISSUE THREAD

**Issue by pixe00** [Lunat1q/Catchem-PoGo#209]
New catchem 1.4.0.0
 this not presenting the MAP is presenting error messages. following image.

![2016-08-18_10-28-19](https://cloud.githubusercontent.com/assets/21104350/17775434/9be55be8-652e-11e6-8ad6-6c1050cfce16.png)

**Comment by BrLord** [comment]
Tem Br que é burro mesmo, mds. Vc deu muito zoom pra fora/dentro do mapa u.u

**Comment by pixe00** [comment]
Meu caro, se não tem noção do que se trata peço a gentileza de não se meter no assunto, não trata-se do zoom, posso colocar qualquer zoom que continua apresentando o erro.
Por isso que o Brasil não vai pra frente, pessoas como você, ignorantes e pobre de espirito, o burro e sem criação aqui é vc meu caro.

peço desculpas as outras pessoas que realmente tentam ajudar.
