### ISSUE TITLE
Ball Below Catch Probability Settings are not working.

### ISSUE THREAD

**Issue by dbatistadacruz** [Lunat1q/Catchem-PoGo#2090]
I set the Ball Below Catch Probability Settings but the bot doesn't obey them and prioritizes the best balls.

![probability](https://cloud.githubusercontent.com/assets/22527070/18963848/f2ffe74c-864c-11e6-814a-920f489b2257.png)
![chance](https://cloud.githubusercontent.com/assets/22527070/18963851/f68b4528-864c-11e6-9f14-59ee4aa84e70.png)

**Comment by kingtop68** [comment]
HI...
you're "Great Ball = 0" so use "PokeBall"  :)

**Comment by dbatistadacruz** [comment]
The bot uses PokeBall in the second throw.
The first one was a GreatBall throw with a probability of the 45,14%.
I set in the Ball Below Catch Probability 33%.

**Comment by dbatistadacruz** [comment]
The bot uses PokeBall in the second throw.
The first one was a GreatBall throw with a probability of the 45,14%.
I set in the Ball Below Catch Probability 33%.
The bot is always using GreatBall before the PokeBall.

**Comment by dbatistadacruz** [comment]
The bot used PokeBall in the second throw.
The first one was a GreatBall throw with a probability of the 45,14%.
I set in the Ball Below Catch Probability 33%.
The bot is always using GreatBall before the PokeBall.

**Comment by velwong** [comment]
The comma's are correct input? I had though them as decimals.
