### ISSUE TITLE
evolving

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2097]
to autoevolve selected pokemons I must have checked the "use lucky egg" box? it seems that I cant evolve any pokemon

**Comment by kaderDZ13** [comment]
1/- To autoevolve at any time , just check " evolve all poke with enough candy "

2/- To autoevolve with Lucky eggs , check " use lucky egg while evolving " AND the number of available pokes to start this condition

![candypoke](https://cloud.githubusercontent.com/assets/21276155/19013865/3cb76ed0-87d5-11e6-8dd5-a56a67966cfc.jpg)

**Comment by unknowkir** [comment]
yes but if I check the evolve all poke with enough candies its evolving every pokemon not only in the pokemon list... I lost my dratini candies :(

**Comment by kaderDZ13** [comment]
no no , for me working fine when you set the filter to evolve

![candypoke2](https://cloud.githubusercontent.com/assets/21276155/19013909/67fe107a-87d6-11e6-96ac-e62432116a7d.jpg)

**Comment by unknowkir** [comment]
in the evolve list I have only ratata pidgey caterpie.. but the last time I check it evolves and dratini execute.. is it bcs I had checked evolve poke above iv? I am afraid of try it again I don't want to lose any of my candies

**Comment by kaderDZ13** [comment]
Ohhhh " evolve poke above iv " is a condition to evolve any poke in you balls above the definite value ..... in my case i put iv=98% but never check the option. better choose what you evolve , and caterpie/weedle/pidgey for exp  :)

**Comment by unknowkir** [comment]
ohhh thank you man... that's my fault... I have checked bot boxes.. I only need to check evolve all poke with enough candies and not the other box... start over again now.. thanks again!!

**Comment by kaderDZ13** [comment]
Your welcome bro  :)  

Just a little advise, from yesterday lot of accounts are perma ban so be careful when use the bot those days ;)

**Comment by unknowkir** [comment]
omg... i hope not mine :P thanks again!

**Comment by kaderDZ13** [comment]
hope so ^^^^^^^ good luck ^^^^

**Comment by unknowkir** [comment]
another question :p it will stop evolving the pokemons automatically or i must uncheck the box to stop ?

**Comment by kaderDZ13** [comment]
Until you have no candies nor pokes to evolve  :) after the bot start check for transfer useless pokes

**Comment by unknowkir** [comment]
Great THANKS AGAIN!! :)

**Comment by kaderDZ13** [comment]
You're welcome  :)
