### ISSUE TITLE
PokeBuddy

### ISSUE THREAD

**Issue by Cruilowa** [Lunat1q/Catchem-PoGo#2099]
I'm having trouble to retrieve the candies found by my pokebuddy, is there anything i can do to retrieve all of them, my it says my pokemon walked 30km and i only got about 15 candies

**Comment by Wat3v4** [comment]
Maybe a bug? or Maybe you didn't notice you used them?

**Comment by Cruilowa** [comment]
@Wat3v4 i think is a bug, because, when i open the app on my phone it says magikarp has found 5 candies, but counting the km can be 10 or 15, maybe is something with the syncing

**Comment by alanearl** [comment]
Bug due to catchem is not 0.37 API.
