### ISSUE TITLE
longitude and latitude error

### ISSUE THREAD

**Issue by Jere100** [Lunat1q/Catchem-PoGo#21]
so i have a error with the longitude and latitude, when i want to start the bot it removes the the point after the first two numbers oft the longitude and latitude. on the console is than written something like no pokestops in the near found is the search radius to smal?
leveling up of the pokemon is possible so i think to log in to account was sucessfull.
can you help me, Please?

**Comment by Lunat1q** [comment]
Will be fixed in future release, it cause cause of language settings, decimal separator

**Comment by Jere100** [comment]
Thank you for the answer. How long will it take to fix? Or can i change the language settings in the bot?

**Comment by Lunat1q** [comment]
Try to get location with map, untill bot is started - u can double click on it to get startup position, look at video in readme, i'll take a look at this at sunday.

**Comment by Jere100** [comment]
So i just download the new version today. But then it doesn't worked also. But i was trying again to remove the dot and put comma instead of it now it works. This trick wasn't working in the version before.
