### ISSUE TITLE
accounts not working

### ISSUE THREAD

**Issue by MixerNaji** [Lunat1q/Catchem-PoGo#2100]
If my accounts not working by catch'em bot or pokrmon go app .35v . So what is the problem, are am I banned or servers down?

I searched and each one gives different answers, I got "unable to authenticate pokemon go" message.

Any help?

**Comment by voctavio** [comment]
you are banned

**Comment by moontillaa** [comment]
Until Catchem is updated, the chances of being banned are huge.

**Comment by alanearl** [comment]
Hahaha bye2x :D

**Comment by MixerNaji** [comment]
voctavio  & moontillaa <<< how to solve it< how to unban my accounts ?

**Comment by MixerNaji** [comment]
@voctavio  & @moontillaa  <<< how to solve it< how to unban my accounts ?

**Comment by era12345** [comment]
there's no way to unban the account. email Niantic, explain everything and hope for a positive response with you accounts.
