### ISSUE TITLE
We finished the project?

### ISSUE THREAD

**Issue by cassone200** [Lunat1q/Catchem-PoGo#2101]
We finished the project? No Out No more update, there is ONLY v1.5.2.1

**Comment by Horizonne** [comment]
i believe they are still doing reverse engineering on the new features and ban detection method or at least waiting for someone to release the source code for reverse engineering results LOL... in the meanwhile we can still try bot with trash account until they get banned lol

**Comment by Pex972** [comment]
It takes time. So i'm thankful for all the job they're doing... and finally it's a game and we are cheating :)

**Comment by darkKyle** [comment]
Unfortunately I also have the feeling that the bot is dead. Will it continue? Its really the best Bot i know :( 

Or what bot do you use now?

**Comment by Wat3v4** [comment]
Have faith in Catchem :D Devs here are awesome and they gave us the best bot out there!
Just need to be patient and everything will be ok :-) 
You can always donate to motivate the dev :D

**Comment by HernestoSanchez** [comment]
Patience little grasshoper!

**Comment by alanearl** [comment]
The only disadvantage of catchem is they are so dependent on API by pogodev.org as long as the dev can't reverse engineer it there is no such thing as catchem update.
Pokeland Legends to the rescue :D

**Comment by matuszak01** [comment]
could at least warn if dropped out of the project because there are no updates for a long time and no information on how this progress, wish I could help, but my knowledge is very limited in the programming area

**Comment by icsusan** [comment]
Well...there is enough information...you just should read another posts like the following...

https://github.com/Lunat1q/Catchem-PoGo/issues/2117

**Comment by CDAGaming** [comment]
The API was cracked and release, although the head cracker quit the community shortly after, only working on his own bot, fastpokemap

**Comment by darkKyle** [comment]
oh, so this project is dead? - a pity :(

**Comment by CDAGaming** [comment]
Nope, this project can update to the newer cracked API, but if it's patches again then yea
