### ISSUE TITLE
 "not to catch"

### ISSUE THREAD

**Issue by Daredevil4** [Lunat1q/Catchem-PoGo#2102]
I have de V1.5.3.0, the function don't work. 

I've looked at the other topics on this subject,

for me the button "use pokemon to not catch filter"does not appear.

tks 4 help.

**Comment by zephiel1802** [comment]
![screen shot 2016-10-04 at 10 15 17 am](https://cloud.githubusercontent.com/assets/17824696/19061498/85e047f6-8a1b-11e6-9c3c-8bc175276a2f.png)
why not?

**Comment by Daredevil4** [comment]
i'm so sorry.

it works now

Regards!!!
