### ISSUE TITLE
does anyone knows when a new version will come out with the new API? i dont have any problem with the version 1.5.3 but i am afraid of getting ban..

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2104]

**Comment by medoamanquer** [comment]
No ETA on the new API

don't use any bot or your account will surely be flagged and banned on the next ban wave

**Comment by unknowkir** [comment]
whats ETA ? i still use the bot and runs ok for now... you mean never will be any bot again ?

**Comment by medoamanquer** [comment]
ETA means the time when something is finished
for now nobody should use bot until the new API is cracked

If you try you'll be flagged but not banned immediately
but, you'll be banned on the next ban wave

**Comment by unknowkir** [comment]
when you log in normaly but you get no usable pokestops in your area means ban?

**Comment by Cruilowa** [comment]
ETA= ESTIMATED TIME ARRIVAL
