### ISSUE TITLE
BAN

### ISSUE THREAD

**Issue by Daredevil4** [Lunat1q/Catchem-PoGo#2105]
we have detected signals from your account that suggest you are using third-party applications or modified software typically associated with cheating please be aware that the use of such software can result in the permanent banning of your account and loss of all progress in the game, at any time.

if you have been using such software, we strongly encourage you to stop

**Comment by Daredevil4** [comment]
Hi there,

this message its apear in my account!!

regards

**Comment by alfath2016** [comment]
![capture _2016-10-06-08-36-15](https://cloud.githubusercontent.com/assets/21965034/19137724/342b1a0e-8ba0-11e6-8404-b3c9003b735b.png)

**Comment by codemajor** [comment]
me 2 when i logon phone pokemon today .

**Comment by Neecoe** [comment]
I log-in this morning through my phone, something pops-up asking if im not a BOT and i have to answer question to just to determine that im not a BOT. This one, probably, detects now if someone uses a third-party application.

**Comment by Ricardodille** [comment]
this message its apear for me 2! 
i think is better stop for 2 ou 3 weeks. i really dont wanna lose my account

**Comment by Neecoe** [comment]
Maybe we just wait for the updates from the developers of the third-party app to do their expertise, maybe they could by-pass the Captcha. Let us hope. :-)

**Comment by moeison** [comment]
Ну чо там? Когда новый бот выйдет? Заебался ждать :(

**Comment by jjde06** [comment]
I also received this message on the phone, but already are two days that it remains every time I open the account, which will be permante, or has some way to get her?
And my account is legal,

**Comment by acidwae** [comment]
it appears to everyone, even my wife got that freaking message and her never used a third party program.  i think it`s a warning to tell you `see. i told you to stop (even if you never used it) .. then bang`

**Comment by jjde06** [comment]
What madness that ... the pop-up does not disappear, I'm afraid to = /

**Comment by alfath2016** [comment]
The message and capcha disapear from my phone this morning. I don't understand niantic's trick.

**Comment by Daredevil4** [comment]
for me too desapear now.

**Comment by Neecoe** [comment]
The Captcha only appears once for me, but the NOTICE is kept on popping-up everytime i log-in. But this morning, the notice already gone. I guess, that is just a reminder for us using third-party app. It doesn't mean that the notice is gone we are safe to use third-party apps again. No, cause if google trace your account again they will permanently ban your account.

**Comment by kennytcwong** [comment]
me too

**Comment by Daredevil4** [comment]
Any news about new version of Catchem?
