### ISSUE TITLE
Will this be the 'END' of Catchem?

### ISSUE THREAD

**Issue by era12345** [Lunat1q/Catchem-PoGo#2107]

**Comment by medoamanquer** [comment]
If the API is not cracked I guess so

**Comment by era12345** [comment]
Aside from the notification received from Niantic regarding the warning for using 3rd-party apps they are also looking for the possibility of enabling the Google's captcha when the app is detecting unusual behavior. Hope that the modders will be able to cracked those.

**Comment by paura123** [comment]
80% yes i guess xd

**Comment by mrbigshot29** [comment]
that captcha is a pain trying to click on the pictures when switching accounts and fighting gyms.
