### ISSUE TITLE
 required captcha at login. new update dropped the ban hammer on most accounts.

### ISSUE THREAD

**Issue by mrbigshot29** [Lunat1q/Catchem-PoGo#2109]
as reported the new update has cause catchem not to work properly. the new update has a  required captcha at login. 3 accounts banned, 2 accounts were "warned of suspicious activity associated with cheating or 3rd party software"

**Comment by atarisjay** [comment]
i created a pokemon trainer club last 3 days ago, without opening it on the phone. after bots are not working i was force to open it on my phone and i was shock that it has captcha log in already, i was warned that i am detected of using 3rd party app but not banned . so lucky. i dont know if they will use this on gmail accounts hope not

**Comment by CDAGaming** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/2111

**Comment by CDAGaming** [comment]
IT's there new security measures. I highly suggest staying off catchem for now, until when & if the new api is out

**Comment by atarisjay** [comment]
i think the security is for pokemon trainer club account user for now, i tried opening my new account that i bot which is pokemon trainer club account, before you can log on there is a captcha to prove your not bot. and luckily my account didnt get banned but it is warned that next time i will be ban.

**Comment by atarisjay** [comment]
and for the record i can still use the bot for google accounts. but i dont use it for too long maybe just 1 to 2 hours only or just by hunting some rare pokemons in my place. the captcha if for pokemon trainer club accounts only at this time

**Comment by krummelchen** [comment]
catchem is not working at all anymore it gets closed by windows. how funny is that?

**Comment by CDAGaming** [comment]
I can confirm the security has been fully activated by Niantic on google and trainer club

**Comment by User182** [comment]
Log  (Ptc) in Catchem 1.5.0.0 ; "(EGG) Incubator status update: 4,99km left
[17:49:33] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

Log in phone; No ban, not even captcha...

**Comment by CDAGaming** [comment]
BC The bot won't even run, if you got it to run & it started catching stuff you'll either get a big wrning ingame or just get banned

**Comment by grinse** [comment]
The bot is dead guys.....wake up ...

**Comment by CDAGaming** [comment]
@grinse Yes, unfortunatly the era of pgo bots is ending, unless one person find an api crack soon, all this will soon be lost
