### ISSUE TITLE
Sees PokeStops - Не видит покестопы!

### ISSUE THREAD

**Issue by Fl1mker** [Lunat1q/Catchem-PoGo#2115]
Sees PokeStops! What's the problem? - Не видит покестопы! В чём проблема?
![screenshot_2](https://cloud.githubusercontent.com/assets/22729955/19222091/1f556bd2-8e59-11e6-93ed-fa3fd626fbc0.png)

**Comment by fantomeus** [comment]
yeah this issues was already reported and maybe fix soon i hope ;)

**Comment by Meik1712** [comment]
Ich würde das Boten einstellen sonst wirst du Permanent gebannt Niantic hat die API erneuert, darum findet der auch keine Pokestops...

**Comment by xxxfjbxxx** [comment]
a galera ta usnaod ainda  o bot msms sem o api ?

**Comment by expertas** [comment]
fu
