### ISSUE TITLE
CATCHEM 1.5.3 not work

### ISSUE THREAD

**Issue by Luiz-Souza** [Lunat1q/Catchem-PoGo#2116]
Hellow Everybody.
Here the Catchem version 1.5.3.0 stopped working.
Does not catch more Pokemon or reap more pokestops.
Does anyone know what happened?

Tks!

**Comment by Oswald007** [comment]
I've the same problem

**Comment by rafaelsccp** [comment]
same problem

**Comment by iAngelG** [comment]
Read other issues and stop using the bot until it's updated. Your account will be banned in the next ban wave. The app updated killed the bot and there's NO ETA on an update yet.

**Comment by CDAGaming** [comment]
The update rather disabled the bot from further usage until a new api is vailable
