### ISSUE TITLE
version: Not Working

### ISSUE THREAD

**Issue by guilheme0890** [Lunat1q/Catchem-PoGo#2118]
Good Morning!
Can you tell me if it will still come out a new update to re-run the bot?
I thank the attention!

**Comment by lucashtw** [comment]
![capturar](https://cloud.githubusercontent.com/assets/11354908/19281919/a9a57164-8fc2-11e6-8748-38a6f2e131d0.JPG)

**Comment by doonotstare** [comment]
`closed`

**Comment by gyarados1010** [comment]
ok been looking around and just a bit of input from me im old school back in the yahoo days and they did the same thing tried to stop the bots working but it didnt work and it was all down to the good old fashion captcha code once this was programmed into thebots to allow users to use a captcha code all boots worked again just a fealing and a hunch but im saying they are using a old system and thats why no one seems to find it look back to 2007 and 2008 and captcha codes it worked on yahoo and im sure it will work with pokermon go  bots as well just a hunch like i said

**Comment by HernestoSanchez** [comment]
#2117
