### ISSUE TITLE
just a shot in the dark

### ISSUE THREAD

**Issue by gyarados1010** [Lunat1q/Catchem-PoGo#2120]
hello i like you pokermon program best one on the net just a hunch and a view from me back in 2007 and 2008 yahoo did the same thing to stop the bots being used they incorparted a captcha code so without that code the bots couldnt get into the system but once that was put into the bots they could run a muck again and flood chat rooms and bot them not sure if this will help but im old school and just throwing some ideas from my past 15 years of being around the internet and using all these different programs

**Comment by doonotstare** [comment]
What if we had it run the captcha by us so we, as humans, could enter in a responding code and continue using the modern day game shark.

**Comment by HernestoSanchez** [comment]
#2117
