### ISSUE TITLE
[00:39:18] (ATTENTION) Impossible de trouver des PokeStops dans les environs. La valeur de MaxTravelDistanceInMeters dans config.json est peut-être trop faible?

### ISSUE THREAD

**Issue by dansafran** [Lunat1q/Catchem-PoGo#2121]
[00:39:18] (ATTENTION) Impossible de trouver des PokeStops dans les environs. La valeur de MaxTravelDistanceInMeters dans config.json est peut-être trop faible?
 
![064bc60c-90e0-11e6-93e9-47971a073e14](https://cloud.githubusercontent.com/assets/14239418/19363787/08ef35cc-918c-11e6-95bc-67ba89a1b151.PNG)

**Comment by bikerdedk** [comment]
Il faut lire les autres posts... cela ne fonctionne pas car Niantic a activé la fonction anti-bot avec le captcha... les dev sont entrain de réfléchir au problème

**Comment by HernestoSanchez** [comment]
#2117

**Comment by Frenchies67** [comment]
un post en français c super cool quand on comprend rien a l'anglais

**Comment by Frenchies67** [comment]
j'ai perso utiliser le système 2 jours avant que tout soit bloquer et direct eu message pour me dire stop triche sure que j'ai merdé et pas fait les choses comme il faut.... un petit cours en français serais super si un jour cela devais refonctionner

**Comment by B1gM1k3** [comment]
Je comprends pas comment les gens peuvent continuer à botter malgré tout les avertissements. Vos comptes seront ban. Patientez.

**Comment by dansafran** [comment]
https://www.youtube.com/watch?v=9IogiNBXjZY

**Comment by dansafran** [comment]
La FIN des BOTS et des SNIPERS ? HACKS Pokemon GO FR en danger

https://www.youtube.com/watch?v=9IogiNBXjZY

**Comment by dansafran** [comment]
La FIN des BOTS et des SNIPERS ? HACKS Pokemon GO FR en danger

https://www.youtube.com/watch?v=9IogiNBXjZY

**Comment by dansafran** [comment]
Moi Français
