### ISSUE TITLE
the end of bots?

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2127]
it seems like this is the end of bots? or its take longer to crack the new API?

**Comment by CyberLykan** [comment]
It will always take some time to reverse engineer new Pokemon Go APIs.

Check back often.

**Comment by italcasa82** [comment]
It would be useful if you could have the pokemon management page, maybe even remotely. I used the bot to learn about statistics and for me this was very useful.
Now if by the bot even though locked, when I open pokemon go always asking me if I'm a computer

**Comment by doonotstare** [comment]
@italcasa82 is it asking you on android? I haven't been asked so far on iOS when i log into my legit play account or my botter accounts.
