### ISSUE TITLE
No usable PokeStops

### ISSUE THREAD

**Issue by eriicliima** [Lunat1q/Catchem-PoGo#2130]
Hello all! Could you please help me?
Everytime I try to use the program a error message appears and then nothing more happens. The message is:

> (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

I read something about my ip being blocked for a while, but it's have been 2 days and nothing change.
Does anyone know how to fix it, please?

Thanks! :D

**Comment by PoGoDex** [comment]
The program is not working nearly a month.
They blocked the bot and maps.
Apparently they are almost getting to work again.

**Comment by eriicliima** [comment]
Thank you so much! I was wondering that was something about my account or notebook! hahaha

**Comment by franklourens** [comment]
Does anyone know when it's exactly going to be working again?

**Comment by Rhyd3** [comment]
Unfortunately not of to know.
Since niantic blocked access from api stopped everything when both bot maps.
If I'm not mistaken the FastPokeMap managed to break that lock and is already working.
Maybe soon we have news.

**Comment by HernestoSanchez** [comment]
#2117
