### ISSUE TITLE
The real end of pokemon go bots?

### ISSUE THREAD

**Issue by yandraker** [Lunat1q/Catchem-PoGo#2131]
I heard a lot from everybody in many bot forums that dont worry, somebody is gonna crack the api and bots will be back, in a few days, in a week or so, and I heard of that about a month ago, and somebody a week later asked the same, and it got the same answer. But it have been a month since the new api were released, and it seems like everything is frozen, and theres no real movement about releasing the cracked api for bots developers, or even somebody working on it. I know that fastpokemap did it, but the api is not fully cracked and it wont be an open api for bots, and I dont know other group or people working on it nowadays. Somebody reading this have some information about the future of bots? Or at least have some information of the open api release?

**Comment by B1gM1k3** [comment]
A bot is "working" actually but you have to paid for. And it seems that they have problems with captcha.
Need to wait a little bit more to have "our" bot back !

**Comment by Shiukim** [comment]
All bots used necrobot api, the necrobot developers abandoned the project :(

**Comment by Lichitisky** [comment]
Its over. No more bots coming out.

**Comment by velwong** [comment]
So it has been confirmed? 
So sad.
