### ISSUE TITLE
Quand l'api sera mis à jours 

### ISSUE THREAD

**Issue by tyler22** [Lunat1q/Catchem-PoGo#2132]
Reponder moi au plus vite

**Comment by B1gM1k3** [comment]
Ta façon de demander ne donne pas envie de répondre. Bonjour ? Svp ? La politesse fait-elle partie de ton vocabulaire ?

**Comment by mamatdubitume** [comment]
elle le sera jamais a mon avis sinon sa ferais deja longtemps que tout refonctionnerais... la derniere fois juse 2 jour la plus d'un mois et aucune nouvelle !!
