### ISSUE TITLE
New API \o/ Catchem will return

### ISSUE THREAD

**Issue by valdirljr** [Lunat1q/Catchem-PoGo#2133]
https://pogodev.org/

![image](https://cloud.githubusercontent.com/assets/558397/19983533/8a4757b0-a1f1-11e6-8fe0-ead674a31956.png)

**Comment by beloware** [comment]
Still here, still wait, go for it! Free pikachu :+1:

**Comment by Spk345** [comment]
Lunatiq,  bay101 and I have all be working on getting set up with the current method. We will return as soon as we've got everything running and sorted out. The method requires a lot of changes to catchem application.
