### ISSUE TITLE
bot working, but.....

### ISSUE THREAD

**Issue by watcht** [Lunat1q/Catchem-PoGo#2134]
the bot "POKEFARMER" is working with POGO 0.43 but you have to pay to use it :-1:  
The news is one bot is working and maybe developers like Catchem-PoGo make a free bot :+1:  I really hope it :)

**Comment by NeFShARk** [comment]
It's somewhat working! They are experiencing captcha problems! So not a 100% stable.

**Comment by watcht** [comment]
That's true... but if the bot works it means that they have the API :) a little hope for us.

**Comment by wiselytan333** [comment]
PGBot is working

**Comment by TomanPCM** [comment]
mchristopher/PokemonGo-DesktopMap is working again :-)
