### ISSUE TITLE
PGBot and NinjaBot Working!!!

### ISSUE THREAD

**Issue by phelix8** [Lunat1q/Catchem-PoGo#2135]
Hi everyone, well, both bots are working right now and with no troubles.

**Comment by ArchangelBr** [comment]
Go to discord

**Comment by TomanPCM** [comment]
NinjaBot work, but i wait for Catchem, is best, i love it :)

**Comment by NeFShARk** [comment]
I'll also wait for Catchem, it's a lot better than ninja.

**Comment by hihowru1987** [comment]
Catchem forever , no one can replaced TT
