### ISSUE TITLE
Catchem crash upon start

### ISSUE THREAD

**Issue by iamvertigo** [Lunat1q/Catchem-PoGo#2139]
Catchem crashes upon start and leaves a catchem.json file in de directory.
Installed in a fresh and empty directory. Only copied the "old" profile directory.

{
  "$type": "Catchem.Classes.CatchemSettings, Catchem",
  "ProviderEnum": 0
}

**Comment by ArchangelBr** [comment]
try with a new copy of catchem, with no profile, just to see if the problem is that

**Comment by iamvertigo** [comment]
Some files were accidentally left form an older version. A Verry  verry clean install did the trick :-)
