### ISSUE TITLE
play Catchem

### ISSUE THREAD

**Issue by loppy16** [Lunat1q/Catchem-PoGo#2143]
i did catch a few but the little guy stops for a few mins and then I get a lot of Attention google api key is empty.

**Comment by watcht** [comment]
the same....

**Comment by Mingo1** [comment]
Go to Wiki Setup Guides : https://github.com/Lunat1q/Catchem-PoGo/wiki/Setup-Guides
U need  a routing service api key. Choose one of below of your choice:

Google API Key: https://developers.google.com/maps/documentation/javascript/get-api-key
Mapzen Unified API Key: https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key
