### ISSUE TITLE
label which api version the app is using

### ISSUE THREAD

**Issue by zectvim** [Lunat1q/Catchem-PoGo#2147]
hello, would appreciate if you can label which api this app is using so that we can stop using when new api is being forced. to minimise likelihood of being banned. 

for example, is 1.6.0.0  build 3.7z using .43 api or .45 api?

i understand that .45 api has been forced a few hours ago, but 1.6.0.0 was released 18hrs ago. 

thanks

**Comment by Bay101** [comment]
Hi @zectvim, Will look at putting an Alert or lockout feature in for next update

**Comment by zectvim** [comment]
thanks for the response. looking forward to the next update

**Comment by Spk345** [comment]
Added to current version, next version will check with Niantic to alert when API is pushed when Devs are offline.
