### ISSUE TITLE
actualizar catchem

### ISSUE THREAD

**Issue by lukita83** [Lunat1q/Catchem-PoGo#2149]
Disculpen mi ignorancia ya que no estoy muy interiorizado al respecto.
Como actualizo a la nueva versión el catchem? con el source code? como debo ejecutarlo?
Por favor si alguien puede ilustrarme le estaría muy agradecido.

**Comment by Furtif** [comment]
Hola, descarga la version 1.6.0.0 aqui: https://github.com/Lunat1q/Catchem-PoGo/releases

saludacions

**Comment by lukita83** [comment]
gracias furtif. Entiendo que desde este link puedo actualizar catchem. Mi pregunto es como lo hago, ya que solo veo para descargar "source code"
Cómo utilizo el source code?


furtif thanks. I understand that from this link I can update Catchem. My question is how I do, because I see only download "source code".
How do I use the source code to update.

**Comment by User182** [comment]
Bajaron el link por problemas con la Api, paciencia.

**Comment by di3go1** [comment]
@lukita83 El dev removió el link de descarga pues por el force update de la api a la 0.45.0 ya no es recomedable usar el catchem, hasta que este nuevamente actualizado a esta.

**Comment by Furtif** [comment]
Niantic Entender que permite al cliente 0.43.3 conectarse a prohibir en la próxima banwave. 0.43 Los clientes oficiales se ven obligados a actualizar ahora. Es mejor esperar a que su actualización.

saludos
