### ISSUE TITLE
API Calls

### ISSUE THREAD

**Issue by Ellebis** [Lunat1q/Catchem-PoGo#215]
(ERROR) Niantic Servers unstable, throttling API Calls. What this is mean? I have to worry about that?

**Comment by standujar** [comment]
This appear every 30minutes, always 30minutes, my solution is to put the max catch per hour to 30 and the max pokestops to 35. (In case that your playing in central park / mannathan)

You need to test it, let go for some 30 min session and check how many pokemon/pokestop you can take in 25 min and modify your settings :D.

if dev could just add a row : max time botting before stop :D
