### ISSUE TITLE
where is the executable file of version 1.6.0? 

### ISSUE THREAD

**Issue by shouwei** [Lunat1q/Catchem-PoGo#2151]
Hi there,

where is the new program for 1.6.0? I saw the new version has released but did not find it.

Does any one would like to show me the link?

Thank you so much!

**Comment by CellTheFake** [comment]
I need too!!! Please.

**Comment by NeFShARk** [comment]
The api for pokemon go was updated once again, because of this the download of the executable was removed.

**Comment by CellTheFake** [comment]
Thanks!!!
