### ISSUE TITLE
Ou puis-je télécharger la nouvelle version svp?

### ISSUE THREAD

**Issue by benp100** [Lunat1q/Catchem-PoGo#2153]
Bonjour, j'aimerais télécharger la nouvelle version mais je vois que source code, quelqu'un aurait idée? Merci ;)

**Comment by Furtif** [comment]
Bonjour, bonsoir, Veuillez attendre la version courant utilise api 0.43.3 la version 0.45.0 api est en train de se mettre a jour. Merci

**Comment by benp100** [comment]
D'accord, merci pour cette réponse ultra rapide ;)
