### ISSUE TITLE
Stuck at Idle

### ISSUE THREAD

**Issue by NumberXer0** [Lunat1q/Catchem-PoGo#2154]
Bot was working fine yesterday, but now does nothing. No settings were changed. It just sits on "Idle"

**Comment by fantomeus** [comment]
API updated, just wait the come back from lunatik and catchem will be updated

**Comment by NumberXer0** [comment]
Even with the latest update and latest API, still stuck on idle.

**Comment by Spk345** [comment]
You need a Routing Key. If you do not have a Routing key, your bot will not move. It cannot path.

Get [Mapzen Unified API Key](https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key).
Super simple, follow the wiki's instructions and your bot will move.
