### ISSUE TITLE
mapzen valhalla api key is empty

### ISSUE THREAD

**Issue by benp100** [Lunat1q/Catchem-PoGo#2157]
I got this message non stop after the bot caught 2 pokemon and visit 1 pokestop, and the bot look like to be stuck. Do i have to set mapzen obligatory? Thx for answer

**Comment by misterionl** [comment]
try to make a route, by routecreator, that will work

**Comment by benp100** [comment]
Arff, there any way for make that bot working without set mapzen ot route creator? In old version, i didnt need to set anything. My english is bad and everything is explain in english :( thx for answer!

**Comment by misterionl** [comment]
what is your languge, where are you from ?
you can select another language

**Comment by benp100** [comment]
French, i understand i need a password on github so i have to register and paste code in catchem but if i want to run 5 bot at same time, do i need to use the same mapzen code for each bot? If not how i can get different mapzen code for each?

**Comment by misterionl** [comment]
just google translator
How do you mean need a code?
do you use your account just what you use on your phone?
You can change the language in the upper right where English is


juste google traducteur
Comment voulez-vous dire besoin d'un code?
utilisez-vous votre compte tout ce que vous utilisez sur votre téléphone?
Vous pouvez changer la langue en haut à droite où l'anglais est

**Comment by benp100** [comment]
Ok google traduction is very bad loll, ok so, can you explain me how to configurate mapzen for 5 bot running at the same time because at the moment if i select google direction i got (Attention) google api key is empty, openls, same thing and 2 other one same thing to

**Comment by benp100** [comment]
Thx for answer, im from quebec, canada

**Comment by misterionl** [comment]
5 games I do not know how, think you can ask better managers

**Comment by benp100** [comment]
I just see 1 min ago on discord server you can use the same mapzen key for each bot, can some one confirm pls? Thx! ;)
