### ISSUE TITLE
Bot went crazy

### ISSUE THREAD

**Issue by beloware** [Lunat1q/Catchem-PoGo#2158]
It went crazy, i attached a pic. It did it within seconds, after finished forced move.
![error route](https://cloud.githubusercontent.com/assets/21278576/20246335/2799d5d6-a9b5-11e6-9042-fe01f0f72798.jpg)

**Comment by TheBotter** [comment]
This bug also happened to me, I finished force move and it went crazy like that

**Comment by Spk345** [comment]
Update to the latest build, this issue was corrected for an hour after initial release.

**Comment by beloware** [comment]
I am useing this release:
https://github.com/Lunat1q/Catchem-PoGo/releases/download/1.6.1.0/Catchem_1.6.1.0_build2.7z

I can not find newer version.
Thanks.
