### ISSUE TITLE
Os habeis olvidado de poner español como idioma 😭

### ISSUE THREAD

**Issue by ercolocao** [Lunat1q/Catchem-PoGo#2159]
Porfavoor la version 1.6.1 no trae el español como idioma podrian arreglarlo plisss

**Comment by ercolocao** [comment]
Vale ya esta arreglado Tienes q cojer la version anterior que tengas vas a la carpeta config y donde pone ulenguajes copia el archivo que pone español y lo copias en el catchem nuevo en la carpeta config ulenguajes y listo ya saldra en español

**Comment by di3go1** [comment]
O esperar el siguiente Build ¯\_(ツ)_/¯
