### ISSUE TITLE
stays idle

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2161]
after a while the bot stays idle mode not walking or catching pokemons

**Comment by NumberXer0** [comment]
Same here, even after updating.

**Comment by Spk345** [comment]
Do you have a routing service? No?

Get [Mapzen Unified API Key](https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key)

If you still continue to have issues, please join us on Discord:
[![Join our Discord Server](https://discordapp.com/api/guilds/212977806819196938/widget.png?style=banner2)](https://discord.gg/pPwxX8Q)
