### ISSUE TITLE
Throttling the server

### ISSUE THREAD

**Issue by altanarium** [Lunat1q/Catchem-PoGo#2162]
Hello Guys,

I have this on my 2 accounts.
I didn't bot when there was an API change (few weeks ago and the recent one).
I changed the hardware to iPhone.
I don't know what the problem is, i didn't receive any ban email or something.
Check the screens please.
![throttle](https://cloud.githubusercontent.com/assets/21957033/20247905/f2ddaf6a-a9d8-11e6-9d1c-cb5ffd24d34a.JPG)

![delays](https://cloud.githubusercontent.com/assets/21957033/20247691/20363f82-a9d3-11e6-8b46-b1c87cdd3721.JPG)

**Comment by Broxxx3** [comment]
Same here

**Comment by beloware** [comment]
This is ban. Get over it.

**Comment by altanarium** [comment]
Thought a ban was different >.<

**Comment by altanarium** [comment]
Just checked with a different phone and it is indeed banned >.< can be closed! Thanks
