### ISSUE TITLE
[BUG] Routing APIs are empty.

### ISSUE THREAD

**Issue by CyberLykan** [Lunat1q/Catchem-PoGo#2164]
MobBot, GoogleDirections, Mapzen, etc. 

They all say the "API Key is Empty!"

Bot refuses to continue.

**Comment by benp100** [comment]
Same here!

**Comment by Spk345** [comment]
[Mapzen Unified API Key](https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key)

Catchem requires a Routing service to path correctly. Please follow the wiki and remember to save your settings.
