### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by vladseverrr** [Lunat1q/Catchem-PoGo#217]
![6](https://cloud.githubusercontent.com/assets/21099923/17781258/4f707326-6577-11e6-81c5-64f17823056c.png)

**Comment by standujar** [comment]
Its you proxy... just try another one ;) proxy works ;)

**Comment by vladseverrr** [comment]
In version 1.3.2.1 comes through the proxy .

**Comment by vladseverrr** [comment]
![8](https://cloud.githubusercontent.com/assets/21099923/17781459/16567210-6578-11e6-9d98-20801a6fef32.png)

**Comment by vladseverrr** [comment]
Help me to understand. After any proxy writes ...

**Comment by vladseverrr** [comment]
Если я по русскому напишу, меня кто нибудь поймёт?)

**Comment by standujar** [comment]
Well, the thing dont trust to "Proxy test" sometimes it tells that it works fine but proxy still not working properly.. just try others proxy and tel me if it work, i'm using 1.4.0.0 rev.

**Comment by vladseverrr** [comment]
Set all of the new , I introduced all bots - proxy works! Thank you!
