### ISSUE TITLE
Catchem [Build 1.6.1.0] crashes upon startup!

### ISSUE THREAD

**Issue by iacodalla** [Lunat1q/Catchem-PoGo#2173]
Catchem [Build 1.6.1.0] crashes upon startup!
It doesn't even load the interface.

Here is my [http://pastebin.com/zPrtWvnX] dump file about the Event Viewer Errors.
On the contrary, Build 1.4.9.4 can be opened without issues.

Thanks for your help

**Comment by devgraal** [comment]
Maybe you could first try to update your .net release ?

**Comment by iacodalla** [comment]
it's already the latest
![image](https://cloud.githubusercontent.com/assets/23451598/20263394/c71de2ee-aa66-11e6-866e-2d7ef54b2628.png)

**Comment by iacodalla** [comment]
Hi guys, anyone can help?
I have the same crash even with the new release

**Comment by Spk345** [comment]
You need Catchem to be on the same drive as Windows, as it uses MSCORLIB (Microsoft Common Object Runtime Library) which is in Every Single Windows installation. Catchem cannot communicate with those necessary dependencies if it's on another drive/partition.

**Comment by iacodalla** [comment]
Thanks for the help.
Unfortunately it's still not working.
I redownloaded the latest relase and I've unzipped it into the windows folder just to be sure.
Here's the errors I get: [http://pastebin.com/8n67NHPZ].
![image](https://cloud.githubusercontent.com/assets/23451598/20381249/e9449e3e-aca6-11e6-9050-75a02ff3cee5.png)

I rechecked with the previous release and I can open it without errors.

![image](https://cloud.githubusercontent.com/assets/23451598/20381275/0c92e17a-aca7-11e6-9f77-96c484dcd95c.png)
