### ISSUE TITLE
crash (1.6.1.1)

### ISSUE THREAD

**Issue by afiuq** [Lunat1q/Catchem-PoGo#2180]
the bot keep crushing after several minutes running. tried compatibility mode with win 7, 8, and 10. the results are still the same.
[Catchem-2016-11-14-21.txt](https://github.com/Lunat1q/Catchem-PoGo/files/589683/Catchem-2016-11-14-21.txt)

**Comment by devgraal** [comment]
Running release 1.6.1.1 under Win7-Pro is the same: bot keep crashing after a while. Running 1.6.1.0 without any issue.
If there is some thing I can provide to help, let me know :)

**Comment by B1gM1k3** [comment]
Have a lot of crashes too. Even if running just 1 profile.
