### ISSUE TITLE
error, cant solve

### ISSUE THREAD

**Issue by kilado94** [Lunat1q/Catchem-PoGo#2182]
could someone help me_
what this error means_
http://prntscr.com/d79l4l

**Comment by devgraal** [comment]
What is Mapzen Routing? Why is Mapzen routing key empty? Mapzen Routing services needs to be individually setup by you, the user. Your key can be used across multiple bot profiles. Get a Mapzen unified key for both altitude and routing service, follow the instructions here: https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key

1) Go to the Mapzen Developer site.
2) Sign in with a GitHub Account by clicking on the "Continue with github" button in the middle of the page.
3) To the right of Mapzen Keys, click on the "+ New Key" button, to generate an API Key.
4) Copy Key from Mapzen that was just generated.
5) Launch Catchem and go to the settings page for the bot you wish to use Mapzen with.
6) Check the use Mapzen API Elevation box.
7) Change Routing Service to Mapzen Valhalla.
8) Enter the code copied from the Mapzen website into the "Mapzen API Key" Field.
9) Save your settings.

This is from Discod.
Regards,

**Comment by kilado94** [comment]
thankz
