### ISSUE TITLE
Just Got Ban

### ISSUE THREAD

**Issue by ToxicOwl** [Lunat1q/Catchem-PoGo#2183]
I am testing your bots for a long time never had a problem or getting ban. But today something wrong happened and i got ban. I never got a captcha pop up .If you need any file/configs etc  Let me know..I used just your bot on a testing account.
(Btw I use the same old configs )
DON"T USE YOUR MAIN ACCOUNT!

**Comment by kennytcwong** [comment]
My account banned too

**Comment by CyberLykan** [comment]
Accounts probably got flagged. Make a new one.

**Comment by TheLeoSouza1** [comment]
Is it safe to use? I wanna get Lapras to fill my Pokedex, but I'm affraid to lose my account.

**Comment by unknowkir** [comment]
mine too.. my second account just got banned... but I have another account that works fine

**Comment by ToxicOwl** [comment]
I will make a new account and see what's happening

**Comment by Atmorigasil** [comment]
Got my bot running for over a day now, old account

**Comment by stdxyzgithub** [comment]
My two account got banned too...

**Comment by andnyue** [comment]
Do u move to fast?
I move min 1 and max 7. Max pokemon and pokestop 25 per h, nvr get banned since first time i use this catch em. And i also use schedule..

**Comment by ToxicOwl** [comment]
Nop i done...maybe i got the Captcha and was buged

**Comment by Spk345** [comment]
Using Bots is never 100% safe, and you should never bot an account you don't want to lose. We aren't held accountable for your changes to settings or using our bot in general. If you had received a Captcha, Catchem would have alerted you, and paused the bot.
