### ISSUE TITLE
[Feature Request] A safe way to export profile

### ISSUE THREAD

**Issue by velwong** [Lunat1q/Catchem-PoGo#2189]
I have several profiles with different set up requirements. 
I used to copy the profile folders into the new ones.
But is that the correct way to do it? I am afraid that there might be some new features added in each update that my method may crashes the bot. Wonder if there is a safer to export and import the profiles. Otherwise, I will be resorted to recreating the profiles and go through all the hassle in the Poke list settings all over again for each of them.

**Comment by Spk345** [comment]
We recommend Copying Newest Release over Older Releases folder. It's the easiest and simplest way to update.
