### ISSUE TITLE
Bug Pokeball

### ISSUE THREAD

**Issue by phelix8** [Lunat1q/Catchem-PoGo#2192]
![bug](https://cloud.githubusercontent.com/assets/21318785/20312530/932192b6-ab32-11e6-98f5-7b9b034d8f57.JPG)

When the Pokeballs are empty on my inventory, throw error if the bot it's set with this item to use. So when set another ball like "superball" it works again. Pay attention with it, could be dangerous and take ban.

Saludos from Chile

**Comment by altanarium** [comment]
I had this today also

**Comment by shanishkag** [comment]
1t time i had it today  :(

**Comment by kacper4895** [comment]
can you explain how to fix it please

**Comment by Spk345** [comment]
Update to the Newest Release.
