### ISSUE TITLE
[Bug?] Possible Solved Issue -Evolve failed..

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2198]
(EVOLVED) Failed Rattata. Result was FailedPokemonMissing, stopping evolving Rattata.. I got that message for every pokemon not only rattata

**Comment by CrazyMonkeyy** [comment]
Pls full logg/screen

**Comment by unknowkir** [comment]
![capture](https://cloud.githubusercontent.com/assets/22404190/20324528/9b0d5ba2-ab89-11e6-85f5-2c4c6be7bff0.PNG)

**Comment by unknowkir** [comment]
[Catchem-2016-11-15-22.txt](https://github.com/Lunat1q/Catchem-PoGo/files/593199/Catchem-2016-11-15-22.txt)
LOG file

**Comment by CrazyMonkeyy** [comment]
U got evolve at iv 95 drop it to 1 if u wanna evolve ALL


2016-11-15 22:52 GMT+01:00 unknowkir <notifications@github.com>:

**Comment by Spk345** [comment]
What version of Catchem? This was a known issue with 1.6.1.1.

**Comment by unknowkir** [comment]
now I have the latest 1.6.1.2 and its ok.. do u know why I got the captcha window almost all the time but It didn't work and I am loging with my phone to solve the problem

**Comment by Spk345** [comment]
Your settings suck? I have run 9 accounts for two days, 6 of them being old map scanning accounts and I have YET to get a captcha on any of them. This is with Default Catchem Settings.

**Comment by unknowkir** [comment]
can you please tell me the settings for not getting the captcha? or it maybe the device problem? I mean that I hane note4 and I don't know hot to enter my device settings on the bot..
