### ISSUE TITLE
 It's asking Captcha

### ISSUE THREAD

**Issue by ClaudinCS** [Lunat1q/Catchem-PoGo#2199]
The program stops asking for captcha.
Anyone else with the same problem?

PS.:Take care of my bad English!
.

**Comment by serginhoo** [comment]
I have the same problem :(

**Comment by ClaudinCS** [comment]
Solution I found here was log in the account by phone and solve the captcha.

**Comment by serginhoo** [comment]
Thanks !

**Comment by pctan9** [comment]
I reckon that account will be banned very soon, if you get the second captcam
