### ISSUE TITLE
Catchem Bot traduced entierely in French Language

### ISSUE THREAD

**Issue by AllsGamingHD** [Lunat1q/Catchem-PoGo#220]
Français : 

Salut,
J'ai traduit le BOT en français pour les utilisateurs français qui utilisent le BOT qui est excellent ! :)

J'ai ajouter le temps de pause sur le BOT quand il à capture tous les pokémon / pokéstop par heure. ( je n'est pas encore tester cette fonction ej suis actuellement en train de faire le test ! ) :).

Seul élément non traduit c'est les pokémons. j'ai contacté le dev pour éssayer de trouver une solution :).

Lien de catchem bot traduit :
https://www.dropbox.com/s/5r5sjcyiuku3rqi/Catchem%20FR%20-%20Traduit%20par%20AllsGamingHD.rar?dl=0

Je vous souhaite une agréable journée.
Aurevoir.

English :

Hello,
I translated the BOT in French for French users using the BOT is great! :)

I add the pause on the bot when to capture all pokemon / pokéstop per hour. (I do not test this function ej am currently doing the test!) :).

Only untranslated element is the Pokemon. I contacted the dev to try to find a solution :).

Link bot Catchem translated:
https://www.dropbox.com/s/5r5sjcyiuku3rqi/Catchem%20FR%20-%20Traduit%20par%20AllsGamingHD.rar?dl=0

I wish you a good day.
Goodbye.

**Comment by standujar** [comment]
Le soucis c'est pour les MAJ, il y a la 1.4.1.0 qui viens de sortir..

**Comment by standujar** [comment]
EDIT : Je viens de test, j'ai recup ton dossier Translations que j'ai remplacer par celui officiel, ça fonctionne, tout est en FR :)

**Comment by AllsGamingHD** [comment]
Salut, 
Il s'agit bien de la version qui est sortie cette dernier temps.
Un plaisir :) 
Faut penser à la communauté française il à que des Dev anglais donc des bot souvent que en anglais :/

**Comment by standujar** [comment]
Ah autant pour moi, cela ne fonctionne que pour le cmd (terminal) pas pour les settings / nom des pokemon... faut il vraiment le compiler pour l'avoir en FR ? impossible de corriger le probleme des translations ?

**Comment by AllsGamingHD** [comment]
Oui les translations marche juste pour la console. :/
Pour le moment oui
je suis en contact avec le Dev la pour pouvoir traduire les pokémons

**Comment by standujar** [comment]
S'il est possible d'appliquer le translate sur la totalité des composantes sans devoir recompiler ça serais trop qu'il intègre ton travail ;) merci encore

**Comment by standujar** [comment]
Au passage, ajouter un paramètre de déconnexion reconnexion tout les 28 minutes ! Afin d’éviter l'erreur inconnu à ce jours (pour éviter les risques) : Niantic troubles ;) qui interviens chaque 30 min

**Comment by AllsGamingHD** [comment]
Je lui est demander pour m'aider pour traduire enfin trouver comment traduire les pokemons il ma dit de chercher :/ donc bah vous devrais attendre que je trouver j'espere.

Je savais pas sa une déconnexion à 28min et reconnexion 2 minutes après ?

**Comment by standujar** [comment]
En fait, chaque 30 min, un message d'erreur niantic rouge apparait qui indique un probleme de connexion sous forme de warning, etant donné que cela interviens toute les demi heures et que nous ne savons pas a quoi cela est du, faire une deconexion toute les 28 min, permet d'eviter d'avoir ce message ! Donc il serait bien d'ajouter cette fonction ! Tu comprends ?

**Comment by AllsGamingHD** [comment]
Oui d'accord je comprend je vais essayer de faire sa ;)
J'avais remarquer se message d'erreur mais Niantic unstable API un truc du genre mais je savais que c'était tous les 30Min 
je vais essayer d'ajouter un timer automatique à activer ou désactiver si la personne le veux ou non ;)

**Comment by adriendillens** [comment]
Salut les gars! 

@AllsGamingHD Bien joué pour la traduction ;-)
Pour les noms des items / pokemons c'est juste un JSON non ? 
-> qui est dans : Catchem / config / translations / translations.fr.json
Quand ta traduction sera codée à 100%, tu pourras faire un pull request via git. ;-)

@standujar Et en effet, cette erreur toutes les 30 minutes, je confirme, je l'ai aussi. Pour se la jouer "safe" ça serait bien de faire une déconnexion - reconnexion comme @standujar l'a proposé.

**Comment by AllsGamingHD** [comment]
@adriendillens Merci :)

Non pas du tout le dev ma dit qu'il faut chercher dans le dossier Extension et le fichier Converter.cs & Extension.cs ensuite que je code une façons de renommer les pokémons.

Le dev ma dit qu'il ne voudrait pas publier mon application traduite je vais le faire moi même pas grave.

Et pour la déconnexion je commence à travaillez dessus : 
http://prntscr.com/c7engw

**Comment by AllsGamingHD** [comment]
Pour ceux qui est du timer en quelque sorte j'avais déjà fait une version pour NecroBot.
https://www.dropbox.com/s/z8cuiwl4yomyda5/NecroBotTimer.exe?dl=0

http://prntscr.com/c7eow8 & http://prntscr.com/c7ep9z

Les heures sont pas en 24h mais en 12h.

**Comment by adriendillens** [comment]
@AllsGamingHD Ok !

Oui je vois ^^. Sinon il va livrer une release en FR par défaut.
Je viens de chercher vite fait dans le code et je crois avoir trouvé le fichier où le dev fait le mapping (clé : valeur) entre les fichiers de traduction json ET des objets métier python (clé : valeur):
 Catchem-PoGo/PoGo.PokeMobBot.Logic/Common/Translations.cs

Je ne pense pas que ce soit ce fichier a modifier, mais ça peut t'aider à comprendre la logique...

Pour ce qui est du timer, je vois que tu as déjà une certaine expérience en la matière ;-)
Bon courage, et merci beaucoup !!!

J'ai tellement envie d'aider à développer, mais c'est le temps qu'il me manque ;-)

**Comment by standujar** [comment]
@AllsGamingHD je suis preneur de ta version FR + Timer + Logon/off 28min. Tiens moi au courant :)

**Comment by standujar** [comment]
Très peu de temps pour dev, c'est vraiment sympa de ta part de t'en occuper :)

**Comment by standujar** [comment]
Au passage, effectue le avec la 1.4.1.0 :D

**Comment by AllsGamingHD** [comment]
@adriendillens Oui mais je pense pas il a pas l'air intéresser

Oui bonne recherche mais c'est pas sa ! :/ http://prntscr.com/c7f61h tous les pokémons je les est traduit ici et rien ne change! :(.

Oui je suis débutant je me dermerde lol ^^

Dommage merci à toi je boss c'est plus compliquez le WPF que Windows Forms je code jamais en WPF ^^ donc sa me prend plus de temps à trouver la solutions

**Comment by AllsGamingHD** [comment]
@standujar pff il à resortie une release il veux me tuer xD
a chaque release je doit tous retraduire 1 par 1 je sais pas si je vais pouvoir faire toutes les release...
Je vais finir cette release je vais attendre qui sorte la vrai release car la c'est une PRE-RELEASE. ;)

**Comment by standujar** [comment]
Oui, c'est une bonne solution :) !

**Comment by BrYcOu** [comment]
t'as essayé le fichier : POGOProtos/Enums/PokemonId.cs ?

**Comment by AllsGamingHD** [comment]
@BrYcOu T'es la aussi ^^
Quand je change je vois pas de changement non plus :/

**Comment by AllsGamingHD** [comment]
@standujar cette option ne regle pas ton probleme de niantic api tous les 30Min ? par harsard 
![image](https://cloud.githubusercontent.com/assets/21060448/17788420/e657e5d8-658d-11e6-8fb3-36efe828d801.png)

**Comment by superdevil669** [comment]
Bonsoir, beau travail de traduction. Pourquoi ne pas proposer ton boulot au dev et mettre un petit drapeau dans l'interface pour choisir la langue désiré ce serai cool.

**Comment by BrYcOu** [comment]
quand tu changes PokemonId.cs t'as même pas un changement dans les listes déroulantes dans paramètres ?

**Comment by AllsGamingHD** [comment]
@superdevil669 le dev n'a pas l'air si intéresser.. http://prntscr.com/c7g5z6 / http://prntscr.com/c7g62c
@BrYcOu  Rien :/

**Comment by superdevil669** [comment]
Dommage et je ne comprends pas pourquoi il met les fichier json de traduction du nom des pokemons  puisque chez moi cela ne fonctionne pas ils ne sont pas traduit !

**Comment by AllsGamingHD** [comment]
C'est les fichier necrobot ;)

**Comment by AllsGamingHD** [comment]
J'ai bientôt fini de faire l'auto extinction :) :dash:

**Comment by AllsGamingHD** [comment]
http://prntscr.com/c7gp4r Je test si c'est bon je publie ;)

**Comment by standujar** [comment]
Ok super. Est-ce que ça ne reset pas la déco de limiter pkm / pokestop par heures ?

**Comment by AllsGamingHD** [comment]
@standujar SI ! :/ mais la j'ai arrete de coder je suis en train de coder depuis chez pas quelle heure donc je continue demain parce que c'est pas encore au point.

**Comment by standujar** [comment]
Ouai pas de soucis. Je regarde un peu partout pour ce warning niantic sur des forum allemand.. italien.. personne ne sait à quoi cela correspond

**Comment by AllsGamingHD** [comment]
Sur necrobot sa marque Niantic API Unstable quand j'ai cette sorte d'erreur surment quand les serveur sature ?

**Comment by Lunat1q** [comment]
1 more non english issues and i'll go closed source, i warned.
