### ISSUE TITLE
(Error) Niantic Servers unstable, throtting API Calls.

### ISSUE THREAD

**Issue by techdosm** [Lunat1q/Catchem-PoGo#2200]
After i login to my account, when it mention about the Lat & Lng are right. This error message pop out.

Please help! Using Catchem_1.6.1.1_build2.7 

Thanks :)

**Comment by brianwong66** [comment]
you got banned

**Comment by janhm** [comment]
Also when "no ban" email have been sent?

**Comment by Spk345** [comment]
Yes, because Niantic is great about getting emails to those who have been banned. Check it on your phone if you don't trust us.
