### ISSUE TITLE
Wrong pokemon quantity

### ISSUE THREAD

**Issue by Zelendar** [Lunat1q/Catchem-PoGo#2203]
Hi, comrade =)

Bot is showing wrong pokemon quantity. It shows only 40 pokemons (and 5 eggs ^^) in my inventory, but also can not catch new pokemons, because 
[11:19:44] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[11:19:45] (INFO) [Inventory] Pokemon Stored: 40/250
In GUI bot also is showing only 40 pokemons.
I`ve entered the game and noticed, that pokemon inventory is really full - about 250 pokemons.
If i manually transfer one of 40th pokemons in bot or any from PokemonGo client, bot is catching one more pok and begin to spam same error about full inventory.
Autotransfer is on, settings are right.
Where is the problem?

**Comment by andnyue** [comment]
Try Close Catchem and reopen, usually it cant refresh by itself

**Comment by Zelendar** [comment]
Thx
i`ve transfered manually till 63 pokemons from my smartphone and rebooted PC. Now bot see correct numbers. 
Problem is solved but i`ll leave issue opened for some time.
