### ISSUE TITLE
Dump doesn't work 

### ISSUE THREAD

**Issue by dexxlab** [Lunat1q/Catchem-PoGo#2204]
Hi, 

Is it possible to reintroduce dump of pokemons stats ?
I modify the config file 
    "DumpPokemonStats": true,
    "AmountOfPokemonToDisplayOnStart": 350,

but no dump folder and no dump files...

Thank you very much for your work and for your response.

**Comment by Spk345** [comment]
....

It works just fine.
![Console](http://s11.postimg.org/i4lq6wetf/screenshot_85.png)
![In LOG](http://s11.postimg.org/jraxs4qv7/screenshot_87.png)

It's exactly the same place it has always been.
