### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by Cr0ss0v3r** [Lunat1q/Catchem-PoGo#2206]
When i start the Bot it just goes to the Login and shows :
(INFO) Logging in using account Ptc
Nothing is happening afterwards.

**Comment by B1gM1k3** [comment]
Probably bad password. Try it on ptc website to check it.

**Comment by Cr0ss0v3r** [comment]
No i found the mistake the Account was not activated.

Am 16.11.2016 5:13 nachm. schrieb "B1gM1k3" <notifications@github.com>:
