### ISSUE TITLE
Help with Captcha please ^^

### ISSUE THREAD

**Issue by B1gM1k3** [Lunat1q/Catchem-PoGo#2207]
Hi guys,
I have my first Captcha popup and impossible to see it !

When clicking on Chrome, nothing happens and if i choose Firefox, i have this 👍 

![2016-11-16_13h27_05](https://cloud.githubusercontent.com/assets/21138302/20354696/4d0a71f6-ac1f-11e6-9829-6528ff89d4f7.png)
![2016-11-16_13h27_21](https://cloud.githubusercontent.com/assets/21138302/20354699/4fa6ea16-ac1f-11e6-8011-8e03f215460b.png)
![2016-11-16_13h27_42](https://cloud.githubusercontent.com/assets/21138302/20354701/5123256c-ac1f-11e6-9f99-aeb66907e46c.png)

Finally, Firefox cannot display the Captcha.

**Comment by shanishkag** [comment]
iv got it today too but it works fine with firefox.. but first time it was crashed

**Comment by ClaudinCS** [comment]
Solution I found here was log in the account by phone and solve the captcha.

PS.: Be careful where the bot is located and where you will log in on the phone

**Comment by shanishkag** [comment]
better switch of gps

**Comment by B1gM1k3** [comment]
Account will be flag because phone and Catchem device ID are differents.....

**Comment by saturitos** [comment]
CAPTCHA DONT WORK I HAVE THE SAME ID DEVIDE IN CATCHEM AND IN MY ANDROID DEVICE

**Comment by shanishkag** [comment]
but this catchem is not a android apk.. this is a iso ap RE version.. so better keep in iso details

**Comment by saturitos** [comment]
my id device in catchem is the same id device on my phone

**Comment by Spk345** [comment]
Solve Captcha on mobile device with location services off, this is a known issue. We are currently working on stability. Doesn't matter if your Device ID isn't the same between catchem and your phone. Most people own multiple devices, so who cares.

Also Catchem and ALL BOTS/MAP/SNIPERS run on IOS not Android info.
