### ISSUE TITLE
Error de captura

### ISSUE THREAD

**Issue by trampero** [Lunat1q/Catchem-PoGo#2208]
Como dice el titulo el bot me funciona perfecto pero me tira este error muy seguido y no captura al pokemon, luego de 4 o 5 errores sigue  funcionando bien hasta que me vuelve a salir el mismo error

**Comment by Spk345** [comment]
That's a known issue with version 1.6.1.1. Update to the newest version on here.

Eso es un problema conocido con la versión 1.6.1.1. Actualización de la versión más reciente aquí
