### ISSUE TITLE
[Bug ]Catchem [Build 1.6.1.2] doesn't start, runtime error!

### ISSUE THREAD

**Issue by iacodalla** [Lunat1q/Catchem-PoGo#2211]
Hi,
it's the prosecution of BUG #2173 which has been closed @Spk345 .
The solution proposed didn't worked. 
The new version of catchem is still not working while the old one stil does (the exe is executed correctly).
Thanks for the help.
Unfortunately it's still not working.
I redownloaded the latest relase and I've unzipped it into the windows folder just to be sure.
Here's the errors I get: [http://pastebin.com/8n67NHPZ].
![image](https://cloud.githubusercontent.com/assets/23451598/20381460/d89b2782-aca7-11e6-8eec-ef55fdc29c01.png)

I rechecked with the previous release and I can open it without errors.

image
   ![image](https://cloud.githubusercontent.com/assets/23451598/20381483/df47515a-aca7-11e6-99ba-e8cce5111bd8.png)

**Comment by Spk345** [comment]
That error even states you are missing MSCORLIB dependencies, you are not running on your windows partition/drive.

Replace the ```AMD64``` and ```x86``` folders in your catchem installation with these folders, overwrite as necessary. This file has ALL THE DLLS necessary to run Catchem, including the ones you should have on WINDOWS.
[Download Here](https://drive.google.com/open?id=0B1uy43e3F7gAYTVNVzh4cnp2MXM)

**Comment by Spk345** [comment]
And also, this isn't related to Catchem so much as Windows Tech Support ffs.

**Comment by iacodalla** [comment]
Hi @Spk345, 
I did what you suggested and it's still not working.
I probably have some restriction on the computer.
What I don't understand is why the V1.4 still works properly even though is in the same folder of the new version.

**Comment by Spk345** [comment]
Run as Administrator. 
The reason why the older version works, but the newer version does not is due to the Database that is failing to generate due to an issue with your computer. For some reason, due to your computer, it won't run. It's not Catchems fault, this is due to your windows installation. Something is wrong with it.

**Comment by iacodalla** [comment]
It's work computer, I'm running as administrator but I cannot contact IT on this issue, please do you have any solution to suggest?

**Comment by iacodalla** [comment]
@Spk345

**Comment by iacodalla** [comment]
Hi @Spk345, I finally found a solution, I uninstalled .NET framework and I reinstalled it.
Now it works!
Thanks for your help and sorry for the loss of time.
