### ISSUE TITLE
use great ball all the time and ultra ball not poke balls for all the pokemons :/

### ISSUE THREAD

**Issue by unknowkir** [Lunat1q/Catchem-PoGo#2216]

**Comment by velwong** [comment]
I have this problem too. I saved up like 100 ultra balls.. used up within 1 day . T_T

**Comment by unknowkir** [comment]
yes I know I think is a bug don't know how to fix it

**Comment by Spk345** [comment]
Change the percentages at which you use a certain type of pokeballs.
