### ISSUE TITLE
youre done sorry

### ISSUE THREAD

**Issue by nokialadrillo** [Lunat1q/Catchem-PoGo#2217]
niantic send me that message. Wtf? i mean, come on i couldnt use this a minute

**Comment by kennytcwong** [comment]
Me too

**Comment by Mingo1** [comment]
U receive email or message from the pokemon app?

**Comment by kennytcwong** [comment]
Yes. Just the advertising I think

**Comment by r3rodolfor3** [comment]
Me too

**Comment by r3rodolfor3** [comment]
I received the message at catchem and i'm scared to open the pokemon app on my phone, i was on a different latitude

**Comment by Spk345** [comment]
If you turn off GPS on your phone you can double check the account without sending location information. It sent a status code to Catchem, which is interpreted as the ban message.
