### ISSUE TITLE
The bot is not ignoring the pokemon that are in the list "to ignore"

### ISSUE THREAD

**Issue by LuscasCastro** [Lunat1q/Catchem-PoGo#2219]
Sorry, I'm not fluent in English. I had to use tools to translate.

I do not know if it's happening just with me, but the bot is not ignoring the pokemon that are on the list not to capture. Does this proceed ... or is it some bad setup on my part?

These are the pokemon that are in the list to ignore:
`"PokemonsToIgnore": [
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "rattata",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "sandshrew",
    "sandslash",
    "nidoranFemale",
    "nidorina",
    "nidoranMale",
    "nidorino",
    "clefairy",
    "clefable",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "mankey",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "golem",
    "ponyta",
    "rapidash",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "onix",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "cubone",
    "marowak",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "pinsir",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops"
  ],`

Em meu idioma: (In My Language:)
Desculpe não sou fluente em inglês. Precisei recorrer a ferramentas para traduzir.

Não sei se está acontecendo apenas comigo, mas o bot não está ignorando os pokemon que estão na lista para não capturar. Isso procede... ou é alguma mal configuração da minha parte?

Esses são os pokemon que estão na lista para ignorar:
`"PokemonsToIgnore": [
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "rattata",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "sandshrew",
    "sandslash",
    "nidoranFemale",
    "nidorina",
    "nidoranMale",
    "nidorino",
    "clefairy",
    "clefable",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "persian",
    "mankey",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "golem",
    "ponyta",
    "rapidash",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "onix",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "cubone",
    "marowak",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "pinsir",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops"
  ],`

**Comment by Furtif** [comment]
Ola delete tudo deixe so "PokemonsToIgnore": [],  assim capturara todos sen excepçao.

**Comment by LuscasCastro** [comment]
Sorry, I'm not fluent in English. I had to use tools to translate.

I believe you did not understand. I don't want these pokemon. But the bot does not accept it. Even being on the list not to capture.

Em meu idioma: (In My Language:)
Acredito que você não tenha entendido. Não quero esses pokemon. Mas o bot não aceita. mesmo estando na lista para não capturar.

**Comment by Furtif** [comment]
Ola ok ok bon nesse caso coche a casa "use ignore filter" ou 

## "UsePokemonToNotCatchFilter": true,

Todos pokemons na lista serao ignorados.

**Comment by LuscasCastro** [comment]
Okay, I'll try.

**Comment by Furtif** [comment]
👍  envia noticia positivas, e fecha isto se problema resolvido 👍

**Comment by LuscasCastro** [comment]
It worked ... I had to leave a few minutes without capturing the pokemon, then letting it capture. Now it's working. thanks
#32

**Comment by LuscasCastro** [comment]
#32
