### ISSUE TITLE
[Request] Countdown timer when bot is paused

### ISSUE THREAD

**Issue by jbtadifa** [Lunat1q/Catchem-PoGo#2220]
Hope you can get this back. Thanks.

**Comment by Mingo1** [comment]
X 2 . Plz put the count down timer (red below) back thanks

![image](https://cloud.githubusercontent.com/assets/22056811/20418137/d59a63f2-ad85-11e6-9f7f-780bbe0d2b7b.png)

**Comment by kennytcwong** [comment]
Yes, put the count down timer is better. Thanks

**Comment by Mingo1** [comment]
1.6.2.0build2 have it back :)

**Comment by jbtadifa** [comment]
issue/request has been resolved. Thank you.
