### ISSUE TITLE
Catchem has stopping working @ V1.6.2.0 build 2

### ISSUE THREAD

**Issue by Mingo1** [Lunat1q/Catchem-PoGo#2222]
I experienced 2 time crash of catchem @ V1.6.2.0 build 2

Crash info:
http://pastebin.com/fRHLy9Rr

http://pastebin.com/w6Ak7Ntu

**Comment by Mingo1** [comment]
I am using :
Microsoft Windows [Version 10.0.14393] 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full
    version    REG_SZ    4.6.01586

Seems happened in previous release before : 
[ERROR] Error in Windows 10 1607 x64 #1736
https://github.com/Lunat1q/Catchem-PoGo/issues/1736

**Comment by Spk345** [comment]
Yeah, it's hard figuring out what *exactly* causes the issue sometimes, we are aware and we are working on it :) 
I'm going to close this issue, as it's known about and add it to the Known Issue page :)
