### ISSUE TITLE
Updated pokemon go 0.47.1

### ISSUE THREAD

**Issue by Shiukim** [Lunat1q/Catchem-PoGo#2226]
Updated pokemon go 0.47.1 careful in the last update many took ban

**Comment by thiago-ribeiro** [comment]
Pokemon Go was updated today. Stop using the bot?

**Comment by AndoridNewUser** [comment]
need stop the bot ?

**Comment by kobbey21** [comment]
It wasn't a five update so it safe to bot. Might get force update next week

**Comment by DI3GO1** [comment]
You can see by yourserf api min version https://pgorelease.nianticlabs.com/plfe/version

**Comment by Spk345** [comment]
Forced update will happen next wednesday, this one will not be forced.
