### ISSUE TITLE
please close soure code 

### ISSUE THREAD

**Issue by qweasd5203** [Lunat1q/Catchem-PoGo#2228]
CATCHEM has been http://www.xf-wg.com/forum.php?mod=viewthread&tid=2983&extra=page%3D1 this site into a paid money model, whether you can lock the source code after you and in the Program message that every time that the program does not accept any money at all.I really appreciate you can develop CATCHEM

**Comment by Lunat1q** [comment]
We closed source codes long time ago. And as i can see - they can't crack Catchem now.
Catchem NEVER been on xf-wg - the thing they selled there was stolen copy of catchem.
We are not responsible for the shit they do.

**Comment by qweasd5203** [comment]
They changed the catchem title, changed to GETGO, and the user money, and claimed that they developed the program

**Comment by Lunat1q** [comment]
DO latest build actually works? cause as i know - they can't do it anymore:)

**Comment by qweasd5203** [comment]
Is there a way to keep them from changing the CATCHEM title?

**Comment by Lunat1q** [comment]
There is protection against that. Well, i think they use old version without it, i really didn't have any reports what they can steal our last version now.

**Comment by qweasd5203** [comment]
I have mail to you, the letter has their string of changes to the screenshots, it is certain that they use the 1.6.2.0

**Comment by Lunat1q** [comment]
Screenshow says nothing what it's 1.6.2.0.
