### ISSUE TITLE
Bug? Alakazam Refuses To Show In Pokedex

### ISSUE THREAD

**Issue by g00tch** [Lunat1q/Catchem-PoGo#2229]
I evolved a Kadabra into Alakazam, and it will not update my pokedex. Doesn't even register as seen, or caught, even though Catchem recognized the evolve.

Stopped/Started bot. No change.
Closed/Reopened Catchem. No change.

![alakazam](https://cloud.githubusercontent.com/assets/2353921/20456782/78d118fc-ae4b-11e6-8154-771868ed9ee8.png)

![alakazam2](https://cloud.githubusercontent.com/assets/2353921/20456783/80d68e1a-ae4b-11e6-9000-480773fcc184.png)

![notepad](https://cloud.githubusercontent.com/assets/2353921/20456821/40425658-ae4c-11e6-831e-f292e3ac729b.png)

**Comment by matute022** [comment]
layers what mar the new upgrade pokemon go 0.47.1  play store 
waiting Catchem api 0.47.1

sorry mi google translate
