### ISSUE TITLE
Need an audible alert when captcha is encountered

### ISSUE THREAD

**Issue by preechaw** [Lunat1q/Catchem-PoGo#2232]
Can you make an audible alert when captcha is encountered?
Thank you very much.

**Comment by icsusan** [comment]
It would be great :)

**Comment by Chad64220** [comment]
Is it possible to send email or skype message ?
Thanks.

**Comment by Dracsss** [comment]
Very good idea the auditive alert

**Comment by preechaw** [comment]
@echo off
rem create a batch file (.cmd) like this and i know almost immediately when to come back to my laptop
set WINTITLE=Captcha Encountered
echo Finding window with title '%WINTITLE%'
:LOOPSTART
tasklist /FI "WINDOWTITLE eq %WINTITLE%" | findstr "Image Name"
if '%errorlevel%'=='0' "D:\@sound\alert\Red Alert Alarm Sound Effect.mp3"
waitfor /T 5 Nothing >nul 2>nul
goto LOOPSTART

**Comment by preechaw** [comment]
Sorry. I didn't realize there is Telegram support.
This is way better than just audible alerts.
It alerts when we are away from home too.
Very nice.
