### ISSUE TITLE
Catchem API version is less than the minimum

### ISSUE THREAD

**Issue by Jankelele** [Lunat1q/Catchem-PoGo#2238]
I get this error every time I log in since I updated:
[00:49:12] (ERROR) Catchem API version is less than the minimum stop botting to avoid ban!
Did I mess updating process (simply drag & replace all the files) or what? Bot is working just fine btw.

**Comment by thanatos86** [comment]
I have the same issue suddenly. Looks like it might semi-safe botting is over for a while.

**Comment by Catchemxo** [comment]
Soooo how long are we going to be waiting? lol :p
