### ISSUE TITLE
Translation for EventLevelUpRewards failed

### ISSUE THREAD

**Issue by msdl2016** [Lunat1q/Catchem-PoGo#224]
this message keep showing.. 
"Translation for EventLevelUpRewards failed"

What is the problem

**Comment by standujar** [comment]
Just a little problem with the translation.en.json.. its not important, maybe corrected in the next Update ;)

**Comment by msdl2016** [comment]
thanks

**Comment by Lunat1q** [comment]
was corrected... a bit:)
