### ISSUE TITLE
Strongly recommend! Auto stop bot when pokemon force update.

### ISSUE THREAD

**Issue by CrisOng** [Lunat1q/Catchem-PoGo#2240]
Will really useful i think.

**Comment by CrisOng** [comment]
Ninja have this function.

**Comment by Charlier69** [comment]
Yes pokeframer has it too!

**Comment by Lunat1q** [comment]
BEHOLD THE NEWS, Catchem have it too. You are being warned if running outdated API during startup.

**Comment by CrisOng** [comment]
but Catchem run directly after warn, i mean asking Yes or No to run
