### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Jey1975123** [Lunat1q/Catchem-PoGo#226]
`System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : ptr
   à System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   à PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 191
   à PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:ligne 46
   à PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 18
   à PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 68
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 54
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:ligne 32
[19:35:48] (INFO) Trying again in 45 seconds...
`

Hello,

I have this error since I use 1.4 whereas 1.3.5 works. Somebody can help me?

Thank

**Comment by pikopike** [comment]
you copied profiles try to make new ones.. helped me

**Comment by Jey1975123** [comment]
> you copied profiles try to make new ones.. helped me

I've already tried.

**Comment by Lunat1q** [comment]
Looks like you are missing Resource foler.
