### ISSUE TITLE
Hint to avoid CAPTCHA

### ISSUE THREAD

**Issue by geraldgong** [Lunat1q/Catchem-PoGo#2263]
I tried to set the speed factor to 0.4xx, and it is working for 5 hours till now without any captcha notices.
Probably the default speed is too high.

**Comment by xtraearth** [comment]
now u have flagged ur account for the next ban wave... the api from catchem is outdated (use the 0.45 api and the actual one is 0.47). Look in the discord chat the info (more than a week... if no one reads the issues and the discord chat I'm wondering... what went wrong?)

**Comment by NeFShARk** [comment]
Nah... let him play dude! All these retardes creating issues like this deserve ban because they can't do a simple search or read the word ban in the catchem warnings.
