### ISSUE TITLE
safe settings for captchA

### ISSUE THREAD

**Issue by kilado94** [Lunat1q/Catchem-PoGo#2267]
hi guys
i wonder what the best setting to prevent the captch?
i get captcha every 10 min...
thankz

**Comment by DrGroenlund** [comment]
Do NOT use the bot. API are outdated. You Will get banned... This is the reason you get all thouse capatcha.

**Comment by iAngelG** [comment]
Please the read other issues, and stop using the bot. You're probably banned, and if not, you definitely will be because you keep using it after the update

**Comment by xtraearth** [comment]
please make a party with all the future banned ppl for not reading the last issues and comments... I want my PopCorn!!

**Comment by kilado94** [comment]
omg, thankz alot 
yes i wont ahve read :(
thankz :)
