### ISSUE TITLE
(INFO) Proxy Down?

### ISSUE THREAD

**Issue by ragekwit** [Lunat1q/Catchem-PoGo#227]
Hi.

The bot says "(INFO) Proxy Down?" in the console when I start it while it says "Proxy works fine!" when I click on "TEST PROXY" in the settings.

Any solution ?

**Comment by Lunat1q** [comment]
fixed

**Comment by ragekwit** [comment]
Not fixed at all.

**Comment by vladseverrr** [comment]
When there is one boat without a proxy , then the rest of proxy will not run !
