### ISSUE TITLE
Project dead

### ISSUE THREAD

**Issue by genrichh93** [Lunat1q/Catchem-PoGo#2282]
I know developing isn't as easy as many of us think and developing needs time but since there hasn't been any update and signs of life for 1 month now, this project seems to be dead.
In the meantime everyone who's reading this, you can use PokeGo++ (iOS only).
Does anybody know any other and similar bot? I mean similar to Catchem PoGo or RocketBot. Im prefering bots with some gui because cli is not so overseeable.

Many thanks in advance for your help.

**Comment by KoopaTheTurtle** [comment]
Project isnt dead... if you look at a Issue i posted you will see a reply of this 

"Pokemon Go has been forced updated to minimum client version 49.0. However, API 45.x still works, just with a guaranteed ban chance, and lots of captchas. Remember if you want to run it, you will be banned. There have been a few reports of bans, but no full-fledged Ban Wave has been reported yet. Never bot with an account you do not want to take the chance to lose. We will update to 49.0 as soon as it is possible, but it looks like it may be a bit of time before the API is reversed."

The project isnt dead its more waiting for API to be accessible :P

**Comment by Housy123** [comment]
But why does it take so long ? there are many other bots with the latest API running like a charm

**Comment by jemaloac** [comment]
Other bots run with the API 0.45, only one of them called "Pokefarmer" is the only one that has the API 0.49, but it is not free. If you use any bot other than pokefarmer, the risk is high that your account is flag and banned.

P.S.: Sorry for my bad english.

**Comment by NeFShARk** [comment]
@Housy123 Before asking why is taking so long why don't do a little research to try to understand what an API is? It's taking long because its complicated and it takes a lot of work, because you need to reverse engineer it, because niantic is trying to prevent(by protecting it) people from doing it and etc.

https://www.youtube.com/watch?v=s7wmiS2mSXY

**Comment by Housy123** [comment]
@NeFShARk It's not like I don't know what an API is but I know it won't be that hard to reverse it. There are much harder to "crack" API's which were done in a matter of days e.g sbot/mbot

**Comment by NeFShARk** [comment]
@Housy123 Since you said that it's not that hard, why don't you do it then? I'm sure that it would be a lot faster than complaining why is taking to long for the api to be reverse engineered by someone else, since it's "easy" and you can do it pretty "fast".

**Comment by Housy123** [comment]
@NeFShARk

First of all I didn't complain. Second, If I wouldn't have given up on coding or reverse engineering years ago, I would have done it myself by now.

**Comment by Lunat1q** [comment]
I was away for 2 weeks, now i'n back, stay tuned for the info.

**Comment by thanatos86** [comment]
Yeah budday!

**Comment by thanatos86** [comment]
??

**Comment by thanatos86** [comment]
What's the info?
