### ISSUE TITLE
It was fun....

### ISSUE THREAD

**Issue by vdbk** [Lunat1q/Catchem-PoGo#2289]
and you had a great thing here Lunat1q but keeping us all in the dark with no progress reports is just dumb! So I went looking for alternatives and found a great bot :) running it straight for 3 days now and not even getting any captcha so it runs real smooth! Sorry to say but you could really learn a lot from them if you weren't so a hard-head :( so long!

**Comment by Lunat1q** [comment]
Your opinion is so important to me.
And may be, you will learn how to read.
