### ISSUE TITLE
 not running a fucking Elevation !!!

### ISSUE THREAD

**Issue by vladseverrr** [Lunat1q/Catchem-PoGo#230]
![yyy](https://cloud.githubusercontent.com/assets/21099923/17787788/4eaa2f7e-6593-11e6-9f5a-7fe1a4e4b087.png)

**Comment by standujar** [comment]
Check Human Pathing in settings

**Comment by vladseverrr** [comment]
Everywhere is included !
![default](https://cloud.githubusercontent.com/assets/21099923/17788274/8d197c68-6595-11e6-9655-1ff076f9d23d.png)

**Comment by CDAGaming** [comment]
You also don't have to curse out the Dev's @vladseverrr :(
