### ISSUE TITLE
System.InvalidOperationException in 1.4.1 & 1.4.1.1

### ISSUE THREAD

**Issue by standujar** [Lunat1q/Catchem-PoGo#231]
`[21:32:53] System.InvalidOperationException: La collection a Ã©tÃ© modifiÃ©eÂ ; l'opÃ©ration d'Ã©numÃ©ration peut ne pas s'exÃ©cuter.
   Ã  System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   Ã  System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   Ã  System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   Ã  PoGo.PokeMobBot.Logic.MapCache.UsedPokestopsCleanup() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:ligne 121
   Ã  PoGo.PokeMobBot.Logic.MapCache.CheckPokestopUsed(FortCacheItem fort) dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:ligne 129
   Ã  PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<>c__DisplayClass1_0.<Execute>b__8(FortCacheItem x) dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:ligne 86
   Ã  System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   Ã  PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:ligne 85
--- Fin de la trace de la pile Ã  partir de l'emplacement prÃ©cÃ©dent au niveau duquel l'exception a Ã©tÃ© levÃ©e ---
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   Ã  PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:ligne 58
--- Fin de la trace de la pile Ã  partir de l'emplacement prÃ©cÃ©dent au niveau duquel l'exception a Ã©tÃ© levÃ©e ---
   Ã  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   Ã  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Ã  PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:ligne 38
`

this appear after 10-15 min running, the only solution is restarting the bot

**Comment by Brufer20** [comment]
How can I solve that? You have the solution?

**Comment by standujar** [comment]
The solution is to use the 1.4.0.0 Rev. :) and wait for the 1.5 or 1.4.5

**Comment by Lunat1q** [comment]
1.4.1.2 fixed
