### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Brufer20** [Lunat1q/Catchem-PoGo#233]
[13:51:16] (ERROR) System.InvalidOperationException: Colección modificada; puede que no se ejecute la operación de enumeración.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   en System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   en PoGo.PokeMobBot.Logic.MapCache.UsedPokestopsCleanup() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:línea 121
   en PoGo.PokeMobBot.Logic.MapCache.CheckPokestopUsed(FortCacheItem fort) en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:línea 129
   en PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<>c__DisplayClass1_0.<Execute>b__8(FortCacheItem x) en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:línea 86
   en System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   en PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:línea 85
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:línea 58
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:línea 38

**Comment by Brufer20** [comment]
[13:51:16] (ERROR) System.InvalidOperationException: Colección modificada; puede que no se ejecute la operación de enumeración.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   en System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   en PoGo.PokeMobBot.Logic.MapCache.UsedPokestopsCleanup() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:línea 121
   en PoGo.PokeMobBot.Logic.MapCache.CheckPokestopUsed(FortCacheItem fort) en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:línea 129
   en PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<>c__DisplayClass1_0.<Execute>b__8(FortCacheItem x) en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:línea 86
   en System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   en PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:línea 85
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   en PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:línea 58
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() en D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:línea 38

**Comment by standujar** [comment]
#231 

The solution is to use the 1.4.0.0 Rev. :) and wait for the 1.5 or 1.4.5

**Comment by Brufer20** [comment]
Then just download the 1.4.0.0?

**Comment by Lunat1q** [comment]
It was fixed in 1.4.1.2
