### ISSUE TITLE
Proposal improvement - Don't always use the nearest pokestop. ( Avoid Loop too )

### ISSUE THREAD

**Issue by fll242** [Lunat1q/Catchem-PoGo#238]
File : FarmPokestopsTasks.cs
Ln 360
 var idx = random.Next(Math.Min(5, pokestopList.Count));
 var pokeStop = pokestopList[idx];
  pokestopList.RemoveAt(idx);

Purpose : Don't always use the nearest pokestop. ( Avoid Loop too )

**Comment by Lunat1q** [comment]
There is No loop, and check discovery pathing, and pokestop lucky number
