### ISSUE TITLE
Summary Requests / Enhancements

### ISSUE THREAD

**Issue by nicolaslevy91** [Lunat1q/Catchem-PoGo#239]
Hi i wanna help a bit so im going to summary the things i read in the diferent posts:

1. Divide each type of item Pokeballs / GreatBalls / Ultraballs and Potions/SuperPotions/MaxPotions, etc

2. Able to manually use incense, lucky egg if possible lure also

3. Enhance information tba: 
                                            Pkmn moves
                                            Pkmn exact atk iv/def iv/sta iv (others bots have this)
                                            Able to manually select and transfer more than 1 pkmn
                                            Able to check max capable CP (##/##) and current lvl
                                            Numbers not easy to understand #198 

4. Human pathing and routing not working well #196 

5. Not to catch pkmn not working well

6. Pre-set how long we want to use the bot and a offset to automatically restart (ej: use bot 2 hours, offset 6 hours) it will work 2 hours pause 6 and restart 2 hours but in a random way to implement it.

7. Show in the UI Map the Max Travel Distance ! This will make it MUCH easier to set up the bot, for example, to farm only in the Central Park Area.

8. Identify lured pokestops and stay near them for a while to catch pokemons.

9. Randomly stop at a pokestop and take a random time break.

10. (i dont understand this issue, but i think its kinda important) = #148 

11. In console it would be great to have time to destination of pokestop and to slow down the walk to reach 0-2km/h

Anyway its not all 100% needed its just a review of what can be done to the bot to make it as perfect as possible.

Cya !!

**Comment by Megatone** [comment]
about what to transfer several pokemons at the same time , I think it's not a good idea , you can raise suspicion and cause for banishment

**Comment by CDAGaming** [comment]
Yea, I evolved 20 pokemon at once, got permaban next day

**Comment by Megatone** [comment]
It is very important not to make the very followed actions is better to take more time and this is random

**Comment by CDAGaming** [comment]
#148 is when it auto restarts, which is supposed to happen

The lured pokestops can show up a different color, as there is already code for the lured pokestops

9 wouldn't be very useful to add due to 6

**Comment by CDAGaming** [comment]
Correction:Lured pokestops already show up as a pinkish color

**Comment by CDAGaming** [comment]
There is also a typo here:
Max amount of pokemos 34.9 or pokestops 61.6 per hour reached, bot will be stoped for 49.0 minutes

I'll administer a fix later on

**Comment by nicolaslevy91** [comment]
Then what about the transfer duplicate pkmns? it transfers many sometimes more than 50 ... i think it can be fix with a transfer delay, rigth? or the same with the recycle od the items.. (personaly i didnt know that its banable this things)

The pkestops show up on pinkish, but the bot does not stay in the place it keeps going.. the post of this request wanted an option to be able to stay in place catching pkmns on lurestops, like a re set a range of moving the bot into few meters

(ALL this points are not mine, i only compiled them into a summary)

**Comment by CDAGaming** [comment]
It transfers those that are week or in the filter list, if you do not want all your pokeman transferred You can remove some from the transfer filter

**Comment by Megatone** [comment]
I recommend you remove all Pokemons transfer filter and make transfers manually with a waiting time of more than 2 seconds between transfer and transfer to avoid bans

**Comment by nicolaslevy91** [comment]
LOL, i know what transfer duplicate pkmn is... what im saying is that it transfer very fast lots of pkmn not humanly possible.. so it has a delay ("Delay Transfer Pokemon"), and that can be implemented in a manually select to transfer 40 pkmn at "once" and the bot prepares to transfer all the pkmn but with a 2 sec between. One thing i dunnot know is why always the delays are being set random...

**Comment by Lunat1q** [comment]
I answered all those feautures like.. 10 times already.
