### ISSUE TITLE
(ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json [18:47:34] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)

### ISSUE THREAD

**Issue by tolmai** [Lunat1q/Catchem-PoGo#243]
Everytime i put to run in a proxy, appear this error and the account do not login:

`[18:47:34] (ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[18:47:34] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)`

**My google email do not have this two factor auth enabled!**

When i put proxy off, the account log in normaly!

**Comment by standujar** [comment]
Hello, just follow a Google Two Factor Auth guid ;) it work for me

**Comment by tolmai** [comment]
You mean, enable two factor auth and do the guide?
