### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Brufer20** [Lunat1q/Catchem-PoGo#244]
What is the best configuration for the bot?

**Comment by standujar** [comment]
The default conf is perfect ;)

**Comment by hawaiian96778** [comment]
Yeah can somebody please put thier best conf fig up, I'm pretty sure my level 36 main account is banned, havnt gotten a email stating yet.. But would appreciate it, so far my configure is untouched..

**Comment by Brufer20** [comment]
Speed? and items? I have many problems with items
