### ISSUE TITLE
The "DELAY" unit of mesure

### ISSUE THREAD

**Issue by wackovireshnik** [Lunat1q/Catchem-PoGo#247]
hello guys, plz, i have to be sure about unit of measure
it counting on secondes ? mili.sec? minutes?
there is to big difference between them, dont anderstand the logic (**5000**;3000;2000;1000;250;**0.3**)
im sure many people dont know..put light on our brain please ;)
i feel the bot dont catch pokemons as fast as he can with this DEFAUT config!
ty mates

**Comment by Lunat1q** [comment]
Ms
