### ISSUE TITLE
Device Info

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#260]
Привет. Огромная просьба, сделать кнопку рандомизацию всех полей  Device Info, т.е выставление рандомных значений, как при создании нового проекта. Просто многие дублируют папки с проектами, и дивайс данные остаются те же самые, кроме imei.

_________________________________________________________________________________________

Hey. The huge request , do randomization button all fields Device Info, ie exhibiting a randomly value as when creating a new project. Simply, many duplicate folders with the projects , and divays data remains the same , except imei.

**Comment by Scoopedd** [comment]
https://play.google.com/store/apps/details?id=com.devicefaker.free&hl=de can help you out for the first time :) @JacksonTrue
