### ISSUE TITLE
Pathing worst than before

### ISSUE THREAD

**Issue by inoxas78** [Lunat1q/Catchem-PoGo#265]
Hello all,

Pathing is not human, was better when GUI shows red lines that bot will follow, any idea?

Screen in Disneyland, where pathing works verywell before

![image](https://cloud.githubusercontent.com/assets/21035583/17809126/bb07626e-6614-11e6-93e8-1df29529a065.png)

**Comment by Bay101** [comment]
We are having issues with the API's for the routing services used where they are crashing. We are working on a fix
