### ISSUE TITLE
Max Pokestop Not work

### ISSUE THREAD

**Issue by marvin448** [Lunat1q/Catchem-PoGo#266]
Max Pokestop Not work 
set 69 per hour
i set into 20 not work still continues 
i set into 10 not work still continues 
i set into 1 not work still continues 
i set into 0 not work still continues

**Comment by standujar** [comment]
Yes, this features was working only on the first rev.

**Comment by nicolaslevy91** [comment]
you need to let the bot work for an hour, then it stops.. its not like a counter that when u visit 69 stops the bot stops

**Comment by standujar** [comment]
We need a half hour for the Niantic unknow error every 30 min

**Comment by b3tt0z** [comment]
There is a limitation of approximately 1000 Pokemon captured day and 1500-2034 Pokestops day. Also in 28 or 29 minutes it is triggered a signal, which causes the error.

Suggestion:

- Made available an option of not capture more than 1,000 pokenmons day.
- Provide option to visit visitation maximum recommending not pass the boundary between 1500-2034.
- Timer button start, also timed stop and automatic restart cyclic or for a time, watching the capture option and visitation maximum.

**Comment by Lunat1q** [comment]
"stop" logic check it's run after 1h
