### ISSUE TITLE
Map Proxy issue

### ISSUE THREAD

**Issue by sandinosantos** [Lunat1q/Catchem-PoGo#269]
First: My english is horible, sorry :/ 

So...
I configured the authenticated proxy. I log my Ptc account, but the map is not charging.
Returns: "Exception: The remote server returned an error: (407) Proxy Authentication Required."

![image](https://cloud.githubusercontent.com/assets/21105789/17811891/237e9dd6-65fb-11e6-9c5c-f604249a6b08.png)

Apparently it recognizes the proxy, but is not passing authentication.

By the way... Nice work :)

**Comment by Lunat1q** [comment]
map using default system proxy and default system autorization.
