### ISSUE TITLE
No usable Pokestops

### ISSUE THREAD

**Issue by teddrick** [Lunat1q/Catchem-PoGo#273]
Restarted my pc and then launched the bot and suddenly I get no usable Pokestops nearby...anyone facing the same problem?

**Comment by Scoopedd** [comment]
you perhaps logged in in wrong region ? and got a softban ?

**Comment by teddrick** [comment]
tried 5 accounts and i get the same error...didn't change the location though...all my accounts are in Central Park NY and suddenly this error came out

**Comment by teddrick** [comment]
Lol...i think something to do with my VPN IP...disconnect and reconnect few times and it's working now. Thanks :)
