### ISSUE TITLE
New proposals

### ISSUE THREAD

**Issue by FGonzalezBon** [Lunat1q/Catchem-PoGo#277]
**In settings tab**
- Not to move from one point (pokestops lure all time)
- Not exceed kilometer radius.

**In information tab**
- Reduce the images of pokémons
- add final XP need
- Use lucky egg and lure module with one option as the recycle item.

**Another questions**
Why the puppet moves to the exact position of pokestop, when it can be used at 5 meters?

**Comment by GabrielGalinari** [comment]
Yeah. An option to stand still at a pokestop would really come in hand.

**Comment by pcswatertown** [comment]
Option to standstill , or circle back to lured pokestops

**Comment by Bay101** [comment]
it moves to the position of the poke stop due to the location coordinates fed to the program being the lat and long of the poke stop itself, as for the suggestions they have been noted and may be implemented in the future
