### ISSUE TITLE
Visibility window, recycle items

### ISSUE THREAD

**Issue by JBWKZ2099** [Lunat1q/Catchem-PoGo#278]
I have a pair of problems, the first one is that i can't see all the buttons in bottom.
The second is that i put a range to recycle the items:
80 pokeballs
60 potions
20 razzberries

But i don't know why but when the bot recycles the item, it doesn't keep 80 pokeballs, 80 greatball nor 80 ultraball, i don't know how is it works.

Screenshots:
http://i65.tinypic.com/2lbl5vl.png
http://i63.tinypic.com/2v1rp15.png
http://i66.tinypic.com/2rnj8l4.jpg

Greetings.

**Comment by wagas** [comment]
the 80 pokeballs is the 80 of the total pokeballs you have in your inventory same as potions

**Comment by JBWKZ2099** [comment]
Aamm, so.. Is the total ammount?

20 pokeballs

20 greatball

20 ultraball

20 masterball

Total 80?


Obtener Outlook para Android






On Fri, Aug 19, 2016 at 2:01 PM -0500, "wagas" <notifications@github.com> wrote:





the 80 pokeballs is the 80 of the total pokeballs you have in your inventory same as potions

**Comment by matema13619** [comment]
The bot keeps the higher balls if you have 40 Great balls and 50 Ultra balls, it will dump all pokeballs and 10 great balls.
