### ISSUE TITLE
Human Pathing and Routing 

### ISSUE THREAD

**Issue by AisuMisuto** [Lunat1q/Catchem-PoGo#281]
Even after trying all type of configuration,the bot continue flying over building,someone can help me?

**Comment by KBLOSO** [comment]
Same here. Could someone help us?
Thanks

**Comment by AisuMisuto** [comment]
Its true that Routing Servers Are Down?

**Comment by lazwardi** [comment]
should be a feature like waypoints, its like Force Stop, but dozen of it on the map.

**Comment by rroethof** [comment]
> !PocketMobsters! - Today at 4:59 AM
@here Human routing will be down for maintenance periodically over the weekend, we're doing improvements so it works 100% of the time. We've handled nearly 10 million route requests in the past 24 hours, we did not expect this kind of load so we need to change how certain things are handled.

**Comment by TitQuentin** [comment]
One solution :  would be to "draw" a predefined path with cursor and the bot follow this path

**Comment by Broxxx3** [comment]
Log info:
[01:54:36] Requesting routing info to http://openls.geog.uni-heidelberg.de
[01:54:36] Routing error: Remote server returned an error: (404) Not found.

**Comment by AisuMisuto** [comment]
OpenLS working?

**Comment by Lunat1q** [comment]
routing server died.
looking for a solution
