### ISSUE TITLE
Great BOT!!!! bug Pokemon!

### ISSUE THREAD

**Issue by angelusce79** [Lunat1q/Catchem-PoGo#283]
this week I will send you a donation, your bot is beautiful and very good, has some bugs but can improve , I have 200 margycarps not evolve to gyarados !

**Comment by matema13619** [comment]
It takes 400 candies to evolve to Gyarados...

**Comment by whelvenus** [comment]
but he said he has 200 magikarps, that would be a total of 800 candies..

**Comment by pikopike** [comment]
he need 400 candies not magycarps... transfer and check below amount of candies
