### ISSUE TITLE
What do errors like this mean? [15:44:03] (ERROR) (Error) | Bellsprout, Lvl: 13 | CP: (386/415) | IV: 69.20% | Type: Lure | Chance: 41.52% | Dist: 30.97m | Used: PokeBall (20 left) | XP: 0 | 

### ISSUE THREAD

**Issue by redbone75** [Lunat1q/Catchem-PoGo#284]
Greetings.  Just curious what these kind of errors mean?

[15:44:03] (ERROR) (Error) | Bellsprout, Lvl: 13 | CP: (386/415) | IV: 69.20% | Type: Lure | Chance: 41.52% | Dist: 30.97m | Used: PokeBall (20 left) | XP: 0 |

**Comment by hawaiian96778** [comment]
You might be below the selected amount of Pokeballs to catch said Pokemon?

**Comment by Lunat1q** [comment]
That means what encounter received an error during runtime
