### ISSUE TITLE
[Error] Catching a Pokemon 

### ISSUE THREAD

**Issue by Pengich** [Lunat1q/Catchem-PoGo#29]
So when catching a pokemon it says [Error] not [Flee] not [Escaped] or [Caught]

**Comment by Byakk0** [comment]
I get that too sometimes, when the pokemon has despawned.

**Comment by Pengich** [comment]
@Byakk0 but its like everytime and it flees? after it tried a few times

**Comment by Byakk0** [comment]
@Pengich No, only sometimes. Did you try catching on your phone or bluestacks? To rule out some kind of ban.

**Comment by Pengich** [comment]
@Byakk0 I shall try again now without anything on 30 minutes

**Comment by Pengich** [comment]
@Byakk0 still nothing Still spams an error message saying nothing and not even using pokeballs
