### ISSUE TITLE
rasberry using method

### ISSUE THREAD

**Issue by gambleroflife** [Lunat1q/Catchem-PoGo#290]
In my real play I was using rasberries a lot. Even with easier pokemons. It would be nice if an option to use rasberries after first throw or second throw etc.

**Comment by Lunat1q** [comment]
<img src="http://i.imgur.com/PTcQUNC.png"/>

**Comment by gambleroflife** [comment]
I know these settings. Yet I am talking about a setting like use berry at 3rd attemp or else.
