### ISSUE TITLE
no longer stopping right by pokestops

### ISSUE THREAD

**Issue by Mordascar** [Lunat1q/Catchem-PoGo#291]
so starting today, the bot no longer stops right by a pokestops, instead it stops close to it and then changes directions. thing is, it has messed up INCREDIBLY the routes I used to make with it, namely inside a local park here that is entirely made of tall grass. now it leaves the park instead of alternating between the pokestops within it. any way to change this ?

**Comment by Lunat1q** [comment]
No, it's new humanized logic, bot try to use pokestops as soon as they are in range, so it makes it more humanlike
