### ISSUE TITLE
infinite egg incubator/limited egg incubator

### ISSUE THREAD

**Issue by gambleroflife** [Lunat1q/Catchem-PoGo#292]
This is my third opinion. I would love to use my infinite egg incubator from level 1. However when the use egg incubator option is enabled it uses the limited ones as well. Yet I want to use them after level 30. The distinction between them would be great. IMHO.

**Comment by Lunat1q** [comment]
ehm... sure will do setting for that

**Comment by Lunat1q** [comment]
Done.
