### ISSUE TITLE
[Feature Request] Deployment / Vertification Service for Repo Commits

### ISSUE THREAD

**Issue by CDAGaming** [Lunat1q/Catchem-PoGo#293]
As all/Most repo's have this, I think it would be great to allow the Usage of a CI like AppVeyor or Travis CI

If you wouldn't feel like doing it yourself, I'd be happy to configure it to Work on Catchem to Vertify/Check the Commit for build errors.

Let me know,
CDA

**Comment by Lunat1q** [comment]
I never do non-buildable commits, since I'm the only one coder here, I see no point doing this, but many thanks mate!
