### ISSUE TITLE
What is OpenLS Rounting?

### ISSUE THREAD

**Issue by lucas3820** [Lunat1q/Catchem-PoGo#294]
Hello everyone, I wonder what use the option:
OpenLS Rounting
and
Mapzen Api Elevation Key
and
Use Mapzen Api Elevation

I want to know also how to configure the navigation become more symmetrical (square).

Sorry, translated in google translator.
--------------------------------------------------
Ola a todos, gostaria de saber para que serve a opção:
OpenLS Rounting
e
Mapzen Api Elevation Key
e
Use Mapzen Api Elevation

Quero saber também como configuro para a navegação ficar mais simétrica (quadrada).

Desculpe, traduzido no google tradutor.

**Comment by TomWolker** [comment]
OpenLS Routing É pra vc mover o personagem clicando duas vezes em algum lugar do mapa, aí ele vai ir até onde vc clicou

**Comment by kakasplatt** [comment]
Olá camarada.

OpenLS Rounting e Mapzen Api Elevation são API's para rotas (seu bot irá calcular latitude, longitude e altura a partir destes)

Prefira usar o Mapzen Api Elevation pois, OpenLS Rounting é mais instável atualmente.

Para obter a key para utilizar o Mapzen é necessario acessar https://mapzen.com/developers/sign_in

Para a navegação simétrica tente desativar a opção "Use Human Pathing" na interface do bot, fazendo isso ele deixara de seguir as ruas.

**Comment by Lunat1q** [comment]
OpenLS override Mapzen and MobBot routing system, it's just an alternative, but unstable one

**Comment by lucas3820** [comment]
Thanks for the information, I'm using the key mapzen, I would very much like the bot would use the streets and did not pass over the lojar and homes to achieve your goal. is there any setting for this?

-----------------------------------------------------------------
Obrigado pelas informaçoes, estou usando a chave mapzen, eu gostaria muito que o bot usasse as ruas e não passasse por cima das lojar e casas para atingir seu objetivo. existe alguma configuração pra isso?

I do not want him to walk this way. / Não quero que ele ande desta forma.
[![Untitled-1.jpg](https://s4.postimg.org/wigpbi7zx/Untitled_1.jpg)](https://postimg.org/image/ajaaoar5l/)

**Comment by kakasplatt** [comment]
Camarada, se você quer que ele utilize as ruas basta ativar a opção "Use Human Pathing".

Após ativar observe por alguns minutos se ele irá utilizar as ruas, caso não utilize desative o Mapzen.

**Comment by AisuMisuto** [comment]
kakasplatt fiz isso mas não adiantou,ele continua passando encima das casas e predios.

Ja desativei o mapzen,ja deixei o human pathing ativo,ja tentei o openls e nada :/
