### ISSUE TITLE
THE RED LINE!!!

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#296]
Hi Guys!

If it´s not possible to keep human pathing working, is it possible to disable all the human pathing? Always, after 5 minutes this red line appear in the middle of the map and the bot, dont matter what, just keep flying above everything to get to the end of this line.

Tryed GPX, human pathing, Ls server, everything server, omg, if i could just disable every option, in this stage, would be the best.

![image](https://cloud.githubusercontent.com/assets/21060440/17828130/4b348b2e-665f-11e6-8b1c-48cd27cb9387.png)

Thanks.

**Comment by Bay101** [comment]
Disable all of the check boxes under walking speed max setting, then make sure use discovery pathing is checked to get the human walking feature off.
