### ISSUE TITLE
Pokestop Error... not softban

### ISSUE THREAD

**Issue by TomWolker** [Lunat1q/Catchem-PoGo#297]
Sometimes some pokestops have errors when trying to rotate them in the game, and when it does , the bot accuses of softban , but that's not true because I  checked (only in some pokestops randomly, not always the same ) . With that, he is trying to remove the soft ban, but it never stops ... I would like that: put an option to ignore the pokestop forever (Some never return to work), after the first attempt to remove the soft ban. 

I noticed that this error often happens when it goes beyond the 20km of walking speed , which also happend to the game without the bot. It's a normal game error , but still would be a good idea to place the option mentioned above ...

![image](https://cloud.githubusercontent.com/assets/21134965/17827990/44e9358c-665d-11e6-9cbd-3c5fa2f818a4.png)

Thanks.

**Comment by 50URC3** [comment]
What's up. Decreases the spedd (7-12). In som postos presented here will be fixed soon. 
It would be nice a system that recognizes the time Pokestop. changing randomly after recognizing the Pokestop already used. Abraço, BR aqui! =)

**Comment by Lunat1q** [comment]
Tbh, that "unban" system looks like No more usefull for me, i'll set some checks in logic, thanks
