### ISSUE TITLE
Request: About Snipe

### ISSUE THREAD

**Issue by bloodyrhyme** [Lunat1q/Catchem-PoGo#3]
Really nice Gui and Bot. Could you add "use snipe location server" option and mass transfer option. Thank you.
- [ ]  "use snipe location server"

**Comment by adrian089089** [comment]
If you go into profiles>config you can find "use snipe location server" and change it from false to true. Would be an awesome add to the UI though.

**Comment by Lunat1q** [comment]
This is into my roadmap, not done yet
