### ISSUE TITLE
 I offer updates

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#30]
1) make the "Copy" button to copy the project. It will be very convenient.
2) In pokemon leaf to make the opportunity to put a check mark to select multiple Pokemon, or tick "All"
3) Transfer and delete objects only works after you restart the account, please correct. Make the adjustment value in minutes.
4) Make the number for each kind of objects.
5) I very much want Russian localization
6) Make the ability to add multiple proxies for the account. If proxy 1 is offline, then the connection went to the second proxy.
I apologize for my English) Thank you for your attention.

**Comment by Lunat1q** [comment]
1. - you have batch creation tool, u can do it with it
2. - can cause problems.
3. - should work every 5-8th pokestop.
4. - didn't get it
5. - all localizations will be added in the future
6. - hm, i'll think about it.
