### ISSUE TITLE
[Suggestion] Move Set

### ISSUE THREAD

**Issue by golgolak** [Lunat1q/Catchem-PoGo#300]
Would like to request "Moves" filtering option for the bot. So we only get to keep not only the highest IV but also the ones with the best move set. Thank you.

    "Gyarados": {
      "KeepMinCp": 100,
      "KeepMinLvl": 10,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
          "dragonBreathFast",
          "BiteFast"
          "hydroPump"
        ]
      ],
      "DeprecatedMoves":
        [
          "Twister",
          "DragonPulse"
        ],
      "KeepMinOperator": "and",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 100,
      "KeepMinLvl": 10,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
          "frostBreathFast",
          "blizzard"
        ]
      ],
      "DeprecatedMoves": null,
      "KeepMinOperator": "and",
      "MovesOperator": "and"

**Comment by 50URC3** [comment]
It is a good suggestion.

**Comment by Bay101** [comment]
Suggestion Noted.

**Comment by golgolak** [comment]
thanks for your kind consideration. cheers!
