### ISSUE TITLE
cant catch pokemons

### ISSUE THREAD

**Issue by andrewhsr** [Lunat1q/Catchem-PoGo#302]
i only can farm the pokestops, but all the pokemon flee... 

what could be? :/ it's not ban cuz i can farm the pokestops

**Comment by marvin448** [comment]
you are soft ban

**Comment by andrewhsr** [comment]
deam... well 2 hours or something like that? cuz pikestops works well

**Comment by marvin448** [comment]
try the trick try it of your mobile phone or nox/bluestack if you find a pokemon click it and trow a pokeball away 30-40 times and at last try catch it or close bot and open it change not catch pokemon only pokestop farm for 10-15mins and try to enable catch pokemon after that
