### ISSUE TITLE
Application performance.

### ISSUE THREAD

**Issue by whelvenus** [Lunat1q/Catchem-PoGo#303]
There are times that Catchem.exe freezes and resumes, slows down and continue normal speed, and sometimes just stops responding. It happens randomly, freshly started laptop, even after a restart, sometimes it runs smoothly and after like 5 hrs it slows down, I just close it and stop botting because it freezes. I notice that when performance goes down, the map loads very slow and distorted at different areas.

Btw i use 1.4.0 and 1.4.2

**Comment by whelvenus** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21096186/17829198/e4e2d648-66d9-11e6-9a10-6197d1ae5fe7.png)

**Comment by PassiveModding** [comment]
is that windows 98.... no wonder

**Comment by whelvenus** [comment]
nahh.. windows 7 Ultimate SP1, 32-bit

**Comment by wagas** [comment]
low specs computer can freeze your bot =) LOL

**Comment by Lunat1q** [comment]
Well, freezes can be caused in case of unstable api, can you check ram usage? May be there is mem leak

**Comment by whelvenus** [comment]
it was running fine few days ago.. it just happens randomly throughout the day.

**Comment by Lunat1q** [comment]
Well, some things changed in code:) may be it's because of em, may be you can run it through VS from source? So we can find a bug, if Catchem crash during Debug session in VS - PM in Discord directly

**Comment by whelvenus** [comment]
it also does those freezes and slow map loading on older versions from 1.3.5 to 1.4.0.

Ive been using 1.2.3 for as long as i can remember, but now it freezes and loads the map so slow.

**Comment by wagas** [comment]
what is the specs of your laptop, you even lower your graphics of your theme..

**Comment by whelvenus** [comment]
will it matter? i ran 1.4.0 for 16 hrs straight yesterday without having any problem. after coming home from work, maybe 12 hours ago, i tried and it's freezing, loads the map slowly, and distorted, and I've been trying different versions since then and it's all the same.

**Comment by wagas** [comment]
yes it matters.. i have 2 bots, one is on computer and one is on laptop, the same as yours, the bot on my laptop freezes =)

**Comment by whelvenus** [comment]
but doesn't it seem weird? got 3 accounts to lvl 25 using this laptop then all of a sudden I cant use the app smoothly, i feel like the problem is how the app is getting the map but I don't have any knowledge to check if it was really that.
