### ISSUE TITLE
No Usable Pokestops found in your area.

### ISSUE THREAD

**Issue by jukestarr** [Lunat1q/Catchem-PoGo#305]
I keep getting the message "(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?" 
I used the default maximum distance (5000) I even tried increasing it,  my character seems to be stuck and not walking or moving.  I tried placing him in the middle of a four pokestop just to catch pokemon and that error still pops up. 
Help please!

**Comment by Bay101** [comment]
Make sure that you are on the latest version: https://github.com/Lunat1q/Catchem-PoGo/releases/download/v1.4.2.0/Catchem_v1.4.2.0_.7z

**Comment by pikopike** [comment]
its ban
stop bot asap
and try in 1h
