### ISSUE TITLE
Pokestops don't operate occasionally

### ISSUE THREAD

**Issue by Terroorr** [Lunat1q/Catchem-PoGo#306]
![capture](https://cloud.githubusercontent.com/assets/21138515/17829824/3694bfd6-66c3-11e6-8f05-cc3e54dbfc9d.PNG)

from 10 to 12 speed

**Comment by Lunat1q** [comment]
It's new softban, consider to stop bot for couple of hours

**Comment by Terroorr** [comment]
I did not stop the bot. Error appears and disappears itself.
I'm not sure, but when I evolved Pokémon is shut down ban.
The next time a ban will try again to evolve Pokémon.

(Я бота не останавливал. Ошибка то появляется, то пропадает сама.
Еще я не уверен, но когда я эволюционировал покемона то  бан отключился.
В следующий раз как появится бан попробую опять эволюционировать покемона. )
