### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by justchab042** [Lunat1q/Catchem-PoGo#309]
Hello, ( first of all sorry for my bad english ) I tried to put in the configuration "Translation language code " in French so "fr" instead of "en" but it doesn't work. It's possible to fix that or not ? I know this is not your priority at this time but it could be great if it worked ! Thank's for your job ! ;)

**Comment by angelusce79** [comment]
I would like a portuguese version (pt-BR ) to send me the code can translate for you!

**Comment by justchab042** [comment]
`  "StartUpSettings": {
    "AutoUpdate": false,
    "TransferConfigAndAuthOnUpdate": true,
    "DumpPokemonStats": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "StartupWelcomeDelay": false,
    "TranslationLanguageCode": "en",
    "WebSocketPort": 14251,
    "DisplayPokemonMaxPoweredCp": true,
    "DisplayPokemonMovesetRank": true,
    "StopBotToAvoidBanOnUnknownLoginError": true,
    "UseHumanPathing": true
  },`

So it's basic config but if I change "en" by "fr" I press save settings and I reboot the bot nothing changes in the console.
But starting the bot a yellow message appears saying : 

`[14:00:41] Translation for WelcomeWarning failed`

**Comment by algerino77** [comment]
Hello :)
I have the same problem, like justchab042.
The french translation exists but can not activate.

So, when active renaming Pokemon, it works in English, but not French ... The bot is also in English.
Thank you for helping us correct this problem :)

Otherwise, it's really good job , well done!

**Comment by Lunat1q** [comment]
reload UI after you changed lang code
