### ISSUE TITLE
The window doesn't fit the screen

### ISSUE THREAD

**Issue by mohhawk** [Lunat1q/Catchem-PoGo#313]
I meant the "Save Settings" button hides behind the taskbar so the bottom events in log , so I was forced to enable the auto-hide option of taskbar. Further more the window can't be resized vertically.
http://imgur.com/a/CgFqS
Using Windows 7 64-bit.

**Comment by angelusce79** [comment]
create a version of the program does not pass the taskbar if it is possible !

**Comment by dcmaster01** [comment]
same here didn't fit on my laptop thanks

**Comment by CDAGaming** [comment]
That would require a lot of recoding to have everything fit on that, even if it is a small size decrease

**Comment by CDAGaming** [comment]
But hey here's a fix, Enable auto hide taskbar :D

**Comment by Lunat1q** [comment]
fixed
