### ISSUE TITLE
farm near lured pokestops

### ISSUE THREAD

**Issue by Melessin** [Lunat1q/Catchem-PoGo#317]
how to farm pokemons near lured pokestops?
if I turn off "use discovery pathing" and set a little distance - he stands still, catches BUT does not collect pokestops
if I turn on "use discovery pathing" and set a little distance - he collects pokestops BUT finds pokemons near lured pokestops only every 5 minutes, when pokestops be available for collection (not looking for pokemons constantly)

**Comment by Lunat1q** [comment]
set movement speed to VERY low
