### ISSUE TITLE
[BUG?] Recycling and Transfering

### ISSUE THREAD

**Issue by Johnnywang2001** [Lunat1q/Catchem-PoGo#32]
The recycling system does not update fast enough and the Pokemon transfer system does not update either. I have to manually restart the bot so that they could be updated.

**Comment by conmicon** [comment]
try to edit config manually automaticinventorymangement to true, set "RecycleInventoryAtUsagePercentage" to 0.5-0.6

**Comment by Johnnywang2001** [comment]
I already set it to automatic but still doesn't really work...

**Comment by Johnnywang2001** [comment]
nvm works really well after I changed the Usage Percentage to 0.5!! Thanks!
