### ISSUE TITLE
Is it safe to use multi-account ?

### ISSUE THREAD

**Issue by khairulpetrcech** [Lunat1q/Catchem-PoGo#320]
is it safe to run multiple bot at the same time ? does anybody getting IP ban or softban? because both bot show using same IP..

**Comment by giovani3** [comment]
There was a time i used 3 acc at same time, dont know if was for that or not, but after a few minuts the pokestops disapear, so i stoped with that and now i only use 1

**Comment by erazyon** [comment]
If you use proxy for each bot it's ok.

**Comment by khairulpetrcech** [comment]
> If you use proxy for each bot it's ok.

any good free proxy provider ?

btw im using 2 bots right now..for more than 1 hour now,not getting ban...yet
