### ISSUE TITLE
Question about logs

### ISSUE THREAD

**Issue by giovani3** [Lunat1q/Catchem-PoGo#321]
Hello

I want to know if there is any chance i can see the logs in the console ( I had to close the bot, in order to log in my account in my android  to check if there was a visual bug in the bot) , cuz I had a dragonite 92% IV with 2550 CP that I upgraded 10 minuts ago, and after that I deleted some pokemons I didnt want there (deleted them in the bot), the question here is: I dont know if I deleted the dragonite too cuz i used the trasnfer all selectec pokemons or if he just disapear from my account.
Second Question: Does de Bot transfer favorite pokemons?
PS: Sorry for bad english

**Comment by Lunat1q** [comment]
there is a logs in the profile folder
