### ISSUE TITLE
MaxTravelDistanceFromStart 

### ISSUE THREAD

**Issue by erazyon** [Lunat1q/Catchem-PoGo#322]
Hi,

The bot travel everywhere, it could be nice if it could only travel in a selected area, for farming pokemon we looking for. 
So the most easy could be to put a radius with a MaxTravelDistanceFromStart. And the Most fun could be to select an area on the map drawing the area. 

I hope it's not too complicated to implement. 

Thank you for your great work.

**Comment by Bay101** [comment]
You need to disable discovery pathing and also set the max travel distance
