### ISSUE TITLE
fixed my question!

### ISSUE THREAD

**Issue by RafaeLqAe** [Lunat1q/Catchem-PoGo#323]
fixed sorry! :dash:

**Comment by oZacDo** [comment]
Give you two example ...

Config\translations\translation.en.json
set "en" into Translation language code

Config\translations\translation.uk_UA.json
set "uk_UA" into Translation language code

**Comment by standujar** [comment]
this is not working

**Comment by giovani3** [comment]
For me to work i Had to restart the bot
