### ISSUE TITLE
Evolve is now buged

### ISSUE THREAD

**Issue by standujar** [Lunat1q/Catchem-PoGo#324]
I can't evolve pokemons.. it dont work one by one too :'(

**Comment by oZacDo** [comment]
Me too.

**Comment by Messiah93** [comment]
Same.

**Comment by standujar** [comment]
Fixed, check if you have enought candys xD

**Comment by Messiah93** [comment]
The number of displayed candy is not always accurate. Sometime we can evolve, sometime we can't. Transfer also. I think it's an issue with the multi select.
