### ISSUE TITLE
can't use with google account

### ISSUE THREAD

**Issue by alexis01120** [Lunat1q/Catchem-PoGo#33]
i can't use the bot with google account, can you help me? 
(its work with ptc account) 
![b32882cd298a452b9d133a525c12407c](https://cloud.githubusercontent.com/assets/20953384/17645148/10c32dea-619d-11e6-8917-ebadfa957e6a.png)

**Comment by conmicon** [comment]
failed to get data from server. try it on your phone or nox

**Comment by Lunat1q** [comment]
Try to use app speciffic password.
