### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by madgar29** [Lunat1q/Catchem-PoGo#333]
I noticed your adding things to the pokemon what to do with them.... when it comes to evee are you going to let us rename her rainer or any of the others so she evloves differently... in my experience playing the game evee renaming her and then evolve has given me the biggest CP pokemon iv ever had infact in my arenas your gonna see a few rainers.......... just a suggestion to add...

**Comment by Lunat1q** [comment]
that "renaming" doesn't work, you know, right?
