### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by henriquemestre06** [Lunat1q/Catchem-PoGo#335]
First of all, thanks for your dedication :)

**## Suggestion:**

- Clicking on map, set automatically our coordinates.

Different types of booting ... For Example:
- Just find Pokemons
- Focus pokestops + Find pokemons
- Focus in pokestops
- Focus in gyms 
- Focus in gyms + pokemons
- Focus in all ( 20 min focus pokemons + 10 min gyms and last time focus pokestops)

Inventory (option):
- In Settings, we can create a desirable inventory list to the bot try to get as near as possible to that list.

**Comment by angelusce79** [comment]
great idea

**Comment by bunnymuny** [comment]
no good idea at all thegame will lose all the quality ........

**Comment by Lunat1q** [comment]
Sorry, i don't think what suggestions you made can improve anything.
