### ISSUE TITLE
Is not working?

### ISSUE THREAD

**Issue by loganout** [Lunat1q/Catchem-PoGo#338]
![image](https://cloud.githubusercontent.com/assets/4658212/17833897/3fa8d092-6701-11e6-87cf-072c3810073d.png)

**Comment by Scoopedd** [comment]
It appeared during using? Or during log in?

**Comment by Lunat1q** [comment]
banned, or api is dead

**Comment by loganout** [comment]
My login works in the normal game.
The bot log in and then it appears.
