### ISSUE TITLE
(ERROR) Niantic Servers unstable, throttling API Calls

### ISSUE THREAD

**Issue by TankardBR** [Lunat1q/Catchem-PoGo#339]
Can someone explain me this error? 
`(ERROR) Niantic Servers unstable, throttling API Calls.`

Thx so much

**Comment by jaydee9296** [comment]
Having this one too but meh I leave it aside. :)

**Comment by TomWolker** [comment]
PermaBAN...

**Comment by angelusce79** [comment]
(ERROR) Niantic Servers unstable, throttling API Calls  here too!

**Comment by standujar** [comment]
This is not permaban..

**Comment by ClaasPlayz** [comment]
and what is this than??

**Comment by Lichitisky** [comment]
Got that massage and then, this one: [15:20:13] (ERROR) PTC login failed. Make sure you have entered the right Email & Password. If you continue to get this, check your phone or Nox for a ban. Exiting...
