### ISSUE TITLE
Suggestion: Moves List&PokeBalls

### ISSUE THREAD

**Issue by MatkeMatke** [Lunat1q/Catchem-PoGo#34]
Hi - firstly I gotta say i simply LOVE the work you've made with the bot so far, cannot say I've found any real issues. I only suggest adding an option for us to see the moves of our pokemon while looking at the information tab - that way when we evolve or catch a new pokemon we can decide whether or not to keep it, based on the moves it has gotten.
The other suggestion would be a bit more control for our inventory, that is, pokeballs. I personally always discarded nearly all of my regular pokeballs and just kept the great/ultra balls. It would be awesome if you gave us an option to decide how many of each type we would want to keep. 
Another thing i would appreciate is for our "Pokemon to Not catch" list, to filter the pokemon the bot tries to snipe if we tick the "snipe at pokestop" location. In my case it kept sniping a lot of magikarps
and gastlys even though they are on my not to catch list.
Thanks for reading and keep up the great work ! p/

**Comment by Lunat1q** [comment]
Acceoted, please, check roadmap at discord.
