### ISSUE TITLE
force move bug

### ISSUE THREAD

**Issue by marvin448** [Lunat1q/Catchem-PoGo#340]
![image](https://cloud.githubusercontent.com/assets/21125541/17834817/969a2f26-6784-11e6-92b7-faded0a48d06.png)

i set force move near at player
i set too far
i set slitly near
all are not work on v1.4.3.0

v1.4.2.0
working

**Comment by Lunat1q** [comment]
Works just fine
<img src="http://i.imgur.com/sbWdjLV.png"/>
