### ISSUE TITLE
Suggestion: Pokemon List Settings in alphabetical order.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#341]
Dear Dev Support,

Could you please create an alphabetical order in Pokemon List Setting Tab from A-Z.

Thank you.

Keep up the Good Work!

**Comment by Bay101** [comment]
There already is an alphabetical sorting system implemented.

**Comment by alanearl** [comment]
Im using version 1.4.2? did you mean that version?
