### ISSUE TITLE
【bug】stop loop after sniping

### ISSUE THREAD

**Issue by pogoaccount** [Lunat1q/Catchem-PoGo#343]
Everytime after finish sniping, the bot could not loop the pokeonstop, and it is not IP ban. But after I restart the program, it works again.

**Comment by mikekng** [comment]
How do you activate sniping? I could not :(

**Comment by jimdana** [comment]
Could you so me how to turn on sniping? thanks

**Comment by jimdana** [comment]
could you show me how to turn on sniping, thanks

**Comment by pogoaccount** [comment]
I think the this issue could be fixed by making sure the role is back to the original place after snipe the last pokemon, because now the role stay at the place where the last sniped pokemon is locate.
