### ISSUE TITLE
Translation language code does not work

### ISSUE THREAD

**Issue by superdevil669** [Lunat1q/Catchem-PoGo#344]
I do not think it's logical or so I done something wrong?

![capture](https://cloud.githubusercontent.com/assets/8571116/17836003/562eae30-6784-11e6-980e-fdea0bbfe316.PNG)
![capture1](https://cloud.githubusercontent.com/assets/8571116/17836004/5a98728a-6784-11e6-96b6-12d8fc53a290.PNG)

**Comment by algerino77** [comment]
Hello :)

Same for me ;)
Before, we do an issue and the dev say : change language and reload, but it doesn't work...
How can we fix it ?

**Comment by algerino77** [comment]
I have test many things :
When i rename translation.fr.json to translation.en.json, it doesn't work.
The app create by itself a translation.en.json or, she edit translation.fr.json to translation.en.json ...

I don't understant why...

**Comment by Lunat1q** [comment]
Restart Catchem after changed translation

**Comment by algerino77** [comment]
It doesn't work :

https://github.com/Lunat1q/Catchem-PoGo/issues/378
