### ISSUE TITLE
Suggestion : manual path ?

### ISSUE THREAD

**Issue by Gunjha** [Lunat1q/Catchem-PoGo#346]
Hello;

it should be usefull to make our own path on the map
like the forced to move system but with steps 1 2 3 4 etc

i lived near a great parc and there is a lake
i can't make the bot run around the lake :(

![image](https://cloud.githubusercontent.com/assets/20795840/17836099/043b964e-6787-11e6-8589-c98a2781edcb.png)

**Comment by wakenabom** [comment]
2nd for this. i need it too.

**Comment by B1gM1k3** [comment]
Need it too !

**Comment by Broxxx3** [comment]
Please try with gpx pathing. It is exactly what you want.

**Comment by B1gM1k3** [comment]
I have a handmade gpx file but how to use it with Catchem ?

**Comment by Broxxx3** [comment]
Put it in the folder where "Catchem.exe" is. 
Edit your config file in "Profiles/bot_name/config/config.json" (with notepat or other editor).
Locate section LocationSettings or search for "UseGpxPathing" and "GpxFile". Set
"UseGpxPathing": true,
"GpxFile": "your_gpx_file.gpx"

**Comment by B1gM1k3** [comment]
Trying ^^ Thanks mate !

**Comment by Gunjha** [comment]
What's the structure of a GPX files ?
i never used it

**Comment by Broxxx3** [comment]
Feel free to try https://wtracks.appspot.com/.
Check "Don't save metadata" while saving.
