### ISSUE TITLE
API problem every 30 minutes Resetting GPX pathing

### ISSUE THREAD

**Issue by Broxxx3** [Lunat1q/Catchem-PoGo#350]
Every 30 minutes I get
[23:50:14] Niantic Servers unstable, throttling API Calls.

Side effect:
Because of the routing server problem I switched to gpx pathing.
At this point pathing is reset and the bot goes to the gpx file starting point ignoring routing at all walking through buildings and over water.

**Comment by inouext** [comment]
Same here:
Bot ignoring path routing and moving over streets, buildings and  water.
