### ISSUE TITLE
killswitch uses wrong amount of pokemon

### ISSUE THREAD

**Issue by marker2k** [Lunat1q/Catchem-PoGo#352]
My Bot is stopping after catching 25 Pokemon althoug Limit in settings is set at 41. 

[12:35:18] (ATTENTION) Max amount of pokemos 24,9 or pokestops 69,7 per hour reached, bot will be stoped for 43,0 minutes. 

Even defaultsettings in .sln-Projekt are saying         
public int MaxCatchPerHour = 42;
public int MaxPokestopsPerHour = 69;

Am i doing smoething wrong or is this a bug?

**Comment by Lunat1q** [comment]
he overreached pokestops.
