### ISSUE TITLE
Where i open the bot? LOL

### ISSUE THREAD

**Issue by itzJOKINHA** [Lunat1q/Catchem-PoGo#354]
Where is the .exe file to open the bot?

**Comment by B1gM1k3** [comment]
Have you unzip the file ? If correctly done you will have a Catchem.exe

**Comment by itzJOKINHA** [comment]
![image](https://cloud.githubusercontent.com/assets/20844112/17837138/790bda9a-67a2-11e6-9d82-5ccfe3d79c3a.png)
![image](https://cloud.githubusercontent.com/assets/20844112/17837139/81a8cc76-67a2-11e6-900f-2909ed68d6c6.png)

**Comment by itzJOKINHA** [comment]
I dont have nothing xD

**Comment by B1gM1k3** [comment]
You have not downlad the good file.
Try with this one : https://github.com/Lunat1q/Catchem-PoGo/releases

**Comment by itzJOKINHA** [comment]
![image](https://cloud.githubusercontent.com/assets/20844112/17837182/91ef451e-67a3-11e6-9eda-9212451e37c7.png)
![image](https://cloud.githubusercontent.com/assets/20844112/17837185/9928a58c-67a3-11e6-80ad-78ea82b6c32c.png)

I've downloaded it , and keeps not appearing xD

**Comment by B1gM1k3** [comment]
Look inside the Catchem folder.

**Comment by itzJOKINHA** [comment]
![image](https://cloud.githubusercontent.com/assets/20844112/17837197/2978a858-67a4-11e6-8940-366394d175ed.png)
Nothing o.O

**Comment by B1gM1k3** [comment]
Delete all the folder and re-extract the original file in a clean folder. Check also if your antivirus blocked the file during extraction.

**Comment by itzJOKINHA** [comment]
I dont have anti virus , and i already tryied to delete and re-extract ... :+1:  Nothing works wtf...

**Comment by itzJOKINHA** [comment]
Can you please DRAG here your .exe file

**Comment by B1gM1k3** [comment]
[Catchem.zip](https://github.com/Lunat1q/Catchem-PoGo/files/428835/Catchem.zip)

**Comment by itzJOKINHA** [comment]
Yap, its working ! +rep B1gM1k3
