### ISSUE TITLE
HELP? 

### ISSUE THREAD

**Issue by itzJOKINHA** [Lunat1q/Catchem-PoGo#356]
[14:17:35] (ERROR) System.ArgumentNullException: O valor não pode ser nulo.
Nome do parâmetro: ptr
   em System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   em PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) em D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 218
   em PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) em D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 51
   em PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() em D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   em PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() em D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() em D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:line 46
--- Fim do rastreio da pilha da localização anterior em que a excepção foi emitida ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() em D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 225
[14:17:35] (ERROR) Current Operation was canceled.

**Comment by caprae** [comment]
Valor não pode ser nulo.
Nome do parâmetro: ptr
