### ISSUE TITLE
this new version is getting meany errors and stopping...

### ISSUE THREAD

**Issue by claudiopn** [Lunat1q/Catchem-PoGo#359]
Could you please check why this version is stopping after few minutes? also almost every catch is excellent... I'm using the same figures than before (the standard ones)...

**Comment by TomWolker** [comment]
It is working normal for me . Of course I had to change various settings ... to outwit the softban

**Comment by g00tch** [comment]
I'm set at 6/kmh using a speed factor of 1....been running 11 hours continuous in a heavy pokestop downtown area.

Not a single softban. Actually haven't had one since 1.3.4
