### ISSUE TITLE
bug :

### ISSUE THREAD

**Issue by madgar29** [Lunat1q/Catchem-PoGo#366]
I admit i forgot to turn it off last time but it kept running and running.... problem was i woke up to it with 241/250 pokemon and it kept saying over and over pokemon inventory full transfer.... but it would never transfer like it always has? i reboot the program login to make it transfer or restart everything still not transferring....

**Comment by TomWolker** [comment]
check the pokemon listed "Pokemon List Settings" = (Not To Transfer list) 
check the box in the "Settings" = (Transfer Duplicate Pokemon)
