### ISSUE TITLE
I dont found .exe file...

### ISSUE THREAD

**Issue by itzJOKINHA** [Lunat1q/Catchem-PoGo#368]
One user tryied to give me the .exe file but that gaves me an error....
Please i want 1 link to download the NOT PROGRAMMER VERSION of Catchem

**Comment by EnzzoCaaue** [comment]
[Here](https://github.com/Lunat1q/Catchem-PoGo/releases) we have the releases, and [here](https://github.com/Lunat1q/Catchem-PoGo/releases/download/v1.4.3.0/Catchem_v1.4.3.0.7z) the latest version of Catchem.
