### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by pikopike** [Lunat1q/Catchem-PoGo#372]
Ty for programming BEST BOT EVER!

Like bot has xp/h. 
It would be nice to have POKESTOPS and POKEMONS / 24h   (since that`s one of main reason for bans)

Best regards
                      Fan

**Comment by Cranki** [comment]
+1
Ty for Bot bro, its really a nice one. No Ban 8 Days Account with that bot...
I miss the funktion to activate items on the Info screen. Lucky Egg and Incense would be awesome :)

**Comment by Lunat1q** [comment]
There is HOURLY limit settings.
