### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by SailingLion** [Lunat1q/Catchem-PoGo#375]
The bot downloads the new version, but does not install it.

**Comment by EnzzoCaaue** [comment]
Catchem does not need to be installed but unzipped

**Comment by SailingLion** [comment]
Yes, it doesn't apply the update..I don't have the new functions and it says it needs to update everytime I restart the bot..

**Comment by Lunat1q** [comment]
Then... Unzip it? 7zip isn't installed on every pc, so please do it by your hands.

**Comment by SailingLion** [comment]
Seriously this is how you are going to react..I thought donators had extra support? I ask a normal question because other bots unzip the file themselves..

**Comment by SailingLion** [comment]
Plus the bot says that it is installing the file when it's not so it's normal I think something is wrong. THANK U.
