### ISSUE TITLE
delay ??

### ISSUE THREAD

**Issue by Fpereirinha** [Lunat1q/Catchem-PoGo#376]
my bot wait 7-8 segs for all action, lool, speed factor solves it ?

**Comment by maxsofar** [comment]
There's delay settings

**Comment by maxsofar** [comment]
There are delay seetings

**Comment by Fpereirinha** [comment]
but my delay settings are all in 0

**Comment by hazmad** [comment]
could be slow connection (proxy?) mine goes slow on a slow connection

**Comment by Lunat1q** [comment]
Even with 0 delay bot will still do some, hardcoded as fool-safe logic.
