### ISSUE TITLE
Only green and blue lines

### ISSUE THREAD

**Issue by xXDjMikeXx** [Lunat1q/Catchem-PoGo#377]
I got only green lines and blue ones with google directions! Please help

**Comment by xPokemasterx** [comment]
You got an introduction for using google directions? i dont know what to do, to use it..

**Comment by hazmad** [comment]
@xXDjMikeXx Mine's working fine with google directions api. I'm guessing red is the future path, blue is the past path. looks like green is the non-human path (direct from stop to stop).

Are you using google directions api?

**Comment by Lunat1q** [comment]
Read release note!
