### ISSUE TITLE
Translation doesn't work even after a reboot

### ISSUE THREAD

**Issue by algerino77** [Lunat1q/Catchem-PoGo#378]
Hy !

So it's the third issues about that but a reboot of the app doesn't work...
A reboot of my computer doesn't work too...
I give you 10$ to help you solve this problem :)

----------------------------------------------------------------------------------------------------------
 
1st screen : I have fr in configuration file
![1](https://cloud.githubusercontent.com/assets/17982582/17839850/8762b4c6-67f5-11e6-8622-e967114d532c.jpg)

----------------------------------------------------------------------------------------------------------

2nd screen : I have the fr translation file
![2](https://cloud.githubusercontent.com/assets/17982582/17839851/87683e50-67f5-11e6-8da7-9cb20d56998b.jpg)

----------------------------------------------------------------------------------------------------------

3rd screen : I have an error message about translation when I start bot
![3](https://cloud.githubusercontent.com/assets/17982582/17839852/876a508c-67f5-11e6-909a-bfbabf9c1bcc.jpg)

----------------------------------------------------------------------------------------------------------

4th screen : we can see that it doesn't work...
![4](https://cloud.githubusercontent.com/assets/17982582/17839853/876efe52-67f5-11e6-97fb-e79202771963.jpg)

**Comment by Lunat1q** [comment]
I'll check that.

**Comment by algerino77** [comment]
Thank you so much !

**Comment by Lunat1q** [comment]
<img src="http://i.imgur.com/zvrNvRq.png"/>
<img src="http://i.imgur.com/2Cobf5y.png"/>
fixed.

**Comment by Lunat1q** [comment]
translation doesn't req reboot now

**Comment by algerino77** [comment]
Hy, 

I delete all my file of the bot, i download the latest version, configure all and put language to fr.
After that, i close the bot, reboot my computer and start the bot but still in english...
How you do the fr translation like your screen ?
And what is "req" ? 

Thank you very much !

**Comment by picobn** [comment]
Hello,

I'm French and I had the same problem.

I have downloaded your fix here : https://github.com/Lunat1q/Catchem-PoGo/blob/master/Catchem/Config/Translations/translation.fr.json
Now the translation file is working but there's other things strange :

 - When listing inventory in the console/map tab only the first sentence is in french
[19:30:29] (INFO) [Inventaire] Pokeballs: 39 | Superballs: 98 | Hyperballs: 0 | Masterballs: 0
[19:30:29] (INFO) [Inventory] Potions: 0 | Super Potions: 0 | Hyper Potions: 35 | Max Potions: 0 | Total: 35
[19:30:29] (INFO) [Inventory] Razz Berries: 145 | Bluk Berries: 0 | Nanab Berries: 0 | Pinap Berries: 0 | Wepar Berries: 0 | Total: 145
[19:30:29] (INFO) [Inventory] Revives: 25 | Max Revives: 0 | Total: 25

 - Same but inverted for pokeball throwing (1st sentence in english, 2nd in french)
[19:35:13] (PKMN) Throwing Spinning Excellent! PokeBall - WILL HIT
[19:35:15] (PKMN) (Capturé) |Normal-Roucool Lv 14,5 29,34% 220/272 | 40,01% Chance sur 49,77m | 38 PokeBall restant, 210

 - and the more important none of my pokemon and items are in french :)

Is it normal ? if not how can I correct this ?

Thanks for your help !
