### ISSUE TITLE
Catchem stop to work

### ISSUE THREAD

**Issue by 1below** [Lunat1q/Catchem-PoGo#380]
I can't install 
stopped to working after double click
![stopped wroking](https://cloud.githubusercontent.com/assets/21162247/17840122/ac7582b0-67d3-11e6-876d-c4a874edfbd3.png)

**Comment by ShadyBS** [comment]
Same here. Previous version works fine.

**Comment by ShadyBS** [comment]
running as admin solves the issue

**Comment by 1below** [comment]
i've tried many versions, but none works, even running as admin (win 7)

**Comment by Lunat1q** [comment]
Update .net
