### ISSUE TITLE
Google Maps Directions API with PTC

### ISSUE THREAD

**Issue by akadamente** [Lunat1q/Catchem-PoGo#384]
Can I use a PTC account with Google Maps Directions API?
If yes, how to set the API on Google?

**Comment by ShadyBS** [comment]
Instructions are on the release notes.

**Comment by akadamente** [comment]
Hello,
Thank you for your answer , but the Google Maps Directions API does not work .

When I create an identifier to generate a "Key API" . What key type should I choose ? ( Server or Navigator)
