### ISSUE TITLE
] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by PartyBoyPt** [Lunat1q/Catchem-PoGo#387]
im a little nuub so can someone help me?

**Comment by AoieGT** [comment]
I'm having the same error in the newest version. No issues with 1.4.3

**Comment by EnzzoCaaue** [comment]
Are you using more than one account at the same time ? If yes, are you using proxys in one of them at least?

**Comment by johnypedrolli** [comment]
@EnzzoCaaue 
Also I have the same problem , and I am NOT using More Than One Account

**Comment by jazekmon** [comment]
That's IP ban. Use proxy or VPN so you can have a new IP.

**Comment by andychuaaa** [comment]
Can I use more than one account at the same time? Or do I need to use VPN or proxy in order to do so?

**Comment by jazekmon** [comment]
Use proxy. There's a setting for proxy on every profile. This thread could help, somehow:
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/574784-238-free-pokemon-go-proxies-updated-7-21pm-est-8-20-2016-a.html

**Comment by Lunat1q** [comment]
Looks like it's solved.
