### ISSUE TITLE
Log 2 acc

### ISSUE THREAD

**Issue by Shoier** [Lunat1q/Catchem-PoGo#394]
09:59:08] (ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[09:59:08] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)

can you explain what shoud i change ?

**Comment by Lunat1q** [comment]
Try to google "Google app-password"

**Comment by Shoier** [comment]
what is google app password
