### ISSUE TITLE
Google Maps Directions API with PTC #384

### ISSUE THREAD

**Issue by akadamente** [Lunat1q/Catchem-PoGo#399]
Hello ,

Thank you for your answer , but the Google Maps Directions API does not work .
I do not understand the technical documentation.

When I create an identifier to generate a "Key API" . What key type should I choose ?
( Server or Navigator)

![capture](https://cloud.githubusercontent.com/assets/10062763/17851557/d7490176-6862-11e6-85f4-35084d2351fa.PNG)

**Comment by itterror** [comment]
javascript

**Comment by Turm86** [comment]
https://www.youtube.com/watch?v=CCZPUeY94MU 
Watch this Video from 2:05 to 2:53
Search for "Google Maps Directions API" instead of "Google Maps Android API"

**Comment by akadamente** [comment]
Thank you for your answers , I have an " API Key " ^^ .

I have a last question.

I have a PTC account.
This account is compatible with the " Google Maps Directions API " option?

**Comment by windclara** [comment]
just put the key to the blank
i use ptc account with Google Maps Directions API in my google account (which is blocked by niantic)
it works fine!

bot walks though the roads rather than cross the sea or houses !
