### ISSUE TITLE
Suggestion: Save/Load Multi Config Files

### ISSUE THREAD

**Issue by TemhAAhmeT** [Lunat1q/Catchem-PoGo#4]
Hi,
Awesome Bot/Gui. Thanks for that.

Also it would be perfect to Save/Load multiple configs.
Ex; I have dratini setting just for catching dratini family with dratini nest coords. (1)
     Also i do have online snipe setting with pogolocfeeder. (2)
     Also i do also have local config snipe settings. (3)

Every time i need to change settings or multiply folders and let everything get messed up with an update.

Wish to have that option just loads config-1.json, config-2.json etc.

Cheers

**Comment by Lunat1q** [comment]
That cant be done, cause srttings being changed too often.
