### ISSUE TITLE
action Interrupt

### ISSUE THREAD

**Issue by marvin448** [Lunat1q/Catchem-PoGo#400]
![image](https://cloud.githubusercontent.com/assets/21125541/17851958/3eb3371c-6897-11e6-827c-d5857ab2124b.png)

yes its work google map and looks like human walk
but once Interrupt they change new routing 

looting to pokestop change new route
![image](https://cloud.githubusercontent.com/assets/21125541/17852027/a079e914-6897-11e6-933d-7e58952d2e27.png)

catch a pokemon change new route again
![image](https://cloud.githubusercontent.com/assets/21125541/17852087/ec0eea0a-6897-11e6-8c43-5db68fd7aa82.png)

loot again on pokestop change new route again
![image](https://cloud.githubusercontent.com/assets/21125541/17852109/06db9f5e-6898-11e6-8a72-16d036908862.png)

still unstable bot cant decide one routing once interrupt they change new route

**Comment by marvin448** [comment]
update also moving very small area 
area A to Area B to area C then back to Area B and Area A Looping
![image](https://cloud.githubusercontent.com/assets/21125541/17853068/23d7239e-689d-11e6-81bd-8d5b712652dc.png)

**Comment by Lunat1q** [comment]
Are checked, everything work as it should be.
