### ISSUE TITLE
Suggestion: Pokemon Lists Settings in alphabetical order.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#401]
![qwera1](https://cloud.githubusercontent.com/assets/648116/17852351/7b27a320-6899-11e6-960d-8a13bb5a958a.png)

Dear Support Dev,

Please create a sort for this one.
Thank you.

Keep up the good work!

**Comment by Lunat1q** [comment]
No. They are in # ordered, as they should be.

**Comment by alanearl** [comment]
Dear Support,

Whats the use of # ordered?
