### ISSUE TITLE
google maps directions 

### ISSUE THREAD

**Issue by surfacing1976** [Lunat1q/Catchem-PoGo#407]
i try to create my route and i m going to be mad because i don t understand ,i m not a developper so i nreally need help ( my mother language is french) i try since i woke up 
hx for help

**Comment by Finrod87** [comment]
just follow the guide, then u get a API key. write it in the settings and the bot is creating a realistic patch. nothing more to do for u:)

**Comment by LucasLagrimante** [comment]
Hahaha, I'm Brazilian, but developer. My English is so bad.
Good luck

Em seg, 22 de ago de 2016 11:40, surfacing1976 <notifications@github.com>
escreveu:

**Comment by surfacing1976** [comment]
ok thx it s working now
