### ISSUE TITLE
Returning to 1st trackpoint after pausing by max. hourly rates or throttling api calls on niantic servers

### ISSUE THREAD

**Issue by Snurbsy** [Lunat1q/Catchem-PoGo#409]
Catchem returns to the 1st trackpoint, if the automatic pause after reaching the max. hourly rates for pokestops and/or pokemons catched. The same issue occurs, if api-request slowdown occours (msg "niantec servers unstable").

**Comment by Lunat1q** [comment]
Track point where? U mean during the route?

**Comment by Snurbsy** [comment]
Sorry, forgot to mention that pathing by gpx-file is in use.

**Comment by Lunat1q** [comment]
Gpx is obsolute. Will be replaced soon
