### ISSUE TITLE
How do I do it?

### ISSUE THREAD

**Issue by ChenQiuming** [Lunat1q/Catchem-PoGo#411]
'Client' does not contain a definition for 'InitialLatitude' and no extension method 'InitialLatitude' accepting a first argument of type
 'Client' could be found (are you missing a using directive or an assembly reference?)	PoGo.PokeMobBot.Logic

**Comment by ChenQiuming** [comment]
1.4.4.1

**Comment by Lunat1q** [comment]
Use git properly, or download compilled version
