### ISSUE TITLE
Not google account

### ISSUE THREAD

**Issue by cercado** [Lunat1q/Catchem-PoGo#413]
Hello,

I have an university Account that links to google with @polo.ufsc.br ending and I can't connect to catchem with it (I use it as my main account for pokemon go), and I do have another with @gmail.com and it works. What should I do?

> [15:45:32] (INFO) Logging in using account Google
[15:45:33] (ERROR) PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exceção do tipo 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' foi acionada.
   em PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:linha 40
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:linha 53
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:linha 32

**Comment by Finrod87** [comment]
Using the one with @gmail.com for botting:)

**Comment by cercado** [comment]
[15:35:23] (INFO) Logging in using account Google
[15:35:24] (ERROR) PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exceção do tipo 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' foi acionada.
   em PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:linha 40
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:linha 53
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:linha 32
[15:35:24] (INFO) Trying again in 45 seconds...
[15:35:48] (ERROR) Current Operation was canceled.
[15:36:09] (INFO) Your IP is: 150.162.25.51
[15:36:09] (UPDATE) Perfect! You already have the newest Version 1.4.4.1
[15:36:09] (INFO) Logging in using account Ptc
[15:36:11] (ERROR) PTC login failed. Make sure you have entered the right Email & Password. If you continue to get this, check your phone or Nox for a ban. Exiting...
[15:36:11] (INFO) Trying again in 45 seconds...
[15:36:13] (ERROR) Current Operation was canceled.
[15:43:18] (INFO) Your IP is: 150.162.25.51
[15:43:19] (UPDATE) Perfect! You already have the newest Version 1.4.4.1
[15:43:19] (INFO) Logging in using account Google
[15:43:20] (ERROR) PokemonGo.RocketAPI.Exceptions.GoogleOfflineException: Exceção do tipo 'PokemonGo.RocketAPI.Exceptions.GoogleOfflineException' foi acionada.
   em PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:linha 40
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() na D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:linha 53
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() na D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:linha 32

**Comment by valdirljr** [comment]
Or configure your acc with 2steps verification and create a password for the aplication: 
https://www.youtube.com/watch?v=SbUOMKZ7OpI
