### ISSUE TITLE
Google Directions API issue

### ISSUE THREAD

**Issue by Finrod87** [Lunat1q/Catchem-PoGo#416]
Hey,
thank u for your great work, i love your bot. But i noticed something today. I dont know if its a bug or just to hard to fix. The google directions API pathing works 95% the time just great. But sometimes he travels just from A to B to start a new pathing. The blue line is showing this.
![unbenannt](https://cloud.githubusercontent.com/assets/21174891/17864658/3991996a-689f-11e6-957a-873f3ee3e883.jpg)

**Comment by Icesenator** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/17598875/17865034/e4f4f22e-68a0-11e6-904c-6f455a93ca8b.png)

But very good job !

**Comment by KBLOSO** [comment]
My google directions seems not work. Is something i need to change in my configs? Thanks!

![image](https://cloud.githubusercontent.com/assets/20977814/17866580/60df3d46-687d-11e6-987d-d6a29b1a6986.png)

**Comment by Finrod87** [comment]
If it is a real API key the settings are fine. but u need to activate "use Mapzen Api elevation" if u want to use that key too.

**Comment by KBLOSO** [comment]
Mapzen seems not work in BRAZIL. I receive an error when i active this function. Do you know if Google Directions works in Brazil?

**Comment by Lunat1q** [comment]
just tested, works fine. that can be caused by GPX, but GPX  is obsolute, will be replaced soon

**Comment by HernestoSanchez** [comment]
Hey KBLOSO! Beleza? Cara como voce configurou essa API? To me batendo aqui pra descobrir como rodar. Tens como passar instruções de como conseguir a chave e montar a rota?
Valew

**Comment by KBLOSO** [comment]
Fala mano...Acesse o link https://console.developers.google.com/apis/...Selecione a API Google Directions API...Ele vai pedir pra vc criar um painel...vc cria...Uma vez criado...vc cria a chave do tipo Chave de Servidor...só copiar a colar a chave no bot...
Agora montar a rota me parece q ele monta sozinho.

**Comment by HernestoSanchez** [comment]
Opa! E eu aqui tentando fazer umas coisas mirabolantes (facepalm). Valeu brother!!

**Comment by KBLOSO** [comment]
Everything is working now Lunat1q!! Thank you and great work!

**Comment by HernestoSanchez** [comment]
Dammit. The bot hates me.

![image](https://cloud.githubusercontent.com/assets/21060440/17869271/e82b89f2-6888-11e6-86cb-1f86d2168427.png)


I cant get it working. He always go superman style all over the city

**Comment by KBLOSO** [comment]
Hey man. Make sure your API is active in API Management in your google account.

![image](https://cloud.githubusercontent.com/assets/20977814/17869521/0e2cfbda-688a-11e6-9459-ed1c024e5a13.png)

**Comment by HernestoSanchez** [comment]
Strange.... I copy and paste the key in catchem. The green lines appear but traffic on the website is dead

![image](https://cloud.githubusercontent.com/assets/21060440/17869870/832abd72-688b-11e6-9a95-80e72cf883b3.png)

**Comment by KBLOSO** [comment]
Wrong! Its Google Directions API!

**Comment by HernestoSanchez** [comment]
Oh My Dog! I knew i should have stopped on that eleventh Heineken!!!! (PUNCHFACE)
