### ISSUE TITLE
No Pokestops // No Pokemon

### ISSUE THREAD

**Issue by trytogetme85** [Lunat1q/Catchem-PoGo#417]
Hi,

I have 3 bots running, all same settings.

After one night running, there are no pokestops anymore
`19:38:49] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
`

The other issue, 2 of my bots dont have any pokemon in inventory. I dont know why
The one with a google-account has 34 - all 2 PTC accounts all have 0

**Comment by EnzzoCaaue** [comment]
It's not possible to bot more than one account at same time without a proxy. That might be your problem.

**Comment by Icesenator** [comment]
SoftIPBan

**Comment by trytogetme85** [comment]
Ok, that make sense.
But why I dont have pkmn? Yesterday before I go bed, there were about 10pkmn in all accounts.
In the morning, 2 of them were empty

**Comment by lukas1989** [comment]
i'm running two accounts at the same time without any proxy. still works but every couple of hours i get a softban. but thats the price.

**Comment by Finrod87** [comment]
U will get permabans soon. Its not safe to run 2 accounts without proxy. i think ur accounts are already flagged red.
