### ISSUE TITLE
My player stop

### ISSUE THREAD

**Issue by zBlackLion** [Lunat1q/Catchem-PoGo#418]
Hi, i have an issue, i come from Catchem v. 1.3.4.0, why my player don't walk in the map? He walk only if i use "force move", how can i fix? Is this a bug?

**Comment by lukas1989** [comment]
maybe you should use the latest release?

**Comment by kadius** [comment]
Hey, update the bot. The newest bot version is 1.4.4. Download another one. I'm sure it will be fixed. <3
