### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by isaac2016** [Lunat1q/Catchem-PoGo#42]
Hello, it shows some error messages after start. Is it my problem?

(ERROR) System.NullReferenceException: 
   PoGo.PokeMobBot.Logic.Inventory.<GetPokemons>d__29.MoveNext() 於 D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Inventory.cs:

**Comment by poopfeast42** [comment]
are your settings configured properly?

**Comment by Lunat1q** [comment]
Servers was unstable or u got banned
