### ISSUE TITLE
Pause Bot on Max Hourly Rates Rotine

### ISSUE THREAD

**Issue by olaioo** [Lunat1q/Catchem-PoGo#421]
When a check "Pause Bot on Max Hourly" option, the bot pause when over that rates. But the bot never starts again. Some solution?

**Comment by Charlier69** [comment]
Better, we can set the Braketime manuel, hope that function is comming soon

**Comment by ismail99** [comment]
I hope we get help about that option "Pause Bot on Max Hourly"  ?

**Comment by Finrod87** [comment]
The bot is pausing and starting again. It works fine.

**Comment by olaioo** [comment]
Finrod87 what version are u using?

**Comment by Charlier69** [comment]
Finrod87 mir too all works very Fine the is Runs since 8 Hours with pausings

**Comment by Finrod87** [comment]
Always the latest version olaioo.
