### ISSUE TITLE
Bot Can't get pokestop

### ISSUE THREAD

**Issue by RafaeLqAe** [Lunat1q/Catchem-PoGo#424]
Hi ! My bot and my phone can't get any pokestop, but a can catch pokemon!!!!

Anyone know how fix this?

#sorrymyinglish!

**Comment by ismail99** [comment]
same here !!!

**Comment by wesleyff100** [comment]
Same Here, don't load pokestops in some BOTs
![image](https://cloud.githubusercontent.com/assets/21182225/17870031/2a2dd19a-688c-11e6-94bf-74f76a7b0f5c.png)

**Comment by Charlier69** [comment]
Looks like a SoftBan!

**Comment by wesleyff100** [comment]
I Don't know, how the bot receive the coordenades ,but can is a bad responce from the server ,looks like a SoftBan

**Comment by RafaeLqAe** [comment]
But, softban, don't catch any pokemon, i can catch pokemon!!!

NEW SOFTBAN possible?

**Comment by Charlier69** [comment]
No! There are different softbans Maybe You can get pokestop and no cachtable Pokemons oder up ban or this one...

**Comment by Charlier69** [comment]
*IP ban

Google it there are  many infos about the Banoptions
