### ISSUE TITLE
Pokémon Info

### ISSUE THREAD

**Issue by Shadowxp13** [Lunat1q/Catchem-PoGo#426]
Hey, i really appreciated your work on this. I will suggest you a function that i think is really awesome.
I evolved so much pokémons through Catchem, but i cannot see their Attacks, and this would be really cool. Keep up the good work with this!

**Comment by madgar29** [comment]
He did add teams and it does visit arena's now so in my head that means he has arena play in his plans down the road......

**Comment by Shadowxp13** [comment]
If i wasn't clear, i only want to see pokémon attacks, nothing else.
