### ISSUE TITLE
[ FEATURE ] Automatic updates

### ISSUE THREAD

**Issue by valdirljr** [Lunat1q/Catchem-PoGo#432]
I have a message with "automatic updates are no enabled". 
I looked for a option to turn on automatic updates, but ... not exists ? 

Sorry for my english =/

**Comment by simpaticow** [comment]
go to config in users, open with notepad or notepad++ and set TRUE autoupdate

**Comment by imaheka** [comment]
```
      "Key": "autoUpdaterDisabled",
      "Value": "true"
```
correct me if i'm wrong.

**Comment by valdirljr** [comment]
Thanks

**Comment by rgrodrigo** [comment]
Thanks a lot!
