### ISSUE TITLE
Google Maps Directions API ipv6 ERROR

### ISSUE THREAD

**Issue by akadamente** [Lunat1q/Catchem-PoGo#433]
Hello,
I have a problem with Google Maps Directions API.
When I use my computer with an IPv6 address , the API does not.
But when IPv4 is used, the API works .

My network is IPv6 .

Do you have a solution for " Google Maps API Directions" runs IPV6 ?

**Comment by yibuliusheng** [comment]
may i ask how u create the google map direction api?
