### ISSUE TITLE
catch em .exe missing from file :(

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#436]
redownloaded three times and no exe file in all files.

**Comment by imaheka** [comment]
Where are you downloading? is that the 1.4.5?

**Comment by kingkai808** [comment]
from latest release wiki. just redownloaded again and nothing in file.

**Comment by kingkai808** [comment]
1.4.4.1

**Comment by vatch2** [comment]
Your anti-virus might be flagging the files and deleting it while extracting. Try to create a folder with an exemption  and download it there. Extract in the same folder aswell

**Comment by kadius** [comment]
Are u downloading the release version?
