### ISSUE TITLE
 is giving error escape (in Blue ) is this normal?

### ISSUE THREAD

**Issue by gabsanti** [Lunat1q/Catchem-PoGo#437]
I am Brazilian this working out your project anymore ta happening to me a lot

**Comment by matheusreis7** [comment]
yes

**Comment by matheusreis7** [comment]
you have pokeballs ?

**Comment by gabsanti** [comment]
yes friend will send the image to analyze you ok ?

**Comment by gabsanti** [comment]
[20:33:18] (FLEE) (Flee Attempt #2) | Lapras, Lvl: 10,5 | CP: (815/851) | IV: 67,97% | Type: Normal | Chance: 18,93% | Dist: 7,80m | Used: GreatBall (81 left) | XP: 0 |

**Comment by matheusreis7** [comment]
provable soft ban or ip,  reset your modem

**Comment by kadius** [comment]
Reset your modem and try another acc. If it still doing, idk what to do.

Reseta teu modem e tenta outra cont. Se continuar acontecendo, eu não sei o que pode ser.
