### ISSUE TITLE
Suggestion - Do not get Pokemon that I have not

### ISSUE THREAD

**Issue by rudacs** [Lunat1q/Catchem-PoGo#439]
You could put a new option to not catch Pokemon that are on the list not to pick up and also the Pokémon that has not.

Example: I have Pikachu, I do not want to find him take.
I think the emotion is able to find new ones.
Then take what I've got to be able to evolve, since improvement.

Thank you.

**Comment by oZacDo** [comment]
Can you give more example? 
It's hard to understand your point.

If your don't want to catch "Pikachu", your just need to add "Pikahu" into Not to Catch list.

**Comment by rudacs** [comment]
The idea is to only ease. Because I have to add all that I have. Or it could be a button that is added in this list.
