### ISSUE TITLE
Problem with pokémons to keep

### ISSUE THREAD

**Issue by maxlehot1234** [Lunat1q/Catchem-PoGo#441]
Hi, I set this to 0, but i have 4 MrMine, 2 kangaskhan, 2 krabby, etc.

Why?

I just to keep the best one of each types instead of keep multiple of them...

Thank you

**Comment by oZacDo** [comment]
Only clean your bag until usage percentage threshold.
No function can real time clean your bag now.

**Comment by maxlehot1234** [comment]
My bag have a lot of place.
Another thing, items won,t be recycled...

**Comment by oZacDo** [comment]
Do you means your item (Ball, Berry, ...) recycling function is always not working ?

**Comment by maxlehot1234** [comment]
Yes... and my pokémons won't be power-up...

**Comment by oZacDo** [comment]
It's probably new version bug.
Your only can wait fixed version or use old version.

**Comment by maxlehot1234** [comment]
Ok let's wait... No choice I think, because it is a real problem
