### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rsilveiradesouza** [Lunat1q/Catchem-PoGo#447]
Translation this not working for pt-br, I found that every time the program is initiate, it removes one "," the line 453 leaving the part of the wrong code and the program can not convert the file to json.

I did a workaround to work:
input = input.Replace("[Sniper] Nenhum pokemon encontrado!\"\n    }", "[Sniper] Nenhum pokemon encontrado!\"\n    },");

In the file "\ PoGo.PokeMobBot.Logic \ Common \ Translations.cs" line 618

**Comment by Lunat1q** [comment]
can be outdated, need someone to refresh it
