### ISSUE TITLE
When i used Google direction API

### ISSUE THREAD

**Issue by SeverusSnaps** [Lunat1q/Catchem-PoGo#448]
![map](https://cloud.githubusercontent.com/assets/21189506/17881400/3bbe6d36-692f-11e6-8bfc-fd88a3d3c167.JPG)
![plan](https://cloud.githubusercontent.com/assets/21189506/17881219/e78e886e-692d-11e6-9427-17a9a33ec3a7.JPG)
![setting](https://cloud.githubusercontent.com/assets/21189506/17881220/e78f5258-692d-11e6-9266-6d16dd0df091.JPG)

**Comment by b4545** [comment]
@SeverusSnaps you should keep your API key private. I would delete this key and create a new one, and next time don't share it publicly.

**Comment by xPokemasterx** [comment]
tokyo isn't a good spot for using that api key.. 
better go central park or somewhere else..

btw is there any introduction video how to get an api key?

thanks in advance!

**Comment by agon1982** [comment]
I have a problem when using Google Direction API. The bot start ok, choose 20 pokestops, the api give me the direction, but when bot reach the last pekestop it come back to the first one in a straight line.

is there a way to, when it reach the last pokestop, choose new 20 pokestops and trace a new route?

**Comment by SeverusSnaps** [comment]
@b4545 sry guy i think it's easy to get key lol The important issue is to used Google Direction API
