### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by b4545** [Lunat1q/Catchem-PoGo#449]
Error when trying to run bot:

![image](https://cloud.githubusercontent.com/assets/21189387/17881173/d96a69b6-68c8-11e6-9f8b-34657a8e2e8d.png)
[error.txt](https://github.com/Lunat1q/Catchem-PoGo/files/431738/error.txt)

To show that I have everything set up:

![image](https://cloud.githubusercontent.com/assets/21189387/17881848/1995814c-68ce-11e6-8a3f-d09ceaad7ae2.png)

![image](https://cloud.githubusercontent.com/assets/21189387/17881865/44745d8e-68ce-11e6-9c55-be30a95f28e0.png)

![image](https://cloud.githubusercontent.com/assets/21189387/17881857/3824320c-68ce-11e6-9ed3-ad6631a682ce.png)

**Comment by Lunat1q** [comment]
check your google account settings

**Comment by b4545** [comment]
I am sure that the Google account settings are fine. No two-factor, triple checked password, tried with and without "@gmail.com". I'm able to log into the official client with same credentials right after trying your bot with no problem. I tried to include useful data with this issue, but it's obvious how much effort you are willing to exert.
