### ISSUE TITLE
(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by Rassal** [Lunat1q/Catchem-PoGo#456]
> (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

Is it ban? how long will it be?

**Comment by Rassal** [comment]
ptc accounts work, but google accounts not

**Comment by kaku1237** [comment]
softban. try reset your modem. or use proxy

**Comment by flag1** [comment]
This is beacuse there's no PokeStop around you. Nothing to do with Ban.

**Comment by teddrick** [comment]
Change IP. Most likely IP banned.

**Comment by kingjman1994** [comment]
Sounds like IP ban, are you running multiple bots at a time? If so, try using a proxy or just running one account instead of a few.

**Comment by TenchuA** [comment]
It's always been a softban in my case IP ban and even I didn't used bot anymore, few weeks later I got perm ban. Seem Niantic search to perm ban all users who got softban.
