### ISSUE TITLE
Best cfg

### ISSUE THREAD

**Issue by Daud1337** [Lunat1q/Catchem-PoGo#461]
Hi,

What's the best cfg without ban and lot of XP and max CP pokemon ?

Thanks you for help

**Comment by kaktusisko** [comment]
1. How many accounts can I use with one Mapzen/Google API key?
2. What about best delays? (above 5000?)
3. Can I change Android Board Name and Firmware Brand to random text?

My config is working, but some accounts above 24 lvl was banned. (Why?)
It would be really great if somebody give a good example config.
