### ISSUE TITLE
TF under pokemon

### ISSUE THREAD

**Issue by Geko82** [Lunat1q/Catchem-PoGo#464]
Hi, thank you for hard work.
I have a question.
Under CP of pokemons there are some tag:
"ev" : if a pokemon is in evolve list; 
"nt" : if is in not transfer list;
but for what is "tf"? Not all pokemon have it. (Ex: on Eevee it is on)
Maybe it's a stupid question but someone can tell me?

**Comment by pedrollira** [comment]
Good question! I wanna know it too

**Comment by Lunat1q** [comment]
transfer filter, not implemented into UI, config file only for now.

**Comment by Geko82** [comment]
Thank you!
