### ISSUE TITLE
battery info 

### ISSUE THREAD

**Issue by tseries** [Lunat1q/Catchem-PoGo#467]
add please on sensors battery info , battery charge, battery radomize power, how with using powerbank etc.
I think they can find bot's with battery info

**Comment by tseries** [comment]
+ after battery is out make bot disconetc for hours...

**Comment by amisrtv** [comment]
Help you go to forums

**Comment by Lunat1q** [comment]
<img src="http://i.imgur.com/3rubPwi.png"/> no battery data there.
