### ISSUE TITLE
error cant run exe app

### ISSUE THREAD

**Issue by lubot67** [Lunat1q/Catchem-PoGo#47]
i cant open the app. it says "this app cant run on your pc"

and some message while extracting the zip
"!   C:\Users\Online Technician\AppData\Local\Temp\Catchem_1.2.5-1.7z: Unknown method in Catchem\adb\adb.exe
!   C:\Users\Online Technician\AppData\Local\Temp\Catchem_1.2.5-1.7z: Unknown method in Catchem\adb\AdbWinApi.dll
!   C:\Users\Online Technician\AppData\Local\Temp\Catchem_1.2.5-1.7z: Unknown method in Catchem\adb\AdbWinUsbApi.dll
!   C:\Users\Online Technician\AppData\Local\Temp\Catchem_1.2.5-1.7z: Unknown method in Catchem\Catchem.exe
!   C:\Users\Online Technician\AppData\Local\Temp\Catchem_1.2.5-1.7z: Error - operation failed
"

**Comment by Lunat1q** [comment]
un 7zip it before usage.
