### ISSUE TITLE
[FEATURE] Add multiple pokeballs recycle

### ISSUE THREAD

**Issue by maxlehot1234** [Lunat1q/Catchem-PoGo#472]
Hi, Please add all pokeballs types for recycle, so I can recycle greatball after 50 for example, etc.

I need to use another BOT just for this...

Thanks

**Comment by Lunat1q** [comment]
So u gonna keep great balls unstead of ultra? it's rediculous.

**Comment by maxlehot1234** [comment]
nope.
Keep 150 pkleballs, 50 great, 50 ultra instead of just a total of 200.

Because it is compltely ridiculous to keep only great balls.... Pokeballs can be use for pokémons lower than 900 CP easily

**Comment by maxlehot1234** [comment]
@Lunat1q Reopen please

**Comment by Lunat1q** [comment]
Are u insane? or what? so u gonnarecycle Greatball to keep more POKEBALLS???

**Comment by kakarotto** [comment]
So it prioritizes max/hyper potions over the simple one and master/ultra balls over pokeball on recycle?

**Comment by Lunat1q** [comment]
YES

**Comment by maxlehot1234** [comment]
Greatballs are for bigger CP pokemons, pokeballs for less than 1100, that's my point
