### ISSUE TITLE
Why diese?

### ISSUE THREAD

**Issue by Grieche** [Lunat1q/Catchem-PoGo#477]
![screenshot_1](https://cloud.githubusercontent.com/assets/20818303/17910989/c80facbc-698b-11e6-9d80-04f4c4a1b065.png)

**Comment by LifeForKill** [comment]
It is happening to me too

**Comment by LifeForKill** [comment]
its working now btw, at least for me

**Comment by mioriee** [comment]
It's probably because of route server down
