### ISSUE TITLE
Use Discovery Pathing not working

### ISSUE THREAD

**Issue by rodrigogs** [Lunat1q/Catchem-PoGo#478]
My config:
![1](https://cloud.githubusercontent.com/assets/2362425/17911248/eee5e258-6962-11e6-8e13-55a6ae4f870d.png)

The result:
![2](https://cloud.githubusercontent.com/assets/2362425/17911252/f0a6a7da-6962-11e6-98be-bb1a8fd50d5a.png)

**Comment by Lunat1q** [comment]
See No connection between discovery and off line routing server
