### ISSUE TITLE
Really? BAD HUMAIN ROAD

### ISSUE THREAD

**Issue by maxlehot1234** [Lunat1q/Catchem-PoGo#480]
![image](https://cloud.githubusercontent.com/assets/5159244/17911620/8d81890a-695c-11e6-95cc-2a6d7602fc95.png)

Seriously? This is really easy to detect by Niantic

**Comment by kingkai808** [comment]
right??? lol pier 39 is rough. i only stay to\\under the pier no go to the end because it walk across water.

**Comment by Lunat1q** [comment]
Ask google to fix Directions API
