### ISSUE TITLE
Selecte Area And Stay Here.

### ISSUE THREAD

**Issue by hardeath950** [Lunat1q/Catchem-PoGo#482]
It would be nice if you had a option to select an area on the map where you would wait " Spawn " of " Pokemon " .

Sorry for English but I am Brazilian .

**Comment by TomWolker** [comment]
Yeahh!

**Comment by Broxxx3** [comment]
Vote for!

**Comment by maxlehot1234** [comment]
You can do this by setting max travel disctancxes with a really small radius but it is not recommanded :P

**Comment by Lunat1q** [comment]
You can do it now. Set speed to 0.001
