### ISSUE TITLE
Really. Map issues

### ISSUE THREAD

**Issue by maxlehot1234** [Lunat1q/Catchem-PoGo#484]
![image](https://cloud.githubusercontent.com/assets/5159244/17914394/b0e3fa78-696f-11e6-818c-9926a8b2f02c.png)

Everything was say with this picture...

**Comment by Lunat1q** [comment]
It's a ferry?

**Comment by maxlehot1234** [comment]
@Lunat1q 
Ok, but dis doesn't help me with the error in the console...
