### ISSUE TITLE
What is this message mean?

### ISSUE THREAD

**Issue by JBWKZ2099** [Lunat1q/Catchem-PoGo#491]
I was running the bot in the newest version (1.4.5.0) that was released today and displayed the next message:

`(ATTENTION) Encounter problem: EncounterClosed`

I just start the bot, and I forced to move... then was when the message were displayed.

**Comment by MrCleverCoyote** [comment]
The program encountered a problem that it wanted to bring to your attention.

**Comment by JBWKZ2099** [comment]
I see, so I mustn't be worried about that message... thanks, bro
