### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#493]
what is the purpose of the auto complete tutorial, desired nick?

**Comment by betloga** [comment]
dati kc ggwa k p ng character lologin mo tlga cia s pokemon go app so ngaun mag sskip n cia rekta muna s bot mismo..

**Comment by kaktusisko** [comment]
What about best delays? (above 5000?)

**Comment by nicolaslevy91** [comment]
i change manually the important delays you should too @kaktusisko 

@wagas some ppl dont even bother to open the accounts on the phone, so the tutorial and the nickname and the first pkmn never are set.
Thats the reason.

Cya

**Comment by kaktusisko** [comment]
@nicolaslevy91 Can I change Android Board Name and Firmware Brand to random text?
