### ISSUE TITLE
Improves

### ISSUE THREAD

**Issue by nicolaslevy91** [Lunat1q/Catchem-PoGo#495]
Please @Lunat1q There were literally dozens of ppl asking for the following 3 features:
* implement to be able to check moves on information table!!
* Timer to turn off/on the bot with random time lap offset
* Able to turn on inciense / lucky egg from info tab

Also, personaly i think to be the best and perfect bot it would need:
An upgrade for the ForceMove feature: Manual entry of the path for the bot to take
It would be great to check the exact IV of atk def and sta, not the % of pure.

Bugs:

*The (Un) Favourite pkmn manually feature also does favourite, its good but i would just change the name Fav/Unfav Selected Pokemon

* Can transfer favourite pkmn (this should not be able to transfer)

* I dont know if im setting wrong the google directions (i think im dong it well)

![1](https://cloud.githubusercontent.com/assets/20948550/17917225/bf28a928-6990-11e6-8815-0284436b4d53.jpg)

I wish the best life for you and your family and friends this lasts 90 hours you dedicated to complete strangers mean a lot, at least for me.
Thanks.

**Comment by jobparengz** [comment]
i am also thinking about random delay catch and catch pokemon, pokestop etc on functions with <from>to <delay range>

**Comment by nicolaslevy91** [comment]
@jobparengz the delays are random each time you open the bot the delays change randomly

**Comment by nicolaslevy91** [comment]
BTW, i m trying to answer ppl that makes issues, since i cant help with code and programing, i will help on the new issues.

Cya

**Comment by jobparengz** [comment]
@nicolaslevy91 what i mean is that every movement the bot makes it does go random delay. coz once you open the bot the delay stays the same for whatever value it randomly sets on start. Thanks btw

**Comment by kaktusisko** [comment]
Proxy Checking Button should check is the proxy used for another account. Thanks,

**Comment by Lunat1q** [comment]
Delay is random. Each delay call
