### ISSUE TITLE
Bot doesn't use berry

### ISSUE THREAD

**Issue by tkien212** [Lunat1q/Catchem-PoGo#499]
> [xx:xx:xx] (PKMN) Throwing Spinning Excellent! UltraBall - WILL HIT
> [xx:xx:xx] (ESCAPE) (Escape) | Wartortle, Lvl: 24.5 | CP: (929/1085) | IV: 20.86% | Type: Normal | Chance: 6.11% | Dist: 60.69m | Used: UltraBall (xx left) | XP: 0 | 
> [xx:xx:xx] (PKMN) Throwing Excellent! UltraBall - WILL HIT
> [xx:xx:xx] (ESCAPE) (Escape Attempt #2) | Wartortle, Lvl: 24.5 | CP: (929/1085) | IV: 20.86% | Type: Normal | Chance: 6.11% | Dist: 60.69m | Used: UltraBall (xx left) | XP: 0 | 
> [xx:xx:xx] (PKMN) Throwing Spinning Excellent! UltraBall - WILL HIT
> [xx:xx:xx] (FLEE) (Flee Attempt #3) | Wartortle, Lvl: 24.5 | CP: (929/1085) | IV: 20.86% | Type: Normal | Chance: 6.11% | Dist: 60.69m | Used: UltraBall (xx left) | XP: 0

My Settings:
Use Berry Min Cp - 1500
Use Berry Min Iv - 90
Use Berry Below Catch Probability - 0.3

Shouldn't it met the third option and use berry? I checked its inventory when it happened and it still have 50 berries

**Comment by yashara19** [comment]
try this setting
check the box on use pokemon not to catch filter
Use Berry Min Cp - 200 (depends on pokemon's cp)
Use Berry Min Iv - 10 (depends on pokemon's min lv)
Use Berry Below Catch Probability - 0.5 (depends on pokemon's probability to catch)

setting should be set by your standard of using berries

**Comment by Lunat1q** [comment]
nope, there is that logic:
<img src="http://i.imgur.com/Ojkbn0h.png"/>
