### ISSUE TITLE
[Visual Bug] Information Tab - Sorting Buttons Disappearing On Form Resize

### ISSUE THREAD

**Issue by Thoridal** [Lunat1q/Catchem-PoGo#5]
The buttons **CP , IV** and **A-Z** used for sorting on the **Information Tab > Pokemons** disappear when maximizing the window. They seem not to be anchored to the rest of the window. Example bellow.

**Fully maximized Window**
![untitled](https://cloud.githubusercontent.com/assets/4540695/17606648/52d0b1e6-6029-11e6-9325-c2289e307d45.png)

**Resizing the form**
![untitled2](https://cloud.githubusercontent.com/assets/4540695/17606760/e9005716-6029-11e6-91fb-0d40ec2ae162.png)

**Comment by Lunat1q** [comment]
Got it, will fix this asap

**Comment by Lunat1q** [comment]
done :)
