### ISSUE TITLE
how do i start it

### ISSUE THREAD

**Issue by oOBlueArrowOo** [Lunat1q/Catchem-PoGo#50]

**Comment by poopfeast42** [comment]
download the zip file and launch it then create a profile and input your settings THEN press start

**Comment by poopfeast42** [comment]
"download this: https://github.com/Lunat1q/Catchem-PoGo/releases/download/v1.2.5/Catchem_1.2.5.7z
unzip Catchem_1.2.5.7z
go in folder and search for Catchem.exe"

literally 3 posts below this lol

**Comment by oOBlueArrowOo** [comment]
i cant find catchem 1.2.5.7

**Comment by poopfeast42** [comment]
go to downloads or recently downloaded in your browser and click show in folder

**Comment by oOBlueArrowOo** [comment]
still wont work

**Comment by Lunat1q** [comment]
look at git readme
