### ISSUE TITLE
Proxy help!

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#504]
I'm am new to this and I want to be able to run 5 accounts at the same time. But I don't know how proxies work or where to get them? I know using more than 1 account per device id per IP address is a sure fire way to get banned. Anyone experienced in proxies point me in the right direction so I can start using more than 1 bot? Thanks :)

**Comment by raviloga** [comment]
I would also like to know. Has proxy been disabled in 1.4.5.0?
