### ISSUE TITLE
[Fixed] IP Banning

### ISSUE THREAD

**Issue by Kaiserlz** [Lunat1q/Catchem-PoGo#509]
Firstly, I love your bot, it's pretty well coded and designed, and the user interface is pretty neat and intuitive.
With this new update, this message keeps popping up, and the player can't get any pokemon or pokestops... I tried to fix it in the settings, but can't seem to find it...

Is it possible that Niantic finally got us? =(

Regards.

A gratefull player.

**Comment by OSIRISzzGOD** [comment]
max travel distance = 5000 ,U change this ?
my friend change to 10k , now has no pokestop

**Comment by Kaiserlz** [comment]
No, I have not changed anything in my previous settings... It began yesterday, after the update...

**Comment by OSIRISzzGOD** [comment]
What Code u receive from progam same this or other?
[17:30:44] (ERROR) Niantic Servers unstable, throttling API Calls.

**Comment by Kaiserlz** [comment]
I get this code from time to time... but I did not calculate it though.

**Comment by Kaiserlz** [comment]
Nvm guys, it was my IP, they are banning IP now... just reset your router whoever gets this problem too...

**Comment by totolouis** [comment]
Use the search fierld next time :) your issue was fixed before

**Comment by Kaiserlz** [comment]
Sorry, I really did though... 

But the problem keeps happening every 10min or so... coudn't find a fix for that yet.

**Comment by totolouis** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/456
and change your parameters 

You can take this one : https://github.com/Lunat1q/Catchem-PoGo/issues/462

**Comment by ClaasPlayz** [comment]
What mean this Niantic Servers unstable, throttling API Calls. I have one account with this ?
