### ISSUE TITLE
Pokemon FLEE

### ISSUE THREAD

**Issue by claudiopn** [Lunat1q/Catchem-PoGo#510]
Hi, 
I'm very worried because in this new version every single pokemon that the program trows the pokeball FLEEs... I'm using practically the standard configuration and all of them are fleeing... could you please check why this is happening?
![capturar](https://cloud.githubusercontent.com/assets/21157859/17929150/01433aa0-69d5-11e6-8903-c93b8d99a192.JPG)

**Comment by rapdem** [comment]
Sounds like a ip ban reset your router if you have a dynamic ip.

**Comment by claudiopn** [comment]
I will try it, thank you so much!!
