### ISSUE TITLE
Reaname is buggy

### ISSUE THREAD

**Issue by C0D3D3V** [Lunat1q/Catchem-PoGo#515]
RenamePokemonTask should run before FavoritePokemonTask because of the condition at RenamePokemonTask.cs line 44

**Comment by Lunat1q** [comment]
RenamePokemonTask.cs is autorenamer, which SKIP renaming favorite pokemons. See no bugs in it.

**Comment by C0D3D3V** [comment]
It is a bug because Pokemons with a IV above FavoritePokemon IV will never be renamed.
