### ISSUE TITLE
Pokestop lucky number

### ISSUE THREAD

**Issue by Liframe** [Lunat1q/Catchem-PoGo#518]
"UsePokeStopLuckyNumber": true,
    "PokestopSkipLuckyNumberMinUse": 3,
    "PokestopSkipLuckyNumber": 1,
    "PokestopSkipLuckyMin": 0,
    "PokestopSkipLuckyMax": 4,

Any explanation for these lines? I wanna be able to keep on searching pokemons without using the pokestops (to avoid reaching limit and too much exp). Is it possible?

**Comment by Lunat1q** [comment]
It skip some pokestops while in Non Discovery pathing, actually, can be Obsolute.

**Comment by Liframe** [comment]
So if discovery path is enabled, I don't skip pokestops? Would it keep walking even if I hit pokestop limit? I wanna be able to earn exp mostly from catching pokemons and not thru pokestops. 

I really appreciate the job you're doing here, great bot :)
