### ISSUE TITLE
[Suggestion] Add delay between each snipe

### ISSUE THREAD

**Issue by retphern** [Lunat1q/Catchem-PoGo#52]
Adding some delay between each snipe, not just at pokestop start sniping delay helpful to prevent ban.
Just like pokesniper2 delay between snipe.

**Comment by Lunat1q** [comment]
check delay section

**Comment by retphern** [comment]
Delay between each individual snipe. In delay section only min delay to start sniping not each snipe.
![1](https://cloud.githubusercontent.com/assets/4834781/17651038/b0d40fb2-6287-11e6-8712-3df959c02889.png)
![2](https://cloud.githubusercontent.com/assets/4834781/17651039/b0da01ba-6287-11e6-8c2a-897b63537a1c.png)
