### ISSUE TITLE
Pokemons with a IV above FavoritePokemon IV will never be renamed.

### ISSUE THREAD

**Issue by C0D3D3V** [Lunat1q/Catchem-PoGo#523]
Sorry that I open that issue again but I don't know if you read closed issues.

RenamePokemonTask should run before FavoritePokemonTask because of the condition at RenamePokemonTask.cs line 44

It is a bug because Pokemons with a IV above FavoritePokemon IV will never be renamed.

**Comment by Lunat1q** [comment]
Will recheck that. But i bet u don't read code in right way.

**Comment by C0D3D3V** [comment]
This bug happens if you  start the bot with a account that have not favorited Pokemons with IV above FavoritePokemon IV.

**Comment by C0D3D3V** [comment]
Because the auto favorite feature will favorite the pokemon before the auto rename feature  can rename it.

**Comment by Lunat1q** [comment]
ok, it's not a bug.
Bot will never evolve favourite pokemon.
You can evolve it by hands.
Case closed.

**Comment by C0D3D3V** [comment]
why the fuck should this not be a bug. This fucking pokemons get not renamed.

**Comment by Lunat1q** [comment]
<img src="http://i.imgur.com/81OyUM1.png"/>
can u read?
Favourited pokemons can be renamed only from UI, autorenamer will not touch them. THAT WORKS HOW IT SHOULD BE.

**Comment by C0D3D3V** [comment]
you say the auto rename feature should only work without the auto favorite feature?
