### ISSUE TITLE
upcomingo captcha bot check

### ISSUE THREAD

**Issue by Mordascar** [Lunat1q/Catchem-PoGo#524]
what  kind of behaviors should we avoid ? will there a way to make the captcha appear for us while using the bot, so we can answer it manually ?

**Comment by kaktusisko** [comment]
www.deathbycaptcha.com

**Comment by Lunat1q** [comment]
Captcha isn't a problem, for now.

**Comment by HernestoSanchez** [comment]
Now that´s a desperate measure! Captcha huh? What wll be Niantic next step? Stop developing the game so no one could play it? 0.o
