### ISSUE TITLE
Only Excelent and Great Throws !

### ISSUE THREAD

**Issue by narutozordom** [Lunat1q/Catchem-PoGo#526]
My bot only throws excelent and great pokebol, this is normal ? have any configuration to change this ? this not like a human player, maybe a huge chance of detection.

**Comment by Lunat1q** [comment]
read wiki

**Comment by narutozordom** [comment]
Bro, i read all wiki and faqs and postsn and find nothing about this, u can help to solve that problem ? 

    Em Quarta-feira, 24 de Agosto de 2016 11:57, Max <notifications@github.com> escreveu:
 

 read wiki—
