### ISSUE TITLE
It may expose us...

### ISSUE THREAD

**Issue by kaktusisko** [Lunat1q/Catchem-PoGo#534]
1. I think that we shouldn't transfer Pokemon and get their list for each start. It may expose us...
Can you randomize this moments?

2. Can you add minimum Delays as in official apk?

3. Please add information about how many accounts can we set per api?

**Comment by Icesenator** [comment]
4. Add some random transfer when walking ?

**Comment by Finrod87** [comment]
option to trandfer pokemon right after the catch like i always do while playing legit.

**Comment by HernestoSanchez** [comment]
Humm.. good point. Maybe an option to randomize this moments and another as Finrod mentioned. Something like. Transfer after catch if IV < xx

**Comment by noeldiego** [comment]
Does that interfere on our account or is just a client-side thing? And what about the item checks? I find it so unnecessary. It should be optional. If that tickles the server, pulling info, i guess it expose us indeed.

**Comment by Lunat1q** [comment]
Fixed
