### ISSUE TITLE
cannot auto evolve

### ISSUE THREAD

**Issue by saldotman** [Lunat1q/Catchem-PoGo#535]
pokemon with num of candies exactly the same as minimum required candy, can not evolved automatically. example, vulpix that has 50 candies

**Comment by lukaz0rz0** [comment]
I have the same issue, first I thought that was a problem with configurations but nothing seems to fix it

**Comment by gadgetmase** [comment]
have you added vulpix to the pokemon to evolve list?

**Comment by afr044** [comment]
Got the same problem :( I want to  evolve all Pidgey, Rattata, Weedle or Caterpie when I got enouth candies (actually 1000+ each one, got 30/40 Pokémons each), but they don't :( This Pokémons are the only one added on "To Evolve" List.
