### ISSUE TITLE
Fly over the buildings

### ISSUE THREAD

**Issue by Alicesaglisse33** [Lunat1q/Catchem-PoGo#537]
Hello,
My bot do not use the human pathing even if it's checked. Do you have a solution ?
(The bot fly over the buildings travelling from a pokestop to an other pokestop, not using the street like an human)
Thanks.
(Sorry for my english, i'm french..)

**Comment by Icesenator** [comment]
Salut, je suis fr aussi, tu utilise quel service de routine ?

I use Google API but can you (or add a setting) to increase waypoint between pokestop to avoid :
![image](https://cloud.githubusercontent.com/assets/17598875/17939853/a53b8a7a-6a2c-11e6-8c78-8c222a50a0bd.png)

**Comment by Alicesaglisse33** [comment]
Salut, j'utilise Mapzen API Elevation.
I can see the red path, but not always.
Merci de ta réponse rapide.

**Comment by Lunat1q** [comment]
It's because of difference between Google Map and OSM

**Comment by Icesenator** [comment]
No I already check that.
