### ISSUE TITLE
Error v1.3.0.1

### ISSUE THREAD

**Issue by lainhacker** [Lunat1q/Catchem-PoGo#54]
look error which new version (sorry for my englis) :

[23:46:21] (ERROR) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PoGo.PokeMobBot.Logic.Tasks.CatchPokemonTask.<Execute>d__1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\CatchPokemonTask.cs:ligne 131
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.PokeMobBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\CatchLurePokemonsTask.cs:ligne 59
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.PokeMobBot.Logic.Tasks.FarmPokeStopsDiscoveryTask.<Execute>d__1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsDiscoveryTask.cs:ligne 161
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\FarmState.cs:ligne 54
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:ligne 38
[23:46:35] (RECYCLING) 33x ItemPokeBall
[23:46:39] (INFO) Logging in using account Google
[23:46:44] (ERROR) System.UriFormatException: URI non valide : Impossible d'analyser le nom d'hôte.
   à System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   à System.Uri..ctor(String uriString, UriKind uriKind)
   à System.Net.Http.HttpClient.CreateUri(String uri)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 98
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 65
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:ligne 52
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:ligne 161
[23:46:44] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: Lng: ( I HAVE DELETE MY POSITION SECRET)
[23:46:45] (ERROR) System.UriFormatException: URI non valide : Impossible d'analyser le nom d'hôte.
   à System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   à System.Uri..ctor(String uriString, UriKind uriKind)
   à System.Net.Http.HttpClient.CreateUri(String uri)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 98
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 65
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__1.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Map.cs:ligne 69
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.MapCache.<UpdateMapDatas>d__6.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\MapCache.cs:ligne 39
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.InfoState.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\InfoState.cs:ligne 21
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\StateMachine.cs:ligne 38

**Comment by lainhacker** [comment]
and : [01:21:05] (ERROR) Niantic Servers unstable, throttling API Calls

**Comment by Scoale** [comment]
you are too fast down the rate at Km 9 min is 15 Km Max is his pass.

**Comment by Lunat1q** [comment]
Duplicate
