### ISSUE TITLE
Eevee evolution

### ISSUE THREAD

**Issue by renatopaulos** [Lunat1q/Catchem-PoGo#542]
There could be the information tab, in the pokemon context menu, an option to select the evolution of Eevee to rename the pokemon before the evolution automatically.

There could be even an option for "Evolve Eevee preferably to ..." that renames before evolution.

It's nothing too serious or that it can not do without, but it would be nice ...

**Comment by Lunat1q** [comment]
It doesn't work, you know? there was an issue 100% like this.

**Comment by EnzzoCaaue** [comment]
Well, @Lunat1q , I've done this like all time and always worked to me. :|

**Comment by renatopaulos** [comment]
For me also always worked, @Lunat1q @EnzzoCaaue . Renaming and evolving accordingly. But it's alright. It was only a suggestion.
