### ISSUE TITLE
Future thing

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#544]
i think it´s good to know i you know how far is it to the target, if you make an ForceMove?!
ATTENTION) ForceMove to xxxxxx - xxxxxx Started (xx,xx meters)

**Comment by Lunat1q** [comment]
Sure, that's easy to do.

**Comment by Charlier69** [comment]
Thanks :-)

**Comment by Lunat1q** [comment]
done
