### ISSUE TITLE
Excellent and great throws !

### ISSUE THREAD

**Issue by narutozordom** [Lunat1q/Catchem-PoGo#545]
Only excellents and greats throws, I read all wiki, faqs and posts, but can't find de solution, anyone can help me. it is not humanized throw and probably easy to detect for niantic.

**Comment by rcarrillom1410** [comment]
Decrease the max accuracy to 0.8 and the min to 0.6, also activate humanize throws

**Comment by narutozordom** [comment]
Very thx, bro u solve my problem !
