### ISSUE TITLE
ERROR LOGIN

### ISSUE THREAD

**Issue by PascalLzx** [Lunat1q/Catchem-PoGo#548]
Hello, I have this error when I click on start button : 

[00:05:22] (INFO) Logging in using account Google
[00:05:22] (ERROR) System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   à DankMemes.GPSOAuthSharp.GoogleKeyUtils.ParseAuthResponse(String text) dans D:\Ketchum\Catchem-PoGo\GPSOAuthSharp\GPSOAuthSharp.cs:ligne 143
   à DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data) dans D:\Ketchum\Catchem-PoGo\GPSOAuthSharp\GPSOAuthSharp.cs:ligne 60
   à DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion) dans D:\Ketchum\Catchem-PoGo\GPSOAuthSharp\GPSOAuthSharp.cs:ligne 83
   à PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__4.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Login\GoogleLogin.cs:ligne 24
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 54
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:ligne 32
[00:05:22] (INFO) Trying again in 45 seconds...

[00:06:07] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Une exception de type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' a été levée.
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:ligne 79
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:ligne 0
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() dans D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:ligne 53
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() dans D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:ligne 225
[00:06:07] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40,7824630901822 Lng: -73,964570100074 Alt: 12
[00:06:07] (ERROR) Niantic Servers unstable, throttling API Calls.
[00:06:20] (ATTENTION) Current Operation was canceled. Bot stopped/paused.

Can you help please ? 
PS: I'm not banned or soft banned.

**Comment by OSIRISzzGOD** [comment]
U fill name in the Desire Name box ?

**Comment by PascalLzx** [comment]
"Auto complete tutorial and set name as below" is not selected et desired nick is "CatchemFanea9wnc" @OSIRISzzGOD

**Comment by Lunat1q** [comment]
Try google spec account pass

**Comment by PascalLzx** [comment]
Its already google spec account pass @Lunat1q
