### ISSUE TITLE
Can master make it able to make a automation that switches between 2 accounts? #Catchem

### ISSUE THREAD

**Issue by h3wiin** [Lunat1q/Catchem-PoGo#552]
Want to set 12Hx2 between me 2 account. Would that be possible?

**Comment by trainermortiz** [comment]
how about switch to run another account every hour... i want that! :) so that we could limit pokemon catch and pokestops.

**Comment by h3wiin** [comment]
Yepp.  Cooldown timer in sidebar.

**Comment by h3wiin** [comment]
Black one

**Comment by kollp3** [comment]
do you want a ban.. 
because that's how you get a ban
