### ISSUE TITLE
Encounter problem: Lure Pokemon NotInRange : seems to result in IP ban

### ISSUE THREAD

**Issue by GhostMidnight** [Lunat1q/Catchem-PoGo#553]
Hi, 

Encounter problem: Lure Pokemon NotInRange : seems to result in IP ban.

Sorry if I missed any info on this, but I didn't see anything in the issues list related.

What causes this error? How can we avoid it?

BTW great bot, thanks.

**Comment by Lunat1q** [comment]
U can just skipp it, nothing serious

**Comment by GhostMidnight** [comment]
Well, it just happened again  and the IP I was using got banned. No
pokestops etc showing. So I'll burn through IPs eventually.
