### ISSUE TITLE
Please add option about nice, great, excellent percentage

### ISSUE THREAD

**Issue by zeldaleonz** [Lunat1q/Catchem-PoGo#554]
please add option to set how much percentage will be throwing will result nice,great, excellent throw.
- too much excellent or great will make it show it not very human.
- too much excellent throw make faster level up and not too good
- even nice throw with just 100 exp will be good for us to stock up stardust until next level up, i mean prolonged time to get level up ( i think this more human behavior, not many always get excellent throw)

thanks for your time

**Comment by juliopokemon** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/21186387/17955860/8815758a-6a5b-11e6-9ba8-f6cca24830c8.png)

always 100 exp

**Comment by zeldaleonz** [comment]
How about if i want make chance of excellent is only 10% will occur,  great
20 %, least is nice?

Thank for your great work

**Comment by zeldaleonz** [comment]
Oh, my bad not to think about that, thank you sir

**Comment by zeldaleonz** [comment]
I think its closed enough
