### ISSUE TITLE
Custom Waypoint

### ISSUE THREAD

**Issue by zeldaleonz** [Lunat1q/Catchem-PoGo#555]
Is there any way to make custom waypoint for bot, to just wandering in closed and specific poke stop only?
and if all of that area the pokestop is already collect, the bot will use standby mode (stand still)
or any option for bot only just sit around and waiting any pokemon nearby/lure come.

Its Great project sir, thanks for your hard work

**Comment by Lunat1q** [comment]
There is forcemove option.
