### ISSUE TITLE
Got banned a lot this version

### ISSUE THREAD

**Issue by noeldiego** [Lunat1q/Catchem-PoGo#558]
Sometimes i login and there's not any pokestop appearing. Even to newly created account. And since i can't check pokemon's moveset and have the urge to login and check that, 2 acc of mine got banned, even when i login at the exactly same spot i stopped the bot (using tutuapp pokemon go).

Is that happening to someone else? Login and there's not a single pokestop around, and you know there are a lot of them at that location.

**Comment by mastema13619** [comment]
All of our got "We are humbled by your incredible response..." and now they just refuse our connection.

**Comment by ankhmok** [comment]
i can even start the bot, it always show "Niantic Servers unstable, throttling API Calls."

**Comment by ronniebigtiger** [comment]
Maybe you can test it again using the cell phone, sometimes it can be recover by relocate the GPS.

**Comment by Icesenator** [comment]
Ignore "Niantic Servers unstable, throttling API Calls." btw.

**Comment by alanearl** [comment]
The main problem is you must use 4G-HSPA+ Network.

**Comment by noeldiego** [comment]
@mastema13619 At tutuapp pokego - I didn't see this message, yet. I just see a "failed login" message and a retry blue button (at that gyarados screen). And when using the normal pokego, can't the login screen.

@ankhmok at the last version, i was getting that a lot and then i found out i was banned already.

@ronniebigtiger no sucess to recover the banned accounts. Sad i got a 100% dratini, cubone, 98% karps :'(

@Icesenator sometimes it happens while playing and things continues normally, but when you see it happening a lot, it's banned, at least in my case i was.

@alanearl I didn't. I play at home and i use the same wi-fi on both pc and android. The past versions didn't do that, i didn't get banned like in this one. Maybe niantic is raising its awareness.

I always use the humanize option, low speed walking, no Teleport, no snipping (is that even possible in this version) pause after 40 pokecatchs or 50 pokestops and so.

**Comment by GhostMidnight** [comment]
I have had this happen to me and found if I use a new IP address via proxy etc ... the stops reappear for my account.  Seem like it would happen every time I see this message also: Encounter problem: Lure Pokemon NotInRange. Or accidentally teleport by keying in the wrong coordinates doing the same as you have. (was only by a couple hundred meters)

Also it would be great if we could see move sets as I sometime prioritize those over IV at times when deciding which dupes to transfer or evolve.

**Comment by noeldiego** [comment]
I made a fresh acc, login at the default location (central park) and there was not a single pokestop nearby and the avatar just stood still.

**Comment by noeldiego** [comment]
@GhostMidnight I read that proxies are resulting in permaban faster, then i was afraid of using it and all my accs are not behind proxy. Is that a reason to get banned faster too? Is proxy a must or really recommended?

**Comment by noeldiego** [comment]
@GhostMidnight the pokestops reappered after renewing the IP. Thanks for the tip!
