### ISSUE TITLE
PokemonTransferFilter doesn't work

### ISSUE THREAD

**Issue by carminaburana123** [Lunat1q/Catchem-PoGo#564]
So i tried to install the PokemonTransferFilter manually by editting the file in profiles. 
But it gets overwritten when i start the bot. 
I do not see any option to use the PokemonTransferFilter in the menu. How should i activate this option???

**Comment by alanearl** [comment]
![capture1](https://cloud.githubusercontent.com/assets/648116/17965830/2caa2d12-6af1-11e6-95e7-dbd31713b656.PNG)
![capture2](https://cloud.githubusercontent.com/assets/648116/17965831/2cba465c-6af1-11e6-9c3f-0fccdd278a15.PNG)

**Comment by Lunat1q** [comment]
Transfer Filer will be implemented later.
