### ISSUE TITLE
where I can configure pause time on max X/hour ?

### ISSUE THREAD

**Issue by raulken78** [Lunat1q/Catchem-PoGo#566]
where I can configure pause each X dust, or pokemon, or exp?
thankyou

**Comment by B1gM1k3** [comment]
Settings -> Pause on max hourly rates, and you choose what you want.

**Comment by raulken78** [comment]
I dnot find It, where is? sorry for your time

**Comment by gdtesam** [comment]
![capture](https://cloud.githubusercontent.com/assets/21229905/17962617/9f459f48-6aa9-11e6-8661-eabb8fe5dc37.PNG)

**Comment by B1gM1k3** [comment]
Check the box. And set what you want here.
Max catch per hour (pokemons per hour)
Max pokestops per hour
XP per hour
Stardust per hour

**Comment by raulken78** [comment]
I found it but sorry, I am find the "seconds of pause", so id this limit is reach oh many time is in pause? sorry for my eng and ty

**Comment by gdtesam** [comment]
i'm not sure this is correct as i haven't tried it,
but say you put Max Catch Per Hour 20, if you get 20 pokemon in 30 minutes it would pause and then start again once 1hr has passed.

**Comment by raulken78** [comment]
ok, and instead of 1hr can I configure this pause on X seconds, for example 2000 seconds? or better a range for example from 1000 to 25000 seconds? ty And may beautifull a automatic night pause of 9hours... and 1 dinner etc XD tyyyy

**Comment by B1gM1k3** [comment]
The bot actually allows only pause on pokemon catch, pokestop, xp or stardust per hour.
You cant ask it to stop after x hours. (or i didnt found the option)

**Comment by GhostMidnight** [comment]
My recent pause showed "bot will be stoped for 173.0 minutes".

Yes, would be a good option to set a min and max time for pause. 

Thanks

**Comment by Lunat1q** [comment]
Minutes are being calcualted on the rates.

**Comment by raulken78** [comment]
what is the caluculated param? so how I can configure for just 15min of pause?! ty
