### ISSUE TITLE
sign in error

### ISSUE THREAD

**Issue by yashara19** [Lunat1q/Catchem-PoGo#568]
I got this message does this mean i got banned?

(ERROR) PTC login failed. Make sure you have entered the right Email & Password. If you continue to get this, check your phone or Nox for a ban. Exiting...

**Comment by gdtesam** [comment]
have you tried to login to the PTC site? maybe their servers are down. just a thought

**Comment by yashara19** [comment]
yep I tried but I got message to verify my account. but I cant verify it beacause I accidentally add extension domain to my email but I already contacted them regarding to that issue.
