### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by luisclaudiojr** [Lunat1q/Catchem-PoGo#578]
When changing the location , either by map or by the lat and long , the program goes into an infinite error

**Comment by pikopike** [comment]
How big was the change of the location? (1km, other country other continent )

**Comment by luisclaudiojr** [comment]
other continent, but, the bot is offline, i am create new bot and try this location:
45.03011194599717,-93.31930540502071

I tried to change comma( ,) by dot (.) but the error persists

this location is very good, have 6 poke lured, better than the central park

**Comment by pikopike** [comment]
I think you need to wait if you want to jump like 1h... however I would suggest you using same location... less risk for ban...

**Comment by luisclaudiojr** [comment]
Take the test with another account never used , open the Catchem in lat put what I went through and long put what I went through thee , you will see that the error will happen, it prevents me hunt in other places other than the central park, 
I believe to be some Catchem failure to find the locations .

**Comment by pikopike** [comment]
put in central park catch 1 pokemon or spin 1 pokestop... than tp to new location as soon as you spin or catch ban... try it out... you need to do somthing to get bant only tp will not get you ban...

**Comment by luisclaudiojr** [comment]
I know the risks , but it was to give to change the latitude and longitude was not it? if I want to go somewhere else , it does not work ? I tried to the map , but the error is the same

**Comment by pikopike** [comment]
... im not talking about the risks. You CANT change location (to other country or continent) without soft BAN...
its the same for all bots. this is how game is made... and its not a BUG...

**Comment by luisclaudiojr** [comment]
yes , I know that in reality the problem is not softban , the account is new , I want to start it right in this location and it 's me the following error, i am try , and . in the geolocation this: 45.03011194599717,-93.31930540502071

[11:32:59] (ATTENTION) Translation for WelcomeWarning failed
[11:32:59] (ATTENTION) Coordinate failure, please check them again!

**Comment by Lunat1q** [comment]
Update.
