### ISSUE TITLE
Does not loot while force move

### ISSUE THREAD

**Issue by itterror** [Lunat1q/Catchem-PoGo#58]
The forcemove function is really great, on the other side the bot does not look any pokestop encounterd.

Also it would be great if you have started a force move, you can abort it by clicking somewhere else and redirecting.
But that would be just nice to have.

**Comment by chyle** [comment]
yup.. ive noticed that also.. on the bright side.. it still catch pokemon on the way.. hehe

**Comment by Lunat1q** [comment]
there is no way to loot pokestops while it moves. for now. aborting path can be done.
