### ISSUE TITLE
Future Thing? :)

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#582]
Is there in the Future the optin so set more than one ForceMove?
so i can set ForceMove 1 than ForceMove 2 ForceMove 3... now i have to wait to reach the first ForceMove and than i can set the secound one.

**Comment by Cranki** [comment]
or a route :)

**Comment by serik78** [comment]
Custom Routes will Implemtend soon -> https://github.com/Lunat1q/Catchem-PoGo/issues/538
