### ISSUE TITLE
Low Catch rate

### ISSUE THREAD

**Issue by alyssonwentz** [Lunat1q/Catchem-PoGo#583]
Hello. I started the bot in tokyo.
6-12 km/h catch all.
Mas catch per hour: 40
[x] Catch wild pokemon.
I dont know why, in 46 min i just captured 3 pokemons.
Robbed a lot os pokestop, but i'm not catching.
The problem its not the location, i get lvl 5 manually in 20 in, captured 10, 15 pokemons.
Do i have some config that i dont observed?

**Comment by Lunat1q** [comment]
Nope, shouldn't be a problem tbh, try restart or change location

**Comment by alyssonwentz** [comment]
Actually i solved it. Its was about the delay pokemon caught. I don't know which specifically, i reduced all of then.
