### ISSUE TITLE
Request: evolve Pokemons if you have xx Pokemons that could be evolved

### ISSUE THREAD

**Issue by Cranki** [Lunat1q/Catchem-PoGo#584]
Hi Guys,

super thanks for the nice bot.
It would be great, if the Bot count the total amount of your current Pokemons that could be evolved and shows it on screen.
Like
You have 20 Pokemons that culd be evolved.
And then a Command that read this info and eolve Pokemons at a number that the suer set.
For example.
StartEvolvePokemonsIfCurrentAmountEvolveablePokemonsIS: 20,

So the Bot read the amount of the evolveable Pokemons compared with the List of PokemonsToEvolve, shows it in the Screen and if the amount is at the same Number as the COmmand StartEvolvePokemonsIfCurrentAmountEvolveablePokemonsIS: 20, then the Bot starts to evolve them.
Best Regards

Crank

**Comment by alyssonwentz** [comment]
It would be great if have the option to use lucky egg automatically before start all the evolutions too.

**Comment by Lunat1q** [comment]
roadmap, discord.
