### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#585]
I propose to make an additional window with a standard gaming interface and the ability to take a screenshot of the window. This feature is very handy to take screenshots on the sale of accounts and do not have to go to nox each time .
Under standard gaming interface , I mean it http://screenshot.ru/e389d81f489da430944d857a969cbfbd
I do not know how much it would be difficult to implement , but the function would simply elegant .
___________________________________________________________________________________________________________

Предлагаю сделать дополнительное окно со стандартным игровым интерфейсом и возможностью сделать скриншот данного окна. Данная функция будет очень удобна для того, чтобы делать скриншоты на продажу аккаунтов, и не придется заходить в нокс каждый раз.
Под стандартным игровым интерфейсом, я имею ввиду это http://screenshot.ru/e389d81f489da430944d857a969cbfbd

Не знаю, на сколько сложно будет это реализовать, но функция была бы просто шикарная.

**Comment by Lunat1q** [comment]
Очень сложно. Делать не буду.
Way to hard and useless, feeling free to do it by yourself and pr
