### ISSUE TITLE
Why Sourcecode?

### ISSUE THREAD

**Issue by Charlier69** [Lunat1q/Catchem-PoGo#592]
Why you give us the Sourcecode, Niantic can see it too?!

**Comment by pikopike** [comment]
https://github.com/Lunat1q/Catchem-PoGo/releases/tag/v1.4.6.0

**Comment by Cranki** [comment]
Yes I admit, no one need the Code. Its your Code and you should keep it in your safe until the day you dont want to keep on the work with Bots!
So please keep it hide from now on!
