### ISSUE TITLE
[BUGSSS] Can't power up/levelup/transfer pokémons automatically

### ISSUE THREAD

**Issue by maxlehot1234** [Lunat1q/Catchem-PoGo#594]
Hi, I can't levelup pokémons sometimes, it simply doiesn,t work and have candy and stardust.

The autolevelup simply doesn't work too. I need to use another bot to this.

The pokémons won't be transfer automatically... I have 21 Golbat... It was not in the" not to transfer" list.

These bugs are really bad and I have this for few versions now...

**Comment by Lunat1q** [comment]
Everything works just fine for me and thousands of users. U fucked up with your settings.
