### ISSUE TITLE
Pokestops - No usable PokeStops

### ISSUE THREAD

**Issue by Stefanoac** [Lunat1q/Catchem-PoGo#598]
![sempokestops](https://cloud.githubusercontent.com/assets/1659676/17983580/c0c79c90-6ae3-11e6-92b0-8f85e57361ac.PNG)

Can't find pokestops here, but have so much...

**Comment by maxlehot1234** [comment]
You are probably ban

**Comment by alyssonwentz** [comment]
Ip ban i guess. Chage your ip (if dynamic) by turning off your modem, and restarting 15s later. If its a Fix IP, you need to use proxy.

**Comment by Lunat1q** [comment]
ip ban, 100%
