### ISSUE TITLE
Telegram command

### ISSUE THREAD

**Issue by eduardoedson** [Lunat1q/Catchem-PoGo#601]
listbots command don't work with me

**Comment by Finrod87** [comment]
i think it doesnt work with 1 bot. but u dont need that command if u just have one.

**Comment by eduardoedson** [comment]
i have two

**Comment by Finrod87** [comment]
then just try 1 and 2 and keep it in mind until a fix comes :package:

**Comment by kaktusisko** [comment]
Bot should stop in case of changes in the game and send notification to the Telegram!

**Comment by lfgranja** [comment]
Seems like the command is "bots", not "listbots"
