### ISSUE TITLE
Checking Inventory again, again and again :S

### ISSUE THREAD

**Issue by TomWolker** [Lunat1q/Catchem-PoGo#602]
After reaching the limit of 350 items , he decides to check the inventory, but he do every 1-2 minutes ... I tried to set the limit for pokeballs , potions, razzberry in 1000 , but this not has resolved . This leaves the bot slow ...

When there pokemons around he focuses on them , but when not, he decides to check the inventory instead of go to pokestops ...

![image](https://cloud.githubusercontent.com/assets/21134965/17988581/8daf0680-6afd-11e6-8124-628d8703bae3.png)

Thanks.

**Comment by Lunat1q** [comment]
U have wrong settings for feeling amount of items.
