### ISSUE TITLE
Proxi list?

### ISSUE THREAD

**Issue by Slipknotivo2** [Lunat1q/Catchem-PoGo#603]
Help! Proxy list avatible? Proxy is http. Proxy 4 or 5? Good bot and thanks for help friend!

**Comment by kaktusisko** [comment]
Public IP's will not work.
They are blocked.

**Comment by Slipknotivo2** [comment]
Use proxy sock 4? Or??? All proxy connect fail

**Comment by kaktusisko** [comment]
They are blocked.
