### ISSUE TITLE
[Enhencement] Add Pokemon MOVE information 

### ISSUE THREAD

**Issue by spambox1404** [Lunat1q/Catchem-PoGo#604]
Thank you making a very good program. I'm enjoy it very much. It will be the best if you can visualize the move of each pokemon, my picture is a suggestion, you can overwrite the text over pokemon icon or make smaller pokemon  icon. Thank you!
![image](https://cloud.githubusercontent.com/assets/21224382/17989664/54daaa60-6b59-11e6-82e5-ea91a99807e2.png)

**Comment by wakenabom** [comment]
2nd for this. 
i hope u can add INFO from console to Information tab in list view. Thanks in advance.
![info](https://cloud.githubusercontent.com/assets/8787638/17992788/e247d18e-6b7c-11e6-9b7a-59639d13ca2c.jpg)

**Comment by Lunat1q** [comment]
Let me see... It's in roadmap:)
