### ISSUE TITLE
How to prevent soft ban?

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#61]
im always getting soft ban and my ip always gets block.. please help

**Comment by Scoale** [comment]
Speed Max 9 KM/H i play the bot 16 Times and no Ban :)

**Comment by wagas** [comment]
thanks... is that the only setting you change after downloading the bot?

**Comment by Scoale** [comment]
and Humanize throws and finish

**Comment by Scoale** [comment]
[config.txt](https://github.com/Lunat1q/Catchem-PoGo/files/417369/config.txt)

**Comment by adeputu** [comment]
Try Human Pathing too, it'll move from 1 stop to another using direction from Google, so it will be more 'human'

**Comment by Scoale** [comment]
and especially not to multi account on the same IP (IP Direct Ban)

**Comment by wagas** [comment]
multi account on 1pc? what if im going to use 2 computer.. but same connection.. is it ok?

**Comment by Scoale** [comment]
not good I tested it is my ban my IP Modem.

**Comment by Scoale** [comment]
is good after 50 minutes
[PokeMobBot-2016-08-15-02.txt](https://github.com/Lunat1q/Catchem-PoGo/files/417382/PokeMobBot-2016-08-15-02.txt)

**Comment by wagas** [comment]
thanks
