### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TinhuRJ** [Lunat1q/Catchem-PoGo#611]
Here in Brazil , it is not working , only the message " ( ATTENTION ) No usable PokeStops found in your area . Is your maximum distance too small ? "

I'm not banned, it works with other bots and on my phone, only in Catchem not find pokestops

**Comment by madgar29** [comment]
usually a sign ur softban

**Comment by jeffersonvs** [comment]
(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
what is this?
