### ISSUE TITLE
Restricting walking in the map

### ISSUE THREAD

**Issue by goiabs** [Lunat1q/Catchem-PoGo#615]
I think you could add a function that allows to determine (restrict) a region to walk in the map. It would be very useful to walk through a place that has a pokemon nest and only catch that specie. For example: in the image below, we see a magikarp nest only in the sea shore. To prevent that I walk around a big region that there are not magikarps, I would draw a region in the map which I will walk in. See:

http://i.imgur.com/IY1WG7d.png
![screenshot_108](https://cloud.githubusercontent.com/assets/21255689/17995473/7792365c-6b38-11e6-8757-9d90cf2419d1.png)

http://i.imgur.com/8UAJI4l.png
![capturar](https://cloud.githubusercontent.com/assets/21255689/17995487/8a88ef6c-6b38-11e6-89f7-8a1a240944ba.PNG)

I see that, actually, we don't have a control of the places that the bot walks. So, it would be very nice!

**Comment by Lunat1q** [comment]
And also that will require quite a lot of rewrite, Not sure what i'll do it soon.
