### ISSUE TITLE
Range of limited values per hour

### ISSUE THREAD

**Issue by hazanpro** [Lunat1q/Catchem-PoGo#616]
There is a way to control when the bot will take a break of playing by using limit to some options (pokemons/pokestops/exp/stardust etc...)
My suggestion is putting a range of each limit that will pick randomize while bot starting again, that makes more human like playing...

Because if someone botting at place that have lots of pokestop the bot will stop the most of time by pokestops limit, and this will be always the same value!

But if the limit to stop will catch you every time by the pokestops limit and it have a range that randomize each time the bot is starting you have different values to stop the bot

Happy botting every one :)

**Comment by Lunat1q** [comment]
:/.... i see no point to randomize that data, it's already being randomized well enough.

**Comment by hazanpro** [comment]
@Lunat1q thanks for comment
i had another question, if i want to stop the bot only when im reach X exp per hour
for now, X is a constant that i have to change every time...
so niantic can see that im not a human, because when they count my exp per hour is always X

while if its randomize (min X max Y) the bot pick a value and every hour im botting my exp will be change, and im still stop playing

if u think if not useful i cant do nothing...
but i really want it, i think ur bot is awesome!

and really thanks for the fast replay
