### ISSUE TITLE
Exploration radius setting?

### ISSUE THREAD

**Issue by Siedjeey** [Lunat1q/Catchem-PoGo#619]
There is this rare pokemon spawning place near where I live with only 3 pokestops so I set up the bot there but there is also this one annoying Pokestop pretty far off and i don't want to go there but the bot keeps walking over there, wasting a lot of time and also traversing terrain that is normally not possible...

Is is possible to perhaps implement a radius where you can explore or exclude some pokestops?

**Comment by guiguigui222** [comment]
Yeah I have 4-5 pokestops with lure that I'd like to farm but I can't cause it also takes all the other pokestops in the range that I put in the settings

**Comment by itterror** [comment]
is this an issue tho?
set min radius so the pokestop is out of range and turn off discovery pathing and you are fine.

**Comment by Siedjeey** [comment]
Ok so travel distance is not the max amount of kilometers walked, the wording was a bit weird to me. So it IS the exploration radius so to speak. What does discovery pathing actually do? It was on by default iirc.

**Comment by Siedjeey** [comment]
Hmm when I turn off Discovery Pathing the bot seems unable to find a valid Pokestop and just keep standing still and not even catching Pokemon that spawn... Also the Pokestop should reactivate after 5 min to be able to use again normally...
