### ISSUE TITLE
Sometimes even with correct position and config bot says : No usable Pokestops found in your area (...)

### ISSUE THREAD

**Issue by skzbr** [Lunat1q/Catchem-PoGo#62]
Tested spawning from the same coordinate point on the latest build of Necrobot and Catchem, Necrobot works fine, catchem does not work sometimes.

What this could be?
Apparently all configs looks fine.

UPDATE: sometimes work, sometimes not.
UPDATE 2: when i deselect human pathing, dont work.

ERROR: http://prnt.sc/c5s74u

Config used looks fine: http://prntscr.com/c5s63i

**Comment by skzbr** [comment]
Take a look into settings again, and then the bot set altitude 53421523524353 random number. Maybe thats why not found.

**Comment by Lunat1q** [comment]
I'll take a look at this.

**Comment by CaMoTraX** [comment]
Getting this error for about 12 hours now. Cant level my account anymore...

**Comment by itmightbeyou** [comment]
i think it is an IP ban. Been troubled by this for the past few days already

**Comment by Bay101** [comment]
Try force moving the character by double clicking on the map to somewhere nearby to see if that fixes it.

**Comment by Lunat1q** [comment]
banned or servers are unstable
