### ISSUE TITLE
sex selection)

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#625]
Просьба, реализовать выбор пола, при создании персонажа. (как дополнение к функции просмотра туториала и выбора ника) Просто многие не хотят бабами играть, желательно создавать парней)
__________________________________________________________________________________________________________
Please realize sex selection when creating a character . ( In addition to the options for viewing and selecting the tutorial nick ) Simply, many other women do not want to play , it is desirable to create guys)

**Comment by juliopokemon** [comment]
you can change sex at any time

**Comment by Lunat1q** [comment]
no. avatar will be random one.
or do it manually with your phone.
