### ISSUE TITLE
Recycle Settings??

### ISSUE THREAD

**Issue by kakarotto** [Lunat1q/Catchem-PoGo#626]
Hi, is there a way to be more specifics about recycle itens?
There are only options to recycle "potions" and "pokeballs", and I wanna to recycle the lesser ones only, and leave alone greatball, ultraball, max potion.

Because right now the bot recycled all my great and ultra balls =[

**Comment by kakarotto** [comment]
Like This:

 "TotalAmountOfPokeballsToKeep": 40,
    "TotalAmountOfGreatballsToKeep": 80,
    "TotalAmountOfUltraballsToKeep": 120,
    "TotalAmountOfMasterballsToKeep": 100,
    "TotalAmountOfPotionsToKeep": 3,
    "TotalAmountOfSuperPotionsToKeep": 5,
    "TotalAmountOfHyperPotionsToKeep": 10,
    "TotalAmountOfMaxPotionsToKeep": 30,
    "TotalAmountOfRevivesToKeep": 20,
    "TotalAmountOfMaxRevivesToKeep": 40,
    "TotalAmountOfRazzToKeep": 50,

Would be great to individualize each item

**Comment by Lunat1q** [comment]
Look at #472

**Comment by maxlehot1234** [comment]
@Lunat1q 
This would be AMAZING, but you doesn,t want to add it, it's ok but that's bad.
Pokeballs are used for less than 1000 cp pokemons for example
