### ISSUE TITLE
Coordinate when you save, doest not work.

### ISSUE THREAD

**Issue by skzbr** [Lunat1q/Catchem-PoGo#63]
When sometimes you save some coordinate, the bot just spawn you in the middle of the nowhere,  just like 0,0,0 coordinate of the world.

Then if you look into config saved

"DefaultLatitude": -23587458396918148.0,
    "DefaultLongitude": -46655847085773743.0,

He just drop the zero after all the coordinates,

The error with the coordinate problem: http://prntscr.com/c5sdjz

But, anyway, the bot looks incredible! You are doing a really good job, thank you!

**Comment by Lunat1q** [comment]
Where are u from? What's your language settings?

**Comment by TemhAAhmeT** [comment]
My lang setting is en. And i have that problem too.

**Comment by enryIT** [comment]
Make sure you have dots or commas in the coords text boxes as it depends on your language settings.

**Comment by skzbr** [comment]
Yep, its not a lang problem, en or pt-br, is the same problem. I didn`t even change de lang.
I`m from Brazil.

but okay, let's assume that I'll put it  respawn by the click where I want to (before start the bot of course).  The problem still happens, he just send me to the middle of the nowhere

**Comment by manfras** [comment]
I´m from Brazil also and I can only make it work if I change Latitude and Longitude directly inside the json file. Use dot, not commas inside json.

**Comment by Lunat1q** [comment]
Yeah, that issues cause Brasillian players. Should take a look

**Comment by Antister** [comment]
im from argentina and have the same issue, must use the inglish lang in my pc?

**Comment by fgrep** [comment]
That is a problem with any country that uses comma **,** as a decimal separator.

A quick fix is to go to Windows regional settings and change the formart to English US
http://www.blackbaudknowhow.com/wp-content/uploads/2011/10/windows7.jpg

**Comment by skzbr** [comment]
Lunat1q, when switch bot`s tab, he erases the dot (.) or comma (,) of the LAT,LONG, maybe this is one of the causes of the error that i said on other issue.

Other issue, the new build 1.3.1, random crash, no reason after 2 minutes started.

**Comment by skzbr** [comment]
My Windows is PT-BR, but my keybord is US international.

**Comment by Lunat1q** [comment]
try latest

**Comment by Lunat1q** [comment]
fixed
