### ISSUE TITLE
Telegram not work

### ISSUE THREAD

**Issue by fredimartins** [Lunat1q/Catchem-PoGo#631]
i complete the guide to create a telegram bot 2 times and have a same issue:
-  Bot not answer any command
-  The name of sender is only "@"

![catchem](https://cloud.githubusercontent.com/assets/8070129/18005642/a0961f08-6b71-11e6-93c0-725fa783c2f6.png)

**Comment by Lunat1q** [comment]
u set no owner. READ WIKI

**Comment by fredimartins** [comment]
Sorry, I removed it today.
I put the name but still can not get the answer. What name should I put?
I expected that the name appeared on the console, so I could copy and paste the name to owners.

**Comment by fredimartins** [comment]
all right now
