### ISSUE TITLE
[Feature Request] PokemonTransferFilter

### ISSUE THREAD

**Issue by carminaburana123** [Lunat1q/Catchem-PoGo#634]
I try to discribe the perfect PokemonTransferFilter for me:

# Example Code

```json
"<Pokemon1>": { 
		"KeepMinCp": 500,
      	"KeepMinLvl": 5,
      	"UseKeepMinLvl": true,
      	"KeepMinIvPercentage": 60.0,
      	"KeepMinDuplicatePokemon": 1,
      	"Moves": [],
      	"DeprecatedMoves": [],
      	"KeepMinOperator": "and",
      	"MovesOperator": "or",
      	"OverwriteIV": "true",
      	"OverwriteIVValue": 95.0
    },
"<Pokemon2>": { 
		"KeepMinCp": 500,
      	"KeepMinLvl": 5,
      	"UseKeepMinLvl": true,
      	"KeepMinIvPercentage": 60.0,
      	"KeepMinDuplicatePokemon": 1,
      	"Moves": [],
      	"DeprecatedMoves": [],
      	"KeepMinOperator": "and",
      	"MovesOperator": "or",
      	"OverwriteIV": "true",
      	"OverwriteIVValue": 95.0
    }
```

## Explanation

**Comma seperated list**
```json
"<Pokemon>": {...},
"<Pokemon>": {...},
"<Pokemon>": {...}
```
So the first part would be a comma seperated list of every pokemon you want in there. Between de {}-brackets you can assign the parameters.

**Minimum Combat Power**
```json
"KeepMinCp": 500,
```
This is the minimum combat power for a pokemon. Every pokemon below this will be transferred

**Minimum Lvl**
```json
"KeepMinLvl": 5,
```
This is the minimum level for a pokemon. Because who wants 22 rattata's of lvl 3.

**Do we need to use the minimum lvl**
```json
"UseKeepMinLvl": true,
```
Ok the minimum lvl is indeed usefull, but the cp and IV are way more important than the lvl. So maybe we don't wanna use the lvl option. (you can also set the KeepMinLvl to 0)

**Minimum IV**
```json
"KeepMinIvPercentage": 60.0,
```
We all love pidgey except the weak little shits, they should burn and die. So let's just use the IV to seperate the weak little shits from the bad ass birds that will rain hell down on every enemy. 

**Minimum duplicate**
```json
"KeepMinDuplicatePokemon": 1,
```
I just caught Mew whoohoo... Oh shit mew is a weak little shit and my bot deleted him because it's only a lvl 1... NOOOOOOOO!!!!
Well you're in luck because i thought about everything today. We kan keep a minimum duplicate of every pokemon. Even if he is below our cp and iv parameter

**Moves**
```json
"Moves": [],
```
Bruno Mars has them, Michael Jackson has them. But maybe our  pokemon doesn't. And let's be honest what is a magicarp without "splash"?

**Deprecated Moves**
```json
"DeprecatedMoves": [],
```
Your 2500CP 100%IV Garydos Doesn't know hyper beam? Delete the motherfucker (*sorry about the language* :-D)

**IV and CP operator**
```json
"KeepMinOperator": "and",
```
Some of us will choose to sort the pokémons using the CP and the IV, others will probably want to keep pokemon that are above a sertain IV or a sertain CP (Pro's will choose and, just saying)

**Moves Operator**
```json
"MovesOperator": "or",
```
Same as the previous but now with the moves. 

**Overwrite IV**
```json
"OverwriteIV": "true",
```
Like i said before the pro's use the and operator with IV and CP But we still don't wanna miss that 100% IV caterpie. If you set this to true you can set a value that will keep a pokemon no matter what CP or lvl or moves

**Overwrite IV value**
```json
"OverwriteIVValue": 95.0
```
The fucking overwrite value 

## Something else

Everyone thank you for reading this.

If you like this idea give it a thumbs up, a smiley face or a heart. (or all three). 

Or maybe you have an idea of your own. Reply to this message.

Or maybe you didn't like it at all. Well go jump of a ... *stay calm, stay calm*. Well that's your honest opinion. Why don't you like it.

**Thank you** for all the real MVP's (the coders that make magic happen with a keyboard)

**Comment by carminaburana123** [comment]
Any pro Github user that knows how i should add labels?

**Comment by Bay101** [comment]
you cant

**Comment by zanhehe** [comment]
Where can i find this config.json? Cant find it in the folder. Thanks

**Comment by zanhehe** [comment]
Nvm i found it

**Comment by carminaburana123** [comment]
@zanhehe Gonna answer for everyone else who needs to find the config file:
    ...\Catchem\Profiles\<YourProfile>\config\config.json

**Comment by Lunat1q** [comment]
Good request and idea, may be I'll do it during transfer rewrite

**Comment by goiabs** [comment]
It would be very nice! But you could do an interface to it.

**Comment by xafelld** [comment]
From Above:  "Ok the minimum lvl is indeed useful, but the CP and IV are way more important than the lvl. So maybe we don't wanna use the lvl option. (you can also set the KeepMinLvl to 0)_"

My Thoughts:
CP values/possible ranges vary so much between different Pokemon AND evolution stages. I would argue that Pokemon Level & IV are the most useful raw data points for deciding which ones to keep. 

The max level Pokemon caught in the wild is 30. So when I get to level 30 I want to keep anything above level 26 with %80 + IV. I won't waste dust on anything starting under level 26.. the CP will sort itself out and is basically irrelevant to the calculation because high level & IV will = great CP for that Pokemon...

Move set is arguably more important than IV so the move set filter is great but I personally just wait until I have a good collection of a certain type that is Level 26+ and %80+ IV, then start powering up the ones with good move sets.

**Comment by carminaburana123** [comment]
Exactly why all of the parameters need to be in there. Some will prefer to train a lvl 9 100%IV pokemon, others will rather choose for a higher lvl

**Comment by goiabs** [comment]
I need it too much!!!!

**Comment by 1000octane** [comment]
My pokemons are not transferred as set. I have a lot of pokemons twice, but set in the main page that i want to keep at least 1. Keep min CP is 1800 and IV is 95% but for example I have two Butterfree with CP/IV 52/215 and 49/330. The bot says that I have to many pokemons???????

**Comment by 1000octane** [comment]
Hi carminaburana123,

I would like to combine the moveset with the IV or/and the CP.
E.g. a I would like to have a Dragonite with moveset "Dragon Breath/Hyper Beam" and one with moveset "Dragon Breath/Dragon Claw".
I set keep Dratini to min 3 and CP to 700 and IV to 90% and prefer IV over CP.
Maybe I have now 3 a 88% "Dragon Breath/Hyper Beam" and find 3 "Dragon Breath/Dragon Claw" so my best Hyper Beam will be lost :-(

I would like to say how many of each move set combination I would like to collect. So my Hyper Beam wouldn't get lost.

But its a great Idea.

I wish I could configure this in a spreadsheet where all combinations are listed and I can set how many of each combination I would like to collect and min IV and min CP level. That would be great.

Thanks for all
