### ISSUE TITLE
No usable Pokestops found in your area.

### ISSUE THREAD

**Issue by Siedjeey** [Lunat1q/Catchem-PoGo#635]
Hi after changing the Max distance setting the bot now seems stuck and unable to find any viable Pokestops... I tried to change it back to the original setting which was 5000 but it doesn't help...
Anyone know how to help me?

**Comment by Siedjeey** [comment]
I have this issue now with EVERY newly created bot... Any fix?

**Comment by tsalcazar** [comment]
Just started receiving this error on all my bots.  New and old.

**Comment by Koromaru1989** [comment]
I have the Same Issue here was working yesterday same thing this mornaning was working and since 14H eastern time cant find a single pokestop even thought there is (Any help plz) I tried the older 1.4.5 and the new 1.4.6 same issue

**Comment by Koromaru1989** [comment]
Working back Here's what I did hope this will help :) I reseted all my internet by hard resset which with my compagnie change Ip adress as well and did restart my computer also. Then working :) hope it helps

**Comment by SelfRighteous69** [comment]
> Just started receiving this error on all my bots. New and old.

Edit: Nevermind. I changed proxy and hey worked again.


Change proxy? What do you mean by that exactly

**Comment by SelfRighteous69** [comment]
_tsalcazar_

> Just started receiving this error on all my bots. New and old.

Edit: Nevermind. I changed proxy and hey worked again.

Changed proxy? What exactly do you mean by that? And did it also work on bot profiles that you had saved prior to changing the proxy?

**Comment by tsalcazar** [comment]
I use a proxy server to change my ip. And they all worked after I changed it

**Comment by SelfRighteous69** [comment]
_tsalcazar_
> I use a proxy server to change my ip. And they all worked after I changed it

I seem to be having issues with creating/joining one. I've never used a proxy before, no clue how this stuff works. Could you explain it to me? Rn I keep deleting all my bots, then rebooting my pc and adding my bots, plus all my desired settings over and over because it keeps messing up on the pokestops (too small)

**Comment by Siedjeey** [comment]
The solution for me is pretty simple, I just check the Discovery Pathing again. My issue with the pokestops is due to the fact I was messing around with the Distance setting and it sometimes seems to mess up the bot but if I put the Discovery Pathing on again, it is fixed.

**Comment by Lunat1q** [comment]
It's up ban
