### ISSUE TITLE
[ TelegramBot Not Notify Catched Pokemons 1.4.6.5 ]

### ISSUE THREAD

**Issue by maknado** [Lunat1q/Catchem-PoGo#636]
Please help! I wanna see catched pokemons on my telegram!

Telegrambot not sending notify for catched pokemons.
I included all pokemons and it not work for me!

**Comment by maknado** [comment]
My version is v1.4.6.1

**Comment by Lunat1q** [comment]
U forgot to set an owner and send /start

**Comment by maknado** [comment]
Yep... I have set te owner, but o /start /stop solved by cp..
I testing anymore form listed pokemons
