### ISSUE TITLE
[Feature Request]  Randomize Delay(s) on Timer ... not startup.

### ISSUE THREAD

**Issue by redbone75** [Lunat1q/Catchem-PoGo#639]
While running, a randomize delay(s) based on a timer instead of startup.  This would always keep settings influx and not static... which should be "more human".  Make sense?

**Comment by redbone75** [comment]
... like auto-randomize every minute.  That'd be much harder to monitor for if that's one thing that might be monitored/detected.  A fixed number stuff like delay between player actions would probably be detectable given enough samples.  The same applies to each one of the delays.

so,.,, auto-randomize and save commit could really be a good thing?  Thoughts?

**Comment by kaktusisko** [comment]
+/- 1 randomize to almost all values.
It will help a lot in anonymity.

**Comment by kaktusisko** [comment]
I know that I can to do a batch creation.
But it would be great, if we could import the configuration from txt file to all accounts.
It can save a lot of time .

It can be spined like {1option|2option|3option|...}, so you can do randomization with running single file, for example once a day.

**Comment by Lunat1q** [comment]
Bot randomise delays EVERY call, it's inside logo .

**Comment by Lunat1q** [comment]
Logic*
