### ISSUE TITLE
[suggestion] put one step in telegram wiki

### ISSUE THREAD

**Issue by fredimartins** [Lunat1q/Catchem-PoGo#640]
add one step explain how to get the user to put in owner field.
few people use the telegram in Brazil, so they are not familiar with this program.
obs .: The user field can be blank if the user to register with a phone number.

**Comment by miguelslemos** [comment]
Mobile version: open left menu -> tap in Settings -> tap in Username -> type your username and save.

**Comment by fredimartins** [comment]
great! put this on wiki to help others =)

**Comment by miguelslemos** [comment]
done
