### ISSUE TITLE
Unknown command!

### ISSUE THREAD

**Issue by fredimartins** [Lunat1q/Catchem-PoGo#641]
![image](https://cloud.githubusercontent.com/assets/8070129/18010874/d04831f2-6b88-11e6-990a-e4ddc8ce70c1.png)
Telegram bot not recognize the command listbots.
Why commands not have slash? With this the app give features.

**Comment by miguelslemos** [comment]
type bots

**Comment by fredimartins** [comment]
this command work great. Start command give wrong list.

**Comment by fredimartins** [comment]
this command work great. Start command give wrong list.
