### ISSUE TITLE
Request; build own route

### ISSUE THREAD

**Issue by Akyoto16** [Lunat1q/Catchem-PoGo#643]
Hello maybe you can add the funktion to create a own route?
The Google Api is good but the route is not perfekt.
When we can create a own route we can walk more 
individually ,legit,and there who we found good pokemons.

(Maybe with force move?)

Have a nice day~

**Comment by erazyon** [comment]
You can create your own GPX file for your own route.
go here for that   https://www.bikemap.net/en/route/create/ 
After take your GPX file, put it in the catchem.exe folder.
Go to config.json, 
"UseGpxPathing": true,
"GpxFile": "putthenameyourfile.GPX"

**Comment by zanhehe** [comment]
Imma try this for sure lol. Thanks @erazyon

**Comment by cartmanez8** [comment]
thanks  erazyon that worked great for me

**Comment by zanhehe** [comment]
Wait where can do i look for config.json? Dont see it anywhere. Lol mb

**Comment by zanhehe** [comment]
Nvm i got it

**Comment by TomWolker** [comment]
worked, thanks erazyon

**Comment by zanhehe** [comment]
Lol mine doesnt move. Need help thanks haha

**Comment by Bay101** [comment]
:smiley: GPX is best option, Will look into making it accessible in the UI

**Comment by zanhehe** [comment]
Where do u guys put the config.json

**Comment by Bartmeu** [comment]
Hey, i made a gpx file in the link that he posted, and placed at the same folder than cathem.exe, and i adjusted my configs to it ( Its on the profiles ), but when i start the bot, it says: Unhandled data in GPX file, attempting to skip.
what i need to do?

**Comment by zanhehe** [comment]
I adjusted mine too. But hes not walking on the same path as i edited on the website. Lol

**Comment by zanhehe** [comment]
I got the same issue too. Unhandled gpx file

**Comment by yibuliusheng** [comment]
can't find catchem.exe folder

**Comment by zanhehe** [comment]
Mines workin. Thanks. Put the .gpx file where the catchem.exe is placed.

**Comment by yibuliusheng** [comment]
![catc](https://cloud.githubusercontent.com/assets/21186027/18027950/94d783cc-6ca3-11e6-9c59-27c463d4b6ab.jpg)

is it here?

**Comment by zanhehe** [comment]
yup thats the place lol. Even if u see the error ' unhandled gpx file etc.' just leave it be and it will start moving onto the directions you edited.
