### ISSUE TITLE
i cant login using PTC

### ISSUE THREAD

**Issue by farisyusry** [Lunat1q/Catchem-PoGo#647]
why i cant login using ptc?

**Comment by impossibrubear** [comment]
Were you able to login earlier? Is this the first time you're trying? What message is appearing? You may be banned if there's no pokemon in your highest CP & IV lists. Or maybe you're mistyping your password or something like that. I tried to login now and it's fully working.

**Comment by Bay101** [comment]
We need more information to try and fix it or find a bug other than  "I cant login using PTC" :smiley:
