### ISSUE TITLE
v1.4.6.5 Telegram bot

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#648]
Hi there,

i created telegram for bots and followed all your instructions. when i message the bot, it does show in catch'em but it is not doing anything. for example, i message "start". it show "Recived Message (start) from @" but it doesn't start the bot. what am i missing? are extra things i need to do?

**Comment by topzaza** [comment]
yes!!

**Comment by lonelies** [comment]
i found the problem in closed issue which there's no owner. but i already set mine. it still end with @.
any guides?

**Comment by Burner6999** [comment]
You need to set a username in telegram, under settings.

**Comment by lonelies** [comment]
thank you!
