### ISSUE TITLE
Niantic Servers unstable..

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#65]
(ERROR) Niantic Servers unstable, throttling API Calls. <---- What does it mean?

**Comment by crisperfx** [comment]
a error still unexplained, some are trying to discover what the exact cause is. But this is no proof that Niantic is scanning your account ;)

**Comment by zootvmexico** [comment]
I get this error [04:22:32] (ERROR) Niantic Servers unstable, throttling API Calls. 
Is a perm ban ?

**Comment by crisperfx** [comment]
@zootvmexico no it is not a perma ban.
