### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by hoffhouse** [Lunat1q/Catchem-PoGo#650]
Hey Guys!

<img width="251" alt="bildschirmfoto 2016-08-26 um 20 38 10" src="https://cloud.githubusercontent.com/assets/21260603/18016499/faf559a4-6bcc-11e6-82b1-7319903498d7.png">

In the right upper corner of my running account is a red "2". Whats does this number mean?

Thanks

**Comment by lonelies** [comment]
go to Map & Console. usually it indicates that there's an error. You can view the error in Map & Console. I usually get the niantic throtling bla bla..

**Comment by Lukaum** [comment]
This happened to me while a had internet problems, but these notifications may be a problem with niantic servers or something like.
