### ISSUE TITLE
AutoUpdate not working

### ISSUE THREAD

**Issue by HernestoSanchez** [Lunat1q/Catchem-PoGo#653]
Hi Dudes!

Catchem is not autoupdating, even if i set TRUE on config file. Is I missing something?

Thanks!

**Comment by KBLOSO** [comment]
same here.

**Comment by Bay101** [comment]
Auto updating isnt fully done yet, it is currently only an update notifier. This should be fixed soon. :smile:

**Comment by cjbougher** [comment]
Yay :)
