### ISSUE TITLE
BUG: stop on max

### ISSUE THREAD

**Issue by madgar29** [Lunat1q/Catchem-PoGo#654]
I have xp set to zero because i dunno a good xp to stop at but i do have 40 pokemon STOP 80 pokemonstops STOP once u added the xp it stopped stopping with these settings????  I understand your adding features but I want the bot to still stop at 40 pokemon and/or 80pokemon per hour when you added the xp somehow it's over writing my limits?

fyi my limits are set to the limit of pokemon go they say if you go over 2000 pokemon or 4000 pokemon stops you are not human within 24 hours.........

**Comment by Lunat1q** [comment]
1000 and 2000 actually, limits should work fine
