### ISSUE TITLE
Cant open SLN file inside the ZIP?

### ISSUE THREAD

**Issue by voidarmour** [Lunat1q/Catchem-PoGo#658]
I downloaded the ZIP file, in which I found the catchem bot. However, I cannot run the file as it is an SLN file, when I tried to convert it to a .exe file it would not work. Sorry if I'm being dumb I'm just not familiar with this sort of stuff.
![14102320_890540577757712_1782647868904244208_n](https://cloud.githubusercontent.com/assets/21270774/18023650/9e9e4c70-6bf3-11e6-93c2-32daf6dc196d.jpg)

**Comment by LionDev514** [comment]
my expels when trying to build me a long list of errors, such as 125 errors

**Comment by Bay101** [comment]
You have downloaded the source code, please download the .7z file from the latest release here: https://github.com/Lunat1q/Catchem-PoGo/releases

**Comment by miguelslemos** [comment]
you downloaded the source code,

this link is program https://github.com/Lunat1q/Catchem-PoGo/releases/download/v1.4.6.5/Catchem_1.4.6.5.7z

**Comment by voidarmour** [comment]
I'm an idiot-.-
Thanks for the help guys!
