### ISSUE TITLE
[Feature Request] Anti softban / Daily Limits

### ISSUE THREAD

**Issue by skzbr** [Lunat1q/Catchem-PoGo#66]
From a post on the pokemongodev subreddit:
Pokestop ban:

Occurs when you search roughly 2k pokestops in a 23 hour timespan.
Pokemon ban:

Occurs when you catch 1k pokemon in a 23 hour timespan.
Are there any included anti-measures (take a long pause/quit when getting close to the limits, for instance) or would it be easy to include?

EDIT: Source: https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

Other things that could be limited daily

EXP per 24 hours (or user defined)
km walked per 24 hours (or user defined)

**Copy from other bot Issue on github forum**

**Comment by wagas** [comment]
i got a question if i play 1hour per day then until 24days = 24hours then i got a 1k+ pokemon i would still be ban?

**Comment by Lunat1q** [comment]
Check roadmap.

**Comment by skzbr** [comment]
Can`t findt it, where is it?
