### ISSUE TITLE
A Likely cause of Soft IP Bans and possible future perma bans

### ISSUE THREAD

**Issue by GhostMidnight** [Lunat1q/Catchem-PoGo#664]
I am fairly sure that when this message occurs "Encounter problem: Lure Pokemon NotInRange" an IP soft ban occurs. (Past few days since server patch)

This may be the cause of many of your IP bans occurring. 
You might check your logs and find this error prior to pokestops disappearing from your session.

I'm curious to know how many of you get this recently after the latest server patch last weekend.
It may be one of the methods Nianitc is flushing out botters. It looks like other bot programs are running into the same. Perhaps if the same account results in this error many times an eventual perma ban for the account may occur.

I tried to look through the code but its likely a return message from the server. 
I'm trying to filter out not catching Missingno, legendary pokes and mews to see if that avoids the error as the actual app does not yet catch those. That would be an easy way for Niantic to catch and send back "Encounter problem: Lure Pokemon NotInRange" and soft ban the ip.

Perhaps an option to not catch lured pokemon may be good if you plan to leave a session running for awhile without check to avoid the bot running short until this is flushed out?

I'd like to see if others find the same.

All in the name of academic research of course ;)

**Comment by felipeuntill** [comment]
Choose a  geolocation who match your IP.

**Comment by GhostMidnight** [comment]
@felipeuntill Thanks for info but, I still encountered this when my geolocation matches the IP I used twice.

I have a direct correlation between error and IP ban. Not a big sample but close to a dozen match up. Haven't had any issues otherwise in pass few days.

Did you get this error when you got IP banned? I'm sure this is just one of many methods which Niantic  is using to spot botters etc..

**Comment by magicdev2** [comment]
Yes when you get that error it means you got IP ban it for a few hours I recommended you use VPN or Proxy.

**Comment by kingjman1994** [comment]
My account is currently lvl 27, running around about 30 miles from where I live and I'm using my own home internet. Basically assumed that I should stay within my state at least, so no more running around central park unless I want to be banned or use a vpn that other people are using to do the same thing. *shrug*
