### ISSUE TITLE
Sudden increase of speed after pokecatch or pokestops

### ISSUE THREAD

**Issue by ruvinz** [Lunat1q/Catchem-PoGo#668]
My min speed is 3 and max = 7. Using Google API, Mapzen API, Discovery pathing, human pathing. The bot usually follows the red path in the UI, but after it finishes catching or spinning pokestops, it'll suddenly increase it's speed, like having a NOS activated during racing LOL. sometimes it's just a short time, but kinda scary when it does this in a very long line, that niantic might use this as reason for flagging the account/softban. Also, during this sudden speed increase, the line it follows becomes crooked and sometimes goes thru buildings. I don't know if it's an issue? But I hope you can have time to look at it. Thank you, Luna and devs! Great bot, btw!

**Comment by Siedjeey** [comment]
I think this is just due to the fact that the visual on the map is catching up to where the bot is in the actual game...

**Comment by ruvinz** [comment]
I hope so. Because it's just scary sometimes when around 10 secs or more after the bot finishes catching a pokemon or after spinning a pokestop, that the bot suddenly zooms forward almost one block from it's location. Fortunately, still have no softban. Is that really the case, Sir Luna? Or other Sir Devs? Thanks!

**Comment by Lunat1q** [comment]
Try to do same action in real game, you will see the same
