### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by CaMoTraX** [Lunat1q/Catchem-PoGo#67]
I bought a private proxy to prevent softbans on multi lvling, but i cant connect to googleaccount, because i need to whitelist a IP adress on my private proxy, wich is not my local one...
Already tried to reverse the TCP connection to get the ip the bot connect's to, but it seems not to be the adress ...

So wich IP-Adress i need to Whitelist on my Proxy to get it to work? ...

Image: http://www2.pic-upload.de/img/31462985/noconnection.png

**Comment by Lunat1q** [comment]
U use address:port? Like 
Myproxy.com:1233?

**Comment by CaMoTraX** [comment]
Yep

**Comment by Lunat1q** [comment]
Will add test proxy button

**Comment by enryIT** [comment]
Make sure you're using HTTP proxies, HTTPS and SOCKS doesn't work.

**Comment by xXDjMikeXx** [comment]
Tested Proxy function. It says proxy works fine. When i try to start the Bot it says i am using 2 auth Factor but i am not using it




[21:47:03] (INFO) Logging in using account Google
[21:47:05] (ERROR) As you have Google Two Factor Auth enabled, you will need to insert an App Specific Password into the auth.json
[21:47:05] (ERROR) Opening Google App-Passwords. Please make a new App Password (use Other as Device)
[21:47:12] (ERROR) Make sure you have entered the right Email & Password.
[21:47:14] (ERROR) System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: message
   bei Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   bei Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 115.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 211.
   bei PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:Zeile 260.
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in D:\Ketchum\Catchem-PoGo\PokemonGoAPI\PokemonGo.RocketAPI\Rpc\Player.cs:Zeile 52.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in D:\Ketchum\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:Zeile 181.
[21:47:14] (ERROR) Current Operation was canceled.

**Comment by xXDjMikeXx** [comment]
okay fixed thiis problem

**Comment by xXDjMikeXx** [comment]
but now it always says (with proxy and without)

[21:53:45] (INFO) Logging in using account Google
[21:53:49] (INFO) Playing as TheUltiGirl2
[21:53:51] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: -33,85945 Lng: 151,212657
[21:54:03] (INFO) [Inventory] Pokemon Stored: 56/250
[21:54:05] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by xXDjMikeXx** [comment]
okay fixed it my Altitude was on 10102

**Comment by Lunat1q** [comment]
proxy test added
