### ISSUE TITLE
Bug Evolution

### ISSUE THREAD

**Issue by blackbakers** [Lunat1q/Catchem-PoGo#675]
Firstable i want to say a big thanks for the devs , your bot is awsome ! :)

My little issue is with the auto evolution , maybe there is no bug and i don't use it like it should be.
I want to evolved only the pokemons that i choose to in the tab "pokemon list setting" and "to evolve" and i checked the box "evolve all pokemon above iv" in the tab "settings" but the problem is in this configuration , all the pokemons above the iv that i fixed evolve regardless of my list "pokemon to evolve" but if  i don't check the box "evolve all pokemon above iv" the bot does not evolve the pokemons...

So my question is this, what can i do to make the bot evolve ONLY the pokemons that i choose in the  "pokemon list setting" ?

Thanks in advance for your response

PS: excuse my broken english i am french

**Comment by Lunat1q** [comment]
It work exactly as u said - it evolve only poke you selected.

**Comment by blackbakers** [comment]
But this is not the case and that's why i came here, all the pokemons evolve and not only the pokes i selected :( for example the bot has evolving a polywag and this poke is not even in my poke list
