### ISSUE TITLE
OSM Map bug with mapzen

### ISSUE THREAD

**Issue by m-dl** [Lunat1q/Catchem-PoGo#676]
Hey guys,

OSM map is not showing anymore after entering mapzen api key (elevation of the park i'm at is 53 meters):

![thrth](https://cloud.githubusercontent.com/assets/6748565/18027335/3d809d62-6c61-11e6-8bb8-d4aee57aef4f.png)

**Comment by ppokego2016** [comment]
same issue.

**Comment by m-dl** [comment]
Maybe just a coincidence with mapzen when I started the bot so ... And changed my IP, same issue.

**Comment by ranrinc** [comment]
Same goes at my end.. something wrong with the map

**Comment by super9172** [comment]
same problem

**Comment by kakarotto** [comment]
yeah. everyone has the same problem

**Comment by SweeTIPi** [comment]
And where is the solution?  ):

**Comment by eSPiYa** [comment]
I changed the provider to Google Map as a temporary solution. [I uploaded a compiled code with this change.](https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242919505)

**Comment by Bay101** [comment]
Fixed, will be in next release :smiley:
