### ISSUE TITLE
Bug Auto evolution

### ISSUE THREAD

**Issue by blackbakers** [Lunat1q/Catchem-PoGo#677]
I have create an issue #675 that was closed a little to fast so i think there was maybe a misunderstanding.

The problem is that all the pokemons evolve and not only the pokes i selected for example the bot has evolving a polywag and this poke is not even in my poke list so maybe there is a bug ?

**Comment by GGGgolovkin** [comment]
Hello

I have exactly the same issue , the pokemons who evolve dosen't match with my pokelist :(

**Comment by Bay101** [comment]
Have you checked the box to only evolve the ones that are in the list? have you checked you settings?

**Comment by GGGgolovkin** [comment]
Where is this options ? Where do you see "only evolve the ones that are in the list" oO
