### ISSUE TITLE
Exception: The remove server returned an error: (403)Forbidden.

### ISSUE THREAD

**Issue by wagas** [Lunat1q/Catchem-PoGo#678]
Please help

**Comment by impossibrubear** [comment]
Same here

http://imgur.com/a/oZCzF

**Comment by Barusco** [comment]
Just like here.
Started this way this morning...

**Comment by maknado** [comment]
I'm also getting this error!

**Comment by marker2k** [comment]
dito

**Comment by yibuliusheng** [comment]
did u all use google dierction api key?

**Comment by impossibrubear** [comment]
@Lunat1q a new issue appeared!

**Comment by impossibrubear** [comment]
@yibuliusheng  I don't even know how to use it!

**Comment by NekoPandiCornio** [comment]
The same problem

**Comment by Barusco** [comment]
@yibuliusheng do you have a solution?

**Comment by Sotorifico** [comment]
@yibuliusheng I have not used any of the API, and I have the same problem. The error is being generated with the map itself.

**Comment by maknado** [comment]
I forced myself, and still farming! But with this error!

**Comment by yibuliusheng** [comment]
zoom out and use force to move as for now.

**Comment by impossibrubear** [comment]
It's working, but the map does not shows up!

**Comment by kasosei** [comment]
same here. 
workaround is to get the lat long from google map and replace

**Comment by DK784** [comment]
same problem, but it`s working.
[http://imgur.com/MDb54jn](url)

**Comment by eduardo2016xd** [comment]
I have this problem too :(

**Comment by teemo63** [comment]
hello I have the same problem that you have an idea of when is the bug will be fixed?

**Comment by gdtesam** [comment]
i'm no expert but i think the application has been banned from getting the tile information from Open Street Map

**Comment by yibuliusheng** [comment]
i hav when after install the latest update

**Comment by impossibrubear** [comment]
@DK784 how did you make that paths? Did you make it at the bikepath website? Does it really works? The bot keeps on track at all times?

**Comment by impossibrubear** [comment]
Does the app runs behind all apps in your pc? I can't see it when i click the taskbar icon, i have to minimize everything because it's behind all the apps.

**Comment by DK784** [comment]
@impossibrubear  yes it works, made ​​by Google API. It maintains all times automatically generating paths .

**Comment by eSPiYa** [comment]
[Found the solution](https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242918181)
