### ISSUE TITLE
When trying to play pokemon with phone all pokemons rans away

### ISSUE THREAD

**Issue by Kazper887** [Lunat1q/Catchem-PoGo#679]
Why it does that i think it is because of the app also sometimes it says failed to detect location why?

**Comment by eduardo2016xd** [comment]
Maps don't work :s

**Comment by Icesenator** [comment]
U'r Softban !

**Comment by Kazper887** [comment]
Its not because of that my maps works

27.8.2016 4.30 ip. "eduardo2016xd" <notifications@github.com> kirjoitti:

**Comment by Kazper887** [comment]
Anyone knows how to unban

27.8.2016 4.32 ip. "Icesenator" <notifications@github.com> kirjoitti:

**Comment by impossibrubear** [comment]
@Kazper887 yes, if you look at youtube there are many vids explaining, but basically, you have to stand in front of ONE pokestop and click it and spin, click it spin, click it spin, until items fall from it. It always worked for me. Sometimes it took me like 15+ times until it normalized. Try it! And be careful to not teleport it always softban or ban!

**Comment by Kazper887** [comment]
Thank you yea i dont ever teleport again😂👍

27.8.2016 4.46 ip. "Imp Elec" <notifications@github.com> kirjoitti:

**Comment by gamelordhacker** [comment]
just remember were the last time you Stop or save the latitude and longitude and altitude  were  you stop and input it manually !! 

If you like to change the Location Remember the Travel Time from that place to the Other place you like to Bot on.. Exp. Im at Lat>10.294514, Long>123.902951  Altitude>10.6 (123°54'10.6"E) Philippines last stop and going to Lat> -24.980904, Long>134.388170 Altitude>17.4 (134°23'17.4"E) Australia   estimating time travel 1day or 12 hours more or less and start the Bot .  

To UnSoftbanned  Just run the Bot it will just Unsoftbanned by doing the PokeStop 10-40 times

**Comment by Kazper887** [comment]
Yes but my bot doesnt find any pokstops and idk why

27.8.2016 5.07 ip. "gamelordhacker" <notifications@github.com> kirjoitti:

**Comment by impossibrubear** [comment]
@Kazper887 Another fix for you: stop the bot, quit the app, get a new IP, start the app again and start the bot. Always works for me. If the startup list shows your pokes, then you're good to go, if not, you've been banned!
