### ISSUE TITLE
Telegram Message for Hatched Eggs Please

### ISSUE THREAD

**Issue by maknado** [Lunat1q/Catchem-PoGo#683]
Please include hatched egg message on bot telegram and more commands, for example:

status 1 egg - to display status of eggs,

**Comment by Bay101** [comment]
will look into it :smiley:

**Comment by maknado** [comment]
Come on ppl!

**Comment by FrancoCJ** [comment]
> will look into it :smiley:

I would also say to include a tab to check on egg status and inventory (see what eggs I have and so on)

**Comment by M4xweLL** [comment]
Please, help me to config telegram in catchem!!

**Comment by Bay101** [comment]
@M4xweLL https://github.com/Lunat1q/Catchem-PoGo/wiki/Telegram-setup

**Comment by Bay101** [comment]
when an egg is hatched you get the new Pokemon message

**Comment by M4xweLL** [comment]
I followed all the steps, everything connects well but if I write something from the cell I can see in the window Catchem, but in my cell responses Catchem not see, I can have misconfigured?
