### ISSUE TITLE
Map error 403

### ISSUE THREAD

**Issue by CarlosSLoureiro** [Lunat1q/Catchem-PoGo#686]
http://prntscr.com/cb2rq4

**Comment by Koromaru1989** [comment]
I have the exact same thing here

**Comment by RadBitt** [comment]
Same issue

**Comment by eSPiYa** [comment]
This is already [fixed](https://github.com/Lunat1q/Catchem-PoGo/issues/680). Please wait for the next binary release. You may download the code and build it yourself or you may use [this temporary fix](https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242919505) while waiting for the official one.

**Comment by whccpl** [comment]
Same issue

**Comment by dansafran** [comment]
same error

**Comment by eduardo2016xd** [comment]
Wait for the next release.

**Comment by eduardoedson** [comment]
When the next release coming out?
