### ISSUE TITLE
Fleshout the logic from the GUI

### ISSUE THREAD

**Issue by eSPiYa** [Lunat1q/Catchem-PoGo#689]
I highly recommended that the logic should be in a separate class library project from the GUI. This will make things a lot easier in a long run. Specially porting this application to other platforms or replacing the GUI to a different one.

I want to contribute in making a web-based implementation of this so it can be deployed on other platforms like Linux. I'm planning to use this by deploying on a Raspberry Pi device so it can run the whole day without worrying about the electric bill.

**Comment by Lunat1q** [comment]
Logic is in Logic.dll, while UI is bot manager to start/stop em.

**Comment by eSPiYa** [comment]
Is everything already inside PoGo.PokeMobBot.Logic?

**Comment by Lunat1q** [comment]
yeah, 99% of logic is there
