### ISSUE TITLE
Map error 403 ?

### ISSUE THREAD

**Issue by dansafran** [Lunat1q/Catchem-PoGo#690]
![capture](https://cloud.githubusercontent.com/assets/14239418/18028298/91838d56-6c7b-11e6-9fd3-2caa6b236b3d.PNG)

**Comment by vinisdl** [comment]
same error

**Comment by bunthay** [comment]
same error

**Comment by hazmad** [comment]
me too

**Comment by hazmad** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242919505

this worked for me

**Comment by eduardo2016xd** [comment]
Wait next release

**Comment by dansafran** [comment]
https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view

**Comment by eSPiYa** [comment]
@This is already [fixed](https://github.com/Lunat1q/Catchem-PoGo/issues/680). Please wait for the next binary release. You may download the code and build it yourself or you may use [this temporary fix](https://github.com/Lunat1q/Catchem-PoGo/issues/680#issuecomment-242919505) while waiting for the official one.

**Comment by cyberfilou** [comment]
Thx, the modification work

**Comment by Geko82** [comment]
me too

**Comment by heliofidalgo** [comment]
Need help !! im using the version 1.4.6.5 and error 403 persist ...
What is the procedure to correct the error ?
