### ISSUE TITLE
Translations can't be used

### ISSUE THREAD

**Issue by Asia81** [Lunat1q/Catchem-PoGo#691]
I see there are some translations, but neither of them can be used.

If in Catchem I change the translation code from en to fr (I want french), and I restart the bot, nothing has changed.
If I delete the english translation file, and rename translation.en.json to translation.fr.json, nothing happen too.

So how can we use translations?

**Comment by justchab042** [comment]
J'ai eu le même soucis que toi j'ai supprimé/réinstallé Catchem et recommencé depuis le début (refaire les config) et depuis ça marche...

**Comment by Lunat1q** [comment]
It's translation for console commands only.
