### ISSUE TITLE
Question About Telegram

### ISSUE THREAD

**Issue by m0s-san** [Lunat1q/Catchem-PoGo#692]
Hi Folks,

i´ve  question... i followed the telegram setup guide. set owner, api-key ect.
the Telegram Console Log is showing that the bot has recived messeges. 
but i´m not getting any infos send back. do i need to do something else?

ps: sorry for my bad english !

**Comment by maknado** [comment]
Please, On your telegram select the your bot and click stop and restart!
This worked for me!

**Comment by m0s-san** [comment]
thanks for your advice! but unfortunately that is not working for me :)
[06:14:58] Recived Message (help) from @
that is all what happens after typing a command. i assume there should be a message like send.
i´ll keep trying a little bit i´m still new to all that stuff :D Have a nice weekend

**Comment by lonelies** [comment]
check "Telegram Bot" in closed issue

**Comment by m0s-san** [comment]
Jesus thanks alot .  I thought i already did... but seems not to be the same as needed !
you made my day :)
