### ISSUE TITLE
USE THIS FIX TO THE ERROR 403 (FIX TO MAPS DON´T WORK)

### ISSUE THREAD

**Issue by eduardo2016xd** [Lunat1q/Catchem-PoGo#694]
Copy, paste and replace the Catchem folder to run the bot with normality. No is an official fix is for the bot work temporarily, neither is mine I found it in a comment ;)

https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view

**Comment by impossibrubear** [comment]
For those, like me, who doesn't feel comfortable using an unofficial solution, the bot still works normally (move to pokestops, catch pokémon, recycle, etc.). 

Use the coordinates to place your bot for the first time and if you don't know where are the pokestops, use this: http://www.pokemongomap.info/

I'll wait for an official correction for this.

**Comment by pedrollira** [comment]
100% here. Tks
