### ISSUE TITLE
How do I use the lucky eggs?

### ISSUE THREAD

**Issue by Uzoot** [Lunat1q/Catchem-PoGo#695]
I want to evolve some specifically selected Pokemons, but would like to use the lucky eggs for double xp. Is there any way to use the eggs?

**Comment by moontillaa** [comment]
Yes, is set by the "Poke list Setting" > "To Evolve". Specifically you **add** or **remove** what kind you want to evolve.

**Comment by impossibrubear** [comment]
Set how many pokemons (minimum) you must have so the bot can use the lucky egg at the "Lucky Egg Min Poke" box, leave the "Evolve all pokemon with enough candy" on. You can set it to 1 and wait til the bot use the egg. When it uses, you can turn off the use lucky egg, just to be sure that the bot will not use your Lucky Eggs with 1 pokemon and spend the 29:30 without earning any XP.
