### ISSUE TITLE
How to translate this program into Chinese?

### ISSUE THREAD

**Issue by tillersing** [Lunat1q/Catchem-PoGo#696]
As there are plenty of Asian using this program, it would be easier to read if there is a translated version. However, I have tried  CXA (ASCII method, but result in garbled), Resource Hacker and ResEdit both can't find out the words. Do someone can tell me the ways to translate. After that I will post to the forum which will benefit many people. Thanks in advance. Sorry for bad English :(

**Comment by Lunat1q** [comment]
You can download sources:) and do what you want, with proper credits ofc
