### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by imbackniantic** [Lunat1q/Catchem-PoGo#698]
What about using a geo location bounds filter insted insted of  

> max travel distance

. We set a SouthWest and a NortEast point and the player can move only inside the square.

Another interesting feature can be t

> he priority IV over PL only if PL_max - PL_IV  is less then X.

 I explain: it's a filter which normally prefer to trasnfer low PL but if there is a pokemn with high IV an PL not to smaller (X)  it will be preserved.

**Thanks for the Fantastic work, you are awesome!**

**Comment by Lunat1q** [comment]
Duplicate
