### ISSUE TITLE
Feature Requests (Downloadable (offline) Map, Incense, Lure, Spawn Mapping)

### ISSUE THREAD

**Issue by GrimmHubber** [Lunat1q/Catchem-PoGo#699]
Love the bot and I hope you guys think these features might make it even better:

Offline Map: Download the map for the city the player is confined to so it doesn't overload a server.

Incense: An option to activate an incense (only one, and command has to be given in the information panel ratter than activated in the settings panel).

Lured Stops: a settings option that forces the bot to stay withing range/ standing-beside an active lured pokestops.

Spawn Mapping: Maybe a new panel where we can ask the bot to memorize the spaw spots of key pokémon, for an example, if dratini is selected as a key pokémon and its seen spawning the bot will save the coordinates os the spot the dratini spawned and will later show on map where (and when, maybe) if the user requests it.

**Comment by Lunat1q** [comment]
I'll enable map caching next release.

**Comment by goiabs** [comment]
Spawn Mapping is the best idea! It would be very useful since the function "snipe" is dangerous.
