### ISSUE TITLE
[Feature Request] Transfer Logic Improvement

### ISSUE THREAD

**Issue by poopfeast42** [Lunat1q/Catchem-PoGo#70]
Currently the bot only keeps either highest cp or highest IV if over the IV threshold. It doesn't check to see if it meets atleast 1 of the requirements and only rigidly xfers based on the transfer priority.

I.E. If I have a 2190 snorlax IV 45 and a 100 snorlax IV 92 
and my Keep Max CP is 2000 and Keep Max IV is 85 w/ prioritize IV over CP enabled
then it will still transfer the 2190 snorlax even if it meets the CP requirement, I assume this is a logic mistake or maybe I am not understanding the way its supposed to work?

**Comment by Lunat1q** [comment]
Will check that, thanks

**Comment by Lunat1q** [comment]
add this pokemon to transfer filter.
