### ISSUE TITLE
Blue screen on Map & Console error 403

### ISSUE THREAD

**Issue by ggUdU** [Lunat1q/Catchem-PoGo#700]
see this error on upgrade! http://imgur.com/a/lteZE

this bug in map no show, Catchem pokemon go mesage erro Exception: the server return a error: (403) , no display open street map server conect

I worked replace to, Yes i replace .exe catchem and now is display map, wtf this bug, https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view&usg=ALkJrhhH5EwEhmRiaVjYgTf0opN4tIsoSw

**Comment by kdokiller** [comment]
Same here

**Comment by iron313** [comment]
wow i was reporting this issue right now

**Comment by pusislayer** [comment]
Same problem here. Was working well about 3 hours ago.

**Comment by pikopike** [comment]
its not the bot its the map provider... you will get new maps with update tomorrow

**Comment by kdokiller** [comment]
until there i found this here on closed issues.

https://github.com/Lunat1q/Catchem-PoGo/issues/694

**Comment by kingkai808** [comment]
just wait for map to update. have to just sit tight for now.

**Comment by pikopike** [comment]
if you want more information join Discord

**Comment by ggUdU** [comment]
Yes i replace .exe catchem and now is display map, wtf this bug, https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view&usg=ALkJrhhH5EwEhmRiaVjYgTf0opN4tIsoSw

**Comment by Brucksp** [comment]
World map option not working

**Comment by tiagolimavip** [comment]
Not working...

**Comment by GrimmHubber** [comment]
One of my bots was confined to a small area so i know exactly where it is. The other one... I'm trying to find the park by analysing the pokestops patterns.
This .exe file was stoped by my anti-virus, so I'm making do and I will wait for the next release.

**Comment by kingkai808** [comment]
Just chill out guys. Dev is working on it and is aware. Wait till he releases it.

**Comment by impossibrubear** [comment]
I'd think twice before installing unofficial archives. The bot is working. Only maps are not showing, but if you have this http://www.pokemongomap.info/ and Google Maps, you should know how to locate yourself.

**Comment by GrimmHubber** [comment]
impossibrubear: that's how I've been goin' round. =)

**Comment by nikogoe** [comment]
Go out and really enjoy Pokémon GO ! :D
