### ISSUE TITLE
LUNAT1Q PLEASE UPTADE BOT (MAPS DON'T WORK)

### ISSUE THREAD

**Issue by eduardo2016xd** [Lunat1q/Catchem-PoGo#702]
Please update bot, maps don't work, only have temporaly fix.

**Comment by iron313** [comment]
replace .exe catchem and now is display map https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view&usg=ALkJrhhH5EwEhmRiaVjYgTf0opN4tIsoSw

**Comment by Neo619** [comment]
link not work

**Comment by tjard13** [comment]
I think this .exe could be a virus !

**Comment by iron313** [comment]
sorry guys, this link will help you... and its not virus, work for me :) https://github.com/Lunat1q/Catchem-PoGo/issues/694

**Comment by Neo619** [comment]
works thanks

**Comment by impossibrubear** [comment]
I'd think twice before installing unofficial archives. The bot is working. Only maps are not showing, but if you have this http://www.pokemongomap.info/ and Google Maps, you should know how to locate yourself.

**Comment by Brucksp** [comment]
Guys this is just a error provider map
The rest is working normal.
Stop complaining and wait until another release.
LUNAT1Q bot is the best.
