### ISSUE TITLE
Do Nothing function

### ISSUE THREAD

**Issue by goiabs** [Lunat1q/Catchem-PoGo#705]
Hello Lunatic.

You could implement the function "Do Nothing". Sometimes i want to login in the bot only to transfer pokemon manually, but the char continues walking and doing actions. It can be a problem because i would be doing actions and the bot too, so it will be a lot of actions bypassing the delays. I do not know if you understood (sorry, i'm brazilian and my english is bad).

**Comment by goiabs** [comment]
For example: i put an eevee to transfer. But the bot was throwing a pokeball. So, my eevee was transfered between the throw and the catch. It´s is not humanly possible. See:

![capturar2](https://cloud.githubusercontent.com/assets/21255689/18030735/785f2b56-6c98-11e6-9b63-118c92fea720.PNG)

**Comment by NicolaIsotta** [comment]
A queue for actions would be useful too

**Comment by windclara** [comment]
that's what i want to.
not to make the role locate my place so that i could start the bot in a short time.

**Comment by alanearl** [comment]
Yes i agree... queue is the best option :dart:
