### ISSUE TITLE
GYM

### ISSUE THREAD

**Issue by flag1** [Lunat1q/Catchem-PoGo#707]
Will you guys, put some gym functions?

**Comment by kaktusisko** [comment]
This is a very difficult decision.
It can destroy the game. 
It can cause the bot popularization and block too.
And we should increase donations by the way.

**Comment by flag1** [comment]
I see that, but atleast you can put an dialog with informations about the gyms, and if someone is using the bot in his city, this person would know where to find this place. And another idea, put markers in map, to save places.

**Comment by kaktusisko** [comment]
Bot sometimes visits pokestops already.
