### ISSUE TITLE
BUG transfer auto pokemon Min Duplicate FAIL for Cp or Iv and Eevees

### ISSUE THREAD

**Issue by ggUdU** [Lunat1q/Catchem-PoGo#708]
Need option NOT TRANSFER if IV = or > (value) exemple 75% , this actual option is bug

yes, you have to transfer Pokemon errors when they are duplicated.

Need option ignore CP and transfer by IV = 80+ is more important.

I did several tests,

Keep duplicate selected min = 4

Keep min iv % = 80

Keep Min Cp = 1000, then 500, then 10

Prioritize IV Over CP - activated

Other options not seleciononei

And it does not work. Especially when Eevee capture or Snorlax

only time kept Eevees was when Keep Min Cp = 10 but also kept several other pokemon with lower IV <80% and varied Cp

but if the Keep option Min Iv = 80%, it can not transfer Eevee with iv 85%

The bot transferring this pokemon that need to maintain, and pokemon that need to transfer it keeps more than 4 duplicates.

The logic of the bot is wrong if it is possible to fix this would be of great help!

**Comment by lonelies** [comment]
Reading this bug report is giving me cancer

**Comment by nikogoe** [comment]
Go out and really enjoy Pokémon GO ! :D

**Comment by talktonetto** [comment]
not selecionei hahahaha , ok br.

**Comment by hugoleosp** [comment]
So confusing, I didn't understand what he really wants
