### ISSUE TITLE
Exception: The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by boomer00oo** [Lunat1q/Catchem-PoGo#709]
The fuck is this?

https://i.gyazo.com/7ffa24f1472da9dc75b7b50662875230.png

**Comment by ivanengler** [comment]
Ban

**Comment by villemil** [comment]
No you are not banned. It is a bug that will be fixed in the next patch

**Comment by R4mulus** [comment]
Yes, having the same issue.  Looking forward to next patch. -  thanks

**Comment by toshiossada** [comment]
Does Already Have some release?
