### ISSUE TITLE
Still having an issue with Transfer

### ISSUE THREAD

**Issue by Pengich** [Lunat1q/Catchem-PoGo#71]
it doesn't read the pokemons correctly I have 250 in my inventory and it only reads 242

**Comment by Lunat1q** [comment]
used sniping?

**Comment by skzbr** [comment]
The same happen to me, and i didn`t snipe on Catchem. Only with other bots.

**Comment by skzbr** [comment]
[08:55:27] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[08:55:28] (INFO) [Inventory] Pokemon Stored: 241/250

**Comment by Pengich** [comment]
No Sniping
