### ISSUE TITLE
Telegram : CATCHEM 1.4.6.5

### ISSUE THREAD

**Issue by csindone** [Lunat1q/Catchem-PoGo#711]
Telegram : CATCHEM 1.4.6.5 is not reporting using telegram.

Auto start Telegram bot - checked
Boot API Key - entered
Owners - entered
Report any above CP (set 0 to disable) - 0
Auto report selected pokemons - checked
All pokemons selected in list

Telegram Started Successfuly with account: confirmed

From Telegram app installed on an iPad I can enter commands and see them in the Telegram : CATCHEM 1.4.6.5 but I don't get any feedback

**Comment by lonelies** [comment]
https://github.com/Lunat1q/Catchem-PoGo/issues/648

**Comment by csindone** [comment]
Thank you, changing the username in Telegram to match the Owners in CATCHEM 1.4.6.5 has allowed me to send commands.

However with settings in the original post I still don't get reports of pokemon being caught.
