### ISSUE TITLE
Please, provide the old version

### ISSUE THREAD

**Issue by arcavoordo** [Lunat1q/Catchem-PoGo#712]
Hi, very good your work! Continue beating as if you are getting very famous with your program! Congratulations my friend!

Too bad this last update left his full program errors, such as:

Map giving error
Few Pokémon to capture
The route that your program does is very short, once he walked around the city, now only walk a maximum of 1 neighborhood.
Every time updated inventory, causing the doll stop walking all the time.

I wonder if you have any way you desponibilizar the old version, the version 1.4.3.0 the way it was before, whether this new update.

Thank Lunat1q, you are the best!****

**Comment by viniciusduzzi** [comment]
When walking I would only set the pokestops my preference or trace the way to go on the map Catchem

Thank Lunat1q.. u are the best

**Comment by Yassnichou** [comment]
I have problems with new versions too, I've been back to 1.4.4.1.7 which is the one working the best for me ! I have the problem with the map too but everything's working, here you go : http://www.filedropper.com/catchemv1441
