### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by brockylim** [Lunat1q/Catchem-PoGo#713]
![untitled](https://cloud.githubusercontent.com/assets/21167012/18031114/17270bda-6d04-11e6-8ac2-a8d9dfe953d9.jpg)
I get this map error when i open catchem today, can you please fix it? thx

**Comment by pokemon666** [comment]
same here... can't use for like 24hrs now...

**Comment by viniciusduzzi** [comment]
:(
