### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by samucamg** [Lunat1q/Catchem-PoGo#714]
I'm goting map error size morning
![maperror](https://cloud.githubusercontent.com/assets/21285687/18031157/d93fe5bc-6ca9-11e6-9367-e486829274db.JPG)

**Comment by dirrwx** [comment]
me too

**Comment by arcavoordo** [comment]
Me too!!

**Comment by awhile** [comment]
我也是

**Comment by yugishinigami** [comment]
Me too!

Help, plz XD

**Comment by miguelslemos** [comment]
will be fixed in next release

**Comment by madafoquer** [comment]
Guys, do a search on issues, you will find that this was posted 543284383687436874364 times. There is an .exe that solve the problem temporarily. If you don't what to download that exe, just wait untill the next update.

**Comment by arcavoordo** [comment]
What is the link to download this exe

What is the procedure to use after downloading it?

**Comment by yugishinigami** [comment]
Copy, paste and replace the Catchem folder to run the bot with normality. No is an official fix is for the bot work temporarily, neither is mine I found it in a comment ;)

https://drive.google.com/file/d/0B41ZnZXuOUNFWFVxNURrV3ZFY1k/view

**Comment by arcavoordo** [comment]
Thank you friend!

**Comment by yugishinigami** [comment]
Tudo nosso
