### ISSUE TITLE
listbots command not working.

### ISSUE THREAD

**Issue by jerryang76** [Lunat1q/Catchem-PoGo#715]
Jerry:
Help
[12:47:46 PM] xxx_bot:
The following commands are avaliable: 
- listbots 
- start [bot Number / all] 
- stop [bot Number / all] 
- status [bot Number] 
- top [bot Number] [cp/iv]
Jerry:
Listbots
[12:47:46 PM] xxx_bot:
Unknown command!

**Comment by Bay101** [comment]
It's just bots now, changed it and forgot to change the help message :smiley:
