### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by KoopaTheTurtle** [Lunat1q/Catchem-PoGo#718]
This is on the latest release v1.4.6.5
I assume just a small fix
![capture](https://cloud.githubusercontent.com/assets/21056276/18031412/7bc8dac6-6d33-11e6-887c-2b6c2807da00.PNG)

**Comment by Brucksp** [comment]
Guys this is just a error provider map
The rest is working normal.
Stop complaining and wait until another release.
LUNAT1Q bot is the best.

**Comment by KoopaTheTurtle** [comment]
@Brucksp calm down i was just notifying Luna about it okay. I wasnt saying "FIX IT RIGHT NOW BLAH BLAH BLAH INSULT" was I. I simply stated thats what the map looked like and what version i was using

**Comment by Brucksp** [comment]
I'm using V1.4.6.5 and work for me
![img_1491](https://cloud.githubusercontent.com/assets/21279754/18031524/6a522716-6d1f-11e6-8dd0-404ffb0256fc.JPG)
![img_1490](https://cloud.githubusercontent.com/assets/21279754/18031525/75c347e2-6d1f-11e6-87c6-1c53c60edc53.JPG)

**Comment by osnoser1** [comment]
Me too @Brucksp, and i have the same error.

**Comment by Snurbsy** [comment]
>@Brucksp ...Guys this is just a error provider map...

Seems to be blocked API-requests by OSM due violating usage policy, i.e. requests per second and caching results and tiles.

Note: Some Users retrieve cached results from proxies, thats all and OSM seems to work for them (until caching by proxy expires)

**Comment by raulken78** [comment]
https://help.openstreetmap.org/questions/29938/in-my-app-problem-downloading-maptile-000-http-response-http11-403-forbidden

**Comment by lukas1989** [comment]
same problem here. I'll try your method later raulken78 and report.if it works
