### ISSUE TITLE
No usable PokeStops

### ISSUE THREAD

**Issue by ommeirelles** [Lunat1q/Catchem-PoGo#719]
(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

I already log in with my Iphone and i was able to Catch pokemons and pokeStops, so i'm not soft baned. Can u explain why this is happening ?

**Comment by Nickdundee** [comment]
IP Ban

**Comment by samucamg** [comment]
Ip Ban.  I have the same problem, and using another ip, I have my service back
how you can see.
![capturar](https://cloud.githubusercontent.com/assets/21285687/18031488/4658289e-6cb9-11e6-98ee-eba660e7852e.JPG)
![capturar2](https://cloud.githubusercontent.com/assets/21285687/18031490/59b31d40-6cb9-11e6-9b79-88c7d0148b10.JPG)

**Comment by alanearl** [comment]
Use 4G-HSPA+ Network.
Restart your modem if required.
