### ISSUE TITLE
Power UP

### ISSUE THREAD

**Issue by JacksonTrue** [Lunat1q/Catchem-PoGo#720]
Нельзя одновременно бустить сразу несколько аккаунтов. Либо я выбираю на 1 аккаунте несколько штук и делаю max power up, или же на другом. Пока на одном аккаунте выполняется задача, на другом окно покемонов становится не кликабельным. 
______________________________________________________________________________________________________

It is impossible to simultaneously boost multiple accounts . Either I choose on 1 account and make a few pieces of max power up, or on the other. While on one account, the task is executed , on the other Pokemon window is not clickable

**Comment by nikogoe** [comment]
IP failure ... live with it - go out and play !! Pokémon GO!
