### ISSUE TITLE
 No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by samucamg** [Lunat1q/Catchem-PoGo#721]
I got this error, any were.
[00:40:10] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
![capturar](https://cloud.githubusercontent.com/assets/21285687/18031466/812295be-6cb8-11e6-803e-5e5320e4e67c.JPG)

**Comment by KoopaTheTurtle** [comment]
apparently (another person posted the same error and got this reply) its an IP ban

**Comment by nikogoe** [comment]
Yep it's an IP ban. Go outside and enjoy what PGO was really made for.

**Comment by kingkai808** [comment]
IP ban

**Comment by Rozjil** [comment]
an IP ban..? Soft or Perma ban then..? @nikogoe

**Comment by talktonetto** [comment]
isnt a ip ban, in altitude, you maybe was seted max less de minimum ,

**Comment by talktonetto** [comment]
if was that , tell here . or delete ur user name and post ur setup print

**Comment by alanearl** [comment]
Use 4G-HSPA+ Network. Then restart your modem or smartphone if it is using 4G.
