### ISSUE TITLE
Can see moves of pokemon

### ISSUE THREAD

**Issue by yivan11** [Lunat1q/Catchem-PoGo#722]
Love the new catchem bot! Too many features to tinker about. But the one feature i think that it should had been in there is the ability to check all of your pokemons' moves (not only the best CP and IV pokemons from console). I just want to know if my high IV pokemon has decent moves so I can keep it. Otherwise (if it has bad moves) im keeping a high IV useless pokemon and since I have the IV filter on, other decent pokemon are getting transfered :/
Anyhow thank you so much for the update! One of the best bots out there

**Comment by nikogoe** [comment]
So just setup your Config for IV - not for CP - or set transfer to FALSE.

**Comment by alanearl** [comment]
Yes you can find it in the logs or just stop the bot and start again... it will list the pokes then you can see in the console their moves... lols
