### ISSUE TITLE
Error: Remote Server is Forbidden.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#723]
Dear Dev Support,

What is this?
![capture1](https://cloud.githubusercontent.com/assets/648116/18031594/7ec1c414-6d19-11e6-90c1-75995de11c72.PNG)

Thanks.

**Comment by KoopaTheTurtle** [comment]
as Buck said "Guys this is just a error provider map
The rest is working normal.
Stop complaining and wait until another release.
LUNAT1Q bot is the best."

apparently some people have this and some done :/ apparently there is an update in a few hours gonna come to fix this. in the mean time use google maps and http://www.pokemongomap.info/ and the co-ords in settings to move around. Other than this the bot still works with catching pokemon and going to pokestops :D

**Comment by alanearl** [comment]
Im just asking man :)
But thanks anyway.. yeah its still working...
Maybe open street experience sudden increase of bandwidth lols.

**Comment by Poincare1** [comment]
I also have this error.  The Catchem bot is, and continues to, work fine except for a map error. It says in blue "We are sorry, but we don't have imagery at this zoom level for this region."  Then right below that in red, "Exception: The remote server returned an error: (403) forbidden."  

Maybe there is some Google Maps API that the user, or developer(?), needs to update?

**Comment by Snurbsy** [comment]
Seems to be blocked API-requests by OSM due violating usage policy, i.e. requests per second and caching results and tiles.
