### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by ericspakauskie** [Lunat1q/Catchem-PoGo#731]
![image](https://cloud.githubusercontent.com/assets/16110743/18033027/1e24f7bc-6d4a-11e6-83ad-6f21d626f5cb.png)

**Comment by WsTs** [comment]
Please use new version, it will solved all your problems.

**Comment by ericspakauskie** [comment]
wow I didn't notice that there was a new update. well thanks!
and thank you for the developers who made this. you are all amazing!
