### ISSUE TITLE
How to keep poke above 1000 CP

### ISSUE THREAD

**Issue by Melessin** [Lunat1q/Catchem-PoGo#735]
How to keep ALL monsters with CP above 1000 and no one but them? I installed to "keep Min CP" = 1000 but bot keeps one from 10 to infinity CP and transfer the same monster with 1000 CP. I want to keep all monsters with CP above 1000

![default](https://cloud.githubusercontent.com/assets/21140629/18033420/8f05e04a-6d2c-11e6-9009-3bee69b9e1a8.jpg)

**Comment by dansafran** [comment]
![capture](https://cloud.githubusercontent.com/assets/14239418/18033462/d40680a2-6d25-11e6-81fb-b6e6e4e5bd71.PNG)

**Comment by Melessin** [comment]
in this case it keeps just one monster of the same type with CP above 1000. I need **ALL** above 1000 CP. In addition it keeps monsters with 10 CP

**Comment by petoe93** [comment]
then just lower your 'keep min IV %' value **or** uncheck "prioritize both IV and CP for transfer"

**Comment by Melessin** [comment]
I tried 'keep min IV %' = 1 and 100. Switched on and off "prioritize both IV and CP for transfer". But it does not transfer Rattata with CP 10
I don't understand why it keeps all these small pokemons
