### ISSUE TITLE
Add a view of pokemon attacks

### ISSUE THREAD

**Issue by Wombidou** [Lunat1q/Catchem-PoGo#736]
Hi,
Can you add an option to show pokemons profiles like attacks ?

Thanks for your great job !

PS : I think the sort by date of capture is inverted, in the game, the top of the list are latest captured pokemons

**Comment by Asia81** [comment]
Same thing for me, a **MOVE1** and **MOVE2** viewer would be perfect _(maybe in the same area as IV, candies... Or in a Pop-Up?)_.
I have some duplicated 95+IV pokemons, and I don't know which to transfer _(depend on attack)_. I prefer a 80 move to a 35, if you see what I mean xD

I need to connect on my phone for view them instead, so an "all-in-one" would be very perfect.

**Comment by imbackniantic** [comment]
it  is already planned in the roadmap
