### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by sapdkeybinder** [Lunat1q/Catchem-PoGo#737]
Hey, What is the Telegram?

**Comment by 4ur3l** [comment]
https://github.com/Lunat1q/Catchem-PoGo/wiki/Telegram-setup

**Comment by sapdkeybinder** [comment]
I've read, but what does it do?

**Comment by 4ur3l** [comment]
If you ask, you did not really read, it can't be more clear in the introduction "The addition of telegram to Catchem allows you to remotely control your bots when you are not at your computer"

**Comment by grinse** [comment]
telegram can tell the status of your bot and which pokemon the bot has catched.

But Im to stupid I think....Telegram works fine, its startet in the bot too and the bot write me the pokemon which it has catched....Another user has the same problem, but closed his Thread. If I typed "listbots" (without "") I get unknown command. I just tried  with / ; - and so on. Can someone plz help me.
TY

**Comment by 4ur3l** [comment]
@grinse, same for me, "listbots" never worked and notifications of pokémon catching only worked on the first Catchem Telegram release

**Comment by grinse** [comment]
@4ur3l look above ;) only **bots** not **listbots**

**Comment by grinse** [comment]
**All Bot commands**

Bots  => list all bots
start 1 => start Bot 1
stop 1 => stop Bot 1
Status 1 => Bot Stopped or running

**Comment by sapdkeybinder** [comment]
commands not working, what commands are working

[03:26:11] Recived Message (/help) from @
[03:26:45] Recived Message (status) from @

**Comment by grinse** [comment]
With v1.4.7.0.7z my commands working fine.

**Comment by sapdkeybinder** [comment]
me too version 1.4.7.0

what for commands? List?

**Comment by grinse** [comment]
Are you not able to read the thread? 

 grinse commented 21 minutes ago

All Bot commands

Bots => list all bots
start 1 => start Bot 1
stop 1 => stop Bot 1
Status 1 => Bot Stopped or running

**Comment by sapdkeybinder** [comment]
Yes is not working ....

**Comment by grinse** [comment]
Youre bot api key is correct and the telegram bot ist on start?

**Comment by sapdkeybinder** [comment]
yes. im Catchem in the Telegram Console i get Recived Messages

**Comment by grinse** [comment]
than have a look to the closed issues. Maybe there is something which can help u.

**Comment by sapdkeybinder** [comment]
is not going to matter

**Comment by agon1982** [comment]
Add your telegram username in bot owner telegram settings 

if u dont know(or not set yet) go to settings on your telegram app and verify/configure a username

after that u can send commands to your bot :P

**Comment by sapdkeybinder** [comment]
is working, thx

**Comment by TankardBR** [comment]
I have same problem someone can help me?
