### ISSUE TITLE
ban prevent

### ISSUE THREAD

**Issue by raulken78** [Lunat1q/Catchem-PoGo#738]
with this ban got LESS % of ban...

1) bot for many time... I think its better ad a max "operation hours at day" in 12h... 8h its better. Add add a random pause after 45-75minutes

2) teletrasport... I think it's easy remember last position and block the trasfer to new position if this require ur speed ad light flash XD

3) dnot switch from bot to cell and viceversa, for this U must write a better bot with info on pokemon, first attach and charge attack etc... egg info etc.... and wait the desire level before switch to cell forever.

**Comment by Mordascar** [comment]
the bot uses your cellphone info, I don't think using the same account on both places is an issue, unless if you do it at the same time, of course.

**Comment by madgar29** [comment]
pokemon go said itself it does not like accounts on same ip 3 is the max more you get banned. So far im not banned yet and i am using pokemon go's official human "limits" 2,000 pokemon catch daily limit 4000 pokestop limit... bot is doing a wonderful job as well so basically its 40 pokemon an hour 80 stops bot stops and stops randomly from an hour to 12 mintues so i never get the max.... im yet o find out if leaving it on 24/7 is harmful so far its not but i understand in future if i have to limit it like say 7 to 5.
