### ISSUE TITLE
[Feature Request] Kill Switch after New Soft Bans

### ISSUE THREAD

**Issue by PassiveModding** [Lunat1q/Catchem-PoGo#74]
AutoStopping (killswitch) after 
X amount of hours
X amount of pokestops spun
X amount of pokemon caught

with randomisation of each value so it would not be able to detect patterns of these either
This would help prevent the new soft bans for max pokestops and pokemon caught

Max pokemon is roughly 1000 in the last 23 hours and Max pokestops is roughly 2000 in the last 23 hours
This would make a good feature for the bot to descrese ban detection and soft bans in general

**Comment by PassiveModding** [comment]
Also one more thing, there is soon going to be a ban wave detection discord that warns users about upcoming and current ban waves
It may be useful to look into implementing a killswitch based on the discord warnings also 
https://discord.gg/3vGuKg5

**Comment by Lunat1q** [comment]
Cause implemented
