### ISSUE TITLE
Telegram dont work anymore

### ISSUE THREAD

**Issue by georgygrunt** [Lunat1q/Catchem-PoGo#740]
In version 1.4.6.1, telegram works fine,  but in version 1.4.7.0, you can start or stop the bot, get the statut or the top but it don't send the caught pokemons anymore.

**Comment by agon1982** [comment]
Me too. I can send commands (start,stop,status e etc) but dont receive caught pokemons

**Comment by miguelslemos** [comment]
i never received notification when you caught pokemons
version: 1.4.6.5
