### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ivanengler** [Lunat1q/Catchem-PoGo#749]
Anyone can teach me how to use the proxy option ?

Ty!

**Comment by Asia81** [comment]
a proxy adress and a proxy port, simple as that

For example:
123.456.789.000
8080

**Comment by hermsicodes** [comment]
You have to check the "Use Proxy" box and simply add your desired proxy. It's strongly reccomended to use a proxy with the same country / city as your bot-spot.

Check those links for free proxys:
https://incloak.com/proxy-list/
http://proxylist.hidemyass.com/

Regards

**Comment by ivanengler** [comment]
@Asia81 @hermsicodes And the Login/Password ?

**Comment by hermsicodes** [comment]
@ivanengler @Asia81 Free proxys usually don't need a passwort or username, simply fill out IP:PORT and leave the rest blank. If you buy Proxies, you will likely get some login credentials.

**Comment by ivanengler** [comment]
@hermsicodes Ty so much!!

**Comment by berreta1987** [comment]
what about http or socks for using catchem?

**Comment by ivanengler** [comment]
All proxy servers that I found and are working says I'm IP Baned. Is that normal ?
