### ISSUE TITLE
[Feature Request] PokeMobBot or Necrobot and Langs

### ISSUE THREAD

**Issue by ColliderTD** [Lunat1q/Catchem-PoGo#75]
Had the chance, you can choose the type of bot?

I know Necrobot (official) is no longer in development, but there are several forks and be good to choose the bot is desired.
Ex.:
https://github.com/NoxxDev/NecroBot

In addition to choose the language of Catchem.

Thank you,

**Comment by Lunat1q** [comment]
Languages added
