### ISSUE TITLE
How to Get Data From My Android

### ISSUE THREAD

**Issue by moJoeKerns** [Lunat1q/Catchem-PoGo#750]
Topic says all, how do i transfer the information of my phone into the bot? I clicked it with my phone connected through USB but nothing happened. Please advise. Thanks!

**Comment by agon1982** [comment]
U have to enable developer settings and install adb drivers to be able to get data from your phone.

google: how to enable android developer settings

Adb universal drivers can be download from: http://adbdriver.com/

**Comment by sapdkeybinder** [comment]
enable usb debugging

**Comment by moJoeKerns** [comment]
Perfect, thanks!
