### ISSUE TITLE
 i got ban or bug? :(

### ISSUE THREAD

**Issue by iron313** [Lunat1q/Catchem-PoGo#751]
my bot was working perfectly, suddenly i got this https://postimg.org/image/ppzpnwnwb/

yes, there are lot of pokestops in this area... all my 3 bots got the same problem in the same time

**Comment by miguelslemos** [comment]
IP ban, restart modem to get a new IP or wait 2 hours

**Comment by kakarotto** [comment]
Do not run more than one at the same time, cuz you're gonna get IP ban

**Comment by iron313** [comment]
i try to reset my modem twice and use proxy(all proxys are failed), but nothing change :( help me guys

**Comment by imbackniantic** [comment]
i can confirm it is an IP ban, turn OFF your router and restart

**Comment by iron313** [comment]
i already try, my ip doesnt change... i turned off for 10 min
