### ISSUE TITLE
 bot is on the water

### ISSUE THREAD

**Issue by manuwar9** [Lunat1q/Catchem-PoGo#753]
bot crosses through the middle of the sea, activated option behave like human in the options, but seems it ignores , solution? , would be good to add , you can see the pokestops baits , also the bot , repeat poj¡keparadas and makes circles in the nearest pokestops , an option not to repeat pokestops , 
You could add the bot stay in a particular place , stop walking and just capture the place , which is no walk? For example, when we know that somewhere out a type of pokemon .I'd be fine, I leave a picture , thanks for your work , I love the bot , it is extraordinary

http://thumbs.subefotos.com/2e4c6540b80e36386308dfad025bb266o.jpg

**Comment by imbackniantic** [comment]
probably your are using the mobbot routing, change in google directions

**Comment by manuwar9** [comment]
I changed the option , I leave a picture , I restarted bot, and keep walking by the water , to go pokestops .

http://thumbs.subefotos.com/b92759bb70a59902df4d1678cf524fa0o.jpg

http://thumbs.subefotos.com/dee0370dd34235baa8ff7621705579eco.jpg

**Comment by imbackniantic** [comment]
you must yous an api key
