### ISSUE TITLE
Since UPDATE I cant see Pokestops

### ISSUE THREAD

**Issue by caxinal** [Lunat1q/Catchem-PoGo#759]
Since UPDATE I cant see Pokestops, any toughts??

thx

**Comment by imbackniantic** [comment]
try to change ip

**Comment by caxinal** [comment]
Yup already changed it

it keeps saying

[18:28:49] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

but i have like 3000 max travel, and i use to keep the bot at his coordinates.

but since update, is getting this message

**Comment by jusimperfectguy** [comment]
you got ip banned .. wait for 20 mins or more ~and try again
