### ISSUE TITLE
Stop the bot player on the MAP, but not the "whole bot" + Some Features not working ?

### ISSUE THREAD

**Issue by Asia81** [Lunat1q/Catchem-PoGo#761]
Hi, let me explain.

I have a lot of pokemon to evolve _(XP spamming, with my luck egg)_, but evolve a pokemon take a certain time _(at least 10s to 15s per pokemon)_ when the player is not doing anything else.
If he do, the script say "Player busy, try later" and I lose a precious time for my egg.

But this is the problem, I want stop the player on the MAP _(Not walking, not catching, no pokestop, NOTHING AT ALL)_. Just stay where you are, and don't move at all.

But If I set catch pokemon to uncheck, and max pokestop on 1/hr, he still catching pokemon, and snipping pokestop, as you can see here ->
http://image.noelshack.com/fichiers/2016/34/1472404809-catchem.png

And idk what to set to stop him from walking.

Any ideas ?

**Comment by sapdkeybinder** [comment]
you have saved the settings?

**Comment by Asia81** [comment]
of course, even restarted catchem + pc

**Comment by Asia81** [comment]
@Lunat1q Instead close without any response... Maybe you could also answer to the problem i'm sending you about settings not used, like not catch?
