### ISSUE TITLE
Evee doesn't evolve

### ISSUE THREAD

**Issue by cercado** [Lunat1q/Catchem-PoGo#764]
The bot transfers evees but don't evolve them.
I programmed it to keep at least 1 pokemon of each and to keep every pokemon that can evolve, but it is transfering every evee but one, while I have 500+ candys.
Please make evees evolve! I could have 20 evolutions already :)

**Comment by Asia81** [comment]
Well, I evolved at least some 90IV+ eevee today, it worked fine
http://image.noelshack.com/fichiers/2016/34/1472407953-test.png

**Comment by exeleo** [comment]
See this
http://image.prntscr.com/image/919e3524cf8b4dea986b24a92f6a310e.png
