### ISSUE TITLE
Different command about listbots and bots

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#767]
Did i or everyone just notice that in Telegram show that to use list all bots can use "listbots" command which is the real command was only "bots" which is determine at [Link](https://github.com/Lunat1q/Catchem-PoGo/wiki/Telegram-setup) ?..?

**Comment by Cryptologism** [comment]
Did i or everyone just notice that in Telegram show that to use list all bots can use "listbots" command which is the real command was only "bots" ?..?

**Comment by sapdkeybinder** [comment]
yes command ist bots  and help says listbots is not working, bots id working use this
