### ISSUE TITLE
Not to Catch - not working

### ISSUE THREAD

**Issue by xsoft** [Lunat1q/Catchem-PoGo#77]
Hi,
there is no way to disable pokemon catching (and eg. go just with pokestops).
Ive tried:
- add all pokemons to Not to Catch (config, gui, restarts, .. still Ive got those which are banned).
- decrease Pokeballs/Pokemon to 0 (no effect)
- decrease Amount of Pokeballs to keep to 0 or 1 (no effect)

Simple check button "do not catch" will be great.

**Comment by conmicon** [comment]
did you check the box say "use pokemon to not catch filter"?

**Comment by xsoft** [comment]
My bad. I though I check that button already.
*close*

**Comment by Daredevil4** [comment]
Hi Lunat1q,

I have the same problem, and the button "use pokemon to not catch filter" don't exist.
the version is V1.5.3.0

tks"
