### ISSUE TITLE
Bot Stop due to max reach limit

### ISSUE THREAD

**Issue by ggebler** [Lunat1q/Catchem-PoGo#770]
Why does the bot stops longer than 60 minutos when reach one of those limits? This limit isn`t hourly?
For now, my bot has been stopped for 229 minutes. Is this normal? There is a calculated extimed time behind the scenes I do not know? Thanks.

**Comment by baklaforever** [comment]
set
max catch per hour to 900
max pokestops per hour 900
max xp per hour 1000000
max stardust per hour 1000000

**Comment by madgar29** [comment]
those settings are way to fucking high.... pokemon go officials stated 2000 pokemon and 4000 pokestops every 24 hours is max for any HUMAN PLAYER getting more you are under suspesion......

now divid 2000/24 thats 40 her hour and 80 stops per hour.... do that settings and bot pauses for 10-50mintues then goes again these are legit safe settings....

**Comment by ggebler** [comment]
This is the point... The bot is pausing at least 200 min.. 200/60 = 3.3 hours... Once it has notice me It`ll be paused for 600 minutes... O.o
This is why I`m asking... Is this normal? This stopping time...

**Comment by Lunat1q** [comment]
It is normal.
Cause bot doesn't check rates untill first hour is ended.
