### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by KoopaTheTurtle** [Lunat1q/Catchem-PoGo#771]
1) Under the Pokemon in the info tab there is ev tf and blank. What do these mean?
2) In a locked Issue there was a thing about Discord... Link to it?

3) Thank you so much Luna for fixing the maps quickly <3

**Comment by Bay101** [comment]
2) https://discord.gg/pPwxX8Q
1) they are tags corrisponding to the lists on the pokemon lists page
