### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DavePoke** [Lunat1q/Catchem-PoGo#773]
Hello! I'm using the last update 1.4.8.0, the bot crash when I check some options (transfer duplicate poke, keep poke that can evolve, etc.. ) in "bot info"..

**Comment by lelouchvibrittania3** [comment]
same here

**Comment by pdkellerman** [comment]
same here

**Comment by malcolm89** [comment]
The Same. 1.4.7 worked Wonderful, 1.4.8 Crash. THX for your job

**Comment by Lunossm** [comment]
I'm in version 1.4.8.0 , the crash happens mainly in the transfer settings. Thank you for your work.

**Comment by CelloDE** [comment]
Same

**Comment by Cryptologism** [comment]
same here... too muchin almost tick box in this new update... firstly i thougt it was my mistake....

**Comment by Asia81** [comment]
same when i check evolve all above iv

**Comment by ExequielGC** [comment]
crash when i create route
