### ISSUE TITLE
Bug Poke List Settins - Not To Catch

### ISSUE THREAD

**Issue by raselan** [Lunat1q/Catchem-PoGo#777]
In the tab " Poke List settins " I was in the "Not To Catch " option and added the Pokemons , gave a save , but he still catching those selected Pokemons

**Comment by eloxxx** [comment]
save your selections, close the bot and restart it, it should be fine.

some changes are approved only when you re-open the bot.

**Comment by Lunat1q** [comment]
There is option to USE that list.
