### ISSUE TITLE
Possible to transfer the all account credential / save telegram credential in old version into new version

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#778]
Is there any ways to transfer or maybe auto update which is can save the credential from old version into new version... Cuz i got tone id to farm and when got new version i need to start to make it one by one again including telegram credential... Thx Sir Lunati1q..
**I will try to donate to you after got my this month salary**
It was really hard work sir... Thx you again...

**Comment by sygul** [comment]
I have nothing to do with project, so take my advise with care.  I extract the update to a different directory and simply copied the Profiles subdirectory from the original version to the new version (the profile directory doesn't exist on a fresh extraction).  It's possible the content may change between releases so it may not always work. All I can say is it work for me from 1.4.6.1 to 1.4.8.1 (so far !). if not happy just delete the new install and re-extract and manually add profiles again. 

Hope this helps.

**Comment by petoe93** [comment]
i did the same as sygul, since 1.4.5 to 1.4.6 to 1.4.7
safest way is to create a empty new profile and compare the config files from the different releases if there is any change to it.  if not, you can copy&paste the whole folder like sygul said, otherwise you've got to create a new profile :)

**Comment by Cryptologism** [comment]
ooo so what do you guys mean was extract the new version into new folder and directory than copy some file which is stay in old directory into new directory...??
Ermmm nice way guys.. never think of it... Thx for the infromation guys... 
But still hope that Mods can make this like the title say... ^_^

**Comment by izon13** [comment]
just compare your settings... Better... You don't want the bot to accidentally transfer all your pokemon because the coding or settings changes.. I have no idea on programming though..
