### ISSUE TITLE
v1.4.8.0 - Attempting to toggle any radio box in settings crashes application

### ISSUE THREAD

**Issue by brendoncwright** [Lunat1q/Catchem-PoGo#779]
Just updated to 1.4.8.0 from 1.4.7.0 and discovered whern attempting to set it up that attempting to check or uncheck any radio button in the settings crashes the application. Running in Windows 10.

**Comment by Cryptologism** [comment]
Yeah most of the tick box button were headed to make this version of bot crash.. wait for Sir Lunatiq to update it.. ^_^

**Comment by Akyoto16** [comment]
Same issue by me wait for fix soon :)

**Comment by jemfox** [comment]
same here, it crashes when I tick any check boxes

**Comment by pokemolosse** [comment]
when I want to change the values ​ application closes

**Comment by mirdhan123** [comment]
you can change it manually by edit file config.json

**Comment by animekk** [comment]
Join the Discord live chat for Catcher
https://discord.gg/6z5AMX5
