### ISSUE TITLE
Prevent Ban Catche flee

### ISSUE THREAD

**Issue by felipetmartini** [Lunat1q/Catchem-PoGo#78]
https://github.com/NoxxDev/NecroBot/commit/b3cff60264f379ac9137f39711973e434d4458c7 nice feature to prevent catch flee ban plz add

**Comment by conmicon** [comment]
what is the max catch flee rate? 40/ hr? i caught more than 200/hr and havent gotten it.

**Comment by felipetmartini** [comment]
dont know yet some guy talk about 2k by day other in 500 but is better make this configurable to test and to who want prevent.

**Comment by Lunat1q** [comment]
Done
