### ISSUE TITLE
Tranfer

### ISSUE THREAD

**Issue by talarmin29** [Lunat1q/Catchem-PoGo#784]
My pokemon do not transfer
My config is not good ?
<img width="567" alt="2016-08-28 1" src="https://cloud.githubusercontent.com/assets/21173205/18036939/4536389c-6d78-11e6-9d74-da3734cf00db.png">

**Comment by tryndamerewu** [comment]
put this 2 options on 
prioritize both lv and cp for transfer
prioritize lv over cp

**Comment by talarmin29** [comment]
software crash when I click on
