### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by kingkai808** [Lunat1q/Catchem-PoGo#785]
Getting lots of force closes on random errors like making routes, saving a route then making another and force close. 
after this happened if i try to add a new bot and edit settings i get a force close

**Comment by TomWolker** [comment]
The same with me : X

**Comment by kingkai808** [comment]
found out how to get around this for now.
make a route. save it. and exit the application.
restart it and then you're good. seems like a save script error with saving it and continuing to do other things.
