### ISSUE TITLE
[00:09:26] (ERROR) (Error Attempt #4) | Pidgeotto, Lvl: 26,5 | 

### ISSUE THREAD

**Issue by xPokemasterx** [Lunat1q/Catchem-PoGo#789]
Did anyone also got always Errors on 1.4.8 by catching Pokemons? 

[00:09:26] (ERROR) (Error Attempt #4) | Pidgeotto, Lvl: 26,5 | CP: (798/909) | IV: 39,84% | Type: Lure | Chance: 14,68% | Dist: 39,84m | Used: PokeBall (1 left) | XP: 0 |  

Thats written in Red text...

what does it mean?

**Comment by eloxxx** [comment]
I had that 2 days ago, so I stoped the bot all the night, and the folowing day everything was fine, cant help you more on that, but not a big deal

**Comment by latenikrsk** [comment]
same problem. i think this error happens when pokemon is too far away, but bot is trying to catch it whatever

**Comment by Lunat1q** [comment]
Wrong catch settings.
