### ISSUE TITLE
Get data from your android device

### ISSUE THREAD

**Issue by theman480** [Lunat1q/Catchem-PoGo#79]
So i connect my Zenfone 2 with usb ( i have adb configured and usb debug) But when i click "get data from your android device" i get nothing. Can anyone help me to solve that?

**Comment by Lunat1q** [comment]
Look at readme.md

**Comment by theman480** [comment]
@Lunat1q :

`adb server version (32) doesn't match this client (36); killing...* daemon started successfully *`

Then i run "adb devices" and i have the following output:

```
List of devices attached
adb server is out of date.  killing...
* daemon started successfully *
f9azb6009622    device
emulator-5554   device
```
