### ISSUE TITLE
route creator error

### ISSUE THREAD

**Issue by iron313** [Lunat1q/Catchem-PoGo#790]
API KEY ERROR

"You have to enter Google Direction API or mapzen to any of your bots, before creating a route"

some one can help me? i dont know what to do

**Comment by ommeirelles** [comment]
https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen -- mapzen
https://github.com/Lunat1q/Catchem-PoGo/wiki/Google-Directions-API -- google direction

**Comment by jemfox** [comment]
already have the key but still receiving the error "You have to enter Google Direction API or mapzen to any of your bots, before creating a route"

**Comment by iron313** [comment]
tahank you, work for me! i used mapzen

**Comment by yalept** [comment]
what is the best one?

**Comment by alanearl** [comment]
MobBots is still the best routing.
Mapzen is use for altitude only.

**Comment by Lunat1q** [comment]
Mapzen Valhalla is THE SAME as MobBot
