### ISSUE TITLE
Exception: Remote server returned an error. (403) forbidden

### ISSUE THREAD

**Issue by redmarverick** [Lunat1q/Catchem-PoGo#792]
how do i solve this exception?

![image](https://cloud.githubusercontent.com/assets/16127046/18037433/3f858f4c-6d5a-11e6-8af2-bf2067d140da.png)

**Comment by WsTs** [comment]
Use the latest version

**Comment by redmarverick** [comment]
the error persists, i'm using V1.4.4.1, isn't it the latest?

**Comment by Cryptologism** [comment]
Nope... The latest i think qas 1.4.4.7 or 1.4.4.8... Correct me if im wrong...
Yours was using an  old version which is have problem with mapping api... See this link.. 

https://github.com/Lunat1q/Catchem-PoGo/releases
