### ISSUE TITLE
1.4.8 crashes every time I try to change a setting like number of pokeballs to keep

### ISSUE THREAD

**Issue by redbone75** [Lunat1q/Catchem-PoGo#793]
1.4.8 crashes every time I try to change a setting like number of pokeballs to keep

**Comment by Sagitarius13** [comment]
Have the same problem

**Comment by Uzoot** [comment]
I think that is reversed with potions or revives. kkkkkkkkkkkkkk

**Comment by Sagitarius13** [comment]
:P

**Comment by redbone75** [comment]
sorry... this issue is the same as other people.  I'm closing it to help Lunat1q out.
