### ISSUE TITLE
Crashing constantly

### ISSUE THREAD

**Issue by impossibrubear** [Lunat1q/Catchem-PoGo#794]
Trying to type new values in the boxes and the app crashes. Somebody too?

I've been trying to change the transfer min value and it keeps crashing.

V1.4.8.0

**Comment by Sagitarius13** [comment]
Have the same problem

**Comment by mcmoasn** [comment]
Have the same problem

**Comment by superkomang** [comment]
same problem here. Can't change anything in the poke boxes. It keeps crashes

**Comment by JeanRolszt** [comment]
same problem to

**Comment by lucky4com** [comment]
yeah, same here

**Comment by LupaB** [comment]
Same problem here. I Can't change anything in the setting boxes, always crashes.

**Comment by Cryptologism** [comment]
Ok guys... Lunatic and other mods are working on this error... Please do patiently waiting for this being fixed... Thx you and dont flood with the same question... Theres a ton of same question being asked...

**Comment by saldotman** [comment]
you can also change the value directly to the config.json inside your profile folder\<your bot name>

**Comment by impossibrubear** [comment]
@saldotman What is causing it? Change what value, where, why? I can't follow you up, breh!

**Comment by Spk345** [comment]
New Release available now.
