### ISSUE TITLE
"Mapzen Valhalla API key empty" warning constantly showing

### ISSUE THREAD

**Issue by impossibrubear** [Lunat1q/Catchem-PoGo#795]
Why do i need to use that? How do i acquire an API for that?

**Comment by ANTROAX** [comment]
Like my pops can fill me how much I get this message [ 18:52:11 ] ( ATTENTION ) Mapzen Valhalla API Key is Empty!
![oojoj](https://cloud.githubusercontent.com/assets/20980089/18037761/74e47fc6-6d51-11e6-8752-8ee774df9f73.jpg)

**Comment by alanearl** [comment]
You can get API key from here https://mapzen.com/products/turn-by-turn/
Then set routing to mapzen valhalla then check and select custom route.
Still mobBot is more stable at gaining exp.

**Comment by ANTROAX** [comment]
ok then does not hurt anything , it then appears that msj

**Comment by impossibrubear** [comment]
But it's annoying and i guess he just missed some ; somewhere or something :p
