### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Tauroz** [Lunat1q/Catchem-PoGo#796]
when I disable the "Transfer Duplicate Poke" the program stops working and closes

**Comment by RevGDFreeze** [comment]
I have a crash issue when trying to check or uncheck delay randomizer, maybe related?

**Comment by Cryptologism** [comment]
Yeah almost of the tick box button are problems right now... lunatics and others mod are fixing it asap... Do patiebtly wait for them... Thx you

**Comment by abling** [comment]
crahes when i try to edit settings

**Comment by izon13** [comment]
Same.. Crashes whenever i change setting numbers.. ^^

**Comment by viperball** [comment]
same issue, I cannot do any check box now because when I do that the program will crashes then force close. also all the settings will reset to the previous save.

**Comment by Spk345** [comment]
Update to new Release.
