### ISSUE TITLE
How can I do for my character get stop in the same place?

### ISSUE THREAD

**Issue by PedroPH2** [Lunat1q/Catchem-PoGo#797]
How can I do for my character stop walk and I can make some changes in my Pokemon and then make him walk again?

**Comment by Cryptologism** [comment]
Stop then running again at same place? I dont understand... 
Well for the second questiion just simply stop the bot for a while,edit what you want then start it again... Simply as that...

**Comment by PedroPH2** [comment]
I want to envolve, transfer, rename pokemon manually, while i'm doing this I want my character don't move
