### ISSUE TITLE
no pokestop

### ISSUE THREAD

**Issue by Dalsenof** [Lunat1q/Catchem-PoGo#799]
in my not appearing this pokestops after the last updated

[21:36:59] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by RevGDFreeze** [comment]
IP Ban, wait an hour or so then load bot.

**Comment by Dalsenof** [comment]
ok tks

**Comment by Rozjil** [comment]
@RevGDFreeze hey man just want to ask a question. Does running multiple(5) bots get you banned faster or something like that..? I've been reading stuff like that...

**Comment by alanearl** [comment]
Restart modem... then use 4G-HSPA+ Network.

**Comment by impossibrubear** [comment]
@Dalsenof Don't do these. Just get a new IP from your ISP and you're good to go. But first quit the app completely. After getting the new IP, start it and you're fresh :dancer:
