### ISSUE TITLE
crash!! route creaor

### ISSUE THREAD

**Issue by jingyulee** [Lunat1q/Catchem-PoGo#800]
in the route creator tab.i set the waypoint and follow the setting ,when i build the route.the catchem was crash....

**Comment by TomWolker** [comment]
:/ same here

**Comment by izon13** [comment]
changing settings makes the app crash..

**Comment by chrislim80** [comment]
unzip in to a new folder and copy your old profile to the new folder! Please refer to discord!

**Comment by lendsp** [comment]
same error, i copyed my old profile from previos version to have same device settings.... 
i dont know use api

**Comment by hanjers** [comment]
I cant save my created route by closing and reopen the app.

**Comment by HernestoSanchez** [comment]
I Always download new versions to new folders, and, configure everything from scratch, copying only my device info. Even tough, the moment i check Build Route, the app crash.

**Comment by jingyulee** [comment]
chrislim80 .i copy my old profile to the new folder.but i also have the same error.

**Comment by Lunat1q** [comment]
Fixed, now routes are much stable
