### ISSUE TITLE
[Feature Request] Logging Coordinates of Capture

### ISSUE THREAD

**Issue by Spk345** [Lunat1q/Catchem-PoGo#801]
Is there a way for logs of Capture including the Lat/Long Coordinates, similar to Necrobot? I find that amazingly helpful in plotting spawn points around town. I didn't see another thread asking for anything like this, let me know if I missed it. Thank you!

**Comment by Lunat1q** [comment]
added, that info will be in log file under this marker:
![](http://i.imgur.com/ixtMOUr.png)
