### ISSUE TITLE
Snipe pokemon

### ISSUE THREAD

**Issue by ndasmumet** [Lunat1q/Catchem-PoGo#803]
Catchem didnt support snipe pokemon ?
cuz i see in config have snipe settings.

**Comment by chrislim80** [comment]
please refer to discord channel and snipping have been diable to avoid banned!

**Comment by izon13** [comment]
Sniping will make you ban.. Tried and tested.. And don't try those sniping program because they are phishing accounts.. One of my account got hacked because of it.. They change my account password and email..
