### ISSUE TITLE
error, check / uncheck: Catchem has stopped working

### ISSUE THREAD

**Issue by nghakhoi** [Lunat1q/Catchem-PoGo#806]

**Comment by wagas** [comment]
even when u change Keep min Duplicate.. it has stopped working

**Comment by nghakhoi** [comment]
anywhere, bro :(

**Comment by HernestoSanchez** [comment]
The only way to check uncheck things here is directly in config. :/

**Comment by hanjers** [comment]
its the same thing i experienced

**Comment by maxlehot1234** [comment]
same for me and no news from the devs...

**Comment by Lunat1q** [comment]
It should be fixed now.
