### ISSUE TITLE
Incense and Lucky egg

### ISSUE THREAD

**Issue by CuspMe** [Lunat1q/Catchem-PoGo#809]
can you put an option that you can use lucky egg and incense manually? please :)

![image](https://cloud.githubusercontent.com/assets/21124201/18040055/e7bbacc4-6ddb-11e6-8378-185e518796a5.png)

**Comment by abusivo05** [comment]
please!!

**Comment by yivan11** [comment]
x3

**Comment by kevindevm** [comment]
yes please
