### ISSUE TITLE
Character barely moves due inventory checking

### ISSUE THREAD

**Issue by pitxu** [Lunat1q/Catchem-PoGo#812]
**Just some random details:**
My account is running on a short custom route around a lake. Total distance of a "lap" is less than 1km. On his way, character encounters 5 Pokestops, and the distance between is really, really small. My settings are all randomized, nothing "robot like" or inhuman. _(Ban-safe since aug/3, take this Niantic!)_

**The issue, as title says is**: my bot can't run even on small distances. It walks like 3 steps, stops, check inventory. Check it again, and again... then moves a little bit. Stops... and repeats...

I got a bot-test account running (not at the same time, obviously. I just bot this little guy with some days-delay from my main, with IP changes, etc, etc) on another country, with standart settings. Totally opposite of my main, just for fun. High speed, no waypoints, just going from pokestop to pokestop until it drops _(usually ban after 2 or 3 days, but who cares lol)_. There, I got no inventory issues, he checks only at pokestops, maybe 1 or 2 times random. 

**Question is**: what is wrong? I'm pretty sure it's a silly detail passing by, just can't figure out what it is! 

**Oh, another detail:** On inventory usage, items are set to 300/350! So no problem with item cap!

Help, please! I'm on a 40min. run and my character hasn't reached half of the way!

**Comment by stark93** [comment]
It happens exactly the same to me, i created a route at Central park in New York and the bot constantly stops and checks inventory, is there any way i can fix this?

**Comment by stark93** [comment]
I have noticed something, each time the bot starts inventory checking, the current altitude increases and decreases a lot. I tried using mapzen elevation api but still doesn't solve the problem and the altitude keeps varying too much, this only happens when the custom route is activated.

**Comment by Lunat1q** [comment]
You've set inventory recycle percentage to low level, in that case - bot is trying to recycle smth each turn.

**Comment by stark93** [comment]
It worked, thanks.

**Comment by pitxu** [comment]
Hey, @Lunat1q! 

Changed those settings, worked like a charm! Thank you! :D
