### ISSUE TITLE
[Questions] Is there any way to detect if we were banned by using Telegram cmd?

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#815]
As the title say,is there any way to detect by using telegram to know that if we were softbanned or ip banned cuz i really dont know what actually happen to bot when i was out to somewhere.. Which is for sure not using TeamView of course..
And errrmm, is there any possibility to check inventory just using cmd from Telegram(delete item or use item)?

Tq sir Lunat1q and have a great day ahead... 😊

**Comment by Lunat1q** [comment]
well, may be, in the future, we have telegram commands improvements in our plans
