### ISSUE TITLE
[Features Request] Pokemon Snipe?

### ISSUE THREAD

**Issue by angelo350** [Lunat1q/Catchem-PoGo#816]
Is there a chance that you will support _**pokemon sniping**_?

**Comment by Cryptologism** [comment]
I see some delay button on this superb bot about sniping but not sure if it can be used to sniping or not... Maybe it was a try to ask the mods btw...

**Comment by angelo350** [comment]
It will be a great feature though, for example you can set a delay between snipe, like every 5 minutes the bot will snipe for pokemon that specified on your snipe list :smile:

**Comment by hoffhouse** [comment]
This idea is not really serious. 5 minutes????
Show us how you travel from New York to Sydney in only 5 minutes.
All users, which sniped were banned!

**Comment by Cryptologism** [comment]
Hahahaha
Okay2 it was really dangerous tough... Highly chances to get banned...
