### ISSUE TITLE
[Feature Request] : Multibots settings interface

### ISSUE THREAD

**Issue by Waale** [Lunat1q/Catchem-PoGo#821]
Hi, first thanks for the huge work. The software is awesome and I'm impressed by your ability to improve it so fast.
I'd love something to be added on one of the next releases : it'd be great to have an interface on which you can manage the settings for multiple bots at once. Because when you have a lot of them it is kinda annoying to have to update them all if you just want to change a few settings on all of them.
That'd  be awesome, thank you and keep up the good work :)

**Comment by Cryptologism** [comment]
Ermmm actually i have the same questions too dude... But did you running mutiple bot in one ip? Dont you get ip banned?
And is there any way to do that? Mybe somekind trick or tips to do multiple bot mybe 3-4 is enough at the same time?..?

**Comment by Waale** [comment]
Actually I only run 3-4 bots at the same time to limit the risk. I never got definitively IP banned, but sometimes none of my accounts seem to locate any pokemon/pokestops, but I'm not quite sure it is a temporary IP ban or just the a bot bug or simply Niantic servers being unstable.
I've reset my IP address a few times but it's hard to tell, sometimes it fixed the problem, sometimes it didn't.
But anyway it is really simple to get another IP address, so I think it's worth the risk if you know what you're doing.

**Comment by Cryptologism** [comment]
Ya just change the ip tough...  For right now im just trying to botting 2 acc only... Mybe tonight 3 botting according to your recommendation...  But as you said there were not pokestop or catch flee its mean ip banned.. I get this several time when trying 5 and above....

**Comment by Cryptologism** [comment]
Ip banned maybe temporary for me..
