### ISSUE TITLE
[Questions] Is this normal? And how to understand this?

### ISSUE THREAD

**Issue by Cryptologism** [Lunat1q/Catchem-PoGo#822]
In my telegram,when i type status 5 which is my bot it show like this...

Current Status for SangKuraKura2 Bot #4:
Current bot Run Time: 00:00:07
Level: 19 Exp/h: 9,304.8
Stardust 60224, Farmed: -9151 (1,028,571.4/h)
Poke Caught: 0 (0.0/h)
PokeStops spinned: 0 (0.0/h)

That farmed was negative and it was 1million per hour? What was that mean... And wonder why my other bot level 20,i try to leveling it 1 day exatly start from last night still on lvl 20... It show like i need or mybe have 32mil/h... What was that mean? Can someone explain this? Tq guys..

**Comment by Lunat1q** [comment]
...7 seconds... rly dude?
