### ISSUE TITLE
force move action stopped after resuming the pause.

### ISSUE THREAD

**Issue by rokashou** [Lunat1q/Catchem-PoGo#823]
Here is the situation.

1. Force the actor to move to somewhere else by double-click on the map.
2. the actor pause for a while as it reach the limit of hour-rate.
3. the actor resumed, but it search the path around, not work to the point forced to move.
  but the force to move mark is still on the map.

is there something not work well?

**Comment by Cryptologism** [comment]
I think the actor cannot be moved if it not be paused or stopped... Then after pause or stop was confirmed then you can move it....

**Comment by rokashou** [comment]
The actor can be set force move to somewhere on the map that it can reach by double-click on the map when the bot is running. the path will show on the map if you use the google direction api.

but it stopped trace the path after resuming.

I think that maybe the forced move mark should be clean up when bot get pause, then I will take it as specification: when the bot pause/stop, the force-move action will stop.

**Comment by Wombidou** [comment]
It's the same with RouteCreator, if you reach the limit of hour-rate the bot will be stopped and at the reconnection it will go back to the start of the route

**Comment by rokashou** [comment]
Yes. But should not the force move mark be clean up?
It feels something wrong as there is no "force move done" after "force move started"
and the bot start to search another path even it didn't reach the goal.

**Comment by Lunat1q** [comment]
If u got pause during the force move, u have to do forcemove again after pause is lifted.

**Comment by Lunat1q** [comment]
marker will be removed upon bot stop.
