### ISSUE TITLE
Use of  incense

### ISSUE THREAD

**Issue by yalept** [Lunat1q/Catchem-PoGo#824]
Hey,

Its possible to use  incense? or this will be perhaps in a nex update?

**Comment by Cryptologism** [comment]
Yeah i have this in mind too... Cuz got around 10 incense not used... Hahahahha

**Comment by Spk345** [comment]
Incense and lucky eggs are on the road map of features to be implemented.

**Comment by Spk345** [comment]
Will most likely not be in next update. Update will most likely be bug fixes to correct errors of route creator.
