### ISSUE TITLE
CustomRoute builder export

### ISSUE THREAD

**Issue by necora01** [Lunat1q/Catchem-PoGo#825]
Sorry for my English, How I can export or where's a file for a CustomRoute builder I have done?

**Comment by Spk345** [comment]
The information is stored in the catchem.Json next to application launcher, under Routes.

**Comment by necora01** [comment]
my catchem.json only have:
{
  "$type": "Catchem.Classes.CatchemSettings, Catchem",
  "Routes": [],
  "ProviderEnum": 0
}
no information on my route in the file

**Comment by Spk345** [comment]
Did you make sure you built and saved this route? It is showing my route I made with version 1.4.8.0.

**Comment by necora01** [comment]
if, follow the instructions on the web step by step only thing I did´nt was save settings in the settings tab, it is perhaps what I have missed do.

**Comment by necora01** [comment]
I have already discovered, does not save the route until you leave the program when you close the program saves routes you have configured in catchem.Json , thank you very much
