### ISSUE TITLE
possible bug in custom route

### ISSUE THREAD

**Issue by necora01** [Lunat1q/Catchem-PoGo#826]
possible bug in custom route: when does a lengthy operation such transfer or capture many pokemons in an area, when the process finished does not follow the route, The player come back to the starting point of the route

**Comment by timlai1217** [comment]
hello today, download a new version
crash occurs setting self Landmarks

Is there a solution?

The previous version 1.4.7.0 No change

**Comment by CKWTHN** [comment]
in the release it is mentioned that, it actually has a limit, try to keep waypoints limited, problem is that it uses street routing and this makes a lot of waypoints, maybe it should let it be as the bird flies routing...

**Comment by necora01** [comment]
The problem occurs when there is too much distance between two waypoints, to shorten this distance to another does not pass, thank you very much
