### ISSUE TITLE
Let us see the pokemon's ability

### ISSUE THREAD

**Issue by Aegis110** [Lunat1q/Catchem-PoGo#829]
For top percentage pokemon, I really need to know the pokemon's ability for me to keep or transfer especially after evolve.

**Comment by brocils** [comment]
it should be very nice if you can show the pokemon move when I click on my Pokemon.

**Comment by Gulishausen** [comment]
Yeah, this will be useful.

**Comment by KBLOSO** [comment]
Yes. I did suggest this. Would be great!

**Comment by Lunat1q** [comment]
Will be in next release.
