### ISSUE TITLE
Human pathing problem 

### ISSUE THREAD

**Issue by eloxxx** [Lunat1q/Catchem-PoGo#830]
Hello guys, 

With the older version of catchem the player on the screen was fallowing a red line which was automaticaly generated by catchem, but now I don't have this line, so the player is cutting buildings, roads, and sometimes walking on the water,

How to fix it please guys,

Thanks a lot !

**Comment by tryndamerewu** [comment]
use routing service select google directions our mapzenvalhalla and put in your api key

**Comment by eloxxx** [comment]
thanks mate !, i used mapzen and put an api key and it is working fine !

thanks again

**Comment by Alexitou** [comment]
Hello! I post here because i have the same problem. 

I signed up to Mapzen and got my Vahalla key that i put in the Api key section, but even after that the bot continue to go in straight lines between pokestops.

 I have "Use human pathing" and "Use discovery pathing" enabled too. 

Thank you!
