### ISSUE TITLE
Mapzen the key

### ISSUE THREAD

**Issue by Virusdead49** [Lunat1q/Catchem-PoGo#831]
hello, or do I put the key Mapzen in the file
Can You Make a tutorial

**Comment by tryndamerewu** [comment]
just start the bot  go to setting in left top corner  then loook for  routing service you got 4 options  google mapzenvalhalla openls mobbot use 1 and  scrol down you see api key put in the key

**Comment by Virusdead49** [comment]
like this
![2016-08-29_131150](https://cloud.githubusercontent.com/assets/10480101/18049796/b7d6a612-6dea-11e6-81c4-3d919cb6e125.jpg)

**Comment by tryndamerewu** [comment]
is it working now?

**Comment by Virusdead49** [comment]
it works now
tk

**Comment by tryndamerewu** [comment]
cool have fun

**Comment by eloxxx** [comment]
you put the wrong key, dont put the key starting by "saerch" but put the other one starting by "valhalla"

**Comment by Lunat1q** [comment]
ehm... it should be <b>valhalla-xxxxxxxx</b>
