### ISSUE TITLE
[Feature Request] Add information to the UI

### ISSUE THREAD

**Issue by feedrss81** [Lunat1q/Catchem-PoGo#833]
Thanks and congratulations for the excellent work

Information tab
- add the missing XP to next level (Also on Telegram)
- The number of eggs , the incubator and the remaining distance (Also on Telegram)
- Opportunity to request the coins if there are pokemon in gyms

**Comment by Lunat1q** [comment]
1. added
2. will be someday :) 
3. Not for now.
