### ISSUE TITLE
[Feature] Customized amount on inventory

### ISSUE THREAD

**Issue by CaiqueBrito** [Lunat1q/Catchem-PoGo#834]
Hi _Lunat1q_, Wonderful work, as far the best BOT of Pokémon GO,

Could be a good idea if you customize each item as you like, with the rule of maximum inventory size, ex:
```
Ultra Balls: 100
Great Balls: 50
Pokeballs: 20
Hyper Potion: 40
...
Total 340/350.
```

The BOT sometimes recycle Great balls and keep a lot of simple Pokeballs.
If this feature already exists disregard this "issue", but please tell me how to do it, i looked on start guide and i does not found a way to do that.

Kind regards.

**Comment by Lunat1q** [comment]
can't be ![](http://i.imgur.com/sN44cmP.png)
Bot saving best pokeballs he can.
