### ISSUE TITLE
Feature request threads closed- Incense and lucky eggs

### ISSUE THREAD

**Issue by sukarito** [Lunat1q/Catchem-PoGo#837]
Why are the threads about lucky eggs and incense closed? Does it mean that this feature are incoming or does it mean that you don´t put them in the game?
![incense1](https://cloud.githubusercontent.com/assets/21292367/18051155/0581399c-6df3-11e6-877e-dfae64f5d08e.PNG)
![incense2](https://cloud.githubusercontent.com/assets/21292367/18051157/0582e24c-6df3-11e6-923c-89ce1ba84573.PNG)

**Comment by Lunat1q** [comment]
It's DUPLICATE, at first, read #614 before posting smth.
