### ISSUE TITLE
Custom Route catch pokemon & use pokestops..?

### ISSUE THREAD

**Issue by Rozjil** [Lunat1q/Catchem-PoGo#838]
#356 When following a Custom Route does the character catch Pokemon and use Pokestops..? Just wanted to know, so now I can create a route from my home to the city... and another question, can you use 1 API Key for different accounts..? and also my poke catch chance are all 100%... are some of my settings wrong or is it because i just started and these are easy catches..?

**Comment by Lunat1q** [comment]
yes. he does.
