### ISSUE TITLE
[Feature request]Telegram add geolink

### ISSUE THREAD

**Issue by Compufreek** [Lunat1q/Catchem-PoGo#841]
Hello!
I use this great bot as a Radar for the area i live in. And the telegram feature is amazing, but the problem is that it does not send the location of said pokemon. Could this be aded so that the information would contain a google maps link at the end with long/lat of the pokemon(if not possible then bot location would be more than enough). 
Examp:
http://www.google.com/maps/place/lat,lng
That way when you recive meassage of the nearby pokemon you just click the link and you can go find him with your phone.

**Comment by Lunat1q** [comment]
sorry, that can cause some mess into bot logic
