### ISSUE TITLE
[Question] What is the number in the top right corner of the bot box? 

### ISSUE THREAD

**Issue by TerrificPoet** [Lunat1q/Catchem-PoGo#843]
![image](https://cloud.githubusercontent.com/assets/21310451/18051920/ca184b3e-6df7-11e6-87c7-5016ef1144ce.png)

Here is the box i'm talking about.

Also, if i were to use the technique to gain max xp where u evolve lots and lots of pidgey while using an egg, for that i would only have to have : 
- Evolve all pokemon with enough candy (in settings)
- and only pidgey the pokemon evolve list located in the "poke list settings" 

or should i use something else

big thanks to the creater of the bot btw =)

**Comment by Lunat1q** [comment]
errors.

**Comment by TerrificPoet** [comment]
what type of errors? should i try to do anything to bring the number down ? the more errors = the more likely that i'll get ban ?
