### ISSUE TITLE
Telegram constantly repeats messages

### ISSUE THREAD

**Issue by vallaha** [Lunat1q/Catchem-PoGo#847]
Hı,

Telegram Api is not working properly. When I send a message like "help", "top 10", "bots" or "status" the app will not reply it. But when I send message like "reportabovecp 1500" app changes the "Report any above CP" value. 

To test it I send "reportabovecp 1500", and then send "reportabovecp 1750" and again "reportabovecp 1500" now it changes "Report any above CP" value to 1500 then 1750 and 1500 again. 
![telegram](https://cloud.githubusercontent.com/assets/21308547/18053351/9761e366-6e07-11e6-8c73-f6f29372aca2.jpg)

**Comment by Lunat1q** [comment]
weird bug, looks like it can't remove messages from the server queue.

**Comment by vallaha** [comment]
And app cannot reply my commands from telegram.

**Comment by serdaregemen** [comment]
hi,
i m having the same problem ... any improvement on solution ?
