### ISSUE TITLE
always checking inventory

### ISSUE THREAD

**Issue by mjabelon** [Lunat1q/Catchem-PoGo#849]
Why is the bot always checking inventory? Is my settings wrong?

**Comment by Cryptologism** [comment]
Refer to #812 solution...
Maybe you make a changes in delay in checking the inventory

**Comment by fabntic** [comment]
Yes setting...
A=amount of pokeball + potions + revives +berries 
B=recycle at usage percentage X 350 items in bag. 
A should be << than B
Example 
100+40+20+50=210 A
0,85x350=297 B
The difference is enough B-A= 87 item before next recycling.

**Comment by mjabelon** [comment]
can you specify which delay is that?

**Comment by mjabelon** [comment]
Thank you fabntic! You're very helpful!
