### ISSUE TITLE
Minimize Soft/IP Bans

### ISSUE THREAD

**Issue by jaydee9296** [Lunat1q/Catchem-PoGo#85]
Since this update was released, almost 5-10 minutes it already gave me soft bans for like 30 minutes to 1hour and I've always used VPN in changing IP Addresses... Hope this will be enhanced and fixed.

**Comment by kaiserdj** [comment]
yes is true :+1:

**Comment by Lunat1q** [comment]
ask niantic to stop banning u, what do u expect from me?

**Comment by jaydee9296** [comment]
hahaha it is completely different I think from the last version because it doesn't give me softban while using the bot in 5 minutes :/
