### ISSUE TITLE
What is "Mapzen Valhalla API" ? (building route)

### ISSUE THREAD

**Issue by iSellPizza** [Lunat1q/Catchem-PoGo#852]
When I click on "build the route" it says :"You have to enter Google Direction API or Mapzen Valhalla API to any of your bots, before creating a route."
Can someone explain to me what I have to do to fix this ?

**Comment by xBlade01** [comment]
go to Mapzen Website to generate API kEY

**Comment by impossibrubear** [comment]
I generated, put it there and it keeps asking. Back to v1.4.7.0 :(
