### ISSUE TITLE
[Feature request]Don't transfer favorite pokemon

### ISSUE THREAD

**Issue by xBlade01** [Lunat1q/Catchem-PoGo#854]
hello ,

it's just an idea but if it's possible to add a feature like " don't transfer favourite pokemon" it could be very interesting and useful 

thanks

**Comment by impossibrubear** [comment]
I'd love this feature. But sometimes the settings you selected favorite or unfavorite many pokémons. It would be nice to have something that forbid the unfavorite from manual favorited pokes, i guess.

**Comment by fabntic** [comment]
An idea could be to split into:
1- "Pokemon go" un/favorite pokemon
2- "Catchem" un/favorite pokemon

**Comment by Lunat1q** [comment]
Bot doesn't transfer faviurited pokemons, since... day 1
