### ISSUE TITLE
No stops, just catching pokemon.

### ISSUE THREAD

**Issue by pusislayer** [Lunat1q/Catchem-PoGo#857]
Can i set my bot not to claim any pokestops, but only to wander in search of pokemon? There is a "max pokestops per hour" option, but it pauses the bot rather than allowing him to go without taking any more pokestops.

**Comment by Marcel0002** [comment]
In the settings you found the point "catch wild pokemon"is there a tick?
do you have a tick by "use no catch filter" ?

**Comment by Marcel0002** [comment]
Or you have a softbann try a different account in this case

**Comment by pusislayer** [comment]
I don't think you get the idea. I don't want my character to collect pokestops. I want it just to capture pokemon.

**Comment by Lunat1q** [comment]
added
