### ISSUE TITLE
Help! (Problem) - No proper route loaded

### ISSUE THREAD

**Issue by Santtorinii** [Lunat1q/Catchem-PoGo#862]
Please'm from dawn trying to get the configuration, can not connect with the country outside Brazil ... always gives the same error and I followed to the letter the last tutorial on the site. Please help me. Already grateful. (Obs .: I usually log 5 bills and never gave problem and then this update ta not working or with 1 account).

![errorr](https://cloud.githubusercontent.com/assets/21304887/18058270/98d86376-6de1-11e6-8f27-8bac65b54a6a.jpg)

**Comment by sapdkeybinder** [comment]
same problem on google

**Comment by Santtorinii** [comment]
A tutorial that will help me solve this problem?

**Comment by CKWTHN** [comment]
You have to select Mapzen Valhalla as Routing service in the Bot info Page, and also Sign up to mapzen developer API to obtain the API so the bot can acccess the mapzen map data efficiently.

Good luck

**Comment by necora01** [comment]
unmark Use Custom Route and works!!!!!!!!
