### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by raselan** [Lunat1q/Catchem-PoGo#863]
i cant change the language "EN" to "PT-BR" anyone can help me, im save and close bot but no change

**Comment by Santtorinii** [comment]
Mas você conseguiu deixar o Bot rodando normal? tipo pegando os pokemons e PokerStop? ou é só o Problema da Língua que você tem.?
Porque eu não consigo deixar o Bot rodando...poderia me passar as suas configurações de Navegação pra eu comparar aqui?
