### ISSUE TITLE
Routes Creation Problem Whenever / Bot crashes after save routes

### ISSUE THREAD

**Issue by Marcel0002** [Lunat1q/Catchem-PoGo#864]
Whenever I set the waypoints and click save route crashes of from bot.Please help me

**Comment by Marcel0002** [comment]
Sorry for my bad englisch

**Comment by sapdkeybinder** [comment]
same, restart bot, set a Start and Only way Points. and geht nBuild the route for save

**Comment by Marcel0002** [comment]
dont work :(
