### ISSUE TITLE
problem on the screen

### ISSUE THREAD

**Issue by Raafaax** [Lunat1q/Catchem-PoGo#871]
this my appearing this aki took to print you see what I do

http://prntscr.com/cbrlc8

**Comment by CKWTHN** [comment]
you have to apply in mapzen developer website for an API, it's a code the Bot uses for accessing map data from Mapzen Valhalla, it will be given for free and all you need to do is Copy+Paste it into the bot info page and restart the bot...

**Comment by moontillaa** [comment]
Follow this tutorial: https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen :+1:
