### ISSUE TITLE
Save my setting

### ISSUE THREAD

**Issue by dodo02** [Lunat1q/Catchem-PoGo#872]
Hey,

I'm trying to save a custom way in RouteCreator. But when I try to save more than 2 or 3 way it crashes and all of my setting is missing (just Telegram Setting & RouteCreaor Setting)

I have the same problem when I'm rebooting catchem : I can't save telegram setting & RouteCreator setting...

How Can I fix it?

Thanks for your reply

**Comment by CKWTHN** [comment]
Sounds like a library that the Bot uses might be missing from your computer, and as the bot tries to access it.. it crashes. Make sure you have .net and other common libraries installed on your PC.

Another thing to try is running the app with Administrator rights.. that sometimes helps.
