### ISSUE TITLE
"Auto Favorite Poke" doesn't work

### ISSUE THREAD

**Issue by hermsicodes** [Lunat1q/Catchem-PoGo#876]
I'm using the latest release of Catchem (1.4.9.0) and checked the box "Auto Favorite Poke" with iv > 95%.
But it seems like he won't favorite those pokemon at all. If I force the bot to favorite the pokemon via "Information"-Tab it works like charm.

Does any1 else experience this "bug"? 

Regards,

Hermsi

**Comment by SoniMail** [comment]
Same problem here.

**Comment by xBlade01** [comment]
Same problem too
