### ISSUE TITLE
MobBotRouting API Key is Empty!

### ISSUE THREAD

**Issue by Viking021** [Lunat1q/Catchem-PoGo#882]
MobBotRouting API Key is Empty! what's this? plis help me

**Comment by maxsofar** [comment]
You have to enter API Key to use routing
![2016-08-29](https://cloud.githubusercontent.com/assets/21108932/18063289/045550c2-6e33-11e6-8490-74fe7c5407be.png)

**Comment by SalamanderRX** [comment]
where i found this api key?

**Comment by denes223** [comment]
Same problem here

**Comment by maxsofar** [comment]
https://github.com/Lunat1q/Catchem-PoGo/wiki/Setup-Guide

**Comment by esBrunoL** [comment]
Same here!

**Comment by lucasbrega** [comment]
same here ! how can i get?
