### ISSUE TITLE
Why is this "[15:38:56] (FLEE) (Flee) | Caterpie, Lvl: 4 | CP: (35/235) | IV: 25,87% | Type: Normal | Chance: 78,21% | Dist: 26,92m | Used: PokeBall (72 left) | XP: 0 |"

### ISSUE THREAD

**Issue by AdilsonCSPinto** [Lunat1q/Catchem-PoGo#885]
Hello, why when I start Catchem and he finds the pokemon when more will stick it appears that

[15:38:56] (FLEE) (Flee) | Caterpie, Lvl: 4 | CP: (35/235) | IV: 25.87% | Type: Normal | Chance: 78.21% | Dist: 26,92m | Used: Pokéball (72 left) | XP: 0 |

Can you help me?!

**Comment by SoniMail** [comment]
seems like a softban

**Comment by AdilsonCSPinto** [comment]
With some after a few minutes and tries it back to normal, more whenever he tries to catch the first this happens!

**Comment by maknado** [comment]
Change you IP

**Comment by AdilsonCSPinto** [comment]
My IP?! You want talk my GPS?!
