### ISSUE TITLE
Bug - "Information" panel freeze

### ISSUE THREAD

**Issue by 4ur3l** [Lunat1q/Catchem-PoGo#891]
Hi,

I just just found a weird behaviour, when i favorite (or do any action with right click) a Pokémon the panel is freezed until the action is proceed. Even that new awesome Pokméon infobox did not appear.

Hope it's clear.

Sorry for is my english is a bit poor.

Your work is awesome thank you for all !

**Comment by Lunat1q** [comment]
it's not freeze, it's locking, cause u can't do 2 actions at same time
