### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by pedrazza** [Lunat1q/Catchem-PoGo#893]
The possibility to change the bot name and the move set damage behind (?) their names.
Thank you

**Comment by SoniMail** [comment]
You can change the bot name, go to "Catchem > Profiles" and rename the fold of the bot you wanna rename.
With the bot closed, ofc

**Comment by pedrazza** [comment]
Thank you

**Comment by pedrazza** [comment]
imo showing the dmg of every move is very important, tks
