### ISSUE TITLE
Not spinning pokestops?

### ISSUE THREAD

**Issue by redbone75** [Lunat1q/Catchem-PoGo#894]
Look at the logs for this new version, I see pokemon being caught but there doesn't appear any action on pokestops.  I've watched it for about 10 minutes now where several have been walked past, but they aren't being spun.

Anyone else seeing this?

**Comment by IlDomestico** [comment]
Estrailo nuovamente e vedrai che andrà mi è successa la stessa cosa adesso

**Comment by iAngelG** [comment]
Check your settings if you just updated. There's a checkbox for looting pokestops now

**Comment by RevGDFreeze** [comment]
*facepalm* if you add an option to disable an action don't disable what it use to do by default LOL!, thought i was soft banned hahah

**Comment by petoe93** [comment]
just check your settings after each update, facepalm is on you this time

**Comment by RevGDFreeze** [comment]
I'm well aware of my settings changing after updating LOL!

**Comment by redbone75** [comment]
I see it now.  Thanks.  IMO... this should have been left "checked" and not disabled after an update adding the option. 

Thank you all.
