### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Pokelost** [Lunat1q/Catchem-PoGo#898]
First of all I would like to give a big thanks to all the developers. You guys are doing such a great job. This 1.4.9 update is just amazing.

I would like to ask that you guys consider an option in the tab:
**"Information"** -> **"Inventory"** -> **"Recycle Item"** / **"Refresh list item"** / **_"Use Item"_** to use incense and improve the capture of Pokemons while botting.

And also if possible, I would like to have the amount of necessary candys to evolve the pokemon next to the amount of total candys.

**Comment by Spk345** [comment]
This is one the Road Map for things to be implemented, don't worry, I'm sure Lunatiq will get on this as soon as possible.
