### ISSUE TITLE
Transfer does not work

### ISSUE THREAD

**Issue by talarmin29** [Lunat1q/Catchem-PoGo#900]
<img width="565" alt="2016-08-29" src="https://cloud.githubusercontent.com/assets/21173205/18067668/0da38238-6e3e-11e6-966d-943ff1c2a733.png">

I do not understand why my Pokémon do not transfer.

**Comment by Lukuntz** [comment]
Hi, mine ain't workin either.

**Comment by talarmin29** [comment]
All it's ok now
