### ISSUE TITLE
Egg Hatching Information Tab

### ISSUE THREAD

**Issue by FrancoCJ** [Lunat1q/Catchem-PoGo#904]
I know there is a request to add telegram notifications of egg hatching but I would also like to ask a tab or something in the app to let  us see what eggs we have and what egg is hatching and its status, since the info in the console is almost none

**Comment by CKWTHN** [comment]
Indeed

**Comment by arcavoordo** [comment]
How to use the Route Creator feature?

**Comment by medoamanquer** [comment]
this would help need to show all incubator & (free/used) as status
kind of egg(2/5/10)km & distance left

**Comment by agreda** [comment]
this would be a sweet feature
