### ISSUE TITLE
Ability to activate Incense and Lucky Eggs in game

### ISSUE THREAD

**Issue by CKWTHN** [Lunat1q/Catchem-PoGo#906]
In all recommendations there should be a time between switching from Phone to Bot... and it beats the purpose or risk in wanting to activate a lucky egg in rural areas, if will obviously expire before I can switch back to the bot from my phone.

Please add option in Information Tab to allow "Use" Items.

Good luck

**Comment by Spk345** [comment]
This is on the road map of development.
