### ISSUE TITLE
Auto Level Pokes

### ISSUE THREAD

**Issue by kingjman1994** [Lunat1q/Catchem-PoGo#907]
Still having issues with auto-leveling my pokemon. I'll check the box, save settings, but the setting never saves.
![catchembugs](https://cloud.githubusercontent.com/assets/21153559/18070553/4900504c-6e14-11e6-96ea-72d5b8a3611f.png)

**Comment by Cryptologism** [comment]
Auto leveling... Ermmm never test it before cuz can do it manuaally... Btw did you just check other option... Mybe there was some clash with this auto leveling....??

**Comment by kingjman1994** [comment]
Yeah I actually just found out that I could right click to level them up now in my pokemon lists. This issue can be closed now, thanks! :)
