### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by s4p3p3s4** [Lunat1q/Catchem-PoGo#908]
[20:31:32] (ERROR) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Se produjo una excepción de tipo 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException'.
   en PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() en D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Extensions\HttpClientExtensions.cs:línea 79
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() en D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\BaseRpc.cs:línea 0
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__4.MoveNext() en D:\Catchem-PoGo\PoGoAPI\PoGo.RocketAPI\Rpc\Player.cs:línea 53
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PoGo.PokeMobBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() en D:\Catchem-PoGo\PoGo.PokeMobBot.Logic\State\LoginState.cs:línea 225

[20:31:33] (ERROR) Niantic Servers unstable throttling API Calls.,

**Comment by magicdev2** [comment]
i got i error but i had to update it it

**Comment by Cryptologism** [comment]
There lot thread talking about this error... 
And many reason for it too...
1: Use latest version 
2:Make sure all setting was correct according to the tutorial
3:Make sure you update all kind of graphic or netframe work
4:Perfect Internet connection is needed
5:Restart the bot or pc if needed
6:Chance mybe server pokemon is busy for moment..  Try again later..
7::Make sure you not ipbanned or softbanned or hardbanned or permabanned
