### ISSUE TITLE
can't catch pokemon or use pokestops :(

### ISSUE THREAD

**Issue by Grandpanopants** [Lunat1q/Catchem-PoGo#909]
can someone help me out?, i just got the bot and i setup following a guide but the bot is not catching any pokemon or using any pokestop.. please help, thanks

**Comment by Spk345** [comment]
If you have the new release and you transferred over your profiles, or made a new one, make sure you check your settings to Catch pokemon and Use Pokestops. 

If those are both checked already, you may be temporarily IP Banned. Double check with another device on the same wifi if possible.

**Comment by Cryptologism** [comment]
Yup... I can sure that you already do the correct thing like setting and everything but mybe you do over react like botting more than 1 bot in same ip....
