### ISSUE TITLE
Got this on the new update with APIs, routing and stuffs...

### ISSUE THREAD

**Issue by tenderbeyr** [Lunat1q/Catchem-PoGo#912]
![error](https://cloud.githubusercontent.com/assets/21322662/18071557/50617b8e-6e89-11e6-8ce0-aa8f642c5ad6.png)
got this error from the new updates. (maybe my mistake)
well i think i still have to use v1.4.6.5.. coz some of the old ones have good settings and much easier to use like the mobBot w/o APIkeys.. (using this mobbot w/o api for standby farming)

-hope in the future, there will be a **standby mode that pauses the character or disable the automatic route feat given by the API or routecreator**.
**or** possible combination with a delay or combining routes made by the route creator( like using this route1, after a given time or finishing the route or a chance in midway, itll change to route2..)

update:  got it working again, but ill stick in the old updates... for now...

**Comment by baklaforever** [comment]
same altitude on api is not staying on range from 9-14 i got -3000 to inf

**Comment by tenderbeyr** [comment]
![error a](https://cloud.githubusercontent.com/assets/21322662/18081425/c081f338-6ecc-11e6-9bff-0b918b8d2255.png)
ive manage to make the bot and route i want with the settings above.

![error b](https://cloud.githubusercontent.com/assets/21322662/18081463/f7e9fc58-6ecc-11e6-95e7-e43ef5715587.png)
after a few hours after i botted got this error again when i logged the bot with the same settings..
(the route,red lines, didn't show when the error appeared)
i think that the settings not quite working properly and unstable when used again with the same settings..
so what i did, logout or stop the bot, then tweak the settings a bit (unchecked the custom route) then start.
the bot then move to the given route by the valhalla. while its running, i checked the custom route and sooner the custom route appears, but then got the error again. after that i forgot to stop the bot and it relogged. but this time it still working w/o errors..

**Comment by Lunat1q** [comment]
that's weird... added some check inside logic, should be fine now

**Comment by tenderbeyr** [comment]
oh btw, got a crash..
and update about the error when logging in with the recent custom route sesttings.
it says "No proper route loaded" while the recent settings was still there and work well b4..
this time i didnt get an error with red texts, i just unchecked the custom route and it goes well using the APIs.
then checked it again, still working but i think the bot still not reading it yet about the custom route, or maybe its still pending while the bot still implementing the 1st orders.

**Comment by tenderbeyr** [comment]
oh it crashed again, got a red text errors just like the last picture ive posted, and the custom route loaded..

i think this is because after the bot do the things with the APIs, then before it reads the custom route, itll crash..

hope this helps..
