### ISSUE TITLE
Error.... can somebody help me?

### ISSUE THREAD

**Issue by Grandpanopants** [Lunat1q/Catchem-PoGo#913]
this error it appears when i try go start the god damn bot.... anyone knows how to solve?
![fucking piece of shit](https://cloud.githubusercontent.com/assets/21321828/18072042/2dfcf454-6e31-11e6-8e0f-2f6843ae143f.png)

**Comment by Cryptologism** [comment]
For first problem can be solve just by download latest browser like chrome or mozilla firefox....
The other error solution can be found in my post for this question at this thread click --> #908

**Comment by impossibrubear** [comment]
You can't use the same profiles folder. Configure them again, manually!
