### ISSUE TITLE
Pokemos and Pokestops are gone

### ISSUE THREAD

**Issue by LupaB** [Lunat1q/Catchem-PoGo#915]
I took softban. I changed my IP. I use GoogleDirections. But the game (last release) continues to show problems for me. The character hangs in pokestops, just a few pokestops appear (before were several). Also appear only about 3 Pokemon and then no longer appear. Any suggestions to solve this?

**Comment by Cryptologism** [comment]
Ermmm look like ip banned again...  Well try to change ip again and make sure did not boting more than 1 acc... Also try to find any error i any colour in your cmd of catchem bot...

**Comment by LupaB** [comment]
I changed my IP minutes ago. And no error was reported by the game.

**Comment by izon13** [comment]
Don't use google account.. Sometimes they will block you from using your account when you change IP & Gadget..
