### ISSUE TITLE
Isn't working for hours! Help?

### ISSUE THREAD

**Issue by TheBenEffect** [Lunat1q/Catchem-PoGo#92]
I keep getting this message : 

[20:28:27] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

I've my max distance on 100000000..

Help please :/

**Comment by lainhacker** [comment]
I have the same problem

**Comment by chyle** [comment]
ip ban...

**Comment by Lunat1q** [comment]
Servers are unstable.
