### ISSUE TITLE
Cannot loot in any pokestops

### ISSUE THREAD

**Issue by gambyrocks18** [Lunat1q/Catchem-PoGo#925]
Hello,

I am having trouble getting some loot in poke stops, every time i went in a poke stop no loots found. right now i don't have any pokeball to use.

Please help. 
Thanks!

![image](https://cloud.githubusercontent.com/assets/21325676/18073954/bdbbfd3c-6e9b-11e6-8ccd-cd339ea3714b.png)

**Comment by iron313** [comment]
check the new option about pokestops in last update, or maybe, can be a soft ban

**Comment by tranlehanam1996** [comment]
soft ban sure

**Comment by gambyrocks18** [comment]
How to remove soft ban? do i need logout my account and not use for a day?

**Comment by animekk** [comment]
Not softban. Come to the Discord chat to explain it for you: https://discord.gg/6z5AMX5

**Comment by animekk** [comment]
It's just an option you forgot

**Comment by gambyrocks18** [comment]
I went in https://discord.gg/6z5AMX5 my user is Gambyrocks18

**Comment by animekk** [comment]
I see you... let's chat!

**Comment by OSIRISzzGOD** [comment]
same me

**Comment by animekk** [comment]
Users?

**Comment by OSIRISzzGOD** [comment]
[09:50:25] (ATTENTION) MobBotRouting API Key is Empty!

**Comment by Spk345** [comment]
MobBot is now a pay for Service. Use:
Mapzen API + Valhalla API (Key from Turn-by-Turn)
https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen
Google API
https://github.com/Lunat1q/Catchem-PoGo/wiki/Google-Directions-API

**Comment by flaviooficial** [comment]
it can't be a soft ban because bot is getting pokemons normaly. it must be a bug. Loot Pokestops option is on also
