### ISSUE TITLE
problems with proxy

### ISSUE THREAD

**Issue by iron313** [Lunat1q/Catchem-PoGo#928]
hi guys, i try many proxies and i cant have it working properly, there is soooooo much lag to log, to loading pokestops and to do anything, its basicaly impossivel play... what is this problem?

**Comment by Spk345** [comment]
You do not need proxies to use a bot, as long as you use 1-2 bots on reasonable settings. Free Proxy services end up becoming IP banned very quickly. Try a paid proxy service if you want one. You can always request a new proxy IP if yours gets banned from a paid service.

**Comment by animekk** [comment]
Live Help at
https://discord.gg/6z5AMX5

The Discord Chat for Catchem

**Comment by shinmyu7** [comment]
Lag? it's because you use free proxy, try private proxy and you dont have lag anymore
