### ISSUE TITLE
MobBotRouting API Key is Empty!

### ISSUE THREAD

**Issue by raselan** [Lunat1q/Catchem-PoGo#930]
plz help me

**Comment by Spk345** [comment]
Mapzen API + Valhalla API (Key from Turn-by-Turn)
https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen
Google API
https://github.com/Lunat1q/Catchem-PoGo/wiki/Google-Directions-API

**Comment by Spk345** [comment]
MobBotRouting API is a paid for service now, use either of those.

**Comment by animekk** [comment]
Talking live about that right now on Discord Channel for Catchem
Join us:
https://discord.gg/6z5AMX5

**Comment by OSIRISzzGOD** [comment]
Thx a lot

**Comment by raselan** [comment]
thx so much

**Comment by animekk** [comment]
leave your nicknames on chat so  can welcome you guys..

**Comment by raselan** [comment]
lol my bot cant take pokestops what i can do??

**Comment by Spk345** [comment]
Make sure you choose Loot Pokestop option in settings, especially if you transfered over your profiles. It's not on by default.

**Comment by rgrodrigo** [comment]
Thanks a lot!

**Comment by tmarques8686** [comment]
Qual melhor rota para usar: valhalha api ou google api? How the best?

**Comment by CivicNotorious** [comment]
How I do I choose the route? Click where?

**Comment by CivicNotorious** [comment]
I can not do it walking on the green line , it just walking on red
