### ISSUE TITLE
The bot is good but will be better

### ISSUE THREAD

**Issue by JihWei666** [Lunat1q/Catchem-PoGo#933]
As we all know pokemons are time-limited targets.
Sometimes pokemons appear together but the one we prefer to catch is just counting down.
It will make candy collection more efficient if we can set the priority of chatching pokemons.

**Comment by animekk** [comment]
https://discord.gg/6z5AMX5

**Comment by Spk345** [comment]
Perhaps use the Not To Catch Function if you would like to not capture certain pokemon.
