### ISSUE TITLE
Catchem_v1.4.9.0.7z

### ISSUE THREAD

**Issue by raselan** [Lunat1q/Catchem-PoGo#934]
my bot cant take pokestop in this version

**Comment by iAngelG** [comment]
Check your settings. There's a check box for looting pokestops.

**Comment by OSIRISzzGOD** [comment]
Bot info - catch - Max catch per hour - loot pokestop <<<<< this is

**Comment by animekk** [comment]
Live Help at: https://discord.gg/6z5AMX5

Join us!
