### ISSUE TITLE
Egg hatching

### ISSUE THREAD

**Issue by EnzzoCaaue** [Lunat1q/Catchem-PoGo#936]
I checked all my log files to see if bot hatched any egg and couldnt find any egg hatched. The bot is hatching eggs or nah ? I got 
This is my setting for eggs:
![ss 2016-08-30 at 01 13 19](https://cloud.githubusercontent.com/assets/6455295/18075833/0316cf58-6e4f-11e6-9bac-fa5c364035d2.png)

**Comment by animekk** [comment]
Live Help at: https://discord.gg/6z5AMX5

Join us!
