### ISSUE TITLE
The latest release is crashing

### ISSUE THREAD

**Issue by skzbr** [Lunat1q/Catchem-PoGo#94]
Just this, cannot start the bot, when start, just crash.

Issue 2: The problem with coords and altitude, not solved :(.

**Comment by BrLord** [comment]
It's crashing more then before, and before it was crashing from 30 to 30 seconds

**Comment by skzbr** [comment]
Server off, or another mass ban, watch out guys, happening now!

**Comment by skzbr** [comment]
Or maybe he just spawn me at 0,0,0 again and i`m soft ban!

**Comment by skzbr** [comment]
Yep, my "premium" acount maybe just got soft banned because bot spawn me at 0,0,0.
Used rarely this account for boting and only humanized steps, bla bla bla.

I will hope its temporary ban :)
