### ISSUE TITLE
Bot crash when I send command from telegram

### ISSUE THREAD

**Issue by devost02** [Lunat1q/Catchem-PoGo#940]
The bots just stop working (crash) when i send command to group of bots on telegram. Anyone have ideal why?
and just my opinion, if the bot maker - our hero could make bot recive command by syntax @the_bot_nam command when it has been added to group for easy control multi bots. Thank

**Comment by animekk** [comment]
Live help at:
https://discord.gg/6z5AMX5

Join us!

**Comment by Bay101** [comment]
Could you please send through a screenshot of your telegram config or DM it to me @Bay101 on discord so that I can see what the problem is

**Comment by animekk** [comment]
@Bay101 can you join our channel? Let me know your nick name and I'll make you Administrator....
https://discord.gg/6z5AMX5

We're 197 members now helping each other...

**Comment by devost02** [comment]
@Bay101 thank, but i cant find u on discord, but here is my config
![tele config](https://cloud.githubusercontent.com/assets/21315621/18078458/cfb2d0c8-6eb5-11e6-8fc4-9761f0af8ef1.png)

**Comment by Kerdigue** [comment]
HI, i got the same thing since yesterday !
Btw you're all making a fckin great job, i love you guys !

**Comment by franj62** [comment]
Hi, the bot crash when you put Telegram today.

Nice job, thanks for all your work.
