### ISSUE TITLE
V1.4.9.0 - Catch Wild Poke still catches all pokemon when disabled

### ISSUE THREAD

**Issue by brendoncwright** [Lunat1q/Catchem-PoGo#945]
When "Catch Wild Poke" is checked, bot still catches all the pokemon it seems to come across. 

My interpretation of this option was always that it would stop catching all pokemon and only tap pokestops. Is my understanding of this option incorrect, or is it not functioning properly? 

Found the same issue reported 17 hours ago that was marked solved (https://github.com/Lunat1q/Catchem-PoGo/releases) however that was now a previous release, and my problem still stands. Any advice anyone can offer?

**Comment by Lunat1q** [comment]
Can't be true. just checked, it skipp all pokes
