### ISSUE TITLE
Error when egg hatched. Bug?

### ISSUE THREAD

**Issue by mirdhan123** [Lunat1q/Catchem-PoGo#947]
My bot shows error message "(Error) Niantic Server unstable, throttling API Cals." every time an egg hatched. Is it a bug ?

![error](https://cloud.githubusercontent.com/assets/20819295/18078566/ceb4173c-6ebe-11e6-8efb-4c8d34c0994c.png)

**Comment by Lunat1q** [comment]
every time? are u sure?

**Comment by mirdhan123** [comment]
yes.

**Comment by mirdhan123** [comment]
some people have this issue too
https://github.com/Lunat1q/Catchem-PoGo/issues/943

**Comment by Ch1l1C0nCarnag3** [comment]
Funny. I don't have this issue, but my eggs refuse to hatch until I stop the bot and start it back up. They will just sit there and refuse to tell me what I got, or place a new egg in the incubator. So it looks like there are a few issues related to eggs.

**Comment by CrisOng** [comment]
same here after hached egg it happened always test with different acc different proxy also similiar

**Comment by eady** [comment]
exactly same here.

**Comment by kaktusisko** [comment]
This error is displayed sometimes randomly, too.

**Comment by Lunat1q** [comment]
Did some improvements in EggWalker, shouldn't occur anymore, or even less.
