### ISSUE TITLE
NO MAP

### ISSUE THREAD

**Issue by darklordor** [Lunat1q/Catchem-PoGo#949]
I can't load the map, obviously i have internet conection

![f0c372621bdbe4ed52d8adb5071404f5](https://cloud.githubusercontent.com/assets/20802047/18079697/6e67e178-6e92-11e6-823d-dafff6dc96f1.png)

**Comment by Cryptologism** [comment]
Try to restart the bot or download fresh new version of it and start it again...

Other solution is try to join discord channel here

https://discord.gg/6z5AMX5

**Comment by zellerda** [comment]
Do you have the last version of the application ?
https://github.com/Lunat1q/Catchem-PoGo/releases

**Comment by darklordor** [comment]
i have the last version, aand i have also lunched the app as an administrator

**Comment by darklordor** [comment]
FIXED; I DOWNLOADED THE NEW VERSION BUT STILL USING AN OLD ONE xD, THX
