### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by uldisbiks** [Lunat1q/Catchem-PoGo#952]
Add new state for buttons - pause, when bot is paused, it would be easier to distinguish if bot is paused or stopped from main screen.
Disable bot to connect from main IP if proxy is not available but enabled - this could lead to bans, maybe add checkbox - if proxy enabled do not connect directly.
Also I noticed that many times bot is walking in circle, not sure why. This could be related to some specific geographical place, but it could be also prevented by remembering last let`s say 10 stops and preventing bot to traveling to them again in some period of time.
Add some marker in logs for each bot (bot name?) to be able to separate log records for each bot, or separate log file per bot.

**Comment by kaktusisko** [comment]
Catch Delays should be randomize separately!
It takes much more time than other activities in the game.

**Comment by Lunat1q** [comment]
1. Pause can't be done, there is no pause for the real pogo, if u mean that auto pause routine, well, i'll think about that, but not sure now.
2.  Bot will not connect directly if proxy failed
3. It's just random, nothing special.
4. I'll think about that.
