### ISSUE TITLE
[Suggestion] Start looting pokestops at minimal setting

### ISSUE THREAD

**Issue by MarkoHess** [Lunat1q/Catchem-PoGo#954]
I like the idea to let the bot start looting pokestops at a desired minimal value of items.
e.g.
we already have the amount of pokeballs, potions, etc. in the settings.
Maybe add another setting there that says "start looting pokestops if below a certain percentage of all those items"
So it starts looting pokestops at e.g. 20% of wished item amount and stops once it has reached your wished amount of items. (example: amount of pokeballs set to 100, start to loot at 50%, so the bot uses pokeballs till 50 and then starts to loot again pokestops till pokeballs are at 100 again)
What do you think, is it usefull?

**Comment by MaK-88** [comment]
I already asked for it a few days ago ("Loot Pokestops if Pokeballs below X"), got closed without a comment.

**Comment by MarkoHess** [comment]
Maybe it wasn't detailed enough?

**Comment by MaK-88** [comment]
> MarkoHess commented 4 minutes ago
Maybe it wasn't detailed enough?

It was not detailed, because it is a simple feature xD

**Comment by Bravething** [comment]
u can give question & have answer on discord....
