### ISSUE TITLE
Unavail pokestops

### ISSUE THREAD

**Issue by ALFAru** [Lunat1q/Catchem-PoGo#956]
After running bot for long time (10h+) bot starts only catching pokemons, so i check ingame - when i try to use pokestops it say "try again later", looks like a soft ban, and it takes hours to dissapear, i wonder what causing it, may be bot farms too much xp per hour, or walks too many kms, should i nurf my settings or what?
![pogocatchem](https://cloud.githubusercontent.com/assets/13641969/18083450/80b8aaf2-6ee6-11e6-9666-dcfc50c39de4.jpg)

**Comment by Lunat1q** [comment]
There is server-side limit for pokestops/day

**Comment by ALFAru** [comment]
Спасибо
