### ISSUE TITLE
Pokemon List Freezes Every Time I Evolve 

### ISSUE THREAD

**Issue by g00tch** [Lunat1q/Catchem-PoGo#958]
Every time I evolve a Pokemon, the entire Pokemon list section of the Information tab freezes for about 45 seconds to 1 whole minute. The Inventory still works, as do the other tabs, but I can't scroll through my Pokemon, or click on any others for quite a while. I've had this issue since 1.4.6

**Comment by Lunat1q** [comment]
It's not a "freeze", its lockdown, cause you should be able to do other stuff while evolve in process.

**Comment by g00tch** [comment]
You can still dump inventory during evolves...Just an FYI.
