### ISSUE TITLE
[REQUEST]HumanWalkSnipe

### ISSUE THREAD

**Issue by marvin448** [Lunat1q/Catchem-PoGo#960]
HumanWalkSnipe - Snipe a pokemon and force go to specific area near you and catch it

the safest snipe no teleport just walk until you get the exact area and catch a pokemon

Difference of Snipe
NEW - snipe a pokemon near you just walk until you get it 
OLD - snipe a pokemon in different areas and teleport to get it

**Comment by Lunat1q** [comment]
Pokemon disappear in 15 minutes. That's useless.

**Comment by marvin448** [comment]
its not useless its working at necrobot 9.6 they automatic scan and snipe

**Comment by pokeplayer2** [comment]
Hi,
yes this is one missing feature and it works fine into necrobot:
https://github.com/NoxxDev/NecroBot/wiki/Human-walk-snipe-config
