### ISSUE TITLE
The (INFO) [Inventory] updates too often

### ISSUE THREAD

**Issue by michaelkanrs** [Lunat1q/Catchem-PoGo#964]
It updates every 2 minutes and its getting really annoying. is there a way to reduce the rate?

**Comment by fabntic** [comment]
Yes setting...
A=amount of pokeball + potions + revives +berries 
B=recycle at usage percentage X 350 items in bag. 
A should be << than B
Example 
100+40+20+50=210 A
0,85x350=297 B
The difference is enough B-A= 87 item before next recycling.
Refer to #812 solution...
Maybe you make a changes in delay in checking the inventory

**Comment by michaelkanrs** [comment]
Is there a way to have to bot stay on roads?
