### ISSUE TITLE
Keep checking inventory but din't transfer any.

### ISSUE THREAD

**Issue by cheessyong** [Lunat1q/Catchem-PoGo#966]
v.1.4.9.0:
I'm using custom route on several bot and some are not, but they're all having the same problems.
Characters keep checking the inventory and did not transfer any when its full or overload.(double checked item setting total amount below 350, recycle at usage percentage 0.85)
They keep checking the inventory makes them become very slow to loot pokestops, then always out of pokeballs.(especially Greatball *Greatball catch probability setting 0.23)
Now they can't even reach 8-9k xp/h, bots nonstop farming over 8hours.(easy to reach 11k+ xp/h and keep pause every 1~2hours at the same location)

**Comment by lonelies** [comment]
I don't have any problem with mine. Well i only keep those with high CP. So, yeah. This is how my setting look like.

<a href="http://imgur.com/IrT4eTR"><img src="http://i.imgur.com/IrT4eTR.png" title="source: imgur.com" /></a>

**Comment by Lunat1q** [comment]
added some extra logic into inventory maintaining during custom route.
