### ISSUE TITLE
Further enhancement on Pokemon data

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#968]
Hi admins!

The latest release was superb with the new poke data which is displayed when you hover your mouse to the pokemons!

I have an idea where when we hover to the pokemon, we're also able to see the possible evolution CP(if the pokemon able to be evolve) just like when you're using the app "calculato for pokemon go" or anything like that.

Cheers!

Example (sorry poor editor :p ) :
<a href="http://imgur.com/9Vntbf5"><img src="http://i.imgur.com/9Vntbf5.png" title="source: imgur.com" /></a>

**Comment by Lunat1q** [comment]
424 is the maxcp number.

**Comment by Lunat1q** [comment]
about the rest - i'll think about it.

**Comment by lonelies** [comment]
got the data from "calculator for Pokemon go" apps from google playstore. not sure if it is correct or not

<a href="http://imgur.com/1xqCHJp"><img src="http://i.imgur.com/1xqCHJp.jpg" title="source: imgur.com" /></a>

**Comment by JinxGenius** [comment]
hey boss, one minor suggestion, Candy: xx/zz <--- where zz is the evolving requiring candy amount

**Comment by Lunat1q** [comment]
i did candy xx/zz yesterday already.

**Comment by JinxGenius** [comment]
Yes, I saw that, thanks alot!
