### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#969]
in Settings: add space between BerriesTo
in Settings: make it "Delay Recycle Item"
there is a msg on the console where 'stopped' is spelled 'stoped'

**Comment by Lunat1q** [comment]
fixed, thanks!

**Comment by Cowering** [comment]
in information tab, it should be '(Un)Favorite' not '(Un)Favourite' ... unless maybe you are a brit :)
