### ISSUE TITLE
 I do to evolve only Pokemon that are on the list! Pidgey Ratata Caterpie Weedle

### ISSUE THREAD

**Issue by maknado** [Lunat1q/Catchem-PoGo#972]
How i do to evolve only Pokemon that are on the list for independent evolution of iv and cp?

Help.....

**Comment by maimirai** [comment]
yea, we need this

**Comment by maknado** [comment]
I found a way!
Uncheck:
Evolve All Poke Above Iv

AND
check the option:
Evolve All Poke With Enough Candy


Coleque in Listing Pokemon: Pidgey, Caterpie, Weedle, Ratata!

Save Settings!
Stop and Start Bot again!


Enjoy :-D
