### ISSUE TITLE
[BUG] New release crashes after a random time.

### ISSUE THREAD

**Issue by kaktusisko** [Lunat1q/Catchem-PoGo#974]
New release crashes after a random time. (about half an hour)
Any ideas?

**Comment by jerryang76** [comment]
mine, too. I used telegram. Maybe that caused it.
It's using more cpu power in this version.

**Comment by nandotech** [comment]
I have experienced crashes/freezes--however not nearly to the scale these guys are saying.

I ran 2 bots on 2 separate computers all night long last night and in the morning both apps crashed on me (little over 10 hours up).

Also, I think I have narrowed it down to when I attempt to manually transfer and/or evolve a large number of Pokemon but at the same time a pokemon spawns nearby and the character attempts to enter into a fight.

See attached screenshot for console messages I begin receiving.  _Also_, in the case below I simply waited it out and the bot did seem to recover itself.

**Earlier** this morning, I did get actual Windows crashes from catchem.exe itself.

![image](https://cloud.githubusercontent.com/assets/2347606/18090652/bb111cb4-6e93-11e6-80aa-487345781d0b.png)

**Comment by JeanRolszt** [comment]
I have a lot of crashes to, i have W10

**Comment by kemdark** [comment]
Win 7 and win server 2008 r2.  Catchem_v1.4.9.0.7z crash

**Comment by kaktusisko** [comment]
Windows Server 2008/2012 too.

**Comment by kaktusisko** [comment]
Maybe it's becouse 64-bit system.

**Comment by animekk** [comment]
Live help at:
https://discord.gg/s4PyT

=)

**Comment by kemdark** [comment]
New Version Catchem_1.4.9.1.7z, I'm testing

**Comment by kaktusisko** [comment]
@Lunat1q This release is running without any errors. First time ever. Good job! Thanks!

**Comment by kaktusisko** [comment]
@Lunat1q Unfortunately, even without any errors in console - crashed again with Windows error.

**Comment by Lunat1q** [comment]
take a look at windows journal, may be there is an error

**Comment by kemdark** [comment]
Spanish log:

`Nombre de la aplicación con errores: Catchem.exe, versión: 1.4.9.0, marca de tiempo: 0x57c4871a
Nombre del módulo con errores: KERNELBASE.dll, versión: 6.1.7601.23418, marca de tiempo: 0x5708a7e4
Código de excepción: 0xe0434352
Desplazamiento de errores: 0x0000c54f
Id. del proceso con errores: 0x1510
Hora de inicio de la aplicación con errores: 0x01d20262ca708a1e
Ruta de acceso de la aplicación con errores: C:\Users\Debo\Desktop\Catchem\Catchem.exe
Ruta de acceso del módulo con errores: C:\Windows\syswow64\KERNELBASE.dll
Id. del informe: c6f7b38e-6e96-11e6-bcec-001c1060c0ec`

**Comment by kemdark** [comment]
Spanish log from Windows server 2008 R2 x64

> Nombre de la aplicación con errores: Catchem.exe, versión: 1.4.9.0, marca de tiempo: 0x57c4871a
> Nombre del módulo con errores: KERNELBASE.dll, versión: 6.1.7601.18409, marca de tiempo: 0x53159a86
> Código de excepción: 0xe0434352
> Desplazamiento de errores: 0x0000c42d
> Id. del proceso con errores: 0x4dd8
> Hora de inicio de la aplicación con errores: 0x01d202ba47c1b505
> Ruta de acceso de la aplicación con errores: C:\Catchem 29-08-16\Catchem.exe
> Ruta de acceso del módulo con errores: C:\Windows\syswow64\KERNELBASE.dll
> Id. del informe: d108ce30-6eb4-11e6-a5fe-9cb65401ab12

**Comment by wagas** [comment]
it crashes on checking in the inventory

**Comment by kaktusisko** [comment]
No cause in windows journal.
The program stops and is automatically turned off by windows becouse no response.

**Comment by Cryptologism** [comment]
Just happen to me a few second ago... Using Window 8.1 64 bit... i think maybe overload or conflict with telegram...

**Comment by devgraal** [comment]
I am using last release, without telegram, and no crash, no freeze (Win7-EN-64b)

**Comment by kemdark** [comment]
Testing Catchem_v1.4.9.1.7z with telegram all reports.

**Comment by kaktusisko** [comment]
V1.4.8.1 works best for me!
3hours and counting...

**Comment by devost02** [comment]
The bots crash when it check inventory (not always)

**Comment by kaktusisko** [comment]
![crash](https://cloud.githubusercontent.com/assets/21192128/18129639/e07b6ca4-6f8b-11e6-9a43-8ad1d0f07225.png)
