### ISSUE TITLE
more typos

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#975]
oops, didn't notice you closed the last one..
in information tab it should be '(Un)Favorite' not '(Un)Favourite' (unless maybe the brits spell it that way)

**Comment by Lunat1q** [comment]
it's spelled "Favourite", and it's the right way to spell it.

**Comment by Cowering** [comment]
do you read comments after closing? my .33 USA client app shows it as 'favorite'. Also, 'preffer' should be 'preferred' in 'always preffer long distance egg'
