### ISSUE TITLE
REALLY act like a stupid human

### ISSUE THREAD

**Issue by Cowering** [Lunat1q/Catchem-PoGo#978]
Sometimes, when not wearing my eyeglasses, i try to evolve or level up a PM without enough candy. Maybe the bot can do that every hour or so to look more like a real human.

Also, is the API called when you do things like swipe from pokemon list to egg list; does it record the direction, speed and distance of a pokestop swipe? If so those could be randomized. (I'm doing this strictly blackbox for now, I'm not looking at your code)

**Comment by magicdev2** [comment]
.....

**Comment by magicdev2** [comment]
just no just no.....

**Comment by Cowering** [comment]
Hey, think Turing Test for PMG!
