### ISSUE TITLE
uhmm.

### ISSUE THREAD

**Issue by PokegoNL** [Lunat1q/Catchem-PoGo#982]
Just downloaded it and extracted but i dont see the launch icon anywhere?

**Comment by animekk** [comment]
Live help at:
https://discord.gg/s4PyT

=)

**Comment by fabntic** [comment]
Try ti click on: 
Pulse
Somewhere there's "published" (green): click on the last version. 
Then at the bottom just download this 
Catchem_vx.x.x.x.7z
