### ISSUE TITLE
PowerUp a Pokemon = Set the original english name

### ISSUE THREAD

**Issue by Asia81** [Lunat1q/Catchem-PoGo#984]
I use the french translation for the cmd, names, etc...
But when I PowerUp a pokemon, it take the orignale english name.

Look:
http://image.noelshack.com/fichiers/2016/35/1472567592-originalenglishnames.png

**Comment by Lunat1q** [comment]
ah... let me see :)

**Comment by Lunat1q** [comment]
fixed
