### ISSUE TITLE
Improvement for pokemon hunting

### ISSUE THREAD

**Issue by geronimoolivera** [Lunat1q/Catchem-PoGo#985]
Is possible to add the option to visit pokestops when the player have like 20 pokeballs? Because at the moment when the location have much pokestops the bot stop every 20 min (because reach the total pokestop by hour).

Thanks for the great bot!

**Comment by Bravething** [comment]
@geronimoolivera 
what are ur version...
its allready have option to visit pokestop...
if u run out the balls, that always have automatic to reach the nearby pokestop first before catch....
try check ur delay pokestop is high or low value u fill in (in milisecond)...
try check ur random min & max delay to...
on me while i set (example) 50 pokestop, thats still pass away that pokestop limit coz i set an xp & stardust limit to...

can u join & ask to discord??

**Comment by SweeTIPi** [comment]
An option that you can choose in: only visit pokestop or only catch pkm; that would be nice.

**Comment by Bravething** [comment]
@SweeTIPi 
it's allready added...
if u want ask or make suggestion more... join in our discord...
u can ask there untill u cant breath....hehehe... :)

**Comment by SweeTIPi** [comment]
@Bravething on latest version? Im with problem to start it(crash). ): waiting for a solution
