### ISSUE TITLE
Suggestion Telegram Bot

### ISSUE THREAD

**Issue by leozinxd** [Lunat1q/Catchem-PoGo#986]
It would be quite interesting if you could send the location of pokemon via telegram bot or even a print where he was seen, thus being able to use the bot as a radar.
ps. sorry "my" English, was the google translate!

**Comment by Lunat1q** [comment]
useless. sorry

**Comment by leozinxd** [comment]
Some people use the bot, but has an account "clean" and use the button in the locality who live and can get the poke with two accounts, knowing the location would help a lot, would be an alternative, very effective, the pokémesh since the scanning is automatic and the new option of personalisadas routes became much more viable.

**Comment by leozinxd** [comment]
Add at least to send the coordinates, it is easy to obtain information! Please! kkkk

**Comment by leozinxd** [comment]
add "lat" "lng" in line 194 and line 201 in telegrampage.xaml.cs
```
private void PokemonCaught(PokemonId pokemon, int cp, double iv, string profileName, string botNick,
            double level, PokemonMove? move1, PokemonMove? move2)
        {
            if ((!_tlgrmSettings.AutoReportSelectedPokemon || !_tlgrmSettings.AutoReportPokemon.Contains(pokemon)) &&
                (cp <= _tlgrmSettings.ReportAllPokemonsAboveCp || _tlgrmSettings.ReportAllPokemonsAboveCp <= 0))
                return;
            string messageToSend =
                $"[{botNick}]({profileName}) got {pokemon}! CP:{cp}, Iv:{iv.ToN1()}, Level:{level.ToN1()}, Move 1: {move1}, Move 2: {move2}";
            foreach (var owner in _tlgrmSettings.Owners.Where(x => x.ChatId != 0))
            {
                TlgrmBot.SendToTelegram(messageToSend, owner.ChatId);
            }
        }
```
add variable "lat" e "lng" in TelegramPokemonCaughtEvent.cs who believe that can be obtained from NewMapObject.cs

Please add it!
I will now make a donation to you regardless, because I liked much of his work, but if you add this function will make another donation in return the request of any required shape!
ps. I hope you do not misunderstand me as donations.
