### ISSUE TITLE
Admin Closed Eveything

### ISSUE THREAD

**Issue by animek03** [Lunat1q/Catchem-PoGo#990]
You help this people: you get banned.
246 people in Discord channel trying to help each other: you get banned.
You solve issues: you get banned.
You help with downloads: get banned..

Are you serious Lunat1q? What's wrong with you?

**Comment by Lunat1q** [comment]
Are you insane?
THERE IS OFFICIAL DISCORD SERVER FOR THE BOT. 
But you continue to advertise your server. 
Banned again.

**Comment by kingkai808** [comment]
@Lunat1q  hey sorry if i asked already but is there a snipe implement in the app? i see the option for sniping delay but i don't actually see a snipe option or how it works? sorry for bugging ya. working great so far man thanks!

**Comment by Lunat1q** [comment]
Sniping will not be implemented, said menu times.

**Comment by kingkai808** [comment]
Sorry didn't see my bad man!
