### ISSUE TITLE
minor bug v1.4.9.1

### ISSUE THREAD

**Issue by lonelies** [Lunat1q/Catchem-PoGo#991]
greetings. 

just wanna report that setting the newly made "Report any above iv" if set to zero, it doesn't disable the feature. It actually will report every pokemons that are caught. well all pokemon's ivs are above 0

**Comment by Lunat1q** [comment]
Weird, should check that

**Comment by Lunat1q** [comment]
Found:) will fix it soon

**Comment by lonelies** [comment]
keep up the great work! :+1:

**Comment by Lunat1q** [comment]
fixed, will reupload 1.4.9.1 into releases.
