### ISSUE TITLE
Run 2 Bots, but both must be same location for manual route to work

### ISSUE THREAD

**Issue by piratedking** [Lunat1q/Catchem-PoGo#993]
I tried to create 2x manual routes at different area, so that I can run 2x bots at 2 different locations, but the second bot not able to run & keep getting error message saying something like "not able to load route".

**Comment by lonelies** [comment]
i just tried but im not using manual routes tho. works fine

**Comment by delunatix** [comment]
this is a bug on manual routing dono if fixed on the latest 1.4.9.1 but if not you should manually click on the saved route, build it again then save it under a different filename. Then load it again on custom route under settings. Save it then start bot it should work fine by then. Hope this helps.

**Comment by Lunat1q** [comment]
just tested - works just fine, 2 different bots, 2 different routes.
