### ISSUE TITLE
Please make the  transfer more effective

### ISSUE THREAD

**Issue by MaloneFreak** [Lunat1q/Catchem-PoGo#998]
When i put to transfer , the Pokemon with CP 10,20 ,100 they are not transferred  and keep the message your  Pokemon inventory is full, transferring Pokemon. thanks for your hard work bro , sorry for my English i'm Brazilian

**Comment by lonelies** [comment]
did you set the iv aswell?

**Comment by MaloneFreak** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/21204817/18097377/f6258be4-6eb3-11e6-98cb-cc65e3af988b.jpg)

**Comment by lonelies** [comment]
I think your inventory is full because your "Keep Min CP" is too low which is only 450. at level23, u can easily get pokes that have higher CP than 450. try to set it higher, i set mine 1000 or 1250

**Comment by MaloneFreak** [comment]
Okay Thanks for the Attention  i've  put this value so low because  one time the bot transfered my arcanine CP 1780 hahahahhahaa  i was very angry.

**Comment by lonelies** [comment]
hahaha sorry to hear that

**Comment by maknado** [comment]
i too!
Mym Pinsir of 1330 just capture.

**Comment by alanearl** [comment]
Because Pokemon's should be base on Individual Values not on Combat Power :) 
Combat Power can be easily achieved by Stardust & Candy anyway.
